### ISSUE TITLE
FYI: 444222 window.name

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1012]
[444222](https://bugzilla.mozilla.org/show_bug.cgi?id=444222) windows.name

**Comment by Thorin-Oakenpants** [comment]
and it's landed

**Comment by earthlng** [comment]
pref: `privacy.window.name.update.enabled`

**Comment by Thorin-Oakenpants** [comment]
source: [hacks.mozilla.org](https://hacks.mozilla.org/2020/10/coming-through-with-firefox-82/)
> This [`Window.name`](https://developer.mozilla.org/docs/Web/API/Window/name) property is used to get or set the name of the window’s current browsing context — this is used primarily for setting targets for hyperlinks and forms. Previously one issue was that, when a page from a different domain was loaded into the same tab, it could access any information stored in `Window.name`, which could create a security problem if that information was sensitive.
> 
> To close this hole, Firefox 82 and other modern browsers will reset `Window.name` to an empty string if a tab loads a page from a different domain, and restore the name if the original page is reloaded (e.g. by selecting the “back” button).
> 
> This could potentially surface some issues — historically `Window.name` has also been used in some frameworks for providing cross-domain messaging (e.g. SessionVars and Dojo’s dojox.io.windowName) as a more secure alternative to JSONP. This is not the intended purpose of `Window.name`, however, and there are safer/better ways of sharing information between windows, such as [`Window.postMessage()`](https://developer.mozilla.org/docs/Web/API/Window/postMessage).

**Comment by Thorin-Oakenpants** [comment]
A script with the one google+recaptcha exception is super tight. I need to read the ticket again, but this looks like it's sufficient. How do they handle the recapture then? What does "domain" mean? does loading `secret2.example.com` from `secret2.example.com` clear the window.name?

Needs answers

**Comment by earthlng** [comment]
yes, this new feature is only enabled when the pref is set to `true`

**Comment by Thorin-Oakenpants** [comment]
^^ thanks. Now that I've had a sleep .. of course.. stupid blog post put me off

the other questions remain standing, also better check for any regressions and blockers and stuff

**Comment by Maryse47** [comment]
@Thorin-Oakenpants hi, with `privacy.window.name.update.enabled` set to `true` on ff 85 the [Tab name](https://ip-check.info) test still shows _"window.name" is traceable_ while it shows _"window.name" has been anonymized_ when using canvasblocker ext. Is this a false positive or does using canvas blocker window protection api still makes sense?

**Comment by Thorin-Oakenpants** [comment]
because that test is setting a name AFAICT. What [firefox does](https://hacks.mozilla.org/2020/10/coming-through-with-firefox-82/) is simply clear it when you change eTLD+1 (and restores it when you navigate through your history)

**Comment by Thorin-Oakenpants** [comment]
here you go [Link A](https://arkenfox.github.io/TZP/tests/windownamea.html), which has a link to Link B

What each page does is check if a `window.name` value is present when it loads, then it sets a new one and checks it has been set. You can click rerun as many times as you like. As long a you get success that the page set a `window.name` value, then you're good to continue
- step 1: note the current value, note the new value, click the link to the other test
- step 2: repeat step 1

if you do this with `privacy.window.name.update.enabled` = true, the change in eTLD+1 means it is cleared
if you do this with `privacy.window.name.update.enabled` = false, nothing is cleared

enjoy
