### ISSUE TITLE
CONTRIB: user.js version checker/notifier script (linux)

### ISSUE THREAD

**Issue by atomGit** [arkenfox/user.js#1015]
this bash script simply checks for an updated user.js and displays a desktop notification - the intension is to add it to the startup programs so it runs automatically - instructions are in the script

[user.js-version-checker.sh - codeberg.org](https://codeberg.org/12bytes.org/Firefox-user.js-supplement/src/branch/master/misc)

**Comment by Thorin-Oakenpants** [comment]
line 76 will be fucked soon

**Comment by atomGit** [comment]
yaup - knew that - was just waitin till things solidify

**Comment by atomGit** [comment]
mr. @Thorin-Oakenpants - i didn't expect you to keep this issue open - you could add a link in the wiki if you want, or not - doesn't matter to me - either way you can close this
