### ISSUE TITLE
Does user.js work with thunderbird 78?

### ISSUE THREAD

**Issue by Janaue** [arkenfox/user.js#1017]
My thunderbird 68 just got updated to 78 and it looks a lot like firefox quantum now. Can I use your user.js too with thunderbird  78 ?

after the update, I get a tab opening this page https://www.mozilla.org/en-US/privacy/thunderbird/
about what they do with the personal data.

regards

**Comment by Thorin-Oakenpants** [comment]
try asking at https://github.com/HorlogeSkynet/thunderbird-user.js

**Comment by B00ze64** [comment]
It works fine, I use it myself and just remove a few sections that are not relevant. You might want to disable Resist Fingerprinting, on TB60 for me it make TB open full-screen all the time,,,
