### ISSUE TITLE
4YI: Kind of a vulnr in Firefox for Android (old versions, Fennec-based).

### ISSUE THREAD

**Issue by KOLANICH** [arkenfox/user.js#1019]
https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/red-team-tech-notes/-/tree/master/firefox-android-2020
https://initblog.com/2020/firefox-android/

Mitigation: `browser.casting.enabled`

**Comment by Thorin-Oakenpants** [comment]
> The SSDP engine in Firefox for Android (68.11.0 and below) can be tricked 

They migrated and locked mobile users to ESR68 while they built Fenix (and it's a small team). The roadmap meant they had to have it done and push Fenix out before the EOL of 68. They finished that staged rollout recently - maybe 2 weeks ago from memory (there was a blog post about it - maybe I saw it on planet mozilla)

- https://old.reddit.com/r/firefox/comments/ivj3sg/firefox_bug_lets_you_hijack_nearby_mobile/
- https://www.zdnet.com/article/firefox-bug-lets-you-hijack-nearby-mobile-browsers-via-wifi/ <-- clickbaity title

Thanks for the info, but this doesn't affect anyone (people who don't update their software get no passes from me)
