### ISSUE TITLE
Firefox Autoplay Policy Documentation

### ISSUE THREAD

**Issue by losuler** [arkenfox/user.js#1022]
In an effort to understand the new `media.autoplay.blocking_policy` preference, I found this https://drive.google.com/file/d/1Lkk37Vq8YhURxPL7UBVy0CuuZJU62PYQ/view that was linked from https://support.mozilla.org/en-US/questions/1293231.

It made a lot more sense to me than the already linked spec page, so I thought it might be helpful if it was added as well.

**Comment by earthlng** [comment]
Hi,

thanks for your comment and sorry for the late reply.

Damn, why do they have to put their stuff up on google?!! I really don't want to link to anything on google.

We could put a copy of that pdf in one of our subfolders and link to that instead. But pdf files aren't the most trustworthy file types and it could look shady. Not sure if it's worth it either. @Thorin-Oakenpants waddaya think?

**Comment by atomGit** [comment]
put it on archive.org - or i can if you don't have an account

**Comment by Thorin-Oakenpants** [comment]
Sorry for the late reply as well. I did have a very super quick look 10 days ago, but it didn't register with me that it was a PDF.

Same as earthlng: I don't like the google link. I'm semi-OK with linking to a PDF, as long as we label them as such with a `[PDF]` notation - but I'd rather try to avoid them. Absolutely do not want to host anything. The thing with references is they add legitimacy - so a link to a bugzilla is a reputable source, etc ... the LINK matters. A google drive link has no authentication. A self hosted link doesn't hold any authentication either.

At best, I think we could link to the SUMO and state the SUMO has a link to a 5 page PDF on google drive - over to earthlng for his thoughts

**Comment by Thorin-Oakenpants** [comment]
^ bump

**Comment by earthlng** [comment]
adding a link to this issue is probably the easiest and best solution since we definitely don't want to link to google

**Comment by Thorin-Oakenpants** [comment]
Hrmmm .. I don't like linking back to ourselves if we can help it. It *seems* self-serving. Anyway, I see no advantage in linking to here over SUMO and the user then gets to the PDF
