### ISSUE TITLE
windows users, RFP, and fonts: help required: TIA

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1029]
Hey guys ... earthlng and myself would like some data

For anyone running Windows (any version), we would like to know what fonts vary with RFP, and to do that we would appreciate some results from this test: https://arkenfox.github.io/TZP/tzp.html#fonts
- **you need to be running FF81 or higher**: release, dev, beta, nightly are all good. ESR is no good to us.
- **RFP must be on, documents fonts must be allowed, and no font whitelisting** [1]
- no need to change any settings for downloadable fonts

What we're after, is the `fonts` hash and it's associated font list under `view fonts`. We're not interested in the fallback font, just the test that autoruns
 - In the next post, I'm going to keep a record of the hashes and lists. If your result is already known, just let us know (or not). If it's a hash/list **we haven't listed yet, then please tell us:**
   - the hash (and counts can be handy) and the list
   - that's it
   - super easy
   - see the pic [2]

💋 🤗 🍻  TIA

[1] you can set/check these before loading the test and you shouldn't need to restart
```js
// document fonts
user_pref("browser.display.use_document_fonts", 0); // <-- user.js is currently setting it to 1

// whitelist: IF using it, reset it or blank it (don't forget to remember what you had in it)
// it's a HIDDEN PREF, if you don't see it, that's good
user_pref("font.system.whitelist", ""); // <-- user.js currently has it inactive / commented out

// RFP
user_pref("privacy.resistFingerprinting", true); // <-- currently true in user.js
```

[2] Note the matching hash (in case you run the `click here` test and it's different
 - copy the hash (+ counts if you can) and paste it to us, hit the `copy to clipboard` and paste it to us
 - you'll feel awesome, thanks
![eh](https://user-images.githubusercontent.com/16656956/95117223-bd922780-0737-11eb-9c5e-9ea7cdba15ce.png)

**Comment by Thorin-Oakenpants** [comment]
reserved

**Comment by crssi** [comment]
**2c92feabe2ce9ca1e146ca05f2f6c7cee7461b2d** [102/486]

```
Arial,  Arial Black, Arial Narrow, Bahnschrift, Calibri, Calibri Light,  Cambria, Cambria Math, Candara, Candara Light, Comic Sans MS, Consolas,  Constantia, Corbel, Corbel Light, Courier, Courier New, Ebrima,  Gabriola, Gadugi, Georgia, Helvetica, HoloLens MDL2 Assets, Impact,  Javanese Text, Leelawadee UI, Leelawadee UI Semilight, Lucida Console,  Lucida Sans Unicode, Malgun Gothic, Malgun Gothic Semilight, Marlett,  Microsoft Himalaya, Microsoft JhengHei, Microsoft JhengHei UI, Microsoft  JhengHei UI Light, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft  Sans Serif, Microsoft Tai Le, Microsoft YaHei, Microsoft YaHei Light,  Microsoft YaHei UI, Microsoft YaHei UI Light, Microsoft Yi Baiti,  MingLiU_HKSCS-ExtB, MingLiU-ExtB, Mongolian Baiti, MS Gothic, MS  PGothic, ＭＳ Ｐゴシック, MS Sans Serif, MS Serif, MS UI Gothic, ＭＳ ゴシック, MV  Boli, Myanmar Text, Nirmala UI, Nirmala UI Semilight, NSimSun, Palatino  Linotype, PMingLiU-ExtB, Roman, Segoe MDL2 Assets, Segoe Print, Segoe  Script, Segoe UI, Segoe UI Black, Segoe UI Emoji, Segoe UI Historic,  Segoe UI Light, Segoe UI Semibold, Segoe UI Semilight, Segoe UI Symbol,  SimSun, SimSun-ExtB, Sitka Banner, Sitka Display, Sitka Heading, Sitka  Small, Sitka Subheading, Sitka Text, Small Fonts, Sylfaen, Symbol,  Tahoma, Times, Times New Roman, Trebuchet MS, Twemoji Mozilla, Verdana,  Webdings, Wingdings, Yu Gothic, Yu Gothic Light, Yu Gothic Medium, Yu  Gothic UI, Yu Gothic UI Light, Yu Gothic UI Semibold, Yu Gothic UI  Semilight, 宋体, 微软雅黑
```

**Comment by PinkieSwirl** [comment]
556cf47261f011f1f40238bd9cff53aa2004c84a [101/486]

```
Arial,  Arial Black, Arial Narrow, Bahnschrift, Calibri, Calibri Light,  Cambria, Cambria Math, Candara, Candara Light, Comic Sans MS, Consolas,  Constantia, Corbel, Corbel Light, Courier, Courier New, Ebrima,  Gabriola, Gadugi, Georgia, Helvetica, Impact, Javanese Text, Leelawadee  UI, Leelawadee UI Semilight, Lucida Console, Lucida Sans Unicode, Malgun  Gothic, Malgun Gothic Semilight, Marlett, Microsoft Himalaya, Microsoft  JhengHei, Microsoft JhengHei UI, Microsoft JhengHei UI Light, Microsoft  New Tai Lue, Microsoft PhagsPa, Microsoft Sans Serif, Microsoft Tai Le,  Microsoft YaHei, Microsoft YaHei Light, Microsoft YaHei UI, Microsoft  YaHei UI Light, Microsoft Yi Baiti, MingLiU_HKSCS-ExtB, MingLiU-ExtB,  Mongolian Baiti, MS Gothic, MS PGothic, ＭＳ Ｐゴシック, MS Sans Serif, MS  Serif, MS UI Gothic, ＭＳ ゴシック, MV Boli, Myanmar Text, Nirmala UI, Nirmala  UI Semilight, NSimSun, Palatino Linotype, PMingLiU-ExtB, Roman, Segoe  MDL2 Assets, Segoe Print, Segoe Script, Segoe UI, Segoe UI Black, Segoe  UI Emoji, Segoe UI Historic, Segoe UI Light, Segoe UI Semibold, Segoe UI  Semilight, Segoe UI Symbol, SimSun, SimSun-ExtB, Sitka Banner, Sitka  Display, Sitka Heading, Sitka Small, Sitka Subheading, Sitka Text, Small  Fonts, Sylfaen, Symbol, Tahoma, Times, Times New Roman, Trebuchet MS,  Twemoji Mozilla, Verdana, Webdings, Wingdings, Yu Gothic, Yu Gothic  Light, Yu Gothic Medium, Yu Gothic UI, Yu Gothic UI Light, Yu Gothic UI  Semibold, Yu Gothic UI Semilight, 宋体, 微软雅黑
```

FF 81.0.1, Win10

**Comment by stan1408** [comment]
2bd40476fd5d49e0f6361545182d8412074d2b56 [67/486]

`Arial, Arial Black, Calibri, Calibri Light, Calibri Light Italic, Cambria, Cambria Math, Candara, Comic Sans MS, Consolas, Constantia, Corbel, Courier, Courier New, Ebrima, Gabriola, Georgia, Helvetica, Impact, Lucida Console, Lucida Sans Unicode, Malgun Gothic, Marlett, Microsoft Himalaya, Microsoft JhengHei, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Sans Serif, Microsoft Tai Le, Microsoft YaHei, Microsoft Yi Baiti, MingLiU_HKSCS-ExtB, MingLiU-ExtB, Mongolian Baiti, MS Gothic, MS PGothic, ＭＳ Ｐゴシック, MS Sans Serif, MS Serif, MS UI Gothic, ＭＳ ゴシック, MV Boli, NSimSun, Palatino Linotype, PMingLiU-ExtB, Roman, Segoe Print, Segoe Script, Segoe UI, Segoe UI Light, Segoe UI Semibold, Segoe UI Symbol, SimSun, SimSun-ExtB, Small Fonts, Sylfaen, Symbol, Tahoma, Times, Times New Roman, Trebuchet MS, Twemoji Mozilla, Verdana, Webdings, Wingdings, 宋体, 微软雅黑`

FF 81.0.1, Win7

**Comment by earthlng** [comment]
13afc3f72ea2582c317d9726876d44575b3db164 [65/486]

```
Arial, Arial Black, Calibri, Cambria, Cambria Math, Candara, Comic Sans MS, Consolas, Constantia, Corbel, Courier, Courier New, Ebrima, Gabriola, Georgia, Helvetica, Impact, Lucida Console, Lucida Sans Unicode, Malgun Gothic, Marlett, Microsoft Himalaya, Microsoft JhengHei, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Sans Serif, Microsoft Tai Le, Microsoft YaHei, Microsoft Yi Baiti, MingLiU_HKSCS-ExtB, MingLiU-ExtB, Mongolian Baiti, MS Gothic, MS PGothic, ＭＳ Ｐゴシック, MS Sans Serif, MS Serif, MS UI Gothic, ＭＳ ゴシック, MV Boli, NSimSun, Palatino Linotype, PMingLiU-ExtB, Roman, Segoe Print, Segoe Script, Segoe UI, Segoe UI Light, Segoe UI Semibold, Segoe UI Symbol, SimSun, SimSun-ExtB, Small Fonts, Sylfaen, Symbol, Tahoma, Times, Times New Roman, Trebuchet MS, Twemoji Mozilla, Verdana, Webdings, Wingdings, 宋体, 微软雅黑
```

FF81.0, Win7

**Comment by earthlng** [comment]
Win7 so far:

compared to Pants 68 fonts, my list is missing `Arial Narrow`, `Calibri Light`, `Calibri Light Italic`.
Stan's list has the 2 Calibri Light's but is also missing the `Arial Narrow`.

Apparently the 2 Calibri Light's were not installed by default on Win7 but came with an optional, non-security update:

https://support.microsoft.com/en-my/help/2761217/an-update-is-available-to-add-the-calibri-light-and-calibri-light-ital

As for the `Arial Narrow`:

it's **not** in the official **Font List Windows 7**: https://docs.microsoft.com/en-us/typography/fonts/windows_7_font_list

from [Is the Arial Narrow font missing on your system?](https://www.thebest3d.com/dogwaffle/faq/missing-arial-narrow-font.html):

> On some Windows systems, such as Windows 7 / 64-bit, recent releases, and perhaps even on earlier similar releases (we don't know exactly), the Monotype Arial Narrow font (a TrueType font) is not included by default with the operating system. It is licensed and included with MS Office, and other apps, but not as part just of the OS in itself

and from [Arial Narrow with Windows 7](https://forums.autodesk.com/t5/autocad-forum/arial-narrow-with-windows-7/m-p/3219306#M216327):

> I have discovered that Arial Narrow is not installed on Win 7 machines until you install office.

---

so, ideally mozilla should not allow styles which aren't explicitly listed and also remove `Calibri Light` from the list.
That would be a major improvement which would hopefully make pretty much all Win7s lookalike and since this is an RFP feature which doesn't affect the majority of the "normal" FF users, shouldn't be too much to ask.
If they could additionally make any not-explicitly-allowed font-style fallback to its regular font style (if that one's in the allowlist), so fe `Arial Narrow` -> `Arial`, `Calibri Light` -> `Calibri`, most people would probably not even notice it and sites using such fonts would still look close enough to their intended style.

**Comment by earthlng** [comment]
The only difference between the 2 Win10 lists is `HoloLens MDL2 Assets`.
According to [Microsoft](https://docs.microsoft.com/en-us/typography/font-list/hololens-mdl2-assets) it was installed as part of an update in 2015.
Unless we find out more, I don't think we can make the argument to remove that font from the list "because some people haven't updated their systems in 5 years" :)

**Comment by Thorin-Oakenpants** [comment]
good digging: maybe we move that and this comment to a new thread and not derail this one (keep it for results only, and we need more results)? anyway: some thoughts
- they are not going to do anything for win7 users (and win7 vs win10 will not get parity IMO, although they theoretically could I think)
- ^^ that said, the optionally installed family styles (from the likes of MS Office) have the same impact on win10 by the looks of it
- changing font listing to handle styles per family might be complicated (IDK) and I have NFI of the implications or how it's done in Mac or Linux
- it may be low priority: i.e if 5 font styles or fonts cause entropy for a possible 20 buckets (e.g. on Win10), then that may be good enough for now: the rational being that 220 million FF users, say 150 million are on windows (100 million on win10), then 20 buckets in that pool is OK (for now) - it depends on the spread (they won't be equally sized buckets)
- or they could drop, comment out, some unneeded fonts from the list: who "needs" calibri?: certainly not for displaying characters: for example, it's not used in TB's whitelisting

At this point, I know what I would do: drop fonts that are redundant to displaying the correct characters. Then look at what leaks via styles in a family (maybe that fix is easy, who knows?)

**Comment by Thorin-Oakenpants** [comment]
> I don't think we can make the argument to remove that font

Well, yes. we would need more data. However, from a FP defence standpoint, you reduce the attack surface - removing redundant unneeded fonts is step one and would cover HoLens (NFI why someone would be missing it: windows can be hit and miss IMO)

**Comment by earthlng** [comment]
We're talking about an RFP feature here. 220 million FF users aren't using RFP.

> they are not going to do anything for win7 users

I think it depends. Of course arguing for Win7 + Win10 parity is too much to ask and never going to happen. But just making it a strict list (ie don't allow additional, unlisted styles) and maybe removing 1 or 2 fonts isn't unreasonable IMO and would be a major improvement. And perhaps it's not very time consuming or difficult to implement. We won't know unless we ask Jonathan.

**Comment by PinkieSwirl** [comment]
> Unless we find out more, I don't think we can make the argument to remove that font from the list "because some people haven't updated their systems in 5 years" :)

Since my system is updated, my guess is that it is due to the N version I use: Windows 10 Pro N

**Comment by Thorin-Oakenpants** [comment]
> We're talking about an RFP feature here. 220 million FF users aren't using RFP.

That wasn't my point. I should have worded it differently. Long term the plan is to make RFP front facing, maybe make it default in PB mode (along with making dFPI default for all windows). So the assumption/logic is that at some stage there will be significant numbers. So if 220 million users -> 150 million windows -> 100 million on win10 -> 5-10% use RFP: thats 5-10 million users. TB for example has AFAIK, about six million users (concurrently?) of which only some will be windows

As log as the intended bucket is sufficient numbers, and the more numbers the better, then it's all good. Coding or logic around low numbers of users is a waste of effort (not to be confused with removing the attack surface). Not sure if I'm being clear here: I need a break :)

> Since my system is updated, my guess is that it is due to the N version I use: Windows 10 Pro N

Yeah. I never thought you weren't up to date: 5 years is whack: missing at least 5-year-old font does not mean no updates. As I said, windows can be hit and miss. Elaborating: due to complexity, patches fail. Patches can be optional. There's a plethora of release versions and so on.

> We won't know unless we ask Jonathan

Right. So we need more data. And then we can propose two things a) reduce the surface of unneeded fonts like calibri b) look at styles vs families. It really comes down to the data, for all we know in the next 1 million tests the diff is only 4 fonts/styles - or it could be 20 fonts/styles

**Comment by Thorin-Oakenpants** [comment]
I also actually think we can achieve win7 + win10 parity: and this would be of interest to TB

**Comment by r-a-y** [comment]
<details><summary>208a715ffdcb22a22b86e3d9c0d598303ced6911 [101/486]</summary>

> Arial,  Arial Black, Bahnschrift, Calibri, Calibri Light, Cambria, Cambria  Math, Candara, Candara Light, Comic Sans MS, Consolas, Constantia,  Corbel, Corbel Light, Courier, Courier New, Ebrima, Gabriola, Gadugi,  Georgia, Helvetica, HoloLens MDL2 Assets, Impact, Javanese Text,  Leelawadee UI, Leelawadee UI Semilight, Lucida Console, Lucida Sans  Unicode, Malgun Gothic, Malgun Gothic Semilight, Marlett, Microsoft  Himalaya, Microsoft JhengHei, Microsoft JhengHei UI, Microsoft JhengHei  UI Light, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Sans  Serif, Microsoft Tai Le, Microsoft YaHei, Microsoft YaHei Light,  Microsoft YaHei UI, Microsoft YaHei UI Light, Microsoft Yi Baiti,  MingLiU_HKSCS-ExtB, MingLiU-ExtB, Mongolian Baiti, MS Gothic, MS  PGothic, ＭＳ Ｐゴシック, MS Sans Serif, MS Serif, MS UI Gothic, ＭＳ ゴシック, MV  Boli, Myanmar Text, Nirmala UI, Nirmala UI Semilight, NSimSun, Palatino  Linotype, PMingLiU-ExtB, Roman, Segoe MDL2 Assets, Segoe Print, Segoe  Script, Segoe UI, Segoe UI Black, Segoe UI Emoji, Segoe UI Historic,  Segoe UI Light, Segoe UI Semibold, Segoe UI Semilight, Segoe UI Symbol,  SimSun, SimSun-ExtB, Sitka Banner, Sitka Display, Sitka Heading, Sitka  Small, Sitka Subheading, Sitka Text, Small Fonts, Sylfaen, Symbol,  Tahoma, Times, Times New Roman, Trebuchet MS, Twemoji Mozilla, Verdana,  Webdings, Wingdings, Yu Gothic, Yu Gothic Light, Yu Gothic Medium, Yu  Gothic UI, Yu Gothic UI Light, Yu Gothic UI Semibold, Yu Gothic UI  Semilight, 宋体, 微软雅黑
</details>

FF 81.0.1, Win10

Of the other Win10 submissions, I'm missing Arial Narrow.

**Comment by Thorin-Oakenpants** [comment]
https://docs.microsoft.com/en-us/typography/fonts/font-faq is the source to use - straight from the horse's mouth

earthlng indicated that `Arial Narrow` is added with Office (and maybe with other MS products). I have narrow, and I also have office. Office has (or had, not sure on some of the last offline versions) options (use custom install) for additional fonts, unicode fonts, japanese fonts etc (not sure on the exact wording or the default setting if not custom) - so that makes sense (what E said)

**Comment by earthlng** [comment]
I think we already have enough data to make a good argument to hide unlisted font-styles from CSS. Clearly it's not just an issue on Win7. And it's probably not just a problem with MS Office but with any 3rd party software that installs additional styles of allowed font families.
By doing that they'd make fe a bunch more Windows machines **with** Office indistinguishable (font-wise) from Windows systems **w/o** Office.
Maybe it's not even very difficult to implement and if we tell them now it might even make it into FF83 or 84.
The longer we wait, the longer it's gonna take until we get a better solution is all I'm saying.

Another good argument can be made to comment-out Calibri Light to make Win7's with mainly security-only updates indistinguishable from Win7's with security+optional updates. This is super easy to implement and they can put in a note that it's mainly for Win7 and to allow the font again when they officially end Win7 support, *if* they think that Calibri Light is *that* important.

I mean they clearly care about making the font FP-ing less of an issue or they wouldn't have done any of this, and just removing one font to put more people in the same bucket is a small price to pay IMHO.

**Comment by Thorin-Oakenpants** [comment]
> but with any 3rd party software that installs additional styles of allowed font families

I don't *think* it works that way. The fonts are "owned" by MS and I don't *think* sure you can't just stack more styles into *system* fonts - but moot point, we already know optional styles can cause entropy - so it's a hole that needs closing

> ...

Oh I agree that it's super easy to comment out a font or two. BTW, they added telemetry on users system fonts specially for this. So maybe it's time to do an analysis. And we already know the two things they can do: reduce the list, change it to a font style rather than a family (see line 7's ToDo in the list)

I'll see what I can started upstream, fingers crossed

**Comment by earthlng** [comment]
Yeah, IDK for sure either but I think companies can pay licensing or distribution fees if they want to include certain fonts in their softwares. Of course smaller software won't come with any additional, (+ costly) fonts but bigger and expensive software like fe Adobe Photoshop etc probably can afford to ship some fonts with their product.

**Comment by lazyletucce** [comment]
not sur if i have done it right because it's different:
a20cc33086d8b4bcbb41556954758dfb769b4633 [2/486]
`MingLiU-ExtB, PMingLiU-ExtB`

**Comment by Thorin-Oakenpants** [comment]
^ thanks @lazyletucce 💋  : you're the same as r-a-y and my windows 10 VM

**Comment by Thorin-Oakenpants** [comment]
this has served it's purpose - thanks to everyone who provided data 💋
