### ISSUE TITLE
HTTPS mode (#1031) and extensions

### ISSUE THREAD

**Issue by syncng** [arkenfox/user.js#1032]
#1031
I was wondering...
Are you going to eventually flip these prefs to active, and if so, does it make HTTPZ and HTTPS Everywhere unnecessary?

**Comment by Thorin-Oakenpants** [comment]
HTTPS-Only Mode

Depends: if we flip it (when it's ready), then ESR78 users would need to unflip it (even though we expect them to use the v78 user.js, that's not how the real world works) - we'd be breaking things. But it's definitely something I want to flip on: but needs some thought/discussion

---

Extensions

I don't even use HTTPS-Everywhere (or any other extension). Ditched it about six months ago. I think these days it's pretty much moot given:
- the majority of sites (e.g. in the top 10k or 100k) have migrated to secure, including the CDNs and other bits and bobs
- we block mixed content (both active and passive)
   - nothing much breaks anymore (not like it did 3 or 4 years ago). Sure, you might get the odd site, but fuck them
- so as long as all your regular sites / bookmarks use HTTPS, then you're fine
- there might be an issue with some sites not redirecting insecure to secure: but I'd say it's rare
- for sites you arrive at (e.g. clicking links) that end up insecure
  - this mode would still allow you to load it (when the bugs are fixed)
  - as long as you're not doing anything on the site (you'd have to be logged in = not possible), then the worst that could happen is someone knows exactly what page you looked at (but you are masking your IP right? one can only assume)
  - the urlbar indicates non-HTTPS, but this HTTPS-Only mode adds another layer of defense

I do get that HTTPS-E has a bunch of entries, rules-based, cross-domain shit: but TBH, in my experience, nothing has broken (and I block mixed content), so it wasn't doing anything for me. **THAT SAID** .. i'm anecdotal and clearly 25% (or whatever) of web traffic or page loads or something is insecure - it has a long way to go until insecure is totally blocked by default for all browsers

**Comment by syncng** [comment]
That's fair, you make good points all around
You can close this or maybe leave it for future discussion, I'll leave it up to you
