### ISSUE TITLE
reminder: uMatrix on wiki

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1044]
needs to be noted as unmaintained or something
* [ ] wiki extensions
* [ ] wiki uMatric page 4.2.3

@gwarser your input and superior knowledge here would be welcome

What feature parity is lacking in uBO (and I don't necessarily mean the fine grained control)? such as
- ~~CSP scope~~ (sorry, that's a uBO feature)
- mixed content scope (we can probably ignore this with active/passive prefs and upcoming HTTPS-Only mode)
- workers scope
- what's the status with CNAME in uMatrix

My thoughts were to simply label it as "currently unmaintained; for experts" or something, but leave it in the recommended list, maybe at the bottom

**Comment by gwarser** [comment]
Someone who uses both should comment. 

CSP scope? What do you mean?

Features:

- referrer spoofing
- cookie blocking

Notes:

- CNAME should be working in dev version
- problem with "hpHosts" list is not fixed
- outdated "malware" lists
- in general it will be good idea to skim through issues https://github.com/uBlockOrigin/uMatrix-issues/issues/

Maybe dev version should be recommended? Changes: https://github.com/gorhill/uMatrix/compare/1.4.0...master

**Comment by Thorin-Oakenpants** [comment]
> Someone who uses both should comment.
my bad, but your knowledge is super welcome

> CSP scope
never mind: confused myself: I meant the CSP reports and that's a uBO setting, so all good

> others: all good points to consider

- cookie blocking: I consider this to be covered by a) blocking shitloads of 3rd parties b) FPI
- referrer spoofing: there's alternatives
- lists: personally, i've never used uMatrix for this: it's always been about fine grained control

I guess I should map out all the things uM does and check off what isn't covered by uBO etc. Anyone willing to help gets a virtual beer

**Comment by tzipx5** [comment]
I don't use umatrix anymore, because there is no active development.
The last version is beta 1.4.1b6 from February 2020.
The developer Raymond Hill (gorhill) has uMatrix archived on GitHub. This means that no further commits are possible.

Comment on reddit from gorhill

> I don't have time to work on uMatrix -- it's a project large enough that I would be able to work on it only if I wasn't working on uBO.

https://www.reddit.com/r/uBlockOrigin/comments/i240ds/request_for_a_stable_umatrix_release_for_cname/

**Comment by geeknik** [comment]
> I don't use umatrix anymore, because there is no active development.
> The last version is beta 1.4.1b6 from February 2020.
> The developer Raymond Hill (gorhill) has uMatrix archived on GitHub. This means that no further commits are possible.

That’s the cool thing about GitHub and Open Source software, anyone can fork a project and call it their own. I’m running 1.5.1b4 right now, all the outstanding known bugs have been fixed and a couple of features added. But I’m like gorhill, I don’t feel like supporting users so I won’t be releasing my branch. But it’s only Javascript, so feel free to jump in. 👍🏻

**Comment by Jee-Hex** [comment]
DNS _may_ still leak (or not) when using uM dev version with ESR78 because:
- Fix for `browser.dns` API was supposedly landed in FF80+ only
- `cnameUncloakProxied` was yet to be implemented in uMatrix

**Comment by atomGit** [comment]
[nuTensor](https://github.com/geekprojects/nuTensor) - uMatrix fork

**Comment by EchoDev** [comment]
@Jee-Hex the DNS leak related to cname uncloaking seems to have been fixed. I used multiple DNS leak tests to confirm this so no more DNS leaking with uMatrix when cname uncloaking is enabled on proxied sites.

**Comment by Thorin-Oakenpants** [comment]
https://news.ycombinator.com/item?id=25242917 

I'm not into the rules and syntax, I liked to click in the matrix... but here's some info on how uBO can do what uM did: such as blocking all XHR etc

FYI: I'm still using uM but did some changes
- disabled delete cookies/ local storage / clear cache = I have never used these
- disabled spoof referrer (I changed FF prefs to hard mode: no breakage for my usage)
   > - user_pref("network.http.referer.XOriginPolicy", 2);
   > - user_pref("network.http.referer.XOriginTrimmingPolicy", 2);
- disabled all assets (saves some memory I guess) - I doubt I've ever triggered a block from it in my life
- disabled strict HTTPS (FF has HTTPS-Only mode) - not sure if I used this before
- disabled hyperlink auditing (it's covered by FF prefs)

So that just leaves these (which can be covered by uBO AFAICT)
- workers
- noscript tags 
- rules

Still trying to work out how to do this on the extensions page. I was thinking of moving HTTPS-E, uM, and CSS-Exfil to a new section e.g. "extensions [maybe]": so: (super rough example)
- HTTPS-E: maybe use this if you don't use HTTPS-Only mode
- CSS-Exfil: the threat is practically non-existent, and if it happens to you, the website is already compromised, you have bigger things to worry about (or something)
- uM: not currently maintained, but it's practically feature complete and stable as fuck: keep using it if it's working. Maybe turn off assets which will be outdated. Maybe get the last dev version on github which has CNAME stuff. Otherwise, you can achieve everything uM does in uBO (just without the matrix to click in)

soz for the rambling, but comments welcome
