### ISSUE TITLE
tidy readme (in the user.js)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1045]
@earthlng et al

simplify it, make it more appealing to actually read
- I'm a little torn as on one hand having the info in the actual user.js is good the sense that everything really important is with the file, but on the other hand, it's encouraging users to skip the reading
- the point about updates immaterial (they get prompts!!)
- the point about binary downloads in SB is somewhat covered by the single security tag
- the point about backing up is somewhat covered by the read the wiki titles
- the point in the harden tag point is already made: see step 1 consider TB, and almost all hardens come with a warning which is already listed (the only exception being mathml)
- note the `[default*]` tag being mentioned: maybe we could resolve that another way: e.g. don't provide FFver numbers with default info where it can cause ambiguity (or vice versa: what was the reason you wanted some of those default infos added - was it for the diffs?). But while I think this looks a little out of place, it solves the issue
- also while it's trimmed right down, its a chance to add anything missing
- am open to ideas

---

before: 28 lines, 2.04kb

<details><summary>before</summary><p>

```
  0. Consider using Tor Browser if it meets your needs or fits your threat model better
     * https://www.torproject.org/about/torusers.html.en
  1. READ the full README
     * https://github.com/arkenfox/user.js/blob/master/README.md
  2. READ this
     * https://github.com/arkenfox/user.js/wiki/1.3-Implementation
  3. If you skipped steps 1 and 2 above (shame on you), then here is the absolute minimum
     * Real time binary checks with Google services are disabled (0412)
     * You will still get prompts to update Firefox, but auto-installing them is disabled (0302a)
     * Some user data is erased on close (section 2800). Change this to suit your needs
     * EACH RELEASE check:
         - 4600s: reset prefs made redundant due to privacy.resistFingerprinting (RPF)
                  or enable them as an alternative to RFP (or some of them for ESR users)
         - 9999s: reset deprecated prefs in about:config or enable the relevant section for ESR
     * Site breakage WILL happen
         - There are often trade-offs and conflicts between Security vs Privacy vs Anti-Fingerprinting
           and these need to be balanced against Functionality & Convenience & Breakage
     * You will need to make changes, and to troubleshoot at times (choose wisely, there is always a trade-off).
       While not 100% definitive, search for "[SETUP". If required, add each pref to your overrides section at
       default values (or comment them out and reset them in about:config). Here are the main ones:
       [SETUP-SECURITY] it's one item, read it
            [SETUP-WEB] can cause some websites to break
         [SETUP-CHROME] changes how Firefox itself behaves (i.e. NOT directly website related)
           [SETUP-PERF] may impact performance
         [SETUP-HARDEN] maybe you should consider using the Tor Browser
     * [WARNING] tags are extra special and used sparingly, so heed them
  4. BACKUP your profile folder before implementing (and/or test in a new/cloned profile)
  5. KEEP UP TO DATE: https://github.com/arkenfox/user.js/wiki#small_orange_diamond-maintenance

```

</p></details>

[draft] after: 18 lines, 1.08kb (approx 47% reduction)

<details><summary>after</summary><p>

```
  1. Consider using Tor Browser if it meets your needs or fits your threat model better
       * https://www.torproject.org/about/torusers.html.en
  2. Required reading: Overview, Backing Up, Implementing, and Maintenance entries
       * https://github.com/arkenfox/user.js/wiki
  3. If you skipped step 2, return to step 2
  4. Make changes
       * There are often trade-offs and conflicts between security vs privacy vs anti-fingerprinting
         and these need to be balanced against functionality & convenience & breakage
       * Some breakage will happen. Everyone's experience will differ
       * While not 100% definitive, search for "[SETUP" tags
       * Take the wiki link in step 2 and read the Troubleshooting entry
  5. Some tag info
       [*-SECURITY] it's one item, read it
            [*-WEB] can cause some websites to break
         [*-CHROME] changes how Firefox itself behaves (i.e. not directly website related)
           [*-PERF] may impact performance
          [WARNING] extra special and used sparingly, so heed them
         [DEFAULT*] The default value for the current release
```

</p></details>

Will await E's expert and valued opinion, and anyone else's thoughts

**Comment by Thorin-Oakenpants** [comment]
I can see improvements
- remove the warning tag info? (it's pretty clear what it does)
- lose the numbering?
- under changes: bullet point the sanitizing on close info we lost

```
  4. Make changes
       * There are often trade-offs and conflicts between security vs privacy vs anti-fingerprinting
         and these need to be balanced against functionality & convenience & breakage
       * Some site breakage and unintended consequences will happen. Everyone's experience will differ
           e.g. some user data is erased on close (section 2800), change this to suit your needs
       * While not 100% definitive, search for "[SETUP" tags
```

**Comment by Thorin-Oakenpants** [comment]
maybe add this (rewritten) under the releases info: because that's about the only thing now missing from the original (assuming the sanitize on close info is added as per above post)

```
   * EACH RELEASE check:
         - 4600s: reset prefs made redundant due to privacy.resistFingerprinting (RPF)
                  or enable them as an alternative to RFP (or some of them for ESR users)
         - 9999s: reset deprecated prefs in about:config or enable the relevant section for ESR
```

**Comment by Thorin-Oakenpants** [comment]
bump

**Comment by earthlng** [comment]
> what was the reason you wanted some of those default infos added - was it for the diffs?

no not for the diffs. It's just to help people reading through the file to know which prefs they can more or less ignore fe for troubleshooting or when they first start using the file. It made the most sense for active prefs but since you commented out a bunch of active prefs with default values it looks a bit weird now.

I don't think we need the explanation for default tags under your point 5. In the past we also only added them if the default value also matched ESR's default value. Not sure if that still the case for all of them.

I'd write the full setup tag names, not with *

> remove step 3?

no! :)

> lose the numbering?

no

> bullet point the sanitizing on close info we lost

yes that's definitely worth mentioning somewhere

You wrote all this to begin with so I'll leave it to you to change/update it as you see fit.

**Comment by Thorin-Oakenpants** [comment]
> I don't think we need the explanation for default tags under your point 5

but see what was said in #1040 , or am I missing something as to why you thought the 70+ info should stay on that pref

> I'd write the full setup tag names, not with *

damn. I just knew you'd say that :)  It kinda looks weird and too whitespacey. I'll see what I can do. Whats the worst that can happen? We re-edit it! :)
