### ISSUE TITLE
[Request] REMOVED or HIDDEN : Adding a tag for [HIDDEN]

### ISSUE THREAD

**Issue by iWARR** [arkenfox/user.js#1046]
I've always dreamed of [HIDDEN] tag inside the **REMOVED or HIDDEN** list.
It would be so helpful. So good time-saving info.

Unfortunately, I didn't find a reliable way checking the list by myself to be 100% sure which ones of the prefs are really not REMOVED, but only HIDDEN...

If changing the list repesentation seems too complicated, it's OK, just close this issue.
It was just a question and one-time request.

**Comment by Thorin-Oakenpants** [comment]
there are 28 `[HIDDEN*` tags in the user.js. if one of those prefs is deprecated, then it's moved to the deprecated section as is (no changes) and the bugzilla linking to it's demise is added. At this point, the pref is GONE: we provide the bugzilla. In other words, it's actually not hidden anymore, it actually doesn't exist: so the hidden tag is for posterity and those on ESR

Also, a hidden tag is not 100% definitive: a pref's hidden status
- could be OS dependent (don't think I've ever seen one like this)
- could easily change: lots of bugzillas about moving things to all js etc, and "no need to hide this anymore" or "let's hide this": it's not about being secretive, it's about damage control that users going into about:config can cause

One thing I do once in a while it open a vanilla FF and check our hidden tagged prefs are still hidden by default, just like I do to make sure our `[SETTING` tags are correct. I do not check all the other prefs aren't hidden: but feel free to do so
