### ISSUE TITLE
0710: network.gio.supported-protocols

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1050]
So I was looking a different ticket [1535950](https://bugzilla.mozilla.org/show_bug.cgi?id=1535950) "On Linux the download URI is saved to GVFS/GIO metadata even in private browsing" ... and it reminded me of 0710, which is

```js
/* 0710: disable GIO as a potential proxy bypass vector
 * Gvfs/GIO has a set of supported protocols like obex, network, archive, computer, dav, cdda,
 * gphoto2, trash, etc. By default only smb and sftp protocols are accepted so far (as of FF64)
 * [1] https://bugzilla.mozilla.org/1433507
 * [2] https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/23044
 * [3] https://en.wikipedia.org/wiki/GVfs
 * [4] https://en.wikipedia.org/wiki/GIO_(software) ***/
user_pref("network.gio.supported-protocols", ""); // [HIDDEN PREF]
```

[1433507](https://bugzilla.mozilla.org/show_bug.cgi?id=1433507) was resolved in FF60. Tor Browser's about config does not contain the entry (maybe they maintained their old patch: I would have to check what they rebase). 

I might just ping @acatarineu to check if TB rely on the upstream patch and that is sufficient

OT: By the looks of it, we added it around FF64 - [here we go](https://github.com/arkenfox/user.js/commit/732c438148511b3b32e7f1ce40486db3f2a3431d) .. in 63-alpha, which earthlng brought up in #490

**Comment by Thorin-Oakenpants** [comment]
https://hg.mozilla.org/mozilla-central/rev/848c2234cb27

```c
#ifdef MOZ_PROXY_BYPASS_PROTECTION
      ""           // use none
#else
      "smb:,sftp:" // use defaults
#endif
    );
```

who/what sets MOZ_PROXY_BYPASS_PROTECTION?

**Comment by acatarineu** [comment]
Building with `--enable-proxy-bypass-protection` in the mozconf does that.

**Comment by rusty-snake** [comment]
`about:buildconfig` does not show `--enable-proxy-bypass-protection` for me.

**Comment by acatarineu** [comment]
In Tor Browser? It shows it for me, in Linux. Are you sure it's not there? Which OS?

**Comment by rusty-snake** [comment]
Firefox 82.0 (64bit) - Mozilla Firefox for Fedora

If the offical mozilla binaries uses it and :jeans: say he does not support binaries form distros (which have own patchs, build, config, configure but are 99% offical firefox and are used by a clear majority of the linux users), I can add this to my overrides.

**Comment by acatarineu** [comment]
In TB we build with `--enable-proxy-bypass-protection` but official builds do not, AFAIK. So you need the `network.gio.supported-protocols` pref I think.

**Comment by Thorin-Oakenpants** [comment]
> Building with `--enable-proxy-bypass-protection` in the mozconf does that.

Ahh.. cool. That explains that then :) Thanks

**Comment by gmvk** [comment]
For testing:
https://pseudo-flaw.net/tor/torbutton/scan-protocol-handlers.html

**Comment by Thorin-Oakenpants** [comment]
Thanks. That's old, not sure it even works anymore. Protocol handler FPing is a different beast and is being mitigated upstream.

This pref is for making sure there are no proxy leaks. But the bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1433507 is about the build flag `MOZ_PROXY_BYPASS_PROTECTION`, not the pref (which is hidden so I can't exactly find it by testing FF versions)

The FF60 patch https://hg.mozilla.org/mozilla-central/rev/848c2234cb27 says use none if `MOZ_PROXY_BYPASS_PROTECTION` otherwise only allow smb and sftp, so not sure why we have FF64 only noted for those

Having trouble finding the ticket that introduced the actual pref

**Comment by Thorin-Oakenpants** [comment]
interesting
- FF88 https://bugzilla.mozilla.org/show_bug.cgi?id=1693493 tests added
- FF87 https://bugzilla.mozilla.org/show_bug.cgi?id=1666725 gvfs-integration for browsing broken
   - i guess gvfs has been broken since e10s ? who cares :)

**Comment by Thorin-Oakenpants** [comment]
I just keep coming back to [494163](https://bugzilla.mozilla.org/show_bug.cgi?id=494163) in FF5 (yup, five)
```
+#define MOZ_GIO_SUPPORTED_PROTOCOLS "network.gio.supported-protocols"
```

**Comment by earthlng** [comment]
FYI ...

re: "By default only smb and sftp protocols are accepted so far (as of FF64)" (in the description)

it looks like since FF87 they removed smb from the default-allowed protocols:
https://hg.mozilla.org/mozilla-central/rev/1e47f831e5f2bd7533b32da4c85da666a808a9d7#l15.370

**Comment by gmvk** [comment]
> Thanks. That's old, not sure it even works anymore. Protocol handler FPing is a different beast and is being mitigated upstream.

Date: 12/12/2021, 7:32:43 PM
started
found: sftp (GNOME support)
finished

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/1623 - 11 years ago
