### ISSUE TITLE
localhost or 127.0.0.1 with a port number doesn't work

### ISSUE THREAD

**Issue by iio7** [arkenfox/user.js#1053]
I have searched the old issues, but could not find this issue. Running a local webserver on a non-standard port and trying to access that with Firefox doesn't work. E.g. http://localhost:8080/ gets an "Unable to connect".

I'm sorry if I have missed anything, but I haven't been able to locate any settings directly regarding this.

**Comment by seonwoolee** [comment]
I vaguely remember having this issue. Try enabling `network.dns.disableIPv6`.

**Comment by iio7** [comment]
Yes, that did it. Thanks. I wonder why disabling IPv6 would affect that.

**Comment by Thorin-Oakenpants** [comment]
^ Your router is my guess

**Comment by Thorin-Oakenpants** [comment]
ahh, here we go #757

**Comment by Thorin-Oakenpants** [comment]
I did a bit of searching, and for windows, for example, you can change the priority of ipv4 over ipv6. Or you can disable ipv6 OS wide. And I think you can add a redirect in hosts as another solution. But I'm totally loathe to suggest OS changes to users, and these solutions just seem wrong, as they're out of scope IMO, and can lead to other problems

The php solution is great

@iio7 What are you running for your server, what OS?

**Comment by iio7** [comment]
The server is running Arch Linux.

**Comment by Thorin-Oakenpants** [comment]
> I don't think this should be dealt with in user.js ...

@iio7 : would it have helped you if you had searched for `localhost` and found something like this

```js
/* 0701: disable IPv6
 * ...
 * [NOTE] This may break localhost in PHP. Try configuring your server, see arkenfox #757
 * ... ***/
user_pref("network.dns.disableIPv6", true);
```

So, did you manage to tweak your PHP server and now it's all working?

**Comment by iio7** [comment]
Yes, definitely! :) The first thing I did was to enter `user.js` and search for localhost :)

I recommend making it even easier with something like:

```
[NOTE] This may break localhost in PHP. Use php -S 127.0.0.1:PORT for IPv4 since PHP defaults to IPv6 when you use "localhost".
```

**Comment by iio7** [comment]
By the way, thank you for the amazing work!

**Comment by Thorin-Oakenpants** [comment]
FYI: landed in FF84... this old comment is interesting [1220810#c3](https://bugzilla.mozilla.org/show_bug.cgi?id=1220810#c3) ... in fact the whole bug is interesting
