### ISSUE TITLE
How to handle cookie

### ISSUE THREAD

**Issue by lamboley** [arkenfox/user.js#1056]
Good morning,

Sorry, this is not a real issue, but I dont know where to ask this.

@Thorin-Oakenpants said he doesn't use any extension for managing cookies since it give a false sense of privacy[(776)](https://github.com/arkenfox/user.js/issues/776).
From my understanding he block all cookie and add exception afterwards.

I tried this method on github, but I can't make it work, even with an exception for 'github.com'. Github still show 'Cookies must be enabled to use GitHub'.
How can I achieve this ? Is it still possible to do that ?

I'm also aware that [Cookie AutoDelete](https://addons.mozilla.org/fr/firefox/addon/cookie-autodelete/) now support the deletion of IndexDB, local storage and other things in-session. So with these new feature is it even now a false sense of privacy ? Do blocking all cookies/persistent storage is still better then using CAD ? 

Here is my [user-overrides.js](https://gist.github.com/lamboley/73ecd7f7add2a6181b248a5364705334).

Regards,
Lucas

**Comment by rusty-snake** [comment]
> I tried this method on github, but I can't make it work, even with an exception for 'github.com'. Github still show 'Cookies must be enabled to use GitHub'.

How did you add the exception? AFAIK you _must_ use site-pop-up left in the urlbar if FPI is enabled, because the "Add Exception"-button on about:preferences can not add a firstPartyDomain.

**Comment by lamboley** [comment]
It is as you said, I have FPI enabled and I was using the button 'Add Exception'.
By site-pop-up you mean uncheck the box from the shield in the urlbar ? If I uncheck this, will it not also enable all the other thing (crypto minning, etc) ?

**Comment by Thorin-Oakenpants** [comment]
> AFAIK you *must* use site-pop-up left in the urlbar if FPI is enabled

I'm not sure what is meant by OP saying he added an exception: all I know is that in preferences that is manual, and you can add *whatever* you like, including first party syntax. It's just that by adding exceptions via the site identity panel does that auto-magically for you

Your exception should be `https:\\github.com^firstPartyDomain=github.com`
![like-this](https://user-images.githubusercontent.com/16656956/97868446-9d8a5f80-1d07-11eb-99d4-eb3a2b8e9f00.png)

---

As for the question about CAD. If you're using FPI then at least persistent and session storage is isolated. If you're not using FPI, then *while the persistent and session storage exists* then it can be used - so imagine having a dozen websites open and five of them share a tracker, but you say "oooh but I have CAD and it clears shit" .. can you see the potential problem now?

And if you're using FPI then you don't really need CAD except for repeat visits in a session if you're trying break any linkability to the previous visits (do note that your IP would likely still be the same). And a better solution that pissing around with cleaning up all the time is to simply use TC in hard mode (or do what I do, don't allow it in the first place)

In think #1018 is probably a good read for you

**Comment by atomGit** [comment]
there are a few caveats with @Thorin-Oakenpants default-deny method; shared workers, service workers and session restore are broken, plus you lose granularity over what kind of storage data you want to keep (it's all or nothing) (see his and my conversation starting [here](https://github.com/arkenfox/user.js/issues/1018#issuecomment-698629166))

pants' method is clean and doesn't require a storage cleaner, and i would posit that it's the better way to go IF it works for you, but it doesn't quite work for me personally ... anyway, just wanted to mention this so you know what to expect - if shared/service workers and session restore aren't important to you, go with his method

note that FPI MUST be enabled either way

**Comment by Thorin-Oakenpants** [comment]
> pants' method is clean and doesn't require a storage cleaner, and i would posit that it's the better way to go IF it works for you

hardened TC is also "clean" and doesn't require a storage cleaner, and I would posit that it's the BEST way to go because it works for everybody and you can even relax FPI for cross domain logins, and create multi-containers etc

Not sure what "clean" means. If you mean by simple, then yes. If you mean "bulletproof", then no. It's bulletproof to me, because the only sites I `Allow` cookies is those I log into, so they already have my unique login. And a handful of sites (five or six?), I `Allow for session`, and I couldn't give two hooters about linking me across a session (for these five or six sites) .. but it certainly isn't 100% rock solid bulletproof. TC in hardened mode especially with FPI would be more solid - I guess, not used it: I mean you can make exceptions and so on, so it's really a case of OpSec

**Comment by atomGit** [comment]
sorry, i keep forgetting you're using TC

**Comment by lamboley** [comment]
Well, I will go with Thorin's method, it's working for the moment. It's now working for github with your help, thanks.

**Comment by Marc05** [comment]
The default-deny method also effectively means you can't have autologin on session restore. If you were to add a site exception, that would apply to all TC containers, even temporary ones. That would mean if I whitelist Google, then google cookies won't get cleared from containers that don't have anything to do with Google. In this situation, Cookie AutoDelete is the only practical way. Please feel free to correct me.
