### ISSUE TITLE
Some advice to use uBlock Origin with user.js

### ISSUE THREAD

**Issue by Dupond** [arkenfox/user.js#1060]
Hello,

Since the uMatrix repository has been archived, I'd like to replace it with uBlock Origin, and I assume I'm not the only one ;)

I've read the [Wiki page about uBlock Origin](https://github.com/arkenfox/user.js/wiki/4.2.2-uBlock-Origin), and I've applied the rules and filters of this page, but I still have some questions about the settings, and would appreciate some advice in order to not be counter-productive while using this extension in conjunction with user.js. Maybe adding some recommended settings in the Wiki page would be nice.

I've checked:
- [x] I am an advanced user

On the "Settings" page of the extension, there are four "**Privacy**" settings:

- [ ] Disable pre-fetching (to prevent any connection for blocked network requests)
- [ ] Disable hyperlink auditing
- [ ] Prevent WebRTC from leaking local IP addresses
- [ ] Block CSP reports

From my understanding:
- [ ] "Disable pre-fetching" is redundant with [0601], [0602] and [0603] and should be unchecked
- [x] "Disable hyperlink auditing" should be checked
- [ ] "Prevent WebRTC" is redundant with [2001] and should be unchecked
- [ ] "Block CSP reports" is redundant with [2600] and should be unchecked (the user.js file even says "[WARNING] CSP is a very important and widespread security feature. Don't disable it!")

Am I right?

On the same page, there are also some "**Default behavior**" settings, including those two:

- [ ] Block remote fonts
- [ ] Disable JavaScript

Still from my understanding:

- [x] "Block remote fonts" should be checked since [1401] ("disable websites choosing fonts") is commented out; it can then be overriden on a per-site basis
- [ ] "Disable JavaScript" should be unchecked: scripts will be disabled using `block` settings in the "My rules" tab

Am I also right here? Or is it safe to uncheck "Block remote fonts" and rely on RFP for limiting font enumeration?

The wiki page also says:

> Best practice is to default deny-all, then whitelist.

So here are my rules:

```
* * 1p-script block
* * 3p block
* * 3p-frame block
* * 3p-script block
* * inline-script block
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop
```

All those `behind-the-scene` rules are set by default by the extension itself. Have I made some mistakes? Do you think those rules could be recommended on the wiki page?

Thanx for any help!

**Comment by atomGit** [comment]
> Since the uMatrix repository has been archived...

see [nuTensor](https://github.com/geekprojects/nuTensor)

personally i still use uM for dynamic filtering - i find it much easier to use, and more granular, than uBO (i haven't switched to nuTensor yet) - it works fine and will probably continue to do so for a some time

> On the "Settings" page of the extension, there are four "Privacy" settings:

i thought uBO read prefs.js in order to set these, but i am wrong - ill be interested in feedback on this as well

personally i'm not so liberal with the behind-the-scene stuff, but that's up to you - if you set those to deny you need to remember that when stuff breaks

**Comment by rusty-snake** [comment]
> "Disable pre-fetching" is redundant with [0601], [0602] and [0603] and should be unchecked
> "Prevent WebRTC" is redundant with [2001] and should be unchecked

It's redundant AFAICT, but it does not harm.

>  "Block CSP reports" is redundant with [2600] and should be unchecked (the user.js file even says "[WARNING] CSP is a very important and widespread security feature. Don't disable it!")

This does not block CSP (uBlock origin requires CSPs to work). This blocks reporting of  CSP violations. https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports. You should enable it.

**Comment by atomGit** [comment]
re: 'Disable pre-fetching' and Prevent WebRTC...

> It's redundant AFAICT, but it does not harm.

i thought this as well, but it's a bit interesting that uBO seems to be handling this internally rather than just toggling the prefs

**Comment by rusty-snake** [comment]
> i thought this as well, but it's a bit interesting that uBO seems to be handling this internally rather than just toggling the prefs

If you reset the prefs so that they are not tracked as user-set by firefox and then enable "Prevent WebRTC from leaking local IP addresses". The prefs get flipped on about:config.
- `media.peerconnection.ice.default_address_only`
- `media.peerconnection.ice.no_host`
- `media.peerconnection.ice.proxy_only_if_behind_proxy`

**Comment by Thorin-Oakenpants** [comment]
this is kinda duplicating #1044 where I wanted to go through and work out what is redundant in uM (aside from the popup matrix granularity)

> "Block remote fonts" should be checked since [1401] ("disable websites choosing fonts") is commented out; it can then be overriden on a per-site basis

https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts - this is about downloadable fonts and has nothing to do with pref 1401, which is about using OS/system fonts

**Comment by Dupond** [comment]
Thanx for all the answers!

> personally i'm not so liberal with the behind-the-scene stuff

I agree. I have to look at those more carefully, but I'm not 100% sure to understand it very well. Because of my bad english, and my lack of computer knowledge, I find the explanations on the uBlock Origin wiki hard to understand...

> This does not block CSP (uBlock origin requires CSPs to work). This blocks reporting of CSP violations.
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports. You should enable it.

Right! I'll do that, thanx for the explanation.

> this is kinda duplicating #1044

I'm really sorry about this. I had read your post, but hadn't understood it very well... I'll close this thread, then.

**Comment by Dupond** [comment]
Thanx for all the answers!

> personally i'm not so liberal with the behind-the-scene stuff

I agree. I have to look at those more carefully, but I'm not 100% sure to understand it very well. Because of my bad english, and my lack of computer knowledge, I find the explanations on the uBlock Origin wiki hard to understand...

> This does not block CSP (uBlock origin requires CSPs to work). This blocks reporting of CSP violations.
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports. You should enable it.

Right! I'll do that, thanx for the explanation.

> this is kinda duplicating #1044

I'm really sorry about this. I had read your post, but hadn't understood it very well... I'll close this thread, then.

**Comment by Thorin-Oakenpants** [comment]
well, it's only *kinda* duplicating ... here you wanted to know what settings to use in uBO - the other post was for me to deal with uM on the wiki and just throwing out what feature parity was lacking, what's already covered elsewhere (handling cookies, prefetching, etc), what wasn't important (such as assets), and what pitfalls uM might have (such as CNAME not in stable on AMO) - basically so I could get a handle on what to do with it

> I had read your post, but hadn't understood it very well

Which post: what I said here in this issue (e.g. you said nothing about my comment on the fonts), or the other one? What don't you understand - ask way
