### ISSUE TITLE
Twitch.tv (and other) problem [solved: 2803 Offline Website Data]

### ISSUE THREAD

**Issue by zdat** [arkenfox/user.js#1064]
- browser version: 82.0.3
  - Steps to Reproduce (STR): Set `user_pref("privacy.clearOnShutdown.cookies"` to false in the user.js. Enable dark mode on twitch. Close and open the browser.
  - actual result: Twitch doesn't remember and dark mode will have reset.
  - expected result: Remember my preferences!

This started happening maybe 2 week ago. Basically twitch doesn't remember most of the things I change on the site. It keeps me logged in and remembers my cookie preferences but everything else resets to default every time I restart the browser; dark mode, stream resolutions, BTTV and FFZ extensions etc.

I also noticed there's a popup on reddit that wouldn't appear after I closed it once. It comes back every time I close firefox now. Haven't noticed anything on any other sites. Both of these issues started happening at the same time.

Doesn't happen on a fresh firefox profile but does happen with a fresh user.js with `user_pref("privacy.clearOnShutdown.cookies"` set to false. Also I tried an older user.js and it still happened.

Actually Twitch and reddit would "reset" these things at irregular frequencies before, but it wasn't frequent enough for me to care. Now it seems these aspects (mentioned above) reset every time I close the browser.

I tried clearing the cookies for these sites because I thought maybe it was some bad cookies but it didn't fix anything.

Any idea on how I can go about fixing this?

**Comment by Thorin-Oakenpants** [comment]
> Doesn't happen on a fresh firefox profile but does happen with a fresh user.js

Have you tried [troubleshooting](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting)?

Not clearing `cookies` (which also covers localStorage) is important. How did you set that in the user.js - did the change "stick" in about config (i.e check it was applied on startup)

Try `privacy.clearOnShutdown.offlineApps` (Offline Website Data) - sites aren't restricted to using cookies only: they can use localStorage and IDB

```
     - "Offline Website Data" includes appCache (2730), localStorage (2710),
       service worker cache (2740), and QuotaManager (IndexedDB (2720), asm-cache)
```

**Comment by Emetophobe** [comment]
I get this issue as well with Twitch and Firefox 83.

Setting dom.storage.next_gen to false fixes it.

**Comment by Thorin-Oakenpants** [comment]
^^ that sounds whacky ... if this is indeed *the* (single) fix you needed, then I would suggest you clear all persistent data (ctrl-shft-del, for all time, check everything except passwords - sure, you'll have to login in again on some sites but that's about it), or at the very least when on twitch click the padlock and click "clear cookies and site data" .. or go to about:preferences#privacy and `manage data` (clear everything)

LSNG is the bees knees and the cat's pyjamas

Or you could test first - what if you created a new profile with the user.js, and configured it to not sanitize cookies, etc on close. And logged in to twitch (I don't have an account) and changed to dark mode, closed, reopened.

> This started happening maybe 2 week ago. 

I only added the LSNG pref [less than 6 days](https://github.com/arkenfox/user.js/commit/accef19af474c4aba5534325f465d45c5fb85ea1) before this issue was opened

I'm not convinced LSNG is the problem in OPs case.

**Comment by zdat** [comment]
> Have you tried [troubleshooting](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting)?

I tried the troubleshooter script but I didn't get it to work as I had to restart Firefox every time to test the issue.

> Setting dom.storage.next_gen to false fixes it.

Yep, this fixed it. What are the privacy implications with setting this to false?

> if this is indeed _the_ (single) fix you needed, then I would suggest you clear all persistent data (ctrl-shft-del, for all time, check everything except passwords - sure, you'll have to login in again on some sites but that's about it), or at the very least when on twitch click the padlock and click "clear cookies and site data" .. or go to about:preferences#privacy and manage data (clear everything) ... edit and do a Firefox restart just to be sure

I really don't wanna clear everything. Pretty sure this stuff is more than just logins (dark modes, various other preferences for sites etc.) and even if it isn't I don't wanna log into all my sites again. Wouldn't a fresh profile (like I tested before) be enough?

**Comment by Thorin-Oakenpants** [comment]
> I really don't wanna clear everything

it wasn't clear, but I was pointing that at Emetophobe, as at the time I didn't think your problem was related

But not that it is, you can just continue to leave LSNG at false, or we can dig into why it happens (not sure how I can replicate)

> Wouldn't a fresh profile (like I tested before) be enough

That was to test if the data initializating was the real issue. A brand new profile would of course be starting with zero existing data. So yeah - if you can create a new profile, copy over your your user.js with your overrides (in other words, it would be just like your real profile without any data), and see what happens when you login into twitch, change to dark mode, close, restart and go back - also see if any errors are in the console (but if you don't know what that means, that's OK)

---

I want to leave this open so I can drill down into a proper solution (i.e one that allows LSNG) and maybe add something to the user.js entry - and also so I can learn more about what is holding back Mozilla flipping it on

**Comment by Thorin-Oakenpants** [comment]
> Doesn't happen on a fresh firefox profile but does happen with a fresh user.js

I'm not sure, but sounds like you already tested what I just asked. Hard to tell. So you have it working in your real profile. Copy the user.js to a new profile, flip LSNG and test again: that way the only change is the pref and nothing else, not existing data. That would be definitive for me to take some action

thanks 👍

**Comment by Thorin-Oakenpants** [comment]
FYI: [source](https://bugzilla.mozilla.org/show_bug.cgi?id=1643999#c0), emphasis mine
> Some users experience unsuccessful temporary storage initialization. **It is the only thing which prevents LSNG from being enabled on Release channel**.

**Comment by zdat** [comment]
> I'm not sure, but sounds like you already tested what I just asked. Hard to tell. So you have it working in your real profile. 

Yes, working in my real profile.

>  Copy the user.js to a new profile, flip LSNG and test again: that way the only change is the pref and nothing else, not existing data. That would be definitive for me to take some action

I just put a fresh user.js into a fresh firefox profile with the only change being `dom.storage.next_gen` to false and twitch remembers my dark mode preference after a restart.

With a fresh user.js into a fresh firefox profile with no changes (`dom.storage.next_gen` to true) twitch doesn't remember my dark mode preference after a restart.

I think that's what you wanted.

It probably doesn't remember any of the other things I mentioned above either (stream resolutions, BTTV and FFZ extension configs, the reddit pop-up). Twitch dark mode is just the easiest to test.

> (I don't have an account) 

Btw you don't need an account on twitch to mess with dark mode if you wanted to test.

**Comment by Thorin-Oakenpants** [comment]
Thanks .. so that confirms that it's not the pref (per se), but the existing data initialization - because you have old data

**Comment by Thorin-Oakenpants** [comment]
OK, I *knew* that didn't make sense... LSNG is not the problem. LSNG doesn't fail initialization when there is no existing data. If you're losing data then it must be sanitizing. And indeed, it is as per my first reply

Tools: Vanilla Profile FF83
Test: twitch
Note: Using storage inspector: the theme is stored in localStorage

🔻 Control
- no changes
- load twitch, it should be light theme, change to dark theme
- restart, load twitch = dark theme remembered ✅ success
- turn on LSNG in about config
- restart, load twitch = dark theme remembered ✅ success

🔻 Test
- add user.js exactly as it is right now in master
- add TWO overrides

```js
/* OVERRIDES */
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.offlineApps", false); // Offline Website Data
```
- close FF, open it, close it (I just want everything to settle and for at least one sanitize on close to happen)
- open FF, go to twitch = dark theme applied ✅ success

🚑 Solution

- see the overrides above

Once again
```
     - "Offline Website Data" includes appCache (2730), localStorage (2710),
       service worker cache (2740), and QuotaManager (IndexedDB (2720), asm-cache)
```

**Comment by Thorin-Oakenpants** [comment]
@zdat @Emetophobe 

Up to you guys
- Either don't use LSNG (`dom.storage.next_gen`) and continue to clear "Offline Website Data"
  - that means you're clearing lots of persistent data (but not cookies, so you're still trackable etc)
  - at some stage it will get turned on by default by Mozilla, and it solves a lot of other problems and is much more robust
- Or use LSNG but don't clear cookies AND don't clear "Offline Website Data"

In terms of persistent local data, if you leave one, then you're potentially re-identifiable (not an issue with sites you log into to, but think about other sites and repeat visits) : so I see no sense in clearing everything except cookies

**Comment by Thorin-Oakenpants** [comment]
this is edge case and possibly changed which the move to the next version of LSNG and changes to sanitizing, so removing label
