### ISSUE TITLE
reminder: CRLite 84+

### ISSUE THREAD

**Issue by earthlng** [arkenfox/user.js#1065]
[1429800](https://bugzilla.mozilla.org/1429800) - [**meta**] Implement a CRLite based revocation mechanism

a quick summary:

- CRLite filters can be downloaded since FF70 (1563056) but were unused at that point

- FF73+ (1586855) made the data usable via the `security.pki.crlite_mode` pref.
But at that point, setting the pref to 2 (=enforce) only covered **revoked** certs:

> Set to 2, CRLite will enforce revocations in the CRLite filter, but still use OCSP if the CRLite filter does not indicate a revocation.

source: https://blog.mozilla.org/security/2020/01/09/crlite-part-2-end-to-end-design/

- in FF84+ it'll finally work for valid certificates too!
[1670985](https://bugzilla.mozilla.org/1670985) - don't fall back to OCSP when the CRLite mode is "enforce"

This will reduce the number of times an OCSP server needs to be contacted and therefore increase privacy.

> ... [in] December 2019, CRLite covered approximately 100M certificates in the WebPKI, of which about 750k were revoked.
> The whole size of the WebPKI trusted by Mozilla with any CRL distribution point listed is 152M certificates, so CRLite today includes 66% of the potentially-compatible WebPKI

![figure5-enrolled-certificates](https://user-images.githubusercontent.com/25846669/99554504-2adfdc00-29b7-11eb-94a7-4e90b4486a56.png)

source: https://blog.mozilla.org/security/2020/01/09/crlite-part-2-end-to-end-design/

---

necessary prefs:

```js
user_pref("security.remote_settings.crlite_filters.enabled", true); // enable data download
user_pref("security.pki.crlite_mode", 2); // set mode to "enforce"
```

IMO we can already enable this now even though it won't do much until FF84.

---

mozilla blogposts about CRLite:

- part 1: [Introducing CRLite: All of the Web PKI’s revocations, compressed ](https://blog.mozilla.org/security/2020/01/09/crlite-part-1-all-web-pki-revocations-compressed/)
- part 2: [The End-to-End Design of CRLite](https://blog.mozilla.org/security/2020/01/09/crlite-part-2-end-to-end-design/)
- part 3: [CRLite: Speeding Up Secure Browsing](https://blog.mozilla.org/security/2020/01/21/crlite-part-3-speeding-up-secure-browsing/)

**Comment by Thorin-Oakenpants** [comment]
yup - this and appCache as soon as we hit 84-beta

**Comment by Thorin-Oakenpants** [comment]
[1677399](https://bugzilla.mozilla.org/show_bug.cgi?id=1677399) ...
