### ISSUE TITLE
ToDo: add FPI "use_site" (inactive)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1066]
`privacy.firstparty.isolate.use_site`

- added in FF78 - [1637516](https://bugzilla.mozilla.org/show_bug.cgi?id=1637516)
- Would be inactive as it's experimental and indeed breaks HOM exceptions as one example
- We can then refer to it in our HOM stuff in #1047 

more to follow

**Comment by Thorin-Oakenpants** [comment]
### Info

Tool: Nightly 85 (with HOM disabled)
Test sites
 - https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases
 - https://wiki.mozilla.org/RapidRelease/Calendar
 - http://example.com
 - https://example.com

### Results

🔻 FPI on, scheme off

Note: on the wiki site I changed every single of the site permissions (to see if they all got the same FPI notation

The preferences exception UIs (for cookies, location, etc all use the exact same notation)
 - i.e `https://arkenfox.github.io^firstPartyDomain=arkenfox.github.io`

![FPI-on-scheme-off-1](https://user-images.githubusercontent.com/16656956/99771745-85854f00-2b01-11eb-9a2f-c668a7ec5ce0.png)

🔻 FPI on, scheme on

Yup, I cleared all site permissions first

So it's now using ``https://arkenfox.github.io^firstPartyDomain=%28https%2Carkenfox.github.io%29``

![FPI-on-scheme-on-1](https://user-images.githubusercontent.com/16656956/99771751-88803f80-2b01-11eb-9bce-24e5f046f020.png)
![FPI-on-scheme-on-2](https://user-images.githubusercontent.com/16656956/99771982-e2810500-2b01-11eb-8cf5-9d2abbe46b52.png)
![FPI-on-scheme-on-3](https://user-images.githubusercontent.com/16656956/99771987-e4e35f00-2b01-11eb-9270-177538d6fc64.png)

🔻 made me think

Are they compatible. Answer: no

test if a scheme works in a non-scheme
- don't sanitize site permissions on close
- FPI on, scheme off
- load TZP index
- block cookies, check exceptions UI/sqlite = `https://arkenfox.github.io^firstPartyDomain=arkenfox.github.io`
- turn scheme on
- restart
- check exceptions UI/sqlite = still there
- load TZP index ▶️  site panel has no permissions set
- do the zombie test ▶️  cookies aren't blocked

test if a non-scheme works in a scheme
- carrying on from above
- go to cookies exception UI and remove the arkenfox entry
- block cookies, check exceptions UI/sqlite = `https://arkenfox.github.io^firstPartyDomain=%28https%2Carkenfox.github.io%29`
- turn scheme off
- restart
- load TZP index  ▶️ site panel has no permissions set
- do the zombie test  ▶️ cookies aren't blocked

So there you go. end of tests

**Comment by Thorin-Oakenpants** [comment]
So what exactly is "scheme" here. Site permissions without "scheme" already appear to be HTTP vs HTTPS separated, and already subdomain separated ...

unless the site permission entries are "lying", i.e internal code handles them differently - but note that the site identity panel doesn't show them (i.e it is strictly following what is shown - http vs http, alice.site.com vs bob.site.com)

I guess the URL encoding is to differentiate use_site from no-use_site?
- `%28` = `(`
- `%2C` = `,`
- `%29` = `)`
- `https://arkenfox.github.io^firstPartyDomain=%28https%2Carkenfox.github.io%29`
- `https://arkenfox.github.io^firstPartyDomain=(https,arkenfox.github.io)`

can someone please tell me what "use_site" is doing here then - or find the bugzilla - TIA

**Comment by Thorin-Oakenpants** [comment]
OK, I think I need truckloads of beers and/or sleep, I keep missing the simple things - it's added `http*` as a point of difference in the `firstPartyDomain=` part. The site permission already maps to this distinction in the bit before `firstPartyDomain=` .. which explains that - and which AFAICT makes the `use_site` pref redundant

So is that it? (I haven't followed this TBH) ... I was expecting more, like subdomains

#tomrittervg

**Comment by gwarser** [comment]
"use_site" - I think this term was used in storage isolation to differentiate between splitting on full domain or on eTLD+1 domain. Eg. `^firstPartyDomain=developer.mozilla.org` vs use_site `^firstPartyDomain=mozilla.org`.

**Comment by Thorin-Oakenpants** [comment]
^ yeah. now I've had a little break, I realized earlier that what I was testing was the site permissions. The pref wouldn't do nothing, or it wouldn't have been added. So
- [1] we need to note that site exceptions will need to be re-added if the pref is used (maybe they could re-engineer that, it seems redundant, IDK)
- [2] actual isolation is different ... but in what way is the question - I think HTTP vs HTTPS was always the case, and the diff is as what you said, gwarser .. just need to confirm

**Comment by earthlng** [comment]
> it's mentioned in the chatter in #959 .. but not the bugzilla list

the bugzilla list does have the ticket. Get some sleep mate :)

**Comment by Thorin-Oakenpants** [comment]
what does it all mean? the key for blog.nightly, developer and wiki are the same .. and blog is missing one...

anyway .. FYI
![dns](https://user-images.githubusercontent.com/16656956/99867503-01d76b00-2bb2-11eb-9164-0b4f393dd5a6.png)
