### ISSUE TITLE
4YI: Bing has stopped to serve search results to the users without JS

### ISSUE THREAD

**Issue by KOLANICH** [arkenfox/user.js#1070]
The workaround: https://github.com/KOLANICH/surrogates.user.js/raw/master/bing.user.js

**Comment by atomGit** [comment]
works for me without JS

**Comment by KOLANICH** [comment]
Have yoou tried clearing cookies for bing.com?

**Comment by atomGit** [comment]
yes sir - must be something other than JS, or perhaps it's a geo-specific thing

my configs are this user.js and my [user-overrides.js](https://codeberg.org/12bytes.org/Firefox-user.js-supplement/src/branch/master/user-overrides.js) uM with JS disabled globally by default (actually i'm using LibreMatrix, but it's pretty much the same)
