### ISSUE TITLE
localstorage does not clean when closing the tab in FF84

### ISSUE THREAD

**Issue by proxy-sh** [arkenfox/user.js#1074]
Hello, in firefox 83 it was always cleaned but in 84 that does not happen, how do I solve this?

**Comment by Thorin-Oakenpants** [comment]
Show me where in the user.js it is possible to sanitize on closing a tab? That's not how Firefox's sanitizing works: instead it allows you to sanitize on close (i.e quitting Firefox), sanitize manually (using Ctrl-Alt-Del), or choose "Forget this Site".

This user.js has FPI (first party isolation enabled), so any persistent local web content is not used across first parties (e.g. google analytics on site A cannot be read/used in any way with google analytics on site B)

If you wish to clear any persistent traces on a PER VISIT (i.e try to break any linkifying of traffic within a session on the same domain), then use temporary containers - but be aware that you would also need to flip your IP. You could also use something like Cookie Auto-Delete - but make sure to not have any tab open of said domain, and make sure to wait for things to be removed, and make sure it removes everything

Not even Tor Browser bothers to hide revisits within the same session. In fact, it doesn't even sanitize on a circuit change (load site, click onion, select change circuit). So I'm not sure what you're trying to achieve here

**Comment by Thorin-Oakenpants** [comment]
PS: you can also use one-off Private Browsing windows: since nothing is written to disk, and as soon as the last PB window is closed, it's released from memory.
