### ISSUE TITLE
how do I get session restore to work

### ISSUE THREAD

**Issue by Denirvan** [arkenfox/user.js#1076]
Hello! Please help me set up browser.cache correctly.
My English is bad and therefore it is difficult for me to understand all user.js settings

user_pref ("browser.cache.disk.enable", false) ;
user_pref ("browser.cache.disk_cache_ssl", false);
user_pref ("browser.cache.memory.enable", false);
user_pref ("browser.cache.memory.capacity", 0);
user_pref ("browser.cache.offline.enable", false);
user_pref ("browser.cache.offline.storage.enable", false)

I need that when the browser is opened, the pages remain that were when the browser was closed.

**Comment by rusty-snake** [comment]
> I need that when the browser is opened, the pages remain that were when the browser was closed.

You mean session-restore? #1034 has a good summary I think.

**Comment by Denirvan** [comment]
Спасибо, почитаю.
I meant this:
I close the browser with 5 open pages and when I open the browser again, these 5 pages open the same.

**Comment by Thorin-Oakenpants** [comment]
cache and memory have nothing to do with session restore

here is your answer
```js
/* override recipe: enable session restore ***/
user_pref("browser.startup.page", 3); // 0102
  // user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  // user_pref("browser.sessionstore.privacy_level", 0); // 1021 optional [to restore extras like cookies and form data]
user_pref("privacy.clearOnShutdown.history", false); // 2803
  // user_pref("privacy.clearOnShutdown.cookies", true); // 2803 optional
  // user_pref("privacy.clearOnShutdown.formdata", true); // 2803 optional
user_pref("privacy.cpd.history", false); // 2804 to match when you use Ctrl-Shift-Del
   // user_pref("privacy.cpd.cookies", true); // 2804 optional
   // user_pref("privacy.cpd.formdata", true); // 2804 optional
```

**Comment by Thorin-Oakenpants** [comment]
PS: the title change is not aimed at you (and english is not your first language) but rather at any readers/users to encourage them to read the file or at least search for key words, as the answer is already in there

Your issue made me rethink something, and I'm going to provide a permanent open issue with "override recipes", just like the one above - for common things some users want to enable - so thanks :) have a beer 🍻 or three

**Comment by Denirvan** [comment]
Always happy to help, if anything, please)
