### ISSUE TITLE
discussion on override recipes

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1079]
So I thought I would create a (locked) sticky issue called "Override Recipes" or something. And I can link to it in the wiki and in the user.js

This is not that issue.,. this issue is so you can all post stuff to get it rolling.

Common things that occur are
- session restore
- netflix etc - widevine/drm
- zoom, jitsu etc

Any others?
Post away, with recipes if you want, e.g.

```js
/* override recipe: turn on session restore ***/
user_pref(etc)
```

**Comment by atomGit** [comment]
i haven't been following the chatter here real close lately - are looking for essentially the same input as before when you asked peeps to post their overrides, or are you looking for overrides for specific scenarios, such as netflix, etc.?

**Comment by Thorin-Oakenpants** [comment]
> or are you looking for overrides for specific scenarios, such as netflix, etc

yes. for example in the last month we've had two people ask the same question about session restore. We've had lots of people ask about getting drm working. Now that working remotely is more of a thing, we've already seen people asking how to get that working as well. I'm sure if I dug through past issues there are a couple of other common ones (and I don't mean one pref flips e.g. letterboxing)

**Comment by Thorin-Oakenpants** [comment]
like this u guys

```js
/* override recipe: enable session restore ***/
user_pref("browser.startup.page", 3); // 0102
  // user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  // user_pref("browser.sessionstore.privacy_level", 0); // 1021 optional [to restore extras like cookies and form data]
user_pref("privacy.clearOnShutdown.history", false); // 2803
  // user_pref("privacy.clearOnShutdown.cookies", true); // 2803 optional
  // user_pref("privacy.clearOnShutdown.formdata", true); // 2803 optional
user_pref("privacy.cpd.history", false); // 2804 to match when you use Ctrl-Shift-Del
   // user_pref("privacy.cpd.cookies", true); // 2804 optional
   // user_pref("privacy.cpd.formdata", true); // 2804 optional
```

**Comment by rusty-snake** [comment]
:rocket: :+1:  :rocket: :+1:  :rocket: :+1: :rocket: 

-------

next one, based on discussion in #1068:
```javascript
/* override recipe: Google Meet | JitsiMeet | BigBlueButton */
// Make sure "Prevent WebRTC from leaking local IP addresses" is unchecked in uBlock origins settings
user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001 maybe not required
user_pref("dom.webaudio.enabled", true); // 2510
   // user_pref("media.autoplay.blocking_policy", 0); // 2031 if you don't want to add exceptions
   // user_pref("media.getusermedia.screensharing.enabled", true); // 2022 optional
```

**Comment by Thorin-Oakenpants** [comment]
@earthlng: we could also add an ESR78 recipe

**Comment by atomGit** [comment]
/* override recipe: allow copy on various websites (d.tube embed code for example) ***/
`user_pref("dom.allow_cut_copy", true);`

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/1079#issuecomment-751169601
> and I don't mean one pref flips

Thanks. But a single item isn't a "recipe". I don't want this to become a list of everything: because everything will break something, otherwise Firefox would have already flipped it

however, that reminds me that I want to recheck that one out. I learnt some more about clipboard shit the other day. I think this falls in the same category

**Comment by Thorin-Oakenpants** [comment]
OK, I've
- created a sticky with two recipes so far
- added the override recipes link to the readme
- added the override recipes to the [implementation](https://github.com/arkenfox/user.js/wiki/1.3-Implementation) steps in the wiki
- updated the [example](https://github.com/arkenfox/user.js/wiki/3.2-Applying-Your-Changes#small_orange_diamond-example) in the wiki on applying changes

If anyone wants to list the netflix/drm stuff for me that would be cool - otherwise I'm see if I can work it out (I've never bothered before and would prefer it if someone gave me a known working solution) - thanks

**Comment by rusty-snake** [comment]
If the history is disabled, SR will not work I guess, will it?
```javascript
   // user_pref("places.history.enabled", true); // 0862 required if you had it set as false
```

**Comment by crssi** [comment]
> 
> 
> If the history is disabled, SR will not work I guess, will it?
> 
> ```js
>    // user_pref("places.history.enabled", true); // 0862 required if you had it set as false
> ```

No, it will not.
