### ISSUE TITLE
horizontal stripes atop youtube videos when UX shows

### ISSUE THREAD

**Issue by securingmom** [arkenfox/user.js#1086]
parrot not dead.   problem vanishes in duplicated profile without userJS.  This is macbook pro 16 i9 Catalina with 64gigs of ram.

userJS in play since pastebin filters are retarded
https://raw.githubusercontent.com/securingmom/pastebinnopes/main/youtubbery

console errors
https://raw.githubusercontent.com/securingmom/pastebinnopes/main/youtubberyconsolery

waterfox G3.0.2

1. view https://youtube.com/watch?v=ycVkX39NdnA
2. while UX visible horizontal stripes
3. move mouse off video pane
3. wait for UX to hide
4. observe stripes gone

<img width="887" alt="Screen Shot 2020-12-31 at 2 17 57 AM" src="https://user-images.githubusercontent.com/76798008/103406942-6a701b00-4b54-11eb-9dee-2e7415192d86.png">

control shift K appears to do nothing in about:config per troubleshooting

also using uBlock Origin, MultiAccount Containers

**Comment by rusty-snake** [comment]
That's RFP's Canvas protection.

**Comment by earthlng** [comment]
I don't get the stripes, not sure why. Try enabling the AdGuard Annoyances + Fanboy’s Annoyance filter lists in uBlock Origin.

> control shift K appears to do nothing in about:config per troubleshooting

maybe the hotkeys are different on Mac or in Waterfox, IDK. In Firefox can also load the Web Console via the Hamburger Menu > Web Developer

**Comment by Thorin-Oakenpants** [comment]
> OP: control shift K appears to do nothing in about:config per troubleshooting
> E: maybe the hotkeys are different on Mac

Users can just open the hamburger menu and click Web Developer
![Untitled-1](https://user-images.githubusercontent.com/16656956/103436765-31e54580-4c17-11eb-9244-caa3657e1785.png)

**Comment by Thorin-Oakenpants** [comment]
> waterfox G3.0.2

closing as invalid

**Comment by securingmom** [comment]
yes, it was BOTH a canvas issue and a fork issue.  Solved with change and switch to firefox.
