### ISSUE TITLE
Link to BrowserBox

### ISSUE THREAD

**Issue by Torxgewinde** [arkenfox/user.js#1087]
Perhaps you would like to add a link to [BrowserBox](https://github.com/Torxgewinde/BrowserBox) where ArkenFox is used as one important step to harden the security. That VM is intended to quickly set up a Browser in a Box, separating the Host-OS and and the Browser inside the VM.

**Comment by Thorin-Oakenpants** [comment]
Thanks. But I do not want to be seen as endorsing anyone else's setups or configs as it can create conflict / confusion (e.g. Decentraleyes is used in BrowserBox). This repo needs to not only **_be_** fully independent and also **_look_** independent

**Comment by Thorin-Oakenpants** [comment]
PS: it's `arkenfox/user.js` ..  not `Arkenfox/gHacks user.js` (i.e there is no `gHacks`)

**Comment by Torxgewinde** [comment]
Thanks for the hint, I will fix it ASAP
