### ISSUE TITLE
prefsCleaner.bat keeps deleting all my user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{XXXX}", true);

### ISSUE THREAD

**Issue by Janaue** [arkenfox/user.js#1091]
I am on w10 1809 with portable firefox and I use prefsCleaner.bat through updater.bat as soon as I update my user-overrides.js, but the prefscleaner keeps deleting all the lines like

 
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{random stuff}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{random stuff}", true);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\" lots of stuff there");

When those lines are removed, all my extensions are like new: they dont see their settings. For instance, this addon https://addons.mozilla.org/en-US/firefox/addon/form-history-control/ no longer shows all the text which are in  backups so I loose everything.

it's very tedious to keep having to copy paste, each time I update, those lines from the backup prefs.js to the new ones in order to link the addons to their real dabatases.

**Comment by earthlng** [comment]
Hi

you can just remove those prefs from your user-overrides.js and the problem should be solved.
I assume you copied all the prefs you had in your prefs.js into your user-overrides when you started using this user.js, or something like that?
Those prefs are set and updated by Firefox internally + automatically and thus there's no need to change or add them to your overrides.

**Comment by Janaue** [comment]
No those prefs user_pref("extensions.webextensions.uuids" and so on are in prefs.js only. My user-overrides.js has only the prefs that I change from your user.js

**Comment by earthlng** [comment]
Hmm, okay, that's weird. I tried to replicate it but I can't.
Are you running the updater.bat with some parameters, or maybe from another directory?
It must find these prefs somewhere. IDK what else could be causing this problem

**Comment by Janaue** [comment]
I put my user_pref("browser.uiCustomization.state" and the various user_pref("extensions.webextensions.ExtensionStorageIDB.migrated. in this pastebin https://pastebin.com/yYpAceVX

I am using the ESR version right now, but it's the same on firefox 84.

So  I use https://portableapps.com/apps/internet/firefox-portable-esr and launch it in order to create the profile.
Then I just add all those browser.uiCustomization.state and extensions.webextensions.ExtensionStorageIDB.migrated.
to the original perfs.js
I also put your updater.bat and prefsCleaner.bat in the profile

Finally, I just create a user-overrides.js with 
user_pref("media.default_volume", "0.22");
user_pref("findbar.highlightAll", true);

and I launch updater.bat.

The result is that the perfs.js goes from 18KB to 17KB and the final clean perfs.js is here https://pastebin.com/iTtPBnXi

i think user_pref("browser.uiCustomization.state", is intact, but user_pref("extensions.webextensions.uuids", has disappeared.

**Comment by Janaue** [comment]
just to be clear. I launch firefox portable only once, ie  in order to build the profile. I don't need to  launch it afterwards.

**Comment by earthlng** [comment]
1. all your `extensions.webextensions.ExtensionStorageIDB.migrated.*` are still there in your final prefs.js
2. your 1st pastebin link doesn't contain an `extensions.webextensions.uuids` pref.

FYI you don't have to start FF portable first to let it create a profile. You can just create a "profile" folder under data and already place your files in there even before you start that portable FF for the 1st time. That way, all the telemetry stuff etc will be disabled right from the get-go.

**Comment by Janaue** [comment]
the correct pastebin with the extensions.webextensions.uuids is here
https://pastebin.com/yVMDgXcs

THe ''extensions.webextensions.ExtensionStorageIDB.migrated.*'' do disappear with my real profile.

**Comment by earthlng** [comment]
then you must be doing something different in your real profile. That's why I asked if you're running the updater with some parameters or from another directory, or something like that. Because as you clearly just demonstrated yourself, the problem doesn't happen otherwise.
If you're using fe the `-multioverrides` parameter and you have a `user.js-overrides` folder in your profile then the updater.bat would pickup any *.js files from that folder, apply them to your user.js as overrides and the prefsCleaner would then reset them.

**Comment by earthlng** [comment]
what you can try is say no when the updater asks if you want to run the prefscleaner, and then look at the user.js. It will almost certainly have those prefs you mentioned in there and you'll have to figure out where it's getting them from.

**Comment by Janaue** [comment]
The user.js is downloaded only after I click updater.bat and the only modification is adding the dummy user-overrides.js with :
user_pref("media.default_volume", "0.22");
user_pref("findbar.highlightAll", true);

so the end of the user.js is :

/* END: internal custom pref to test for syntax errors ***/
user_pref("_user.js.parrot", "SUCCESS: No no he's not dead, he's, he's restin'!");
user_pref("media.default_volume", "0.22");
user_pref("findbar.highlightAll", true);


So to sum up.

I tried again with my real profile in a new profile of portable firefox. In the new profile created by Portable firefox, I delete everything but the ''prefs.js'' file, I import the folders ''extensions'' and ''storage'', I import the files ''extension-preferences.json'', ''extensions.json", "extension-settings.json" and ''storage-sync.sqlite"

In the ''prefs.js'' I add the lines about all the ''extensions.webextensions.uuids'' and ''extensions.webextensions.ExtensionStorageIDB.migrated.*" which is this paste https://pastebin.com/1c2pcZVR . This gives this prefs.js https://pastebin.com/5pWgnTCY

Then I execute firefox and quit, which gives this prefs.js https://pastebin.com/MKzDY6pT
At this point all the addons work.

Then in the profile folder, I put the files ''prefsCleaner.bat'', ''updater.bat'' and the dummy ''user-overrides.js'' consisting of:
user_pref("media.default_volume", "0.22");
user_pref("findbar.highlightAll", true);

I execute ''updater.bat'' in order to get the user.js and merge it with the dummy ''user-overrides.js'' and also clean the prefs.js.
The user.js is this https://paste.ee/p/MAQaR#fUn7O37yiKTe7mtrbDo7SNnZqKPXmdSW
[pastebin says there is offensive content in it, so I use another site]
The cleaned  ''prefs.js'' is this https://pastebin.com/gtuKWqzH
where all the ''extensions.webextensions.uuids'' disappeared.

I launch firefox and no addon works. I quit firefox and this gives the prefs.js https://paste.ee/p/kozYG#Ek3ICLz9tncOTEhUTywtc2GxapH68q1u

I launch firefox and then click to enable safemode, in order to see if the addons will come back later on.
In safemode, there is no addon and I quit firefox. I launch firefox again and all the addons come back. But all settings are lost for the addons which do not use ''storage-sync.sqlite". For instance  the addon https://addons.mozilla.org/en-US/firefox/addon/form-history-control/ loses all its backup entries.

 I quit firefox and this gives the prefs.js https://paste.ee/p/vkG5e#tBJ84ihQd1fN02mm2LHxo0ZWD7Nyv1Np

**Comment by earthlng** [comment]
Ok I can reproduce now with your prefs.js. The problem is that DOS silently drops lines longer than 8k bytes.
I'll see if I can come up with a sanity check to abort prefscleaning in cases like yours.
Thanks for reporting the problem.

**Comment by earthlng** [comment]
> I'll see if I can come up with a sanity check to abort prefscleaning in cases like yours.

done.

ATM I can't be bothered to come up with something better because not too many people will have 50+ extensions installed.
F.e. the longest string in my prefs.js is `browser.uiCustomization.state` at just under 3.3k bytes.

**Comment by Janaue** [comment]
ok thanks for finding the cause!

**Comment by Thorin-Oakenpants** [comment]
> ATM I can't be bothered to come up with something better because not too many people will have 50+ extensions installed.
F.e. the longest string in my prefs.js is browser.uiCustomization.state at just under 3.3k bytes.

FYI: my line in prefs.js is is 1.4kb 

The pref doesn't clean itself up when you remove extensions. You can reset it, then restart FF, and then re-customize (drag and drop your icons etc around, re-add the search bar, etc .. whatever)

**Comment by dezza** [comment]
I also have issues with prefsCleaner removing `browser.uiCustomization.state` after being run. If I put it in `user-overrides.js` it does actually get appended to `prefs.js`, but the UI won't change until I manually paste it into `about:config` overriding the exact same pref. I assume it sets a flag somewhere when `browser.uiCustomization.State` has changed or been updated.
