### ISSUE TITLE
updater.bat suddenly stopped working

### ISSUE THREAD

**Issue by potassiumchloride** [arkenfox/user.js#1093]
Hello,

since I couldn't re-open issue #1092, I started a new one.

Since yesterday I also face exactly the same problem on two Windows machines (7 and 8.1, all 64bit) as the user has reported in issue #1092:

"Update failed. Make sure PowerShell is allowed internet access."

It's the most recent version (4.12) of updater.bat and, needless to say, it has always worked without any problems since I started using ghacks/arkenfox user.js. (I update regularly.) Therefore, I believe, it is not really a problem on your side. It fails both with my regular profile and a temporary, portable profile.

Neither I have changed any Windows settings (on any of the PCs) nor I have installed additional snake oil (external virus scanner, etc.). The PCs just have Microsoft's own virus scanner (Defender, Microsoft Security Essentials) installed.

Ideas anyone?

**Comment by Thorin-Oakenpants** [comment]
I'll close this one and reopen the other one to keep all the setup info in the same issue
