### ISSUE TITLE
Reading that might be interesting

### ISSUE THREAD

**Issue by crssi** [arkenfox/user.js#1096]
`https://www.cs.uic.edu/~polakis/papers/solomos-ndss21.pdf`

Cheers

**Comment by gwarser** [comment]
>Tales of FAVICONS and Caches:Persistent Tracking in Modern Browsers

**Comment by KOLANICH** [comment]
How about making a page in the wiki with a pick of papers?

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1618257#c7

**Comment by Thorin-Oakenpants** [comment]
soz for the delay, twas busy. I read about this several days (or one day?) ago and knew that FF was not affected. And if they did fix it, then we were still covered by [FPI](https://bugzilla.mozilla.org/show_bug.cgi?id=1277803) (or dFPI), and that the fix would take into isolation into account, so it was pointless to follow up on it - that said, I haven't read the paper, and I'm going on very tiny snippets and headlines I have seen

There are more serious leaks for FPI/dFPI: such as dev console, print preview, and view source (to name but a few)

**Comment by Thorin-Oakenpants** [comment]
@KOLANICH I'm not interested in maintaining anything. As it is, I gave abraham all my pdfs from over the years, and he created a repo of titles and links etc
- https://github.com/abrahamjuliot/web-fingerprinting
- when I find new things I buzz him

Just use that

**Comment by Thorin-Oakenpants** [comment]
nothing to see here .. FF is not affected, cuz bug .. and now bug will be not be fixed unless some mitigation is added
