### ISSUE TITLE
broke payment sites: network.http.redirection-limit

### ISSUE THREAD

**Issue by privacyonly** [arkenfox/user.js#1100]
```js
/* 2614: limit HTTP redirects (this does not control redirects with HTML meta tags or JS)
 * [NOTE] A low setting of 5 or under will probably break some sites (e.g. gmail logins)
 * To control HTML Meta tag and JS redirects, use an extension. Default is 20 ***/
user_pref("network.http.redirection-limit", 10);
```

I don' t see any links which make this security issue or anything, but this breaks lots of payment sites, mostly government to bank service(non credit card)

Can we disable this?

**Comment by Thorin-Oakenpants** [comment]
you can code like this (below), it makes it easier to read
I edited your first post, so click the edit button if you're not sure what I mean

` ```js `
` ``` `

---

**_Probably worth considering making inactive, or even just removing_**. I don't think the diff between 10 or 20 is significant - the "damage" is already done. I think we used to have it at `3` or `5`. I guess redirects have gotten deeper.

Read:
- [Redirect tracking](https://blog.mozilla.org/security/2020/08/04/firefox-79-includes-protections-against-redirect-tracking/)
- [Open URL Redirection](https://blog.aunyks.com/2020/2/howd-i-get-here) .. for a quick overview
- note: I didn't particularly look very hard for anything: there are bound to be better recent articles about the threat/mitigations for this (e.g XSS, CSRF, etc)

The pref wasn't really there for anything except perhaps some mitigation (I think we had the value lower many years ago: I mean for what legit purpose did sites have bouncing you around 20 sites) .. but I guess 10 is now too little for some websites - extra security steps, oauth, 2 factor, cross-domain logins, and so on - probably more steps today than in the past.

Limiting the HTTP(s) redirects (and not addressing the others: HTML tags and JS) is not the way to protect against these things anyway - the danger being malware, phishing etc

Meanwhile, feel free to override it in *your* user.js

@earthlng .. I'm pumping towards removing it as dead wood and a waste of time
