### ISSUE TITLE
Strict isolation no longer necssary in FireFox 85?

### ISSUE THREAD

**Issue by rugabunda** [arkenfox/user.js#1103]
Seems new protections akin to firstparty.isolate is now enabled by default in standard firefox installs starting with Firefox 85.0.  Is there any benefit using strict site isolation anymore other than the window size remaining the same? Thats kind of annoying imho.

> 
> Firefox 85 partitions all of the following caches by the top-level site being visited: HTTP cache, image cache, favicon cache, HSTS cache, OCSP cache, style sheet cache, font cache, DNS cache, HTTP Authentication cache, Alt-Svc cache, and TLS certificate cache.
> 
> To further protect users from connection-based tracking, Firefox 85 also partitions pooled connections, prefetch connections, preconnect connections, speculative connections, and TLS session identifiers.

src: https://blog.mozilla.org/security/2021/01/26/supercookie-protections/

**Comment by Thorin-Oakenpants** [comment]
this is tracked in #1051 - I'll answer in there so all my crap is in one place
