### ISSUE TITLE
ui.systemUsesDarkTheme doesn't work anymore

### ISSUE THREAD

**Issue by serverfilesync** [arkenfox/user.js#1106]
Not sure if this is a Firefox problem or an arkenfox problem. But dark theme doesn't work anymore. Tested both on Mac and Linux.

I put the following in my user-overrides.js. And verified that it is enabled in about:config

 /*** MY OVERRIDES ***/

user_pref("privacy.resistFingerprinting.letterboxing", false); 
user_pref("keyword.enabled", true);
user_pref("ui.systemUsesDarkTheme", 1);
user_pref("media.autoplay.blocking_policy", 0);

However, the dark theme part failed to work recently. After googling, I also tried setting the devtools.inspector.color-scheme-simulation.enabled property to true but that doesn't work neither.

**Comment by rusty-snake** [comment]
Works for me. Note that this pref only applies for chrome content (=browser) but not for web content if you use RFP.

> Not sure if this is a Firefox problem or an arkenfox problem. 

Test it in a new profile. Open `about:profiles`, create  new one, start it, open `about:config` and set `ui.systemUsesDarkTheme`.

**Comment by serverfilesync** [comment]
Thank you. Tested in a new profile and it works. Guess I messed up my old profile somehow. Not sure what caused it.

**Comment by serverfilesync** [comment]
Very strange. I tried to use arkenfox again by using the updater.sh in my fresh new profile folder. But the problem persists. Dark theme doesn't work after updater.sh with the same overrides:

 /*** MY OVERRIDES ***/

user_pref("privacy.resistFingerprinting.letterboxing", false); 
user_pref("keyword.enabled", true);
user_pref("ui.systemUsesDarkTheme", 1);
user_pref("media.autoplay.blocking_policy", 0);

**Comment by serverfilesync** [comment]
Thank you! Disabling privacy.resistFingerprinting and dark theme works. Sucks that Firefox works this way.

**Comment by Thorin-Oakenpants** [comment]
> Sucks that Firefox works this way

No, that is how it **_should_** work. Values should be enforced in order to achieve heard immunity. Users who want control over various metrics put all the others at risk. Just wear the godamn mask, you filthy animals :)

**Comment by polyzen** [comment]
@serverfilesync, this works so you can have dark mode without disabling RFP:
https://github.com/rugk/website-dark-mode-switcher

**Comment by KOLANICH** [comment]
There is also a `Dark Reader` addon, but it is damn slow.

**Comment by Felipe-9** [comment]
i havent tested this widely but you can set:
`layout.css.prefers-color-scheme.content-override = 2`
to force websites to use dark-theme instead of syncing with system, this allows us to keep the resist fingerprinting.

**Comment by Thorin-Oakenpants** [comment]
> i havent tested this widely but you can set:

RFP ignores all prefs and will return that it prefers light

**Comment by Felipe-9** [comment]
by "that" you mean the override?
Also i made a little mistake on the setting, its value shouldnt be 2, i set to 0 now but here is the guide: 0=dark, 1=light, 2=system, 3=theme colors

**Comment by Thorin-Oakenpants** [comment]
all that pref refers to is this

<img width="741" height="217" alt="Image" src="https://github.com/user-attachments/assets/76e7b615-7424-4a84-93ad-7d54e010c9c9" />

and it has no effect on RFP
