### ISSUE TITLE
Where the bookmark thumbnails are currently stored?

### ISSUE THREAD

**Issue by 07416** [arkenfox/user.js#1111]
https://github.com/arkenfox/user.js/blob/master/user.js

> /* 2604: disable page thumbnail collection
>  * look in profile/thumbnails directory - you may want to clean that out ***/
> user_pref("browser.pagethumbnails.capturing_disabled", true); // [HIDDEN PREF]
> If you still need help, help us help you by providing relevant information:
>   - browser version
>   - Steps to Reproduce (STR)
>   - actual result
>   - expected result
>   - anything else you deem worth mentioning

  - 85.0 (64-bit, Fedora)
 - I only have the following directories in my profile folder (I haven't yet enabled the `browser.pagethumbnails.capturing_disabled` preference):

```
bookmarkbackups/         datareporting/  saved-telemetry-pings/  storage/
browser-extension-data/  extensions/     security_state/         weave/
crashes/                 minidumps/      sessionstore-backups/
```

**Comment by gitthehubs** [comment]
Here on Windows 10 with Firefox 85.0 portable I do have the directory profile\thumbnails with `user_pref("browser.pagethumbnails.capturing_disabled", true);` .

Can you reproduce the problem with a new profile without any custom settings? If the directory is still not there can you do some browsing so Firefox can create a screenshot to place in the thumnails directory and show it on you frequenlty visited sites on your newpage tab.

https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/browser.pagethumbnails.capturing_disabled

> The preference browser.pagethumbnails.capturing_disabled controls whether the application creates screenshots of visited pages which will be shown if the web page is shown in the grid of the "New Tab Page" (about:newtab) which offers the most often visited pages for fast navigation.

**Comment by rusty-snake** [comment]
Issue 1111 :tada: 

@07416 Maybe in `~/.cache/mozilla/firefox/yeti.bigfood`.

**Comment by Thorin-Oakenpants** [comment]
the location might be OS dependent? Disabling newtab and AS might also be a factor. And new tab pages etc try and use favicons AFAIK, so you might have to scratch around trying to find a site that FF can't find a suitable favicon for which then causes a thumbnail

**Comment by Thorin-Oakenpants** [comment]
In nightly I enabled top sites, cleared it all, add a custom url (you click on the upper right corner of a tile on the ellipsis) .. and I added  [this link](https://gitweb.torproject.org/builders/tor-browser-build.git/plain/projects/tor-browser/Bundle-Data/Docs/ChangeLog.txt) which is a text file. Then I clicked the tile, which populated the tile with an image of the web content

![thumbs](https://user-images.githubusercontent.com/16656956/107053113-5f994d80-67c6-11eb-8f73-d0554c3c2fba.png)

In my nightly profile,. there is no thumbnails dir: and it's not in favicons sqlite. IDK where it's kept

**Comment by 07416** [comment]
> @07416 Maybe in `~/.cache/mozilla/firefox/yeti.bigfood`.

The `thumbnails` folder was there.

**Comment by rusty-snake** [comment]
FTR: Firefox has two profile directories under Linux. One for caches and one for everything else.

![firefox-about-profiles-linux-fs8](https://user-images.githubusercontent.com/41237666/107155191-ea1cb100-696e-11eb-8ba6-16d1ba3e88df.png)
