### ISSUE TITLE
Recipe for unbreaking zoom.us with arkenfox user.js

### ISSUE THREAD

**Issue by mlario** [arkenfox/user.js#1116]
zoom.us does not work with default video conferencing unbreak recipe. Here is a combination to make it work, hope it helps anybody searching for solution:

//standard web conferencing unbreak
user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001 [may or may not be required]
user_pref("dom.webaudio.enabled", true); // 2510

//needed for screensharing
/* 2022: disable screensharing ***/
user_pref("media.getusermedia.screensharing.enabled", true);

//needs to be true for zoom 
/* 2422: disable WebAssembly [FF52+]
user_pref("javascript.options.wasm", true);

//screen flicker in zoom, this should be false
user_pref("layers.acceleration.force-enabled", false);

/* 2010: disable WebGL (Web Graphics Library) ***/
user_pref("webgl.disabled", false);// NEEDED FOR ZOOM
/* 2012: limit WebGL ***/
user_pref("webgl.min_capability_mode", false); // NEEDED FOR ZOOM

/* 4501: enable privacy.resistFingerprinting [FF41+] ***/
user_pref("privacy.resistFingerprinting", false); //breaks zoom if true!

**Comment by Thorin-Oakenpants** [comment]
out of interest: what exactly breaks in zoom with RFP (4501)

**Comment by crssi** [comment]
With RFP enabled the video sharing (from my camera) does not work.

This is the result of my video sharing:
![image](https://user-images.githubusercontent.com/17024151/107881652-33c04b00-6edd-11eb-96bf-1dfe51ef8c25.png)

Without WASM the audio (mic) does not start.

I haven't found any difference of `media.peerconnection.ice.no_host` being `true` or `false`.

**Comment by rusty-snake** [comment]
> This is the result of my video sharing:

Add a canvas exception

> I haven't found any difference of media.peerconnection.ice.no_host being true or false.

Seems to depend on ???internet connection???.

**Comment by KOLANICH** [comment]
@mlario, thanks a lot for your research. You also may find useful [my fork of ResourceOverride addon](https://github.com/KOLANICH-WebExts/ResourceOverride) (cannot merge it because this addon is unfortunately almost unmaintained by its current maintainer and the position of the maintainer is "just become a new maintainer and upload a new addon into AMO under another name").

**Comment by KOLANICH** [comment]
Also please read https://bugzilla.mozilla.org/show_bug.cgi?id=1680150 , RFP may be not needed to be disabled.

**Comment by Thorin-Oakenpants** [comment]
already in the override recipe
> //standard web conferencing unbreak
> user_pref("media.peerconnection.enabled", true); // 2001
> user_pref("media.peerconnection.ice.no_host", false); // 2001 [may or may not be required]
> user_pref("dom.webaudio.enabled", true); // 2510
> 
> //needed for screensharing
> /* 2022: disable screensharing ***/
> user_pref("media.getusermedia.screensharing.enabled", true);

added note to add canvas site exception (not sure when: probably from here)
> /* 4501: enable privacy.resistFingerprinting [FF41+] ***/
> user_pref("privacy.resistFingerprinting", false); //breaks zoom if true!

added (just now)
> //needs to be true for zoom
> /* 2422: disable WebAssembly [FF52+]
> user_pref("javascript.options.wasm", true);

this pref is not in the user.js
> //screen flicker in zoom, this should be false
> user_pref("layers.acceleration.force-enabled", false);

leaves this
> /* 2010: disable WebGL (Web Graphics Library) **_/ user_pref("webgl.disabled", false);// NEEDED FOR ZOOM /_ 2012: limit WebGL ***/
> user_pref("webgl.min_capability_mode", false); // NEEDED FOR ZOOM

so you enabled webgl? the user.js doesn't enable webgl by default? I'm not against adding the info for users who enable webgl, just want to confirm there is no issue with webgl disabled @crssi can you test this 💋

**Comment by crssi** [comment]
You mean, test the zoom with webgl enabled and disabled?

**Comment by Thorin-Oakenpants** [comment]
@crssi yes: new profile, disable webgl: what happens

**Comment by crssi** [comment]
FF 85.0.2 x64, Win10, nilla profile

With
``` js
user_pref("webgl.disabled", true);
```

the video stream of other parties is black and so is also the "my camera" preview... everything else works.

You do not even need to reconnect to zoom meeting and immediately when you set
``` js
user_pref("webgl.disabled", false);
```
the other parties stream shows up (starts to work) and the "my camera" preview also starts to work.

Cheers

**Comment by Thorin-Oakenpants** [comment]
So zoom **_needs_** webgl? right? I mean, whats the point in having a black video stream? right?
So what about `webgl.min_capability_mode`? 

I guess I'll just list them both

**Comment by crssi** [comment]
Did another test... this time nilla profile and  with
``` js
user_pref("webgl.min_capability_mode", true);
```
results as black screen instead of video.

> I guess I'll just list them both

Correct. That is the only way to make it work.

Cheers

**Comment by Thorin-Oakenpants** [comment]
> That is the only way to make it work.

Besides not using zoom as it requires too many privacy sacrifices, or at least using zoom in a different profile/browser :)

**Comment by crssi** [comment]
As usual. 😄 

Beside zoom, "my users" needed webgl for some other stuff (again, those are the "1 browser only" users, who will go chrome immediately something is broken).
So here, webgl is enabled anyway with hope that CanvasBlocker WebGL section is sufficient to "make a noise".

**Comment by Yolakalemowa** [comment]
> zoom.us does not work with default video conferencing unbreak recipe. Here is a combination to make it work, hope it helps anybody searching for solution:
> 
> //standard web conferencing unbreak user_pref("media.peerconnection.enabled", true); // 2001 user_pref("media.peerconnection.ice.no_host", false); // 2001 [may or may not be required] user_pref("dom.webaudio.enabled", true); // 2510
> 
> //needed for screensharing /* 2022: disable screensharing ***/ user_pref("media.getusermedia.screensharing.enabled", true);
> 
> //needs to be true for zoom /* 2422: disable WebAssembly [FF52+] user_pref("javascript.options.wasm", true);
> 
> //screen flicker in zoom, this should be false user_pref("layers.acceleration.force-enabled", false);
> 
> /* 2010: disable WebGL (Web Graphics Library) **_/ user_pref("webgl.disabled", false);// NEEDED FOR ZOOM /_ 2012: limit WebGL ***/ user_pref("webgl.min_capability_mode", false); // NEEDED FOR ZOOM
> 
> /* 4501: enable privacy.resistFingerprinting [FF41+] ***/ user_pref("privacy.resistFingerprinting", false); //breaks zoom if true!

Hi... straight up noob here :D

I came looking for a solution to using jitsi/zoom on FF arkenfox.

My only problem is not being able to hear others' audio (everything else works fine). I tried the overrides recipe and also tried the quoted solution but nothing is working.

Can you help me solve this?

thanks a lot!

**Comment by rusty-snake** [comment]
Maybe autoplay?

https://github.com/arkenfox/user.js/blob/ba052105de3c4be2e34cf103f08b2f28c6d5b496/user.js#L642-L652

**Comment by Yolakalemowa** [comment]
> Maybe autoplay?
> 
> https://github.com/arkenfox/user.js/blob/ba052105de3c4be2e34cf103f08b2f28c6d5b496/user.js#L642-L652

actually yes and even though I tried that at first didn't work... looks like I had to just refresh the page :s... works on default user.js without overrides even.

thanks a lot!

**Comment by linsui** [comment]
https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L589

This breaks jitsi.
