### ISSUE TITLE
about:config in FF87+

### ISSUE THREAD

**Issue by earthlng** [arkenfox/user.js#1118]
If anyone's interested: https://github.com/earthlng/aboutconfig

**Comment by icpantsparti** [comment]
Nice to see there is a choice, thanks.

I'm playing with the console and [JavaScript functions](https://raw.githubusercontent.com/icpantsparti/firefox-user.js-tool/master/userjs-tool-aboutconfig-functions.js) to get more out of the new about:config.

**Comment by earthlng** [comment]
You're welcome :)

That's very cool! Nice to see people using some of my code snippets for other interesting things 👍
