### ISSUE TITLE
Firefox-esr question

### ISSUE THREAD

**Issue by kocjs** [arkenfox/user.js#1120]
I have just upgrade to firefox-esr 78.7. How to enable search in the location bar?

I have enabled within the user-overrides.js. 

`user_pref("keyword.enabled", true); `

Additionally this settings.
```
user_pref("browser.urlbar.trimURLs", true);
user_pref("browser.search.suggest.enabled", true);
user_pref("browser.urlbar.suggest.searches", true);

```
I do not get any errors in the java console.

Is there any user.js especially for firefox-esr?

**Comment by Thorin-Oakenpants** [comment]
you can use the current master user.js, just turn on the deprecated section for your ESR version at the end

readme at the top
```
* RELEASES: https://github.com/arkenfox/user.js/releases

  * It is best to use the arkenfox release that is optimized for and matches your Firefox version
  * EVERYONE: each release
    - run prefsCleaner or reset deprecated prefs (9999s) and prefs made redundant by RPF (4600s)
    - re-enable section 4600 if you don't use RFP
    ESR78
    - If you are not using arkenfox v78... (not a definitive list)
      - 1244: HTTPS-Only mode is enabled
      - 1401: document fonts is inactive as it is now covered by RFP in FF80+
      - 4600: some prefs may apply even if you use RFP (currently none apply as of FF84)
      - 9999: switch the appropriate deprecated section(s) back on
```

so the deprecated section is this
```js
user_pref("_user.js.parrot", "9999 syntax error: the parrot's deprecated!");
/* ESR78.x still uses all the following prefs
// [NOTE] replace the * with a slash in the line above to re-enable them
// FF79
// 0212: enforce fallback text encoding to match en-US
   // When the content or server doesn't declare a charset the browser will
   // fallback to the "Current locale" based on your application language
   // [TEST] https://hsivonen.com/test/moz/check-charset.htm
   // [1] https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/20025
   // [-] https://bugzilla.mozilla.org/1603712
user_pref("intl.charset.fallback.override", "windows-1252");
// * * * /
// FF82
// 0206: disable geographically specific results/search engines e.g. "browser.search.*.US"
   // i.e. ignore all of Mozilla's various search engines in multiple locales
   // [-] https://bugzilla.mozilla.org/1619926
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.geoSpecificDefaults.url", "");
// * * * /
// ***/
```

change the character so it's like this **and do it time you update the user.js**
```js
user_pref("_user.js.parrot", "9999 syntax error: the parrot's deprecated!");
// ESR78.x still uses all the following prefs
// [NOTE] replace the * with a slash in the line above to re-enable them
// FF79
// 0212: enforce fallback text encoding to match en-US
   // When the content or server doesn't declare a charset the browser will
   // fallback to the "Current locale" based on your application language
   // [TEST] https://hsivonen.com/test/moz/check-charset.htm
   // [1] https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/20025
   // [-] https://bugzilla.mozilla.org/1603712
user_pref("intl.charset.fallback.override", "windows-1252");
// * * * /
// FF82
// 0206: disable geographically specific results/search engines e.g. "browser.search.*.US"
   // i.e. ignore all of Mozilla's various search engines in multiple locales
   // [-] https://bugzilla.mozilla.org/1619926
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.geoSpecificDefaults.url", "");
// * * * /
// ***/
```

**AND**

from the readme, you will want some **overrides** such as disabling HTTPS-Only mode (it does not work in ESR78)

But do consider just using the v78 user.js

**Comment by Thorin-Oakenpants** [comment]
> How to enable search in the location bar?

I'm sorry, but you will have to explain to me what it is you want exactly. I'm not up to date with it at all .. since my urlbar has been a dumb non-animated box for over five years. i.e what exactly do you want it to show/do? Suggest search engines, provide real time search suggestions, show history and suggestions?

**Comment by kocjs** [comment]
### Thank you very much. 

I just want to use the urlbar to start a search, that then opens duckduckgo to do the search. I do not use the search bar.

Thank you for clarifying how to use the user.js with firefox-esr. I studied the wiki up and down for hours, and missed the relevant information in the file. I should be mentioned there.

However it works now, using the the v78 user.js.
I think i just forgot to apply the overdrive section to the user.js. Sorry, it was late Yesterday.

**Comment by Thorin-Oakenpants** [comment]
glad you got it sorted out. The urlbar is probably slightly different in release vs ESR since they upgraded it to megabar and more changes are slowly being added: that said, definitely **_applying_** any overrides is a good step 😁

**Comment by ililiillililil** [comment]
> you can use the current master user.js, just turn on the deprecated section for your ESR version at the end
> But do consider just using the v78 user.js

I am wondering, what is the best practice here? Is the first optional equivalent to using the updater script with the "-e" option for ESR?

**Comment by Thorin-Oakenpants** [comment]
I don't use the updater. But according to the wiki, `-e` flips the ESR section on. IDK how that works with two ESR sections (because we have an overlap of releases v92 deprecated through to v95 as the first new-ESR version with the old-ESR version at EOL so prefsCleaner can still be used as users update)

**Comment by ililiillililil** [comment]
Agreed, overlapping ESR versions might be an issue for the updater script. Assuming, one does not use the updater for Firefox ESR 78, is there any recommendation to use release "ghacks user.js v78" or release "arkenfox user.js v91" with the ESR section enabled?

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/issues/1120#issuecomment-780775407
