### ISSUE TITLE
Suggestions for your user

### ISSUE THREAD

**Issue by gallegonovato** [arkenfox/user.js#1121]
Good morning:

First of all thank you for your user, your work and all your help.

I wanted to show you some entries I found on the internet. I apologize if for some reason I messed up or do not apply today. But my knowledge is not much and I am only trying to help.

The entries are:

layers.geometry.basic.enabled

toolkit.legacyUserProfileCustomizations.stylesheet s

browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons

browser.bookmarks.max_backups

network.manage-offline-status

xpinstall.signatures.required

accessibility.typeaheadfin y demas del estilo

general.appversion.override

general.buildID.override

general.platform.override

general.useragent.override

general.appname.override

dom.w3c_touch_events.enabled 0

dom.maxHardwareConcurrency 2

privacy.cpd.downloads

privacy.cpd.formdata

privacy.cpd.offlineApps

privacy.cpd.siteSettings

privacy.clearOnShutdown.openWindos

privacy.cpd.openWindows

privacy.cpd.cache true

privacy.cpd.cookies true

browser.contentblocking.category

permissions.default.shortcuts 2

layers.acceleration.disable

gfx.direct2d.disabled

security.nocertdb

security.pki.crlite_mode 2

security.nocertdb true

browser.chrome.site_icons

browser.cache.memory.capacity

browser.urlbar.maxRichResults

network.ftp.enabled

extensions.update.autoUpdateDefault false

toolkit.legacyUserProfileCustomizations.stylesheet s

browser.privatebrowsing.vpnpromourl

browser.messaging-system.whatsNewPanel.enabled

browser.tabs.unloadOnLowMemory

browser.urlbar.suggest.bookmarks

browser.urlbar.suggest.engines

ui.key.menuAccessKey y ui.key.menuAccessKeyFocuses

browser.display.show_image_placeholders

devtools.debugger.ui.editor-wrapping

browser.helperApps.showOpenOptionForPdfJS

pdfjs.defaultZoomValue

browser.tabs.closeWindowWithLastTab

accessibility.blockautorefresh

image.avif.enabled

editor.truncate_user_pastes

media.videocontrols.picture-in-picture.video-toggle.has-used

media.videocontrols.picture-in-picture.video-toggle.always-show

privacy.cpd.sessions

browser.cache.cache_isolation

privacy.purge_trackers.logging.level

privacy.purge_trackers.consider_entity_list

browser.cache.cache_isolation

privacy.cpd.siteSettings

privacy.history.custom

privacy.cpd.cookies

privacy.cpd.sessions privacy.cpd.siteSettings

privacy.sanitize.timeSpan privacy.history.custom

toolkit.telemetry.coverage.opt-out

full-screen-api.transition-duration.enter 0 0 ??

full-screen-api.transition-duration.leave 0 0 ???

full-screen-api.warning.delay 0???

full-screen-api.warning.timeout 0???

full-screen-api.warning.delay -1???

full-screen-api.warning.timeout -1??

layout.css.focus-visible.enabled

layout.css.grid-template-masonry-value.enabled

network.cookie.sameSite.laxByDefault

network.cookie.sameSite.noneRequiresSecure

network.cookie.sameSite.schemeful

pdfjs.viewerCssTheme

browser.proton.tabs.enabled

browser.proton.appmenu.enabled

browser.newtabpage.activity-stream.newNewtabExperience.enabled

browser.proton.toolbar.enabled

browser.proton.toolbar.version

browser.proton.contextmenus.enabled

privacy.webrtc.globalMuteToggles

A hug and I apologize if I have messed up in any way.

**Comment by Thorin-Oakenpants** [comment]
already in the user.js
```
accessibility.typeaheadfind
browser.bookmarks.max_backups
browser.cache.memory.capacity
browser.chrome.site_icons
browser.contentblocking.category
browser.messaging-system.whatsNewPanel.enabled
browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons
browser.tabs.closeWindowWithLastTab
browser.urlbar.maxRichResults
browser.urlbar.suggest.bookmarks
browser.urlbar.suggest.engines
dom.maxHardwareConcurrency
dom.w3c_touch_events.enabled
extensions.update.autoUpdateDefault
full-screen-api.warning.delay
full-screen-api.warning.timeout
general.appname.override
general.appversion.override
general.buildID.override
general.platform.override
general.useragent.override
gfx.direct2d.disabled
layers.acceleration.disabled
network.ftp.enabled
network.manage-offline-status
permissions.default.shortcuts
privacy.clearOnShutdown.openWindows
privacy.cpd.cache
privacy.cpd.cookies
privacy.cpd.downloads
privacy.cpd.formdata
privacy.cpd.offlineApps
privacy.cpd.openWindows
privacy.cpd.sessions
privacy.cpd.siteSettings
privacy.sanitize.timeSpan
security.nocertdb
security.pki.crlite_mode
toolkit.legacyUserProfileCustomizations.stylesheets
toolkit.telemetry.coverage.opt-out
ui.key.menuAccessKey
xpinstall.signatures.required
```

does not exist
```
browser.cache.cache_isolation
pdfjs.viewerCssTheme (but there is viewerCssTheme property for pdfjs)
```

proton prefs are only temporary (and nothing to do with privacy)
```
browser.proton.appmenu.enabled
browser.proton.contextmenus.enabled
browser.proton.tabs.enabled
browser.proton.toolbar.enabled
browser.proton.toolbar.version
```


nothing to do with privacy and changing some of them can be detected by JS
```
browser.display.show_image_placeholders
browser.newtabpage.activity-stream.newNewtabExperience.enabled
browser.privatebrowsing.vpnpromourl
browser.tabs.unloadOnLowMemory
devtools.debugger.ui.editor-wrapping
full-screen-api.transition-duration.enter
full-screen-api.transition-duration.leave
image.avif.enabled
layout.css.focus-visible.enabled
media.videocontrols.picture-in-picture.video-toggle.always-show
media.videocontrols.picture-in-picture.video-toggle.has-used - set internally
pdfjs.defaultZoomValue - and AFAICT not used at all in code
privacy.webrtc.globalMuteToggles

```

these are experiments running in Nightly and will ride the train to stable when ready and will be dealt with then
```
layout.css.grid-template-masonry-value.enabled
network.cookie.sameSite.laxByDefault
network.cookie.sameSite.noneRequiresSecure
network.cookie.sameSite.schemeful
```


leaves these and I see no reason to look at them in any detail at first glance
```
accessibility.blockautorefresh
browser.helperApps.showOpenOptionForPdfJS
editor.truncate_user_pastes
layers.geometry.basic.enabled
privacy.history.custom
privacy.purge_trackers.consider_entity_list
privacy.purge_trackers.logging.level
```

the only interesting one is `privacy.history.custom` which I think is set by runtime since we already use custom history options, but might pay to check it

**Comment by Thorin-Oakenpants** [comment]
fyi: `pdfjs.viewerCssTheme` is new in FF86+

**Comment by gallegonovato** [comment]
Good afternoon @Thorin-Oakenpants 

Thank you very much for your time and help.

They were entries I was writing down, and others found from bugs I found around the web.

I am sorry for the inconvenience caused and the mistakes on my part.

**Comment by Thorin-Oakenpants** [comment]
> the only interesting one is `privacy.history.custom` which I think is set by runtime since we already use custom history options, but might pay to check it

In a vanilla ESR78 profile
- pref is default false
- add user.js with just section 2800
- restart
- pref is default false and stays that way forever until you open options, then runtime changes it

So the question is, what affect does this pref have when false but we're trying to use custom "history" settings

**Comment by Thorin-Oakenpants** [comment]
https://searchfox.org/mozilla-central/search?q=privacy.history.custom&path=&case=false&regexp=false

AFAICT, its only used for the preferences UI
- https://searchfox.org/mozilla-central/source/browser/components/preferences/privacy.js#1372-1412

**Comment by Thorin-Oakenpants** [comment]
something is nagging me

https://searchfox.org/mozilla-central/search?q=prefsForKeepingHistory&redirect=false

```js
  prefsForKeepingHistory: {
    "places.history.enabled": true, // History is enabled
    "browser.formfill.enable": true, // Form information is saved
    "privacy.sanitize.sanitizeOnShutdown": false, // Private date is NOT cleared on shutdown
  },
```

so if I read it right...
```js
 /**
   * Initialize the history mode menulist based on the privacy preferences
   */
  initializeHistoryMode() {
    let mode;
    let getVal = aPref => Preferences.get(aPref).value;

    if (getVal("privacy.history.custom")) {
      mode = "custom";
    } else if (this._checkHistoryValues(this.prefsForKeepingHistory)) {
      if (getVal("browser.privatebrowsing.autostart")) {
        mode = "dontremember";
      } else {
        mode = "remember";
      }
    } else {
      mode = "custom";
    }

    document.getElementById("historyMode").value = mode;
  },

  /**
   * Update the selected pane based on the history mode menulist
   */
  updateHistoryModePane() {
    let selectedIndex = -1;
    switch (document.getElementById("historyMode").value) {
      case "remember":
        selectedIndex = 0;
        break;
      case "dontremember":
        selectedIndex = 1;
        break;
      case "custom":
        selectedIndex = 2;
        break;
    }
    document.getElementById("historyPane").selectedIndex = selectedIndex;
    Preferences.get("privacy.history.custom").value = selectedIndex == 2;
  },
```

as long as the menulist is set as custom then we're good, and this requires `prefsForKeepingHistory` be false, which means one of these must be the opposite
 - "places.history.enabled": true, // History is enabled
 - "browser.formfill.enable": true, // Form information is saved
 - "privacy.sanitize.sanitizeOnShutdown": false, // Private date is NOT cleared on shutdown

Now we actually flip formfill and sanitize, but what if a user overrides and flips those two back: what happens? And what happens if we add `privacy.history.custom` = `true` in that same scenario?

Not sure if it's worth the effort: would users really flip sanitizeOnClose instead of flipping individual sanitize prefs? @earthlng

**Comment by Thorin-Oakenpants** [comment]
pdfjs allows JS (which we disable) .. do some testing, it might leak, it might not - but TBH, I do not care about dark theme - 99% of the web doesn't even have a prefers-color-scheme

**Comment by opusforlife2** [comment]
> do some testing

Not sure how to do that. Is there a test available in TZP?

**Comment by Thorin-Oakenpants** [comment]
look, pdfjs has limited js (if enabled). Since it's a different principal, and there is no JS, it can't exfil anything anyway, AFAIK. And chrome colors are not web accessible. So, without being 100% sure, the answer is, I don't really care. Seems harmless to me.

I also think this color is supposed to, or will, follow the theme: and maybe RFP will affect that down the track, and then maybe RFP won't when it gets granularity (e.g exempt certain principals/extensions etc)

once again ... I do not care about all this obsessing over dark theme - the next person who asks about dark themes will get a picture of a hamster eating at a tiny picnic table

locking this old resolved issue sorry
