### ISSUE TITLE
prefsCleaner.sh: This script should be run from your Firefox profile directory.

### ISSUE THREAD

**Issue by ohnonot** [arkenfox/user.js#1125]
That sentence is misleading (or plain wrong, depending on how tight you put your unix hat on).
The way it is now, the script _must be copied to the FF profile directory_.
Running it from the profile directory could also mean this:
~~~
$> cd ~/.mozilla/firefox/nnnn.nnnn
$> sh ~/git/arkenfox.user.js/prefsCleaner.sh
~~~
But the first thing the script does is `cd` away from it, and errors out with "prefs.js not found in the current directory"!
AFAICS there is no need for this directory changing at all since the script uses only relative paths anyhow.
So, removing `cd "$(dirname "${sfp}")"` and everything above it, I re-ran the script succesfully ([gist](https://gist.github.com/ohnonot/8594297fe541367e4246b807ff1fcf5c)).
That way, the sentence "This script should be run from your Firefox profile directory." becomes actually true.
And there's no need to copy the script to the FF profile directory, one just needs to start the script with the correct current working directory.

I cannot imagine that this would be any different from Linux on MacOS or some BSD. But maybe I'm missing something important; but then at least that sentence (title) should be changed.

**Comment by Thorin-Oakenpants** [comment]
Thanks. This is @earthlng 's area. Hopefully he might reply soon :)

**Comment by earthlng** [comment]
Hi,

I think that sentence was just copied from the Windows version (along with most of the other static text) and yes it could be misunderstood on Linux/Mac.
We need to get the profile path somehow and in my mind the easiest and most reliable way is to get it from the script path.
It's more convenient to just place the script in your profile directory and then you can call it from anywhere you want. You only have to do that once whereas with cd-ing into the right directory you'd have to remember to do every time.
If you prefer to do it any other way, you can of course edit your copy of the script however you want.

I'm not opposed to change that sentence but it has to be something better than it is now.
I don't like "the script must be copied to the FF profile directory" because that's a weird message for a script that's already running.
"This script should be run from your Firefox profile directory." on the other hand serves as kind of a nice and subtle reminder as to what the problem could be if something doesn't work.

**Comment by ohnonot** [comment]
You are thinking of running this non-interatively, yes?

If this was for Linux only... I'm sure I could offer a mechanism that attempts to find the Firefox profile instead, and `cd` into it which would be more robust IMO.
Sth like (pseudocode):
~~~
find /all_possible_options_for_a_ff_profile_to_reside/unique.file && cd to that path
~~~
"unique.file" would be something that is very likely only present in a FF profile's root, e.g. `addons.json` or `webappsstore.sqlite` (`prefs.js` could be ambiguous)?

If multiple paths are returned, the user could be offered a `choice`.

But since this script needs to cover MacOS too, I'm not so confident.

It's of little consequence anyhow, but that sentence would need to be changed. Or better yet removed and replaced with a test that will exit on fail, with a suitable message like "Please move this script to your FF directory".

**Comment by earthlng** [comment]
> You are thinking of running this non-interatively, yes?

no not really, it always prompts for Start, Help or Exit anyways.

We already have something similar to what you're suggesting in the updater.sh with the readIniFile functionality.
We could reuse that in the prefsCleaner and to that end I just posted a [pull request](https://github.com/arkenfox/user.js/pull/1128) for a cleanup/improvement of that function.

You're more than welcome to test that code, give feedback/improvements and/or implement the same or something similar for the prefsCleaner in a new Pull Request.

My idea would be to copy-paste the new readIniFile function and use something like this for getProfilePath():
```bash
getProfilePath () {
  declare -r f1=~/Library/Application\ Support/Firefox/profiles.ini
  declare -r f2=~/.mozilla/firefox/profiles.ini

  if [[ -f "$f1" ]]; then
    readIniFile "$f1" # updates PROFILE_PATH or exits on error
  elif [[ -f "$f2" ]]; then
    readIniFile "$f2"
  else
    # message about profiles.ini not found, attempting to use scriptpath as PROFILE_PATH
    some code here
    PROFILE_PATH=...
  fi
}
```

**Comment by ohnonot** [comment]
Isn't that overcomplicating things?
It's enough to figure out where the profile directory is (interactively to be sure) and `cd` into it, like I wrote earlier.

**Comment by earthlng** [comment]
IDK what you have in mind until you show me some code. Only then can I tell you if I think that's good enough.

ATM you just have to copy the script into your profile directory and anything we add beyond that is overcomplicating things, IMO.
If we add something more, it has to be reliable and parsing the same file FF uses, seems like the most logical + reliable way to go.
