### ISSUE TITLE
Thoughts on gfx.webrender.all ?

### ISSUE THREAD

**Issue by itsdeadguy** [arkenfox/user.js#1126]
Hello, loving this project so far.

Does anyone know what the privacy ramifications of setting this option to true would be? It is currently false on my 85.0.1 64bit on Void Linux.

I first came across it on this [video about testing color contrast and simulating color blindness on the mozilla developer youtube channel](https://www.youtube.com/watch?v=eBefjaWud-M).

On the one hand, it would be useful for my work, but on the other it might be better to have it on in a different profile? So far, i've been trying to see how much of my actual job (designing websites and testing them for accessibility) i can do while staying privacy conscious using arkenfox and the results have been good.
I just figured i'd ask here first and see if anyone knew about this.

**Comment by Thorin-Oakenpants** [comment]
https://wiki.mozilla.org/Platform/GFX/WebRender_Where

you can check if you have webrender by going to about:support, scroll down to the `Graphics` header and the first item will say something like `Compositing : WebRender`

webrender is being automatically rolled out to everyone. It's not a privacy issue. If you do not have it by default, feel free to enable it and see what sort of results you get (not sure if that is the only pref needed: I thought it used to be more, IDK)
