### ISSUE TITLE
Making permissions.default.xr consistent

### ISSUE THREAD

**Issue by freelyskycloud** [arkenfox/user.js#1129]
`permissions.default.geo`, `permissions.default.camera`, `permissions.default.microphone`, `permissions.default.desktop-notification` and `permissions.default.shortcuts` all have a value of 2.

I think `permissions.default.xr` value should be 2, rather than 0 to keep it aligned with the rest of them.

**Comment by Thorin-Oakenpants** [comment]
true :)
