### ISSUE TITLE
Using v78 in ESR 78.8

### ISSUE THREAD

**Issue by cronos1998** [arkenfox/user.js#1131]
Hi,

it is recommended that Arkenfox v78 should be used for the most recent Firefox ESR version (78.8)

By the time Arkenfox v78 came out (July 2020), it was obviously targeting ESR 78.0

Therefore, it doesn't cover all the changes from later ESR versions (78.1 and higher)

As far as I understand, minor ESR upgrades bring changes regarding security

Can somebody please explain why these changes are not a reason to use a more recent Arkenfox version?

Is there a need to update v78 in any way?

Thanks

**Comment by Thorin-Oakenpants** [comment]
The patches ESR gets are security ones, and generally do not affect preferences. They are likely to be free-after-use critical bugs, or bugs causes crashes etc.

The only thing missing in the v78 release for ESR78 would be improved defaults, better reference links, better information/descriptions etc
