### ISSUE TITLE
Add DoH(DNS over HTTPS) setting

### ISSUE THREAD

**Issue by OraBB1t** [arkenfox/user.js#1133]
I noticed that user.js doesn't have a DoH(DNS over HTTPS) setting. I know that mozilla has enabled this by default on some countries, but not all. It would be nice to have the setting, possibly enabled by default in user.js.  Add it under '0700' ?

[https://wiki.mozilla.org/Trusted_Recursive_Resolver](https://wiki.mozilla.org/Trusted_Recursive_Resolver)

`network.trr.mode` turns on the DoH support.

Bascially,
0 - Default value (currently is 5, which means DoH is disabled)
1 - DoH is enabled, but Firefox picks if it uses DoH or regular DNS based on which returns faster query responses
2 - DoH is enabled, and regular DNS works as a backup
3 - DoH is enabled, and regular DNS is disabled
5 - DoH is disabled
-[https://www.zdnet.com/article/how-to-enable-dns-over-https-doh-in-firefox/](https://www.zdnet.com/article/how-to-enable-dns-over-https-doh-in-firefox/)

2 or 3 should do. I suggest 3 though(more privacy).

You may need to add `network.trr.uri` too.

**Comment by rusty-snake** [comment]
Duplicate of #1027

**Comment by OraBB1t** [comment]
Ah my bad. Closing.
