### ISSUE TITLE
FYI: GitHub introduced a browser-fingerprinting SHcrIpT they call a "CAPTCHA" by a third-party company

### ISSUE THREAD

**Issue by KOLANICH** [arkenfox/user.js#1134]
`https://github.com/account/organizations/new?coupon=&plan=team_free`

-> `https://octocaptcha.com/?origin_page=github_org_create&responsive=true&require_ack=true`

-> `https://api.funcaptcha.com/fc/api/?onload=loadFunCaptcha`

-> `https://cdn.arkoselabs.com/fc/js/0d89385d25aee2e58dad96e4d3e2a121/standard/funcaptcha_api.js`

1. We need an another forge. I particulary am waiting for a FSF "ethical forge", but it is very likely it won't be launched neither this year, nor the following one.
2. GH privacy policy says
>Device information
>We may collect certain information about your device, such as its IP address, browser or client application information, language preference, operating system and application version, device type and ID, and device model and manufacturer. This information may include User Personal information.

This was introduced in a large and messy commit https://github.com/github/site-policy/commit/a42023fb78e465ae6babef926ac93d34722747d7#diff-2f1b40ad665a8e80ef8b8ce95ae1f73b274bf6e4cc752e9337b96218cfe28404R83 , so it is not very surprising that this was overlooked.

3. But  `Arkose Labs, Inc` is not mentioned in https://github.com/github/site-policy/blob/main/Policies/github-subprocessors-and-cookies.md . It **can** be a violation of GDPR (but I'm not a lawer).

**Comment by Thorin-Oakenpants** [comment]
You do realize you log into github right? And that tens/hundreds of thousands of sites use fingerprinting scripts, including first party. This is nothing new.

**Comment by KOLANICH** [comment]
>You do realize you log into github right? And that tens/hundreds of thousands of sites use fingerprinting scripts, including first party. This is nothing new.

I do realize I log into GH. But this shit wasn't happenning untill quite recent times, i.e. in December 2020 there was no "CAPTCHA" on that page.

**Comment by atomGit** [comment]
this is why i moved my shit to codeberg, because fuck microsoft

**Comment by KOLANICH** [comment]
>i moved my shit to codeberg

Thanks for the info! I'd consider to do the same, though IDK how much I can trust it.

I don't beleive in charity especially in the setting of a tragedy of commons.

Commercial corporations not charging for service, like GH and GL, have sources of income other than selling personal data, and making a platform popular for non-paying users may still be beneficial for platforms: such users are free testers risking own projects, workflows and man-hours, so corporate clients get already well-tested-enough service for a charge.

Well-known orgs without own business making profit, such as FSF, get less trust, if they opened paymentless-for-everyone services. But if they require each user to make something beneficial to them enough to sustain an own service, like be involved in development of a FOSS project from having which not dead they get direct profit in a form of money, they get much more trust.

And even less trust goes to Redrick Schuhart-like services that give services for free to everyone and it is not clear how they make profit from each customer, like gitgud and codeberg and repo.or.cz. 

Paid-only services from companies like SourceHut may be OK, but I feel like it is not OK to pay nonnegligible amount for being able to share anything useful with people.

Also, even how much you pay to them, the service will always have incencetives to behave dishonestly, if the conseqencies for them won't outweight profits from behaving dishonestly. And usually they won't.

So in order to make a company trusted enough, it must proove that behaving dishonestly will not give it more profits than behaving honestly, even if it paid for a third-party threat actor. It is impossible, and even if it was possible, it is not in the best interests of companies to proove that.

I feel like the only solution would be decentralysed services like Radicle, but Radicle is Node.JS and Rust-based, and given the very teaching example of a backdoor in pybitmessage, that noone, including me, have spotted in time, because noone has been actively searching for a backdoor, andeveryone only looked for the things that were needed for them in that case. In a software relying on npm and cargo it would be disaster, they have a lot more deps, than pybm, and noone additionally wants to audit deps and deps of deps and then deps of deps, and thn make own forks of them and then backport updates to them.
