### ISSUE TITLE
Mozilla restrictions

### ISSUE THREAD

**Issue by 2glops** [arkenfox/user.js#1135]
Looking at 2662 and 4503 :

/* 2662: disable webextension restrictions on certain mozilla domains (you also need 4503) [FF60+]
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
   // user_pref("extensions.webextensions.restrictedDomains", "");

/* 4503: disable mozAddonManager Web API [FF57+]
 * [NOTE] To allow extensions to work on AMO, you also need 2662
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true); // [HIDDEN PREF]

So, shouldn't be 2662 active ? 
Or 4503 inactive ?

**Comment by rusty-snake** [comment]
What do you want? If you want to allow extensions access to AMO both are needed IIRC.

**Comment by KOLANICH** [comment]
Both should be active.

**Comment by crssi** [comment]
Both should be inactive.

**Comment by 2glops** [comment]
For me both prefs should be on same state in the user.js, either active or inactive. The later seems more logical.

**Comment by Thorin-Oakenpants** [comment]
They have different functions and are treated as such
- `4503` is a perceived privacy issue: happy to have it active
- `2662` is a security issue, and by default will be off

**Comment by KOLANICH** [comment]
>`2662` is a security issue, and by default will be off

If one doesn't trust the extensions he installs, he shouldn't use them in the first place. If one trusts them, there is no reason to keep `2662` off. And `2662` is also a privacy issue, without privacy-protecting extensions there is no privacy (though someone may argue that there is no privacy in the Web at all and that people wanting privacy should use Gemini or maybe just disconnect a computer from the net, or maybe just throw it into trash, but I don't aggree to such opinions).

**Comment by Thorin-Oakenpants** [comment]
> And `2662` is also a privacy issue

Yes, It is **_also_** a perceived privacy issue.

domains in the current nightly pref
```
accounts-static.cdn.mozilla.net,
accounts.firefox.com,
addons.cdn.mozilla.net,
addons.mozilla.org,api.
accounts.firefox.com,
content.cdn.mozilla.net,
discovery.addons.mozilla.org,
install.mozilla.org,
oauth.accounts.firefox.com,
profile.accounts.firefox.com,
support.mozilla.org,
sync.services.mozilla.com
```

We added this back in v60. We also flipped [DNT to true](https://github.com/arkenfox/user.js/issues/422#issuecomment-392789507)
> we don't clear `extensions.webextensions.restrictedDomains` by default and some mozilla domains use GA but do honor the DNT flag

Content scripts are not allowed on pages that have elevated privileges via mozAddonManager. It's one thing to disable mozAddonManager, but to allow scripts access to oauth, accounts, sync etc **_by default_** is a bad idea. 

**_security_** trumps a perceived privacy gain

At the end of the day, GA on a few Mozilla domains is not a big deal. How many times does a person go to AMO? I'd be lucky if I go there once every three months.

**Comment by KOLANICH** [comment]
>security trumps a perceived privacy gain

What security one can exist when the enemy is already inside?

And if the enemy is not inside, I don't see that privacy gain outweights security one.
