### ISSUE TITLE
InfluxDB 2.0 web UI blank when WebAssembly disabled

### ISSUE THREAD

**Issue by influxdbWebGUI** [arkenfox/user.js#1138]
By default WebAssembly is disabled (`ser_pref("javascript.options.wasm", false);`), but then InfluxDB 2.0 web UI doesn't work and visiting `http://localhost:8086` shows 

```
Uncaught ReferenceError: WebAssembly is not defined
```
in the Web Console. 

If, for security reasons, it's still necessary to disable WebAssembly, then I say leave it disabled.

**Comment by Thorin-Oakenpants** [comment]
yes, disabling wasm will break sites that rely on wasm: good to know there is a clue in the console

**Comment by KOLANICH** [comment]
https://github.com/influxdata/influxdb/issues?q=is%3Aissue+wasm

@influxdbWebGUI, Just go there and create an isse there.
