### ISSUE TITLE
Empty screen space around website content

### ISSUE THREAD

**Issue by boogewooge** [arkenfox/user.js#1141]
Hey,

when using this user.js, the actual website content is enclosed by unused grey space. Apart from the obvious issue of wasted screen real estate, this causes one to have to hunt and peck for the scrollbar instead of being able to just rush the cursor all to the right.

This is on firefox 86.0 and using wayland (fwiw).

See this screenshot (Actual website content is framed red. This is the same for every website):
![userjsscreenspace](https://user-images.githubusercontent.com/56923667/110975057-2ae55c80-8357-11eb-87bc-8db61f5bd8c1.jpg)

Do you have a hunch as to what setting might cause this? If this is not a problem somehow very specialized to my machine, I think it might be worth adding to the override recipes, as this is the only gripe I have with the user.js after using it for a little while.

Cheers!

**Comment by crssi** [comment]
``` js
/* 4504: enable RFP letterboxing [FF67+]
 * Dynamically resizes the inner window by applying margins in stepped ranges [2]
 * If you use the dimension pref, then it will only apply those resolutions. The format is
 * "width1xheight1, width2xheight2, ..." (e.g. "800x600, 1000x1000, 1600x900")
 * [SETUP-WEB] This does NOT require RFP (see 4501) **for now**, so if you're not using 4501, or you are but
 * dislike margins being applied, then flip this pref, keeping in mind that it is effectively fingerprintable
 * [WARNING] The dimension pref is only meant for testing, and we recommend you DO NOT USE it
 * [1] https://bugzilla.mozilla.org/1407366
 * [2] https://hg.mozilla.org/mozilla-central/rev/6d2d7856e468#l2.32 ***/
user_pref("privacy.resistFingerprinting.letterboxing", true); // [HIDDEN PREF]
```

😉

**Comment by rusty-snake** [comment]
> I think it might be worth adding to the override recipes

> Recipe: more than one pref

So it's actually not a recipe candidate (and has a SETUP-WEB).
