### ISSUE TITLE
question: browser.download.useDownloadDir

### ISSUE THREAD

**Issue by crssi** [arkenfox/user.js#1143]
What exactly is a reason for `browser.download.useDownloadDir` to be active and different as is default?
Does this pref not actually qualify for `5000` section?

Thank you and cheers

**Comment by rusty-snake** [comment]
Drive-by-download protection. 

https://github.com/arkenfox/user.js/blob/b7c80841a9c9c886906f8cadfcc28cb97d2e6406/user.js#L1200-L1203

Downloads w/o user interaction are bad, very bad. https://lwn.net/Articles/708196/

**Comment by crssi** [comment]
@rusty-snake this pref has nothing to do with your suggestion.
You still need to confirm downloading and saving or opening of downloaded content.

**Comment by rusty-snake** [comment]
You asked about `browser.download.useDownloadDir`. It's the same pref.

**Comment by rusty-snake** [comment]
> You still need to confirm downloading and saving or opening of downloaded content.

Only if this mime-type is set to "Always ask". If it is set to "Save File", the file is downloaded when you click on a link without interaction.

**Comment by crssi** [comment]
Perfect explanation. Tested now and you are true.

Thank you @rusty-snake ❤️
