### ISSUE TITLE
Your extensions and strategy?

### ISSUE THREAD

**Issue by FriendlyNeighBore** [arkenfox/user.js#1144]
Hello! I am a new user here who recently decided to use arkenfox.
As such, I would appreciate it if you share some extensions and the various strategies (to preserve privacy) that you use, of course it is fine if you don't. 

Thank you all, and I think you guys are doing an excellent job!

**Comment by atomGit** [comment]
* [4.1 Extensions](https://github.com/arkenfox/user.js/wiki/4.1-Extensions)
* [Everything Firefox](https://12bytes.org/articles/tech/firefox/)

**Comment by rusty-snake** [comment]
FWIW: You can find my config at https://gitlab.com/rusty-snake/firefox-config. However, it is clearly a advanced config. You (as a new user) are better off using @atomGit articles. Or even simpler: Install µBlock origin. Then you have the first simple 50% protection.

**Comment by crssi** [comment]
Everyone has it own poison and not everyone agrees with everyone... which is the beauty actually. 😄 
Here is mine https://github.com/crssi/Firefox

**Comment by FriendlyNeighBore** [comment]
Thank you all very much for sharing your configurations. It was very education and helpful for me.
One more question: Are extensions such as FM, GM, VM, and Stylus deemed as a security or privacy threat?

PS: Is the name Arkenfox a reference to LotR or The Hobbit?

**Comment by rusty-snake** [comment]
> Is the name Arkenfox a reference to LotR or The Hobbit?

Strf+F for it in #1009 to find the answer :laughing:

**Comment by atomGit** [comment]
@rusty-snake - are you sure about Stylus not being a privacy (FP) threat? i asked pants about this and i believe he said that anything that modifies the DOM could be used to FP as long as JS is enabled, though i would guess that pretty much no one is looking for this

**Comment by rusty-snake** [comment]
I misunderstood the question. Yes everything like that can be detected. You're absolutely right.
