### ISSUE TITLE
Set `user.js` in Browser Automation

### ISSUE THREAD

**Issue by F1nx** [arkenfox/user.js#1146]
Basically, would it be of any use if I or we composed a short script to move `user.js` into the configuration directory?
If so, I'm thinking either Shell, Python, or compiled JavaScript should be used for the job.

**Comment by Thorin-Oakenpants** [comment]
Why?

**Comment by F1nx** [comment]
To give another inch of helping people to use `user.js`.

**Comment by Thorin-Oakenpants** [comment]
sheesh louise 🤦

why does this need to exist?: as in
- what purpose does moving it serve
- does it solve a problem and if so what is that problem
- what are the benefits of moving it
- what are the downsides to moving it
- how does it work
- who would use it
- who would maintain it
- who would answer any questions about it
- who would add the wiki page
- did you eat a 🥧 on [🥧 Day](https://en.wikipedia.org/wiki/Pi_Day)

Eagerly waiting your answers, trembling wet with anticipation :)

**Comment by Svallinn** [comment]
> Eagerly waiting your answers, trembling wet with anticipation :)
Sounds kinky 😉

**Comment by Thorin-Oakenpants** [comment]
ok, I assume you don't want to answer or make a case. feel free to reopen when you do so
