### ISSUE TITLE
WiFi scanning and geo.provider.network.scan

### ISSUE THREAD

**Issue by xaur** [arkenfox/user.js#1149]
Hi all, I found this pref `geo.provider.network.scan` by accident and wonder if it is something that belongs to user.js?

It is [mentioned](https://searchfox.org/mozilla-central/search?q=geo.provider.network.scan&path=) in one code file and a bunch of tests. In [NetworkGeolocationProvider.jsm](https://searchfox.org/mozilla-central/source/dom/system/NetworkGeolocationProvider.jsm) it has something to do with "wifi scanning" (sounds scary). In FF74 it was [renamed](https://hg.mozilla.org/mozilla-central/rev/261683a6e3511bcfde9afc46ef120a8223041ced) from `geo.wifi.scan`.

I could not find any info on the web or in arkenfox user.js. One mention [here](https://www.wilderssecurity.com/threads/firefox-quiet.375074/page-2) saying it was a hidden pref, a commit to [addon-sdk](https://github.com/mozilla/addon-sdk/commit/138ee8035a8a04ed3e14b91000df9327cd4712f6), pref [disabled](https://github.com/mozilla/geckodriver/commit/2bfdc3ec8151c427a6a75a6ba3ad203459540495) in geckodriver automation testing (labelled as "Do not scan wi-fi") and in the [config](https://gist.github.com/andreastt/dde0749a7f0fa4aea226f617d5b5f0bf) of same person. But nothing describing the feature.

Does anyone know what it does?

**Comment by Thorin-Oakenpants** [comment]
geo is behind a prompt: if you allow geo on a site, then you're accepting that you will be located to some degree of accuracy

https://developers.google.com/maps/documentation/geolocation/overview ... **_EMPHASIS_** mine
> The Geolocation API returns a location and accuracy radius based on information about cell towers **_and WiFi nodes_** that the mobile client can detect. This document describes the protocol used to send this data to the server and to return a response to the client.

That's the google API. We've set the key to use Mozilla's - hah, [this is hilarious](https://bugzilla.mozilla.org/show_bug.cgi?id=1632859#c3)

`geo.enabled` is the master switch. Maybe `geo.wifi.scan`/`the new pref name` is for the nodes bit above? IDK, but sounds legit
