### ISSUE TITLE
Section 5000: restore pinned tabs on demand?

### ISSUE THREAD

**Issue by adrian5** [arkenfox/user.js#1151]
Maybe this would make a good addition to the examples in SECTION [5000]?

```js
user_pref("browser.sessionstore.restore_pinned_tabs_on_demand", true);
```

I don't use pinned tabs anymore but when I did I preferred them not loading all at once when I opening the browser. Granted, by default arkenfox doesn't restore sessions at all, but for those who override that, the above is a setting worth considering.

**Comment by Thorin-Oakenpants** [comment]
We don't start with session restore, as you pointed out, for several reasons
- the session data is written to disk
- loading web content vs extensions on startup - used to be an issue, not sure if it still is: e.g. I think uBO or something would have large'ish stuff to load and there might be a bit of a race - IDK
- the rest of the user.js is geared toward this
   - e.g. clearing cookies (so your login session pages will fail)
   - e.g. session restore data is limited as a fallback
   - history is cleared

SR is not exactly a bad thing: device security is less of a risk/threat and can be mitigated at an OS/OpSec level... as opposed to browsing the web which is more of an app level

but I'm going to decline: I can't add everything
- the above: **_it doesn't fit what we're after_**
- and then there's the inevitable maintenance, questions, bugs, additional complexity with other listed prefs etc
   - [1466440](https://bugzilla.mozilla.org/show_bug.cgi?id=1466440)
   - and that invariably ends up being me = no thanks

**Comment by adrian5** [comment]
Fair enough, that makes sense.

**Comment by Svallinn** [comment]
> loading web content vs extensions on startup - used to be an issue, not sure if it still is: e.g. I think uBO or something would have large'ish stuff to load and there might be a bit of a race - IDK

FYI still somewhat of a race, at least on my old rig
I'm using [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) and if I click a YouTube link outside the browser (which triggers a browser opening), more often than not, I land on the actual website instead of Invidious or FreeTube
