### ISSUE TITLE
OffTopic question: security.enterprise_roots.enabled does not work anymore in FF 87

### ISSUE THREAD

**Issue by crssi** [arkenfox/user.js#1152]
I really struggled to post the question here since it does nothing to do directly with this project.
But I also know here are a lot knowledgeable persons who might have an answer. 

Until now I have used pref `security.enterprise_roots.enabled =  true` to use OS certificate store in Firefox instead of Firefox internal.
It seems that with the latest version, that is v87, this is not working anymore.

Does anyone know the solution?

Thank you in advance and wish you all best... cheers

**Comment by Thorin-Oakenpants** [comment]
FYI: added in FF4 [1265113](https://bugzilla.mozilla.org/1265113)

**Comment by crssi** [comment]
>     * what OS

Windows 10 up-to-date


>     * any other prefs flipped to support this - like auto-import or whatever

not known to me... what fo you mean with auto-import?


>     * does the problem happen in a new profile

sure it does, a plain vanilla - same issue


>     * does it then happen with just that pref (or prefs) changed

not sure I know what you mean 😢 

With this move the Mozilla effectively killed the Firefox usage in the enterprise environments where private certificate authority is in use. 😞 
Users here are massively switching to other browsers ( a few thousands of them).

**Comment by Thorin-Oakenpants** [comment]
> not known to me... what fo you mean with auto-import

Ignore that. It worked with just the one pref change, and now it doesn't - that's all that matters. When I was doing some quick searching, I saw some recent (< 1 yr) tickets (since closed) with this pref and another one that was something like `auto-import`

> > does it happen...

Vanilla FF - fails - expected
Vanilla FF + the single pref change - fails - unexpected

That's what I was asking - just trying to clarify there was nothing else invloved.

You might get more traction/answers just directly filing a ticket under `Core > Security PSM` (that seems like the right component but IANAE)

**Comment by crssi** [comment]
> You might get more traction/answers just directly filing a ticket under `Core > Security PSM` (that seems like the right component but IANAE)

Thank you @Thorin-Oakenpants.
Not sure if I want to spend some more time with the writing a ticket/issue at Mozilla and then waiting for years nothing to happen. I do not believe that those users will come back after a few days being off.

**Comment by Thorin-Oakenpants** [comment]
Well, if you **_do_** report it, then **_at least_** it's there to be hopefully actioned: doing nothing is self-defeating. But sure, if you don't want to at least try and get some clarity, that's your decision.

You make it sound like it's a big bug, and thousands of users leaving (via Enterprise? would Enterprise use ESR and Policies?), so surely someone else must have reported it. IANAE, maybe it's a big regression, or maybe it was planned(?! *shrug*), or maybe it's only your organization, or some weird edge case? IDK

up to you `¯\_(ツ)_/¯` ... Up, Up, Down, Down, Left, Right, Left, Right, B, A, Start

**Comment by crssi** [comment]
^^ All true. Thank you Pants. WIsh you best weekend with a lot of beer and naked dancing singing out loud. ❤️

**Comment by crssi** [comment]
[1701177](https://bugzilla.mozilla.org/show_bug.cgi?id=1701177)

Cheers

**Comment by earthlng** [comment]
maybe this ? ...

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/87#http

> Some enterprise authentication services require that TLS client certificates be sent in CORS preflight requests. Users of these services can enable this (non-specification compliant) behavior using the `network.cors_preflight.allow_client_cert` preference

**Comment by gitthehubs** [comment]
@crssi 
You can always add certificates to Firefox, or use the Firefox group policy object.

Setting Up Certificate Authorities (CAs) in Firefox
https://support.mozilla.org/en-US/kb/setting-certificate-authorities-firefox

Customizing Firefox Using Group Policy (Windows)
https://support.mozilla.org/en-US/kb/customizing-firefox-using-group-policy-windows

Because malware can insert certificates in the windows certificate store it is already advised to import your certificates to Firefox instead of using the windows certificate store.

**Comment by crssi** [comment]
Thank you @gitthehubs and also @earthlng (do not know how could I missed your post)... ❤️ 
Will digest this info in the next days.

The quote from the web site on the first link, that is https://support.mozilla.org/en-US/kb/setting-certificate-authorities-firefox.

> Setting the "security.enterprise_roots.enabled" preference to true in about:config will enable the Windows and MacOS enterprise root support. 

And this doesn't work anymore in FF 87 for some up-to-now unknown reason, at least I haven't found anything about.


> Because malware can insert certificates in the windows certificate store it is already advised to import your certificates to Firefox instead of using the windows certificate store.

When this happens, your computer is already heavily compromised. 😉

**Comment by crssi** [comment]
Dana Keeler responded to bugzilla ticket and she hit the head of the nail with `security.osclientcerts.autoload`.

Thank you and love you guys 👍

**Comment by Thorin-Oakenpants** [comment]
IDK .. sometimes I should just back my instincts more ... I did mention an `auto-import or whatever` pref in my very first reply - shame I closed my FF session and lost my quick research history ... `autoload` it was then. Doesn't explain why you said you didn't need that prior to 87.

**Comment by crssi** [comment]
> Doesn't explain why you said you didn't need that prior to 87.

No it doesn't. Its a mystery to me ATM, but for sure it was mine "shit hits the fan" sort of thing.

**Comment by Thorin-Oakenpants** [comment]
So I hope you learned your lesson - file a bugzilla, and don't be a drama queen with the doom and gloom: just stick to facts and STR etc 👍

**Comment by Thorin-Oakenpants** [comment]
watch... [1696997](https://bugzilla.mozilla.org/show_bug.cgi?id=1696997) enable osclientcerts by default in release

**Comment by crssi** [comment]
Thank you Pants for caring.
