### ISSUE TITLE
Suggest migrate history and bookmarks to clean profile

### ISSUE THREAD

**Issue by Ygarr** [arkenfox/user.js#1153]
Suggest to add if possible script to migrate data(history, bookmarks, addons)from dirty default  to new clear profile with arkenfox-user.js

**Comment by Thorin-Oakenpants** [comment]
No thanks. Migrating extensions is problematic due to extension UUIDs. And other items can also be problematic such as permissions (due to differences in OA keying). This repo is not about how to migrate profiles, sorry

**Comment by crssi** [comment]
@Ygarr  `https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data`
