### ISSUE TITLE
Font is rendered incorrectly

### ISSUE THREAD

**Issue by PrimoDev23** [arkenfox/user.js#1162]
Hey guys,
I am using your user.js since today and I am happy that people do this for free and open source, so thanks to you.

Using the latest Release for Firefox 87.0 is giving me a small font rendering issue on https://replit.com/@AndyNovo/filteredshipwreck

It's expected to show normal font displaying clang version etc.

But it actually just displays colored bars instead of any text.
If I copy the text and paste it, I can read it normally.

![fontrenderedincorrectly](https://user-images.githubusercontent.com/46970398/114057683-4d00ca80-9882-11eb-8339-2a9ef03b635b.jpg)

I have already tried it with a new profile + user.js and with disabled addons aswell. Nothing seems to help.

I hope you guys have a solution to this since it's a bit annoying/ugly. Else everything seems to work great.

**Comment by rusty-snake** [comment]
This is caused by RFP, add a canvas exception in the permissions panel left from the `https://` in the urlbar.

**Comment by crssi** [comment]
Here you go:
![ice_video_20210408-180805_edit_0](https://user-images.githubusercontent.com/17024151/114060639-1b3d3300-9885-11eb-83fd-1a216fcd6db3.gif)

Cheers

**Comment by Just-me-ghacks** [comment]
The pref in question is:
```javascript
user_pref("privacy.resistFingerprinting", true);
```

**Comment by rusty-snake** [comment]
One "colored bars rendered" issue per month this year :tada: :upside_down_face: .

@Thorin-Oakenpants what about an additional point in https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting or in the issue template? _If anyone reads the wiki and the issue template before raising an issue/using the user.js._

```
### 🔸 Add a Canvas Exception

If you just see colored bars, add a canvas exception.

<screenshot>
```

**Comment by PrimoDev23** [comment]
Oh well thanks for the quick help
