### ISSUE TITLE
WebAssembly, any way to better protect against it if enabled?...

### ISSUE THREAD

**Issue by bitpixl** [arkenfox/user.js#1165]
Hi,

I've recently started using "standard notes" as my note taking solution.
The biggest reason for choosing this note taking app is encryption (and cross-platform support (apps and browser)).
By process of elimination (in user.js) I found out that standard notes requires WebAssembly (javascript.options.wasm) to be enabled.

So my question now is, how dangerous is having WebAssembly enabled (using latest Firefox ESR) and can it still be secured in some way using a specific extension? Or is it just a big fat "no no" and should I look for another note taking solution? (thing is, there's very few note taking apps that offer sync & encryption (and have been audited).)

**Comment by bitpixl** [comment]
nvm, I found this topic that answered (most of) my questions: [https://github.com/arkenfox/user.js/issues/1037](url)

**Comment by Thorin-Oakenpants** [comment]
It's on of those things that will get more popular, and everyone's needs will differ. Not familiar with standard notes - I see they have apps for each OS, and there's a web link there. I thought extensions could still use wasm even if it was disabled - is this an extension that interacts with what sites you visit? Can you tell me more?

It's really up to you and your workflow. If you enable wasm (default is true), and you use uBO (probably helps e.g cryptomining) ... it's just a slight security risk .. it more than likely comes down to the meatware, not the software

**Comment by bitpixl** [comment]
I asked the Standard Notes developers (you probably got informed @Thorin-Oakenpants as I linked one of your posts from here) if it would maybe be possible to also provide a web version without webassembly. For completeness sake I'll link that topic here https://github.com/standardnotes/web/issues/541

p.s. hope you don't mind me linking one of your posts.

**Comment by bitpixl** [comment]
> 
> 
> It's on of those things that will get more popular, and everyone's needs will differ. Not familiar with standard notes - I see they have apps for each OS, and there's a web link there. I thought extensions could still use wasm even if it was disabled - is this an extension that interacts with what sites you visit? Can you tell me more?
> 
> It's really up to you and your workflow. If you enable wasm (default is true), and you use uBO (probably helps e.g cryptomining) ... it's just a slight security risk .. it more than likely comes down to the meatware, not the software

Standard Notes is basically a note taking app and they do provide an app for every platform (which is one of the reasons I'm interested in this and them being one of the very few to provide full encryption). The web option is not an extension and luckely doesn't require one. It just logs you into your Notes enviroment from wihtin the browser. 

Without enabling wasm I don't get past the logon screen, it shows the message "generating keys" while trying to login.
I found out it was wasm by using a clean profile, no extensions and just the user.js. Then by process of elimination it turned out to be option 2422 "javascript.options.wasm".

uBO is a must these days and I'm also using most of the extensions from the 'recommended extensions'. 
Wasm seems to be growing in popularity and at one point we probably can't get around it anymore.

**Comment by Thorin-Oakenpants** [comment]
Ahh, OK, so it's the website itself (not an extension).. or to be more precise, the authentication module. Got it! :). For the crypto my initial thought would be that allowing an alternative is unwanted overhead and risk.

Guess it's up to you. Enable wasm: 99.99% of users won't ever get bitten: I would think you're a careful/savey internet user and could spot cryptomining happening: your fans would go wild and your and CPU would heat up. Not that all malicious wasm code has to be cryptomining. Your choice ;)
