### ISSUE TITLE
Lost all open tabs

### ISSUE THREAD

**Issue by vgivanovic** [arkenfox/user.js#1166]
I lost all my open tabs. Not critical, but they represented a portion of what I wanted to remember. I don't think the docs mention this.

**Comment by Thorin-Oakenpants** [comment]
Sorry about that. I know people should not rely on session restore as some kind of backup (and you're not: but some people do), but that is annoying

I've added the following to the [wiki](https://github.com/arkenfox/user.js/wiki/1.3-Implementation#small_orange_diamond-at-a-bare-minimum) under the `❗ ULTRA UBER IMPORTANT: Pay attention!` section

> - We disable session restore (0102)
>   * :star: If you rely on session restore you had better change this

**Comment by Thorin-Oakenpants** [comment]
^ would seem a bit silly not to also tag it
