### ISSUE TITLE
pdfjs.enableScripting in FF88+

### ISSUE THREAD

**Issue by majewsky** [arkenfox/user.js#1167]
The [release notes for Firefox 88.0](https://www.mozilla.org/en-US/firefox/88.0/releasenotes/) mention that JavaScript embedded in PDFs is now evaluated by default. And indeed, whereas the `pdfjs.enableScripting` config option was set to default false before, it's now set to default true on 88 (at least on my system). Setting it to explicit false may be in scope for this user.js for hardening purposes.

**Comment by KOLANICH** [comment]
One should be either mad or malicious to introduce this not-well-adopted yet antifeature (and this way increasing its adoption and power of malicious actors to blackmail users into not using PDF viewers where it is disabled) and especially have it enabled by default.

**Comment by Thorin-Oakenpants** [comment]
it'll be handled in #1164
