### ISSUE TITLE
System add-ons and pre-installed search extensions

### ISSUE THREAD

**Issue by Gitoffthelawn** [arkenfox/user.js#1170]
Hi all.  It's been a while since I dropped by.  Hope you all are doing well.  `user.js` is looking incredible.  Great job!

Section 0500 mentions system add-ons.  It states that you can manually remove them.  You may want to mention "by deleting the corresponding XPI file".  AFAIK, that's the only way to *remove* them (is that correct?).

There are a few websites that claim you can *disable* them.  ***Can they be disabled (vs. removed), or is this wishful internet fiction?***

Item 0308 briefly mentions "built-in or Web Extension search engines", but goes no further.  These, of course, include privacy-concerning sites like Google, Yahoo, and Amazon.  These can be pseudo-disabled via clicking on `Remove` in `about:preferences#search`, but from what I can tell, doing this:

1. Does not actually remove the corresponding XPI files.
2. Does not even prevent the corresponding XPI files from being loaded (unlike normal extensions).  Disabling a normal extension causes the XPI file to remain, but not get loaded.  "Removing" a pre-installed search extension (such as Google) neither removes the XPI file nor prevents it from being loaded by Firefox.

***Can anything more be done about these pre-installed search extensions?***

Either if "yes" or "no", adding a little more detail about them in user.js may be helpful.

**Comment by rusty-snake** [comment]
They don't harm if you don't use them, look at their source: resource:///chrome/browser/search-extensions/google/manifest.json

Anyway, with [mozlz4-edit](https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/) ([arkenfox wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#small_orange_diamond-extensions-tools)) you can edit `search.json.mozlz4`. However

> **Warning!** You should not delete *default* search engines from a `search.json.mozlz4` file if you edit the file. If you delete a default search engine then the Firefox will **reset** search engine list to a **default** state. But you can add new search engines.
Maybe there is another way to delete default search engines except Firefox Preferences menu but I don't know how.

**Comment by Thorin-Oakenpants** [comment]
The only bundled system addons are
- DoH rollout: so far only USA and I think might have been the UK. I am not sure how they determine country for rollout (language, build, locale, region check), and not too concerned: you get prompted AFAIK. Nothing to worry about here
- formautofill: we disable it: this is the credit cards, addresses etc: they have only rolled this out to a few regions (due to complexities and variations in how all this works, I assume). Nothing to worry about
- screenshots: does nothing except take local screenshots: there is no upload to cloud or anything
- webcompat reporter: is disabled by default, and enforced in the user.js (because submitting a compat issue to Mozilla when we flip approx 200 prefs is a bit stupid and a waste of everyone's time). Nothing can happen anyway unless the use chooses to click "Report Site Issue"

If anything, I should remove the information that suggests deleting the files, as none of them pose any risk

---

As for built in search engines, they do nothing if you disable them. Modifying files to remove them etc is beyond the scope of the project

**Comment by atomGit** [comment]
hi @Gitoffthelawn - personally i remove ALL of them - i've seen enough of Moz's unethical behavior (imo) in the past regarding system extensions and experiments to allow them to remain

you didn't mention your OS but i assume dumping them on Windows is easy enough - on *nix, you could look for them at: `/usr/lib/firefox/browser/features` and to remove them, open a terminal there and `sudo rm *.xpi`

@Thorin-Oakenpants - on Linux the packaged sys add-ons are:

```
doh-rollout@mozilla.org.xpi
formautofill@mozilla.org.xpi
pictureinpicture@mozilla.org.xpi
screenshots@mozilla.org.xpi
webcompat-reporter@mozilla.org.xpi
webcompat@mozilla.org.xpi
```

i think the pictureinpicture one is fairly new

**Comment by Gitoffthelawn** [comment]
@rusty-snake Thanks for the details, including the important caveat.  I try to keep things as lean as possible.  Although they cause no harm, I prefer not to load code that isn't needed.

@Thorin-Oakenpants Although they cause no harm, they do take time/resources to load and keep in memory.  Also, although these current ones may all be safe, IIRC Mozilla has a checkered history regarding their choices of forced extensions.  Since `arkenfox user.js` (what's an *arkenfox*?) isn't rolled out instantly for every new FF release, I think it's good that you've been informing people how to deal with ones that aren't covered.  Plus, I think Mozilla pushes different ones to different regions, so what one person sees may be different from what another user sees.

@atomGit Hi! Thanks for the info.  I primarily use Linux and Windows these days.  Do you manually delete those files each time there is a FF update?  Not hard to do or anything... just need to remember to do it.  Or do you automate it?  Also, do you do anything special for the unneeded/unwanted pre-installed search engines?

**Comment by atomGit** [comment]
yes, i manually them after each update and no, i haven't yet automated it

re: the search plugs, i just don't use them - if you delete them FF will recreate them - i make sanitized copies - see: [Firefox Search Engine Cautions, Recommendations](https://12bytes.org/articles/tech/firefox/firefox-search-engine-cautions-and-recommendations/)

this may also interest you: [The Mozilla Monster](https://12bytes.org/articles/tech/the-mozilla-monster/)
