### ISSUE TITLE
please submit: tiny webgl test to help mozilla and RFP

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1171]
Go to test page, **_follow instructions_**, submit data
- TEST: https://ritter.vg/misc/rendering/index.php

Note: I just used a vanilla profile: arkenfox does flip a few wbgl things

Thanks 🍻 and 🍕 

Edit: Tom Ritter is a Mozilla security engineer, works on Tor Uplift (when it's active) and is a long time Tor Project contributor etc .. in case you were wondering about the domain

**Comment by tomrittervg** [comment]
Thanks all!  We've gotten a few responses and it's shown us that we are not there yet unfortunately. We're going to take a look at the data and see how to move forward.  This is all happening in a few people's very limited free time so please don't be upset by slow progress :)

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg Out of interest .. does webGL ship the same math library for all platforms?

Closing. If you ever need a plethora of tests, don't hesitate to ask here

**Comment by crssi** [comment]
@tomrittervg Sorry, I missed this one. Do you need some more? That is mine too.

**Comment by tomrittervg** [comment]
> @tomrittervg Sorry, I missed this one. Do you need some more? That is mine too.

No worries; we're set for now!
