### ISSUE TITLE
FYI: dom.enable_performance = false = AliExpress breakage

### ISSUE THREAD

**Issue by Just-me-ghacks** [arkenfox/user.js#1172]
Internal pages in AliExpress are broken with `user_pref("dom.enable_performance", false);`

test: https://www.aliexpress.com/item/1005002571624344.html

I don't use resistFingerprinting.

**Comment by Thorin-Oakenpants** [comment]
confirmed in a new profile (well, almost new) with just `user_pref("dom.enable_performance", false);`
works with just RFP (also pref is default true in TB)

section 4600 doesn't get a lot of attention :)

```js
   // user_pref("dom.maxHardwareConcurrency", 2);
user_pref("dom.enable_resource_timing", false);
user_pref("dom.enable_performance", false);
   // user_pref("device.sensors.enabled", false);
user_pref("browser.zoom.siteSpecific", false);
   // user_pref("dom.gamepad.enabled", false);
user_pref("dom.netinfo.enabled", false); // [DEFAULT: true on Android]
user_pref("media.webspeech.synth.enabled", false);
user_pref("media.video_stats.enabled", false);
   // user_pref("dom.w3c_touch_events.enabled", 0);
user_pref("media.ondevicechange.enabled", false);
user_pref("webgl.enable-debug-renderer-info", false);
user_pref("ui.prefersReducedMotion", 0); // [HIDDEN PREF]
user_pref("dom.w3c_pointer_events.enabled", false);
user_pref("ui.systemUsesDarkTheme", 0); // [HIDDEN PREF]
user_pref("layout.css.font-visibility.level", 1);
```

hardwareConcurrency as inactive seems out of place, I don't see that as breaking anything: maybe we made it inactive when RFP covered it, but never adjusted it when we made 4600

Looking at the uptodate https://www.w3.org/TR/navigation-timing/#privacy and the security section under that
- note: timing (including RFP) can be bypassed, so this is more about the API
- if RFP (which is for Tor Browser, and I have no idea of some of those concerns aren't mitigated by using Tor) doesn't block it, then I fail to see what this pref ultimately achieves (other than to make it harder) given the threat model and a determined attacker
