### ISSUE TITLE
[Question] [Help] [Troubleshoot] How to install it on Linux Mint?

### ISSUE THREAD

**Issue by mistless** [arkenfox/user.js#1177]
Hi to all! This looks very interesting.
To be honest, I am new to Linux.
And I would like to know if you know how I should apply it in Firefox on my Linux distribution.
Thank you.
Browser: Mozilla Firefox 88.0.1 (64 bit)
OS: Linux Mint 20.1

**Comment by rusty-snake** [comment]
Everything explained in the [wiki](https://github.com/arkenfox/user.js/wiki).

https://github.com/arkenfox/user.js/wiki/3.3-Updater-Scripts#small_orange_diamond-maclinux

**Comment by mistless** [comment]
Well, thanks anyway.

I'll catch it later.

What happens at least with me, is that since I do not know how to handle Linux yet. I don't know what folder to put the files in.

In addition you should know that not all people have an advanced level in all subjects.

Regards.

**Comment by rusty-snake** [comment]
> I don't know what folder to put the files in.

> To find your profile directory, go to `about:profiles` (note: this does work with portable Firefox). This will list all profiles, so make sure to select the one that is marked as the profile in use. You will see an Open Folder button which you can click.

<sup>src: https://github.com/arkenfox/user.js/wiki/1.2-Backing-Up</sup>

> Firefox also allows configuration for a profile via a user.js file: user.js kept in the profile folder, usually `~/.mozilla/firefox/xxxxxxxx.default/`.

<sup>src: https://wiki.archlinux.org/title/firefox#Configuration</sup>
