### ISSUE TITLE
trouble getting custom icons on firefox home to work

### ISSUE THREAD

**Issue by TPO100Cofficial** [arkenfox/user.js#1181]
i'm aware! firefox's home page isn't very safe, but i can't help it. i like it!
i'd like to use custom icons on the shortcuts in the page, but they don't seem to load.
![image](https://user-images.githubusercontent.com/33667869/120497781-383a4200-c3ae-11eb-856d-2fc936587b9c.png)
what should i change in my user.js in order to allow these images to load? would it have a collateral effect of interfering with other safety measures, like allowing other websites to load 3rd party cookies or similar?

**Comment by Thorin-Oakenpants** [comment]
> i'm aware! firefox's home page isn't very safe, but i can't help it. i like it

Firefox's home page is safe. There is nothing insecure about it. If you mean from a privacy standpoint, there are no issues there either: top stories, top sites (from history), suggested pocket reads, etc are all curated locally, and users can tweak what is displayed via `Home>Personalize>`

hacking activity stream to use custom icons is not what this repo is about
