### ISSUE TITLE
gfx.e10s.font-list.shared

### ISSUE THREAD

**Issue by gitdine** [arkenfox/user.js#1183]
`gfx.e10s.font-list.shared`, which was flipped by default on in FF89, appears to break RFP's anti-font fingerprinting, at least according to EFF's test.

Run the test at:
https://coveryourtracks.eff.org/
And scroll down to the System Fonts section.

For me on FF89 it shows a high level of entropy at 13.92 bits of identifying information in fonts and tells me I have a unique FP. But when I turn off `gfx.e10s.font-list.shared` and run the test again it shows 3.65 bits, which was in line with what I got pre-FF89 when the pref was off.

**Comment by Thorin-Oakenpants** [comment]
what makes you think the font test at EFF is reliable or that their entropy is anything real world?

**Comment by Thorin-Oakenpants** [comment]
Here is RFP with and without gfx.e10s.font-list.shared, on Windows 7
- e6f016b045892fa56d630cbcd60dd71bd56c6efd 68 fonts
- 89d55cf654c36b79a9ac3e614bb004481440a1ba 64 fonts
   - fonts no longer detected: `宋体`, `微软雅黑`, `ＭＳ ゴシック`, `ＭＳ Ｐゴシック`

windows fonts in TZP list
`宋体`,`微软雅黑`,`新細明體`,`細明體`,`굴림`,`굴림체`,`바탕`,`ＭＳ ゴシック`,`ＭＳ 明朝`,`ＭＳ Ｐゴシック`,`ＭＳ Ｐ明朝`

`宋体` = SimSun
`微软雅黑` = Microsoft YaHei
`ＭＳ ゴシック` = MS Gothic
`ＭＳ Ｐゴシック` = MS PGothic
etc - I'm not a font expert, but AFAIK there are just aliases

If you look at the [Win10 list](https://searchfox.org/mozilla-central/search?path=StandardFonts*.inc) you will see SimSun, Microsft YaHei, MS Gothic, MS PGothic are already in base fonts

The RFP font protection is not broken. Everyone is still the same. The EFF test is not real world. Using entropy figures from EFF and like sites is what is broken

**Comment by Thorin-Oakenpants** [comment]
Interesting ... https://bugzilla.mozilla.org/show_bug.cgi?id=1714543
