### ISSUE TITLE
Instagram videos won't play [solved: 1603: network.http.referer.XOriginPolicy]

### ISSUE THREAD

**Issue by eleius** [arkenfox/user.js#1184]
I've been using the arkenfox user.js for months, and I was able to see instagram videos by clicking on them (as autoplay is disabled). Now, nothing happens.

I'm using Firefox 89.0 64-bit on Linux. Just to be sure it wasn't an addon issue, I created a new Firefox profile and was able to see the videos. Then I closed Firefox, added the current arkenfox user.js and videos stopped working.

I searched for "instagram" in the user.js and in the github issues but didn't find anything relevant.

**Comment by rusty-snake** [comment]
Did you try that?

https://github.com/arkenfox/user.js/blob/b6d7b2bff53b1a87b8bfdbb28ba0c019eadadfbb/user.js#L932

**Comment by eleius** [comment]
Just tried it, but it doesn't seem to work. I guess the issues is not with autoplay.

**Comment by rusty-snake** [comment]
Hmm, you can [troubleshoot](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting) this but I don't have any specific idea nor can I really test this (without account).

**Comment by Thorin-Oakenpants** [comment]
I can't test either if it requires an account. But I'm confused

> I've been using the arkenfox user.js for months, and I was able to see instagram videos by clicking on them (as autoplay is disabled). Now, nothing happens.

If you've been using the user.js for months and it worked .. well, we haven't done anything different as such ... so did the problem happen when you updated to 89? Is there something blocking it in the blue ETP shield?

**Comment by eleius** [comment]
> so did the problem happen when you updated to 89? Is there something blocking it in the blue ETP shield?

I think it started a few weeks before 89. As for settings, Autoplay was set on "Block audio and video", but changing to Allow doesn't make any difference. Also, Enhanced tracking protection was enabled, tried disabling it, no difference.

> when you click to play, are there any messages in the console?

I tested with and without user.js, no particular message in the console even if I click one of those videos.

I noticed the problem happens for Instagram videos that have the "play" (triangle) icon, but there are also other videos with the "tv" icon (don't know what they're called) and those work fine.

Also, if I use https://www.picuki.com (an online instagram viewer that doesn't require an account) I can see those videos. So maybe Instagram just changed their player code?

**Comment by Thorin-Oakenpants** [comment]
sounds like something changed on their end (and reflects in the user.js), and the only way to find the pref culprit(s) is to troubleshoot - using a binary method works well: using your vanilla profile, add half the user.js .. test, if it works, add the next quarter .. etc

There's only going to be so many likely culprits
- ETP: just test disabling off for that site + reload (which you tried)
- autoplay settings: try an exception (which you tried)
- 1603+1604 is common for causing third party blocks: IDK what the source of the vid is (3rd party cdn or what?)
- video: DRM (you should have seen a DRM prompt, so I don't think this is it)
- RFP: you never know (and canvas icon in the urlbar, try allowing a RFP canvas site exception)
- 2302: service worker?

**Comment by eleius** [comment]
> 1603+1604 is common for causing third party blocks: IDK what the source of the vid is (3rd party cdn or what?)

Found it! XOriginPolicy must be 0 (not 2, not 1), then it works. It doesn't seem to care about 1604.

**Comment by Thorin-Oakenpants** [comment]
thanks for testing and getting the exact cause.
- we changed 1603 +1604 in [v84](https://github.com/arkenfox/user.js/issues/1088), see #1077


added it as a specific item to check in the readme header
```
       * While not 100% definitive, search for "[SETUP" tags
         e.g. third party images/videos not loading on some sites? check 1603
```

and [wiki](https://github.com/arkenfox/user.js/wiki/1.3-Implementation)
> We hardened cross origin referers (1603, 1604)
>
> - :star: This may cause breakage where third party images and videos may not load
> -  Change to suit and consider installing an extension

anyway, I added instagram in the user.js so at least searching for it shows up .. can't hurt
