### ISSUE TITLE
[Question] Beta or Nightly Firefox builds?

### ISSUE THREAD

**Issue by TheCultLeader666** [arkenfox/user.js#1186]
Is it not recommended to use the user.js with the beta or nightly builds of Firefox? I notice that user.js releases correspond with Firefox releases, so I was wondering if there were any security/privacy concerns with using the user.js with unstable channels.

**Comment by rusty-snake** [comment]
#901

**Comment by TommieWong** [comment]
I'm wondering the same thing, but I don't understand @rusty-snake's answer. Could you clarify, please?
