### ISSUE TITLE
Compare function in updater tool removes somes prefs

### ISSUE THREAD

**Issue by Onfroygmx** [arkenfox/user.js#1188]
Hello,

File concerned:
updater.sh
Not tested with the updater.bat file

I had some issues migrating from an old user.js to a new one because when using the diff tool, I had some differences but when looking in your user.js file they were present.

After some digging, here is the result:
All prefs after a multi-line comment declaration, on a single line, are deleted with the remove_comments function from the updater.
Some lines with comments, within multi-line comments are deleted

example:
/* 0105a: disable Activity Stream telemetry ***/
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);

remove_comments function from the updater:
`sed -e 's/^[[:space:]]*\/\/.*$//' -e '/^\/\*/,/\*\//d' -e '/^[[:space:]]*$/d' -e 's/);[[:space:]]*\/\/.*/);/' userjs-arkenfox.js | sed '/^user_pref("_user.js.parrot"/d' | sort > userjs-arkenfox-updater.txt`
[userjs-arkenfox-updater.txt](https://github.com/arkenfox/user.js/files/6604103/userjs-arkenfox-updater.txt)
Count: 175 lines

My test output:
`cat userjs-arkenfox.js | grep "^user_pref*" | sed '/^user_pref("_user.js.parrot"/d' | sort > userjs-arkenfox-test.txt`
[userjs-arkenfox-test.txt](https://github.com/arkenfox/user.js/files/6604104/userjs-arkenfox-test.txt)
Count: 234 lines

Another test output:
cc -undef -E -P -xc userjs-arkenfox.js | sed '/^user_pref("_user.js.parrot"/d' | sed '/^$/d' | sort > userjs-arkenfox-cc.txt
[userjs-arkenfox-cc.txt](https://github.com/arkenfox/user.js/files/6604110/userjs-arkenfox-cc.txt)
Count: 210 lines

This makes the comparison between files not reliable because there are lines stripped from your file as well as from the user file.
I don't have the perfect solution yet, but maybe a warning for the users for next update could be useful.
I can help do some extra tests if needed.

Onf
#1173

**Comment by earthlng** [comment]
Hi, yeah that's a problem, thanks for reporting it.

I found a relatively simple solution that produces the same output as the cc command, except that it misses the last user_pref.
IDK why it misses the last one but since that's always a parrot pref in the user.js it's not that bad but could still be problematic for user-overrides. But compared to the current command it's still much better and the best I can do ATM.

new:
```js
remove_comments () { # expects 2 arguments: from-file and to-file
  sed -e 's/^[[:space:]]*\/\/.*$//' -e '/^\/\*.\+\*\/[[:space:]]*$/d' -e '/^\/\*/,/\*\/$/d' -e '/^[[:space:]]*$/d' -e 's/);[[:space:]]*\/\/.*/);/' "$1" > "$2"
}
```

**Comment by Onfroygmx** [comment]
Hi,

Thanks for tackling it.
Unfortunately this brings another/new issue.

The previous command was compatible Mac and Linux (giving the same wrong result).
Now on Linux which uses gnu sed, the behavior is the one you describe, same as cc (which  seems the correct one).
But on Mac which uses by default the bsd sed function it still gives the same result as previously ( workaround possible by installing/using the gnu sed function on mac).

`sed -e 's/^[[:space:]]*\/\/.*$//' -e '/^\/\*.\+\*\/[[:space:]]*$/d' -e '/^\/\*/,/\*\//d' -e '/^[[:space:]]*$/d' -e 's/);[[:space:]]*\/\/.*/);/'  userjs-arkenfox.js | sed '/^user_pref("_user.js.parrot"/d' | sort > userjs-arkenfox-newsed.txt`
[userjs-arkenfox-newsed.txt](https://github.com/arkenfox/user.js/files/6604683/userjs-arkenfox-newsed.txt)

gsed -e 's/^[[:space:]]*\/\/.*$//' -e '/^\/\*.\+\*\/[[:space:]]*$/d' -e '/^\/\*/,/\*\//d' -e '/^[[:space:]]*$/d' -e 's/);[[:space:]]*\/\/.*/);/'  userjs-arkenfox.js | sed '/^user_pref("_user.js.parrot"/d' | sort > `userjs-arkenfox-newgsed.txt`
[userjs-arkenfox-newgsed.txt](https://github.com/arkenfox/user.js/files/6604686/userjs-arkenfox-newgsed.txt)

**Comment by icpantsparti** [comment]
Hi.
@earthlng, further to your fix, re-arranging the statement seems to address the loosing stuff off the end.  (moved the first match to third place). @Onfroygmx, does changing the `.\+` to `.*` resolve?

`sed -e '/^\/\*.*\*\/[[:space:]]*$/d' -e '/^\/\*/,/\*\//d' -e 's/^[[:space:]]*\/\/.*$//' -e '/^[[:space:]]*$/d' -e 's/);[[:space:]]*\/\/.*/);/' "$1" > "$2"`

@Onfroygmx FYI some comparers:
https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html?box=a
https://github.com/claustromaniac/Compare-UserJS

**Comment by Onfroygmx** [comment]
Just did the test with the new sed:
[userjs-arkenfox-new_newsed.txt](https://github.com/arkenfox/user.js/files/6604849/userjs-arkenfox-new_newsed.txt)
[userjs-arkenfox-new_newgsed.txt](https://github.com/arkenfox/user.js/files/6604851/userjs-arkenfox-new_newgsed.txt)

Both results are OK and the same now.

Thanks for the links. 
I already had done that a long time ago and had not updated my scripts for a while (I'm coming from your pre-github version). 
I'm trying to autoupdate/backup all my security configs on a regular basis ( FF, blocklists, dnscrypt, ...)

**Comment by earthlng** [comment]
Hey, thanks for testing again and reporting back. I didn't expect sed on mac to be different from other nixes.

> Both results are OK and the same now.

so it works on Mac with `.*` instead of `.\+` ie the line posted by @icpantsparti ?

> re-arranging the statement seems to address the loosing stuff off the end

Thanks @icpantsparti for pointing that out. That helped me understand why it removed the stuff at the end:
the 1st pattern removed the last line of our special 9999 block which is formatted in such a way that it can be enabled/disabled and still be valid syntax (ie the `// ***/`). Without that line it's an unterminated multi-line comment and everything at the end gets removed.

I'll fix it right away. Thanks for your help, guys, much appreciated!

**Comment by Onfroygmx** [comment]
Sorry, if I was not clear.
Yes it works with both bsd and gnu sed, with the commands of @icpantsparti and the commit you made.
`sed -e '/^\/\*.*\*\/[[:space:]]*$/d' -e '/^\/\*/,/\*\//d' -e 's|^[[:space:]]*//.*$||' -e '/^[[:space:]]*$/d' -e 's|);[[:space:]]*//.*|);|' userjs-arkenfox.js | sed '/^user_pref("_user.js.parrot"/d' | sort`
and
`gsed -e '/^\/\*.*\*\/[[:space:]]*$/d' -e '/^\/\*/,/\*\//d' -e 's|^[[:space:]]*//.*$||' -e '/^[[:space:]]*$/d' -e 's|);[[:space:]]*//.*|);|' userjs-arkenfox.js | gsed '/^user_pref("_user.js.parrot"/d' | sort`

Thanks for the quick replies and fixes.

**Comment by earthlng** [comment]
hey, no need to apologize, I was pretty sure that's what you meant but just wanted to double-check before closing the issue.

> Thanks for the quick replies and fixes.

np, thank you for finding this bug and reporting it. And thanks for posting the `cc` cmd, that was very helpful!

**Comment by rprimus** [comment]
Tue Jun  8 06:34:35 BST 2021

> cc -undef -E -P -xc userjs-arkenfox.js 

Where can I find more info on the  `cc`  cmd?  Is it the `gcc` compiler?

**Comment by rusty-snake** [comment]
> `cc` command […] stands for C Compiler, usually an alias command [symlink] to gcc or clang. As the name suggests, executing the cc command will usually call the gcc on [GNU/]Linux systems. It is used to compile the C language codes and create executables.

<sup>src: https://www.geeksforgeeks.org/cc-command-in-linux-with-examples/</sup>
