### ISSUE TITLE
Browser not allowing toggling light/dark theme in developer tools

### ISSUE THREAD

**Issue by vatonbero** [arkenfox/user.js#1193]
Hi all,

I cannot determine what to white-list and override to make Firefox allow me toggling light/dark color scheme on website, using developer tools. It uses css `prefers-color-scheme` but there is only one entry in the user.js mentioning this (#`4617`) and i really do not know where to start.

I have searched what i could in the user.js and yet nothing allows me to enable this behavior. I have tried a new profile without arkenfox user.js and it works as intended so it is definetely related to it.

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/12c063190098b6a62e0671db0f704939678811eb/user.js#L1450
https://github.com/arkenfox/user.js/blob/12c063190098b6a62e0671db0f704939678811eb/user.js#L1465

**Comment by vatonbero** [comment]
Hi there,

Not sure why is this closed already since i provided no input.

> https://github.com/arkenfox/user.js/blob/12c063190098b6a62e0671db0f704939678811eb/user.js#L1450
> 
Not really solving the issue because it fixes the value? It states the following:

> // 0=light, 1=dark : This overrides your OS value
I would like to avoid overriding anything and let Firefox change this dynamically. And no, this is not fixing the issue in dev mode

> 
> https://github.com/arkenfox/user.js/blob/12c063190098b6a62e0671db0f704939678811eb/user.js#L1465

Not allowing me to toggle color scheme in Firefox even after setting this to `false`

Just to make sure that i am asking this right, here is what i need:

- Open "Inspect mode" (F12 or select "Inspect this element" anywhere on any page)
- Click on "Inspector"
- Click on toggle buttons for color simulation: 
![ff-dev-tools](https://user-images.githubusercontent.com/59034981/122668484-8a55d280-d1b8-11eb-8c3a-c47c65dbeb1a.jpeg)

**Comment by Thorin-Oakenpants** [comment]
Since FF67, RFP (`privacy.resistFingerprinting`) when enabled, will always return `light`
```
 1494034 - return "light" with prefers-color-scheme (see 4618) (FF67+)
```

So your first step is to make sure RFP is false. Each to their own, but if you're doing development work, then why are you using a heavily modified profile?

---

```
// 4618: enforce prefers-color-scheme as light [FF67+]
   // 0=light, 1=dark : This overrides your OS value
user_pref("ui.systemUsesDarkTheme", 0); // [HIDDEN PREF]
```

This pref is **_not used_** by default as all of section 4600 is commented out, and is an alternative way to enforce light (or dark) for content (and it also changes the chrome)

RFP does not respect this value, RFP will still return light to web content.

So
- delete `ui.systemUsesDarkTheme` in about config
- reset RFP in about:config
- reload your webpage, reopen dev tools

**Comment by rusty-snake** [comment]
> > [user.js/user.js](https://github.com/arkenfox/user.js/blob/12c063190098b6a62e0671db0f704939678811eb/user.js#L1465)
> 
> Not allowing me to toggle color scheme in Firefox even after setting this to `false`

1. Set `privacy.resistFingerprinting=false` on `about:config`
2. Go to https://browserleaks.com/css
3. Open inspector
4. Click simulate dark/light
5. See how `prefers-color-scheme` is changing between `light` and `dark` (JS allowed)

**Comment by vatonbero** [comment]
Guys,

Thank you for this. I learned something today. It works now (resetting `privacy.resistFingerprinting` and then setting it to `false` in user-overrides.js) and it works now. I have reset both parameters in about:config mentioned in this report as @Thorin-Oakenpants suggested.

If it means anything @Thorin-Oakenpants ,I never really had to change anything in this user.js implementation and i was able to debug many websites without issues. I mostly use it for front end thus there is a (very strong) possibility that I am missing advanced features. This css trick for light/dark schemes is not so old to be frank so i expected a few quirks here and there.

@rusty-snake thank you for that awesome website, will keep it bookmarked from now on!

Thanks again.
