### ISSUE TITLE
Add security.ssl3.rsa_aes_256_gcm_sha384 and security.ssl3.rsa_aes_128_gcm_sha256 to 1264

### ISSUE THREAD

**Issue by LStandman** [arkenfox/user.js#1196]
Hi,
First things first, I heeded the warnings about meddling with my cipher-suite.

_However_, 1261 and 1264 are there for a reason. I believe 1264 is missing security.ssl3.rsa_aes_256_gcm_sha384 and security.ssl3.rsa_aes_128_gcm_sha256, which were hidden prefs up to firefox 80:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1641356
* https://hg.mozilla.org/integration/autoland/rev/cf748096e59f

According to https://browserleaks.com/ssl, these ciphers do not offer PFS.

For your consideration.
Thanks,
LS

**Comment by Thorin-Oakenpants** [comment]
Thanks. Seems reasonable to me to add them to the list in 1264 for the info factor - thanks for the bugzilla link

- so added in FF78 : [1638369](https://bugzilla.mozilla.org/show_bug.cgi?id=1638369) which fits nicely with the description in 1264 `as of FF78... `
- your linked bugzilla 1641356: added to all.js and thus no longer hidden in FF80
   -  I think we can just ignore the hidden info for ESR78-FF79, unless we add `[HIDDEN in FF78-79]`, but then we just end up cleaning it up after ESR78 goes EOL ~~in about three months~~ sometime after 2021-10-05 when we move to v94-alpha - I can do without the maintenance TBH

using the SSL test, and keeping with `in order of preferred by FF`, here are the non-good ones: the top 8 are 1264 (with the two new ones) and the last one is 1263

```
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA  // user_pref("security.ssl3.ecdhe_ecdsa_aes_256_sha", false);
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA  // user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA    // user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA    // user_pref("security.ssl3.ecdhe_rsa_aes_256_sha", false);
TLS_RSA_WITH_AES_128_GCM_SHA256       // user_pref("security.ssl3.rsa_aes_128_gcm_sha256", false); // no PFS  <-- new
TLS_RSA_WITH_AES_256_GCM_SHA384       // user_pref("security.ssl3.rsa_aes_256_gcm_sha384", false); // no PFS  <-- new
TLS_RSA_WITH_AES_128_CBC_SHA          // user_pref("security.ssl3.rsa_aes_128_sha", false); // no PFS
TLS_RSA_WITH_AES_256_CBC_SHA          // user_pref("security.ssl3.rsa_aes_256_sha", false); // no PFS
TLS_RSA_WITH_3DES_EDE_CBC_SHA         // user_pref("security.ssl3.rsa_des_ede3_sha", false); <-- 1263
```

I'll do a PR for @earthlng

**Comment by Thorin-Oakenpants** [comment]
> However, 1261 and 1264 are there for a reason

That reason being to tell people NOT TO MESS WITH THEM :) ... and they also get reset with prefs cleaner
