### ISSUE TITLE
Firefox restore google like default search engine

### ISSUE THREAD

**Issue by AramatZ** [arkenfox/user.js#1198]
Guys remember a few years ago you advised to sanitize search.json.mozlz4. I followed your advice and has enjoyed a cleaned version of my "GoogleSan" for many years. But already three versions in a row Firefox restores Google like default search engine and I have to go to the settings each time when make clean browser install and delete this engine because it overrides my "GoogleSan". Sometimes I forget to do this and it is very annoying.
 Can you suggest any pref for user.js to stop it or it's hard written in omni.ja? I know that mozilla make money in this way, but it is very annoying when overrides my browser settings.

**Comment by rusty-snake** [comment]
> **Warning!** You should not delete **default** search engines from a `search.json.mozlz4` file if you edit the file. If you delete a default search engine then the Firefox will **reset** search engine list to a **default** state.

<sub>src: https://addons.mozilla.org/de/firefox/addon/mozlz4-edit/</sub>

Just go to `about:preferences` and change your default search engine. Unfortunately you can not do this in a user.js file.

**Comment by AramatZ** [comment]
I`m not delete. Just add new based on google engine just sanitized.

> Just go to about:preferences and change your default search engine. Unfortunately you can not do this in a user.js file.

I do not want to do it every time when I replacing the search.json.mozlz4 file with my own. For several years it was not required now mozilla changed something.

**Comment by rusty-snake** [comment]
Ahh, I got you wrong. If you only add new SEs (with new names) that's fine.

> I do not want to do it every time when I replacing the search.json.mozlz4 file with my own. For several years it was not required now mozilla changed something.

Did you created this file "several years" ago? If so firefox maybe changed the format (e.g. changed parameters) and considers your old one corrupted.

**Comment by AramatZ** [comment]
>Ahh, I got you wrong. If you only add new SEs (with new names) that's fine.

No. It`s my fault. My bad english. :)

Yes I create file in 2017. But I try create new one and have the same issue. Inside search.json.mozlz4 have user profile id and when this ID change in file or create new firefox profile (with new ID of course) than FF restore google above my own search engine. It`s start after v.85 or v.86.

**Comment by atomGit** [comment]
see if this helps you - it may need updating since i haven't done anything with it for quite a while...

[Firefox Search Engine Cautions, Recommendations](https://12bytes.org/articles/tech/firefox/firefox-search-engine-cautions-and-recommendations/)

**Comment by rusty-snake** [comment]
As I understand it you only want to add a custom (e.g. sanitzed google) SE to your fox (with as little as possible steps).
Here are my tries for that:

- Write a [WebExtension manifest.json](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides) with your SE, zip it, rename to .xpi and add it to firefox. Drawbacks: Requires `xpinstall.signatures.required=false`.
- Write [opensearch-plugins](https://gitlab.com/rusty-snake/firefox-config/-/tree/master/search-plugins) and add them to your firefox. Drawbacks: Does not work via `file:///`.
- Find a good one on AMO or at mycroftproject.com.

**Comment by Svallinn** [comment]
FYI, `xpinstall.signatures.required` isn't supported in the Firefox release builds.

![image](https://user-images.githubusercontent.com/41585298/123488827-3a379f80-d600-11eb-8519-8ba4aef43193.png)
