### ISSUE TITLE
https://fingerprintjs.com gmp-clearkey

### ISSUE THREAD

**Issue by gmvk** [arkenfox/user.js#1199]
I noticed https://fingerprintjs.com creates
```
/home/*/.mozilla/firefox/*/gmp/Linux_x86_64-gcc3/gmp-clearkey/id/*/
origin
salt
topLevelOrigin
```
What is it?

`media.gmp-provider.enabled` is disabled.

**Comment by rusty-snake** [comment]
FWIW: File content
```
$ bat "$HOME"/.mozilla/firefox/PROFILE/gmp/Linux_x86_64-gcc3/gmp-clearkey/id/*/* --style=header
File: /home/rusty-snake/.mozilla/firefox/PROFILE/gmp/Linux_x86_64-gcc3/gmp-clearkey/id/ID/origin
https://fingerprintjs.com^userContextId=24957&firstPartyDomain=fingerprintjs.com

File: /home/rusty-snake/.mozilla/firefox/PROFILE/gmp/Linux_x86_64-gcc3/gmp-clearkey/id/ID/salt
K3M5thKwKf5uZPWvFzHwpt6veDXbkO7P

File: /home/rusty-snake/.mozilla/firefox/PROFILE/gmp/Linux_x86_64-gcc3/gmp-clearkey/id/ID/topLevelOrigin
https://fingerprintjs.com^userContextId=24957&firstPartyDomain=fingerprintjs.com
```

**Comment by rusty-snake** [comment]
I can not tell you what it is, but it looks like it is
1. isolated (by FPI and userContext)
2. cleared (Ctrl-Shift+Del History&Downloads time:all removes the files, so I guess it's cleared on shutdown too)

**Comment by gmvk** [comment]
Yes clears, but `/gmp-clearkey/id/343999408/` does not change.

**Comment by Thorin-Oakenpants** [comment]
What is the folder under `/id/` ? You guys are asterisking it out. Here's mine
- `\profile\gmp\WINNT_x86_64-msvc\gmp-clearkey\id\2427915045\`

**Comment by Thorin-Oakenpants** [comment]
not to take anything away from the test, but it seems to be a bit naive. I don't allow cookies, and IDK if they try to use those, but every visit (even in a browser session as well) returns a different ID. I'm not using any extensions that would change anything, and I'm not resizing. So it is being totally sucked in by random canvas, which I find rather lame of them TBH.

**Comment by reallyuniquename** [comment]
>I noticed https://fingerprintjs.com creates files

My understanding is Firefox spins up plugin container that actually loads Gecko Media Plugins even if you set them to never activate and `media.eme.enabled` is `false`. 

Is there a way to prevent this unwanted behaviour? Anything else besides purging `gmp-clearkey` directory?

>`media.gmp-provider.enabled` is disabled

As @Thorin-Oakenpants pointed out in https://github.com/arkenfox/user.js/issues/709#issuecomment-487871860 that option is purely cosmetic (see also Bugzilla #1474197).

>Now Tor Browser disables it but they also disable widevine and cdm and openh264 etc, along with all the background update checks etc.

How did they implement that?

**Comment by Thorin-Oakenpants** [comment]
@reallyuniquename what is the privacy concern here?

**Comment by reallyuniquename** [comment]
It's more of a security concern. With user.js I expect no external plugins to be loaded.

Anyway, any helpful ideas?

**Comment by rusty-snake** [comment]
Are they external?

**Comment by reallyuniquename** [comment]
Yes.

**Comment by Thorin-Oakenpants** [comment]
explain what the security concern is

**Comment by reallyuniquename** [comment]
The same one we had with Flash. GMP is a platform for 3rd party extensions and ClearKey is just one that comes pre-installed. If you have a plugin named `gmp-whatever` Firefox will happily side-load that too.

Look, I'm not here to argue whether this is a privacy or security concern. I just figured this is the place to ask. If you have no idea how to disable GMP without rebuilding Firefox from sources just say so and I'll move along.

**Comment by rusty-snake** [comment]
> If you have a plugin named `gmp-whatever` Firefox will happily side-load that too

From my digging in the code, gmp plugins must be signed (like extensions) by default. (Not 100% sure, but that what I got so far so as long as no one shows me something else ...)
