### ISSUE TITLE
Synology DSM 7 login

### ISSUE THREAD

**Issue by Chris122AT** [arkenfox/user.js#1204]
Until the V6.x of the Synology Web GUI, the login worked properly using user.js. Since the update to DSM 7, the login is no longer possible. The following errors occur using the user.js: 

sodium.js:
`Uncaught (in promise) Error: Both wasm and asm failed to loadTypeError: t.asm.sodium_init is undefined
    e https://192.168.0.10:5050/scripts/noise/sodium.js?v=1621235040:1`

and 

vue.min.js:
`TypeError: this.cred is undefined
    GetLoginParams https://192.168.0.10:5050/webman/sds-common.js?v=1623045722:12
    VueJS 17`

Unfortunately, I do not find the parameters in user.js causing for these errors.

Does anyone have solutions?

**Comment by rusty-snake** [comment]
> […] wasm […] failed to load […]

https://github.com/arkenfox/user.js/blob/a6d20eaf5b4d6fc306257cf56beb89595c6be173/user.js#L1048-L1056

> […] asm failed to load […]

(maybe)

https://github.com/arkenfox/user.js/blob/a6d20eaf5b4d6fc306257cf56beb89595c6be173/user.js#L1032-L1039

**Comment by Chris122AT** [comment]
@rusty-snake Thank you very much!

**2422** set to **true** solved the probem!
`user_pref("javascript.options.wasm", true)`
