### ISSUE TITLE
How to enable silent permission popup

### ISSUE THREAD

**Issue by specter78** [arkenfox/user.js#1205]
Chrome recently implemented a change whereby permission for notification, location, etc will be display within the url bar itself, without a popup.

Is there a way to enable the same in Firefox?

**Comment by Thorin-Oakenpants** [comment]
Not that I know of. Permission prompts/fatigue can be annoying - personally I don't see very many. If Firefox wants to do something to reduce that, great, but it's not really something that fits this repo
