### ISSUE TITLE
Change fission.autostart to "true" for Site Isolation

### ISSUE THREAD

**Issue by dot-clear** [arkenfox/user.js#1208]
Site isolation is a security feature in Chrome since many time.
Site isolation is available in Firefox with “fission.autostart » true.
Could you add it ?

https://blog.mozilla.org/security/2021/05/18/introducing-site-isolation-in-firefox/

More explanation : https://wiki.mozilla.org/Project_Fission

**Comment by Thorin-Oakenpants** [comment]
It will land when it lands. Some items we push early, if there are very few bugs. But overall I am loathe to add in prefs that eventually end up as default, and just end up cluttering the user.js. Fission is not something they will sit on. Also, it's slightly problematic given ESR users like to use the release version

https://wiki.mozilla.org/Project_Fission#Known_Issues

https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/
> ... Fission (Site Isolation). This feature will be gradually enabled by default on Firefox Beta in the upcoming months and will start rolling out a small percentage of release users in Q3 2021

Well, we're now at the start of Q3 .. my guess is for all release users is somewhere in Q4 .. right smack dab in the [middle](https://wiki.mozilla.org/Release_Management/Calendar) .. 2nd Nov, Firefox 94 sounds legit

Firefox has been without "fission" for a long time ... browsers (major ones like safari, firefox, chrome, edge and a few big forks like brave, vivaldi) are inherently already very secure. A few more months is not going to hurt anyone. Given the complexity of it (see below), I am happy to wait for Mozilla to enable it

---

I'll add this from somewhere else that I talked about this (and no, I am not an Mozilla employee)

> I read some recent comments about site isolation on hackernews - ~~I think~~ [this](https://news.ycombinator.com/item?id=27196526) is the one. It was an idea floated around 2012 (at google I think) and it's a massive engineering feat: Chrome didn't get it production ready until 2018 (not saying it was six years: IDK when or what priority shit had)
> 
> Mozilla have been working on fission since some time after Quantum. I actually met the guy in charge of it all, and sat in on one of his presentations. It's a small team and was just getting underway when I was in `<snip snip snip>` (2 years ago) - so that's pretty fucking impressive
> 
> When I say massive engineering, it really is: not that IANE. Even a simple things like search, means you have to send all the isolated bits to a parent process with more privileges .. actually [this comment](https://news.ycombinator.com/item?id=27203743)

**Comment by dot-clear** [comment]
Yes I have read about fission from a tech news, I’m not in a hurry. The news was probably a little optimistic in comparison with Mozilla announcements.

About ESR users (version 78.11), maybe some are present here, but they aren’t representative from most of the users. They should [reconsider ](https://github.com/arkenfox/user.js#--the-arkenfox-userjs)their version choice:

In July (https://www.stetic.com/market-share/browser/) :
Firefox 89 : **7.80%**
Firefox 78 : **0.79%**

**Comment by Thorin-Oakenpants** [comment]
we're all reporting as ESR .. see RFP

**Comment by dot-clear** [comment]
The interest from arkenfox user.js against ffprofile.com or our own tweak, is to apply the same settings.
I have read the [Wiki](https://github.com/arkenfox/user.js/wiki), to find the ESR recommendation, I didn’t find it. 
I doubt also most arkenfox users use ESR version. In addition arkenfox user.js [release](https://github.com/arkenfox/user.js/releases) induce to follow the main Firefox release.

Just to say, the README.md file is missing :
- requirements to use user.js 
- a **simple** process to install step by step the same config

**Comment by Thorin-Oakenpants** [comment]
I don't understand?
- What does this have to do with ffprofile?
- Who is "our" in "our own tweak"?
- What does "apply same settings" mean - what settings?
- What ESR recommendation in the wiki? I do not see anything in there about ESR

> I doubt also most arkenfox users use ESR version

I also doubt most arkenfox users use ESR, but that doesn't invalid ESR, including arkenfox users using it.

Do I wish arkenfox ESR users would use the corresponding arkenfox user.js release (e.g. v78)?, yes - but some users like to use the latest version as it is a year between ESR releases now, and we can make lots of changes in that time such as better info/refs, pref changes (like #1099 and #1194), pref removals (like https://github.com/arkenfox/user.js/commit/9cc132e69db7688aa1d5f9ff72b99627527e5e78 ) - i.e **_things that ESR STILL BENEFITS from_**. It's not too difficult to make the live version work for ESR with the end user only having to make a couple of changes, but that doesn't mean I don't consider the consequences of it when I add new prefs

My point about arkenfox users who do not override RFP, is that they also report that they are in the smaller group of ESR users. So if you meant those stats to indicate a fingerprinting risk, then it's kinda moot. However, scripts can accurately detect versions via feature detection, or it shows in contrast with other fingerprinting metrics automatically (it's not like a script has to explicitly test for "are you really ESR"). Not that I expect you to know all that, but most scripts are naive, and just scrape the reported version from the user agent - so my point about your argument being moot still stands (assuming you were trying to point out that it is more fingerprintable: I see no other reason why you should advocate users not use a SUPPORTED channel)

> README.md file is missing

What? It's not missing any requirements - it says `is made specifically for desktop Firefox.` That's all that is required. And info on how to use it is in the wiki, which is linked to, in the very first paragraph

**Comment by dot-clear** [comment]
What does this have to do with ffprofile?

Nothing to do with the initial subject, but like arkenfox user.js is (not only) about Firefox template, privacy and security.

    Who is "our" in "our own tweak"?

The user, he can change directly some things in about:config 

    What does "apply same settings" mean - what settings?

Both, general settings and advanced [settings](https://support.mozilla.org/en-US/kb/about-config-editor-firefox) 

    see RFP

Yes RFP is mentioned anywhere but not clearly explain. I suppose you refer to the parameter `privacy.ResistFingerprinting`.

    So if you meant those stats to indicate a fingerprinting risk

Yes indicate a fingerprinting risk, doing with arkenfox user.js a niche (there is 19 sections in the wiki) for insiders (probably unintended) and by letting users choose between to much [strategy](https://github.com/arkenfox/user.js/wiki/1.3-Implementation#small_orange_diamond-decide-on-a-strategy).

I like the arkenfox project and your wiki is very useful. But honestly it take me some time to understand how to use it and how it works. 
I don’t think a basic user want to read 19 sections and to be questioning.

    What ESR recommendation in the wiki? 

Yes I said that : I didn’t find it
When you took about ESR that it made me doubt, I wasn't sure if I was using user.js correctly

**Comment by Thorin-Oakenpants** [comment]
I get the feeling English is not your native language, and this conversation is going nowhere fast

**Comment by Thorin-Oakenpants** [comment]
> It will land when it lands.

FYI: [1732358](https://bugzilla.mozilla.org/show_bug.cgi?id=1732358) assuming everything goes smoothly ... FF96 landing 2022-Jan-11

**Comment by Thorin-Oakenpants** [comment]
FYI: Fission roll out is normandy pref-flip (shield studies), so anyone who disabled `app.shield.optoutstudies.enabled` won't get it until it is enabled in source code - now planned for 97 [1732358](https://bugzilla.mozilla.org/show_bug.cgi?id=1732358). And of course, we disable experiments :)

The rollout the other day was at 100% for windows/mac and 50% linux. Experiments is used as it is the only way they can push via platform and percentage (AFAIK)
