### ISSUE TITLE
Question: what's the recommended way of getting around webp?

### ISSUE THREAD

**Issue by itsdeadguy** [arkenfox/user.js#1209]
As the title says, is there a way to make firefox stop accepting this format? i need to save images as they are, not in some google-owned format.

I know there's a couple extensions out there but i was hoping there's a pref i can add to overrides or something.

Thank you

**Comment by Thorin-Oakenpants** [comment]
I think you need to change the accept header (⚠️  I do not recommend this as it will alter your passive fingerprint) - AFAIK sites should use that to determine whether to serve jpg or webp

[browserleaks](https://browserleaks.com/ip), scroll down to Accept HTTP Headers
```
`text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8` <-- Firefox Nightly
`text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`   <-- I assume
``` 

I assume that's the correct string from [this](https://hg.mozilla.org/mozilla-central/rev/0614c786ca70). I also assume that this is what those extensions are doing - very fingerprintable

I *think* this works, it sure does change the accept header on the browserleaks test - USE AT YOUR OWN RISK
```js
user_pref("image.http.accept", "*/*");
```

**Comment by Thorin-Oakenpants** [comment]
FYI: https://old.reddit.com/r/firefox/comments/oihccg/firefox_defaulting_to_saving_jpegs_as_webp_why_is/h4w051e/

looks like the second extension is better for your fingerprint - you just have to use the context menu. So depending on *how* your workflow goes, this might fit - e.g. it wouldn't let you drag n drop images AFAICT

the first extension could be improved if it had an allowlist, if that fitted with you getting most images from a couple of sites, and by extension (pun intended) that's not to harm your fingerprint much if at all (a FP script has to run, and that script needs to be universal across the allowlist)

@jscher2000 just pinging ya FYI

**Comment by jscher2000** [comment]
Re: [Don't "Accept" image/webp](https://addons.mozilla.org/firefox/addon/dont-accept-webp/)

> the first extension could be improved if it had an optional allowlist, if that fitted with you getting most images from a couple of sites, and by extension (pun intended) that's not to harm your fingerprint much if at all (a FP script has to run, and that script needs to be universal across the allowlist)

That might be feasible. One of the complexities is that images often are hosted on different servers than the sites displaying them.

For now, there's an on/off button for the toolbar so you can send standard requests until you find that you need to modify them.

**Comment by Thorin-Oakenpants** [comment]
thanks @jscher2000 👍 that complexity is a user workflow issue - if they're always grabbing images from the same origins it should be easy, same for toggling the extension state (I didn't think of that, great stuff) if they go on an hour long image grabbing spree. Nothing will cover all use cases, unfortunately: i.e protecting the fingerprint

**Comment by Ne3tCode** [comment]
`user_pref("image.webp.enabled", true);`  // default
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,**image/webp**,\*/\*;q=0.8

`user_pref("image.webp.enabled", false);` // FF can't render WebP images, no more WebP's on Imgur :D
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,\*/\*;q=0.8

**Comment by rusty-snake** [comment]
FWIW my workaround (lossy):
1. Right-click > Open Image in New Tab
2. Right-click > Take Screenshot

**Comment by Thorin-Oakenpants** [comment]
OT (but I don't have a reddit account) @jscher2000 
- https://old.reddit.com/r/firefox/comments/rp0e3b/firefox_doesnt_want_us_to_use_the_menu_bar/
- op doesn't say what OS or what his googled solution is, but another cause could be accidental toggling via the Alt key

````
   // user_pref("ui.key.menuAccessKey", 0); // disable alt key toggling the menu bar [RESTART]
```
