### ISSUE TITLE
Can Sponsorblock be detected in Youtube?

### ISSUE THREAD

**Issue by TearJoy** [arkenfox/user.js#1212]
Hi! I've been watching more and more youtube videos lately and feel the need to use sponsorblock (I use NewPipe + Sponsorblock on Android and it has been a lifesaver)

For anyone who doesn't know what Sponsorblock is, it's an extension that lets you skip sponsor segways in youtube videos. No security and privacy benefit, just there for convenience.

My question is that can using Sponsorblock or similar extensions can be detected or not

I know I should be using Invidious, but it's not reliable for me most of the time because there are tons of instances and idk which is the fastest for me and sometimes the ones i pick are just down. I would be glad if someone knowledgeable in this area can answer.

Edit: Or should I just be using a different profile? I tried using a different profile for watching anime last time but the prefs are pretty much the same so it just doesn't seem worth it

**Comment by TearJoy** [comment]
> ???
A different FF profile for streaming videos.

Well I guess I got my answer. I'm closing this issue. Thanks a lot for the response!

**Comment by Thorin-Oakenpants** [comment]
Well, if it only manipulates one site, and can't be detected on any others, then who cares

**Comment by TearJoy** [comment]
Hmmm, I see. Might reconsider this.

**Comment by Thorin-Oakenpants** [comment]
OK, so disable all extensions
- test: https://abrahamjuliot.github.io/creepjs/tests/prototype.html
- did you pass? you should
- enable your extension
- redo the test: does it leak anything
   - some extensions leak some info if they don't interact with the page in any way
   - for example NoScript, AdBlocker Ultimate do
   - uBO doesn't

I don't know if that test is up to date, there were changes made elsewhere to detect proxy lies, not just prototype lies. TZP is up to date, but runs the short abridged version, not the full gamut - that should be enough

**Comment by atomGit** [comment]
@TearJoy - perhaps a little off-topic, but check out [FreeTube](https://freetubeapp.io/)

or if you wanting to use an Invidious instance, check out [Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) for Firefox

**Comment by TearJoy** [comment]
> 
> 
> @TearJoy - perhaps a little off-topic, but check out [FreeTube](https://freetubeapp.io/)
> 
> or if you wanting to use an Invidious instance, check out [Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) for Firefox

I have used FreeTube before, I didn't like it. I've used Privacy Redirect too but I didn't have a use case for it so I just removed it.




> 
> 
> OK, so disable all extensions
> 
>     * test: https://abrahamjuliot.github.io/creepjs/tests/prototype.html
> 
>     * did you pass? you should
> 
>     * enable your extension
> 
>     * redo the test: does it leak anything
>       
>       * some extensions leak some info if they don't interact with the page in any way
>       * for example NoScript, AdBlocker Ultimate do
>       * uBO doesn't
> 
> 
> I don't know if that test is up to date, there were changes made elsewhere to detect proxy lies, not just prototype lies. TZP is up to date, but runs the short abridged version, not the full gamut - that should be enough

I passed with extensions enabled and disabled.
