### ISSUE TITLE
HTTP background request

### ISSUE THREAD

**Issue by adrian5** [arkenfox/user.js#1213]
> ```javascript
> /* 1246: disable HTTP background requests [FF82+]
>  * When attempting to upgrade, if the server doesn't respond within 3 seconds, firefox
>  * sends HTTP requests in order to check if the server supports HTTPS or not.
>  * This is done to avoid waiting for a timeout which takes 90 seconds
>  * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1642387,1660945 ***/
> user_pref("dom.security.https_only_mode_send_http_background_request", false);
> ```

I wonder, is this necessary after [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1660945#c4) commit? Does the _background_ request still contain data beyond the (root) domain?

**Comment by rusty-snake** [comment]
AFAIK no.

**Comment by Thorin-Oakenpants** [comment]
Right, as rusty said, the clearnet request is a domain only check. The `1246` pref is so you don't even leak the domain in the clear .. unless you wait for the timeout and then proceed to go anyway

**Comment by rusty-snake** [comment]
FTR: You still leak the Domain in the SNI unless you use ESNI or ECH.
