### ISSUE TITLE
Browser opens in Window mode and screen is not fully used

### ISSUE THREAD

**Issue by HyperCriSiS** [arkenfox/user.js#1215]
Hi,

I read you do not support forks and I fully understand. I just need a small hint if possible.
I just tested your template with newest Waterfox, without any overrides.
The Browser starts always in Window mode now and the screen is not fully used by websites.
Which settings could cause something like this?

![grafik](https://user-images.githubusercontent.com/11708192/126207436-cc66fff3-42bd-4264-b4d0-a00db75b16e4.png)

Thanks,
Hyper

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/b761a9dd32f79395b0fca183ad8fe45f7e99d26f/user.js#L1392-L1481

**Comment by HyperCriSiS** [comment]
Thanks so much!! Works perfectly :)
