### ISSUE TITLE
Be proud of what you're doing:

### ISSUE THREAD

**Issue by Onfroygmx** [arkenfox/user.js#1219]
![firefox](https://user-images.githubusercontent.com/25054585/127522196-43e3c56a-b87c-4dc1-8c75-a637b16cd77f.png)

FF current, beta,  nightly
Following you since several years.
Onf

**Comment by KOLANICH** [comment]
Pride is a sin. And creating useless issues with no valuable information is disrespect.

**Comment by atomGit** [comment]
the answer Alex, is 'what an idiot would say'

@Onfroygmx - i'm sure the devs will appreciate your comment and i second it

**Comment by Thorin-Oakenpants** [comment]
@Onfroygmx Thanks ❤️ I'm sure @earthlng and other contributors appreciate it as well

@KOLANICH Others before have _occasionally_ created a ticket to say thank you, or just posted out-of-context comments in existing issues. That's OK. We're all human, and sometimes a little pat on the back and some validation is needed. God only knows at times I've almost thrown this away - so I for one appreciate it. I do agree though, that _professionally_, unnecessary noise should be kept to a minimum.

Downright lambasting someone for saying kind words is not appropriate IMO .. also [pride](https://en.wikipedia.org/wiki/Pride) is not necessarily a sin - that's a debate for philosophers

anyway, here's a story book I read as a kid, about philosophers
![fucks](https://user-images.githubusercontent.com/16656956/127530253-a95ec1d4-6ec7-49cb-bef1-bb63a0299f8f.jpg)

**Comment by Onfroygmx** [comment]
OK let's close this then!

**Comment by Thorin-Oakenpants** [comment]
Free reminder that you always worship at the Altars of Pants
- [Red Panda Altar of Pants](https://github.com/arkenfox/user.js/issues/1191#issuecomment-861705546)
- [Pussy Cat Altar of Pants](https://github.com/arkenfox/user.js/issues/1217#issuecomment-886401078)
