### ISSUE TITLE
very small correction to 1021 description

### ISSUE THREAD

**Issue by practik** [arkenfox/user.js#1220]
I've been adding the `user.js` to my setup a few lines at a time. Today I activated 1021 (with 0102 overridden) and was surprised to find my scroll positions being remembered after a restart, since the description for 1021 says "extra session data contains contents of forms, scrollbar positions, cookies and POST data."

AFAICT the "scrollbar positions" part of that line is outdated and should be deleted – see discussion at https://support.mozilla.org/en-US/questions/1303499

I know this is a minor thing but it might confuse other users too, so I figured I'd mention it.

Thanks for building this monster and staying on top of all its moving parts!

**Comment by Thorin-Oakenpants** [comment]
Thanks @practik for finding the SUMO link and @jscher2000 for digging into the code
