### ISSUE TITLE
Ublock not work with user.js

### ISSUE THREAD

**Issue by Atlantistux** [arkenfox/user.js#1222]
Hello, i'm on Debian 10 Buster with Firefox 78.12 ESR.

I've installed Ublock from Debian repo and it doesn't appear when i use the user.js config file.
With the default config, the extension works. I search on the wiki page (troubleshooting), existing issue on github, and on internet, i found nothing on this problem.
So have you an idea what modified in the config file for Ublock work ?

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/5c93ebb54f7248bb9419ebed27ced383e65be324/user.js#L1206-L1212

**Comment by rusty-snake** [comment]
Try this in your overrides

```js
user_pref("extensions.enabledScopes", 13);
```

**Comment by Atlantistux** [comment]
Ohhh, its works, thanks you very much : ) .
It's been 2 days that I've been struggling to find a solution !
