### ISSUE TITLE
question regarding wiki uMatrix

### ISSUE THREAD

**Issue by gitlerat** [arkenfox/user.js#1227]
Hi, I've read the wiki and under extionsions it says:
"Everything uMatrix did can be covered by prefs or other extensions"

I used uMatrix for only allowing first party cookies and scripts, frames, xhr, ... and whitelist only some website to use third party scripts and so on. 

Is this possible with **only using prefs**?

kind regards

**Comment by crssi** [comment]
For cookies yes.
For scripts, frames, xhr, ... you can use uBlock Origin.

Cheers

**Comment by gitlerat** [comment]
Ok, I asked because I thought I can achieve it without installing any extension, but thanks for clearing me up :)

**Comment by crimsonpython24** [comment]
Are there any problems of using uMatrix? The wiki only mentions that
1. it's redundant (which I don't think the Wiki has mentioned anything bad regarding redundant extensions)
2. it's no longer maintained

**Comment by Thorin-Oakenpants** [comment]
> only mentions ....

are you not ~~entertained~~ informed?

**Comment by remyabel2** [comment]
>     1. it's redundant (which I don't think the Wiki has mentioned anything bad regarding redundant extensions)

Use hard mode, but even the UBO wiki says that hard mode is marginally better than medium mode.

>     2. it's no longer maintained

So it will no longer receive fixes, security updates and probably stop working at some point if Firefox changes its APIs.
