### ISSUE TITLE
Allow url bar to use search engienes.

### ISSUE THREAD

**Issue by CTZxVULKAN** [arkenfox/user.js#1230]
After installing the user.js script in my Firefox profile i have now lost the functionality of searching with search engines through my URL bar. Currently my URL bar only accepts URLs and even normal search quires (words , letters no.s etc) are also treated as URLs.

 How do i change this behavior ?
Any help in this matter will be greatly appreciated.

**Comment by Thorin-Oakenpants** [comment]
read the docs, search the user.js ... everything you need is there .. have you tried reading the README bit at the top like line 26 ... 

```
/* 0801: disable location bar using search <-- READ THIS
 blah blah
 * [SETUP-CHROME] <---- LOOK AT THIS
```
