### ISSUE TITLE
updater scripts

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1233]
can you guys and gals check that the code handles three digits - TIA
- [ ] updater.bat
- [ ] updater.sh

**Comment by icpantsparti** [comment]
Both look okay to me, although I am not familiar with powershell, so perhaps if someone can give a quick second opinion.

The scripts do not appear to do anything significant with the "digits", they both parse that info from the user.js but based on a hardcoded line number, and just use the info for output to the screen.

Where the updater.sh optionally activates the ESR section digits are used, and it's looking for 2 or more digits so ok.  The updater.bat finds that ESR line by the text after the digits so no issue there either.

**Comment by Thorin-Oakenpants** [comment]
OK, thanks ... we'll see if anything breaks come v100
