### ISSUE TITLE
FF93+ RFP testers please

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1234]
Test: https://snkth.com/browser-fingerprinting/math-fingerprint-tests/ .. click `Do Test`

STR
- must be FF93 2021-08-13+ (the update was only about a couple of hours ago)
- RFP = on, load test
- RFP = off, load test in a second tab (or remember previous result, and just hard refresh)

Reply with OS etc, and results. If the count is not zero, then paste the raw data

--

edit: if you visit [this math test](https://arkenfox.github.io/TZP/tests/math.html) you should get `F20` using the Firefox control (default) which happens to match one of the [seven android results](https://arkenfox.github.io/TZP/tests/mathdata.html) `F20-F26`

Android still has some differences, but remove the sin/cos/tan differences and it drops from 7 results to 4. Desktop is looking good, and I see no reason why they should now differ 🎉 Remembering that the goal is not to hide the OS, but to hide differences **_within each OS_**

---

### summary

🔻 windows
- ✓ Windows 7 64bit, FF64bit: 0 (was 17)
- ✓ Windows 7 32bit, FF32bit: 0 (was 35)
- ✓ Windows 10 20H2 64bit, FF 64bit: 0 (was 11)
- ✓ Windows 11 (22000.132) 64bit, FF64bit: 0 (was 11)

🔻 linux
- ✓ Fedora 34 64bit: 0 (was 14)
- ✓ Debian Bullseye (64-bit) : 0 (was 14)

🔻 mac
- macOS BigSur 11.4 64bit: 0 (was 32)

---

🔻 android
- ✓ Android Galaxy S9: 32bit: 0 (was 0)
- ✓ Android 11 OnePlus 7 Pro (64bit): 0 (was 0)
- ✓ Android 10 OnePlus 3 64bit (Lineage OS): 0 (was 0)

**Comment by Ilomantis** [comment]
Windows 11 64bit, FF64bit: 0 (was 11)

**Comment by rusty-snake** [comment]
Fedora 34 64bit: 0 (was 14)

**Comment by 2glops** [comment]
Debian Bullseye (64-bit) : 0 (was 14)

**Comment by Youngblood50** [comment]
Android 11 OnePlus 7 Pro (64bit): 0 (was 0)

**Comment by Youngblood50** [comment]
Windows 10 20H2 64bit, FF 64bit: 0 (was 11)

**Comment by fxbrit** [comment]
macOS BigSur 11.4:
- rfp on = 0
- rfp off = 32

sorry bout not using the _was_ notation but I did not want to mess up lol.

**Comment by Thorin-Oakenpants** [comment]
thanks peoples .. have some free mooncake 🥮 🥮 🥮 🥮
