### ISSUE TITLE
tips for more privacy and less telemetry

### ISSUE THREAD

**Issue by gallegonovato** [arkenfox/user.js#1240]
Good afternoon:

First of all thank you for your work and for all your time.

I am contacting you, to suggest some changes. In order to have less telemetry and privacy.

The suggestions are:

user_pref("geo.provider.network.url", "");

user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);

user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
  | user_pref("browser.safebrowsing.provider.google.updateURL", "");
  | user_pref("browser.safebrowsing.provider.google.gethashURL", "");
  | user_pref("browser.safebrowsing.provider.google4.updateURL", "");
  | user_pref("browser.safebrowsing.provider.google4.gethashURL", "");
  | user_pref("browser.safebrowsing.provider.google.reportURL", "");
  | user_pref("browser.safebrowsing.provider.google4.reportURL", "");
  | user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "");
  | user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "");
  | user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "");
  | user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "");
  | user_pref("browser.safebrowsing.provider.google4.dataSharing.enabled", false);
  | user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
  | user_pref("browser.safebrowsing.provider.google.advisory", "");
  | user_pref("browser.safebrowsing.provider.google.advisoryURL", "");
  | user_pref("browser.safebrowsing.provider.google.advisoryName", "");
  | user_pref("browser.safebrowsing.provider.google.gethashURL", "");
  | user_pref("browser.safebrowsing.provider.google4.advisoryURL", "");
  | user_pref("browser.safebrowsing.blockedURIs.enabled", false);
  | user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
  | user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
  | user_pref("browser.safebrowsing.reportPhishURL", "");
  | user_pref("browser.safebrowsing.features.cryptomining.update", false);
  | user_pref("browser.safebrowsing.features.fingerprinting.update", false);
  | user_pref("browser.safebrowsing.features.malware.update", false);
  | user_pref("browser.safebrowsing.features.pishing.update", false);
  | user_pref("browser.safebrowsing.features.trackingAnnotation.update", false);
  | user_pref("browser.safebrowsing.features.trackingProtection.update", false);

user_pref("permissions.delegation.enabled", false);

user_pref("browser.messaging-system.whatsNewPanel.enabled", false); // What's New toolbar icon [FF69+]
--
  | user_pref("messaging-system.rsexperimentloader.enabled", false);
  | user_pref("extensions.pocket.enabled", false); // Pocket Account [FF46+]
  | user_pref("identity.fxaccounts.enabled", false); // Firefox Accounts & Sync [FF60+] [RESTART]
  | user_pref("reader.parse-on-load.enabled", false); // Reader View

A hug and thank you for your time

**Comment by Thorin-Oakenpants** [comment]
What makes you think any of those improve privacy?
