### ISSUE TITLE
minor clarifications for wiki "1.3 Implementation"

### ISSUE THREAD

**Issue by podiki** [arkenfox/user.js#1252]
Thanks for making this! I'm working my way through the details, but wanted to point out a few minor clarifications that might be needed for the Implementation wiki page.

1. "We disable binary checks not in Safe Browsing local lists (0412)": where has 0412 gone? I only see references through this page and some issues, but not in user.js. It would also be helpful to have either a slightly longer description here, or a link to a page to read what this is (I only found out indirectly).
2. "FPI is enabled (4001)" states to "clear (Ctrl-Shift-Del) everything (except passwords and site preferences)". What does this mean exactly, all cookies, history, etc.? This seems to be in a few places in Firefox Settings, so would be helpful to have some more detail here. Also, not sure what the key shortcut here is for (used in one of the setting's lists? this might be OS-specific, too).

If I come across anything else a new user might find confusing I'll be sure to add, though I appreciate the detailed and helpful wiki pages so far!

**Comment by rusty-snake** [comment]
1. It's now, since the cleanup in the last few weeks, 0403.
2. Ctrl-Shift-Del (or settings > Privacy & Security > History > Clear History) select time range=everything and all checkboxes expect of site settings.

**Comment by podiki** [comment]
@rusty-snake thanks for the speedy response! Thanks, that clears it up, didn't realize that was a shortcut key for Clear History, that's handy.

I would suggest next round of wiki updates to fix that number and something like "It is recommended that you clear everything (except passwords and site preferences) in History (shortcut Ctrl-Shift-Del)..."

**Comment by Thorin-Oakenpants** [comment]
yeah, sorry, I missed one with the number changes .. make that two, I just also fixed search and form history (was 0860). Site preferences are actually keyed with FPI (since 78?) so I fixed that too
