### ISSUE TITLE
RFP causes Cloudflare to loop infinitely

### ISSUE THREAD

**Issue by SakhJack** [arkenfox/user.js#1253]
## Issue
Enabling `privacy.resistFingerprinting` (RFP) makes it impossible to pass Cloudflare DDOS check

## How
1. Create fresh profile and **only** enable above mentioned config, no add-ons or other configurations
2. Visit either `https://sendspace.com/` or `https://steamdb.info/app/730/`

## Expected Result
Page redirects only once as usual, proceeding to desired website

## Observed Result
Page repeats the check indefinitely, making website inaccessible 

## When
This started happening since some previous version, but not earlier than 89

## Temporary Solution
Disabling `privacy.resistFingerprinting` resolves the issue, but I'd rather find a way to use it again

**Comment by Thorin-Oakenpants** [comment]
FYI @tomrittervg 

For what it's worth, I used ctrl-i to allow a canvas permission (because that was mentioned in the console), but that wasn't enough to stop the loop. I guess RFP is working then .. because everyone's RFP characteristics are the same as Tor Browser and cloudflare or the website's restrictions is battling anonymous spammers or whatever

> This started happening since some previous version, but not earlier than 89

It's not an RFP change, the same thing happens in ESR78

**Comment by SakhJack** [comment]
so this means nothing can be done until Mozila fixes this bug?

**Comment by rusty-snake** [comment]
1. Visit https://gitlab.com/users/sign_in and make sure it works
2. Clear cookies
3. Set `privacy.resistFingerprinting=true` and visit https://gitlab.com/users/sign_in again, it is now broken.
4. Reset RFP and clear cookies
5. Visit https://gitlab.com/users/sign_in, it works again
6. Now set `dom.enable_resource_timing=false` and visit https://gitlab.com/users/sign_in, it is broken again.

**Comment by Thorin-Oakenpants** [comment]
> so this means nothing can be done until Mozila fixes this bug

Was going to post was that RFP breaks web standards, that's what all it's protections do. When this happens, things can break. And apart from the obvious (e.g. utterly wrecked and randomized canvas), that **_timing_** is a usual suspect (and rusty-snake confirms this is the area to start looking at).

It's not a question of when Mozilla can fix this, it's a question of finding the **_exact_** cause and seeing if it's feasible to do anything about it - i.e they wouldn't want to weaken the timing mitigations.

[cloudflare bugs](https://bugzilla.mozilla.org/buglist.cgi?classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&short_desc=cloudflare&short_desc_type=allwordssubstr&resolution=---&query_format=advanced)

Some of those may be relevant, but it's more likely a change in their protection code ... I _think_ what is happening is their code is ending too early (timers?) and causing a re-check. Have you lodged a bugzilla?

In the meantime, they only solution for these few sites, is to open them in a secondary browser/profile. You can install Nightly and Beta along stable, at least on Windows. I do **_not recommend_** toggling RFP as it is a **_global_** switch and _mostly_ runtime (I don't think anything requires a new session), so open tabs will lose protections and cause paradoxes and issues (such as workers can retain the original RFP instance, while the document doesn't)

**Comment by Thorin-Oakenpants** [comment]
here's the js file that is loaded, enjoy :)
- https://sendspace.com/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=69114d3d8ab9555d

**Comment by Thorin-Oakenpants** [comment]
Not convinced it's timing - I can trigger the same result by lying about my timezone (via extension which is of course can leak) - I could try to see what happens if I change my system timezone and restart the browser and see if the protection is related to IPs and expected timezones
- https://support.mozilla.org/en-US/questions/1269260 gave me the timezone idea

**Comment by rusty-snake** [comment]
UA tampering can cause this too, https://support.mozilla.org/sw/questions/1347179. However if I fake my betafox to `Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0` (RFP) I still solve the challenge.

If I start my betafox with `TZ=NZ` (maybe a linux only hack) I still solve the challenge.

**Comment by Thorin-Oakenpants** [comment]
On Windows, just change your timezone .. right click the clock, follow your ninja intuition .. and THEN restart the browser. The TZ environment hack is linux only AFAIK. When I lied about my timeZone (albeit with an extension), I did not get to the challenge. The problem, well at least the first one, is that the page keeps reloading. If you do get to the challenge, IDK if you can solve that with RFP - I never tried

**Comment by fxbrit** [comment]
FYI I opened an issue on gitlab's side, which also mentions what's discussed in this issue. hope y'all don't mind it.
I'll also reach out to cloudflare asap to see what they have to say.

if you want to have a look -> https://gitlab.com/gitlab-com/www-gitlab-com/-/issues/12422

**Comment by Thorin-Oakenpants** [comment]
they're not going to do anything about it, including your gitlab one. no-one gives a fuck about people tweaking their browsers, and all tor users are kiddie fiddlers and druggies and tor is used for evil, and all they care about is blocking bots and proving you're human. No one cares about 0.0001% of traffic

**Comment by Thorin-Oakenpants** [comment]
this is not something that is going to get fixed, regardless of who it is, cloudflare, gitlab, etc. Bugs or info about this should be kicked upstream, closing

**Comment by Thorin-Oakenpants** [comment]
FYI from fxbrit - https://community.cloudflare.com/t/resistfingerprinting-vs-cloudflare-challenge/306354/7

**Comment by KOLANICH** [comment]
I have stopped using GitLab sice they have introduced this malicious antifeature and continued the malicious behavior of migrating functionality into JafaScript.

**Comment by SakhJack** [comment]
btw using [Privacy Pass](https://privacypass.github.io/) doesn't help either

**Comment by Thorin-Oakenpants** [comment]
^ which is ironic because that's their own suggestion

**Comment by SakhJack** [comment]
can access `steamdb.info` again maybe they fixed it on their end

**Comment by Thorin-Oakenpants** [comment]
`privacy.resistFingerprinting.exemptedDomains` is [temporary, only for testing](https://bugzilla.mozilla.org/show_bug.cgi?id=1635603#c12) - it's not even hooked up, it's barely past the stage of just creating the prefs.

Timezone is special and [requires more changes](https://bugzilla.mozilla.org/show_bug.cgi?id=1709867)
> so I dug in a little bit on TimeZone, which is one of the ugliest/dirtiest hacks that we have for RFP. When we first started spoofing timezone (or at least, when we uplifted it in Bug 1330890), we used the environment variable.
> 
> Some browser 'stuff' implicitly uses the TZ environment variable (like system file dialogs) - so if we want those to be accurate, we can't edit that

**Comment by mimecry** [comment]
i get the same result as rusty - `user_pref("dom.enable_resource_timing", false)` caused the loop to occur on a new and otherwise blank profile

**Comment by Thorin-Oakenpants** [comment]
same old story: https://old.reddit.com/r/firefox/comments/pt40os/firefox_beta_developper_cant_connect_to_gitlab/

**Comment by mimecry** [comment]
i meant for myself. just tried it and seems to work okay now

**Comment by FrBst** [comment]
In case someone with the same problem as me finds this page:
Cloudflare was blocking me because of a user-agent switcher. If you use one, try to disable it and test. In my case RFP + no agent-switcher works fine

**Comment by KOLANICH** [comment]
I'm not wn expert in that, in fact I have never used this trick personally, but analysis of source code of some projects in Python has given a clue that one of the ways to bypass Cloudflare fingirprinting is to use TLS libraries with abilities to fake TLS fingerprints and use the fingerprint of Chrome. And those projects execute no JS, it seems that just faking Chrome TLS fingerprint is enough to persuade Cloudflare software nit to present the fingerprinting page.
