### ISSUE TITLE
Keepa not loading, strange behavior of security.tls.enable_0rtt_data

### ISSUE THREAD

**Issue by Coggi** [arkenfox/user.js#1254]
Hi,

i'm on latest Firefox and latest user.js.
I've got a problem with  Keepa the Amazon price tracker, both the website and the Firefox extension.

The site won't load at all and after a while loading it will throw a websocket error 1006.

I've tryied troubleshooting using the troubleshooter script and found a strange behavior.
Whenever I flip the about:config option security.tls.enable_0rtt_data while the site is loading or when the error is shown then the site will load (even if with missing pictures). 

It doesn't matter if the flip is from true to false or viceversa, if you flip it will party load if not (ex reloading after it loaded) it stays stuck forever

To be fair i'm a bit lost here, never encountered such strange behavior

Can anyone point to some advice to track down the problem?

Thank you

**Comment by Thorin-Oakenpants** [comment]
Do I need an amazon account to be able to test this? I've never used the Keepa addon. I need a little more info on steps to reproduce and what to expect. Let's ignore missing pictures and `security.tls.enable_0rtt_data` for now.

websocket was keyed to FPI in FF92 [1721858](https://bugzilla.mozilla.org/show_bug.cgi?id=1721858) - where does this throw the error? in the console

My first suggestion is to test if FPI. A lot of permissions/storage etc is keyed by origin attributes like FPI - this may affect your extension data. So what I would if I were you, is to create a new profile for testing

STR
- create new profile, open FF with it, close FF
- add user.js (the master one here)
- add user.js override to set FPI to false
- open new profile again in Firefox
- install keepa, etc .. test

If everything works, then we know it's related to the bugzilla. If doesn't work, then we can test something else

**Comment by Coggi** [comment]
I'm sorry, 
I got to try and test this right now but it seems to be working, could maybe be an issue with the webiste at the time I wrote my first post :/
Sorry to have wasted your time and thanks for your help

**Comment by Thorin-Oakenpants** [comment]
@Coggi fyi: https://palant.info/2021/10/05/abusing-keepa-price-tracker-to-track-users-on-amazon-pages/
