### ISSUE TITLE
firefox suggest

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1257]
moving to a separate topic for v92

[fxbrit said](https://github.com/arkenfox/user.js/issues/1248#issuecomment-926622341)
---

FIY: quicksuggest aka "Firefox Suggests"

- `browser.urlbar.quicksuggest.enabled` controls wether the UI is shown or not (screenshot to follow). I _think_ it works as a master switch for the whole feature but I haven't done any in depth testing.
- the above pref is also controlled by `browser.urlbar.quicksuggest.scenario` which can be set to `online`, `offline` or `history`, and which enables the quicksuggest experiment (I call it experiment cause that's what firefox calls it in its source code). even if I set `browser.urlbar.quicksuggest.enabled` to false with a .cfg file (both `defaultPref` and `pref`) that value would be changed to true based on the scenario.
- couldn't bother doing any super in depth testing but after a few fresh installs with different .cfg files I found that the only way to prevent that experiment from being enabled was to set the scenario to an empty string using `pref` (otherwise overwrote, but it doesn't matter for user.js files and I was just being precise). so `browser.urlbar.quicksuggest.scenario` = `""`, which guarantees that `browser.urlbar.quicksuggest.enabled` = `false`.
- `browser.urlbar.suggest.quicksuggest` and `browser.urlbar.suggest.quicksuggest.sponsored` control the checkboxes in the UI (again screenshot to follow)
- `browser.urlbar.groupLabels.enabled` didn't do anything for me, although I've read online a few times that it is used to control firefox suggests. no idea.

finally the screenshot (Settings > Privacy & Security > Address Bar) :

![screen](https://user-images.githubusercontent.com/16656956/134841930-c5902104-4ea4-4b07-ac93-2effa76f5e00.png)

when the experiment is enabled "Address Bar" name changes to "Address Bar - Firefox Suggests".

**Comment by Jee-Hex** [comment]
> 
>   *  `browser.urlbar.groupLabels.enabled` didn't do anything for me, although I've read online a few times that it is used to control firefox suggests. no idea.
> 

Flipping this to false hides the "Firefox Suggest" label in the address bar in FF92.

https://www.ghacks.net/2021/09/09/how-to-disable-firefox-suggest/

**Comment by mimecry** [comment]
> 
> 
> > * `browser.urlbar.groupLabels.enabled` didn't do anything for me, although I've read online a few times that it is used to control firefox suggests. no idea.
> 
> Flipping this to false hides the "Firefox Suggest" label in the address bar in FF92.
> 
> [ghacks.net/2021/09/09/how-to-disable-firefox-suggest](https://www.ghacks.net/2021/09/09/how-to-disable-firefox-suggest/)

right, and it requires a reset to take effect. as a FYI, you can also hide it via CSS

```css
.urlbarView-row[label="Firefox Suggest"]::before{ display: none !important; }
.urlbarView-row[label="Firefox Suggest"]{ margin-top: 0 !important; }
```

**Comment by Thorin-Oakenpants** [comment]
> `browser.urlbar.quicksuggest.enabled` controls wether the UI is shown or not (screenshot to follow). I think it works as a master switch for the whole feature but I haven't done any in depth testing.

So is this the master switch or not? Anyone? Feel free to look at the source, otherwise I'll see if I can get around to it in the next four weeks and then put out a v92 - TIA

**Comment by Thorin-Oakenpants** [comment]
On the two checkboxes

```
user_pref("browser.urlbar.suggest.quicksuggest", false);  // <- top checkbox
```

This is enough AFAICT. This is the top checkbox, the sponsored child checkbox is shown as unchecked at runtime. The value in about config is simply it's state should you flip the parent on.

```
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false); // <- sub-checkbox (IF the parent checkbox is checked)
```

We could add the sponsored one as a pair

The sponsored checkbox one remembers it's state, but if the top one is unchecked (either manually or via user.js on startup), when you look at settings in runtime, both are unchecked

**Comment by Thorin-Oakenpants** [comment]
>The pics only showed

The first pic clearly shows a `Firefox Suggest` group label, the second image clearly shows a `Sponsored` label for eBay under the item listed in the `Firefox Suggest` group

I don't really care about if a restart is required or not, because the pref is useless for our purposes. If you want contextual (which is from a local list), then at least let that shit be labeled :)

**Comment by fxbrit** [comment]
new UI from 94.0.2:

<img width="696" alt="ugh" src="https://user-images.githubusercontent.com/34379516/142617859-40158342-674b-4133-a698-f90a743d98b4.png">

- first switch is controlled by `browser.urlbar.suggest.quicksuggest.nonsponsored`
- second switch is controlled by `browser.urlbar.suggest.quicksuggest.sponsored`
- third switch is controlled by `browser.urlbar.quicksuggest.dataCollection.enabled`
- UI can still be hidden using `browser.urlbar.quicksuggest.enabled`
- `browser.urlbar.quicksuggest.remoteSettings.enabled` might stop opt in? the previous workaround that I reported (with `browser.urlbar.quicksuggest.scenario` did not do the trick)

**Comment by Thorin-Oakenpants** [comment]
is this from https://bugzilla.mozilla.org/show_bug.cgi?id=1735976 ?

**Comment by fxbrit** [comment]
yup. unless you want to block suggestions from firefox or enforce the dataCollection pref the current setup is good.

also, not very relevant for arkenfox but as a follow up to my previous comment, neither of the above prefs could prevent opt-in my later tests. I evened tried with `browser.urlbar.quicksuggest.scenario = history` but it got set back to `offline`, which means opted in without on boarding dialog being presented ([see here for scenario-prefs combinations](https://searchfox.org/mozilla-central/source/browser/components/preferences/tests/browser_privacy_firefoxSuggest.js)).

**Comment by Thorin-Oakenpants** [comment]
I'm happy with the prefs we set so far. I've monitored my test FFs to see what happens, and my main FF - e.g. i can't find it now, but I noticed one of my profiles has a bunch of files for categories of suggestions. So far nothing like that has been downloaded in my main arkenfoxed FF, and I haven't been prompted to opt in

I noticed that bugzilla a few days ago, and was going to address it in FF96 diffs, but happy to reopen this as a reminder

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1735976 was added to beta, and will be handled in 94-95 diffs

**Comment by Thorin-Oakenpants** [comment]
> There seems to be something wrong with the description here

The "work" refers to "live search" - and AFAICT this is real time search results from the search engine - that's what "LIVE" search means.

I just tested. Both prefs off .. silence ... one pref on .. silence ... both prefs on live results per keystroke

**Comment by Thorin-Oakenpants** [comment]
so using some common sense ... we are setting at least one of the prefs to false .. so by your logic we are deliberately breaking the location bar so it can't be used
