### ISSUE TITLE
changelog: v92, v93

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1263]
changelog: v92, v93

* date: 11-October-2021
* foreword: These are all the changes since the last changelog ([v91](https://github.com/arkenfox/user.js/issues/1250)).

[FF92 release notes](https://www.mozilla.org/firefox/92.0/releasenotes/)
[FF92 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/92)
[FF92 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2021-38/)

[FF93 release notes](https://www.mozilla.org/firefox/93.0/releasenotes/)
[FF93 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/93)
[FF93 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2021-43/)

---

### CHANGELOG
- [[all changes 91-92](https://github.com/arkenfox/user.js/compare/91.0...92.0)]
- [[all changes 92-93](https://github.com/arkenfox/user.js/compare/92.0...93.0)]
- links to bugzilla tickets and default pref changes in Firefox are in our ToDo diffs issues
   - [ToDo: diffs FF91-FF92](https://github.com/arkenfox/user.js/issues/1249) issue
   - [ToDo: diffs FF92-FF93](https://github.com/arkenfox/user.js/issues/1261) issue
- for all the rest see the full list of pref changes below

:star: your friendly reminder to run prefsCleaner

---

### OTHER NEWS

- @practik added some missing `[SETTING]` tags in #1260 and https://github.com/arkenfox/user.js/commit/8404e8a59c6c54142594f6a856bb50b46227b130 :cake:
- @a1346054 made improvements to prefsCleaner and tidied up some files in #1255 and #1258 :beer:
   - and thanks @Xathros1 tested and picked up a bug :pizza:

---

### ALL CHANGES

- new in user.js v92
  - see #1257
```js
user_pref("browser.urlbar.suggest.quicksuggest", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
```

- made active in user.js v92
   - see #1251
```js
   // user_pref("network.proxy.failover_direct", false);
```

- moved to `9999: DEPRECATED / REMOVED` in user.js v93
```js
   // user_pref("security.ssl3.rsa_des_ede3_sha", false);
```

---

### STATS

```
 STATS v92/v93: up to and including section 4500, minus the parrots
 =========
    total: 233
 inactive:  49
           ---
   active: 184
  default:  13 (at least)
      n/a:   2 (of the three prefs in 0204, only one will apply)
           ---
  flipped: 169 (at most)
```

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/wiki/4.1-Extensions
> ```diff
> -* Neat URL
> -   * [outdated](https://github.com/Smile4ever/Neat-URL) and covered by ClearURLs and uBlock Origin's `AdGuard URL Tracking Protection`
> +* Neat URL, ClearURLs
> +   * redundant with uBlock Origin's `removeparam`
> ```

ClearURLs is only redundant with uBlock Origin's `removeparam` and Skip Redirect (or Request Control rules).

> import Actually Legitimate URL Shortener Tool

Nice. I think I can minimize [my list](https://codeberg.org/rusty-snake/firefox-config/src/branch/main/assets/uBlockOrigin:queryprune.txt).

**Comment by g-2-s** [comment]
^ Fantastic, that's 1 extension less! Now, is there a way to manage cross-origin referers within Firefox itself so I can get rid of Smart Referer as well?

**Comment by rusty-snake** [comment]
If you do not need exceptions, the user.js does it already for you

https://github.com/arkenfox/user.js/blob/85438d00e457bff692303af519da618c6372476b/user.js#L606-L612

And if you use a hardened TC, SR is already redundant.

**Comment by crssi** [comment]
@rusty-snake What does SR stands for?

Thank you

**Comment by rusty-snake** [comment]
Jup

**Comment by Thorin-Oakenpants** [comment]
ugh ..

- ~~https://github.com/ClearURLs/Rules/blob/master/data.json~~ wrong file
- https://github.com/ClearURLs/Rules/blob/master/data.min.json <-- this one

**Comment by gwarser** [comment]
@Thorin-Oakenpants please don't even suggest importing this list. It's obviously in wrong format (JSON).

**Comment by rusty-snake** [comment]
If you want to import data.min.json into µBlock origin, you need to convert it:

```bash
jq -r '.providers | .[] as {urlPattern: $urlPattern, rules: $rules} | $rules[] | "/" + $urlPattern + "^/$removeparam=/^" + . + "=/" ' < data.min.json > data.min.json.ublock_origin.txt
```

https://gist.githubusercontent.com/rusty-snake/91f738b288c150fc1c95fd9b5b5729a0/raw/b3e2f5a68e217e44ec899c1ebf4d52a95c1d8922/data.min.json.ublock_origin.txt

**Comment by Thorin-Oakenpants** [comment]
> @Thorin-Oakenpants please don't even suggest importing this list (ClearURLs). It's obviously in wrong format (JSON).

That's why I pay you guys the big bucks. Edited original with correct link, removed last post (even though I did mention the format - i am not a uBO filter list expert)

**Comment by Thorin-Oakenpants** [comment]
> > As :pants: said she has one site that does a lot
> 
> True, hasn't always been that way, only recently. I would say I scored an easy million or two off Arstechnica - sometimes I find myself reading comments for half an hour - don't know when it started, but I'm not a heavy user of that site at all

FYI: just thought I would update on this - turns out that blocking "cookies" caused it, which I had been doing for years, so clearly something changed on the site - since I moved to dFPI (where cookieBehavior = 5) it doesn't happen
