### ISSUE TITLE
Size of Windows with RFP

### ISSUE THREAD

**Issue by Loki-L1130** [arkenfox/user.js#1268]
When using `privacy.ResistFingerprinting` pref in `user.js`, Everytime the browser starts it opens in a Fixed Windows size like in Tor Browser. Is it Possible to change to a Default one - I mean Full Screen ?

**Comment by rusty-snake** [comment]
- IDK any way on about:config.
- There's a webext API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/WindowState
- Maybe there is already an extension on AMO or you can write one yourself.
- External Tools are Window-Manger rules, X11 magic, Shell Extensions, ...

**Comment by Thorin-Oakenpants** [comment]
We bumped the max values for newwin in #1286 for v95+
