### ISSUE TITLE
Log out problem

### ISSUE THREAD

**Issue by Sehrail** [arkenfox/user.js#1272]
Ever since I started using this user.js, it keeps auto-logging out of some sites I've logged into.
delete cookies off
Sites I check out:
Whatsapp web
Mastodon
Tutanota
discord

**Comment by Thorin-Oakenpants** [comment]
did you look at the override recipe [🔻 keep cookie + site data exceptions on close](https://github.com/arkenfox/user.js/issues/1080)

**Comment by Thorin-Oakenpants** [comment]
did you read https://github.com/arkenfox/user.js/issues/1223
- which reminded me after I saw this [reddit post](https://old.reddit.com/r/PrivacyGuides/comments/qowj0v/arkenfox_userjs_help_keeping_cookies_for/)

**Comment by Sehrail** [comment]
@Thorin-Oakenpants  sorry I dont understand, Can you describe it in a simpler way?

**Comment by Thorin-Oakenpants** [comment]
> Can you describe it in a simpler way

Be aware that some sites only allow session logins. I don't use the sites you mention above, so I can't specifically comment on them.

here is the link I gave you, so it;s all on one page for you

> 🔻 keep cookie + site data exceptions on close
> - Add exceptions as `Allow`
>    - via website > Ctr-I>Permissions > Set cookies > Allow
>    - via about:preferences#privacy > Cookies and Site Data > Manage Exceptions
> - FPI syntax should be `https://example.com^firstPartyDomain=example.com`
> 
> ```js
> /* override recipe: keep some cookies + other site data on close ***/
> user_pref("network.cookie.lifetimePolicy", 2); // 2703
> user_pref("privacy.clearOnShutdown.cookies", false); // 2802
>   // user_pref("privacy.clearOnShutdown.offlineApps", true); // 2802 optional
> user_pref("privacy.cpd.cookies", true); // 2803 Ctrl-Shift-Del
>   // user_pref("privacy.cpd.offlineApps", true); // 2803 Ctrl-Shift-Del optional
> ```

So you made sure that cookies weren't deleted on close = `user_pref("privacy.clearOnShutdown.cookies", false); // 2802` - that great - so therefore you shouldn't be losing _any_ cookies

---

Maybe someone else can walk you through it, _but I'm done troubleshooting for others with practically zero information_

Read: https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting

First: establish that arkenfox causes it
- Did you test it in a new profile without arkenfox and make sure the problem does not exist?
   -  not needed, we know a new profile does not delete cookies
- Did you then add arkenfox and make sure the problem does exist?
   - not needed, we know arkenfox clears all cookies on shutdown
- But the point is to use a new profile without extensions and a clean unmodified arkenfox for testing/troubleshooting

Then, did you search the user.js, repo, wiki
- user JS has a cookie delete on close pref, that looks promising
- great, there's an override recipe to delete all cookies on close except those you want to keep, that looks promising

**Comment by Thorin-Oakenpants** [comment]
> delete cookies off

how did you change this - you need to do it in the user.js, because the user.js overrides any manual changes on startup - did you read the [wiki page on how a user.js works](https://github.com/arkenfox/user.js/wiki/1.1-Overview#small_orange_diamond-what-is-it-what-does-it-do-and-why-would-i-want-one)
