### ISSUE TITLE
Keep cookies on V94

### ISSUE THREAD

**Issue by IceDBorn** [arkenfox/user.js#1278]
Is there a way to keep cookies on V94? On previous versions I changed `user_pref("privacy.clearOnShutdown.cookies", true)` to false and I could keep cookies for specific sites using CookieAutoDelete. As of V94, this setting is false by default and I can't seem to find a way to keep cookies for specific sites.

**Comment by Thorin-Oakenpants** [comment]
all cookies are session only now: so you need to add exceptions for those sites you want: e.g. to auto-login

you add them to exceptions in `Cookies + Site Data`, as `Allow`

https://github.com/arkenfox/user.js/blob/4b393b9b1220481bf544153893995ba2e4bff7d8/user.js#L868-L875

**Comment by Thorin-Oakenpants** [comment]
unless you want to keep ALL cookies, this is way better for sanitizing (so you're not re-IDed in subsequent sessions by state tracking)

if you do want to keep ALL cookies, just flip the lifetimePolicy pref to `0`

**Comment by IceDBorn** [comment]
I already tried adding sites to the allow list but it still deletes them.

**Comment by IceDBorn** [comment]
![image](https://user-images.githubusercontent.com/51162078/143272465-df91109f-272c-4248-a544-6c30305bc954.png)

**Comment by rusty-snake** [comment]
> ***If using FPI the syntax must be https://example.com/^firstPartyDomain=example.com***

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/1223#issuecomment-890475619

**Comment by Thorin-Oakenpants** [comment]
in arkenfox v96 we're going to be switching from FPI to dFPI, so you might as well keep the existing ones to save doing them again (dFPI can't use the FPI syntax - yet, and certainly not in v96)

or
- it's simple to edit them in the sqlite file (while FF is closed)
- or switch to dFPI now (override recipe)
- or change the lifetime pref to 0 until we reach v96

**Comment by IceDBorn** [comment]
Thanks a lot!

**Comment by Thorin-Oakenpants** [comment]
see #1281

**Comment by theltalpha** [comment]
Hallo! Sorry if this has been asked elsewhere: Are the site data exceptions set via the Firefox UI something that would be affected by `user_pref("privacy.clearOnShutdown.siteSettings", true);` or are they kept regardless of this setting?

**Comment by rusty-snake** [comment]
backup and test ;)

siteSettings = permissions¹, content preferences (zoom, ...?), dom push notifications, security settings (hsts, ...?), cert exceptions

¹ "site exceptions" are permissions

**Comment by theltalpha** [comment]
> backup and test ;)

True! Just am not able at the moment and was impatient to learn. ;-) So thanks for the clarification!

**Comment by rusty-snake** [comment]
HSTS is stored in `SiteSecurityServiceState.txt` so you could sanitize it with an shell-script. 

Why do you want to clear HSTS?

**Comment by Thorin-Oakenpants** [comment]
HSTS is isolated by first party with FPI
HSTS is isolated with network partitioning (if you're not using FPI)

What are you trying to achieve by clearing HSTS?

**Comment by theltalpha** [comment]
Hi! Thank you for the clarification. Clearing HSTS is based on these considerations: [How to prevent HSTS tracking in Firefox](https://www.ghacks.net/2015/10/16/how-to-prevent-hsts-tracking-in-firefox/) ans solution 2. presented therein. But the article is from 2015, and I never investigated if in the meantime more appropriate solutions could be applied (which seems the case through FPI, if I understand Thorin-Oakenpants correctly).

**Comment by rusty-snake** [comment]
If you use https_only_mode (default in the arkenfox user.hs), the HSTS tracking described in https://arstechnica.com/information-technology/2015/01/browsing-in-privacy-mode-super-cookies-can-track-you-anyway/ is limited to sites where you added an exception (i.e. site you load via http). All other sites will get a white id.

**Comment by Thorin-Oakenpants** [comment]
^^ I was just about to post that. 

> There are two things that give his cookies super powers. The first is that once set and depending on the specific browser and platform it runs on, the cookies will be visible even if a user has switched to incognito browsing. The second is that the cookies can be read by websites from multiple domain names, not just the one that originally set the identifier.

FPI/dFPI removes the cross-domain aspect. And most sites are already HTTPS... and I didn't get as far as looking into HTTPS-only mode and what all of that means
