### ISSUE TITLE
update WebRTC

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1282]
with a lot of help from @fxbrit - this issue is to lay out the info for the changes for the commit to refer to

🔹 final patch
```js
/* 2001: disable WebRTC (Web Real-Time Communication)
 * Firefox uses mDNS hostname obfuscation on desktop (except Windows7/8) and the
 * private IP is NEVER exposed, except if required in TRUSTED scenarios; i.e. after
 * you grant device (microphone or camera) access
 * [SETUP-HARDEN] Test first. Windows7/8 users only: behind a proxy who never use WebRTC
 * [TEST] https://browserleaks.com/webrtc
 * [1] https://groups.google.com/g/discuss-webrtc/c/6stQXi72BEU/m/2FwZd24UAQAJ
 * [2] https://datatracker.ietf.org/doc/html/draft-ietf-mmusic-mdns-ice-candidates#section-3.1.1 ***/
   // user_pref("media.peerconnection.enabled", false);

/* 2002: force WebRTC inside the proxy [FF70+] ***/
user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy", true);

/* 2003: force a single network interface for ICE candidates generation [FF42+]
 * When using a system-wide proxy, it uses the proxy interface
 * [1] https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate
 * [2] https://wiki.mozilla.org/Media/WebRTC/Privacy ***/
user_pref("media.peerconnection.ice.default_address_only", true);

/* 2004: force exclusion of private IPs from ICE candidates [FF51+]
 * [SETUP-HARDEN] This will protect your private IP even in TRUSTED scenarios after you
 * grant device access, but often results in breakage on video-conferencing platforms ***/
   // user_pref("media.peerconnection.ice.no_host", true);
```

🔹 not in patch, just FYI
```js
/* FYI: this is the pref for mDNS
 * [1] https://bugzilla.mozilla.org/1554976 <- BUGZILLA ***/
   // user_pref("media.peerconnection.ice.obfuscate_host_addresses", true); // [DEFAULT: true desktop]
```

🔹 logic/reasons

All desktop users (ignoring win7/8) will NEVER leak their private IP unless they grant access: i.e it is a TRUSTED scenario, and even then it may not be used (test): it's not as if you are providing that info for all sites you visit - i.e not a tracking vector or stable FP metric. And none of this makes any sense unless your are protecting your public IP

The API itself will be inactive: with a setup harden for win7/8 users, who should test first: and obviously they wouldn't be WebRTC users if they want to kill the API - but again, it's rather (I say completely) pointless if they're not masking their public IP

That leaves how to harden the private IP when using a proxy. Of the three prefs, one is likely to cause breakage, so that can be inactive with a setup harden. Again, this is only ever going to be in a few trusted scenarios - users can test first and harden if they wish

**Comment by Thorin-Oakenpants** [comment]
in a nutshell
- AF only caters for desktop
- FF uses mDNS for desktop (except Win7/8.*)
- Hiding your private IP is therefore covered (except Win7/8.*)
  - i.e when you are not accepting/initiating WebRTC video/audio - i.e it is user initiated
- TEST first
   - I am on win7, and I am not leaking a private IP address (when not sharing video/audio)
     - https://www.ovpn.com/en/webrtc-leak-test
     - https://www.expressvpn.com/webrtc-leak-test
     - https://www.experte.com/webrtc-leak
     - https://browserleaks.com/webrtc
     - https://webbrowsertools.com/test-webrtc-leak/
   - IDK why this is

here is a post from earlier: fxbrit said
> most important references from this issue:
> - [mDNS explained](https://datatracker.ietf.org/doc/html/draft-ietf-mmusic-mdns-ice-candidates#section-3.1.1).
> - 2 yo [mDNS ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1588817) at bugzilla.
> - `media.peerconnection.ice.obfuscate_host_addresses` is the pref that controls mDNS. [android is fucked](https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js#497)
> - win7/win8.* doesn't support mDNS at all.
> - [IP is still exposed in this case](https://groups.google.com/g/discuss-webrtc/c/6stQXi72BEU/m/2FwZd24UAQAJ), see [here](https://searchfox.org/mozilla-central/source/dom/media/webrtc/jsapi/PeerConnectionMedia.cpp#381). if you're sharing the screen I think it's fair to assume that using the private IP is not an issue.
> - `media.peerconnection.ice.proxy_only_if_behind_proxy` should stay imo, it only proxies webrtc inside the proxy / vpn. see [this comment](https://www.reddit.com/r/firefox/comments/8hjh3h/google_voice_psa_if_you_have_been_recently_having/), although it is from the pre mDNS era.

**Comment by Thorin-Oakenpants** [comment]
> I am not so sure, but still I think that in this case hiding private IP is not pointless. Or is it?

Sure, there will always be edge cases, But _**IF**_ you leak a private IP address, that will add to fingerprinting - but leaking your public IP is going to be far more damaging IMO - it depends on how unique your private IP is vs your public one.

It's pointless in the context of being worried about leaking a private IP but not the public one - you've got your priorities back to front.

**Comment by fxbrit** [comment]
so it works like this:

- whether you use a VPN or not, mDNS always kicks in and it protects your private IP by returning N/A...
- ...until you allow mic OR camera access, then it will need a private address. 
    - if you have a VPN it will grab two -> yours and the other one is probably at the VPN provider (not sure).
    - if you have a VPN and you use ice.default_address_only it will grab one -> the VPN provider one (again not sure).
    - if you do NOT have a VPN it will grab one -> yours.
    - if you do NOT have a VPN ice.default_address_only does nothing and it will grab one -> yours.
    - media.peerconnection.ice.no_host always returns N/A, whether you have a VPN or not -> it causes breakage and it often needs to be reverted for webrtc to work.

**Comment by Thorin-Oakenpants** [comment]
> .until you allow mic OR camera access, then it will need a private address. 

shouldn't that be `AFTER you allow .... it then needs a private address`

**Comment by Thorin-Oakenpants** [comment]
> `media.peerconnection.ice.no_host` always returns N/A, whether you have a VPN or not -> it causes breakage and it often needs to be reverted for webrtc to work

OK, so this is the one that needs a `[SETUP` tag, and we maybe make it inactive (for hardening) - i,e if you intend to use WebRTC you want it to work

**Comment by Thorin-Oakenpants** [comment]
so
- we don't need a setup tag on the webRTC API itself IMO (sorry win7/8 users)
   - maybe drop the note about being pointless as assumed
   - or clarify that if you are masking your IP, then the proxy should be doing the job, otherwise what is the point if you're tkaing basics like masking your IP
- 2002 and 2003 are VPN related and safe to have flipped, i.e no breakage
- 2004 is the one that breaks shit

```js
/* 2001: disable WebRTC (Web Real-Time Communication)
 * Firefox uses mDNS hostname obfuscation on desktop (except Windows7/8) and the private IP
 * is not exposed. It is only after you allow mic or camera access they it may be required
 * [TEST] https://browserleaks.com/webrtc
 * [1] https://groups.google.com/g/discuss-webrtc/c/6stQXi72BEU/m/2FwZd24UAQAJ
 * [2] https://datatracker.ietf.org/doc/html/draft-ietf-mmusic-mdns-ice-candidates#section-3.1.1 ***/
   // user_pref("media.peerconnection.enabled", false);

/* 2002: force WebRTC inside the proxy, when one is being used [FF70+] ***/
user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy", true);

/* 2003: something something when using a proxy***/
user_pref("media.peerconnection.ice.default_address_only", true);

/* 2004: something something
 * [SETUP-HARDEN] something
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1189041,1297416,1452713
 * [2] https://wiki.mozilla.org/Media/WebRTC/Privacy
 * [3] https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-12#section-5.2 ***/
   // user_pref("media.peerconnection.ice.no_host", true); // [FF51+]
```

that's a lot of references
need help with the `something something`s

**Comment by fxbrit** [comment]
- `media.peerconnection.ice.default_address_only`: "limit ICE candidates to the default interface only" [according to mozilla](https://wiki.mozilla.org/Media/WebRTC/Privacy), but it's not that good lol. [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1189041) might also help you with wording. btw reading that link, do you want to mention something about within-LAN calls potentially going through TURN servers? in theory a non issue as long as the call is encrypted and the server isn't malicious, but I'm not super familiar with TURN.
- `media.peerconnection.ice.no_host`: "eliminate all local addresses from the candidates" (from same link as above) sounds good. I would write:
    > [SETUP-HARDEN] This will protect your private IP address even when you allow microphone or camera access, which often results in breakage on video-conferencing platforms.

**Comment by fxbrit** [comment]
> what's not so good about it? can you elaborate

it isn't a very understandable description, but it could be passable for lack of a better one I guess.

**Comment by Thorin-Oakenpants** [comment]
I wanted you to spell it out, now I have to go read it :-(

**Comment by msoxzw** [comment]
I suggest `media.peerconnection.ice.relay_only`: only generate relay (TURN) candidates for ICE, so neither private IP nor public IP will be leaked.
It seems that many popular WebRTC based applications support TURN servers.
I have ever observed that some websites abuse WebRTC STUN servers to occupy upload bandwidth, ads delivery, etc. without user consent.

**Comment by rusty-snake** [comment]
```js
/* 2005: only generate relay (TURN) candidates for ICE
 * [SETUP-HARDEN] Not all WebRTC services support this  <--- but you can set your own with media.peerconnection.use_document_iceservers=false media.peerconnection.default_iceservers=… AFAIK
 * [1] https://wiki.mozilla.org/Media/WebRTC/Privacy ***/
   // user_pref("media.peerconnection.ice.relay_only", true); // [FF42+] <- confirm
```

**Comment by msoxzw** [comment]
Indeed, not all WebRTC services support this, but a lot of web conferencing services support this, e.g. [Google Meet](https://support.google.com/a/answer/1279090)

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.com/librewolf-community/settings/-/issues/108

I'm proposing zero breakage and that `media.peerconnection.ice.no_host` be inactive - WbeRTC requires user permissions

**Comment by fxbrit** [comment]
> I'm proposing zero breakage

it would fuck over win7 and 8.x users.

**Comment by Thorin-Oakenpants** [comment]
That's the point - we cater to the majority to reduce friction

https://github.com/arkenfox/user.js/issues/1282#issuecomment-982700634
> we don't need a setup tag on the webRTC API itself IMO (sorry win7/8 users)

**Comment by Thorin-Oakenpants** [comment]
Also, as a current win7 user, I am not fucked - see my private convo

**Comment by fxbrit** [comment]
> we cater to the majority to reduce friction

would you really want to leave these users out of this protection for one pref flip tho? we also don't have a clear indication of how much breakage that causes in the real world, maybe it's only a zoom/meet thing.

**Comment by Thorin-Oakenpants** [comment]
> would you really want to leave these users out of this protection

Yes, And I am one of those (except I don't seem to leak on win7 which I won't be on for much longer but currently that is approx 20% for FF)- the FPing on a "drive-by" is secondary here IMO, if your not protecting your IP this doesn't make much if any difference, let's not forget the public IP is far more damaging. So as I said

> I did have a TEST FIRST thing there, and a setup tag, so maybe that could be put back for win7/8 users for the API

Thats the sideshow .. I am more interested in the those who do have mDNS and the `ice.no_host` pref

**Comment by Thorin-Oakenpants** [comment]
OK, here's the deal, commit to follow

All desktop users (ignoring win7/8) will never leak their private IP unless they grant access: i.e it is a TRUSTED scenario: it's not as if you are providing that info for all sites you visit - i.e not a tracking vector or stable FP metric. And none of this makes any sense unless your are protecting your public IP

The API itself will be inactive: with a setup harden for win7/8 users, who should test first: and obviously they wouldn't be WebRTC users if they want to kill the API - but again, it's rather (I say completely) pointless if they're not masking their public IP

That leaves how to harden the private IP when using a proxy. Of the three prefs, one is likely to cause breakage, so that can be inactive with a setup harden. Again, this is only ever going to be in a few trusted scenarios - users can test first and harden if they wish

**Comment by Thorin-Oakenpants** [comment]
@fxbrit do we need to change the win7/8 info (see last PR edit) based on that comment .. and looking at sparkling glitter-gitter disco LW room -> is this what you're referring to ? https://searchfox.org/mozilla-central/source/dom/media/webrtc/transport/mdns_service/src/lib.rs#447

**Comment by fxbrit** [comment]
yes, that's the mDNS implementation in Firefox which covers the fact that older Win versions do not support mDNS natively. so we can remove the `(except Windows7/8)` bit since Android is the only platform without proper obfuscation and you documented that by adding `desktop`.

**Comment by Thorin-Oakenpants** [comment]
>  * Firefox desktop uses mDNS hostname obfuscation on desktop (except Windows7/8)

if I remove the `(except Windows7/8)` part it's not strictly true, is it? Win7/8 does not use mDNS, it uses a built in FF fallback obfuscation

**Comment by Thorin-Oakenpants** [comment]
^ just want to get the wording correct, suggest away

**Comment by fxbrit** [comment]
it uses Firefox's own implementation of mDNS, so it's still correct. I would write:

```
/* 2001: disable WebRTC (Web Real-Time Communication)
 * Firefox desktop uses mDNS hostname obfuscation and the
 * private IP is NEVER exposed, except if required in TRUSTED scenarios; i.e. after
 * you grant device (microphone or camera) access
 * [TEST] https://browserleaks.com/webrtc
 ...
 ```
 so remove the win7/8 bit and the `[SETUP-HARDEN]` tag.

the other webrtc prefs descriptions still apply.

**Comment by Thorin-Oakenpants** [comment]
fuck, I added desktop when it was already there ... this is what happens when you snort sugar

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/pull/1606/commits/4d81df84a4f06128b039f8ca411aa9d9df1cfa64
