### ISSUE TITLE
Graphic?

### ISSUE THREAD

**Issue by Aztekz** [arkenfox/user.js#1283]
I just wanted to know if you would like to get a new icon or logo for the Arkenfox project. I'll be happy to contribute.

**Comment by Thorin-Oakenpants** [comment]
someone mentioned this recently and said something along the lines of "a cute fox holding an arkenstone in it's paws" - now how that comes out in a clean simple icon IDK
- arkenstone being the gem in The Hobbit
- and I'm not necessarily thinking of cut gem images but that sort of imagery might be the easiest to convey what it is

initially my first thought, when we renamed, was a fox curled around an arkenstone like FF's logo of a fox curled around the earth/globe
- but no way do I want to infringe on that fox or be anything too similar

thinking out loud
- arkenfox organization <- IDK if this needs anything
- arkenfox/user.js for Firefox <- fox and arkenstone
- arkenfox/tzp for gecko <- fox and onion
- arkenfox/blog <-- fox and pen (as an example)

It would be quite neat if whatever the fox has in it's paws can be substituted - a round arkenstone / a round onion symbol (a pen is altogether a different shape, not that it has to be a pen - pretty sure everything can be represented in a round object)

It doesn't _have_ to be a fox, it could be a paw with a symbol in it. Or it could be a gem shape with a fox or onion or pen in it, etc. Maybe it's a fox with a whiteboard, and we just stick a symbol on the whiteboard

Knock yourself out, with whatever concept/look you think. Personally I want it clean and simple, and the only difference is the symbol (not sure about color changing, but lets say one part stays constant (the fox which is holding objects), the other changes (the arkenstone, the onion, etc))

here's a polar bear with a globe
 - https://thenounproject.com/search/?q=polar+bear&i=1962534
 - too much going on in there, remove the ground, remove the raindrop, enlarge the globe, stick the globe in his mitts, wrap the whole thing in a circle. Imagine if that was a fox with his bushy tail flowing up on one side of him.

Also everything must be attributable and free license, even if used then transformed
- e.g. https://thenounproject.com/search/?q=fox
- https://thenounproject.com/search/?q=paws
- https://thenounproject.com/search/?q=gems

Knock yourself out, but by all means don't waste too much time on it - get some feedback first

**Comment by Aztekz** [comment]
Alright, here is an initial idea/concept ting (rough),

![arkenfoxtemp](https://user-images.githubusercontent.com/87577318/144134639-c944136d-8e55-4280-a6bc-3154ab48d561.png)

**Comment by Thorin-Oakenpants** [comment]
I just quickly searched for "very simple fox outline" (without the quite marks) and filtered for line drawing. The idea is right, but I'd like something that is very simple (as little as possible) - we won't know without playing around

something definitely a fox, with a space in it to stick something .. the above are too busy

btw - saw this while searching for examples
- https://dribbble.com/shots/14249400-Firefox-Logo-Design - I think a fox holding something is too much happening, requires too much detail
- some ideas in here start to convey what what I mean - https://dribbble.com/tags/fox_icon#
- outline, can be abstract
- I think the tail is the key, it creates a space

some more shit I found to try and explain what I mean - I won't know til I find it (and these aren't it)
![abstract](https://user-images.githubusercontent.com/16656956/144138918-9bf53a21-a3a4-47c7-b182-47bc305fa369.png)

**Comment by Thorin-Oakenpants** [comment]
here's another one, this isn't it, but you see the circle or space?
![anotherone](https://user-images.githubusercontent.com/16656956/144139208-0c2fe337-f5f4-48c2-ac9d-38ff1d1916bb.jpg)

**Comment by Aztekz** [comment]
Somewhat minimalist design. Hmm.

The mid portion of it? Yeah. I kinda understand.

**Comment by Thorin-Oakenpants** [comment]
the mittens? paws, tail, gem/onion/fox shape etc are all ideas on how to balance the image, no-one said to use all of em :) cuteness is subjective and was just what someone said (and I'd rather have a "cite" fox than one that is e.g. snarling or looking like a devil) - there are definitely minimalist designs that don't convey softness/cuteness

Here's another minimalist one that if you completed the circle and filled that in with e.g. to onion logo, or shiny arkenstone
![IDK](https://user-images.githubusercontent.com/16656956/144140571-badb2c6e-fe26-4d20-a90a-27ba56806a42.png)

These are all just ideas

**Comment by Aztekz** [comment]
Alright let me make up a basic template and see how things go from there. Can you include the onion logo and the arkenstone?

**Comment by Thorin-Oakenpants** [comment]
everything must be free license - all the above were just ideas. The onion I will check with Tor Project, but I think they will be fine with the onion svg they use which you can see here - https://blog.torproject.org/new-release-tor-browser-11-0/, but I think I want much thinner lines

the above is not free license and is not quite what I want, it's a bit too geometrically simple - it was to show that if you complete the circle and fill that in (e.g. blue for earth, white for arkenstone, green for an onion), then it would be a fox wrapped around a round object (but I haven;t seen it and it will probably look weird, I won't know until I see one - not saying you have to do one) - I don't have a clue what that is above

This is really low priority, btw

**Comment by Aztekz** [comment]
Yeah they will be. Also take your time with it, give me ideas and we will work through them. I'll come up with some of my own ideas too if that's okay with you?

**Comment by Thorin-Oakenpants** [comment]
I'm just kidding, but it needs to be way more professional, no offence

![all hail](https://user-images.githubusercontent.com/16656956/144150551-cdc01e74-6aab-4d0f-9f21-65c219e1c708.png)

**Comment by dngray** [comment]
I still reckon you need a fox wrapped around an arkenstone.

**Comment by Aztekz** [comment]
Hmm i see. Why not use that by the way? 

Is that the size we are going for? Also I need specific information to create a proper template. What i need is, should `arkenfox` be written out or not, what font to use, what size to use, do we need a specific icon, arkenstone etc?

**Comment by Thorin-Oakenpants** [comment]
No I don't want text, I was just playing around and the logo maker wanted an optional company name and slogan, so I obliged, because never ever give the opportunity to say **_ALL HAIL PANTS_**. The size should be large vectors :) the aspect ratio should be 1:1. 

I don't mind that fox to be honest. These simple outlines can become quite stunning with some color - hence why I prefer a background color - encompassed in some shape). The question is how to get the second element in there - which is what the ideas were for - e.g. paws holding something, or a fox wrapped around something, or a cut gem with a fox/pen/onion symbol

TBH, this is as much a thinking and discovery exercise for me as you. It's not something I have thought that much about and it not high priority

**Comment by Thorin-Oakenpants** [comment]
Here's a [peacock one](https://github.com/arkenfox/user.js/issues/1274#issuecomment-965694513) I did earlier
![peacock](https://user-images.githubusercontent.com/16656956/144393503-a64d4192-911e-48f7-945a-48d312839b93.png)

**Comment by Aztekz** [comment]
Does it have to follow that same template? the color scheme?

**Comment by Thorin-Oakenpants** [comment]
this is not going to work - there are plenty of ways to reach out and get professional icon/vector multipacks - including paying for one, and it is better discussed with the designer and tracked elsewhere. I was already tracking this elsewhere

Thanks for offering to help though :) have a free 🍺
