### ISSUE TITLE
Disable Accessibility Services.

### ISSUE THREAD

**Issue by CyberPunkInterface** [arkenfox/user.js#1284]
### Outcome/Goal to improve *Performance* and improve *Privacy.*

**Comment by Thorin-Oakenpants** [comment]
did you want it added? did you want it removed? are you stating it improves performance and privacy, or arguing that it doesn't?

**Comment by CyberPunkInterface** [comment]
Well I would say have that parameter **added** to disable Accessibility Services. 
Correct me if i'm wrong, but when I imported the Arkenfox files into my fresh new firefox profile and tweaked/checked some of the `about:config` settings I saw `accessibility.force_disabled` = `0` set by default.

**I'm stating it improves performance and privacy** I may be wrong though.

Also would suggest adding these parameters if some aren't already. 

`network.dns.disablePrefetch` = `true`

`network.prefetch-next` = `false`

`identity.fxaccounts.enabled` = `false`

`extensions.pocket.enabled` = `false

`geo.enabled` = `false`

`security.ssl3.rsa_des_ede3_sha` = `false`

`security.ssl.require_safe_negotiation` = true

`network.http.sendRefererHeader` = `0`

`media.gmp-widevinecdm.enabled` = `false`

`media.eme.enabled` = `false`

`webgl.disabled` = `true`

`network.http.referer.XOriginPolicy` = `2`

**Comment by Thorin-Oakenpants** [comment]
> when I imported the Arkenfox files into my fresh new firefox profile and tweaked/checked some of the about:config settings I saw accessibility.force_disabled = 0 set by default.

then you're doing something wrong
https://github.com/arkenfox/user.js/blob/4dc53722573a2bcf0052acdebe41951e94f217a1/user.js#L726-L728

please don't paste lists of prefs at me, check the user.js first: e.g.
https://github.com/arkenfox/user.js/blob/4dc53722573a2bcf0052acdebe41951e94f217a1/user.js#L282-L284

https://github.com/arkenfox/user.js/blob/4dc53722573a2bcf0052acdebe41951e94f217a1/user.js#L1227-L1233

you can do the rest

**Comment by CyberPunkInterface** [comment]
@ Thorin-Oakenpants 

Ok, Thanks.
sorry for prematurely posting.

**Comment by CyberPunkInterface** [comment]
@Thorin-Oakenpants

>then you're doing something wrong

I downloaded the user.js-94.1 folder, unzipped it then copied the continents inside to the {location} on my Firefox profile I just created.

These are the files/folders that I copied over to the location of the Firefox profile directory:

scratchpad-scripts
LICENSE.txt
prefsCleaner.bat
prefsCleaner.sh
README.md
updater.bat
updater.sh
user.js 

**Is this the correct way to do this?**

Thanks.

**Comment by Thorin-Oakenpants** [comment]
Ignoring making changes, as you have done
- new profile (nothing to clean up)
- add user.js to profile

---

I am rewriting the wiki to make things simpler and more clear

basic steps
- make changes in a `user-overrides.js` file
- make sure you're using the right profile: `about:support` -> profile folder -> open folder
- a new profile is best
   - if using an existing profile you can clean it up (the scratchpad script - I merged them into one the other day)
   - prefsCleaner (not needed this time with the merged uptodate cleanup script)
- add the files for your OS
   - user.js <-- paste your overrides at the end
   - user-overrides.js
   - updater
   - prefsCleaner

in future, to keep updated and clean (with FF closed)
- run the updater with `-o` (overrides switch) and you will update to the live master and your overrides will be automatically added at the end
- run prefsCleaner
- read the changelog here if you want
