### ISSUE TITLE
override recipe: dnscrypt-proxy local DoH

### ISSUE THREAD

**Issue by zevlee** [arkenfox/user.js#1295]
I have dnscrypt-proxy installed and I wanted to suggest an override recipe. The lines below will set up DNS-over-HTTPS in Firefox using the local DoH resolver provided by dnscrypt-proxy ([details of Local DoH](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Local-DoH)).

```
/* override recipe: configure dnscrypt-proxy local DoH resolver ***/
user_pref("network.trr.mode", 3);
user_pref("network.trr.uri", "https://127.0.0.1:3000/dns-query"); // make sure to add a security exception in firefox
user_pref("network.trr.custom_uri", "https://127.0.0.1:3000/dns-query");
```

**Comment by Thorin-Oakenpants** [comment]
no thanks: DoH is up to the end user: there are too many variables and not all those prefs are in the user.js, so therefore it's "not my problem" :)

If you want DoH (and other knobs) then there are plenty of other guides out there on how to set one up and who to choose - and hopefully one that explains what the actual benefits are instead wild claims on both sides (for/against). I for one, am happy to not touch this topic with a 100 ft barge pole ;)

https://old.reddit.com/r/PrivacyGuides/comments/ra93m6/is_there_a_reason_why_the_arkenfox_userjs_doesnt/
