### ISSUE TITLE
Help installing af/user.js into firefox linux ubuntu

### ISSUE THREAD

**Issue by satyamevajayate** [arkenfox/user.js#1297]
Hello, when using terminal to unpack I am not able to do it because the file is not considered a folder by the system. I tried installing via GUI, copied into profile and unpacked, but that did not work either. Any help would be appreciated. If you are going to tell me to RTFM don't bother, I tried RTFM and did not find any supporting documentation.

**Comment by Thorin-Oakenpants** [comment]
the wiki is being rewritten, but it should be pretty clear. The user.js and user-overrides.js reside in the profile directory. How you put them there is up to you - but if any linux users wants to help out with steps, then I can use that in the rewrite

Open `about:support`. Under `Application Basics` at the top is a line called `Profile Folder`

**Comment by Nallua** [comment]
Fellow Ubuntu user here. What commands are you using on the terminal, and what's the name of the profile folder you're trying to use Arkenfox with?

**Comment by Onfroygmx** [comment]
First of all, this is not an Ubuntu "problem".

You want to customize FF, you should RTFM!

Baby steps for you:
- make a tmp folder ('mkdir tmp' in the FM)
- go to the folder ('cd tmp' in the FM)
- clone the repository ('git clone https://github.com/arkenfox/user.js.git' in the FM)
- go to the folder ('cd arkenfox' in the wiki)
- copy the user.js to your profile folder ('cp user.js ...' in the wiki)
- And restart FF

Why do you want to unpack anything?
Installing through GUI?

Onf
