### ISSUE TITLE
Problem with small number of pages not loading

### ISSUE THREAD

**Issue by dsfsdbvxc** [arkenfox/user.js#1301]
Hi, i'm pretty new to Arkenfox and looking for a bit of help. I've had a look through the [troubleshooting](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting) doc and managed to resolve most issues, but stuck with this one. Any one able to help out?

When trying to access a few webpages, e.g. [https://www.bbc.co.uk/sport](https://www.bbc.co.uk/sport) the page wont load.

From FireFox console:
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
send moz-extension://94409614-xxxx-xxxx-xxxx-xxxxxxxxxxxx/background.js:2807
background.js:2807

Tried disabling all extensions (recommended ones + Bitwarden), no change

I'm running Arkenfox version 95, FireFox version 95.

Any help apprecaited.

**Comment by Nallua** [comment]
Have you set any overrides for Arkenfox, or made any other changes in Firefox? When I use Arkenfox 95 as-is with a fresh profile, the BBC Sports page you linked loads just fine for me.

Could you try using Arkenfox with no changes in a fresh profile that's never had extensions installed or any other settings tweaked, to narrow down for sure whether or not something in Arkenfox's defaults is messing the page up for you?

**Comment by Thorin-Oakenpants** [comment]
What is moz extension `94409614-2060-42e3-a3fe-c9e89c5692b5`

Open `about:debugging`, click `This Firefox' and tell us which extension this UUID refers to

**Comment by dsfsdbvxc** [comment]
> Have you set any overrides for Arkenfox, or made any other changes in Firefox? When I use Arkenfox 95 as-is with a fresh profile, the BBC Sports page you linked loads just fine for me.
> 
> Could you try using Arkenfox with no changes in a fresh profile that's never had extensions installed or any other settings tweaked, to narrow down for sure whether or not something in Arkenfox's defaults is messing the page up for you?

Thanks for the reply, was helpful knowing it wasn't Arkenfox causing the issue on someone elses device. Found the problem, it's my VPN and the site restricting access by the looks of it. No problems with my VPN dissabled. Didnt think to check this, appologies!

> What is moz extension `94409614-2060-42e3-a3fe-c9e89c5692b5`
> 
> Open `about:debugging`, click `This Firefox` and tell us which extension this UUID refers to

Thanks for that, learn something new every day! Relates to Bitwarden, so nothing that should effect site loading etc.

**Comment by dsfsdbvxc** [comment]
Ok, I'm even more confused.

So I'm based in the UK and when connected to my VPN with a UK exit node, I have the problem connecting to some sites using Firefox, e.g. [https://www.bbc.co.uk/sport](https://www.bbc.co.uk/sport). As before, the page won't load or occasionally partially loads but none of the images appear. The page loads correctly with other browsers so issue seems to be with Firefox.

If I change the VPN exit note to outside of the UK, the page will load fine.

Confirmed the problem using Arkenfox 95 and a fresh profile so don't think its an issue with overrides, but I'm using the following for info:

/*** MY OVERRIDES ***/
user_pref("_user.js.parrot", "overrides section syntax error");
user_pref("browser.startup.page", 1); // 0102
user_pref("keyword.enabled", true);
user_pref("browser.urlbar.suggest.searches", true);
user_pref("browser.sessionstore.privacy_level", 0); // 1003 [to restore cookies/formdata if not sanitized]
user_pref("network.http.referer.XOriginPolicy", 0);
user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001
user_pref("media.eme.enabled", true);
user_pref("media.autoplay.blocking_policy", 0); // 2031
user_pref("browser.download.useDownloadDir", true);
user_pref("network.cookie.lifetimePolicy", 0);
user_pref("privacy.clearOnShutdown.history", false);   // [DEFAULT: true]
user_pref("privacy.cpd.history", false);  // [DEFAULT: true]
user_pref("privacy.resistFingerprinting.letterboxing", false); // [HIDDEN PREF]
user_pref("browser.privatebrowsing.autostart", false)
user_pref("browser.urlbar.suggest.history", true);
user_pref("browser.urlbar.suggest.bookmark", true);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("places.history.enabled", true)
user_pref("media.getusermedia.screensharing.enabled", true); // 2022
user_pref("dom.webaudio.enabled", true); // 2510
user_pref("ui.systemUsesDarkTheme", 1); // [FF67+] [HIDDEN PREF]
user_pref("extensions.pocket.enabled", false); // Pocket Account [FF46+]

**Comment by Thorin-Oakenpants** [comment]
you don't need these in your overrides - they are no longer applied in the user.js (they are commented out) and you are setting them at default values
- run prefsCleaner or reset them in about:config
- I am assuming you are using arkenfox v95+ on FF91+
```js
user_pref("media.peerconnection.enabled", true);
user_pref("media.peerconnection.ice.no_host", false);
user_pref("browser.privatebrowsing.autostart", false)
user_pref("browser.urlbar.suggest.history", true);
user_pref("browser.urlbar.suggest.bookmark", true);
user_pref("media.getusermedia.screensharing.enabled", true); // no longer in user.js
user_pref("dom.webaudio.enabled", true);
```

---

Do you still get the problem in FF without arkenfox but using the VPN? That is create a new profile, load that profile and test over the VPN. You need to establish that it is a pref in AF that causes it.

> the page won't load or occasionally partially loads but none of the images appear

Try this in your overrides
```
user_pref("security.OCSP.require", false);
```

**Comment by dsfsdbvxc** [comment]
Thanks for that, i've removed and updated my overrides.

Ok, so reset Firefox and created a new profile, so a fresh install of Firefox and have the same issue. So it's not caused by ArkenFox, seems to be an issue with the desktop version of Firefox (works fine using Firefox on my phone over the same VPN).

I'll close this as it's not an issue with Arkenfox. Thanks for all the replies, learned a lot allong the way :)

**Comment by dsfsdbvxc** [comment]
> Try this in your overrides
> 
> ```
> user_pref("security.OCSP.require", false);
> ```

Also just to add, setting thos to false fixed the image not loading issue. Thanks.
