### ISSUE TITLE
armorgames.com

### ISSUE THREAD

**Issue by Zelmanyr** [arkenfox/user.js#1304]
Hi,

When I try playing a few games on https://armorgames.com/ with arkenfox the performance is terrible. This is not the case with vanilla Firefox. Can you tell me which user_pref I should change and to which value to restore the performance ? And what do I lose compared to the default from arkenfox (privacy / security wise) ? 

Thank you for your time and effort,
Arkenfox is a beautiful project !

**Comment by Zelmanyr** [comment]
Hi,

Thank you for your recipe, it works great ! I think I will use a secondary browser though to keep RFP enabled.

Thank you for your time and effort.

**Comment by Thorin-Oakenpants** [comment]
I added it to the #1080 so thanks for the nudge

**Comment by fxbrit** [comment]
@MagicalDrizzle yes, lowest hanging fruit (aka canvas)
