### ISSUE TITLE
Question about ETP Strict compared to same settings Custom

### ISSUE THREAD

**Issue by Guest-GT** [arkenfox/user.js#1306]
Does Firefox treat using ETP Strict the same way it would if using ETP Custom with the same settings (eg. Fingerprinters/Cryptominers checked, Tracking Content Block List using Strict in all windows, with cookies set to either block all third party or cross site cookies including social media cookies)?

My reason for asking is because I used to use the same settings under the custom selection and found it a few clicks easier to just change the tracking content block list down to level 1 temporarily when needed for any specific site/page and then back versus now changing from strict to custom to change down to level 1 temporarily when needed and then back to strict.

Not an issue or big deal but I was curious if Firefox handled the same settings used with custom as it does when strict is chosen.

Thank you.

**Comment by Thorin-Oakenpants** [comment]
Not sure. The interface for custom is not all the things that are included: also

https://github.com/arkenfox/user.js/blob/bb56056a68906ddd178f64ab0b016c8bbe9786fb/user.js#L1215-L1216

> My reason for asking is because

Don't do that. ETP is a global setting - use the urlbar's ETP Shield

https://github.com/arkenfox/user.js/blob/bb56056a68906ddd178f64ab0b016c8bbe9786fb/user.js#L785-L790

**Comment by rusty-snake** [comment]
> ```js
> pref("browser.contentblocking.features.strict", "tp,tpPrivate,cookieBehavior5,cookieBehaviorPBM5,cm,fp,stp,lvl2,rp,ocsp");
> ```

- lvl2: GUI hidden by default
- rp: no GUI
- ocsp: no GUI

> My reason for asking is because I used to use the same settings under the custom selection and found it a few clicks easier to just change the tracking content block list down to level 1 temporarily when needed for any specific site/page and then back versus now changing from strict to custom to change down to level 1 temporarily when needed and then back to strict.

Do you disable filterlists in uB? No, you disable uB on that site. Same for ETP.

![Screenshot_2021-12-19_08-23-47-fs8](https://user-images.githubusercontent.com/41237666/146668472-e126db3e-1434-4d37-beb5-104b2165ecb0.png)
