### ISSUE TITLE
Error: "Invalid input data: oid and id" on sites that use Daxab.com embed player

### ISSUE THREAD

**Issue by Ptorr** [arkenfox/user.js#1308]
**Example:** https://biqle.ru/watch/424854486_456239050

**Confirming the problem is caused by the `user.js`**: I've confirmed the issue only happens when I've loaded this script onto a firefox profile. Tried opening a profile without this script and the video was available to play. Then downloaded a fresh instance of this script and created a new profile, loaded it on there and visited the same link to be greeted by the same error. Also tried with Extensions and without, the video plays as long as the profile doesn't have this script.

**Browser version**: 95.0.2
  - **Steps to Reproduce (STR)**: go to https://biqle.ru/watch/424854486_456239050 from the profile you have user.js on and you will see that the video player is replaced by the error mentioned in the title.
  - **actual result**: "Invalid input data: oid and id"
  - **expected result**: a Video player, can be achieved by opening any other Firefox profile.

**Anything else you deem worth mentioning**: It could be that there's some config that's clashing with the display of daxab.com's embed video players in these sites. I come to this conclusion by right-clicking on the error > this frame > open frame in a new tab, that leads me to the daxab.com player.

**Comment by Thorin-Oakenpants** [comment]
what a horrible infested site: clicks redirect, clicks (random links) which are using a full page overlay - I got sent to teen porn sites

The error comes from this: it needs to be at default 0 to not get the error
```
user_pref("network.http.referer.XOriginPolicy", 2);
```

But the player doesn't show an image. To get that you need to disable ETP = not a good idea, look at the shit on that page (in 95 it showed me a cryptominer if I recall correctly - I tested in FF95)

But that's the least of your problems. Sites like this are going to get this treatment: here is nightly (and beta is the same)
![nightly](https://user-images.githubusercontent.com/16656956/146692949-979258f5-14a0-44d9-b23b-34a82d52082c.png)
