### ISSUE TITLE
How to keep cookie for specific websites? [solved: duplicate of 1291, 1278, 1223 add site exceptions]

### ISSUE THREAD

**Issue by ve1la** [arkenfox/user.js#1311]
I want cookies for certain websites and my entire browser history to always be saved, even after restarting my browser.
I can't get cookies to work though. I hope I didn't miss anything in the wikia. Sorry if that's the case. 

  - firefox v95
  - Add a website to cookies --> "manage exceptions", login to that website, close the browser and reopen it.
  - I expect to still be logged in, but I am not.
  - I copy pasted this at the end of the user.js file:
 
```
/* override recipe: enable session restore ***/
user_pref("browser.startup.page", 3); // 0102
  // user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  // user_pref("places.history.enabled", true); // 0862 required if you had it set as false
user_pref("browser.sessionstore.privacy_level", 0); // 1003 [to restore cookies/formdata if not sanitized]
  // user_pref("network.cookie.lifetimePolicy", 0); // 2801 [DON'T: add cookie + site data exceptions instead]
user_pref("privacy.clearOnShutdown.history", false); // 2811
  // user_pref("privacy.clearOnShutdown.cookies", false); // 2811 optional: default false arkenfox v94
  // user_pref("privacy.clearOnShutdown.formdata", false); // 2811 optional
user_pref("privacy.cpd.history", false); // 2812 to match when you use Ctrl-Shift-Del
  // user_pref("privacy.cpd.cookies", false); // 2812 optional: default false arkenfox v94
  // user_pref("privacy.cpd.formdata", false); // 2812 optional

```
Then, I went into settings --> cookies and site data
I added some websites to "manage extensions". On restart though, this list was empty (yes, I did click "save")

Also out of curiosity: I noticed I can't type into the address bar and click "enter" to start a search with my default search engine (duckduckgo), unless I click on the "this time search with" icon. It's fine if it makes me safer/improves my privacy, but out of curiosity, how come tor browser (which I'd expect to be the "safer" of the two) does not disable this? Like, what's the risk in keeping it on?

**Comment by rusty-snake** [comment]
> Add a website to cookies --> "manage exceptions", login to that website, close the browser and reopen it.

If you use FPI, you must use FPI syntax.
- Do you use FPI?
- If yes, did you used FPI syntax?

> I expect to still be logged in, but I am not.

Some sites do not support this or require extra check boxes to be clicked. Make sure to test with this a site that support this (e.g. github).

> I copy pasted this at the end of the user.js file:

You should create a user-overrides.js.

Do you have any other modifications?

> On restart though, this list was empty (yes, I did click "save")

Did you set `privacy.clearOnShutdown.siteSettings=true`?

> Like, what's the risk in keeping it on?

If you enter `http://www.examplecom/private` (note the missing `.` in front of `com`) for example, your search engine now knows that you tried to access it. If you use a privacy respecting search engine and don't do top top secret thinks you can enable it.

**Comment by Thorin-Oakenpants** [comment]
if you use a cross-domain login, you also need to allowlist the cross-domain site: e.g. using FB to log into instagram, you need to allowlist both

[click & look](https://github.com/arkenfox/user.js/issues?q=is%3Aissue+label%3Aanswered)
- #1291 
- #1278 
- #1223
