### ISSUE TITLE
arkenfox comparison to my profile js

### ISSUE THREAD

**Issue by 0xspade** [arkenfox/user.js#1312]
No competitions here, I like to implement the arkenfox profile js to my firefox as default but I want the insight of the guys behind arkenfox profile.

Notice the comparison below:
![comparison](https://user-images.githubusercontent.com/18681023/147407502-d66a6a79-1213-4d0b-a76c-dcfce2c26e68.PNG)

I'm just wondering why my profile hides my IP, but arkenfox is not.

currently using my website's [404 page](https://0xspa.de/notexisting.txt).

**Comment by Thorin-Oakenpants** [comment]
you tell me, it's your website, your code

**Comment by Thorin-Oakenpants** [comment]
I cannot see your user.js, I cannot see your site code. And AF is not trying to hide your IP
