### ISSUE TITLE
ETP switches and dFPI

### ISSUE THREAD

**Issue by githubuniqu** [arkenfox/user.js#1315]
So FPI will make way for dFPI in version 96. I had some silly questions and since there is no separate Q&A section, here's new issue about it, similar to https://github.com/arkenfox/user.js/issues/1306

Will dFPI get disabled if I turn off ETP on any given site? I think site isolation will work fine, disabled for one site but for on for others. Is that the case?
I do this on a site so images can load properly(mind uBO is left untouched). Right now since FPI is enabled, never really bothered to care how ETP switches affects stuff on sites.

Currently in ETP section, I have selected custom mode with third party cookies disabled and all other options enabled. How will that change in strict mode?

Plus Temporary Containers is no longer recommended. So is there an alternative for it or put it another way, it can still be used right, just not as ultra privacy add-on?
I used it most on a streaming site which allows to view 3 videos, after which it asked for login. Thanks to TC I just created another container and all things worked fine. Obviously this is done in a different profile(with no changed prefs) for DRM.

**Comment by Thorin-Oakenpants** [comment]
> Will dFPI get disabled if I turn off ETP on any given site?

I assume you mean the urlbar blue shield - This is something I want to confirm (I did mention it somewhere and I thought it was on my list - I just added it), but the answer is likely yes - it's meant to unbreak sites

At first I thought it was just the Tracking Protection (TP) which is one part of it. But even in standard mode, which doesn't have TP, the urlbar still has a toggle

In about:preferences#privacy when strict is enabled it says (emphasis mine)
> Heads up!
> This setting may cause some websites to not display content or work correctly. If a site seems broken, you may want to turn off _***tracking protection**_ for that site to load all content. [Learn how](https://support.mozilla.org//kb/enhanced-tracking-protection-firefox-desktop#w_what-to-do-if-a-site-seems-broken)

The link doesn't make anything clearer - it says
> This will turn off Enhanced Tracking Protection for this site

So IDK the exact answer, it will be covered in the user.js in time and is listed in my ToDos in #1051

One way around this (if ETP exceptions disable dFPI) would be to use Multi-Account Containers and assign those few sites into their own containers

---

> Currently in ETP section, I have selected custom mode

Custom mode was touched on in #1306 - AF is not going to maintain and support stuff about custom mode

I do not fucking care how it works and what prefs you can change to alter custom, or change strict.  Since I am the only person doing all of this (aside from E providing diffs), and have been for the last year and a half (or longer), I refuse to deal with any of it. STRICT mode is going to be it. STRICT is literally named the hardest setting. Considering we were FPI for 4 years, I don't think anyone should give a shit about relaxing down to custom

---

> I used it most on a streaming site which allows to view 3 videos, after which it asked for login

Just use Forget About This Site: it sanitizes it and your count will resume at 0.
- hamburger > history > right click history item > forget about this site
- customize toolbar, drag `Forget` button to toolbar

**Comment by githubuniqu** [comment]
Thanks for clarifying, cheerio.

**Comment by Thorin-Oakenpants** [comment]
> Just use Forget About This Site

or use one off Private Windows. When all Private Windows are closed, everything for PB is cleared from memory

**Comment by githubuniqu** [comment]
Yeah Private Windows is always an option, though I reserve it for one-off. Certainly it has its appeal to take a look again.

What's wrong with Temporary Containers anyway?
Obviously asking to use in a relaxed profile and not as ultra privacy add-on to reduce FPing.

**Comment by Thorin-Oakenpants** [comment]
> What's wrong with Temporary Containers anyway?
> Obviously asking to use in a relaxed profile and not as ultra privacy add-on to reduce FPing.

FPing is a stateless tracker, TC has nothing to do with this. TC, TCP (dFPI), FPI, network partitioning, containers are all about isolating state tracking

**Comment by githubuniqu** [comment]
Yeah my bad. TC, dFPI, FPI are different than FPing. Its just that I mix these words, adblocking also. Well atleast its better to be corrected by an expert.

TC doesn't work with dFPI, I should've read full details on extension page. Bummer. But here's a little suggestion - please separate TC from cookie extensions and highlight TC doesn't work with dFPI yet, but it does with FPI like before. That way it would be easier to add overrides and adding extensions if one goes on FPI route than dFPI.

**Comment by Thorin-Oakenpants** [comment]
correct - the wiki says

> * Temporary Containers, Cookie extensions
>   - Redundant with ... snip
>   - ❗️Sanitizing in-session ... snip
>   - ❗️Cookie extensions lack [APIs](https://bugzilla.mozilla.org/1669716) to work with Total Cookie Protection which [will be the default](https://bugzilla.mozilla.org/1731713)

moving forward, **_I am not going to support FPI questions_** - it is no longer maintained. Mozilla's state partitioning and FPI are two different code paths, and upstream is not going to bother with both
- for example: without intervention, websockets would never have been added to FPI
   - [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1713748#c7) is syrqb getting in on the act _**right after I alerted him**_
   - not saying it wouldn't have eventually been added to Tor Browser's patches and/or maybe eventually upstreamed
   - this is but one example: where moz devs are not bothering with FPI when making improvements or adding new states

/*** [SECTION 6000]: DON'T TOUCH ***/
https://github.com/arkenfox/user.js/blob/2787da7f90b31b19d3549b61a77210b79bd1166b/user.js#L1103-L1106

FPI is pretty robust, but it does not cover service workers, which we now enable. That then means it becomes a recipe involved multiple prefs and yet more maintenance/support - such as dealing with OA syntax in FPI

**Comment by Thorin-Oakenpants** [comment]
anyway ... TC is still redundant with FPI

**Comment by githubuniqu** [comment]
Okay so now TC is out of the way. There are two other add-ons which needs clarification - Privacy Redirect. Now its a good add-on, actually I use it in my user.js profile, but then one question remains - is it making me more unique as general idea about FPing is morr add-ons you add, more unique you become.

Second is uMatrix. Whatever other pros and cons of uMatrix are, one major advantage over uBO is youtube, soundcloud or other third party embeds have links which you can click and they open in their respective sites. It reduces multiple clicks and more often than not, I don't have to allow scripts at all(all scripts denied, css and images all allow). No rules, no noop allow deny, just click it unlike uBO.
Hope you don't mind answering them.

**Comment by crssi** [comment]
> TC doesn't work with dFPI, I should've read full details on extension page.

I don't see it that way. Where did you find that out?

**Comment by githubuniqu** [comment]
Well here's another way to settle this - does TC work with dFPI?

**Comment by crssi** [comment]
> I should've read full details on extension page

^^ I am interested in this. Where on the extension page, what full details? Do you have a direct URL to that?



> does TC work with dFPI?

I don't see why wouldn't. When a new tab/containers opens it has a clean namespace, but TC does not prevent connections that are not user initiated to be opened in any direction, where on the contrary dFPI do (AFAICT).

Actually, what do you exactly mean with "work with dFPI"? That the TC does not work anymore as extension, that does not meet your requirements/goal?

**Comment by githubuniqu** [comment]
This link https://bugzilla.mozilla.org/1669716 states FPI and dFPI are mutually exclusive. And that add-ons which mainly use FPI structure as base will not work with dFPI. Now I'm not an expert, not a chance, but reading this I think TC should not work with dFPI.

Even if TC has been updated to support dFPI, it was last updated on Feb 8 on add-on store, and so atleast that version doesn't support dFPI.

I mainly used TC to create new session on DRM sites, never for logins or to have multiple logins at the same time. Plus most of the time I clear all data on close, so yeah losing TC will be a bummer but no deal breaker for me.

**Comment by crssi** [comment]
> I think TC should not work with dFPI

I don't see a reason why not.

> Even if TC has been updated to support dFPI, it was last updated on Feb 8 on add-on store

I don't see a reason that TC should have any special adaptation for dFPI, I think it should work out-of-the-box on as it is now.
Also when the extension was updated long time ago, that doesn't mean its crap... it might also mean that it was done so good that there is nothing to correct, at least not at this moment.

**Comment by githubuniqu** [comment]
First we're all sporty here right, just having a normal chat.

Look I used TC myself for a long time along with ClearURLs, uMatrix. But things change. Yes TC was updated on Feb 8. That doesn't mean it has regressed in the mean time. See I'm using uMatrix - how often has that been updated in last two years.

dFPI and FPI are mutually exclusive. TC works on FPI principle and so naturally it won't work as well with dFPI. Couple that with the fact it hasn't been updated which most likely tells although it will continue to work well with FPI, not with dFPI though as that would mean a change in source code which hasn't happened yet.

**Comment by Thorin-Oakenpants** [comment]
TC uses a different API for sanitizing

> * Temporary Containers, Cookie extensions 
>    - _**Cookie extensions**_ lack APIs to work with Total Cookie Protection which will be the default

The bugzilla linked is about the extension's "cookie" API or whatever you want to call it
> At the API level, I am considering to introduce a new method to allow extensions to get the expected cookie jar (e.g. `firstPartyDomain` and/or the extension API representation for `partitionKey`) for a given `tabId` / `frameId`. I am considering this, because it is not really obvious which keys an extension should choose when they read or write cookies for a specific document.

None of this changes the fact that they are both redundant
- .TC doesn't need to isolate anything
-  Both (TC and cookie extensions) are not sufficient to create new IDs and is a false sense of privacy. Bad OpSec

**Comment by Thorin-Oakenpants** [comment]
> dFPI and FPI are mutually exclusive

only in how the browser decides how to partition. this has nothing to with extensions. The problem with extensions is that each method needs to added to the cookies extensions API. Pretty sure FPI was lacking initially. Currently dFPI is lacking

**Comment by crssi** [comment]
> First we're all sporty here right, just having a normal chat.

But of course 😄 

Whats in my mind is that it depends what are the reasons to use TC.
In my work I need to be logged on to same web site as a different user (admin, test user, me as myself, etc...) at the same time and I think here the TC will still do the trick opening several different containers to the same destination.

**Comment by githubuniqu** [comment]
Well actually my usage is more than streaming videos which is why in my work/normal/justmakeiteffingwork profile I will continue to use it. I don't see use case for it on user.js profile though as every time I clear all data on close,and PB is more than enough - funny enough I only realised that tomorrow - not the case in normal profile which if I check still has history of months old.

**Comment by githubuniqu** [comment]
Sometimes its better to change a thing or two.
So I switched again to uBO but in medium mode. Problem with Hard mode is unlike uMatrix which allows to only allow specific items like image, uBO noops whole domain/subdomain and so everything is allowed. So then comes the question - is allowing scripts good in hard mode or allowing 3p images, css in medium mode. I'm using medium mode for now.
But I have also disabled JS in settings plus 1p script, inline script, 3p script and 3p frames are globally blocked. This makes for similar setup I had in uMatrix, which is all scripts are blocked and images, css are allowed. I also added two filter rules - $3p,frame,redirect=click2load.html
$1p,frame,redirect=click2load.html

Its weird that everybody recommends to setup modes yet nobody talks about iframes.
These filters solves the YouTube issue and every other embeds as well. I like uBO implementation as even though domain is nooped, frames will still be click-to-load. Exceptions can still be made.
Plus uBO now allows inline scripts regardless of rules and so if I allow one domain, another domain will get nooped as well or in uMatrix language - XHR. Not a deal breaker as it allows for few clicks but interesting nonetheless.

Second I enabled/imported shortener list mentioned in wiki but it is weird. It breaks twitter.com/explore page(disable uBO is no-go, effects of having a single add-on for multiple tasks rather than specialized one for different) and so specific section mainly sports doesn't work, IOW no effect on changing sections. Plus it does nothing for Google search. Yeah Google is bad but sometimes you have to use it. So if I click on a website through Google search, in history Google search results will be showen instead of destination page URL. Plus I read something on reddit -
https://libredd.it/r/uBlockOrigin/comments/pg8dze/are_there_any_filter_lists_that_can_completely/hbach0p/
https://libredd.it/r/uBlockOrigin/comments/rttrbp/no_longer_any_need_for_the_clearurl_extension/

After reading it, I disabled shortener list(mainly because of Twitter) and installed ClearURL after months. Thankfully it has sorted some issues which included amp url when clicking through Twitter links.

TC is gone for now coz unless FPI pref is changed it will not work as dFPI will be the boss.

Privacy Redirect is still the go-to-champ.
