### ISSUE TITLE
ridiculous connections to amazonaws server

### ISSUE THREAD

**Issue by mortezadadgar** [arkenfox/user.js#1316]
Hey,
I have disable firefox sync and google safe browsing but still I'm getting connections to ec2-54-184-42-133.us-west-2.compute.amazonaws.com on firefox startup according to netstat
does anybody know why I'm getting these connections

**Comment by mortezadadgar** [comment]
@Thorin-Oakenpants Dude have i missed anything?

**Comment by Thorin-Oakenpants** [comment]
> Dude have i missed anything

sorry was typing answer as you posted. teh thing is I am sick of this same question. Not all connections are privacy issues, and most are for security reasons

---

could be anything that is not privacy related, such as crlite updates, sb updates (turning of SB doesn't turn off SB updates), extension blocklists, system addon updates, app update checks, extension update checks, etc etc etc

it's a browser, it connects to the internet, get over it

**Comment by mortezadadgar** [comment]
Thanks I thought you unmercifully closed the issue, it doesn't seem to be easy to track for what firefox making the connections
