### ISSUE TITLE
How to deal with cookies efficiently with TCP?

### ISSUE THREAD

**Issue by Dupond** [arkenfox/user.js#1322]
Hello,

In [this post](https://github.com/Thorin-Oakenpants) from a few months ago, @Thorin-Oakenpants explained that, in his daily use of Firefox, he doesn't allow anything to be written on disk:

> auto blocking any web storage just makes everything so much cleaner and less busy having to deal with cleaning up afterwards

Now that [user.js uses Total Cookie Protection](https://github.com/arkenfox/user.js/issues/1281), I wonder if something similar is still feasible... or even if it's just a good idea.

Furthermore, in the [wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#small_orange_diamond-dont-bother) "Cookie extensions" appear in the "Don't bother" section.

So I would have two questions:

1. with the last version of the `user.js` (keeping Total Cookie Protection), is it still possible to block all cookies by default and only allow a few exceptions for the session?
2. if it's indeed possible, would it be a good idea?

I'm a bit afraid that, after an hour or two browsing the internet, many cookies will have been added to my hard drive and will need to be cleaned up... Or maybe there's a way to specify to store the cookies in ram instead of on the hard drive?

Thanx in advance for any explanation/advice!

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/1051#issuecomment-1004491994

**Comment by Thorin-Oakenpants** [comment]
AF uses dFPI which is part of ETP Strict which sets cookies as 5. AF only supports dFPI. Live with it.

Why are you "cleaning cookies"? Sanitizing within a session is a false sense of privacy. They are isolated/partitioned FFS. Just sanitize on close. They are not doing any harm. If you think it stops your visits being linked, did you change your IP? If you want a new identity then do it properly

If you need to bypass a paywall, then just clear that sites "cookies" - either "forget about this site", or via manage cookies and site data. Or just use a one off PB window

**Comment by Dupond** [comment]
Not sure why you ask "why are you clearing cookies"; if it's because of the quote, then it's what _you_ said 6 months ago ;)

> If you think it stops your visits being linked

I'm not worried about that; I was just curious about how you've had to change your habits with the new settings, since you said that you were used to "blocking any web storage"...

Thanx for the answer anyway, and have a nice day!

**Comment by Thorin-Oakenpants** [comment]
> I was just curious about how you've had to change your habits with the new settings

Well, you did ask "I wonder if something similar is still feasible... or even if it's just a good idea"
- no it's not feasible with dFPI (because the cookie pref must be 5)
- no it's not a good idea (because otherwise you would need to use FPI which is no longer maintained) + breakage is higher

I'm using dFPI (so cookies+site-data are not blocked) and sanitizing on close, because that's all we support. It actually creates less breakage and my cookie + site data exceptions are down to only four items as "Allow" (to auto-login). Previously I had another dozen sites with `Allow for session`.

The only drawback is I now get cookie prompts on a few sites per session, which is slightly annoying - e.g. stackoverflow. But when they deprecate the lifetime cookie pref (without affecting sanitizing), then uBO's `cookie-remover.js` will work

**Comment by Dupond** [comment]
Thanx for the more detailed answer!

> you did ask "I wonder if something similar is still feasible"

True ;) But I didn't mean "sanitizing within a session", just "blocking any web storage" like you did before.

> site data exceptions are down to only four items as "Allow" (to auto-login)

I've never done that previously, but with dFPI it definitely seems like a good idea, without any privacy risk, right? What would be the easiest way to create those exceptions, for someone not really good at computers? (typically: my wife ;)) Is it using Ctrl+i? A click on the shield icon in the url bar, then click on "Protection settings", scroll down, click on "Manage Exceptions" and manually enter the domain name won't be an option for her... or maybe there's an easier way?

> But when they deprecate the lifetime cookie pref (without affecting sanitizing)

Thanx for explaining me all this. Would you have any information source where I could learn more about this?

**Comment by Thorin-Oakenpants** [comment]
> But I didn't mean "sanitizing within a session", just "blocking any web storage" like you did before.

The answer, **_for the third time_** is no - there is no way to do it on a global scale with prefs, therefore you sanitize

> where I could learn more about this

https://bugzilla.mozilla.org/show_bug.cgi?id=1681493
