### ISSUE TITLE
Question about LocalCDN and Decentraleyes with current FF privacy settings.(and also NeatURLs and ClearURLS)

### ISSUE THREAD

**Issue by ginick** [arkenfox/user.js#1323]
Hello (i'm not using FRP)
i just read in Privacyguides(which apparently you helped write):
"These extensions aren’t required with Total Cookie Protection (TCP), which is enabled if you’ve set Enhanced Tracking Protection (ETP) to Strict."
with the user.js file, mine is set to custom with all its custom settings.
i was wondering if the statement above still applies to me, and i can remove Decentraleyes?

also a question about NeatURLs and ClearURLS;
i am not using these add-ons because i thought that the Ublock filter "Adguard url tracking protction" took care of that,but apparently it's taken care with Ublock origin new removeparam feature.
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam

i don't really know how to incorporate it, or mainly what Value or filter to assign.
is the default shown there is what i should use:*$removeparam=utm_source or *$removeparam=/^utm_/  ?

**Comment by Thorin-Oakenpants** [comment]
> with the user.js file, mine is set to custom with all its custom settings

❗ read the user.js
⭐ AF is not supporting anything outside ETP Strict: DON'T BOTHER
https://github.com/arkenfox/user.js/blob/7016c2050d20d53242c30eaf0b3beca947e172f6/user.js#L1207-L1215

⭐ AF is not supporting FPI anymore: DON'T TOUCH
- it's no longer maintained and it would required a bunch of prefs and a recipe. Not interested
https://github.com/arkenfox/user.js/blob/7016c2050d20d53242c30eaf0b3beca947e172f6/user.js#L1101-L1104

Anyway, for the next part on LocalCDN .. **_if you're not using dFPI then you should be using FPI_ at a bare minimum**

❗ read the wiki
> * LocalCDN, Decentraleyes
>   - Third parties are already isolated if you use [Total Cookie Protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) (dFPI) or FPI

repeat ... Third parties are already isolated if you use _**(dFPI) or FPI**_

❗ read the F wiki
> * ..., Decentraleyes
>   - ... the [resources](https://git.synz.io/Synzvato/decentraleyes/-/tree/master/resources) for Decentraleyes are hugely out of date and would not likely be used anyway

repeat ... the resources ... are _**hugely out of date and would not likely be used**_ anyway

It is pointless serving local versions, and in fact has security issues, and can be fingeprinted - e.g. serving you an older library and testing for a change, not to mention an extension is injecting shit into your DOM. And it has no privacy benefits. And any claim of perf gains also doesn't hold up. CDNs are already fast as F and I doubt you would even notice

What is the point of requesting a tiny list of files from those few CDNs when 1) your IP is exposed and if it isn't then why bother and 2) you're not blocking all the other 99.9999999% of third party content required for web sites to work

----

clearURLs

❗ read the F wiki FFS
> * Neat URL, ClearURLs
>   - Redundant with uBlock Origin's [`removeparam`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam) and added lists. Any potential extra coverage provided by additional extensions is going to be minimal

repeat ... **_Any potential extra coverage ... is going to be minimal_**

read: https://old.reddit.com/r/uBlockOrigin/comments/rttrbp/no_longer_any_need_for_the_clearurl_extension/hqxddko/
- thanks @gwarser 

clearURLs has feature creep. You don't need any of it except the param tracking part
- ETAGs is covered by .. network partitioning or FPI (the former is enabled by default when not using FPI)
- history API isn't a thing: as in it is already scoped and limited to eTLD+1 per window
   - there are some edge case potential XSS issues: but it'l; never happen to you
- the rest is already covered

About the only thing is that it can do a few more things regards params like `/ref` - but once again, **_any potential extra coverage ... is going to be minimal**_

**Comment by Thorin-Oakenpants** [comment]
Maybe I should just delete the wiki if people won't read it

**Comment by ginick** [comment]
i've read the wiki the first time i put to use the user.js file, but i don't know it by heart.

regarding the first part ; what i meant is that AF user.js sets "enhanced tracking protection" to:
custom
cookies:all third party..
tracking content:in all windows
and the rest of the boxes in the list are checked.
so i was wondering if this was equal to "strict" and that i was fine removing Decentraleyes.

and regarding the ``removparam``;i was asking on how to implement it in Ublock origin;meaning what value should i assign to it.

**Comment by Thorin-Oakenpants** [comment]
> what i meant is that AF user.js sets "enhanced tracking protection" to: custom

it does no such thing, never had

If you meant _YOU_ set that, then the answer is not supported by AF

> and regarding the `removparam`; i was asking on how to implement it in Ublock origi

just add the filters in the wiki under uBO - one is pre-supplied, the other is a custom one

If you meant you are crafting your own - read the uBO wiki or ask at uBO reddit
