### ISSUE TITLE
Cookie Auto Delete

### ISSUE THREAD

**Issue by Loki-L1130** [arkenfox/user.js#1324]
In the Wiki under Extensions,

~~~
Temporary Containers, Cookie extensions

-     Redundant with Total Cookie Protection (dFPI) or FPI
- ❗️Sanitizing in-session is a false sense of privacy. They do nothing for IP tracking. Even Tor Browser does not sanitize in-session e.g. when you request a new circuit. A new ID requires both full sanitizing and a new IP. The same applies to Firefox
- ❗️Cookie extensions lack APIs to work with Total Cookie Protection which will be the default

~~~
Does this also include Cookie-auto Delete Extensions, I am asking this as I want to configure CAD to delete cookies that I no longer use and just want to preserve Login Cookies ?

**Comment by crssi** [comment]
See the last line in the quote in your post. 😉 
That is `Cookie extensions lack APIs to work with Total Cookie Protection which will be the default`

Cheers

**Comment by Thorin-Oakenpants** [comment]
is CAD a "cookie extensions" ... it's called .. wait for it "COOKIE" auto delete
