### ISSUE TITLE
Beta Firefox builds not recommended?

### ISSUE THREAD

**Issue by TommieWong** [arkenfox/user.js#1328]
Since Arkenfox releases seem to follow Firefox public releases, does this mean that it is discouraged to use beta builds?

_Originally posted by @TommieWong in https://github.com/arkenfox/user.js/issues/1186#issuecomment-1011374617_

**Comment by Thorin-Oakenpants** [comment]
use some common sense

most prefs don't change between releases

if anything in the user.js were to become deprecated in the next two releases (beta/dev or nightly), then it makes no difference in that those prefs will do nothing

You will only be missing any possible prefs we haven't added or changed, but 99% of them are stable
- one example would be an upcoming change where `browser.link.open_newwindow.restriction` will be deprecated and replaced. So until we add the replacement prefs and values, then you wouldn't get quite the same result

No-one here is going to keep up-to-date with nightly to track all the changes
