### ISSUE TITLE
user.js broke Vimium extension a bit

### ISSUE THREAD

**Issue by p0pcat** [arkenfox/user.js#1331]
- browser version
  96.0.1
  - Steps to Reproduce
Install Vimium-FF and add default user.js into the profile
  - actual result
  When moving with j, k, l, h, u, d... there is no smooth movement animation 
  - expected result
  Smooth movement animation
  - anything else you deem worth mentioning
  I'm sure that its due to some user.js settings. Also I'm new to FireFox so I didn't even try debugging it, sry.

**Comment by rusty-snake** [comment]
https://github.com/philc/vimium/issues/3759
