### ISSUE TITLE
> I understand you will not bother

### ISSUE THREAD

**Issue by gitthehubs** [arkenfox/user.js#1335]
> I understand you will not bother

No you don't understand because just asked me

I am not interested
I cannot be expected to know everything
I cannot be expected to have the time to investigate everything

Since it's practically just me (and E providing diffs), then I get to decide what the fuck I do. I will only support ETP Strict

_Originally posted by @Thorin-Oakenpants in https://github.com/arkenfox/user.js/issues/1051#issuecomment-1016372505_

I didn't ask you anything, I only explained why I am using another setting and how I am trying to figure it out!

**Comment by rusty-snake** [comment]
> which links to https://searchfox.org/mozilla-central/rev/6db0a6a56653355fcbb25c4fa79c6e7ffc6f88e9/browser/app/profile/firefox.js#1573
> Obviously some old code.. no idea where to find something newer, so I have to figure out wat stp,lvl2,rp,ocsp means and how to set them manually. :)

https://searchfox.org/mozilla-central/rev/d4b9c457db637fde655592d9e2048939b7ab2854/browser/app/profile/firefox.js#1776-1816

> I prefer not to use the strict setting because of the 'Tracking content' option, I prefer to use and trust my own ad-blocker.

You can use both ;)

> And besides that, 'Tracking content' breaks things that are supposed to be fixed again with SmartBlock, which even insert new privacy friendly scripts. I have my doubts about this solution

Guess what uB does

https://github.com/gorhill/uBlock/tree/master/src/web_accessible_resources

**Comment by gitthehubs** [comment]
@rusty-snake 
Thanks for this link!! : https://searchfox.org/mozilla-central/rev/d4b9c457db637fde655592d9e2048939b7ab2854/browser/app/profile/firefox.js#1776-1816 

And I didn't knew uBO was replacing scripts, never seen anything in the logger(not that I use it much).

And the only way I could respond to thorin was this way as he limited the comments in the original issue. He left me no other choice, his response was somewhat rude in my opinion(not that I care and I was not surprised, it happened before).

**Comment by Thorin-Oakenpants** [comment]
> I didn't ask you anything

you @ name dropped me, quoted me and then wrote swathes of information and links ... if that's not ASKING me something then I F don't know what is - at the very least it's adding noise and requiring me to read your comment

Feel free to ask on reddit or elsewhere

**Comment by Thorin-Oakenpants** [comment]
I am rude because people are not taking hints - such as READ THE WIKI
