### ISSUE TITLE
Clarification about prefscleaner

### ISSUE THREAD

**Issue by TommieWong** [arkenfox/user.js#1338]
Hi all,
After having read the wiki section about the prefscleaner, I am left with a few questions. 

My situation: created a brand new FF profile, dropped the most recent user.js, added overrides in a dedicated overrides js file, and then made a couple of changes straight from the preferences panel in FF (changed my default search engine, added a proxy, minor things like that).

- In my understanding, when a new user.js is made available, I should update my own version (preferably using the updater script) and _then_ the prefscleaner should be used (after the update). Is this right?
- In my case, since the profile was new and the user.js used was the most recent, there is so far no need to use the prefscleaner, and I should wait until the next version of the user.js. Correct?
- Using the prefs cleaner will delete the changes I made directly in the FF preferences panel, is that right? And so, in order to keep those changes, I should actually include them (with the proper syntax) in my overrides js file. Is that right?

Thanks in advance!

Tom

**Comment by Thorin-Oakenpants** [comment]
prefsCleaner resets all the prefs in user.js (active and inactive)
on FF start user.js only applies active prefs, one's not commented out
if you change something in Firefox (UI or about:config) that relates to a pref in the user.js then it will get reset either by prefsCleaner (always) or on a restart (if it is active)
