### ISSUE TITLE
96 nits & question

### ISSUE THREAD

**Issue by practik** [arkenfox/user.js#1342]
Nice update! It's so much lighter and airier in here now with 2300 and 4000 cleared out of the way. I made the switch to dFPI a couple of weeks ago (so far so good), but it's nice to have the official version of the JS.

Two minor goofs I noticed:
line 3: year should be 2022
line 1092: pref # should be 6007

Also, just curious: Why did you bring back `browser.eme.ui.enabled`?

**Comment by fxbrit** [comment]
> Also, just curious: Why did you bring back browser.eme.ui.enabled?

https://github.com/arkenfox/user.js/commit/87bd8683fa384c0e9932230c8957ac0717a0b430

thanks for reporting the nits, I made a PR. good eyes uh.

**Comment by Thorin-Oakenpants** [comment]
> Why did you bring back `browser.eme.ui.enabled`?

https://github.com/arkenfox/user.js/blob/10044fcaf77bfe19f2b90c606232f0a9e83401c9/user.js#L635
