### ISSUE TITLE
Using firefox account feature alongisde user.js

### ISSUE THREAD

**Issue by RelicCornhusk** [arkenfox/user.js#1347]
I've tried troubleshooting this on my own but could not find which tweak on user.js prevents me from logging in to my Firefox Account. I keep receiving the message:
```
Cookies and local storage are required

Please enable cookies and local storage in your browser to access Firefox Accounts. 
Doing so will enable functionality such as remembering you between sessions. 
```
I've opened firefox on safe mode (no extensions) and the issue persists. 
Additional info: Pocket works fine for me, I've tried allowing all cookies, I don't use FPI, and storage is allowed. not sure what is preventing Firefox Accounts from working.

**Comment by Thorin-Oakenpants** [comment]
I cannot mind read
- what version of arkenfox are you using?
- did it just start happening e.g. when you changed to the new version, or are you a new user of arkenfox?
- where is this happening (I do not use FF accounts) - is it from the hamburger menu? or about:accounts?
- can you login on https://accounts.firefox.com/ ?
- while on https://accounts.firefox.com/ go Ctrl-I > permissions tab > an change cookies from default to `Allow`
- did you ever run prefsCleaner?

**Comment by Thorin-Oakenpants** [comment]
also: visit https://firefox-storage-test.glitch.me/ and make sure your databases are not corrupted

**Comment by Thorin-Oakenpants** [comment]
also, what is your cookie setting? `network.cookie.cookieBehavior`

**Comment by Thorin-Oakenpants** [comment]
also, did you ensure no extensions are the cause
