### ISSUE TITLE
draft template for troubleshooting issues

### ISSUE THREAD

**Issue by fxbrit** [arkenfox/user.js#1350]
after [this comment from pants](https://github.com/arkenfox/user.js/issues/1330#issuecomment-1014460880) I figured it might be useful if the repository had a step by step template for troubleshooting issues, so I wrote down a draft.
it's worth noting that the template doesn't really take care of the fact that the uBO + Arkenfox combination is strongly suggested.

***

_\_

Please perform the following tasks and mark them as completed once you have:
- [x] I have read the wiki
- [x] I checked existing [answers](https://github.com/arkenfox/user.js/issues?q=is%3Aissue+label%3Aanswered)
- [x] I searched and tested the `[Setup` tags in the `user.js`.
- [x] I have verified that the problem does not exist in a new and **stock profile**, with **no extensions** installed.
- [x] I have verified that the problem exists in a new profile with [**latest user.js**](https://github.com/arkenfox/user.js/releases/latest) applied and **no overrides**, with **no extensions** installed.

If you still need help, fill the following fields and help us help you, by providing relevant information:
  - _Browser version & OS:_
  - _Steps to Reproduce (STR):_
  - _Expected result:_
  - _Actual result:_
  - _Anything else you deem worth mentioning:_

***

the first part between the `<!--` `-->`  is a comment that would not show when the issue is submitted.

**Comment by Nallua** [comment]
Maybe also have the verification process include an additional step of changing ETP from Normal to Strict on the new stock profile with no extensions? That way, if it worked on Normal but then doesn't after switching to Strict, they can just be directed to set a per-site exception. And if works with a stock profile on Normal and on Strict, they've ruled out for sure that ETP Strict isn't the issue. In both cases, no-one would ever have to suggest an unsupported (and heavily discouraged) override.

**Comment by fxbrit** [comment]
I've never seen any kind of breakage related to strict mode, I don't think it's worth having an extra step for that. also strict is a change made by the user.js, so if it causes breakage it's worth opening an issue so that it can be investigated, at least imo.

**Comment by GlassGruber** [comment]
In the template I would suggest also to point the OS used.
