### ISSUE TITLE
Make YT video guide on how to install and use arkenfox/user.js for lay people? 

### ISSUE THREAD

**Issue by Yolakalemowa** [arkenfox/user.js#1356]
Hi, 

I doubt this is the right place to ask for this suggestion, but it seemed the best out of the others. (plz let me know if there's another better platform to ask this)

I tried looking for guides on how to use and _maintain_ the Arkenfox user.js for a noob like me but couldn't find any. Couple of videos on YT only show how to implement it but not how to manage it further: add one's own exceptions, keep it updated with every new release, etc..?

That would really be useful for lay people like us to share around and make this process available for a much wider audience I think. (assuming that's of interest to the team of course: to have more people use it)

Thanks btw, highly appreciate your work!

**Comment by g-2-s** [comment]
https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain
Looks plenty easy to me.

**Comment by Yolakalemowa** [comment]
> https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain Looks plenty easy to me.

I saw that but having trouble with how to implement my own "overrides" and update. It says create your own overrides file, but so is that a blank document where I copy/paste whichever lines I want to override from the user.js and put it in the overrides file? 

and then to update whenever a new release is available I just click the updater? and it knows to keep the overrides? 

btw: what if an update includes smthn in the overrides settings that need to be adjusted?

This is of course much to ask, but would be so helpful to explain what all those configs are and what they do in the front-end. For example the added/removing the borders, took me a long time to figure them out.

**Comment by remyabel2** [comment]
Well a youtube video is a big time commitment having to write the script, edit the video, upload the video, then deal with all of the comments. The guy is doing all this work for free and just released a new wiki. Unfortunately arkenfox will always be for technical users, if you have trouble with the initial steps, you will have trouble maintaining it in the long run.

**Comment by Yolakalemowa** [comment]
@remyabel2 wait... why all that haha... just start screen recording and voice over the steps. 2-4 minutes long.

And I wasn't actually thinking of the devs necessarily but suggesting it to the community here at large maybe someone's interested. No need to reply to comments even. 

Anyway... thought there's no harm in asking ¯\_(ツ)_/¯

thx

**Comment by g-2-s** [comment]
> is that a blank document where I copy/paste whichever lines I want to override from the user.js and put it in the overrides file?
> and then to update whenever a new release is available I just click the updater? and it knows to keep the overrides?

Yep that's basically what an user-overrides.js is: https://github.com/arkenfox/user.js/wiki/3.1-Overrides
The wiki explains it well in my opinion. For the actual creation of such file if you're on Windows download and install a text editor like Notepad++, new file, under Language choose JavaScript, enter your overrides following the syntax, should be something like (this is just my poor attempt at an example lmao):

```
/*** My example overrides ***/

/* EXAMPLE: disable RFP letterboxing ***/
user_pref("privacy.resistFingerprinting.letterboxing", false); // 4504 (true in AF user.js)

/* EXAMPLE: disable WebRTC ***/
user_pref("media.peerconnection.enabled", false); // 2001 (inactive in AF user.js)

/*** parrot for overrides success achievement ***/
user_pref("_user.js.parrot", "success");
```

Save file as user-overrides.js and you're set.

> btw: what if an update includes smthn in the overrides settings that need to be adjusted?

> This is of course much to ask, but would be so helpful to explain what all those configs are and what they do in the front-end. 

You have to read, I was lost at the beginning too but then I decided to read the user.js (https://github.com/arkenfox/user.js/blob/master/user.js) from top to bottom, read the Issues section especially the Changelog threads and make some research myself and it all started to become clear.

Someone more expert will surely correct me but this is somewhat of a start if you're desperate.

**Comment by remyabel2** [comment]
Yep it's already answered in the wiki, so I'm not sure how a video would provide any clairty. I think you underestimate the time it takes to create a youtube video especially for a technical tutorial. Even if you are a lay person it's still expected to do some reading/research, having someone else do the work for you is considered bad etiquette.

**Comment by Yolakalemowa** [comment]
@g-2-s 

thanks so much. I’ll try to do my own document. 

The problem Is I did try to read it all but seemed to always have many questions about things and terms I didn’t understand. I should try again and Google all the new terms. 

Heck maybe I’ll create my own YT guide eventually. Who better to write for noobs than a noob who struggled to figure it out 😂

**Comment by g-2-s** [comment]
I have no idea why do you want a video of all things but okay. You can read this guide too https://12bytes.org/articles/tech/firefox/the-firefox-privacy-guide-for-dummies/ but it uses its own user-overrides.js and you might want to start from scratch since that's a good practice for learning in my opinion.

**Comment by Yolakalemowa** [comment]
@g-2-s

just to clarify I wanted the vid only for implementation and overrides example and update. 

Not an explanation of all the configurations of course. 

Thanks for the source will definitely check it.

**Comment by Yolakalemowa** [comment]
> Yep it's already answered in the wiki, so I'm not sure how a video would provide any clairty. I think you underestimate the time it takes to create a youtube video especially for a technical tutorial. Even if you are a lay person it's still expected to do some reading/research, having someone else do the work for you is considered bad etiquette.

Of course I agree with that. I tried reading everything and I’m obviously a noob who still faced difficulty understanding. I’m new to all this and tryin to learn.

heck I only recently learned how to navigate GitHub -.- 


Anyway, thanks.

**Comment by atomGit** [comment]
> Unfortunately arkenfox will always be for technical users

and therein lies the problem (i'm totally not singling out arkenfox); the tech is often beyond the capability of those that might benefit the most from it

some advocated for an add-on to help, but that's a WHOLE other project that pants wants nothing to do with (i don't blame him)

contrary to some other thoughts here, i think a very generic video could be helpful for the attention compromised crowd, but then i wonder if they'd be diligent enough to keep the js updated, much less customize it

i'm not against making a video (it's something i'll consider doing), but i think the more effective route, at least with regard to updates, is to have an add-on, not like that which was proposed before (a GUI front-end to the js basically), but one that only checks for and optionally downloads updates (installing apparently can't be done with the WebExt API)

i'd like to hear thoughts on that since an add-on as simple as that may not be beyond my capability, though there's others here that are far more qualified

**Comment by Yolakalemowa** [comment]
@atomGit thank you atom. 

I'm disappointed to see that this issue was closed that fast. At least keep it open for others who might share this sentiment and volunteer to make a simple vid or smthn like yourself.

And regarding @remyabel2's comment that this will always be for technical users. It's worth mentioning that the way I came to find this thing is through privacyguides.org. And if I'm not mistaken their mission (following on privacyguides.io) was precisely to make privacy as accessible as possible to noob grandma end users like us...

¯\_(ツ)_/¯

**Comment by remyabel2** [comment]
Is the passive aggressive shrug emote really necessary?

privacyguides is a third party that has no association with arkenfox. They provide recommendations and advice. The projects they link to have no obligation to do *anything*, it's a service they provide for free. You're basically asking people to do work *for* you. If you want to learn, that's great. But we all have to do work for ourselves, especially when it comes to research. Asking people to make a video for you and then going "lol it doesn't take that much work" is kind of silly, no offense.

**Comment by Yolakalemowa** [comment]
@remyabel2 

Sorry if I offended you... I wasn't really blaming you or Arkenfox. I'm obviously very thankful for this script and I know it's not the same as PG. The shrug was at the state of affairs that such an awesome tweak is a bit too advanced for lay people. It's not a situation that I like. 

And I'm not forcing you or anyone here to do work for me. I'm making a suggestion from a noob directed really at one of those people who share my and PG's belief that privacy should be brought as much as possible to the masses. 

You're probably not one of those people :)  let's not make a big deal out of it.

**Comment by remyabel2** [comment]
> You're probably not one of those people :) let's not make a big deal out of it.

There really is no need to make assumptions about what type of person I am. In fact, you can go to my website and see that one of my hobbies IS writing documentation for lay people.

There's a difference between going "can you do X" "no that's too much work" "OK thanks" or doing research then asking clarifying questions instead of expecting others to do the brunt of the work for you. That is going to be the case whether you're technical or non-techical. You are correct that this has gone on for too long and I'm dipping from this convo.

**Comment by Yolakalemowa** [comment]
@remyabel2 . 

alright friend. accept my apologies. probably due to stupid miscommunication over text rather than face2face. 

<3 take care. sorry again.
