### ISSUE TITLE
[Wiki / Question] Why recommending both AdGuard URL Tracking Protection and Skip Redirect ?

### ISSUE THREAD

**Issue by xfzv** [arkenfox/user.js#1357]
From [4.1-Extensions - Recommended](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-recommended):

> - uBlock Origin ✔ Privacy | GitHub
Enable AdGuard URL Tracking Protection
[...]
> - Skip Redirect | GitHub

Sorry if that's a stupid question but why recommending both? it looks like to me they're doing the same thing but if the Wiki recommends both of them, there must be some good reasons.

Keep up the good work. :+1:

**Comment by rusty-snake** [comment]
- Enable AdGuard URL Tracking Protection: Strip query parameters like `utm_source`
  example: `https://example.com/cats.html?utm_source=youtube` becomes `https://example.com/cats.html?`
- Skip Redirect: Skip redirection trackers
 example:  `https://example.com/redirect.html?url=https://example.net/` becomes `https://example.net`

**Comment by xfzv** [comment]
> * Enable AdGuard URL Tracking Protection: Strip query parameters like `utm_source`
>       example: `https://example.com/cats.html?utm_source=youtube` becomes `https://example.com/cats.html?`
> 
>     * Skip Redirect: Skip redirection trackers
>       example:  `https://example.com/redirect.php?url=https://example.net/` becomes `https://example.net`

Thank you.
