### ISSUE TITLE
user-override.js not being applied

### ISSUE THREAD

**Issue by rsolvang** [arkenfox/user.js#1359]
Maybe it's just me being dense, but the my user-overrides.js does not have any effect. The user.js prefs are all applied as expected. This is what I have done on my pretty much vanilla Fedora 35 install:

- Install the most recent Firefox v96.0.3  (from the flathub repo) via GNOME Software
- Create a new Firefox profile named "Arkenfox"
- Cloned this repo into the Arkenfox profile folder under `arkenfox/`
- Linked `user.js`, `updater.sh` and `prefsCleaner.sh` from the `arkenfox` folder into the parent (profile) folder (hard links, not soft).
- Created a `user-override.js` with two prefs:

```js filename="user-overrides.js"
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("keyword.enabled", false);
```

I have tried restarting Firefox, the computer etc, still my overrides won't take. My first instinct is to blame Flatpak for doing something unexpected, but I don't really know.

**Comment by rusty-snake** [comment]
> The updater gets the current live arkenfox 1 and appends your overrides, and then it compares that to the current user.js in your profile. If it's different, it replaces it.

Did you run `./updater.sh`?

**Comment by rsolvang** [comment]
Ok, I'm dense, I thought `user-overrides.js` was applied automatically :man_facepalming:. Running `updater.sh` did the trick. And yes, my second override should have been `true`, but when I could not disable the letterboxing I forgot to change it.

Thanks for helping out! I thought I had read the wiki thoroughly, but apparently I had missed the need to apply the `user-overrides.js` manually.

**Comment by Thorin-Oakenpants** [comment]
I added a  🔽 and bolded and capitalized continue. It now reads

#### 🟪 APPLY

If you are not using a new profile, we recommend running our [cleanup script](https://github.com/arkenfox/user.js/blob/master/scratchpad-scripts/arkenfox-cleanup.js), the instructions are in the file.

- 🔹 Put all the relevant files into the root folder of your profile <sup>[1]</sup>
  - `prefsCleaner`
  - `updater`
  - `user.js`
  - `user-overrides.js` (which you created)
- 🔽 **CONTINUE** with the UPDATE part below
