### ISSUE TITLE
partitioning with proxy? [watch 1769277]

### ISSUE THREAD

**Issue by xowu** [arkenfox/user.js#1360]
What does privacy.partition.network_state.connection_with_proxy do when using proxy?
I always use a proxy and it's hard to find what it does.

Thanks.

Thorin says: see [1769277](https://bugzilla.mozilla.org/show_bug.cgi?id=1769277) - Evaluate privacy.partition.network_state.connection_with_proxy and possibly remove

**Comment by rusty-snake** [comment]
> it's hard to find what it does.

https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#11308

> By default, the network state isolation is not active when there is a proxy setting. This pref forces the network isolation even in these scenarios.

**Comment by xowu** [comment]
Thank you.
Then why isn't this a SETUP tag? That seems terrible.

**Comment by Thorin-Oakenpants** [comment]
> Then why isn't this a SETUP tag? That seems terrible.

Because it's not in the user.js for fucks sake. How about more reading before criticizing/suggesting

**Comment by xowu** [comment]
> Because it's not in the user.js for fucks sake. 

I know this, I'm asking why not, really?

**Comment by Thorin-Oakenpants** [comment]
Because I am one person and cannot be expected to know and see absolutely everything, despite pref diffs per release

Feel free to provide links to all the bugzillas and patches, and comments as to why mozilla felt this was a good default at false

**Comment by xowu** [comment]
>Because I am one person
Yes.
@Thorin-Oakenpants no worries, thank you for your work. 

>Feel free to provide links to all the bugzillas and patches, and comments as to why mozilla felt this was a good default at false
lol how

**Comment by xowu** [comment]
Could you make a "how to do the work" guide?

**Comment by gwarser** [comment]
Search -> follow the links -> read -> learn :)

**Comment by Thorin-Oakenpants** [comment]
I'm not going to get to this soon, but my initial understanding is it is related only to those items stated in the bugzilla (albeit this was back in FF79) and there will be a reason (such as stability, or that isolating those two things alt-srv and pool connections via proxy have no benefit)

**Comment by Thorin-Oakenpants** [comment]
[1769277](https://bugzilla.mozilla.org/show_bug.cgi?id=1769277) - Evaluate privacy.partition.network_state.connection_with_proxy and possibly remove

**Comment by Thorin-Oakenpants** [comment]
closing ... my initial thoughts (IANAE) and then the follow up comment from moz devs indicates this is a nothing burger ... feel free to keep tracking if you want to, but I'm over it
