### ISSUE TITLE
Merino → Disable

### ISSUE THREAD

**Issue by timur-davletshin** [arkenfox/user.js#1361]
Disable "browser.urlbar.merino.enabled" and "browser.urlbar.merino.endpointURL" in order to disable new (FF 96+) suggestion service.

**Comment by fxbrit** [comment]
according to [the comments in the source code](https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#490) merino is just a source for quicksuggest, which is already disabled.

**Comment by timur-davletshin** [comment]
@fxbrit so, essentially it takes user input and suggests adds...

https://mozilla-services.github.io/merino/

**Comment by Thorin-Oakenpants** [comment]
instead of pointing at a document - show me exactly how this impacts privacy

**Comment by Thorin-Oakenpants** [comment]
I'm not asking if it works right now, I am asking you to SHOW me the privacy issue - all you said was " it takes user input and suggests adds..." .. what user input (do you mean the firefox user), how is it collected, etc

**Comment by timur-davletshin** [comment]
It takes user input from Firefox address bar and suggest content from third parties.

**Comment by timur-davletshin** [comment]
@rusty-snake ... but your input can be shared with third parties, right?

**Comment by timur-davletshin** [comment]
@Thorin-Oakenpants 

https://bug1727668.bmoattachments.org/attachment.cgi?id=9240786 

lines: 331-392 — address bar input copied to the server without informing user.
lines: 843-866 — clear indication of the purpose of Merino — advertisement.

**Comment by Thorin-Oakenpants** [comment]
that's a useless link - no line numbers etc

https://bugzilla.mozilla.org/show_bug.cgi?id=1727668 -> https://phabricator.services.mozilla.com/D123707

the info about Merino being for sponsored suggestions is well known, so your lines 843-866 are useless

> address bar input copied to the server without informing user.

stop making things up or embellishing them to fit your narrative - the address bar is not copied. Also, nothing is sent without the user opting in (AFAIRemember, I don't think they have rolled this out yet fully, but the user gets a notification panel to OPT-IN) - if you have proof otherwise, then SHOW IT - stop making shit up

At this point I'm inclined to close this as a frivolous waste of my time

lines 331-392 do not say anything about sending an URL, it sends a searchString - DO SOME HOMEWORK and tell me. once again, what "info" is collected .. along with all the other non-answers to all my questions
```
//line 332
+  /**
+   * Fetches a Merino suggestion.
+   *
+   * @param {string} searchString
+   * @returns {object}
+   *   The Merino suggestion object, or null if there isn't one.
+   */
+  async _fetchMerinoSuggestion(searchString) {
+    let instance = this.queryInstance;
+
+    // Fetch a response from the endpoint.
+    let response;
+    let controller;
+    try {
+      let url = new URL(UrlbarPrefs.get("merino.endpointURL"));
+      url.searchParams.set(MERINO_ENDPOINT_PARAM_QUERY, searchString);
+
+      controller = this._merinoFetchController = new AbortController();
+      response = await fetch(url, {
+        signal: controller.signal,
+      });
+      if (instance != this.queryInstance) {
+        return null;
+      }
+    } catch (error) {
+      if (error.name != "AbortError") {
+        Cu.reportError(error);
+      }
+    } finally {
+      if (controller == this._merinoFetchController) {
+        this._merinoFetchController = null;
+      }
+    }
+
+    if (!response) {
+      return null;
+    }
+
+    // Get the response body as an object.
+    let body;
+    try {
+      body = await response.json();
+      if (instance != this.queryInstance) {
+        return null;
+      }
+    } catch (error) {
+      Cu.reportError(error);
+    }
+
+    if (!body?.suggestions?.length) {
+      return null;
+    }
+
+    let { suggestions } = body;
+    if (!Array.isArray(suggestions)) {
+      Cu.reportError("Unexpected Merino response: " + JSON.stringify(body));
+      return null;
+    }
+
+    // Return the first suggestion.
+    return suggestions[0];
+  }
// end
```

**Comment by timur-davletshin** [comment]
> AFAIRemember, I don't think they have rolled this out yet fully

"browser.urlbar.merino.enabled" is already enabled since https://cat-in-136.github.io/2021/12/diff-between-firefox-960-beta-3-default.html

> do not say anything about sending an URL

I didn't say URL, I said "address bar input". I recommend you to follow your own advice: "stop making shit up".

> what "info" is collected

Whatever you input in address bar. Server-side in closed.

**Comment by Thorin-Oakenpants** [comment]
> I don't think they have rolled this out yet fully

There is an opt-in to sponsored suggestions - the merino is part of the back end. pay attention

> I didn't say URL, I said "address bar input"

you are making so much noise without actually saying anything, and wasting my time, that I phrased that offhand

> Whatever you input in address bar. Server-side in closed

So if I type "https://example.com/HERPES?userid='ihaveherpes'" all that is sent is it? What the fuck does "Server-side in closed" mean?

once again, SHOW us "what" info is sent. And you still haven't answered all the other questions. Have you even worked out if not being opted into sponsored suggestions sends any info?

> recommend you to follow your own advice: "stop making shit up"

This is not how you win friends (who own the repo) and influence people

LAST TIME: SHOW where the privacy issue is

**Comment by timur-davletshin** [comment]
@Thorin-Oakenpants 

You're verbally abusive. I file complain. You can do whatever you like with this bug report. I believe I have provided enough information to make it fixed.

**Comment by Thorin-Oakenpants** [comment]
> I file complain

LOLS

> I believe I have provided enough information

You haven't provided ANY information

**Comment by Thorin-Oakenpants** [comment]
such a cry baby .. LEARN TO READ ... https://github.com/arkenfox/user.js/issues/1361#issuecomment-1030135047

but besides all that, you still never showed how any of it was a privacy issue, or even tried to understand how any of it works

emphasis mine
> merino is just a source for quicksuggest, **_which is already disabled_**

**Comment by KOLANICH** [comment]
>which is already disabled

Mozilla surely doesn't mean it be disabled for ever. If they meant this, there would have been no point to implement it at all.

>arkenfox deleted a comment from timur-davletshin 1 hour ago

I don't see anything in the deleted message (at least in its version that has been mailed to me) that justifies it to be deleted.

**Comment by Thorin-Oakenpants** [comment]
> Mozilla surely doesn't mean

FFS .. **_quicksuggest, which is already disabled_**
