### ISSUE TITLE
Unable clean firefox with Ccleaner or Revouninstaller after use Arkenfox.js

### ISSUE THREAD

**Issue by Leonis87** [arkenfox/user.js#1365]
Hi, 
I just noticed that I can't clear any firefox history using Revouninstaller after apply arkenfox.js. I tried change prefs "privacy.sanitize.sanitizeOnShutdown" to false but still nothing. How can I clear history, cookies, cache with revouninstaller or ccleaner ? I know I can clear it using arkenfox preferences but I would like keep it anf clear it with third party software. Is it possible ?

**Comment by fxbrit** [comment]
to keep EVERYTHING on close you would need to flip both `network.cookie.lifetimePolicy` and `privacy.sanitize.sanitizeOnShutdown`. I don't think this makes much sense tho: the built-in cleaning mechanism is the most solid option, and it likely clears more stuff and in a better manner than third party tools will ever do.

**Comment by Thorin-Oakenpants** [comment]
don't use external tools to sanitize firefox, they can easily damage the data - as well as list things incorrectly, such as labeling HSTS entries as cookies. I can't be bothered to find the bugzilla(s), but I've seen reports of issues with corrupted data and/or weird results - e.g. the index was cleared but not the actual data, or vice versa.

There is not need to sanitize with a third party when FF can already do it.

**Comment by Leonis87** [comment]
Thanks for explanation. I'll use built in firefox sanitizing on close.

**Comment by g-2-s** [comment]
If you really have the need for a cleaner I recommend [BleachBit](https://www.bleachbit.org/download), way better than the ones you mentioned in my opinion.

**Comment by remyabel2** [comment]
Looking at the source code of BleachBit, it seems like its method of "cleaning" things is to straight up delete various files. I don't see anything in there that cannot be handled by sanitizing with Firefox.

The only thing that sticks out to me is that they vacuum the sqlite files, but you are better off doing that in `about:support` and not touching the rest of the databases unless you want to risk possible corruption.

**Comment by Leonis87** [comment]
I use bleachbit in Ubuntu. But I found out how to keep history and downloads after close firefox and delete it manualy. I just was curious whether maybe I'm doing something wrong with arkenfox.js. Thanks guys I appreciate your help.
