### ISSUE TITLE
changelog: v97, v98, v99, v100, v101

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1370]
## :green_square: v101

* date: 12-June-2022

[FF101 release notes](https://www.mozilla.org/firefox/101.0/releasenotes/)
[FF101 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/101)
[FF101 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2022-20/)

nothing of consequence... I promise a new clean issue for v102

* new in user.js v101
   - this is part of ETP Strict and will be used in FF102 by default, also see #1457
```js
   // user_pref("privacy.query_stripping.enabled", true); // [FF101+] [ETP FF102+]
```

* removed in user.js v101
   - showing original arkenfox values below
   - these were all active (and now inactive under `0650` for prefsCleaner - **_RUN PREFSCLEANER_** )
   - `noopener` and `window.name` have been default true since FF79 and FF86 respectively
   - `trimURLs` is cosmetic fluff, see #1473
   - `cookie.thirdparty` is slated for removal upstream and may cause issues with the lifetime cookie pref deprecation and site exceptions, and is also covered by sanitizing on close
```js
user_pref("browser.urlbar.trimURLs", false);
user_pref("dom.targetBlankNoOpener.enabled", true);
user_pref("network.cookie.thirdparty.sessionOnly", true);
user_pref("network.cookie.thirdparty.nonsecureSessionOnly", true);
user_pref("privacy.window.name.update.enabled", true);
```

- [[all changes](https://github.com/arkenfox/user.js/compare/100.0...101.0)]
- [ToDo: diffs FF100-FF101](https://github.com/arkenfox/user.js/issues/1461) issue
- v101 PR is at #1443

---

## 🟩 v100

* date: 9-May-2022

[FF100 release notes](https://www.mozilla.org/firefox/100.0/releasenotes/)
[FF100 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/100)
[FF100 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2022-16/)

* new in user.js v100
```js
user_pref("browser.download.always_ask_before_handling_new_types", true); // FF101+
   // user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true); 
```

* moved to `9999: DEPRECATED / REMOVED` in user.js v100
   -  replaced by `network.http.http2*` prefs
```js
   // user_pref("network.http.spdy.enabled", false);
   // user_pref("network.http.spdy.enabled.deps", false);
   // user_pref("network.http.spdy.enabled.http2", false);
   // user_pref("network.http.spdy.websockets", false);
```

- [[all changes](https://github.com/arkenfox/user.js/compare/99.0...100.0)]
- [ToDo: diffs FF99-FF100](https://github.com/arkenfox/user.js/issues/1439) issue
- v100 PR is at #1423 

---

## 🟩 v99

* date: 9-April-2022

[FF99 release notes](https://www.mozilla.org/firefox/99.0/releasenotes/)
[FF99 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/99)
[FF99 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2022-13/)

v99 was cosmetic changes and one pref deprecated

* moved to `9999: DEPRECATED / REMOVED` in user.js v99
```js
user_pref("security.csp.enable", true);
```

- [[all changes](https://github.com/arkenfox/user.js/compare/98.0...99.0)]
- [ToDo: diffs FF98-FF99](https://github.com/arkenfox/user.js/issues/1418) issue
- v99 PR is at #1419

---

## 🟩 v98

* date: 10-March-2022

[FF98 release notes](https://www.mozilla.org/firefox/98.0/releasenotes/)
[FF98 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/98)
[FF98 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2022-10/)

v98 was just cosmetic changes
- [[all changes](https://github.com/arkenfox/user.js/compare/97.0...98.0)]
- [ToDo: diffs FF97-FF98](https://github.com/arkenfox/user.js/issues/1390) issue
- v98 PR is at #1372

---

## 🟩 v97

* date: 13-February-2022
* foreword: These are all the changes since the last changelog ([v96](https://github.com/arkenfox/user.js/issues/1345)).

[FF97 release notes](https://www.mozilla.org/firefox/97.0/releasenotes/)
[FF97 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/97)
[FF97 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2022-04/)

---

### OTHER NEWS

- revamped new shiny improved simpler faster stronger lighter cleaner magnificently stupendously [awesome wiki](https://github.com/arkenfox/user.js/wiki)
  - still a couple of things to do, but mostly done
  - thanks everyone for their feedback 
  - see #1354 if you want
- fission
  - since we opt of out of rollouts, we had to wait for the pref flips in stable
- @fxbrit (aka 🐟 ) is an admin for this repo
   - congrats 🐟 
   - 🐟 is a maintainer for Librewolf (LW) mac
   - 🐟 is more than that though. I have been working behinds the scenes with 🐟 for about a year: initially for selfish reasons: to align LW more with AF so as to not give AF a bad rep (there is/was a perception that LW was essentially AF)
   - In that time, LW and AF are now _almost_ identical (for things that matter), and in fact, a few changes have resulted because we have worked together to clean things up: such as WebRTC
   - 🎉 party at fxbrit's house

---

### CHANGELOG: [[all changes](https://github.com/arkenfox/user.js/compare/96.0...97.0)]
* links to bugzilla tickets and default pref changes in Firefox are in our [ToDo: diffs FF96-FF97](https://github.com/arkenfox/user.js/issues/1366) issue
* v97 PR is at #1346 <sup>1</sup>
* for all the rest see the full list of pref changes below

<sup>1</sup> see #1299 - starting with v97, all changes to the live master happen once per release: all changes are done in a separate branch/PR and only merged when finished

:star: your friendly reminder to [ALWAYS run prefsCleaner](https://github.com/arkenfox/user.js/wiki/3.5-prefsCleaner)

![62baz6](https://user-images.githubusercontent.com/16656956/150662274-33812185-e970-47e7-899e-72d18cc83f06.jpg)

---

### CHANGES

- new in user.js v97
```js
user_pref("browser.places.speculativeConnect.enabled", false); // [FF98+]
```

- made inactive in user.js v97
   - 0403 `browser.safebrowsing.downloads.remote.enabled` is already false
   - this makes it easier for users to override since the pref needs to be "looked up"
```js
   // user_pref("browser.safebrowsing.downloads.remote.url", ""); // Defense-in-depth
```

---

### STATS

```
 STATS v97: up to and including section 4500, minus the parrots
 =========
    total: 213
 inactive:  43
           ---
   active: 170
  default:  22 (at least)
      n/a:   2 (of the three prefs in 0204, only one will apply)
      n/a:   1 (0605 is FF98+)
           ---
  flipped: 146 (at most)
```

**Comment by Thorin-Oakenpants** [comment]
placeholder

**Comment by fxbrit** [comment]
> party at fxbrit's house

to the person who stole my pokemon pijama last night: please return it asap.

**Comment by earthlng** [comment]
@fxbrit 

> - @fxbrit (aka 🐟 ) is an admin for this repo
>    - congrats 🐟 

welcome on board, mate. Glad to have you. 👍 IDK who stole your pijama though - wasn't me :)
