### ISSUE TITLE
yandex reverse image search

### ISSUE THREAD

**Issue by strongBurger** [arkenfox/user.js#1371]
Hello,

I installed arkenfox on my firefox 78.15.0ESR
All seem to work except when trying to use yandex reverse image search ( https://yandex.com/images )
I get this result with any image i send : https://ibb.co/HdKHtBy

I cannot find what prevent the actual image to be sent normally

note: when using google reverse image search there is no problem

**Comment by KOLANICH** [comment]
It is likely they use Canvas. Just block javascript on that website and write a "surrogate" userscript. Don't forget to share it.

**Comment by remyabel2** [comment]
Firefox 78 is EOL. You should upgrade to 91.

**Comment by Thorin-Oakenpants** [comment]
closing as invalid - failed to read the wiki (RFP canvas is there) or search for existing answers (RFP canvas is there) or search for setup tags (RFP canvas is there)

```
/* 4501: enable privacy.resistFingerprinting [FF41+]
 * [SETUP-WEB] RFP can cause some website breakage: mainly canvas, use a site exception via the urlbar
```

also, unsupported FF version
