### ISSUE TITLE
Extensions question - redirector v. privacy redirect

### ISSUE THREAD

**Issue by WeirDan76** [arkenfox/user.js#1373]
Quick question about recommended addons. In order to redirect URLs (cf. redirect foo.com to bar.com, for instance), the Wiki recommends Redirector, which gives quite some degree of freedom. Conversely, Privacy Redirect focuses only on major social media websites, but automates it all and probably does better than mere hand-made redirects. On github, Privacy redirect had 149 open issues, while Redirector has 99 -- not great for either. On AMO, Privacy Redirect was updated 7 months ago, while Redirector was updated almost 2 years ago. 
Based in this, any reason to recommend one and not the other? Any feedback?
Dan

**Comment by remyabel2** [comment]
> On AMO, Privacy Redirect was updated 7 months ago, while Redirector was updated almost 2 years ago.

Says August 18, 2021 and November 6, 2021 for me.

> Based in this, any reason to recommend one and not the other? Any feedback?

Unless you want to set up all the redirects yourself, might as well use both.

**Comment by WeirDan76** [comment]
Well noted. For Redirector, says 26 March 2020 for me.
Sure, both can be used together but 1) I am queasy about using simultaneously using two addons that are more or less doing the same thing (seems like they could interfere with each other), and 2) it is sound to try and limit the number of addons used.

**Comment by WeirDan76** [comment]
Thanks for chipping in, @Thorin-Oakenpants. I don't have a dog in this fight and I am still new to this. My own reason to be interested is to limit tracking and, therefore, to avoid sites that are full of trackers. So if tracking is fully addressed via FPI/dFPI, maybe this isn't needed after all. Then the question becomes, what could be a valid use case for addons like these? I use invidous/nitter/etc. when directly accessing social media, but am somehow worries about social used on websites that I visit, esp. when logged in. Maybe that's misplaced worry?

**Comment by Thorin-Oakenpants** [comment]
ugh, don't @ name me, it resubscribes

**Comment by WeirDan76** [comment]
Kinda tried to bring you back in with a question ;)

**Comment by m77e4t** [comment]
There is this new extension 'Libredirect' forked from the original Privacy redirect. It is well maintained and has added extra redirections for medium, tiktok, etc. 
If you want, you can use it. Work really well. https://github.com/libredirect/libredirect

I am not affiliated with the project or checked the code myself, so if you want to download and use it, do it on your risk. It is pretty new extension, so it is upto you.
