### ISSUE TITLE
(FAQ) Deleting prefs.js have the same effect of using prefsCleaner.sh or .bat?

### ISSUE THREAD

**Issue by NameLessGO** [arkenfox/user.js#1376]
Previously was using this method because thought it would cause the same effect but was never sure and after reading the wiki for the second time, was not sure

Thanks in advance

**Comment by theltalpha** [comment]
No, deleting prefs.js resets _every_ preference, including those _not_ being modified by user.js. I don't think you want to do this. prefsCleaner only resets those preferences being or having at some time been modified by user.js.

**Comment by Thorin-Oakenpants** [comment]
No where does arkenfox or the wiki recommend or say to delete prefs.js - so why do it?

https://github.com/arkenfox/user.js/wiki/2.2-Backup
> <sup>1</sup> `prefs.js` is a runtime file that includes more than just your pref changes, and backing up `prefs.js` does not cover all the things a `user.js` can alter.

READ THE WIKI (I know you tried)

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/3.5-prefsCleaner
- added a warning

> 🟥 Warning: **DO NOT DELETE PREFS.JS**. `prefs.js` is a runtime file that includes more than just your pref changes.
