### ISSUE TITLE
Can't load a background map

### ISSUE THREAD

**Issue by eliemada** [arkenfox/user.js#1377]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 INFO
  - Browser version & OS:
  - Steps to Reproduce (STR):
  - Expected result:
  - Actual result:
  - Console errors and warnings:
  - Anything else you deem worth mentioning:

---

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
STR:
Go to https://explorer.helium.com/hotspots
And wait for the map to load

You should have a background map loading
I get a grey background
I was wondering how to solve that?

**Comment by fxbrit** [comment]
it requires enabling webgl.

please the next time fill the template otherwise it will just be closed as invalid.
