### ISSUE TITLE
Waterfox?

### ISSUE THREAD

**Issue by martin-braun** [arkenfox/user.js#1378]
Out of curiosity, is the user.js compatible with Waterfox and does it even make sense to use it?

**Comment by Thorin-Oakenpants** [comment]
- https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=
> We do not support forks or no-longer supported releases.

- https://github.com/arkenfox/user.js#readme
- > Also be aware that the arkenfox user.js is made specifically for desktop Firefox. Using it as-is in other Gecko-based browsers can be counterproductive, especially in the Tor Browser

**Comment by martin-braun** [comment]
I'm sorry for hesitating instead of reading, thanks for your reply. :)

**Comment by ByJumperX4** [comment]
Waterfox is basically Firefox ESR with backported features from rolling Firefox and some extra features that do not affect privacy, I use Waterfox with the ESR options enabled, seems to be fine (checked results of websites like browserleaks to compare with regular ESR, seems to be the same)
