### ISSUE TITLE
Installing user.js on all profiles?

### ISSUE THREAD

**Issue by martin-braun** [arkenfox/user.js#1379]
I like how the script allows me to pick a profile with the `-l` flag, but is there a way to enforce to install the user.js on all profiles? If not, it would be nice if this would be possible. :)

**Comment by Thorin-Oakenpants** [comment]
what script are you talking about?

**Comment by martin-braun** [comment]
@Thorin-Oakenpants Sorry that I wasn't clear enough. I'm talking about the [updater.sh](https://github.com/arkenfox/user.js/blob/master/updater.sh).

I can probably come up with my own implementation, it is really just iterating the profile folder and copying the user.js into it, I just thought it might be a useful addition to have a flag in the script itself to do that.

Could you please re-open this issue? If there is no interest in implementing that, someone else might like the idea and want to contribute, maybe even my persona.

**Comment by xfzv** [comment]
Just use `-p` argument:

```sh
./updater.sh -p ~/.mozilla/firefox/path/to/profile
```

You can pass it multiple times for two or more profiles or use several shell commands like `fd` to find all of them for you. I'm on mobile right now but it should be pretty easy to set up.

**Comment by martin-braun** [comment]
@xfzv Hi, thank you I know I can use `-p`, but I want to target all installed profiles *automatically*. The script is already capable to scan the `profiles.ini` using the `-l` element, so why not introducing a flag that combines both to install the `user.js` into *ALL* installed profiles.

Use case: I'm planning to create a profile for each provider (Google, Apple, Amazon, etc.) to prevent cross-service tracking for privacy reasons. I'm thinking even about to run this script whenever I `startx` by putting the call into my `.xinitrc`. I think it would be brilliant to add this feature for users who often manage profiles.

Of course I can simply do multiple calls for multiple profiles and I will probably just iterate the profiles myself for that, but why not include it into the `updater.sh` to bring this to more people right away? My thoughts.

**Comment by rusty-snake** [comment]
>  I'm planning to create a profile for each provider (Google, Apple, Amazon, etc.) to prevent cross-service tracking for privacy reasons. 

https://github.com/arkenfox/user.js/wiki/1.1-to-arkenfox-or-not

> - [State Partitioning](https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning)
> 
>   - [Network Partitioning](https://blog.mozilla.org/security/2021/01/26/supercookie-protections/)
>   - [Total Cookie Protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) (dFPI / Dynamic First Party Isolation)
>   - [Enhanced Cookie Clearing](https://blog.mozilla.org/security/2021/08/10/firefox-91-introduces-enhanced-cookie-clearing/) along with sanitizing1 on close

**Comment by rusty-snake** [comment]
> update all existing profiles.

1. You need to run prefsCleaner
2. You need to check changelogs
3. > Arkenfox changes to the live master happen once per release: all changes are done in a separate branch and only merged when finished.
