### ISSUE TITLE
Facebook comment weird issue.

### ISSUE THREAD

**Issue by Leonis87** [arkenfox/user.js#1380]
Hi 
I just noticed that I have weird facebook behaviour when  I try comment something... So when I start write comment on facebook, whole page just roll down and comment window with flashing coursor is shifted to the bottom of the screen. I don't have a clue which preference is responsible for this.

**Comment by Thorin-Oakenpants** [comment]
read - https://github.com/arkenfox/user.js/blob/master/.github/ISSUE_TEMPLATE/troubleshooting-help.md
> unchecked issues ~~may~~ will be closed as invalid

**Comment by Leonis87** [comment]
Browser version & OS: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Firefox/97.0

Steps to Reproduce (STR):
So I tried facebook comments on ubuntu this time with same user.js and same overrides.js and surprisingly there wasn't any scroll down issue. However in windows 10 problem remains same. I also tried disable all addons, I only have ublock, smart referer, and canvasblocker but not success. So I assume there must be something wrong with preferences...

Console errors and warnings:
. This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see     https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!

. [CanvasBlocker] invalid content script order: require not defined at https://www.facebook.com/ 
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

**Comment by Thorin-Oakenpants** [comment]
[https://github.com/arkenfox/user.js/issues/new](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI

---

Still invalid. You talk about overrides, you talk about extensions Have you confirmed that this is caused by AF - no extensions, no overrides, in a new profile (so none of your other changes from years ago or whatever).  NEW PROFILE + AF + TEST

**Comment by Leonis87** [comment]
I tried every possible solution. I spent some time on this, trust me no joke. Facebook comment without AF works fine on new profile. I tried with and  without overrides. I even reinstall firefox. I tried on two different windows machines and also I tried on my mate's laptop with windows 10 proffesional. On windows same everywhere. I don't know what else I sholud try...

**Comment by Thorin-Oakenpants** [comment]
> Facebook comment without AF works fine on new profile

Finally. So you have confirmed it not an upstream issue

> I tried with and without overrides

By this I assume you mean you tried with the master arkenfox user.js only in a NEW profile with no extensions

> I don't know what else I sholud try...

You haven't even told us what you tried. [Have you read the wiki I keep linking to?](https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting) There is a list of prefs that cause common issues - did you check those - in the new profile with no old pref changes and no extensions? There is a list of prefs tagged with `[SETUP` in the user.js - did you check those - in the new profile with no old pref changes and no extensions?

I'm not going to waste time, and I'm taking a hard stand on this, helping anyone who can't follow instructions. If you did the manual troubleshooting outlined in the wiki, you can very quickly narrow it down from half to a quarter to 1/8th to 1/16th of the user.js to find the problem
