### ISSUE TITLE
How do I know what the change settings do in about:config?

### ISSUE THREAD

**Issue by gun4qmm7h** [arkenfox/user.js#1381]
I just installed arkenfox after watching Techlore and wanted to reverse some things e.x. (firefox starting in window, website are weird size, can't use url for search engine). Is there a list of what the settings you changes do? I've been googling and couldn't find anything

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI

**Comment by rusty-snake** [comment]
> Is there a list of what the settings you changes do?

https://github.com/arkenfox/user.js/blob/master/user.js
