### ISSUE TITLE
Homepage still blank even after overriding with user_pref("browser.startup.homepage", "about:home");

### ISSUE THREAD

**Issue by r00bit1984** [arkenfox/user.js#1384]
- Browser version & OS: Firefox 97.0.1 Windows 10
  - Steps to Reproduce (STR): user_pref("browser.startup.homepage", "about:home"); in user-overrides.js
  - Expected result: Homepage (when the browser starts) is about:home
  - Actual result: its still a blank page.
  - Console errors and warnings: - 
  - Anything else you deem worth mentioning: - 

---

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/4f3f789f2837547d0e65609d96cbf8d5510390d6/user.js#L83-L87

**Comment by r00bit1984** [comment]
> https://github.com/arkenfox/user.js/blob/4f3f789f2837547d0e65609d96cbf8d5510390d6/user.js#L83-L87

Thank you, this solved my issue.

**Comment by rusty-snake** [comment]
Next time check `[SETUP-` tags before opening issues. :innocent:

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI
