### ISSUE TITLE
Reconsider [SECTION 1700]: CONTAINERS

### ISSUE THREAD

**Issue by OdinGitDat** [arkenfox/user.js#1387]
Since containers are redundant now with the introduction of TCP (dFPI), maybe the preferences under section 1700 should be left on false or at least include some more documentation explaining the situation.

**Comment by rusty-snake** [comment]
Why should container be redundant with dFPI but not with FPI? Containers are not redundant with TCP/dFPI.

**Comment by OdinGitDat** [comment]
The wiki says this:
```
Temporary Containers, Cookie extensions

    Redundant with [Total Cookie Protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) (dFPI) or FPI
    ❗️Sanitizing in-session is a false sense of privacy. They do nothing for IP tracking. Even Tor Browser does not sanitize in-session e.g. when you request a new circuit. A new ID requires both full sanitizing and a new IP. The same applies to Firefox
    ❗️Cookie extensions can lack APIs or implementation of them to properly sanitize
```
and the [Librewolf docs](https://librewolf.net/docs/faq/#why-isnt-first-party-isolate-enabled-by-default) say this:
```
Please also notice that dFPI makes containers and containers extensions redudant, unless you want to protect your privacy when visiting the same website multiple times, during the same browsing sessions.
```

**Comment by rusty-snake** [comment]
This was already the case with FPI.

**Comment by rusty-snake** [comment]
Containers are still useful:
- multiple logins
- phishing and "advanced CSRF" mitigation
- permission isolation
- ...

_Yes I know pants don't care about such edge cases._

**Comment by fxbrit** [comment]
when we evaluated this with privacyguides, in an effort to produce a coherent message on the need for extensions, we figured that most users were convinced containers had isolation or sanitization benefits -> both false info -> stick to built-in isolation and reduce attack surface and complexity, no need to have a full blown setup of automatically opening containers that will achieve..nothing at all.

yes, there's the corner case of multiple logins, or websites that use SSO (eg. google and youtube), but that's minimal and we figured you still have a private window to get an extra login + if needed containers are exposed in the UI without needing extensions. the functionality provided by that UI should be more than enough as these are niche cases, that do not apply to most website and users, so there's no need to encourage containers use outside of that.

closing for the above mentioned reasons, we can keep the discussion going tho.

**Comment by rusty-snake** [comment]
Do we talk about "plain containers" or TC?

> as for permissions, do you mean giving the website different permissions in different containers?

TC auto+isolation with `permissions.isolateBy.userContext=true`

> I would be interested in the phishing bit, can you expand?

If every login happens in an own container (no matter if plain, MAC, TC), clicking a malicious link (in the default container or an other container) can not do bad things that require login (one example).

**Comment by OdinGitDat** [comment]
> If every login happens in an own container (no matter if plain, MAC, TC), clicking a malicious link (in the default container or an other container) can not do bad things that require login (one example).

Why not?

**Comment by rusty-snake** [comment]
Because you are not logged in ;)

**Comment by OdinGitDat** [comment]
A phishing attack like that usually depends on the user providing login details themselves, no? Containers cannot protect against that. The CSRF attack depends on existing cookies being sent with a request made by a malicious page, but dFPI already protects against that.

Am I missing a scenario?

**Comment by rusty-snake** [comment]
Well yes if you enter your password nothing will help. (But containers may make you notice the attack).

Regarding CSRF, if it is done as third-party request yes but if it is done first-party by linking e.g. `<a href="https://forum.example.com/foobar.php?thread=123&comment=Unicorn">click me</a>`.

**Comment by fxbrit** [comment]
if the website that you logged into is at least respectable, that request would not carry the authentication cookie, as it should have a strict or lax policy. but sure it's totally possible that some websites suck, and either way this is an interesting (and possibly unintended?) corner case :-)

**Comment by opusforlife2** [comment]
> containers had isolation or sanitization benefits -> both false info -> stick to built-in isolation and reduce attack surface and complexity, no need to have a full blown setup of automatically opening containers that will achieve..nothing at all.

@fxbrit Right now (version 100), the text and accompanying links under `1700: CONTAINERS` present them as this "supa awesome powa" thing that everyone should use. The specific mention of the Temporary Containers extension, along with the Medium article extolling its virtues, together make it seem like an obvious go-to for improving privacy and security. I can't think of another pref or section where this is the case.

If, as the wiki and the LibreWolf docs say, containers don't provide any _privacy_ or _security_ benefits over the status quo, then that section should be removed entirely, and the container prefs should be moved to the `9000: PERSONAL` section, which includes the rest of the usability stuff.

If not, then the wording of the section should be changed, at the very least. "Containers are useful for signing into multiple accounts on the same website. They may improve usability, but have no privacy/security benefits."

**Comment by fxbrit** [comment]
> the container prefs should be moved to the 9000: PERSONAL section, which includes the rest of the usability stuff.

I disagree with this because if one needs containers for multiple logins it is handy to have it there without installing an extension.

the argument about removing the temporary containers' links makes sense tho, let's see what pants thinks about it.

**Comment by opusforlife2** [comment]
> I disagree with this because if one needs containers for multiple logins it is handy to have it there without installing an extension.

Sorry, I didn't get this. What does moving the prefs have to do with the extension?

**Comment by Thorin-Oakenpants** [comment]
OA's can be chained

**Comment by Thorin-Oakenpants** [comment]
> Sorry, I didn't get this.

The prefs enable containers without an extension. The user.js flips the prefs from default. So they will not be moved to personal

**Comment by opusforlife2** [comment]
> The user.js flips the prefs from default. So they will not be moved to personal

Doesn't the Personal section already contain prefs changed from the default?

Either way, I saw the commit. The new version is much better, thanks!

> OA's can be chained

Wot

**Comment by opusforlife2** [comment]
> And the commit removed valuable links. 

I'm not arguing against that. By all means, please restore them. But the _presentation_ of the section, _taken as a whole_, was somewhat misleading. "Hey look at this great extension! Here are a bunch of benefits it provides!" It reads like an advertisement. This is the only extension that's mentioned in the user.js, too, which makes it seem all the more 'official' as a recommendation.

How likely is it that a user would remember that out of all the extensions mentioned in the wiki, Temporary Containers is one of the ones marked "don't bother"? To be honest, I didn't. I read the entire wiki. I read the entire user.js, including several of the Bugzilla and other links. And when, a long, _long_ time later, I finally sat down to customise the user.js prefs for my profile, I _forgot_ that TC was one of the "don't bother" extensions. And so I've been using this "don't bother" extension thinking that it's AF-recommended. Which it isn't.

_All I'm saying_, is that there is some _ambiguity_ between what is being said in the wiki and the textual presentation in the `1700: Containers` section. It would be easily removed by adding what I stated above:

> "Containers are useful for signing into multiple accounts on the same website. They may improve usability, but have no privacy/security benefits."

> fuck it, out it all goes

Jeez, way to make a person feel guilty.

---

> Origin Attributes

I know the term. What I don't understand is what 'chaining' means. A container inside PB would have been a good example, except it can't occur. And dFPI is all internal, from what I understand. So what would be an example of chaining? Or, where does it occur in everyday browsing? dFPI between multiple tabs in a single container?

**Comment by Thorin-Oakenpants** [comment]
> By all means, please restore them

No. Fuck it. Gone :) You are right that it doesn't quite fit with the revamped wiki. It's not an advert, the links were all relevant. TC is pretty awesome. Especially if users couldn't handle FPI. But now we have dFPI. And TC has always been redundant with FPI/sanitizing. I will never please everyone, so fuck it .. out it goes

> I know the term

then you know that OA's can be used in tandem. FPI is dFPI but without the visual syntax. It's still there.

Am locking conversations on old issues, sorry. These are old resolved issues - I can do without the noise
