### ISSUE TITLE
Is user.js able to block this? 

### ISSUE THREAD

**Issue by Wastelander72** [arkenfox/user.js#1389]
Hi, there is a long story of two unsolicited requests that used to be impossible to block, I would like to know if they are still present in FF and if user.js should be able to prevent them (I have read somewhere that they should be added to the hosts file but I don't know how exactly) :

firefox.settings.services.mozilla.com
 aus5.mozilla.org

BTW I'm using Arch Linux. Thanks in advance.

**Comment by Thorin-Oakenpants** [comment]
who said they're unsolicited? where is this long story? what is the purpose of those connections? are they a privacy issue? you can't even tell me that this is EVEN HAPPENING
- > I would like to know if they are still present
