### ISSUE TITLE
delete cookies and site data  Can't close, close Firefox and open it by itself

### ISSUE THREAD

**Issue by ycolor** [arkenfox/user.js#1391]
delete cookies and site data  Can't close, 

close Firefox and open it by itself

**Comment by Thorin-Oakenpants** [comment]
I can't understand any of that, it's complete nonsense

---

[https://github.com/arkenfox/user.js/issues/new](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI
