### ISSUE TITLE
Revert the auto download feature

### ISSUE THREAD

**Issue by Mmoi-Fr** [arkenfox/user.js#1393]
Hi,

FF98 seemed to introduce the auto download feature (who loves that risky thing that is auto download?).

The pref associates is:
browser.download.improvements_to_download_panel
false => old popup
true => auto dl

It would fit in the script IMO

**Comment by rusty-snake** [comment]
Can you outline why `2651` isn't enough with ` browser.download.improvements_to_download_panel=true`.

https://github.com/arkenfox/user.js/blob/d9af90d05f477e5e25f8d9f545eeb7fe0a235d2a/user.js#L736-L739

**Comment by Thorin-Oakenpants** [comment]
There is already an intervention for downloads, as rusty-snake says

and ... rusty edited his comment ... yes `browser.download.improvements_to_download_panel` will be removed, just like every other rollout UI pref change, ever
