### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Ganesha2282882** [arkenfox/user.js#1395]
It would be nice to have an installer for arkenfox. Not a post-install script, but an actual installer like it's another browser. And I'm honest, this is totally feasible (With ~50 lines of PowerShell). Here is an ascii flowchart of how it works:
```
(Installer runs)->[Download a fresh (non-stub) Firefox exe]->[Download arkenfox user.js]->[Extract the ``core'' folder in Firefox]
|----------------------------------------------------------------------------------------------------------<-|
v
[Move the ``core'' folder to the home directory]->[Install arkenfox user.js by opening FF, and closing it, then installing as normal]
|----------------------------------------------------------------------------------------<-|
v
(End)
```
It's completely automated (except for confirmation dialogs). You can base it off my project: https://codeberg.org/brahma/arkenfoxinstaller.git

**Comment by g-2-s** [comment]
No offense but Arkenfox is not a browser last I checked and the updater script does its job just fine. If you're looking for the "another browser" experience might as well just install Librewolf.

**Comment by Thorin-Oakenpants** [comment]
arkenfox is not something you "install" - it requires making changes, which is you read the user.js or readme or wiki you would know
