### ISSUE TITLE
Letterboxing can't turn off

### ISSUE THREAD

**Issue by Ganesha2282882** [arkenfox/user.js#1396]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS:
  - Steps to Reproduce (STR):
  - Expected result:
  - Actual result:
  - Console errors and warnings:
  - Anything else you deem worth mentioning:

---

Everything I do, letterboxing won't go away. Invert the value, it comes back after a restart. Delete the value, it comes back.

Info:
```json
{
    "os": "Windows 10",
    "actual": "Letterboxing will permanently be enabled.",
    "expected": "Letterboxing will be disabled permanently.",
    "console_errors": "None",
    "steps_to_reproduce": "Delete the letterboxing about:config toggle. Restart the browser."
}
```

**Comment by rusty-snake** [comment]
You must use [overrides](https://github.com/arkenfox/user.js/wiki/3.1-Overrides) because a [user.js overrides prefs in prefs.js](https://github.com/arkenfox/user.js/wiki/2.1-User.js)..

**Comment by fxbrit** [comment]
^ this.
