### ISSUE TITLE
Question: Overrides for passwords and urlbar shortcuts

### ISSUE THREAD

**Issue by Roscisco** [arkenfox/user.js#1398]
Hello. I wish to set a few preferences through user-overrides.js so that they are maintained through updates. I've read through the wiki, override recipes, user.js, and answered issues, but haven't found an answer.

* **Disable password manager**
 I'd like to disable Firefox's internal password manager, so that I'm no longer prompted about saving a password. I currently have to do this through about:preferences#privacy --> Logins and Passwords --> uncheck "Ask to save logins and passwords". Updating resets this preference.

* **Disabling "Shortcuts" sites suggestions on urlbar**
 Firefox suggests some sites by default on the urlbar, such as Facebook and Twitter. These are disabled through about:preferences#privacy --> Address Bar --> uncheck "Shortcuts". Updating resets this preference.
I've tried including these preferences in user-overrides.js , but they do not change the Shortcuts preference.
`user_pref("browser.urlbar.suggest.engines", false);`
`user_pref("browser.urlbar.suggest.topsites", false);`

How may I go about adding these overrides? 

Thanks,

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/d9af90d05f477e5e25f8d9f545eeb7fe0a235d2a/user.js#L983-L986

Do you not have an `user-overrides.js` and have you not run the updater script to append your changes to the user.js?

https://github.com/arkenfox/user.js/wiki/3.1-Overrides
> - EVERYONE will need some "overrides". You do this by keeping them in a separate user-overrides.js file in your profile folder, so updating doesn't wipe them but instead appends them.
> - user-overrides.js (you create this file)

https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain
- it does not get any simpler than this
- > - Put all the relevant files into the root folder of your profile [1]
   >   -  prefsCleaner
   >   -  updater
   >   -  user.js
   >   -  user-overrides.js (which you created) <---
   > - 🔽 CONTINUE with the UPDATE part below
   > ...
   > - run updater

Is there something wrong with the wiki? I cannot make it any simpler? You said you read it

**Comment by Roscisco** [comment]
I was unable to find `5003` on user.js when using Xed, but I've found it as shown when using Vim. I've also corrected a mistake on my part when adding `browser.urlbar.suggest.topsites` to user-overrides.js .

I'm sorry to have bothered you, and thank you for your answer.
