### ISSUE TITLE
It requires typing the complete URL in search bar rather than simple words for any search

### ISSUE THREAD

**Issue by kaurav99** [arkenfox/user.js#1399]
As I type anything in search bar and hit enter, it automatically gets convert into a URL format for ex. if I type "google" and hit enter, it will become "https://google", thus gives incorrect address error.

I don't have much knowledge, please help me out. Attached screenshots for reference.

![gh1](https://user-images.githubusercontent.com/86246542/159122666-7a9e2e28-45bb-4c3f-ac69-7d7ee3945975.png)
![gh2](https://user-images.githubusercontent.com/86246542/159122674-a6c9591c-07fa-4de6-86b3-7f712b037584.png)

**Comment by Thorin-Oakenpants** [comment]
the answer is in the wiki,and the user.js itself

---

[https://github.com/arkenfox/user.js/issues/new](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI

**Comment by Thorin-Oakenpants** [comment]
clue: https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]#-common ... 0801

**Comment by kaurav99** [comment]
Ok got it, thanks for the clue. In the future, won't bother you with silly issues.
