### ISSUE TITLE
VPN extensions not working in expected manner.

### ISSUE THREAD

**Issue by kaurav99** [arkenfox/user.js#1401]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
☑️ I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Windows | 98.0.1 (64-bit)
  - Steps to Reproduce (STR):
  - Expected result : VPN Extensions to work exactly the way they are intended to.
  - Actual result: Not giving expected result.
  - Console errors and warnings:
  - Anything else you deem worth mentioning: If anything in user.js that is restricting those extensions to work efficiently and can be changed to achieve the expected result.

---
In hardened profile VPNs taking too much time to get connect to the server and even if they get connect by chance there is a DNS leak (I used https://www.expressvpn.com/dns-leak-test for the test)
To know if it was a problem with user.js, I created a separate profile and only added the one extension i.e. Windscribe to test if I get the same issue but in new profile it was working fine and in test there was no local IP leak.
Attaching screenshots of both the profiles, please help me in this,
Thank you.

**New profile Without arkenfox user.js**
![New profile Without arkenfox user.js](https://user-images.githubusercontent.com/86246542/159163180-d022a801-c37b-438e-a535-a96edddaed0b.png)

**Hardened profile with arkenfox user.js**
![Hardened_profile_arkenfox_userdotjs](https://user-images.githubusercontent.com/86246542/159163268-ecf12be3-e8b5-4e08-a08a-804a0eceaad4.png)

**Comment by fxbrit** [comment]
this seems pretty hard to reproduce, given that I don't expect many to use a VPN extension (why do these even exist? how do they actually work behind the scene?), leave alone that specific one..

if it's nothing more than a proxy, the user.js is instead set-up to force dns queries inside it, so I would expect the exact opposite.

**Comment by Thorin-Oakenpants** [comment]
FF98 new profile with arkenfox master

![vpn](https://user-images.githubusercontent.com/16656956/159198108-5a9660ce-7f12-4300-a132-e9227a1e94ea.png)

![vpn2](https://user-images.githubusercontent.com/16656956/159198122-2f856d95-4c72-413c-8ffb-da36e3d1b0df.png)

![vpn3](https://user-images.githubusercontent.com/16656956/159198128-b615d14d-9062-4d50-991f-4de490f5246f.png)

**Comment by Thorin-Oakenpants** [comment]
I fail to see how this has anything to do with AF to be honest. Use a proper VPN. My other observation, last night, was that on Nightly (where I have about 20 pref changes like sanitizing, nothing major - i.e no arkenfox), I got the opposite results

**Comment by icpantsparti2** [comment]
I tried it with default arkenfox without issue, but if you have uBlock Origin running look at the "Uncloak canonical names" setting: https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

**Comment by Thorin-Oakenpants** [comment]
interesting, my nightly has uBO

nightly with uBO enabled = shows dns exposed x 6
nightly with uBO enabled but disabled for test site = shows dns exposed x 6
nightly with uBO disabled = no leak

all tests done with restarts and full sanitizing in between

**Comment by Thorin-Oakenpants** [comment]
> To know if it was a problem with user.js, I created a separate profile and only added the one extension i.e. Windscribe to test if I get the same issue but in new profile it was working fine and in test there was no local IP leak.

But then OP didn't say they then added arkenfox to that new profile and tested again. OP only said they had a problem in their hardened profile. OP did not show that arkenfox caused this issue. Unless OP says otherwise, this is invalid

**Comment by Thorin-Oakenpants** [comment]
https://old.reddit.com/r/Windscribe/comments/p0ywxn/dns_leak_with_windscribe_for_firefox_addon_ublock/

**Comment by Thorin-Oakenpants** [comment]
despite OP not following instructions - AF does recommend uBO, so I'll mark this as answered so it's more visible

**Comment by kaurav99** [comment]
Yeah, after disabling Uncloak canonical names it is working perfectly, and really sorry for not mentioning that it was working fine with edge, brave and in Firefox hardened profile too but with system-wide VPN.

**Comment by krystian3w** [comment]
https://github.com/arkenfox/user.js/issues/1519
