### ISSUE TITLE
How to uninstall and reverse changes

### ISSUE THREAD

**Issue by Satlinker** [arkenfox/user.js#1404]
Hi, there is a very detailed wiki to arkenfox, but unfortunately no easy install and uninstall instructions. How can I uninstall arkenfox and reverse all changes?

**Comment by rusty-snake** [comment]
Restore your [Backup](https://github.com/arkenfox/user.js/wiki/2.2-Backup). Or remove the user.js and prefs.js (which will reset *all* prefs).

**Comment by Satlinker** [comment]
Thanks, no way to just remove the arkenfox changes?

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/wiki/3.5-prefsCleaner

**Comment by Satlinker** [comment]
do I have to remove user.js and user-overrides.js before of after the cleaner? I don't want to damage anything.

**Comment by rusty-snake** [comment]
prefsCleaner reads the user.js.

**Comment by Satlinker** [comment]
doesn't work. I ran prefscleaner and then delete user.js. Still not able to change e.g. Only HTTPS-mode manually.

**Comment by Thorin-Oakenpants** [comment]
> doesn't work

It does work. Please learn the basics on how a user.js works, and how prefsCleaner works - right there in the wiki

Arkenfox has no idea what your _previous_ values were - your pre-AF profile may have had HTTPS-Only mode and may have ETP set to strict, etc (from manual changes). prefsCleaner will _reset_ **_to default_** all the prefs listed in the user.js (the user.js needs to be there so it knows what to remove them from prefs.js). Then before you restart, rename the user.js (or delete it or whatever) and it literally cannot be applied anymore

What does "Still not able to change e.g. Only HTTPS-mode manually" even mean? don't bother answering
