### ISSUE TITLE
Add in the end (commented) the mozilla connection than can be disabled

### ISSUE THREAD

**Issue by BirdInFire** [arkenfox/user.js#1406]
Note before (have open up an issue since it's related to the user.js file and not the process to generate/update it).
If i have miss-categorized I apologize.

I actually have seen some settings who disable some feature from Mozilla services (commented), is it possible, add in the end of the user.js some who can't be disabled to not break the security/privacy/functionality of the browser ?

One example to know what i mean by that : "extensions.abuseReport.amoDetailsURL" who call "https://services.addons.mozilla.org/api/v4/addons/addon/" does emptying it will cause the extension update to stop working or updating ?

So now the "why" i ask this on the end of the file.
Because lately Mozilla became less and less trustworthy, so reducing to the very minimum connection to them can matter for some of us (the tracker number in the installer (windows)).

And it's why for me (and potentially other) having in the "do not touch" (commented) all the settings, security/privacy related who call a Mozilla owned domain witch cannot be disabled or it will break major security function, can be handy, like that people like me "just" have to find manually all the link who point to Mozilla server and if we doubt (like my example above witch i truly don't know if disabling it will break my add-on update/installation process (so i do not have modified it)) we can check if it's listed in the "do not touch" section.

If you don't add it in user.js, can it be (at least) listed on the read-me or an additional file ?

Additional info : i manually apply update by checking the DIFF on my file and the one into this git (like that i can check what the change do and eventually whitelist website before do the change.

**Comment by Thorin-Oakenpants** [comment]
please show where any privacy issue exists instead of making generalized statements (which is all FUD)

> Because lately Mozilla became less and less trustworthy

and there's a red flag if I ever saw one

I am not going to waste any of my time explaining why your request or assumptions are BS
