### ISSUE TITLE
Major problem in your helping tool

### ISSUE THREAD

**Issue by BirdInFire** [arkenfox/user.js#1407]
Please specify: 
- Open an Issue.
- Say something true
- Ask help to fix what we see as concerning ourself without even asking for doing it for all in the user.js
- Be Rudely responded and locked without even have the answer to the question.
- Be marked as spam.

How to fix the bug : 
- Stop to be this rude to user who push concern based on real issue (https://www.ghacks.net/2022/03/17/each-firefox-download-has-a-unique-identifier/).
- Close as invalid if you think it's the case BUT do note mark this same user as "SPAM" when it's not true.

Additional info :
It seem the module courtesy do not work properly since some contributor are rude as **uck with everyone (when i have rapidly checked the history of these "invalid" response).

Note: will not come again here this bug in the tool "contributor" must be in the history of the closed (since he/she will surly rudely close this one too and limit me but i do not care since this rude human being just prove that the last Firefox user are like Mozilla, rude to their user-base

Good day to ya

**Comment by Thorin-Oakenpants** [comment]
> who push concern based on real issue

what a load of trash. what does this do that an already existing per-profile id doesn't

> Note: will not come again here

good

**Comment by Thorin-Oakenpants** [comment]
point of order

> Say something true

this is false. nothing said was true. nothing was stated or proven. all OP did was spout conspiracy and nonsense without a shred of evidence or any facts

**Comment by Thorin-Oakenpants** [comment]
also, marked as spam like the last one, because 1) it annoys you and 2) it is spam
