### ISSUE TITLE
Some additions for user.js that are worth.

### ISSUE THREAD

**Issue by EdwardLangdon** [arkenfox/user.js#1408]
`security.secure_connection_icon_color_gray` Changes the colour of the secure connection padlock icon in the address bar to white/black (depending on if your theme is light ordark), or green. Enabled by default.

Set to true for white/black, and false for green.

Set as Green in AF.

For Autoplay - `media.autoplay.default` = 5 [0:allow; 1:blockAudible; 5:blockAll]

**Comment by Thorin-Oakenpants** [comment]
I'd have to look up the reasoning for the removed color, but IIRC its part of a longer term strategy on UX. Color doesn't mean anything IMO

Also, since we use HTTPS-Only mode, every site that is not HTTPS is going to have an interstitial (for those that are excepted, then at least on the first visit), so I fail to see what coloring up the icon will do

**Comment by rusty-snake** [comment]
IIRC the reason was/is to mark unsafe sites as unsafe instead of safe sites as safe as safe (https) is/should be the default in the web. Therefore the color moved from green/safe to red/unsafe.

**Comment by Thorin-Oakenpants** [comment]
right .. i'm not going to bother digging up the comments from bugzilla, but that's it from memory - i.e instead of checking for green (which is over half the internet's top sites and something like 80% of traffic), you should be noticing red (was less frequent) - i.e the change is more noticeable

**Comment by rusty-snake** [comment]
> security.secure_connection_icon_color_gray

And FF 100 is going to remove it.

**Comment by Thorin-Oakenpants** [comment]
yeah I noticed that and was going to find this issue to mention it

**Comment by EdwardLangdon** [comment]
> > security.secure_connection_icon_color_gray
> 
> And FF 100 is going to remove it.

No, I need it. Just Updated Firefox and noticed things. Need to fix Overrides.

**Comment by Thorin-Oakenpants** [comment]
you can most likely use userChrome.css and base64 if you want to - don;t ask me, try at r/firefoxcss

**Comment by Thorin-Oakenpants** [comment]
also perhaps watch https://old.reddit.com/r/firefox/comments/uhqt6p/changing_securitysecure_connection_icon_color/
