### ISSUE TITLE
CSS Exfil Vulnerability Tester Fail

### ISSUE THREAD

**Issue by BwntyHntr** [arkenfox/user.js#1409]
🟪 REQUIRED INFO
  - Browser version & OS: 98.0.2
  - Steps to Reproduce (STR): Visit https://www.mike-gualtieri.com/css-exfil-vulnerability-tester
  - Expected result: Your browser is Not vulnerable 
  - Actual result: Your browser is vulnerable 
  - Console errors and warnings: None
  - Anything else you deem worth mentioning: is you install their extension the issue fixes, however if I can fix this using user.js without an additional extension that would be best

---

**Comment by crssi** [comment]
I guess you have read the extension part of wiki https://github.com/arkenfox/user.js/wiki/4.1-Extensions, saying

> CSS Exfil Protection
    Practically zero threat and if the platform's CSS was compromised, you'd have bigger problems to worry about

This was already resolved... you can also gain from using search on closed tickets.

Cheers
