### ISSUE TITLE
Questions about some additional extensions with arkenfox

### ISSUE THREAD

**Issue by thisisauniquename** [arkenfox/user.js#1411]
Hello, I would like to start by saying thank you for the time and energy put into making this guide. I have a few questions concerning using some extensions.

1. Free Download Manager: As we know, FF's native download manager is not the best. I have been using Free Download Manager for stable/faster DLs, but I am sure that this is a no-no with running an arkenfox setup. If it's a no, do I have any ways of optimizing FF's downloads or using another method?

2. DarkReader: Yes or no? If no, what options do I have? I know how to change the color of the about:blank background but that's about it.

3. Qwant search extension: I use Qwant and have no issues with the search engine, however, any vulnerabilities from using the extension? Should I just bookmark the SE and go about it that way?

Thanks in advance

**Comment by rusty-snake** [comment]
2. https://github.com/arkenfox/user.js/issues/655#issuecomment-771060430
3. Just use a opensearch plugin for it ([my](https://codeberg.org/rusty-snake/firefox-config/src/branch/main/search-plugins)).

**Comment by Thorin-Oakenpants** [comment]
I personally wouldn't install search extensions
- i assume this is it - https://addons.mozilla.org/en-US/firefox/addon/qwantcom-for-firefox/
- if you trust em, sure. If it adds extra benefits like settings that it passes to the page, sure.

you can add qwant natively
![search](https://user-images.githubusercontent.com/16656956/160890522-0ee351ec-b02d-4d54-9440-7e98a048655b.png)

**Comment by rusty-snake** [comment]
or from https://mycroftproject.com/search-engines.html?name=qwant to get a plugin without the `&client=opensearch`.

**Comment by thisisauniquename** [comment]
Thank you for the quick responses. Using the Qwant plugin now instead of the extension. Exactly what I needed. It's a shame about the fingerprinting with darkreader. I really do prefer an easy-on-the-eyes experience and it's rarely made sites unusable. Maybe I can find some overlay color inversion software....

**Comment by Thorin-Oakenpants** [comment]
FWIW it's doubtful you'll get fingerprinted from using Dark Reader (or such)
- naive scripts are, well .. umm .. naive (and not likely to test it)
- advanced scripts don't need it
- most scripts are blocked already (ETP, uBO)
- most scripts are universal (widespread) - which they need to be in order to link (as a general rule)

The web needs to be usable for you in your everyday browser. So you do you :)
