### ISSUE TITLE
XSinator still detects exposure after applying arkenfox

### ISSUE THREAD

**Issue by BwntyHntr** [arkenfox/user.js#1413]
🟪 REQUIRED INFO
  - Browser version & OS: V98.0.2
  - Steps to Reproduce (STR): Run all tests in https://xsinator.com/testing.html (From Appendix A)
  - Expected result: All the results should be green.
  - Actual result: A third of the results are exposed.
  - Console errors and warnings: None.
  - Anything else you deem worth mentioning: 
  
Here is the full result of the test after applying arkenfox user.js:
  
![image](https://user-images.githubusercontent.com/81967491/160903250-398066d2-af65-4b2e-a412-5ef38ae24c3f.png)

This is the result on a default profile without any changes:

![image](https://user-images.githubusercontent.com/81967491/160904761-378da17e-b43d-4041-b868-da4f91062770.png)

---

**Comment by Thorin-Oakenpants** [comment]
these are all upstream issues that need to be addressed by browser engines, gecko is not alone

**Comment by BwntyHntr** [comment]
Oh I see, ok, thank you.

**Comment by Thorin-Oakenpants** [comment]
> XSinator still detects exposure after applying arkenfox

AF doesn't claim to protect against known limitations

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1746302
