### ISSUE TITLE
How to manage multiple logins on the same domain?

### ISSUE THREAD

**Issue by 82721350** [arkenfox/user.js#1414]
Hi,

I feel like I need some tips[^1] because MAC[^2] was removed from wiki[^3] and TC[^4] is no longer recommended[^5] because how TCP[^6] from ETP _Strict_[^7] (also know as dFPI[^8] or FPI[^9], do not confuse with RFP[^10]) works. I know that wiki want to keep the things simple[^11], and some users asked related questions before[^12][^13], but I discover these add-ons here[^14] and now I want to know how to deal with or what do you recommend me for multiple logins[^15]: do I still need MAC[^2], native container[^16] are fine[^17], or none of them[^18]? One more question: should I use private tab as TC[^4] substitute? In order to explain it better, let me say the following example[^19] prior ETP _Strict_[^7]:

1. Persistent container[^2]. _Youtube_. Dark theme[^20]. Sign-in with personal account. For regular purposes uses.
2. Persistent container[^2]. _Youtube_. Dark theme[^20]. Never sign-in. Use for listen and find similar genre music (recommended vids[^21]).
3. Non-persistent container[^4]. _Youtube_. Light theme[^20]. Never sign-in. Used for watch videos non-based on my previous searches[^22].

Thanks in advanced for any help, and also let me thanks you for your hard work here guys[^23].

[^1]:I has been reading the wiki multiple times with no luck.
[^2]:Firefox **M**ulti-**A**ccount **C**ontainers (MAC) [add-on](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/).
[^3]:https://github.com/arkenfox/user.js/wiki/4.1-Extensions/_compare/2ba0b9f16b435cf4013e08101cbdf46c711e81df...d774eb66ab0cb6a871803f4454dba5e411ac7819
[^4]:**T**emporary **C**ontainers (TC) [add-on](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/).
[^5]:https://github.com/arkenfox/user.js/wiki/4.1-Extensions/_compare/c4b18f09f0e6beca20697a1085a6c5514442c88a...7077b361a0061cd2fb57bf37b9e4a0888006bef2
[^6]:**T**otal **C**ookie **P**rotection (TCP) is a new [feature](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/).
[^7]:**E**nhanced **T**racking **P**rotection (ETP). [See more](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop).
[^8]:**d**ynamic **F**irst **P**arty **I**solation (dFPI) will be enabled if user select _Strict_ in the ETP menu in Settings.
[^9]:[See differences](https://www.reddit.com/r/firefox/comments/je8juq/difference_between_fpi_firstparty_isolation_and/go1lny8/).
[^10]:**R**esist **F**inger**p**rinting (RFP). [See more](https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting).
[^11]:_This list covers privacy and security related extensions only_. [4.1 Extensions / FOREWORD](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-foreword).
[^12]:https://github.com/arkenfox/user.js/issues/1344#issuecomment-1019379645
[^13]:https://github.com/arkenfox/user.js/issues/1387#issuecomment-1054567626
[^14]:https://github.com/arkenfox/user.js
[^15]:Sign in in the same website (e.g. Youtube) with different account.
[^16]:https://blog.mozilla.org/tanvi/2016/06/16/contextual-identities-on-the-web/
[^17]:It does not compromise ETP _Strict_.
[^18]:Arkenfox's user.js + `user-overrides.js` + current recommended wiki extensions = is enough to do the job?
[^19]:Imaginary scenario.
[^20]:Theme is provided just for clarify it better.
[^21]:I'm talking about that [Youtube](https://www.youtube.com/intl/en_us/howyoutubeworks/product-features/recommendations/) thing.
[^22]:I know that there are many alternatives like _invidious_, but this is a example[^19].
[^23]:I don't want to sound rude or troll, but non-friendly terms become at some point fucking sick.

**Comment by rusty-snake** [comment]
Just just containers (or MAC if you need additional the features provided by it) or TC or PBM or whatever.

**Comment by 82721350** [comment]
So isn't TC redundant like wiki say[^1]? If I added a cookie exception with `Ctrl+I` for a website in a Persistent container, cookies stored from that site in non-container tabs are going to keep alive after Firefox close; and that's what TC prevented.

[^1]:_Temporary Containers_ (is) _Redundant with_ [Total Cookie Protection](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) (dFPI) or FPI. [4.1 Extensions / DON'T BOTHER](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-dont-bother)

**Comment by Thorin-Oakenpants** [comment]
> what do you recommend me for multiple logins

do what every one else does. This has nothing to do with AF's goal of privacy, security, tracking

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/4.1-Extensions
> This list covers privacy and security related extensions only.

Here's an imaginary venn diagram ... just because AF doesn't list an extension does not mean it can't be used .. but

> We recommend keeping extensions to a minimum [... blah blah]

MAC is developed by Mozilla, so you're pretty safe

PS: in future, don't post 23 links as sups or shit like that, it made it almost unreadable and I was about to shitkick the entire post
