### ISSUE TITLE
Service workers

### ISSUE THREAD

**Issue by CaptainFrosty** [arkenfox/user.js#1417]
Hello, I recently switched to using vanilla FF from a fork, and I started getting a bunch of DNS queries to `push.services.mozilla.com` that I never got on the fork, even though notification permissions have always been blocked. I was befuddled, until I realized I had an ass-ton of service workers. Are these not a privacy risk? The old browser had them disabled by default, and I guess I assumed without really thinking about it that the custom user.js would too.

**Comment by Thorin-Oakenpants** [comment]
https://old.reddit.com/r/firefox/comments/txylj7/firefox_sending_out_connections_to_push/
> these frequent DNS queries to `push.services.mozilla.com`

why would a session need to keep re-querying the DNS? do you mean that it simply connects to `push.services.mozilla.com`

checking in with the push server at mozilla is not a privacy issue - you need to actively subscribe to push notifications per site
```
/* 7019: disable Push Notifications [FF44+]
 * [WHY] Push requires subscription
 * [NOTE] To remove all subscriptions, reset "dom.push.userAgentID"
 * [1] https://support.mozilla.org/kb/push-notifications-firefox ***/
   // user_pref("dom.push.enabled", false);
```

SW API is not disabled, but cannot be used by web content because cookie permissions are session only (for now, because we use the cookie lifetime pref = session), and this will throw a security error when a SW is attempted

When we move from session cookies by default (the cookie lifetime pref will be deprecated), then SWers are partitioned
```
/* 2710: enable state partitioning of service workers [FF96+] ***/
user_pref("privacy.partition.serviceWorkers", true);
```

If you want to control third parties then use uBO

**Comment by Thorin-Oakenpants** [comment]
> until I realized I had an ass-ton of service workers

there should be no ASS-TON of SWers in arkenfox - excluding system ones, the only ones that can happen are if you allow a cookie and site exception

if this isn't your case, then you must have modified the cookie lifetime pref AFAICT

**Comment by CaptainFrosty** [comment]
@Thorin-Oakenpants I'm sure the DNS info is cached locally, but either way Firefox attempted to connect roughly every hour according to my logs (`autopush.prod.mozaws.net` also), and it hasn't since I disabled the SWs.

I am glad you mentioned cookie lifetimes, so thanks for that, it made me remember I use Adguard to disable third-party cookies systemwide  by setting TTL to 0. So judging from what you say perhaps that was the culprit, but I can assure you the SWs were there and I never approved any exceptions. Thanks for the explanation as well, obviously I didn't know they were being controlled through a different mechanism when I posted.

I'm not sure what an invalid label is supposed to mean exactly.

**Comment by CaptainFrosty** [comment]
My Firefox cookie settings are not overridden.

**Comment by Thorin-Oakenpants** [comment]
invalid because everything you said was wrong

show me the ASS-TON of SWers in about:serviceworkers . If default cookies are session only, SWers cannot be created. If you added an exception to cookies + site data as `allow` then that site exception can create a SWers, but it is isolated to eTLD+1 and scheme

the fact that you seem to instantly associate connections as evil and claim mozilla will soon becoming google is disturbing to say the least (although that's not what you said here, but at reddit) - try to be a better person and think critically

as for push services, there has to be at least one central point to sent them to from the website, and to get them from for the receiver - it only makes sense that it be a mozilla server (not sure if this shit is E2E, because I never subscribe to any push notifications)

**Comment by Thorin-Oakenpants** [comment]
> invalid because everything you said was wrong

also you didn't follow the rules when logging an issue (posted below for you)
- namely that it doesn't happen in a new profile with arkenfox with no overrides

---

[https://github.com/arkenfox/user.js/issues/new](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI

**Comment by CaptainFrosty** [comment]
I didn't use the bug report because I didn't have a bug to report. If there were a discussion area I would have used that. I was simply seeking information on service workers and why Firefox would be unnecessarily pinging these servers. Which it is still doing every hour on the dot with no service workers; I was incorrect earlier. 

It may be wrong, but it is happening nonetheless. I'll switch off the Adguard and see if the SWs return. I can't prove it to you right now as I already unregistered them. I did not realize I would be taken as a liar by default. If they return again I'm sure there is some way I could show them while proving I'm using the script, but frankly what's the point; the connections are blocked so this is a minor issue. We've wasted enough time. 

I'm not a networking/security expert, nor do I claim to be. If I were I probably would not be here. I do know enough to know that everything I said is not wrong. You just may not believe it. This behavior with the push servers doesn't exist in several FF forks I've used, so clearly someone other than me cares about it and I'm not just making up "wrong" things to post in a Github repo, for funsies.  My knowledge may be deficient (my reason for being here), but I haven't been rude. Meanwhile it's been unceasing hostility from you. I tend to use colorful phrases, which you enjoy repeating, I apologize if that offends you. I try not to take reddit too seriously. It's a crapshoot for tech support anyway.

I'm gonna go now, because your attitude and clear sense of superiority have prolonged and ruined what could have been a quick one-and-done after your explanation (which was helpful, sincerely).  

I realize it's annoying when people don't follow the procedures you put in place in the way you want them to. Assuming it's an intentional slight and getting angry at people over minutiae is no way to live life, though. But it's your repo, your right. It's the attitude that gets me, not the chastening for not following the steps. I think you could use a big slice of humble pie. Maybe just eat the whole damn thing. So long, and thanks for the information, truly.

**Comment by Thorin-Oakenpants** [comment]
> Assuming it's an intentional slight and getting angry at people over minutiae is no way to live life

I'm not angry at all, I'm just being REALLY HARD on making people read the wiki and user.js before asking for help

**Comment by fxbrit** [comment]
for reference https://support.mozilla.org/en-US/kb/push-notifications-firefox

a few highlights:

> Push messages are encrypted per the IETF spec, and only your copy of Firefox can decipher them. The encrypted messages are stored on the server until they are delivered or expired.

> Firefox maintains an active connection to a push service in order to receive push messages as long as it is open. The connection ends when Firefox is closed. We store a randomized identifier (User Agent IDentifier or UAID) on our server for your browser, along with a random client-generated identifier for each push subscription.

> If you don't have any active push notification subscriptions, Firefox rotates the UAID on each new connection.

> We store your IP address for 90 days as part of this service. The stored information is invalidated when either the IP Address or UAID is changed


very good implementation imo.
