### ISSUE TITLE
Question : What is really network.http.referer.XOriginPolicy (a.k.a document.referrer / number 1601)

### ISSUE THREAD

**Issue by d4rklynk** [arkenfox/user.js#1420]
So I really read the wiki, and the explanation in the user.js but I really don't understand it. What does it actually do in normal case, and what will it block when set to 2 ?

**Comment by g-2-s** [comment]
There is a link in Section 1600 of the user.js that explains it fairly decently: https://feeding.cloud.geek.nz/posts/tweaking-referrer-for-privacy-in-firefox/

**Comment by d4rklynk** [comment]
Nice thank you a lot, I get it now !

**Comment by d4rklynk** [comment]
Oh yeah I didn't see the link in the user.js. I'm sorry ! Thank you !
