### ISSUE TITLE
Disabling Pocket totally

### ISSUE THREAD

**Issue by EdwardLangdon** [arkenfox/user.js#1421]
These are some of the remainings of pocket after using `user_pref("extensions.pocket.enabled", false); // Pocket Account`

```
extensions.pocket.site = ""
extensions.pocket.oAuthConsumerKey = ""
extensions.pocket.api = ""
```

The above addition might be great to add.

**Comment by Thorin-Oakenpants** [comment]
If you don't have a pocket account then those three prefs do nothing

the pref `extensions.pocket.enabled` is enough to remove pocket account menu entries and toolbar icons. If you don't have an account then the pref is handy to remove clutter
