### ISSUE TITLE
`2620` interaction with RFP

### ISSUE THREAD

**Issue by fxbrit** [arkenfox/user.js#1424]
one last thing I would like to do is look at `2620` `pdfjs.disabled` since RFP now reports it pdfjs as enabled (which is the default and which we enforce). I should check the browser behavior with an actual pdf (the pref directly affects the navigator property) - and depending on the results, add something to the effect that RFP enforces pdfjs as enabled

Not keen on moving it to `[SECTION 8000]: DON'T BOTHER: FINGERPRINTING` because those who don't use RFP may get the wrong message (it is perfectly fine to override as true it if you are not using RFP, in favor of some other pdf viewer - we set a good default and it's on the end user, not us)

_Originally posted by @Thorin-Oakenpants in https://github.com/arkenfox/user.js/issues/1419#issuecomment-1093796489_

also see https://github.com/arkenfox/user.js/pull/1419#issuecomment-1100569314

**Comment by fxbrit** [comment]
I did some testing on Nightly.

**STR**:
- create a new profile.
- disable pdfjs.
- go to https://www.apple.com/legal/sla/ and try to open the "iPod (PDF)" file.

**results**:
- seems like the browser thinks pdfjs is enabled, but since it isn't it just cannot work and it throws an error. the file is still downloaded at least.
  - I see no RFP correlation with this behavior, the result is the exact same with or without it and it only depends on the handler recognizing that `2620` changed and reacting accordingly.
  - about:preferences > Applications also seems confused, in fact until you click it the handler for pdf is just empty. after clicking it, it flips to always ask and it does not offer an option to use nightly as a pdf reader, so it just seems like it's not listening for a change in that pref until triggered.

**notes**:
- arkenfox is also affected after flipping `2620` but this seems like an upstream issue I guess. it's probably enough to mention that `2620` requires a restart so that the browser can recognize whether it's been flipped or not.
- same behavior when flipping `browser.download.always_ask_before_handling_new_types` and `browser.download.useDownloadDir` as pdf files are set to open in nightly by default.
- RFP doesn't really seem to matter, the browser probably just checks for `2620` and then it decides whether it should give an option to open PDFs in nightly or not. is there a corner case of some kind tho? not sure atm.

**Comment by Thorin-Oakenpants** [comment]
I _think_ the RFP patch just ensures that navigator items are returned the same, and doesn't actually affect behavior
- their is a bug about the handlers missing pdf, it was fixed today I think

**Comment by Thorin-Oakenpants** [comment]
> there is a bug about the handlers missing pdf, it was fixed today I think

https://bugzilla.mozilla.org/show_bug.cgi?id=1759984

WTF you going to do when I'm gone? _sigh_

**Comment by fxbrit** [comment]
> I think the RFP patch just ensures that navigator items are returned the same, and doesn't actually affect behavior

looks like it, yup.

> Not keen on moving it to `[SECTION 8000]: DON'T BOTHER: FINGERPRINTING`

I would say is completely fine for both RFP and non-RFP users to do what they want with that pref nah? RFP users are covered and non-RFP users might as well not bother about something like this.
