### ISSUE TITLE
Pocket Service

### ISSUE THREAD

**Issue by fastcat001** [arkenfox/user.js#1425]
In your latest release, you have:

`user_pref("extensions.pocket.enabled", false);`

However, I've to override the same `user_pref("extensions.pocket.enabled", false);`
in order to disable Pocket service.

Why is this happening?

**Comment by fxbrit** [comment]
it's commented, see https://github.com/arkenfox/user.js/blob/4ff931781a1bf012e0e7e2ec89dc5c2a9bedd890/user.js#L1312

**Comment by Thorin-Oakenpants** [comment]
READ THE WIKI
- https://github.com/arkenfox/user.js/wiki/2.1-User.js#-syntax
