### ISSUE TITLE
question about RFP and webgl

### ISSUE THREAD

**Issue by MagicalDrizzle** [arkenfox/user.js#1428]
do I still need canvasblocker if I use both RFP and webgl? (and will enabling webgl jeopardize any RFP protection?)
couldn't find this in the wiki, my apologies

**Comment by crssi** [comment]
![image](https://user-images.githubusercontent.com/17024151/164405076-24249077-55f5-47f9-90f3-e5388e606da0.png)
Additionally I am using `Audio API`, `DOMRect API`, `SVG API` and `TextMetrics API`.

Maybe some salt and pepper over my comment from @Thorin-Oakenpants ?  🍺 ❤️

**Comment by fxbrit** [comment]
> I use both RFP and webgl?

what do you mean you use both? are they enabled or disabled?

anyway answers to both @crssi and @MagicalDrizzle are [in this part of the wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-recommended).

also relevant to form an opinion on RFP and implement a setup that suits you -> https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D

**Comment by MagicalDrizzle** [comment]
> > I use both RFP and webgl?
> 
> what do you mean you use both? are they enabled or disabled?
> 
> anyway answers to both @crssi and @MagicalDrizzle are [in this part of the wiki](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-recommended).
> 
> also relevant to form an opinion on RFP and implement a setup that suits you -> https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D

both enabled
