### ISSUE TITLE
Firefox still sending out a ton of packets to several different IP addresses

### ISSUE THREAD

**Issue by z0z0z** [arkenfox/user.js#1431]
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

**- Browser version & OS:**

Firefox 98.0.2 Arch Linux x86_64

**- Steps to Reproduce:**

1) Create brand new prefix: `firefox -no-remote -p`
2) Insert the Arkenfox user.js into `~/.mozilla/firefox/profile.whatever`
3) Start Wireshark packet sniffer on a network-quiet system
4) Start Firefox on that prefix

**- Expected result:**

Firefox doesn't sends out tons of packets

**- Actual result:**

Firefox sends out an extreme amount of packets to several different IP addresses

**- Console errors and warnings:**

N/A

**- Anything else you deem worth mentioning:**

Is it literally impossible to stop Firefox from making unsolicited connections now? On top of Arkenfox's user.js I've even disabled OCSP and removed literally every single URL in about:config and it still makes an extreme amount of connections

**Comment by fxbrit** [comment]
https://github.com/arkenfox/user.js/issues/1389#issuecomment-1059933161

**Comment by z0z0z** [comment]
@fxbrit So is it literally impossible? Is there anyone else trying? Is Firefox just spyware no matter what now?

**Comment by fxbrit** [comment]
trying what? please read the answer linked above and answer the questions yourself:

> what is the purpose of those connections? are they a privacy issue?

**Comment by z0z0z** [comment]
> trying what?

To stop Firefox from making any automatic connections on startup.

> please read the answer linked above and answer the questions yourself:
> what is the purpose of those connections? are they a privacy issue?

I don't know what the purpose of those connections are (who does?) 

I personally don't care what their purpose is, I don't want Firefox sending a single packet on startup regardless. I achieved this several years ago but it seems to quite literally be impossible today.

**Comment by fxbrit** [comment]
> (who does?)

me and others who do their homework.

> I personally don't care what their purpose is

so since you don't know nor you care to know, stop the proof-less "firefox spyware" FUD.

**Comment by z0z0z** [comment]
Well, I actually did it. **I made Firefox dead silent on the network.**

You can't just search "url" in about:config

**If you manually go through about:config and blank out every single domain you can find, Firefox will send zero packets on startup**

It still sends some DNS queries to my router, but after searching "dns" in about:config and disabling prefetching stuff, it's now dead silent.

**Comment by fxbrit** [comment]
so?

> what is the purpose of those connections? are they a privacy issue?
