### ISSUE TITLE
Change the Enhanced tracking protection to custom

### ISSUE THREAD

**Issue by prorounak2005** [arkenfox/user.js#1436]
Setting Enhanced tracking protection to custom and enabling all the check boxes will allow firefox to block more stuff.
Also it would be good if the cookies drop down list is set to "All third party cookies" and in the tracking content drop down list is set to "In all windows".
Here is the screenshot of my firefox enhanced tracking protection - http://0x0.st/oAzy.png

**Comment by prorounak2005** [comment]
There are many extensions like cookie auto delete which cannot work on strict mode. It works better on strict mode - 
Here is a related issue- https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1046
Some cookies are not getting deleted because the firefox setting is set to strict. Setting it to custom works. Custom setting with all the check boxes ticked on , tracking content set to " block in all windows" and cookies option set to "block third party cookies" works much better than the strict mode.

**Comment by Thorin-Oakenpants** [comment]
> Setting Enhanced tracking protection to custom and enabling all the check boxes will allow firefox to block more stuff.

and in the process remove the very protections that partitioning (the ones governing Total Cookie Protection) gives you from state tracking

CAD is already noted in the wiki as a waste of time and that it does not working with dFPI

You achieve nothing by blocking third party site data except breakage. 3p is already isolated - there is nothing there to be scared of.

You achieve nothing by sanitizing in session (excluding the obviously e.g. forget about this siet, multiple logins) if you're not also changing your IP, and extensions can lack the ability to sanitize properly (OMFG ... see CAD). The only way (containers aside) to properly sanitize is on close. Even Tor Browser does not sanitize in session e.g. when you request a new circuit.
