### ISSUE TITLE
Jittery / Low FPS videos on reddit and invidious instance

### ISSUE THREAD

**Issue by Nothankslads** [arkenfox/user.js#1437]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 99 on fedora 35
  - Steps to Reproduce (STR):  Launch reddit or invidious instance, play any video (tested so far)
  - Expected result: Normal video playback
  - Actual result: jittery and low FPS video
  - Console errors and warnings: Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. (not sure if related, comes up every time i open a new tab or do anything)

  - Anything else you deem worth mentioning:
  -
Safe mode, and disabling webgl have not seemed to help in fixing it, so it must be a prefs issue

---

**Comment by Thorin-Oakenpants** [comment]
https://old.reddit.com/r/firefox/comments/uh2zqj/arkenfox_hardened_firefox_videos_are_very_jittery/

What am I supposed to do with this? Did you find your solution/answer? I haven't read of any video stuttering due to RFP. Do you have a link I can test on?

**Comment by Thorin-Oakenpants** [comment]
closing as invalid: as per the editing at reddit
> Edit: It was upstream. Fedoras RPM firefox was funky. Flatpak has fixed the issue.
