### ISSUE TITLE
Welcome & What's New Notices doesn't work

### ISSUE THREAD

**Issue by d4rklynk** [arkenfox/user.js#1438]
When toggle What's New switch to `user_pref("browser.startup.homepage_override.mstone", "")` I have a blank page.

When I have my update, a welcome page is opening but it will be blank.
After searching on internet, I read that Firefox downloads regularly that kind of pages. If you want to enable What's New page, you need to say in the comments that there's another switch to toggle (it seems to be in startup requests or telemetry I didn't find yet)

How to reproduce the bug : just go `about:welcome`

**Comment by Thorin-Oakenpants** [comment]
> How to reproduce the bug : just go about:welcome

That's not the problem, you just explicitly went there. Closing as invalid until you provide proper STR and follow the instructions

FWIW, arkenfox does, by default, stop welcome and update pages from loading

---

[https://github.com/arkenfox/user.js/issues/new](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

>  Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

> 🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
> - [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
>    - _unchecked issues ~~may~~ will be closed as invalid_

READ THE WIKI
