### ISSUE TITLE
Add link to relevant changelog from Releases (for atom/RSS readers)

### ISSUE THREAD

**Issue by Victor239** [arkenfox/user.js#1440]
I want to be able to get atom/RSS updates with the changelog for each new release. Normally on most software I use they include it in the GitHub Releases, so I can just subscribe to https://github.com/arkenfox/user.js/releases.atom and receive the changelog as a new entry each time.

For whatever reason you've decided to go with using GitHub Issues for your changelog. Perhaps for the commenting functionality because you don't want to maintain a blog with comments instead, I'm not sure. Either way it'd be very helpful if there was a link to the relevant GitHub Issue changelog when you make a new Release.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/releases/tag/99.0
- do you mean where I have written "End of stable..." to instead list the changes?

it's just how we did things from the start. A changelog issue allows users to comment (mind you, so does the diffs issue I guess), and I always do a release first so I can link to all the changes (but I can edit the issue afterwards)
- e.g. `https://github.com/arkenfox/user.js/compare/97.0...98.0`
- and I use this to help check and create the changelog (but I don't HAVE to)

What you're asking is doable, but means I need to rethink my steps
- create changelog issue
- create release with changes iterated (just a simple list, nothing else), and link to changelog issue
- edit changelog with release links

Question
- if I create the release with the description blank, and then fill in the description afterwards, what happens in your rss feed?

**Comment by Thorin-Oakenpants** [comment]
> Either way it'd be very helpful if there was a link to the relevant GitHub Issue changelog when you make a new Release.

Sorry, got ahead of myself. You just wanted a link to the changelog. So the question still stands. My understanding is I need to create the changelog first and to always put that in the release description on creation. If that's the case, it's no big deal to also itemize the actual changes (but more work for me)

**Comment by Thorin-Oakenpants** [comment]
here's an example
![example](https://user-images.githubusercontent.com/16656956/166552026-5f34c6c1-8aa3-4de6-af6a-2ef18d2082eb.png)

**Comment by rusty-snake** [comment]
>  if I create the release with the description blank, and then fill in the description afterwards, what happens in your rss feed?

![Screenshot_2022-05-03_19-35-53 png-fs8](https://user-images.githubusercontent.com/41237666/166552833-7a6b1bd1-a5cb-4473-b8f6-1e696c986a49.png)

**Comment by Thorin-Oakenpants** [comment]
I'm not a RSS feed expert - isn't that because your feed grabbed the info after my edit. What if it already had that release feed and I edit afterwards - that's what I'm asking. I used to use quiteRSS and that grabs the headline and a snippet, which is cached locally. Is your feed live though - on a webpage? 

But I guess my answer is to always create the changelog first and to always make sure I fill in the description before creating a release - right? Or if I fuck up, quickly get the description in?

**Comment by rusty-snake** [comment]
> What if it already had that release feed and I edit afterwards - that's what I'm asking.

It will depend on your rss viewer. Some will show the updated version but some might stick to the first fetched version. IDK.

**Comment by Thorin-Oakenpants** [comment]
> It will depend on your rss viewer

that's what I thought, so to be safe ... I guess I can try and do that from now on

**Comment by Victor239** [comment]
> if I create the release with the description blank, and then fill in the description afterwards, what happens in your rss feed?

I'm not sure actually, I can test it with my TinyTinyRSS instance if you'd like. 

Another way of doing it is that some projects add just a few summary highlight changes in the Release section, with a link to a longer post with all the changes. That might be simpler if you're concerned about the diff between the two changelogs being too big.

**Comment by adamcstephens** [comment]
I appreciate the better notes in the release feed. Thanks for improving this!

When I added the commits feed to miniflux it only gives me the commit message which isn't super helpful.

**Comment by Thorin-Oakenpants** [comment]
> When I added the commits feed to miniflux it only gives me the commit message which isn't super helpful.

Since user.js commits are done once per release in a PR (e.g. v100 etc), and each PR can have multiple commits, this probably isn't going to be very helpful - except it will show you that other commits have been made - e.g. to prefsCleaner, updaters, scratchpad etc

Use https://github.com/arkenfox/user.js/releases.atom if you want to know when a release is done
Use https://github.com/arkenfox/user.js/commits/master.atom if you want to know when any commit is done

BTW, I opened my test ESR60 (cuz it supports feeds), and here's what I got (commits feed)

![meh](https://user-images.githubusercontent.com/16656956/167543030-ec6cc0e7-d01c-4dc1-bec2-b20c01b727b2.png)

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain#-rss-feeds

**Comment by GlassGruber** [comment]
Interesting! Sorry for bumping what are you using to read the RSS inside of FF? 
Wasn't it [removed ](https://support.mozilla.org/en-US/kb/feed-reader-replacements-firefox)time ago? Or is that an older FF version?

**Comment by EdwardLangdon** [comment]
It is a Older Firefox Version. FF ESR 60. Thorin mentioned that.

**Comment by GlassGruber** [comment]
>BTW, I opened my test ESR60 (cuz it supports feeds), and here's what I got (commits feed)

I can't believe I've missed that, like really right above that screenshot. 
Thank you @EdwardLangdon for not bashing the crap out of me like I deserve x)  🤡 🔨
