### ISSUE TITLE
Cross-site cookies still allowed despite ETP

### ISSUE THREAD

**Issue by ghost** [arkenfox/user.js#1449]
Hi,
I started using Arkenfox a while back with a new profile, so a clean slate in terms of permissions. I have made overrides, but nothing relating to cookies. Given this, I assume my browser's behaviour regarding cookies directly derives from the user.js.
As expected, Enhanced Tracking Protection is set to strict, which should block all cross-site cookies. 
Despite this, I noticed that, on some websites, some cross-site cookies are actually approved -- with permissions that I clearly did not give. For instance, duckduckgo.com authorises cross-site cookies for support.apple.com (see attached image). In some cases, the "third party" website indicated in the permission window is the same as the website I'm on -- which means it should not be considered cross-site, and yet it is labelled as such.
Is this normal? Am I missing something?
Dan

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 101 (beta), macos 12
  - Steps to Reproduce (STR): go to duckduckgo.com (also applicable to other specific websites, such as github), click on the "permissions" icon left of the URL
  - Expected result: cross-site cookies should never be allowed
  - Actual result: in specific websites, cross-site cookies are allowed
  - Console errors and warnings: nothing relevant, as far as I can see
  - Anything else you deem worth mentioning: nope

---
<img width="818" alt="Schermata 2022-05-17 alle 13 42 51" src="https://user-images.githubusercontent.com/99121334/168804665-c4b31711-5175-49f7-9879-4febbce30972.png">

**Comment by WeirDan76** [comment]
Well spotted, @EdwardLangdon. So the conclusion is..... deny/revoke access manually until changes are made in FF102 (as per @Thorin-Oakenpants comments in #1441)?

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/ea139e3ef8810149d90df8637984f2444282745e/user.js#L773-L779

**Comment by EdwardLangdon** [comment]
I am still not yet clear about the Discussion, need to look later. Rusty snake, Can you explain ?

**Comment by rusty-snake** [comment]
Everything is working as intended.

Webcompat is enabled by default because pants want this/less breakage for users/less unnecessary reports about broken sites.

**Comment by WeirDan76** [comment]
No sure I'm well versed enough. But what would it take for these cross-site permissions to be requested instead of just accepted (in the cases where they are accepted)?

**Comment by rusty-snake** [comment]
If you want an request dialog like for geolocation, you need to open an ticket in mozillas bugtracker.

**Comment by privacyguy123** [comment]
> Everything is working as intended.
> 
> Webcompat is enabled by default because pants want this/less breakage for users/less unnecessary reports about broken sites.

So far all of these websites are working as intended with this optin off - begs the question what is it "fixing" by allowing cross site cookies by default?

**Comment by Thorin-Oakenpants** [comment]
> Duplicate of #1448

Not a duplicate if user hasn't added a site exception for ETP or sanitizing

> deny/revoke access manually until changes are made in FF102

- what 102 change? If you mean when we move off lifetime cookie pref, that has nothing to do with this or 1448
- revoking manually means you're just undoing your exceptions (if you added one, e.g. 1448)

My understanding was that nothing is allowed unless user initiated. And we allow compat because without it you can't use the d in dFPI or benefit from the shims

> includes skip lists, heuristics (SmartBlock) and automatic grants

I did try, from memory to work out what automatic grants were, IDK, so much F shit for me to always answer and read ands learn about

**Comment by WeirDan76** [comment]
Indeed, no exceptions had been made for the websites where these cross-site cookies are found to be allowed. 

From a link in the discussion of #1448, I see the following (taken from FF Help website):

> While cross-site cookies from trackers are blocked in Firefox by default, a site may signal to the browser that it needs to use them for important functionality. In this case, Firefox will allow a third-party website to use cross-site cookies the first five times (or up to 1% of the number of unique sites you visit in a session, whichever is larger) without prompting you. 

If I get this right, then this whole thing is not a bug, but just the very design of dFPI and there isn't much one can do, apart from ditching dFPI entirely. Is that right? 

I guess it just feels like the heuristics work in mysterious ways, as I remain quite unsure as to how/why Duckduckgo needs to connect to Apple support for an important functionality...

**Comment by fxbrit** [comment]
> how/why Duckduckgo needs to connect to Apple support for an important functionality...

for the record I couldn't reproduce this, even uBO shows no Apple script or anything.

**Comment by Lostname777** [comment]
This thing even happens when I use starpage Anonymous view (sometimes)

**Comment by ElectricityMachine** [comment]
Just wanted to confirm this as well, it's happened to me, albeit with a different website. I have a cookie exception for DuckDuckGo for settings, but it _still happens_ when I remove the exception, save changes, and restart. I confirmed that cookies were removed since the theme went from dark to light in DDG. I don't really know how to reproduce this reliably, but will try in another profile.

Before removing exception:
![37scjejU53](https://user-images.githubusercontent.com/47489506/171546836-5499f4bc-5640-4f69-bfe2-ec3ab4f7b863.png)

After removing exception:
![sZdKnRl8OD](https://user-images.githubusercontent.com/47489506/171546847-2dfd8d88-6dfd-4d58-9817-98bfb6f26540.png)

**Comment by Thorin-Oakenpants** [comment]
> I have a cookie exception for DuckDuckGo

so duplicate of #1448 

Here's my FF with no cookie exception
![trackers](https://user-images.githubusercontent.com/16656956/176810558-8c5d37df-8346-4666-9be8-ef7d95caa242.png)

**Comment by remyabel2** [comment]
FWIW I run into this issue even though I **don't** have a cookie exception for duckduckgo. The sites listed seem to be sites I have visited from search results and it doesn't happen consistently, I notice it randomly and have to clear the permissions everytime.

**Comment by remyabel2** [comment]
![Screenshot from 2022-08-11 14-41-26](https://user-images.githubusercontent.com/94518122/184215474-83be29ea-6e2f-4d2e-aa9e-3138b5f67d1f.png)

Here is an example after I visited a reddit domain. I don't have cookie exceptions for either.

**Comment by rusty-snake** [comment]
I can not reproduce this yet with my config, but I did saw it on other devices.
Where does the "Learn more" link brings you? What does it talk about?

To remember you call, there is [Opener Heuristics](https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning#opener_heuristics).

If you click on the `a` tag, it is a link

![Bildschirmfoto vom 2022-08-11 20-48-39-fs8](https://user-images.githubusercontent.com/41237666/184216438-d43ae5bb-1de0-417a-a1db-64dd2b4be8e1.png)

but if you click on the `article` tag the "link" is implemented via `onclick` possible using some API that triggers Opener Heuristics under some conditions (IDK which but FF sometimes shows a blocked pop-up banner on DDG when clicking on search results, maybe these are the same. Maybe timing?)

![Bildschirmfoto vom 2022-08-11 20-47-43-fs8](https://user-images.githubusercontent.com/41237666/184216314-cc8baa69-b699-4c68-b34d-d584dc4f3898.png)

**Comment by rusty-snake** [comment]
Here, it's documented: https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning#clear_third-party_storage-access

**Comment by remyabel2** [comment]
> I can not reproduce this yet with my config, but I did saw it on other devices.

I don't have any overrides regarding cookies/storage/webcompat so no idea why some people can reproduce it and others can't.

> Where does the "Learn more" link brings you? What does it talk about?

Yes I linked to it here: https://github.com/arkenfox/user.js/issues/1448#issuecomment-1128321126 The reason why it's confusing is because there's theoretically no reason why DDG would need those permissions, especially without exceptions.

> but if you click on the article tag the "link" is implemented via onclick possible using some API that triggers Opener Heuristics under some conditions (IDK which but FF sometimes shows a blocked pop-up banner on DDG when clicking on search results, maybe these are the same. Maybe timing?)

This is good information. I can only reproduce it on DDG as far as I can tell, so I have no doubt that they are doing something weird. Their privacy policy does mention using local storage and tracking clicks for anonymous analytic purposes, so that may have something to do with it. It may be possible to confirm this by browsing their HTML version of the site for a while and seeing if the problem persists.

**Comment by rusty-snake** [comment]
> The reason why it's confusing is because there's theoretically no reason why DDG would need those permissions, especially without exceptions.

How should Firefox know this? It uses a *heuristic*.

> A heuristic … is any approach to problem solving … that employs a practical method that is not guaranteed to be optimal, perfect, or rational, but is nevertheless sufficient for reaching an immediate, short-term goal or approximation. Where finding an optimal solution is impossible or impractical, heuristic methods can be used to speed up the process of finding a satisfactory solution.

It does not understand what the code does or need, it just detects patterns which indicated that it might need this permissions.

>  I can only reproduce it on DDG as far as I can tell,

I also saw it on other sites but can't remember which. However, if DDG is your primary search engine you use it a lot and open a lot third-party links from it, so it is expected to see it there more often.

Also it may depend on the code of the site you open? IDK.
If someone wants to look in the implementation of the heuristic, go for it...

**Comment by rusty-snake** [comment]
Found some STR:

- search for anything in DDG, e.g. arkenfox
- hold ctrl and primary click on the `article` (not `a`, see https://github.com/arkenfox/user.js/issues/1449#issuecomment-1212371361)

And in deed it's Opener Heuristics (turning it off breaks this STR).

**Comment by rusty-snake** [comment]
Broken SSO-Login for some services and other potential cross site authentification  problems.
