### ISSUE TITLE
[Question] How do I know if I applied ArkenFox Correctly?

### ISSUE THREAD

**Issue by Ryu945** [arkenfox/user.js#1451]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 100.0.1 on Fedora XFCE

---
Once I follow the steps to apply Arkenfox with the user.js folder, how do I know if the browser has successfully applied the changes?

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/d6b26e75588bcd4311251c68912d3c77b8c6e996/user.js#L1368

**Comment by Thorin-Oakenpants** [comment]
be aware that not all syntax errors cause failure - see https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-check
