### ISSUE TITLE
Firefox portable with Arkenfox user.js does not save update setting on restart

### ISSUE THREAD

**Issue by zerovvon** [arkenfox/user.js#1452]
Hi,

I am using Firefox Portable from PortableApps.com.

Without Arkenfox user.js, the "Firefox portable with Arkenfox user.js does not save update setting on restart" setting persists when the browser restarts.

With Arkenfox user.js, the "Firefox portable with Arkenfox user.js does not save update setting on restart" setting does not persist when the browser restarts.

**Comment by Thorin-Oakenpants** [comment]
what update setting?

**Comment by Thorin-Oakenpants** [comment]
also, doubly invalid, read this again .. emphasis mine

> **_Without Arkenfox user.js_**, the "Firefox portable **_with Arkenfox user.js_** does not save update setting on restart" setting persists when the browser restarts.
> 
> **_With Arkenfox user.js_**, the "Firefox portable **_with Arkenfox user.js_** does not save update setting on restart" setting does not persist when the browser restarts.
