### ISSUE TITLE
User JS

### ISSUE THREAD

**Issue by anpace** [arkenfox/user.js#1453]
Hello,

I'm texting you because I'm a little bit confused about user.js usage.
I can't understand firts off all if I need to create a new profile or just I need to copy user.js into Profile:default-release.
If i create a new Profile for example "Profile: Arkenfox", need I copy all the files who are in user.js-master in "Arkenfox" or simply user.js?
If is just about copying user.js, is the same both for windows and mac or there are different ways to use it?

Thank you very much
Anpace

**Comment by fxbrit** [comment]
https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain#-apply

follow the above guide, it answers all of your questions. also there's nothing specific about macOS in this case, so it's all the same.

**Comment by anpace** [comment]
@fxbrit 
I created a new Profile, I copied the files listed on the page you sent me in it (prefsCleaner.sh, prefsCleaner.bat, updater.sh, updater.bat and user.js)
Now, adress bar is not connecting to any website  whitout www......com, if I search for example adobe,  i'm running against this massage:  we can't connect to the server.

**Comment by fxbrit** [comment]
see https://github.com/arkenfox/user.js/blob/master/user.js#L322-L328

**Comment by rusty-snake** [comment]
and https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-common

**Comment by anpace** [comment]
Ok, maybe I found the problem. I'm in about:config, I changed keyword.enabled to true, but nothing changed

**Comment by fxbrit** [comment]
please read the Wiki, all the questions you're asking are covered.

**Comment by Thorin-Oakenpants** [comment]
![readthewiki](https://user-images.githubusercontent.com/16656956/170463810-ce99afc3-0d2b-47fc-a2c7-183b594deb9b.jpg)
