### ISSUE TITLE
"SUCCESS! USER-OVERRIDES SETTINGS LOADED"

### ISSUE THREAD

**Issue by anpace** [arkenfox/user.js#1454]
Let me ask you a little thing,
I used user-overrides.js in a new Profile, I changed keyword.enabled true and I run update.sh.
Everything seems working pretty well, but parrot, is giving me always SUCCESS: No no he's not dead, he's, he's restin'! message.
As far as I understood should be "SUCCESS! USER-OVERRIDES SETTINGS LOADED"?
If is so, why keyword.enabled is changed on true through user-overrides.js if is not loading?

**Comment by rusty-snake** [comment]
Does you user-override.js set a parrot?

**Comment by rusty-snake** [comment]
>  As far as I understood should be "SUCCESS! USER-OVERRIDES SETTINGS LOADED"?

IDK why I think so but I could not find the string `USER-OVERRIDES SETTINGS LOADED` in the wiki. Where is this stated?

**Comment by anpace** [comment]
In my user-overrides,js I just set one parameter:

// my overrides
user_pref("keyboard.enabled", true);

**Comment by rusty-snake** [comment]
And how should this set `_user.js.parrot`?!

READ THE WIKI! Everything you ask is answered there. Invalid.

https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting

**Comment by anpace** [comment]
I don't speak english very well, maybe I explained myself bad.

I created a new profile named Arkenfox. I copied 3 files inside: 
prefsCleaner.sh
updater.sh
user.js

Then i created user-override.js and I set one parameter:
// my overrides
user_pref("keyboard.enabled", true);

Now I run update.sh and everything seems working pretty well: if I search for a single word in adress bar, is working!

I go to about:config and search for _user.js.parrot who is giving me SUCCESS: No no he's not dead, he's, he's restin'!
As far as I understood should be "SUCCESS! USER-OVERRIDES SETTINGS LOADED" is correct?

If is so, why keyword.enabled is changed on true through user-overrides.js if user-overrides.js is not loading?

**Comment by GhoulBoii** [comment]
The parrot config showing "SUCCESS: No no he's not dead, he's, he's restin'!" shows that the user.js is working. Where did you see that the parrot show show the "SUCCESS! USER-OVERRIDES SETTINGS LOADED" ?

**Comment by rusty-snake** [comment]
>  As far as I understood should be "SUCCESS! USER-OVERRIDES SETTINGS LOADED" is correct?

1. If you do not set it, how should it have this value?
2. Why do you think it should have this value? From where did you got this impression?
3. READ THE WIKI!

**Comment by Thorin-Oakenpants** [comment]
READ THE WIKI. If you can't understand it, then arkenfox is not for you
