### ISSUE TITLE
After restarting, the Firefox update setting is reset

### ISSUE THREAD

**Issue by zerovvon** [arkenfox/user.js#1456]
Hi,

Portable Firefox (PortableApps.com) with user.js does not save update setting "Check for updates but let you choose to install them" when browser is restarted.

  - Browser version & OS: 100.0.2; Windows 10
  - Steps to Reproduce (STR): Install Portable Firefox and move user.js to the profile folder. After launching in the Settings-Firefox Updates set up "Check for updates but let you choose to install them" and restart the browser
  - Expected result: The setting is retained after a restart
  - Actual result: The setting is not save

**Comment by Thorin-Oakenpants** [comment]
First AF does not set this, second the pref is limited to NON-WINDOWS and you are using windows, third, please learn how to follow instructions (you didn't say what value you were changing it to, what pref(s) you tried to override or if you did override anything .. etc

https://github.com/arkenfox/user.js/blob/ea139e3ef8810149d90df8637984f2444282745e/user.js#L1278-L1280
