### ISSUE TITLE
Restore opened Tabs after closing browser, but also erasing browser history.

### ISSUE THREAD

**Issue by BwntyHntr** [arkenfox/user.js#1459]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ * ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 
  - Steps to Reproduce (STR): Have tabs open and close the browser.
  - Expected result: Have the tabs restored with the browser history erased.
  - Actual result: Tabs and history erased.
  - Console errors and warnings: None.
  - Anything else you deem worth mentioning:

I have added these as instructed:
```js
user_pref("browser.startup.page", 3); // 0102
  // user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  // user_pref("places.history.enabled", true); // 0862 required if you had it set as false
user_pref("browser.sessionstore.privacy_level", 0); // 1003 [to restore cookies/formdata if not sanitized]
  // user_pref("network.cookie.lifetimePolicy", 0); // 2801 [DON'T: add cookie + site data exceptions instead]
user_pref("privacy.clearOnShutdown.history", false); // 2811
  // user_pref("privacy.clearOnShutdown.cookies", false); // 2811 optional: default false arkenfox v94
  // user_pref("privacy.clearOnShutdown.formdata", false); // 2811 optional
user_pref("privacy.cpd.history", false); // 2812 to match when you use Ctrl-Shift-Del
  // user_pref("privacy.cpd.cookies", false); // 2812 optional: default false arkenfox v94
  // user_pref("privacy.cpd.formdata", false); // 2812 optional
```
  
However, this makes both the tabs and the history to not be erased on close, I was wondering if we could keep the tabs, but have the history erased only.

---

**Comment by Thorin-Oakenpants** [comment]
I assume you are not using PB Windows mode. I assume we are also not concerned here with retaining logins. So if we simplify this, you made these changes

````js
user_pref("browser.startup.page", 3); // 0102
user_pref("browser.sessionstore.privacy_level", 0); // 1003 [to restore cookies/formdata if not sanitized]
user_pref("privacy.clearOnShutdown.history", false); // 2811
user_pref("privacy.cpd.history", false); // 2812 to match when you use Ctrl-Shift-Del
```

the `privacy_level` is optional and has nothing to do with whether or not you use SR (session restore)
the `cpd` pref is for manual sanitizing and optional I guess
the `startup` pref is essential for SR, it's the pref that says "hey enabled SR"

that leave one pref for you to test. Why don't you test it?

**Comment by BwntyHntr** [comment]
If I add these in the override:
`user_pref("browser.startup.page", 3); // 0102`
`user_pref("privacy.clearOnShutdown.history", false); // 2811`

Then both the browser history and the tabs are restored on closing, I want the tabs to be restored but the history to be erased, is that possible?

**Comment by rusty-snake** [comment]
> Then both the browser history and the tabs are restored on closing, I want the tabs to be restored but the history to be erased, is that possible?

No, if you set `privacy.clearOnShutdown.history=true` SR does not work. What does work however is disabling history (`5013`) and SR.

https://github.com/arkenfox/user.js/blob/662eddbc2124d9d09774da7d5bc385f45c287c0d/user.js#L1025-L1028

**Comment by Thorin-Oakenpants** [comment]
> No, if you set `privacy.clearOnShutdown.history=true` SR does not work.

thank you Rusty for doing what was asked. You had one job, one pref .... _sigh_

> What does work however is disabling history (5013) 

not sure what the trailing ` and SR` means. So there you go, thanks Rusty, a solution: you will not have any history during your sessions, and no history can be restored, and you do not need to sanitize history on close (and thus it won't nuke SR - IDK why clearing history on shutdown (or manually?) nukes SR, it just how everything was engineered from way back in the Before Times)

**Comment by BwntyHntr** [comment]
Thank you @rusty-snake that did the trick, now there is just no history produced at all.

At first, I wanted to have the history while I browsed, but now that the history is not even registered, I like it this way better.
