### ISSUE TITLE
The user js is being recognized as a trojan.

### ISSUE THREAD

**Issue by joao1025** [arkenfox/user.js#1460]
When I check the user js file on www.virustotal.com it is showing as a trojan according to microsoft?

**Comment by silverwings15** [comment]
man it's literally a text file, open it in sublime or notepad++ and see. there is no no need to be this paranoid when you're so tech illiterate

**Comment by Thorin-Oakenpants** [comment]
if you got the file from here, and unmodified, it's a false positive

**Comment by Thorin-Oakenpants** [comment]
I uploaded the current master user.js - seems it was first checked 24 days ago and currently shows ZERO security vendors and ZERO sandboxes have flagged this file as malicious

So this claim is invalid, not a false positive

![nope](https://user-images.githubusercontent.com/16656956/171832305-2bf399d7-a5ce-42a1-8a47-30adb4c1f220.png)
