### ISSUE TITLE
follow instructions or this will be closed as invalid

### ISSUE THREAD

**Issue by crimsonpython24** [arkenfox/user.js#1462]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [v] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: FF 101.0, Monterey 12.5 Beta
  - Steps to Reproduce (STR): 1. quit firefox; 2. drag & drop the `user.js` file into the profile directory; 3. re-open firefox
  - Expected result: the screen should fit
  - Actual result: there are black/grey borders around the window
  - Console errors and warnings: No
  - Anything else you deem worth mentioning: I guess it is to prevent the actual screen size from being recorded? But I am a bit bothered by them and will like to know if there is any settings in the `user.js` file that I can do to get rid of the edges. The issue isn't prevalent without `user.js`.

The border is like this:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/76871022/172054285-b8327475-41b5-41e4-a0b8-d8591578767b.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/76871022/172054293-bd46b2bb-8c67-4005-a171-aa71a13f0742.png">

---

**Comment by rusty-snake** [comment]
This is expected. Is' RFP letterboxing.

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-fingerprinting

>  is the pref that creates borders around your webpages

**Comment by rusty-snake** [comment]
Check this `[SETUP-` tag

https://github.com/arkenfox/user.js/blob/662eddbc2124d9d09774da7d5bc385f45c287c0d/user.js#L922-L931

**Comment by crimsonpython24** [comment]
Thank you, the issue is resolved now.

One last thing: what's the consequence of setting line 931 to false?

**Comment by rusty-snake** [comment]
If you do not resize (includes maximize and tiling-wm) none. If you do, websites can detect the actual (inner) window size instead of the (inner) window size with precision of 100. (Pants can explain this better).

**Comment by Thorin-Oakenpants** [comment]
if you can't live with letterboxing, disable it

Anti-fingerprinting on Firefox is more or less restricted to blocking known scripts (uBlock Origin and Enhanced Tracking Protection) and fooling naive scripts (which RFP does). Letterboxing is not tied to RFP, so feel free to override it . I know that the letterbox margins can be extremely outputting (initially, but you can used to them). You should be starting up in a usable window (what you deem usable will depend on you), we set 1600x900 as the max size), and if you don't go full-screen or maximize or drag bigger then you're all set (or should be). But the web needs to be usable for you - if you want bigger, then be bigger and if letterboxing annoys you, then turn it off
