### ISSUE TITLE
resist RFP false in user-overrides ignored

### ISSUE THREAD

**Issue by privacyguy123** [arkenfox/user.js#1463]
![image](https://user-images.githubusercontent.com/50337995/172211726-825a882a-6223-40cc-96cb-c5168e1cd39c.png)

Can't understand why it's the only option not sticking.

**Comment by privacyguy123** [comment]
had to delete user.js and re run updater - fixed.

**Comment by rusty-snake** [comment]
Duplicate of #1359.

**Comment by Thorin-Oakenpants** [comment]
the forth to last pref is missing an ending `;`
