### ISSUE TITLE
Firefox user.js not working as intended

### ISSUE THREAD

**Issue by crimsonpython24** [arkenfox/user.js#1464]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [v] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: FF 101.0, Mac OS 12.5 Beta
  - Steps to Reproduce (STR): 
    - 1. re-install firefox fresh
    - 2. open the profiles folder
    - 3. download `user.js`, `updater.sh`, and `prefsCleaner.sh` and drag them into the profiles folder
    - 4. start Firefox browser
    - 5. quit Firefox
    - 6. create a `user-overrides.js` in the same profile folder
    - 7. run `updater.sh` and `prefsCleaner.sh`
    - 8. open Firefox again
  - Expected result: after step (d), Arkenfox tweaks should be applied; after step (h), my own overrides should appear
  - Actual result: Arkenfox worked after step (d), but nothing worked after step (h) (neither my tweaks nor Arkenfox tweaks are applied to firefox)
  - Console errors and warnings: None
  - Anything else you deem worth mentioning: How I tested this is to go online and look for browser user agent finders. After step (d), they show that I'm on a Windows NT, which is spoofed; after step (h), the websites can accurate reflect that I'm on a Mac

---

**Comment by rusty-snake** [comment]
> neither my tweaks nor Arkenfox tweaks are applied to firefox

You did not said you deleted prefs.js (or anything equivalent) which means your testing must be wrong or your overrides reset every arkenfox-user.js pref.

**Comment by Thorin-Oakenpants** [comment]
> Arkenfox worked after step (d)

so the user.js is being applied

> but nothing worked after step (h) (neither my tweaks nor Arkenfox tweaks are applied to firefox)

That cannot be true, because on a restart, point d is reached again. Even if you overrode every single arkenfox pref, they would still show as modified

> How I tested this

You test it by checking values are changed in about:config

> step g

step g part 2 - open the user.js and check your overrides were added to the end

**Comment by Thorin-Oakenpants** [comment]
> After step (d), they show that I'm on a Windows NT, which is spoofed; after step (h), the websites can accurate reflect that I'm on a Mac

What website? JS OS is not spoofed (except the OS version). Don't bother answering. This is not how you check prefs were changed.

You can also open prefs.js, even while FF is running, just don't edit it, and see all the prefs added

Also, make sure your `user-overrides.js` is a js file and not a `user-overrides.js.txt` text file or something silly

do step g part 2

closing as invalid. We know this all works. You're doing something wrong or misunderstanding what is being applied
