### ISSUE TITLE
user_pref "browser.startup.homepage_override" is required to change homepage

### ISSUE THREAD

**Issue by rio-codes** [arkenfox/user.js#1465]
The comments in the default user.js file, sections 0103 and 0104, suggest that only ```browser.startup.page``` and ```browser.startup.homepage``` are required to set a default homepage. I discovered that I actually needed to add:
```
user_pref("browser.startup.homepage_override", "https://example.com")
```
to restore my preferred homepage. This pref does not appear anywhere else in user.js. In section 9000 it mentions
```
user_pref("browser.startup.homepage_override.mstone", "ignore"); // master switch
   // user_pref("startup.homepage_welcome_url", "");
   // user_pref("startup.homepage_welcome_url.additional", "");
   // user_pref("startup.homepage_override_url", ""); // What's New page after updates
```
but none of these actually change the homepage.

To reproduce the issue, I changed user-overrides.js to this:
```
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", "https://example.com");
```
and ran updater.sh. The homepage was still blank.

Then I changed the user-overrides.js to 
```
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", "https://example.com");
user_pref("browser.startup.homepage_override", "https://example.com")
```
ran updater.sh, and the homepage changed.

**Comment by Thorin-Oakenpants** [comment]
new profile
- copy prefs.js as prefs-old
- go to settings>home> change start page to `https://arkenfox.github.io/TZP/index.html`
- copy prefs.js as prefs-new
- compare the two
- the only difference (besides some cosmetic of timestamps things) is `browser.startup.homepage`
- restart and watch the startpage load the website

reset the profile
- load with a blank page or whatever
- add a user.js with one line in it
- `user_pref("browser.startup.homepage", "https://arkenfox.github.io/TZP/index.html");`
- restart, watch the startpage load the website
