### ISSUE TITLE
mac/linux font testers (windows users feel free to join in)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1468]
so for a while now, fxbrit tells me, that the TZP font test can be unstable on the first run (when the page loads - in a new session), but not always. Of course I don't have a mac and cannot replicate on windows (because the TZP test doesn't fire the font test for about 200ms)

So I built a test - https://arkenfox.github.io/TZP/tests/fontstability.html - which loads fast as F and runs the first test as soon as possible

You should run this with RFP off, and IDCare about TB, just use Firefox, so we cover the most fonts. The list is the same regardless: I just merged all the various lists per OS and de-duped and sorted

You should run this on a COLD APP START - i.e firefox is closed, open it, do test - I don't mean reboot your machine or anything.

Here is my windows on a cold app load: i.e open app, sanitized cache etc (I don't think sanitizing matters), and the very first site loaded is the test, which auto runs the first test - than manually re-run until stable
- I had to be quick. open FF, paste url, hit enter, as fast as I could

![stability](https://user-images.githubusercontent.com/16656956/173070320-ce065de7-9b14-4c27-97f3-50690d8b7929.png)

This is surprising, and hints at some sort of lazy/async loading per Firefox session. Maybe a bit like the fallback char mapping where it renders as tofu and catches up later

The diffs are from the previous result, and are split into new (in the new result) and missing (in the new result)

So what I would like is for mac, windows, linux users to see if they can catch instability, and to report the list of font DIFFS from the console - I don't want to know the fonts found, just DIFFS if any. First it helps if I know what platforms instability happens, and the fonts may give me a clue too

I doubt windows users will get anything unless they have a few additional optional fonts from MS Office, or on Win7, but we'll see.

TIA

**Comment by EdwardLangdon** [comment]
This is what I got with RFP turned on.

![image](https://user-images.githubusercontent.com/101938856/173170287-fba389b5-9b35-42f9-928f-2962544d41b3.png)

My Console Errors

![image](https://user-images.githubusercontent.com/101938856/173170320-c494ec3b-d1da-4fcb-a86e-43ce834b6a2c.png)

With RFP off, I get a `GET` Error for https://arkenfox.github.io/favicon.io. That's it.

I will check again though.

I am windows, btw

**Comment by Thorin-Oakenpants** [comment]
I only need to know if you got instability, and only the font names from the console. Also RFP off. Minimizing your post to clear clutter. Thanks for testing though 👍 but I doubt windows 10+ will produce anything (gut feeling)

**Comment by EdwardLangdon** [comment]
What kind of instability are you asking about ?

**Comment by rusty-snake** [comment]
Fedora Linux; New profile: stable from first run on.

**Comment by 2glops** [comment]
Debian Buster : no instability, stable from first run
FF101.0.1 RFP off

**Comment by fxbrit** [comment]
also re-posting my results in here, osx and FF 101.0.1. setting the test as my homepage gave me 100% hit with always the same hash across 25 tests:
```
RUN2 1 fb17aaf5

"new:Avenir Black, Avenir Black Oblique, Avenir Book, Avenir Heavy, Avenir Light, Avenir Medium, Avenir Next Condensed Demi Bold, Avenir Next Condensed Heavy, Avenir Next Condensed Medium, Avenir Next Condensed Ultra Light, Avenir Next Demi Bold, Avenir Next Heavy, Avenir Next Medium, Avenir Next Ultra Light, Charter Black, Hiragino Kaku Gothic Pro W3, Hiragino Kaku Gothic Pro W6, Hiragino Kaku Gothic ProN W3, Hiragino Kaku Gothic ProN W6, Hiragino Kaku Gothic Std W8, Hiragino Kaku Gothic StdN W8, Hiragino Maru Gothic Pro W4, Hiragino Maru Gothic ProN W4, Hiragino Mincho Pro W3, Hiragino Mincho Pro W6, Hiragino Mincho ProN W3, Hiragino Mincho ProN W6, Hiragino Sans GB W3, Hiragino Sans GB W6, Hiragino Sans W0, Hiragino Sans W1, Hiragino Sans W2, Hiragino Sans W3, Hiragino Sans W4, Hiragino Sans W5, Hiragino Sans W6, Hiragino Sans W7, Hiragino Sans W8, Hiragino Sans W9, Hoefler Text Ornaments, Iowan Old Style Black",
```

![1](https://user-images.githubusercontent.com/34379516/173243233-b02b4971-32ab-47e0-95a9-5ede56e37a7b.png)

**Comment by Thorin-Oakenpants** [comment]
the FF90 `omt` pref flip will be interesting

**Comment by Thorin-Oakenpants** [comment]
hey 🐟 ... how hard is it to test FF89 and then FF90 on your system (default, no pref changes)?Asking for a fiend (not a typo)

**Comment by fxbrit** [comment]
sure, give me a few hours and I will update this post with the results.
