### ISSUE TITLE
windows Tor Browser testers please

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1469]
We (Tor Browser, no I do not work for them) would like to know what scripts (languages) aren't supported across Windows versions: i.e 7 v 8.1 vs 10 vs 11 - in order to get all versions up to date with the same support and fonts

Back story: TB uses a font whitelist. It added some fonts that every Windows user would have to cover as many scripts as possible, and then it also bundles and whitelists some extra fonts for scripts such as Khmer etc

But that was a long time ago, and what is shipped by default (i.e not optional or additional or supplemental Microsoft system fonts) has changed. For example, the font whitelisted for Ethiopic is `Nyala`, and the font whitelisted for Bengali is `Vrinda` - but both of these were dropped in Windows 10

default font lists are here
- e.g. Windows 10: https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list

STR
- open Tor Browser
- go to https://arkenfox.github.io/TZP/tests/fontscripts.html
- click `[ run ]`
- from the summary on the right hand side, copy the list of unsupported scripts
- report back with your windows version (major version, e.g. 7, 8.1, 10, 11)

I really only need one of each, but feel free to test and report back if anything is different (you may have downloaded supplemental fonts)

for example, here is windows 7
```
unsupported [41]

adlam
balinese
bamum
bassa vah
braille patterns
buhid
cjk compatibility ideographs supplement [18/20]
cjk unified ideographs extension-b [19/20]
control pictures
cyrillic extended-a
cyrillic extended-b [18/20]
cyrillic extended-c
deseret
georgian
georgian extended
georgian supplement
glagolitic
gothic
hanunoo
javanese
mandaic
mongolian
new tai lue
nko
ogham [19/20]
old italic
old turkic
optical character recognition [10/11]
osage
osmanya
phags-pa
runic
samaritan
sundanese
syriac
tagalog
tagbanwa
tai le
tamil supplement
tifinagh
vai
```

**Comment by g-2-s** [comment]
Windows 10 IoT Enterprise LTSC
Tor Browser 11.0.14

```
unsupported [48]

adlam
balinese
bamum
bassa vah
bengali
braille patterns
buhid
cherokee
cjk compatibility ideographs supplement [18/20]
cjk unified ideographs extension-b [19/20]
control pictures
cyrillic extended-c
deseret
devanagari
ethiopic
ethiopic supplement
glagolitic
gothic
gujarati
gurmukhi
hanunoo
javanese
kannada
malayalam
mandaic
new tai lue
ogham [19/20]
old italic
old turkic
optical character recognition
oriya
osage
osmanya
phags-pa
runic
samaritan
sinhala
sundanese
syriac
tagalog
tagbanwa
tai le
tamil
tamil supplement
telugu
tifinagh
unified canadian aboriginal syllabics
vai
```

**Comment by Thorin-Oakenpants** [comment]
thanks, win10 being to similar to win11 - plus with Microsoft documentation - I have what we need. Thanks @g-2-s
