### ISSUE TITLE
Skip Redirect vs ClearUrls?

### ISSUE THREAD

**Issue by Irvinehimself** [arkenfox/user.js#1470]
Ediited: copied [Smart Referer](https://addons.mozilla.org/firefox/addon/smart-referer/) from wiki instead of [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/)

Is there  any particular reason the Wiki [recommends](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-recommended=) the extension [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/) over, for example, [ClearUrls](https://addons.mozilla.org/en-GB/firefox/addon/clearurls/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured)?

- I find the latter works better with [Multi-Account Containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/). See [this issue](https://github.com/mozilla/multi-account-containers/issues/2372).
- Also,  the reason I found it is because it has a logger which I am hoping will help debug problem redirects.

In addition, `ClearUrls` is badged as [Recommended by Firefox](https://support.mozilla.org/en-US/kb/recommendations-firefox):
>**How are features and extensions selected?**
>.... selected by Mozilla’s product and editorial teams based upon functionality, **user experience**, and **security**....

What with: _Moving from [NoScript](https://addons.mozilla.org/en-GB/firefox/addon/noscript/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and [Adblock Plus](https://addons.mozilla.org/en-GB/firefox/addon/adblock-plus/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) to [uBlock Origin](https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search); implementing Firefox containers; implementing Arkenfox  user.js and digesting your Wiki._ I am solving issues as I go, so if I have missed something I apologise in advance.

By the way, I really like your project and I love your Wiki :+1:

**Comment by rusty-snake** [comment]
> Smart Referer vs ClearUrls

Pineapple vs. Potato.

**Comment by Irvinehimself** [comment]
Sorry, copied [Smart Referer](https://addons.mozilla.org/firefox/addon/smart-referer/)  from the Wiki instead of [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/)

I can't see any way to change the title?

**Comment by rusty-snake** [comment]
> I can't see any way to change the title?

The "edit" button at the right of it.
