### ISSUE TITLE
Fission and gfx.webrender.all

### ISSUE THREAD

**Issue by 128bitpotato** [arkenfox/user.js#1472]
I set up Arkenfox a couple of weeks ago. While reading up a bit on fission for Firefox a question aroser:

In the [Firefox wiki](https://wiki.mozilla.org/Project_Fission) they state that you need to set both **fission.autostart** and **gfx.webrender.all** to **True** to activate Fission. In my browser fission is activated, but not webrender. I find no setting in user.js for neither, is there a reason for this? My guess is fission is activated by default. But should I activate webrender, or will it in some way compromise security or privacy?

Thanks for any help!

**Comment by Thorin-Oakenpants** [comment]
also see #1208 

fission is enabled by default - https://arewefissionyet.com/
webrender is enabled by default - https://arewewebrenderyet.com/

There is nothing for arkenfox to do, never was

**Comment by Thorin-Oakenpants** [comment]
> In my browser fission is activated, but not webrender

Assuming your are not on ESR... IDK why webrender is not enabled for you. There may be some graphics cards whatever that are edge case blockers - you will have to check with Mozilla support. It might even say something in `about:support`
