### ISSUE TITLE
remove 0803: browser.urlbar.trimURLs ?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1473]
https://searchfox.org/mozilla-central/source/browser/components/urlbar/UrlbarResult.jsm#241

Is it just me, or does 0803 not do anything
```js
/* 0803: display all parts of the url in the location bar ***/
user_pref("browser.urlbar.trimURLs", false);
```

I've even tested FF60, seems to do jack shit

**Comment by rusty-snake** [comment]
WFM.

> **Note**: You need a http site to test this. (e.g. http://neverssl.de/)

**Comment by Thorin-Oakenpants** [comment]
right, it's only for HTTP: so here's ESR91

![tests](https://user-images.githubusercontent.com/16656956/173232924-a90330fb-ff11-41e2-97e6-3cb4aac1eb84.png)

notes
- it doesn't seem to affect `www` at all?
- when it hides `http://` clicking into the urlbar doesn't expand to the untrimmed url (I thought it did in the past?, who cares)
- copying the URL retains the scheme

We already have HTTPS-Only mode which causes an interstitial (excluding site exceptions), and a red padlock is shown if you do go there, plus I guess you could say the lack of the scheme is also a sign

Pretty much going to say this pref is redundant and we can remove it. All in favor of the MIGHTY PANTS, say Aye

**Comment by Thorin-Oakenpants** [comment]
Aye .. voting for myself

**Comment by fxbrit** [comment]
a year later https://hg.mozilla.org/mozilla-central/rev/e3d4641e2265#l1.102

**Comment by Thorin-Oakenpants** [comment]
AF is almost always ahead of the curve - moz just need to move slow and not break things, and priorities - but that entirely misses the point that [1846646](https://bugzilla.mozilla.org/show_bug.cgi?id=1846646) is only an android change
