### ISSUE TITLE
investigate snapshots

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1474]
I guess it's this:

![Screenshot_2022-06-12_14-07-45 png-fs8](https://user-images.githubusercontent.com/41237666/173237180-82b7a397-565d-4340-a47e-5b3527543a4e.png)

_Originally posted by @rusty-snake in https://github.com/arkenfox/user.js/issues/1461#issuecomment-1153182031_

**Comment by EdwardLangdon** [comment]
Actually, Snapshots is nothing but backup of Bookmarks locally.

`browser.bookmarks.max_backups` is the pref that controls how much backups should be there. By Default, It store for 15 days and older than that gets deleted.

You can change it to `0` to not store at all. It stores the amount of day you enter in the value.

**Comment by Thorin-Oakenpants** [comment]
it's not enforced
https://github.com/arkenfox/user.js/blob/1a899966a911dc2b69a808095ac7836bef5e214b/user.js#L1293-L1294

I fully get that this is local data, but 420 days is a long time, or 240 for non user gesture (or whatever it was). I bookmark things all the time on the toolbar and remove them went finally followed up on/actioned. A years worth of that would get me a public whipping, and a forced "does she float" test, before being burned as a witch

So at the very least, I will get around to checking what exactly can be used to disable this (but not bookmark backups), or limit it, for those who want it.

**Comment by EdwardLangdon** [comment]
Well, It is just for 15 Days by default and older that gets deleted. So, Why bother then ?

**Comment by Thorin-Oakenpants** [comment]
the snapshots are not 15 days

**Comment by Thorin-Oakenpants** [comment]
IDFC about `browser.bookmarks.max_backups` - I am investigating SNAPSHOTS which is entirely different

**Comment by EdwardLangdon** [comment]
Well, The screenshots depict about Bookmarks Backups not Snapshots.

**Comment by Thorin-Oakenpants** [comment]
> The screenshots depict about Bookmarks Backups not Snapshots

that's not my picture

**Comment by Jee-Hex** [comment]
> still trying to work out what [snapshots](https://searchfox.org/mozilla-central/search?q=snapshots&path=&case=false&regexp=false) are
>

I was going to say maybe this is frecency-related given some bugs on bugzilla (e.g. [1742470](https://bugzilla.mozilla.org/show_bug.cgi?id=1742470)) but then from your link I found [this](https://searchfox.org/mozilla-central/source/browser/components/places/SnapshotSelector.jsm#121) 

```
*   Whether adult sites should be filtered from the snapshots.
```

which then led me to [this](https://searchfox.org/mozilla-central/source/browser/components/places/SnapshotSelector.jsm#16)

```javascript
  FilterAdult: "resource://activity-stream/lib/FilterAdult.jsm",
```

so I'd say this has something to do activity stream, and if not then maybe telemetry.

**Comment by Thorin-Oakenpants** [comment]
It seems to hook into all sorts of things .. like pagethumbs

**Comment by Jee-Hex** [comment]
Okay so I found [bug 1716748](https://bugzilla.mozilla.org/show_bug.cgi?id=1716748) via [bug 1722891](https://bugzilla.mozilla.org/show_bug.cgi?id=1722891)...

**Comment by Thorin-Oakenpants** [comment]
closing. honestly, this is disk avoidance at most and I consider that to be mostly out of scope - see section `5000`

> so I'd say this has something to do activity stream

maybe. we disable AS by default, but if users want that for the landing page, it's simple enough to config

> and if not then maybe telemetry

It has nothing to do with telemetry, as in we disable telemetry - not that telemetry is a bad thing when done right (not here to have a debate about that). Everything via application goes thru the master switch, even the coverage ping respects the last profile settings. That said, we go super overboard and kill all the actual local collection of it, just look at about:telemetry

If someone wants to allow telemetry, and override all those, then that's on them

**Comment by Jee-Hex** [comment]
Addendum: looks like it's [freceny](https://bugzilla.mozilla.org/show_bug.cgi?id=1804227#a2011746_240353)-[related](https://bugzilla.mozilla.org/show_bug.cgi?id=704027#c3) after all...
