### ISSUE TITLE
Clarity on sections 6000 & 7000 in user.js

### ISSUE THREAD

**Issue by DjKilla2** [arkenfox/user.js#1476]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 101.0.1 Windows 10 21H2
  - Steps to Reproduce (STR): None
  - Expected result:m None
  - Actual result: None
  - Console errors and warnings: None
  - Anything else you deem worth mentioning: See message below

---
I have a few settings set in Arkenfox user.js that have been moved to or are in sections 6000 & 7000 (Don't Bother). What exactly are these sections? If I have settings set in these sections, are they ignored by Firefox? Are these settings deprecated and no longer exist so I should 'Don't Bother' setting any of them? I checked the Wiki for an answer and tried searching for the answer in Issues but didn't find an answer.

**Comment by fxbrit** [comment]
- `[SECTION 6000]: DON'T TOUCH` -> enforced default values that you shouldn't flip.
- `[SECTION 7000]: DON'T BOTHER` -> stuff that doesn't make sense to change, if you're curious see https://github.com/arkenfox/user.js/issues/1235 and the commits in it.
