### ISSUE TITLE
prefscleaner.sh and updater.sh

### ISSUE THREAD

**Issue by cool-clay** [arkenfox/user.js#1480]
prefscleaner.sh and updater.sh

It seems like files might be named incorrectly or the shell script are calling wrong names.

I copied the files into the firefox directory, then I ran the sh scripts and I got errors that files did not exist.

**1) Start
2) Help
3) Exit
#? 1

prefs.js not found in the current directory.
**
**
This script will update to the latest user.js file and append any custom configurations from user-overrides.js. Continue Y/N? 

Status: user.js has been backed up and replaced with the latest version!
Warning: Could not find override file: user-overrides.js
**
The files from the zip extraction
$ ls
arkenfox-cleanup.js  prefsCleaner.bat  README.md           troubleshooter.js  updater.sh
LICENSE.txt          prefsCleaner.sh   scratchpad-scripts  updater.bat        user.js

firefox directory listing
$ ls
application.ini      gmp-clearkey          libnssutil3.so        precomplete
arkenfox             icons                 libplc4.so            prefsCleaner.sh
arkenfox-cleanup.js  libfreeblpriv3.so     libplds4.so           removed-files
browser              libipcclientcerts.so  libsmime3.so          Throbber-small.gif
crashreporter        liblgpllibs.so        libsoftokn3.so        troubleshooter.js
crashreporter.ini    libmozavcodec.so      libssl3.so            updater
defaults             libmozavutil.so       libxul.so             updater.ini
dependentlibs.list   libmozgtk.so          libxul.so.sig         updater.sh
distribution         libmozsandbox.so      minidump-analyzer     update-settings.ini
firefox              libmozsqlite3.so      omni.ja               user.js
firefox-bin          libmozwayland.so      pingsender            userjs_backups
firefox-bin.sig      libnspr4.so           platform.ini
firefox.sig          libnss3.so            plugin-container
fonts                libnssckbi.so         plugin-container.sig

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain

> Put all the relevant files into the root folder of ***your profile*** [1]

> To find your profile, open `about:support` and look for `Profile Folder` under `Application Basics`.

Your profile is NOT your firefox installation.

**Comment by cool-clay** [comment]
I had used the about:support and opened a folder,  but I chose the wrong folder in there,  I wasn't aware that there was another folder option in there.

It works, I'm sorry to have complained, my fault.
