### ISSUE TITLE
FYI: interactive arkenfox user.js | also user.js viewer/comparer tool

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1481]
hijacking OP as a ToDo
- [x] add link in user.js
- [x] add link in readme
- [ ] add links in wiki

---

many thanks to @icpantsparti2 ❤️

We created a repo, with icpantsparti2 as admin, and he has done all the work, which auto loads the current AF user.js, and you can search and filter any which way from here to sunday, and back, with tea and biscuits
- repo: https://github.com/arkenfox/gui
- website: https://arkenfox.github.io/gui

You can even create URLs for your filters/searches; e.g.
- all the defaults - https://arkenfox.github.io/gui/?t=DEFAULT
- all the window specific prefs - https://arkenfox.github.io/gui/?t=WINDOWS
- all the prefs added in FF101 - https://arkenfox.github.io/gui/?t=FF101%2B
- anything to do with `compat` - https://arkenfox.github.io/gui/?s=compat

There's nothing more to do, except maybe polish the looks and feel of it - which shouldn't hold anything up, so ENJOY! I'll be adding some info and links to this in the readme and wiki

---

Also
- previous: #608
- new repo https://github.com/icpantsparti2/firefox-user.js-tool
- this is icpantsparti2's user.js loader/viewer/compare tool, which was used to build the live arkenfox viewer

**Comment by KOLANICH** [comment]
I have read the code of this tool and I bitterly dislike its quality because it is not structured the way making it easier to read, understand and modify it. I also may want to integrate it into my firefox addon applying arkenfox patches to about:config which currently has a very minimalistic GUI.

**Comment by Thorin-Oakenpants** [comment]
icpantsparti built this in his own free time, and I for one have been after something like this for a long time. Is it perfect and super polished, nope. Are you? As far as I'm concerned
- It's already made, and free (and modified for us)
- It's fast
- It works
- It has all the bells and whistles
- It's first party only
- It's maintained

If you have anything constructive/technical to add, then contribute in the appropriate repo, rather than pooing pooing it here

**Comment by icpantsparti2** [comment]
Thanks also to @overdodactyl for the concept (from a previous gui demo), and thanks for all the preparation you, @Thorin-Oakenpants (and any one else) did long ago.  Thanks @Thorin-Oakenpants for the tweaks you suggested.

**Comment by overdodactyl** [comment]
Happy to see it was moved forward.  Nice work!

**Comment by Thorin-Oakenpants** [comment]
OMG the bird lives .. nice to see you again dacky :)

**Comment by atomGit** [comment]
very nice job @icpantsparti2 - might be good to add links to both the wiki and the user.js

**Comment by Thorin-Oakenpants** [comment]
i added a link in the user.js .. will revise wiki

**Comment by Thorin-Oakenpants** [comment]
wiki spot 1 - right at the beginning

![spot1](https://github.com/arkenfox/user.js/assets/16656956/f93277e8-c3f1-46d2-8351-65536e364184)

**Comment by Thorin-Oakenpants** [comment]
I will be updating the read in the very near future - tracking tidying the gui info in there elsewhere (along with some other changes)

So I feel we can close and unpin this now - it should have had enough exposure
