### ISSUE TITLE
soundcloud login is broken when RFP is enabled [solved: caused by RFP version spoofing, solved in v102]

### ISSUE THREAD

**Issue by reslock** [arkenfox/user.js#1482]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 101.0.1 & windows 11 pro
  - Steps to Reproduce (STR): go to https://soundcloud.com/ and try login but always says Our robots think you are a robot.
Try reloading the page.
  - Expected result: be able to log in
  - Actual result: not being able to log in
  - Console errors and warnings:
![imagen](https://user-images.githubusercontent.com/107806935/174491415-6ea555d3-afce-41e7-9cb2-5f4fcee968ad.png)
  - Anything else you deem worth mentioning:
![imagen](https://user-images.githubusercontent.com/107806935/174491446-a9e68867-9486-43c7-bc42-3e4ad16f8e2b.png)

**Comment by fxbrit** [comment]
we are aware of this issue and we reported it to mozilla already. it is caused by RFP spoofing the version of the browser in the UA, so until v102 your only option is to disable RFP to login. from v102+ the version will no longer be spoofed so that breakage should go away 🎉

**Comment by KOLANICH** [comment]
>we are aware of this issue and we reported it to mozilla already. it is caused by RFP spoofing the version of the browser in the UA

Are there any details on how is it caused? I have [searched](https://bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&short_desc=soundcloud&query_format=advanced&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED) but I don't get from the bugs title which bug is about this issue.

**Comment by Thorin-Oakenpants** [comment]
[try harder]https://bugzilla.mozilla.org/show_bug.cgi?id=1610762#c9)

**Comment by Thorin-Oakenpants** [comment]
RFP no longer spoofs version on desktop FF102+
