### ISSUE TITLE
FYI: `firefucks`, a tool converting a regular Firefox into Developer Edition

### ISSUE THREAD

**Issue by KOLANICH** [arkenfox/user.js#1484]
I have written a tool, https://github.com/KOLANICH-tools/firefucks.py , that converts a regular Firefox into Firefox Developer Edition. It enables such features as WebExtensions Experiments and allows installation of unsigned addons.

The tool is only useful for users of Firefox shipped by distros as native binary packages, because users of Mozilla-shipped Firefox will be better if just downloaded the DevEdition, and Snap container is no better than statically Firefox archive from Mozilla.

## Installation

To install you need to install manually
1. libzip from packages of the package manager

Python packages from git repos (install procedure: `git clone <repo>; cd <dir>; python3 -m build -nwx .; sudo pip3 install --upgrade ./dist/*.whl;`, you need a `build` tool, can be installed as `python3-build` in Debian-based distros, or from `pypi`: `pip install --upgrade build`.):
2. https://github.com/KOLANICH-libs/libzip.py 
3. https://github.com/Kronuz/esprima-python
4. https://github.com/ksons/jscodegen.py
5. https://github.com/KOLANICH-tools/firefucks.py

After this `firefucks` binary should appear in your system.

For usage see `ReadMe.md` in the repo.

## Rationale

To be honest, the need in this tool has emerged long ago, when distro maintainers have ignored the calls to enable WebExtensions Experiments. But later even further changes have happenned. I'm not sure whom really to blame for that, Mozilla or maintainers, but somewhen in some Linux distros Firefox has stopped accepting unsigned addons, as it used to be accepting because of the patches applied during the build process when building binary packages for distros. It was a far more restrictive change, since there are some unmaintained addons I use that contain bugs, so I need to debug and fix them, and the maintainer]s official position is "create an own addon on AMO", and of course I'm not going to upload fixed versions of them to AMO since Mozilla's requirement of 2FA is absolutely inacceptable.

So I have created the tool, https://github.com/KOLANICH-tools/firefucks.py . It automates the well-known technique of patching `omni.ja`, which contains some generated modules with hardcoded build-time constants and some generic JavaScript code, the same for regular Fx and DevEdition choosing the branch depending on the constants;

The future direction is to put it into triggers for package managers, to make Firefox patched automatically on installation of the binary package by the package manager.

The tool currently has drawbacks, which should be fixed before we are ready to put it into triggers. Well, it can be put into trigfers right now, but I'm unhappy with the way it operates now.

1. we use the zip library that creates a backup copy of archives when modifying them. Instead we need to overwrite the file in place, without creating a new file and copying the most of archive into it. It can be done in-place, but I know no zip libs doing it in-place. The authour and maintainer of the library we use has refused to make this feature into the lib because it contradicts to his vision of the project. So we need an another lib.
2. triggers should be routed through my abstraction layer. I need to finish it.

**Comment by rusty-snake** [comment]
> requirement of 2FA is absolutely inacceptable.

What do you have against 2FA, it drastically improves account security.

**Comment by fxbrit** [comment]
I'm sorry, but why did you make a promotional post in another repo? I'm going to close and lock for now.

@Thorin-Oakenpants I think we should just delete this one.
