### ISSUE TITLE
Need help editing what it does.

### ISSUE THREAD

**Issue by NoNameISNoMan** [arkenfox/user.js#1485]
I Created the Overrides file, I changed what I needed, nothing happened.
Here are the lines that I changed, maybe I did something wrong?

/** SANITIZE ON SHUTDOWN : ALL OR NOTHING ***/
/* 2810: enable Firefox to clear items on shutdown (2811)
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes ***/
user_pref("privacy.sanitize.sanitizeOnShutdown", false); // [DEFAULT: true]
/* 2811: set/enforce what items to clear on shutdown (if 2810 is true) [SETUP-CHROME]
 * These items do not use exceptions, it is all or nothing (1681701)
 * [NOTE] If "history" is true, downloads will also be cleared
 * [NOTE] "sessions": Active Logins: refers to HTTP Basic Authentication [1], not logins via cookies
 * [NOTE] "offlineApps": Offline Website Data: localStorage, service worker cache, QuotaManager (IndexedDB, asm-cache)
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes>Settings
 * [1] https://en.wikipedia.org/wiki/Basic_access_authentication ***/
user_pref("privacy.clearOnShutdown.cache", false);     // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.downloads", false); // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.formdata", false);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.history", false);   // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.sessions", false);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.clearOnShutdown.cookies", false);
   // user_pref("privacy.clearOnShutdown.siteSettings", false); // [DEFAULT: false]
/* 2812: reset default items to clear with Ctrl-Shift-Del (to match 2811) [SETUP-CHROME]
 * This dialog can also be accessed from the menu History>Clear Recent History
 * Firefox remembers your last choices. This will reset them when you start Firefox
 * [NOTE] Regardless of what you set "downloads" to, as soon as the dialog
 * for "Clear Recent History" is opened, it is synced to the same as "history" ***/
user_pref("privacy.cpd.cache", false);    // [DEFAULT: true]
user_pref("privacy.cpd.formdata", false); // [DEFAULT: true]
user_pref("privacy.cpd.history", false);  // [DEFAULT: true]
user_pref("privacy.cpd.sessions", false); // [DEFAULT: true]
user_pref("privacy.cpd.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.cpd.cookies", false);

Edit: is this it?

/* 0102: set startup page [SETUP-CHROME]
 * 0=blank, 1=home, 2=last visited page, 3=resume previous session
 * [NOTE] Session Restore is cleared with history (2811, 2812), and not used in Private Browsing mode
 * [SETTING] General>Startup>Restore previous session ***/
user_pref("browser.startup.page", 3);

**Comment by rusty-snake** [comment]
Did you run the updater?

**Comment by NoNameISNoMan** [comment]
The updater? It just said that I needed to edit in a new file.

**Comment by EdwardLangdon** [comment]
Read the Wiki.

**Comment by NoNameISNoMan** [comment]
Yea, I did, and it didn't help! That's why I'm here!

**Comment by rusty-snake** [comment]
Do you created `user-overrides.js` or something else like `user-overrides.js.txt`?

**Comment by NoNameISNoMan** [comment]
Not stupid!

![image](https://user-images.githubusercontent.com/85317599/175766042-b3776b72-d2bd-45f1-9e01-68032096165f.png)

**Comment by rusty-snake** [comment]
What do you even want?

Are you asking because the change do not appear on `about:config` or because they do not have the expected effect?

**Comment by rusty-snake** [comment]
Your `user-overrides.js` is newer than your `user.js`.

**Comment by rusty-snake** [comment]
And has same size.

**Comment by NoNameISNoMan** [comment]
I want it to keep me logged in and not close my tabs.

**Comment by rusty-snake** [comment]
Read the wiki.

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-keep-logins

**Comment by NoNameISNoMan** [comment]
Ok, I edited it and guess what, IT DOESN'T WORK! JUST LIKE I SAID!

**Comment by NoNameISNoMan** [comment]
> Your `user-overrides.js` is newer than your `user.js`.

I edited it, is it not supposed too?

**Comment by rusty-snake** [comment]
Read the wiki.

Run the updater.

What we said.

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/wiki/3.1-Overrides

> You do this by keeping them in a separate user-overrides.js file in your profile folder, so updating doesn't wipe them but instead ***appends them (when you run the updater)***.

**Comment by NoNameISNoMan** [comment]
> Read the wiki.
> 
> Run the updater.
> 
> What we said.

Read the Wiki.

Have no idea how to even BEGIN to work with it.

AND THAT'S WHY I FUCKING ASKED.

**Comment by NoNameISNoMan** [comment]
I created a user-overrides.js file AS ASKED. Edited relevant values AS ASKED.
NOW THE FUCKING QUESTION IS: WHAT DO I DO NOW???

**Comment by rusty-snake** [comment]
Run the updater as we and the wiki say to you from the begin on.

**Comment by rusty-snake** [comment]
> AND THAT'S WHY I ASKED.

And nobody is interested in answering the same question [over](https://github.com/arkenfox/user.js/issues/1463) and [over](https://github.com/arkenfox/user.js/issues/1359) again if there is documentation for it.

**Comment by NoNameISNoMan** [comment]
> Run the updater as we and the wiki say to you from the begin on.

Ok, HOW?!?

**Comment by rusty-snake** [comment]
Read the Wiki.

https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain
https://github.com/arkenfox/user.js/wiki/5.1-Updater-%5BOptions%5D

**Comment by NoNameISNoMan** [comment]
I started the updater.bat, pressed S, run the cleaner, AND NOTHING HAPPENED!

**Comment by NoNameISNoMan** [comment]
> I started the updater.bat, pressed S, run the cleaner, AND NOTHING HAPPENED!

Yes, it DID create a backup, but it didn't actually change anything!

**Comment by rusty-snake** [comment]
IDK how the windows updater works, but first open your user.js in a editor (e.g. notepad++) and check if your user-overrides.js got appended.

**Comment by rusty-snake** [comment]
Also

> !! Unicode encoded override files should be stored without the BOM header !!

**Comment by NoNameISNoMan** [comment]
NOPE!

![image](https://user-images.githubusercontent.com/85317599/175766620-35039a9a-4e25-4f13-8846-b7659b77628a.png)

**Comment by NoNameISNoMan** [comment]
WHYYYYYYY?!?!?!

**Comment by NoNameISNoMan** [comment]
What the heck is a BOM header?

**Comment by rusty-snake** [comment]
> NOPE!

It *appends* (unless you use `-merge`).

**Comment by NoNameISNoMan** [comment]
Trying again!

![image](https://user-images.githubusercontent.com/85317599/175766737-72565778-b2ab-45ba-a07b-a72063c6d9a7.png)

**Comment by rusty-snake** [comment]
> What the Heck is a BOM header?

[Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)

**Comment by NoNameISNoMan** [comment]
> > NOPE!
> 
> It _appends_ (unless you use `-merge`).

What? Oh, It might be good to say that I don't know what "appends" means.

**Comment by NoNameISNoMan** [comment]
> [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)

Nope! Not reading that wall of text!

**Comment by rusty-snake** [comment]
> What? Oh, It might be good to say that I don't know what "appends" means.

append
attach
add to the end
hook together

It puts your user-overrides.js at the end of the downloaded user.js.

**Comment by fxbrit** [comment]
dude, this is not tech support and you shouldn't expect rusty to explain to you what append means or what BOM means. if you don't know how to work scripts you should look that up yourself, the internet exists you know...

also use some netiquette: you ignored the template and used capslock over and over. not to mention you sent a thousand different messages in less than 10 mins, chill.

anyway: before you go on with overrides, did at least the user.js apply? have you checked `_user.js.parrot` in `about:config`?

**Comment by NoNameISNoMan** [comment]
> What? Oh, It might be good to say that I don't know what "appends" means.

I read up on it. Still no clue.

**Comment by NoNameISNoMan** [comment]
> > What? Oh, It might be good to say that I don't know what "appends" means.
> 
> append attach add to the end hook together
> 
> It puts your user-overrides.js at the end of the downloaded user.js.

Ah! Got it. Is it not supposed to do it?

**Comment by NoNameISNoMan** [comment]
> dude, this is not tech support and you shouldn't expect rusty to explain to you what append means or what BOM means. if you don't know how to work with scripts you should look that up yourself, the internet exists you know...
> 
> also use some netiquette: you ignored the template and used capslock over and over. not to mention you sent a thousand different messages in less than 10 mins, chill.
> 
> anyway: before you go on with overrides, did at least the user.js apply? have you checked `_user.js.parrot` in `about:config`?

1) This is the only point of contact I found, so...
2) I use CAPSLOCK to enunciate when I would speak louder or when I need to draw attention to something, and although yes I shouldn't have been yelling, but I am frustrated so, Please excuse me.
3) What in the what what?

**Comment by Thorin-Oakenpants** [comment]
42 email notifications in less than an hour. Locking. Do not open another issue or I will ban you

If you cannot understand the simple instructions in the wiki, or even plain english words like append .. then arkenfox is clearly not for you
