### ISSUE TITLE
Internet banking login issue

### ISSUE THREAD

**Issue by Leonis87** [arkenfox/user.js#1488]
Hi everyone. 
I've been using arkenfox for more than 2 years now. I was able solve some issues with websites changing prefs. But now I'm experiencing very weird issue with internetbanking on two different banks, ebay won't let me log on, some airlines won't search for flights and won't let me purchase flight. I never had this problem before and I've been using internetbanking and everything else with arkenfox two years. It started 3 weeks ago. I have to switch to original firefox profile without arkenfox user.js to be able log in to internet banking and some marketplaces.

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 102.0 64bit, Windows 10
  
  - Steps to Reproduce (STR):
     I've tried disable RFP, I've tried remove addons, I've tried two different computers, I even tried ubuntu machine. Same result. I don't       know which prefs is responsible for this.
 
  - Expected result: Sign in to internetbanking
 
  - Actual result: Unable use internetbanking and some marketplaces.

  - Console errors and warnings: No errors in console

  - Anything else you deem worth mentioning:
     
I don't know what happened, but I thought that this weird problem will stop when I update arkenfox to newest but problem still persist.

**Comment by Thorin-Oakenpants** [comment]
RFP is a prime candidate, as is 1600's
https://github.com/arkenfox/user.js/blob/c21b9faefc0d99ab4f91836ceddc68a2a52ff9cb/user.js#L576

**Comment by Leonis87** [comment]
> RFP is a prime candidate, as is 1600's
> 
> https://github.com/arkenfox/user.js/blob/c21b9faefc0d99ab4f91836ceddc68a2a52ff9cb/user.js#L576

**Comment by Leonis87** [comment]
> RFP is a prime candidate, as is 1600's
> 
> https://github.com/arkenfox/user.js/blob/c21b9faefc0d99ab4f91836ceddc68a2a52ff9cb/user.js#L576

Yes, true. 
Apparently "smart referer" addon is causing this issue as well. I had to add my bank website to "custom whitelist sources" to be able sign in. Ebay is sorted too. But RyanAir is not searching for flights no matter what I try.

I tried different combinations, as I mentioned in STR. Last thing what I can do is completely reinstall firefox.

I'm just worried that there is some other prefs responsible for this airlines websites and bank sites strange behaviour. Maybe new firefox update break something... and it can cause some more breakage to other websites as well...

Is it only me having this weird problem ?

**Comment by Leonis87** [comment]
> > banks / referers
> 
> I was reading about this yesterday - https://portswigger.net/web-security/csrf - and how referers are used to help authenticate
> 
> > Last thing what I can do is completely reinstall firefox.
> 
> Nah. That has nothing to do with settings or profiles and won't change anything.
> 
> If you test in a new profile (about:profiles), with arkenfox, this eliminates all other causes (extensions, old pref flips either arkenfox or something you did yourself years ago) .. and then you troubleshoot. You also use this profile before adding arkenfox to check that it is indeed an AF pref(s) - It's all in the troubleshooting wiki page.
> 
> > meh
> 
> Anyway, can you give me STR (steps to reproduce) - I want website URL(s) and exactly what you did and exactly how it fails. If it means logging in, I can't help. But it's generally not that hard to diagnose

1. I created brand new arkenfox profile, pasted my overrides.js and update it. I set "network.http.referer.XOriginPolicy", 0). Then I started test banks and ebay which worked. But www.ryanair.com couldn't search flights even when I was signed in. 

2. I started adding extensions, ublock, skip redirect, canvas blocker,... ebay and banks still worked except airlines. After I added "smart referer" extension banks, ebay and airlines stopped working correctly, I had to add "customs whitelist". Airlines don't work even after added to custom whitelist in smart referer.

**Comment by Leonis87** [comment]
> This might be completely unrelated to your issue but I'll comment just incase; I had some issues aswell with a banking/payment provider a few months ago, and re-enabling `beacon.enabled` temporarily fixed it. Seems like some sites rely on this for more than analytics now. (but still extremely rare)
> 
> -- PS: `referer` header for CSRF mitigation was deprecated many many years ago[[1]](https://bugzilla.mozilla.org/show_bug.cgi?id=446344)[[2]](https://wiki.mozilla.org/Security/Referrer#Further_work) for several reasons. If your bank login still relies on this solely you should report it as a vulnerability. (same with solely using `origin`, its only a defense in depth method[[3]](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#defense-in-depth-techniques))

Hi,
I have ("beacon.enabled", true) always. I was unable do paypal transaction using arkenfox.js since last year, but I'm not using much paypal. So that didn't bother me. But now I can't search and purchase flights and I'm quite confused what is cause this breakage.

**Comment by Thorin-Oakenpants** [comment]
I'm hoping earthlng drops the diffs very soon, I pinged him earlier, so I can get the release done ASAP.

Meanwhile, change your overrides to add these
- up to you about the cookies/offlineApps: exceptions are kept, this is more about keeping logins for site exceptions
- the main one is the lifetimePolicy - using session cookies can have issues: e.g. serviceWorkers fail etc
```
// temp overrides waiting for 102
user_pref("network.cookie.lifetimePolicy", 0);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.cookies", true);
```

**Comment by Thorin-Oakenpants** [comment]
> I created brand new arkenfox profile, pasted my overrides.js and update it. I set "network.http.referer.XOriginPolicy", 0). Then I started test banks and ebay which worked. But [www.ryanair.com](http://www.ryanair.com/) couldn't search flights even when I was signed in.

show your overrides. as I said, a new profile without arkenfox worked, and with 102 user.js worked as well - so that's with RFP, with refererpolicy, beacon all at user.js settings etc, i.e zero overrides

**Comment by Leonis87** [comment]
> > I created brand new arkenfox profile, pasted my overrides.js and update it. I set "network.http.referer.XOriginPolicy", 0). Then I started test banks and ebay which worked. But [www.ryanair.com](http://www.ryanair.com/) couldn't search flights even when I was signed in.
> 
> show your overrides. as I said, a new profile without arkenfox worked, and with 102 user.js worked as well - so that's with RFP, with refererpolicy, beacon all at user.js settings etc, i.e zero overrides

I tried new arkenfox profile without overrides.js and airlines websites worked, but banks not, as I expected because 
("network.http.referer.XOriginPolicy", 2). When I changed value to "1" banks sign in working alright. I haven't try any transactions yet but I hope it will be alright.

I  think I've found prefs responsible for airlines websites breaking. In my overrides.js I had ("intl.accept_languages", "en-US, en") in different language, after I changed it back to english everything is working. I don't know why it started right now when everything was fine for long time...

Ublock origin with settings from "4.1 Extension section" works fine, skip redirect and canvas blocker don't cause any problem either. Smart referer is going to bin from my firefox.

Here are my overrides:

user_pref("_user.js.parrot", "overrides section syntax error");

user_pref("browser.startup.page", 1); // 0102

user_pref("browser.startup.homepage", "about:home"); // 0103

user_pref("browser.newtabpage.enabled", true); // 0104

user_pref("browser.newtab.preload", true); // 0104

user_pref("keyword.enabled", true); // 0801

user_pref("browser.search.suggest.enabled", true); // 0804

user_pref("browser.urlbar.suggest.searches", true); // 0804

user_pref("security.mixed_content.block_display_content", false); // 1241

user_pref("network.http.referer.XOriginPolicy", 1); // 1601

user_pref("media.eme.enabled", true); // 2022

user_pref("media.autoplay.default", 0); // 2030

user_pref("beacon.enabled", true); // 2602

user_pref("network.cookie.lifetimePolicy", 0); // 2801

user_pref("privacy.sanitize.sanitizeOnShutdown", false); // 2810

user_pref("privacy.cpd.offlineApps", true); // 2812

user_pref("privacy.cpd.cookies", true); // 2812

user_pref("privacy.cpd.siteSettings", true); // 2812

user_pref("privacy.resistFingerprinting", false); // 4501

user_pref("privacy.resistFingerprinting.letterboxing", false); // 4504

user_pref("browser.link.open_newwindow.restriction", 2);

user_pref("signon.rememberSignons", false); // 5003

user_pref("browser.toolbars.bookmarks.visibility", "always");

user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);

user_pref("browser.urlbar.decodeURLsOnCopy", true); // 9000

user_pref("_user.js.parrot", "SUCCESS");

I'm using RFP but in different firefox profile. RFP cause some website not showing correctly so I'm switching between 2 profiles.


Thanks for help guys.

**Comment by Thorin-Oakenpants** [comment]
> I think I've found prefs responsible for airlines websites breaking. In my overrides.js I had ("intl.accept_languages", "en-US, en") in different language, after I changed it back to "english US" everything is working.

well that could do it, I mean the values are not meant to be localized, they are in effect set codes used as a standard - they should match what you have in `Settings > General > Language > Choose`

The name might be localized for your app language, e.g French may be Français etc, but the codes aren't

![languages](https://user-images.githubusercontent.com/16656956/176870468-837a5d2a-f1d5-4999-891b-03422308abe2.png)

**Comment by Thorin-Oakenpants** [comment]
Anyway, ryanair works, banks work if you fixup the referer (and maybe other things like RFP), also beacon was new to me

So I think we are done here and there is nothing new. At the end of the day, some sites are problematic, maybe use Firefox Beta as a one off browser for just banking. Personally I can get by with all mine via my banking app(s) and haven;t used a bank web interface in years

Pipe up, re-open if need be, if you have any other issues

**Comment by Thorin-Oakenpants** [comment]
PS: your overrides look very normal to me

**Comment by fxbrit** [comment]
> me and the fish are going snorkelling

yes please, love me some santorini greece

***

a bit late but: changing `intl.accept_languages` impacts the [HTTP Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) so if you set it to something not standard it could cause breakage (couldn't reproduce it on that specific website tho)

**Comment by Thorin-Oakenpants** [comment]
don't forget to pack your pokemon pyjamas

**Comment by Jee-Hex** [comment]
> In my overrides.js I had ("intl.accept_languages", "en-US, en") in different language

If you just need to override `intl.accept_languages` for a couple of sites for whatever reason you can try  [Accept-Language per site](https://addons.mozilla.org/en-US/firefox/addon/accept-language-per-site/). Obviously you will stand out more because it does not cover for things like `navigator.language` and `navigator.languages` so use sparingly.


> maybe use Firefox Beta as a one off browser

I believe you mean ESR.

> Personally I can get by with all mine via my banking app(s) and haven;t used a bank web interface in years

You are surprisingly not paranoid enough. I have never seen a banking site without third-party analytics, and why would anyone expect otherwise with apps?

**Comment by Thorin-Oakenpants** [comment]
> I believe you mean ESR.

nope. I meant Beta, because it's up to date with changes etc and there's no need to fluff around with running it concurrently with stable/nightly
