### ISSUE TITLE
Any way to stop hidden 'Add-ons Search Detection' via user.js?

### ISSUE THREAD

**Issue by CarlosMerc** [arkenfox/user.js#1492]
Can be seen via firefox task manager. It seems to hook to some sort of search engine changes and provides telemetry. 

{
  "manifest_version": 2,
  "name": "Add-ons Search Detection",
  "hidden": true,
  "applications": {
    "gecko": {
      "id": "addons-search-detection@mozilla.com"
    }
  },
  "version": "2.0.0",
  "description": "",
  "experiment_apis": {
    "addonsSearchDetection": {
      "schema": "schema.json",
      "parent": {
        "scopes": ["addon_parent"],
        "script": "api.js",
        "events": [],
        "paths": [["addonsSearchDetection"]]
      }
    }
  },
  "permissions": [
    "<all_urls>",
    "telemetry",
    "webRequest",
    "webRequestBlocking"
  ],
  "background": {
    "scripts": ["background.js"]
  }
}

One way would be just to disable or delete it, but it will come back after an update or restart.

**Comment by Thorin-Oakenpants** [comment]
let me know when you find any privacy issues

**Comment by rusty-snake** [comment]
> and provides telemetry

which is disable by arkenfox user.js

https://github.com/arkenfox/user.js/blob/ceacc9dd74086478d43ccf3a4f0bd5befda53a43/user.js#L152-L183
