### ISSUE TITLE
Homepage is force overridden to "about: "

### ISSUE THREAD

**Issue by privacyguy123** [arkenfox/user.js#1493]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 102.0 Windows 10 LTSC 2021
  - Steps to Reproduce (STR): Have modded user.js and addon that changes homepage (for example https://addons.mozilla.org/en-GB/firefox/addon/momentumdash/)
  - Expected result: Momentum splash page as Homepage (new tab works for some reason)
  - Actual result: Blank page as homepage (says about: (yes with no word after about:)
  - Console errors and warnings: None
  - Anything else you deem worth mentioning:

---

**Comment by rusty-snake** [comment]
Did you even search for "homepage" in the user.js?

https://github.com/arkenfox/user.js/blob/ceacc9dd74086478d43ccf3a4f0bd5befda53a43/user.js#L83-L91
