### ISSUE TITLE
Incorrect pref number in session restore recipe in #1080

### ISSUE THREAD

**Issue by mprobson** [arkenfox/user.js#1497]
Hello 👋 

I noticed a tiny mistake in the session restore recipe in #1080. The current text for the last line of the recipe lists the optional pref to be changed as 2812

```
  // user_pref("privacy.cpd.history", false); // 2812 optional to match when you use Ctrl-Shift-Del
```

Whereas the user.js file has it listed as 2820, so I think the changed line should be the following

```diff
-  // user_pref("privacy.cpd.history", false); // 2812 optional to match when you use Ctrl-Shift-Del
+  // user_pref("privacy.cpd.history", false); // 2820 optional to match when you use Ctrl-Shift-Del
```

I'm happy to open a pull request if that's possible for the issue but I wasn't sure how to modify it or suggest modifications since it's locked. Also, thanks for making such an amazing contribution and I hope I can contribute this small bit.

P.S. I couldn't find a Contributing file or instructions in the wiki so I hope this is the correct process but I'm happy to move or alter this issue if necessary.

**Comment by Thorin-Oakenpants** [comment]
Done. Thanks
