### ISSUE TITLE
Wiki extension recommendations

### ISSUE THREAD

**Issue by Lostname777** [arkenfox/user.js#1502]
Redirector has not updated since 2020, and you still recommend it (in maybe column) in the wiki. Reason?
Instead, what is your stance on recommended something like **LibRedirect**.

Or atleast remove the "✔" sign after Redirector as the extension is not maintained.

Also:
1. Smart Referer - not updated since 2019
2. Header Editor - since 2019
3. Request Control - since 2020
4. Behave! - since 2020
5. mozlz4-edit - since 2019
6. Enterprise Policy Generator - since 2020

And:
Umatrix last release was in 2021, not in 2020: Ref: https://github.com/gorhill/uMatrix/releases/tag/1.4.4

I hope I didn't make it sound arrogant, I am generally concerned. Thanks for your efforts Pants!

**Comment by crssi** [comment]
That might be false "accusation".
Not updated might also mean that it is polished to the very end and update is not needed.

😉

**Comment by rusty-snake** [comment]
> Instead, what is your stance on recommended something like LibRedirect.

Instead of Redirector? Then you could also recommend pineapples.

**Comment by Lostname777** [comment]
> > Note: The check mark is before the "privacy" link and not after the extension name.

Oh got it

**Comment by Thorin-Oakenpants** [comment]
> Umatrix last release was in 2021, not in 2020

The wiki says .. emphasis mine
> No longer maintained, the last commit was April 2020 **_except for a [one-off patch](https://github.com/gorhill/uMatrix/releases/tag/1.4.2)_** to fix a [vulnerability](https://github.com/vtriolet/writings/blob/main/posts/2021/ublock_origin_and_umatrix_denial_of_service.adoc)

Looking at the releases: https://github.com/gorhill/uMatrix/releases (and ignoring beta releases) - IDK where I got April 2020 from
- 1.4.0 was Sept 2019
- 1.4.2 was July 2021 <- this was the vulnerability fix
- 1.4.4 was July 2021 <- this was the following day to clean up a couple of issues I guess

THE POINT IS THIS HASN'T BEEN MAINTAINED SINCE JESUS

Will amend the wiki to show not updated since 2019

**Comment by Thorin-Oakenpants** [comment]
> Enterprise Policy Generator - since 2020

Removed it. It is very out of date with current policies

**Comment by Thorin-Oakenpants** [comment]
> Smart Referer - not updated since 2019

This is being looked at in #1433 - not that it isn't working or needs updating, but that we need a better approach (if users relax 1601)

**Comment by Thorin-Oakenpants** [comment]
> Header Editor - since 2019
> Request Control - since 2020
> Behave! - since 2020
> mozlz4-edit - since 2019

In what way are they not working? Please don't dump lists at me and expect to do the work. Provide evidence

**Comment by Thorin-Oakenpants** [comment]
> what is your stance on recommended something like LibRedirect.

duplicate of #1447
duplicate of #1373

also read -> https://github.com/arkenfox/user.js/issues/1373#issuecomment-1041845984

I do not care about LibRedirect. It is a very limited list and not a full solution. The full solution is to partition and mask your IP

**Comment by Lostname777** [comment]
I meant "not updated" for all of them. Not "not working"

**Comment by rusty-snake** [comment]
> Request Control

https://github.com/tumpio/requestcontrol/issues/164
