### ISSUE TITLE
[ISSUE] MOZILLA_PKIX_ERROR_KEY_PINNING_FAILURE - user.js-102.0 - Firefox 102.0.1 (64-bit)

### ISSUE THREAD

**Issue by marklane33** [arkenfox/user.js#1503]
Hello everyone,

[ISSUE] MOZILLA_PKIX_ERROR_KEY_PINNING_FAILURE 

user.js-102.0 

Firefox 102.0.1 (64-bit)

Windows 11 64 bits

The following happens, in the stable versions of the mozilla browser and your plugin.

I can't visit many pages.

Even pages like "Youtube.com" "Google.com" Etc.

I do not have any other plugin installed in my browser, only yours.

I have tried the following:

Uninstall the browser with everything, folders, profiles, etc.

I did a fresh install from scratch and got the same result.

The only "TEMPORARY" way that I have found to visit certain pages is the following:
Open firefox and go to about:config in address bar
search and change value of "security.cert_pinning.enforcement_level" from 2 to 0. But that solution only lasts as long as I have that section of my browser open. When I close the browser, everything returns to how it was before and with the same problems.

<a href="https://ibb.co/F4qLX6q"><img src="https://i.ibb.co/hF1Jcs1/Captura-de-pantalla-2022-07-12-164404-copia.png" alt="Captura-de-pantalla-2022-07-12-164404-copia" border="0"></a>

<a href="https://ibb.co/qJt6NBW"><img src="https://i.ibb.co/PD7kcx9/Captura-de-pantalla-2022-07-13-202619-copia.png" alt="Captura-de-pantalla-2022-07-13-202619-copia" border="0"></a>

Any ideas and any help. Is really appreciate it.

Cheers.

**Comment by atomGit** [comment]
are you using an AV?

try a value of 1 and see what happens

lastly, if value privacy at all, you can not use windows

**Comment by marklane33** [comment]
Thanks @atomGit for your reply.

Yes I am using an AV. (KTS).

I tried that also... I change from 2 to 0 and to 1 also. But always come back to 2.

Lastly, I value my privacy but sadly I have to use Windows for my work. 

Sometime you have to find a balance between your work and your privacy. 

Anyway, any other ideas or any help on this.

Will be pretty appreciate it.

Cheers.

**Comment by Thorin-Oakenpants** [comment]
> But that solution only lasts as long as I have that section of my browser open. When I close the browser, everything returns to how it was before and with the same problems

So you have the solution then (although I would have thought the default value of 1 was sufficient)

> I change from 2 to 0 and to 1 also. But always come back to 2.

Use an [override](https://github.com/arkenfox/user.js/wiki/3.1-Overrides), and run the updater. It is not recommended to modify the user.js itself directly and do not rely on about:config (except when testing)
