### ISSUE TITLE
Enabling WebGL on a per-site basis?

### ISSUE THREAD

**Issue by umbralOptimatum** [arkenfox/user.js#1505]
I need WebGL for a couple of websites but would prefer to keep it locked down for everything else. Is there any way to enable it just for those sites? I couldn't find anything in the closed issues that wasn't many years out of date.

And thank you folks for putting the work in to create such an incredible resource. I installed Arkenfox yesterday and (despite the intimidating complexity) was pleasantly surprised at how painless it was! A handful of common overrides I obviously needed, a few custom preferences of my own, and it's been smooth sailing. Just one extension conflict so far and it turned out to be entirely the extension's fault—the fix I _thought_ was installed hasn't made it to the live build. Just wish I'd noticed before two hours spent debugging...

**Comment by rusty-snake** [comment]
> I need WebGL for a couple of websites but would prefer to keep it locked down for everything else. Is there any way to enable it just for those sites?

A seperate firefox profile. IDK any good, secure and trusted extension which can block WebGL.

**Comment by fxbrit** [comment]
> Just wish I'd noticed before two hours spent debugging...

you live and learn 😄
