### ISSUE TITLE
SSL_ERROR_UNSAFE_NEGOTIATION

### ISSUE THREAD

**Issue by nnzv** [arkenfox/user.js#1516]
### Browser version & OS

* OS: Gentoo Linux
* Browser: Mozilla Firefox 102.0

### Steps to Reproduce

* Connect to https://9p.io (plan9 website)

### Excepted result

The connection can establish without troubles. 

### Actual result:

```
Secure Connection Failed

An error occurred during a connection to 9p.io. Peer attempted old style (potentially vulnerable) handshake.

Error code: SSL_ERROR_UNSAFE_NEGOTIATION

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem. Learn more...

[Try again]
````

### Console errors and warnings:

```
None
```

##  Anything else you deem worth mentioning:

```js
// file: user-overrides.js
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", "search.brave.com");
user_pref("browser.search.region", "US");
user_pref("keyword.enabled", true);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.urlbar.maxRichResults", 0);
user_pref("browser.urlbar.autoFill", false);
user_pref("places.history.enabled", true);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.download.autohideButton", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", false); 
user_pref("ui.prefersReducedMotion", 1); 
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.warnOnQuitShortcut", false);
user_pref("full-screen-api.warning.delay", 0);
user_pref("full-screen-api.warning.timeout", 0);
user_pref("browser.taskbar.lists.enabled", false);
user_pref("browser.taskbar.lists.frequent.enabled", false);
user_pref("browser.tabs.loadBookmarksInTabs", true); 
user_pref("browser.taskbar.lists.recent.enabled", false);
user_pref("browser.taskbar.lists.tasks.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("extensions.pocket.enabled", false);
```
Note: Even after tried the suggestions made by @geeknik on #895, the issue currently exists.

**Comment by Thorin-Oakenpants** [comment]
In future, use the correct form

https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-check
- check items tagged with `[SETUP-` in the user.js, but notably `[SETUP-WEB` totals 13
   - and/or search the user.js for the error code or part of it
   - https://github.com/arkenfox/user.js/blob/996881aef184246a011ac29382e91d634cda7b65/user.js#L453
   - ^ OMG
- search the repo for existing answers - such as these for example
   -  #1094
   - #895 

> Even after tried the suggestions made by @geeknik on https://github.com/arkenfox/user.js/issues/895, the issue currently exists.

worksforme. in a new profile
- visit site, works
- close site tab, sanitize (this helps), restart (may not be required)
- flip `security.ssl.require_safe_negotiation` to true, visit site - fails with _the_ error above
- close site tab, sanitize (this helps), restart (may not be required)
- flip `security.ssl.require_safe_negotiation` to false, visit site - works

I'm not 100% sure if sanitizing is doing anything, but I did it anyway (everything - not saying you need to do that - probably just a new Firefox session would do it). I never restarted, but I did have to close the previous site tab, and try a couple of times - maybe it's a timing thing where it caches the result for a minute - IDK.

I have also tested this in my main FF which is basically the current AF (with some overrides that have no bearing on this issue), and I flipped the pref in question and visited the site no problems

If you want it permanently, add this to your overrides, run the updater (so it's added to your user.js), and restart the browser
```js
user_pref("security.ssl.require_safe_negotiation", false);
```

If you don't want it permanently, then restart the browser, and flip the pref in about:config BEFORE going to the site (or do what I did and try several times, maybe sanitize)

Personally, up to you. Very few sites (less than 1% of top sites anyway) lack renegotiation - so consider using plan9 in a secondary browser

Closing, but feel free to add if it works
