### ISSUE TITLE
RFP + Maximized Windows on startup [solved: no]

### ISSUE THREAD

**Issue by EdwardLangdon** [arkenfox/user.js#1517]
With RFP on in `user.js`, Is it possible to make Firefox to open in a maximized windows instead of RFP defined 1600 * 900 on startup and on creating new windows by a user config in `user.js` ?

I could use [Maximize All Windows](https://addons.mozilla.org/en-US/firefox/addon/maximize-all-windows/) extension but I wanna reduce the fingerprint it creates.

**Comment by rusty-snake** [comment]
No.

**Comment by Thorin-Oakenpants** [comment]
> I could use Maximize All Windows extension but I wanna reduce the fingerprint it creates.

That's not going to affect your fingerprint any more than manually maximizing - the metric exposed is affected by the action, not an extension "leak"
