### ISSUE TITLE
"Read Aloud" extension [solved: media.autoplay.blocking_policy]

### ISSUE THREAD

**Issue by behradJ** [arkenfox/user.js#1520]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [checked] I have read the troubleshooting guide, done the checks and confirmed this is caused by Arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 102.0.1 / Archlinux
  - Steps to Reproduce (STR): it causes "Read Aloud" add-on stop working.
  - Expected result: I can hear the audio by the add-on (Read Aloud)
  - Actual result: add-on stops working after trying to play the sound.
  - Console errors and warnings: no
  - Anything else you deem worth mentioning:I just want to know what users.js option can possibly cause this problem, and I know you don't support for 3rd parties add-ons. Thanks for your help.

---

**Comment by GlassGruber** [comment]
Hei I'm no expert in this, but errors in the console for addons are unfortunately not visible in the common Web console, instead you need to see the Browser console. 
See these below
* https://stackoverflow.com/questions/57712492/how-do-i-debug-a-firefox-extension-it-seemingly-crashes-silently
* https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html

So basically you should 
1. open the Browser console
2. clear everything in it to make sure only relevant message will be displayed
3. go to a website and start the addon
4. see what appears in console and report back

Also with Steps to Reproduce you should detail what are the steps and actions you do to show us how the error you encounter is produced.

But I wouldn't set too many expectations with this. 

AFAICT these type of addons are calling remote servers where doing fancy computations on received input will spit out something back to the users on their clients, in your case text to speech. 
This workflow usually expects lots of default behaviors from browsers/devices and can break with ease when RFP is on. 

TBH, you really can't expect much privacy with these type of addons so, if it's important to you, your best bet is create a new separate FF profile dedicated to that addon usage. 
This way they will get only the information they can on the sites you are operating the addon but not the rest of your browsing. 

Compartmentalization is many times the only reasonable and viable solution, not perfect but fairly practical, considering privacy as part of the gains involved with this extra operations needed ofc.

But others here are far more experts than me and can add more to this.

**Comment by behradJ** [comment]
> Hei I'm no expert in this, but errors in the console for addons are unfortunately not visible in the common Web console, instead you need to see the Browser console. 
> 
> See these below
> 
> * https://stackoverflow.com/questions/57712492/how-do-i-debug-a-firefox-extension-it-seemingly-crashes-silently
> 
> * https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html
> 
> 
> 
> So basically you should 
> 
> 1. open the Browser console
> 
> 2. clear everything in it to make sure only relevant message will be displayed
> 
> 3. go to a website and start the addon
> 
> 4. see what appears in console and report back
> 
> 
> 
> Also with Steps to Reproduce you should detail what are the steps and actions you do to show us how the error you encounter is produced.
> 
> 
> 
> But I wouldn't set too many expectations with this. 
> 
> 
> 
> AFAICT these type of addons are calling remote servers where doing fancy computations on received input will spit out something back to the users on their clients, in your case text to speech. 
> 
> This workflow usually expects lots of default behaviors from browsers/devices and can break with ease when RFP is on. 
> 
> 
> 
> TBH, you really can't expect much privacy with these type of addons so, if it's important to you, your best bet is create a new separate FF profile dedicated to that addon usage. 
> 
> This way they will get only the information they can on the sites you are operating the addon but not the rest of your browsing. 
> 
> 
> 
> Compartmentalization is many times the only reasonable and viable solution, not perfect but fairly practical, considering privacy as part of the gains involved with this extra operations needed ofc.
> 
> 
> 
> But others here are far more experts than me and can add more to this.
> 
>  
> 
> 
> 
> 
> 
> 

Hi thanks for your help,I'll try that as soon as I get to my pc.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/6e53e841f78c512f4d1eedb6a2409df746eea979/user.js#L848

https://bugzilla.mozilla.org/show_bug.cgi?id=1333641

did you really troubleshoot? If flipping RFP is the solution then shame on you. Also RFP one day won't apply to extensions, but that day is not today. If it's not RFP then reopen and I'll remove the invalid tag

**Comment by behradJ** [comment]
Hi,
I do really sorry for being too late to answer.
I don't want to disable RFP to get it to work, but even when I toggle that, it doesn't work either.
I should mention that I am using this Arkenfox user.js for about a year and this extension was working fine until about 2-3 months ago.
I did what GlassGruber asked me to do and the error in browser console is this:
`Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
defaults.js:1031
    bgPageInvoke moz-extension://484c95f2-f41b-4b1d-bcfe-077453a839fa/js/defaults.js:1031
`

**Comment by Thorin-Oakenpants** [comment]
@behradJ said


console-export
```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
defaults.js:1031
    bgPageInvoke moz-extension://484c95f2-f41b-4b1d-bcfe-077453a839fa/js/defaults.js:1031
```

Hi,
I do really sorry for being too late to answer.
I don't want to disable RFP to get it to work, but even when I toggle that, it doesn't work either.
I should mention that I am using this Arkenfox user.js for about a year and this extension was working fine until about 2-3 months ago.
I did what GlassGruber asked me to do and the error in browser console is this:
`Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved defaults.js:1031 bgPageInvoke moz-extension://484c95f2-f41b-4b1d-bcfe-077453a839fa/js/defaults.js:1031 `

Update:
Now, I noticed that it wasn't the error we are looking for, and it was an error of me clicking on the browser console window while the extension window was open.
So now it does not output any error on the Browser Console which I open that by Ctrl + Shift + J.

Update #2:
I removed "Read Aloud" from toolbar menu and add it to the main toolbar and now on opening the window I get this in browser console:
`Cannot send function call result: other side closed connection (call data: ({path:"windows.create", args:[{allowScriptsToClose:null, cookieStoreId:null, focused:true, height:null, incognito:null, left:null, state:null, tabId:null, titlePreface:null, top:null, type:"popup", url:"moz-extension://484c95f2-f41b-4b1d-bcfe-077453a839fa/popup.html?tab=1", width:null}]}))
`

**Comment by Thorin-Oakenpants** [comment]
> I don't want to disable RFP to get it to work, but even when I toggle that, it doesn't work either.
> I should mention that I am using this Arkenfox user.js for about a year and this extension was working fine until about 2-3 months ago.

These are things you should have mentioned in the first post. Also, it doesn't matter per se that you don't want to disable RFP - this is about finding the cause of the problem.

Have you asked the extension developer? Have you tried a new test profile with the extension and tested it works. And then have you added the user.js SECTION by SECTION, restarting and testing in between adding sections, to see what section this starts to fail on? What are your overrides? But first things first - does it work in a new profile with no other extensions. Prove to me that AF causes this - otherwise I refuse to help - your OP doesn't inspire me that you read the wiki or did any of the troubleshooting, and I only piped up with "try RFP" as a logical choice.

AF has [hardly changed any prefs since v96](https://github.com/arkenfox/user.js/releases)

- 97
   - new: 1 x speculate connect
   - made inactive: x1
- 98
   - cosmetic changes only
- 99
   - deprecated: x1
- 100
   - new: 1 x download prompt + 1 x inactive
   - deprecated: x4
- 101
   - new: 1 x inactive
   - removed: x5
- 102/103
   - changes to do with cookies and sanitizing

That's it. Nothing sticks out that would affect speech in changes since Jan. Basically 2 new prefs, everything else is inactive or deprecated or removed (or to do with cookies/site-data/sanitizing on close).

**Comment by behradJ** [comment]
I finally found the prefs that causes this problem and that was:
`media.autoplay.blocking_policy` which was set to `2` and I change it to `0`.
Now with my understanding, it is not a prefs about privacy right? 
also, thanks for your helping, I did what you said for testing.

**Comment by Thorin-Oakenpants** [comment]
yeah, this isn't really a privacy pref - i'll reopen asa reminder to myself to maybe move 2030 + 2031 them to optional or personal
