### ISSUE TITLE
Need help to get "Read Aloud" back to work.(re-opening #1520 issue)

### ISSUE THREAD

**Issue by behradJ** [arkenfox/user.js#1522]
[console-export-2022-8-6_15-31-27.txt](https://github.com/arkenfox/user.js/files/9275342/console-export-2022-8-6_15-31-27.txt)
(I am reopening [this](https://github.com/arkenfox/user.js/issues/1520) issue as Thorin-Oakenpants tell me to do so.)
Hi,
I do really sorry for being too late to answer.
I don't want to disable RFP to get it to work, but even when I toggle that, it doesn't work either.
I should mention that I am using this Arkenfox user.js for about a year and this extension was working fine until about 2-3 months ago.
I did what GlassGruber asked me to do and the error in browser console is this:
`Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved defaults.js:1031 bgPageInvoke moz-extension://484c95f2-f41b-4b1d-bcfe-077453a839fa/js/defaults.js:1031 `

Update:
Now, I noticed that it wasn't the error we are looking for, and it was an error of me clicking on the browser console window while the extension window was open.
So now it does not output any error on the Browser Console which I open that by Ctrl + Shift + J.

Update #2:
I removed "Read Aloud" from toolbar menu and add it to the main toolbar and now on opening the window I get this in browser console:
`Cannot send function call result: other side closed connection (call data: ({path:"windows.create", args:[{allowScriptsToClose:null, cookieStoreId:null, focused:true, height:null, incognito:null, left:null, state:null, tabId:null, titlePreface:null, top:null, type:"popup", url:"moz-extension://484c95f2-f41b-4b1d-bcfe-077453a839fa/popup.html?tab=1", width:null}]}))
`

**Comment by Thorin-Oakenpants** [comment]
WTF .. use the existing issue
