### ISSUE TITLE
privacy.clearOnShutdown.cookies in user-overrides.js will not change after updating

### ISSUE THREAD

**Issue by candroid-man** [arkenfox/user.js#1523]
This is my current `user-overrides.js` file:

```
// Overrides

user_pref("keyword.enabled", true);
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("signon.rememberSignons", false);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("browser.newtabpage.enabled", true);
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", about:home);
```
As you can see, `user_pref("privacy.clearOnShutdown.cookies", false);` is in there, yet when I restart Firefox it changes back.

EndeavourOS Linux (using Arkenfox CLI tool), Firefox version 103.0.1

**Comment by Thorin-Oakenpants** [comment]
If you are on FF103 then the current live master user.js is v102, which still has

```
user_pref("network.cookie.lifetimePolicy", 2);
```

In v103 which I will _probably_ push in a few days, this pref is moved to deprecated, because it does nothing except _MIGRATE_ users' prefs - one of which is to force cookies to be cleared

So add this to your overrides until you update to AF v103 (when I push it)

```
// my overrides: FF103 needs this to stop migration code on sanitizing prefs
// ^ i.e with AF v102 .. that PANTS chick needs to get her fucking shit together and do a v103 PR
user_pref("network.cookie.lifetimePolicy", 0);
```

**Comment by candroid-man** [comment]
Thank you SO MUCH!

**Comment by Thorin-Oakenpants** [comment]
also, FYI: the pref was officially removed in FF104 .. which is 2 weeks away :)

**Comment by Thorin-Oakenpants** [comment]
we support ESR + stable ... FF103 is history, changing labels
