### ISSUE TITLE
FF103 Strict privacy.query_stripping.enabled.pbmode = false

### ISSUE THREAD

**Issue by BillyJoeJimBob** [arkenfox/user.js#1524]
In FF 103.0.2 strict mode "privacy.query_stripping.enabled" is set to true only in regular windows, not private as follows: 

user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", false);

I couldn't find any mention of this in AF102 or the comments, should it be switched to true in pbmode or ignored for now?
Thank you.

**Comment by fxbrit** [comment]
query stripping will be enabled in PBmode as part of ETP strict starting with FF104, see [1778457](https://bugzilla.mozilla.org/show_bug.cgi?id=1778457). I think we can ignore since users should be using Legitimate URL Shortener in uBO, which also works in private tabs.

**Comment by Thorin-Oakenpants** [comment]
we don't start in pbmode and we do not care about those prefs when "all window" prefs exist, and the query stripping one is part of ETP strict
