### ISSUE TITLE
container group

### ISSUE THREAD

**Issue by imxade** [arkenfox/user.js#1525]
allow hiding tabs under same container like https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ does

**Comment by rusty-snake** [comment]
If you explain how we should do it.

This is a [user.js](https://github.com/arkenfox/user.js/wiki/2.1-User.js). It is a configuration template. It's not a extension. It can only flip prefs in firefox to enabled/disable certain features/behaviour.

If you want to hide container tab groups, the go and use MAC.
