### ISSUE TITLE
Cookies clearing after Firefox restarts even with user-overrides.js file

### ISSUE THREAD

**Issue by candroid-man** [arkenfox/user.js#1532]
Yesterday I updated my Arkenfox configuration to the latest version, and ever since then cookies have been clearing every time I restart Firefox. However, I used the same user-overrides.js file before and after the update.

```
user_pref("keyword.enabled", true);
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("signon.rememberSignons", false);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("network.cookie.lifetimePolicy", 0);
user_pref("browser.newtabpage.enabled", true);
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", about:home);
user_pref("services.sync.prefs.sync-seen.services.sync.prefs.sync.privacy.clearOnShutdown.cookies", false);
```
None of the checkboxes within settings regarding the deletion of cookies are checked, so I'm really confused as to what is causing this. Is there a new pref that was added in a Firefox update?

**Comment by rusty-snake** [comment]
Read the changelog #1526.

Short: Use exceptions or set `privacy.clearOnShutdown.cookies=false`.

**Comment by rusty-snake** [comment]
> user_pref("browser.startup.homepage", about:home);

syntax error

What are the values of the relevant prefs on `about:config`?

**Comment by candroid-man** [comment]
![image](https://user-images.githubusercontent.com/51019003/187539392-09defdb4-5fc2-4557-9ad7-ce367efabdc8.png)

**Comment by rusty-snake** [comment]
How did you checked the cookie clearing? Just by noticing that you are logged out somewhere or by looking at it on `about:perferences`?

**Comment by candroid-man** [comment]
Both

**Comment by candroid-man** [comment]
Also, may I ask what syntax error is there is `user_pref("browser.startup.homepage", about:home);`? Because it doesn't work, but I couldn't figure it out

**Comment by rusty-snake** [comment]
The value must be a boolean, an integer vor a string. `about:home` is none oft them.

**Comment by candroid-man** [comment]
Update: It seems this issue is only affecting certain websites. ProtonMail and Piped don't get cookies saved, but sites like Reddit and GitHub do. These are just the sites I have tested, I really have no idea what could be causing this

**Comment by rusty-snake** [comment]
Read my first comment again.

---

You said that you checked on `about:preferences` that cookies got deleted. Did you really done this? And all cookies got deleted? Apparently not.

**Comment by rusty-snake** [comment]
GitHub handles "cross session login" with "normal" cookies.
ProtonMail handles "cross session login" with localStorage and uses session cookies for in session authentication.

---

And read the section in the user.js. Just search for `cookie` in the user.js and find it.

https://github.com/arkenfox/user.js/blob/06bfef8fd155fdf62e409c30cd1d68572f0c8b41/user.js#L777-L787

**Comment by candroid-man** [comment]
Adding `user_pref("privacy.clearOnShutdown.offlineApps", true);` to my `user-overrides.js` file resolved the issue, thank you for the help!

**Comment by Thorin-Oakenpants** [comment]
It's ALREADY true. So many conflicting comments about what is or was done, set, changed, confirmed

https://github.com/arkenfox/user.js/blob/0dba33688fe468aca9b58c60910201afb3b89f60/user.js#L787
