### ISSUE TITLE
Windows MS Shell Dlg font

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1533]
Background
- https://docs.microsoft.com/en-us/windows/win32/intl/using-ms-shell-dlg-and-ms-shell-dlg-2
> The fonts generated by MS Shell Dlg and MS Shell Dlg 2 are different on different Windows versions

but windows 7

> MS Shell Dlg 2 simply uses the Tahoma font regardless of language

---

I am interested, with RFP disabled, what font is shown when you test `MS Shell Dlg` and `MS Shell Dlg \32`
- win 8/8.1/10/11
- and what language is the OS: super keen if someone has CJK or any other non-Latin/Western language

STR
- load test: https://arkenfox.github.io/TZP/tests/fontdebug.html
- what does the `FONT` in the middle say: e.g. it should say `[DETECTED]` in green
- right click the `ImLwWil` sample text and select `Inspect`
- on the third pane, expand it's width or click the dropdown arrow and select `Fonts`
- what does it say is being used

example
![example](https://user-images.githubusercontent.com/16656956/187853718-49b12473-4e6a-4356-9303-38caaab39d98.png)

Windows 7 english
- `MS Shell Dlg` = Microsoft Sans Serif
- `MS Shell Dlg \32` = Tahoma

TIA ❤️

**Comment by crssi** [comment]
Windows 11, Version 21H2 (OS Build 22000.856)... everything is Arial.

Cheers

**Comment by MagicalDrizzle** [comment]
W10 22H2 English:
- `MS Shell Dlg` = Microsoft Sans Serif
- `MS Shell Dlg \32` = Tahoma

**Comment by crssi** [comment]
Plain vanilla profile also says `Arial`... that is on Windows 11, Version 21H2 (OS Build 22000.856).

Cheers

**Comment by Thorin-Oakenpants** [comment]
crssi, is your OS an english (or french/german/western-latin) setup? or something like greek or CJK or klingon etc?

**Comment by crssi** [comment]
Installation media is `en-US`.

![image](https://user-images.githubusercontent.com/17024151/188214954-1af37d6b-fda1-4738-8ab9-db5c463544f5.png)

**Comment by Thorin-Oakenpants** [comment]
Interesting, because MagicalDrizzle has Microsoft Sans Serif + Tahoma - https://github.com/arkenfox/user.js/issues/1533#issuecomment-1234225719 with W11 21H2 English

**Comment by MagicalDrizzle** [comment]
what would you want to know more about my and their setup?
<img width="540" alt="Untitled" src="https://user-images.githubusercontent.com/49761211/188231345-b0fbdded-3f59-4cfb-8f11-baf9eadb4d72.png">

**Comment by Thorin-Oakenpants** [comment]
^ nothing really: just trying to work out if what MS said was true. Detecting windows releases (e.g. say 7 v 8 v 10 v11) is probably (definitely for some) going to manifest anyway in what fonts are available (e.g. win 11 ships with extra fonts, win7 has fonts that aren't shipped in 10/11, etc)

What I was wondering was if it changed for any other reason, such as regional OS settings/ UI theming. And we have an answer. It's something I can follow up on with Tor Project: and IDK if anything is feasible

Note that the font name is obscured from JS, but we can infer it by matching other font sizes: but we don't need to do that: the entropy is in the measurement.

How this plays out on other platforms other than windows is unknown. On android and linux the font name is shown. On mac it is apple-system - IDK if that apple-system one changes either since 10.12 = it's san franscisco, or .SF something, but for sure, if it changes in future, it gets picked up. I would think mac is pretty locked down, but who knows if alias points to the same for all regional setups, or if measurements change,
