### ISSUE TITLE
Cookies are not cleared on shutdown

### ISSUE THREAD

**Issue by Panja0** [arkenfox/user.js#1534]
I'm using FF 104.0.1 (Windows x64) and user.js v103

My cookies are not cleared on shutdown. Though I have the recommended settings applied as far as I can see.

<img width="584" alt="Screenshot - 2022-09-01 at 10 56 59" src="https://user-images.githubusercontent.com/12939350/187893367-e2bf6130-9b92-46e5-a202-e308e28758aa.png">

Any help is appreciated.

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/06bfef8fd155fdf62e409c30cd1d68572f0c8b41/user.js#L762

> ***if 2810 is true***

https://github.com/arkenfox/user.js/blob/06bfef8fd155fdf62e409c30cd1d68572f0c8b41/user.js#L757-L759

Did you set this to `false` in your overrides?

**Comment by rusty-snake** [comment]
How did you tested?

**Comment by Panja0** [comment]
@rusty-snake 
Lifesaver!

By stupid mistake I did not notice the `user_pref("privacy.sanitize.sanitizeOnShutdown", false); ` in my overrides.
Working now, after I removed it! Many thanks
