### ISSUE TITLE
Making an automatic connection to "shavar.services.mozilla.org"

### ISSUE THREAD

**Issue by Albusvesuvius** [arkenfox/user.js#1536]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Latest
  - Steps to Reproduce (STR): Start the browser
  - Expected result: Not make an automatic connection
  - Actual result: Browser makes an automatic connection to shavar.services.mozilla.org
  - Console errors and warnings: none
  - Anything else you deem worth mentioning:

---

Hey, I'm trying to find out which setting is responsible for my browser to make an automatic connection to shavar.services.mozilla.org.
I thought it would be about webcompat options but I've already turned all 3 of them off:

```
user_pref("privacy.antitracking.enableWebcompat", false);
user_pref("extensions.webcompat.enable_shims", false);
user_pref("extensions.webcompat-reporter.enabled", false);
```

What am I missing here?

**Comment by rusty-snake** [comment]
Where is the issue with this connection?

**Comment by g-2-s** [comment]
From the second result on DDG:
https://support.mozilla.org/en-US/questions/1251590
`shavar.services.mozilla.com is used to update the list of trackers that are getting blocked when tracking protection is turned on`
I don't think you would want to disable this.
