### ISSUE TITLE
Possibly breaking uBlock Origin's functionality, or vice versa?

### ISSUE THREAD

**Issue by ADHDefy** [arkenfox/user.js#1538]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: **Firefox 104.0.1 (64-bit), Fedora 36**
  
  - Steps to Reproduce (STR):
    **1. Install Firefox on Linux host**
    **2. Apply Arkenfox user.js with included overrides (attached at bottom of post)**
    **3. Install uBlock Origin and import settings file (attached at bottom of post)**
    **4. Visit https://www.reddit.com and/or https://www.ultimate-guitar.com/**
    **5. Block any element on the page. Once it disappears, refresh the page and see that the element has returned.**
    **6. Create a new Firefox profile *without* Arkenfox user.js. Repeat steps 3 - 5, and find that uBlock Origin with identical settings will function as intended on a "vanilla" profile.**

  - Expected result: **To not see any side bar ads, and for custom filters to be filtered.**
  
  - Actual result:  **Seeing some ads (not all), and custom filters not applying/persisting.**

![reddit_ads_broken](https://user-images.githubusercontent.com/105878544/189503761-5d8e862a-3eb4-4c09-97e0-ca83decebd2d.png)

![reddit_filters_broken](https://user-images.githubusercontent.com/105878544/189503764-6249bada-f75e-48ab-baea-8a65095590f7.png)

![ug_filters_broken](https://user-images.githubusercontent.com/105878544/189503767-402f41c1-d2a7-49be-9deb-7214e5225786.png)

  - Console errors and warnings:

![console_output](https://user-images.githubusercontent.com/105878544/189503745-1c0ab7b4-2306-4a00-ae56-cf155d58ed53.png)

  - Anything else you deem worth mentioning: **In the screenshots, you will see that I have other add-ons installed. I have gone through all of the steps with all add-ons disabled (except uBlock Origin, obv) and found that the results are the same regardless.**

---

[user-overrides.zip](https://github.com/arkenfox/user.js/files/9541457/user-overrides.zip)
[my-ublock-backup_2022-09-10_15.01.17.txt](https://github.com/arkenfox/user.js/files/9541460/my-ublock-backup_2022-09-10_15.01.17.txt)

```js
/*** MY OVERRIDES ***/
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", "https://search.rhscze.cf/");

user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.allowOverride", false);

user_pref("dom.security.https_only_mode_send_http_background_request", false);
user_pref("network.http.referer.XOriginPolicy", 0);
user_pref("privacy.userContext.enabled", false);
user_pref("privacy.userContext.ui.enabled", false);
user_pref("dom.disable_open_during_load", false);
user_pref("privacy.resistFingerprinting.letterboxing", false); // [HIDDEN PREF]
user_pref("signon.rememberSignons", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false); // [FF78+]
user_pref("extensions.pocket.enabled", false); // Pocket Account [FF46+]
user_pref("extensions.screenshots.disabled", true); // [FF55+]
user_pref("browser.search.widget.inNavBar", true);                         
user_pref("dom.battery.enabled", false);    

```

**Comment by rusty-snake** [comment]
Is this reproducible with plain arkenfox? Your overrides contain prefs like `dom.battery.enabled` which has no privacy problem for years.

Is this reproducible without all the non-default uB lists?

**Comment by rusty-snake** [comment]
Just tried something:
1. Create a elem-hide rules for something on a page.
2. Add a elem-hide exception (`#@#`) in My Filters for the rule created in 1.
3. Open element picker and create the same rule as in 1
   - New rules gets applied and element is hidden
4. Reload page
   - Exception has higher precedence and element is shown

Given your amount of 3p filterlists this is a realistic cause for the behaviour you see.

What does the uB logger show?

**Comment by rusty-snake** [comment]
Does it have to be an elem-hide rule or can it also be a network rules?

**Comment by rusty-snake** [comment]
Only extension can use this API so since Firefox 51(?).
