### ISSUE TITLE
New NoScript Security Feature: Worth Adding to "Recommended" in Wiki?

### ISSUE THREAD

**Issue by Fjpqeign5713** [arkenfox/user.js#1539]
NoScript recently added a new security feature called "Cross-tab Identity Leak Protection" ( https://nitter.net/ma1/status/1557751019945299969#m ), and I was wondering if this feature, alongside the other security features like anti-xss protection, would make NoScript worth being labeled underneath the "Recommended" section of Extensions in the wiki. 

The script-blocking feature of NoScript can be disabled while still leaving the other features enabled, so this can be done to avoid redundancy with uBlock Origin's blocking mode. Maybe for some threat models, the trade-off of having a more unique fingerprint for added security might be worth it.

**Comment by Thorin-Oakenpants** [comment]
99.99999999999999999999999% of which are false positives
