### ISSUE TITLE
changelog: v104

### ISSUE THREAD

**Issue by fxbrit** [arkenfox/user.js#1540]
date: 11-September-2022

[FF104 release notes](https://www.mozilla.org/en-US/firefox/104.0/releasenotes/)
[FF104 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/104)
[FF104 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2022-33/)

**CHANGELOG**
- [all changes](https://github.com/arkenfox/user.js/compare/103.0...104.0)
- [ToDo: diffs FF103-FF104](https://github.com/arkenfox/user.js/issues/1530)
- v104 PR is at https://github.com/arkenfox/user.js/pull/1527

***

- new in user.js v104, see https://github.com/arkenfox/user.js/issues/1530#issuecomment-1242850653

```js
user_pref("privacy.partition.always_partition_third_party_non_cookie_storage", true);
```

- moved to `5000: OPTIONAL OPSEC`

```js
// user_pref("extensions.formautofill.addresses.enabled", false); // [FF55+]
// user_pref("extensions.formautofill.creditCards.enabled", false); // [FF56+]
// user_pref("extensions.formautofill.heuristics.enabled", false); // [FF55+]
```

- moved to `5500: OPTIONAL HARDENING`, see https://github.com/arkenfox/user.js/issues/1529

```js
// user_pref("gfx.font_rendering.opentype_svg.enabled", false);
```

- moved to `6000: DON'T TOUCH`, see https://github.com/arkenfox/user.js/pull/1527/commits/ff8d63f7e428462e0864ca1c20740e8631f96437 and https://github.com/arkenfox/user.js/pull/1527/commits/d040b95ed293548cbdff13c0c10367807ac0ec30

```js
// user_pref("extensions.formautofill.available", "");
// user_pref("extensions.formautofill.addresses.supported", "");
// user_pref("extensions.formautofill.creditCards.available", "");
// user_pref("extensions.formautofill.creditCards.supported", "");
```

***

⭐ your friendly reminder to run prefsCleaner

<img src="https://user-images.githubusercontent.com/16656956/150662274-33812185-e970-47e7-899e-72d18cc83f06.jpg">

***

No stats, no ALL HAIL PANTS and not shiny as usual, blame it on me.

**Comment by rusty-snake** [comment]
First changelog by @fxbrit :tada: :1st_place_medal:

**Comment by Thorin-Oakenpants** [comment]
### STATS

```
 STATS v104: up to and including section 4500, minus the parrots
 ==========
    total: 201
 inactive:  42
           ---
   active: 159
  default:  22 (at least)
      n/a:   2 (of the four prefs in 0204, at most only two will apply)
           ---
  flipped: 135 (at most)
```

**Comment by GlassGruber** [comment]
> no ALL HAIL PANTS and not shiny as usual

Thanks fxbrit! 
Someone is sad though...

![image](https://user-images.githubusercontent.com/1172428/192128661-98f37edc-61d9-40e3-9c73-3578e4677beb.png)
