### ISSUE TITLE
Whitelist cookies in a certain container

### ISSUE THREAD

**Issue by 1Naim** [arkenfox/user.js#1543]
Is it possible to only clear cookies from e.g. google.com on close for the main container but still keep cookies from the same site in another container

**Comment by rusty-snake** [comment]
https://codeberg.org/rusty-snake/firefox-config/src/commit/ea079491d22113843d61b3d93455518cdd00abad/assets/user-overrides.js#L25-L26

**Comment by 1Naim** [comment]
I've flipped this switch, how do I go about adding the whitelist now? Do I add [sitename]^userContext=[container] in the cookie exceptions or simply by allowing cookies in ctrl + i prompt it'll whitelist it only it that container?

**Comment by Thorin-Oakenpants** [comment]
duplicate #1548 (yes, I know this one came first, but the other one is more informative)
