### ISSUE TITLE
friendlycaptcha not working with Arkenfox

### ISSUE THREAD

**Issue by 34candos** [arkenfox/user.js#1545]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- X I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: 105, macOS ventura
  - Steps to Reproduce (STR): go to https://friendlycaptcha.com/demo
  - Expected result: the friendlycaptcha should read "your are human"
  - Actual result: the friendlycaptcha reads "Verification failed"
  - Console errors and warnings: four errors all reading "Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://friendlycaptcha.com/[long token] (“worker-src”)."
  - Anything else you deem worth mentioning: tested with non-Arkenfox FF 105 on the same machine with RFP enabled and it worked normally.

---

**Comment by fxbrit** [comment]
worsforme, I'm also on macOS (Monterey tho).

have you tried in a clean profile with arkenfox? are you using any extension or override?

**Comment by Thorin-Oakenpants** [comment]
worksforme .. windows

**Comment by Thorin-Oakenpants** [comment]
`worker`-src ... you are probably blocking workers (either directly or by blocking cookies)

**Comment by 34candos** [comment]
> `worker`-src ... you are probably blocking workers (either directly or by blocking cookies)

Any idea how I would do that? Doesn't seem like something that either extension would do. 

I also added my user-overrides to the clean profile with Arkenfox and it works -- so the issue should not come from the overrides either. 

ETP is set to strict, so cookies should not be all blocked.

Anything I'm missing?

**Comment by Thorin-Oakenpants** [comment]
I was just guessing. You said you had uBO - and I though there was a global switch for blocking service workers (but now I think I'm confused with uMatrix). In FF there is of course a setting to block all cookies by default (which we don't do) and that also affects all other storage. Even if you allowed the cookie but `only for session` (which you can still do vis Permission tab - `Ctrl-I` ) this can still affect some types of workers. But I don't know what your setup is, I was just guessing

> ETP is set to strict, so cookies should not be all blocked.

correct

> I also added my user-overrides to the clean profile with Arkenfox and it works 

Cool. I can't troubleshoot for you. Must be your extensions ... uBO seems likely, check it's console

**Comment by 34candos** [comment]
Thanks for the reply. Will check later and keep posted.

**Comment by Thorin-Oakenpants** [comment]
i can't reproduce, I don't even see a worker-src in the logger. It's easy to tell if uBO is the culprit, disable it for that site

**Comment by 34candos** [comment]
Ok, massive facepalm. Of course turning is off is not the same as allowing all domains, and of course turning it off fixed it. Case closed.
