### ISSUE TITLE
Built-in screenshot function returns wrong areas

### ISSUE THREAD

**Issue by austinhuang0131** [arkenfox/user.js#1546]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO

  - Browser version & OS: 104.0.2 macOS
  - Steps to Reproduce (STR): Use the screenshot button built into Firefox. Select any area and it'll return with some distortion. In this example say I click "save full page".
  - Expected result: It should save the full page.
  - Actual result: ![](https://user-images.githubusercontent.com/16656689/190828861-8ec77df2-1c95-45ae-a98a-e5136538f7ff.png)
  - Console errors and warnings: None.
  - Anything else you deem worth mentioning: Probably something RFP?

---

**Comment by rusty-snake** [comment]
WFM.

Fedora 36.

> Anything else you deem worth mentioning: Probably something RFP?

Try it.

Console 

> errors and warnings: None.

Did you checked the Browser console?

**Comment by austinhuang0131** [comment]
> Try it.

It was indeed 4501.

> Did you checked the Browser console?

Yes.

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1780910#c6
