### ISSUE TITLE
1Password Autofill Not Working

### ISSUE THREAD

**Issue by PaulDoesDev** [arkenfox/user.js#1547]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 104.0.2 - macOS 12.6
  - Steps to Reproduce (STR):
  	- Fresh profile
  	- Apply arkenfox user.js
  	- Download 1Password Firefox addon
  	- Go to a website login page
  	-  Try to invoke autofill shortcut from Mac app (CMD + /)
  - Expected result:
  	- Login info filled out
  - Actual result:
  	- 1Password quick access window opens like it doesn't know a browser is there
  	- Trying to manually choose a login to autofill doesn't work
  - Console errors and warnings: N/A
  - Anything else you deem worth mentioning:
  	- Set up arkenfox last night (disabled RFP) and noticed this had stopped working. Wiped everything and started from scratch to confirm it was arkenfox that caused it. Worked on a fresh Firefox profile, installed arkenfox, stopped working.
  	- I also have the same issue with LibreWolf, so I assume it's some privacy related setting that stops the 1Password Mac app from being able to interface with the web page/it's extension

Any help would be greatly appreciated
---

**Comment by PaulDoesDev** [comment]
Tried with

```
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("privacy.resistFingerprinting.block_mozAddonManager", false);
```

again just now, but no luck.

**Comment by Thorin-Oakenpants** [comment]
> Worked on a fresh Firefox profile, installed arkenfox, stopped working.

Cool. So you know how to use a test profile

Troubleshoot it. Create new test profile. Add half the user.js, test ... based on the result you now know which half the culprit is. Rinse and repeat (or if the test worked just add the next half of what's left)

using a binary approach will very quickly narrow it down - https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-manual

**Comment by PaulDoesDev** [comment]
Sorry, I forgot to go back to that after I confirmed arkenfox was the issue.

Did that and figured it out.

It was
```
/* 2601: prevent accessibility services from accessing your browser [RESTART]
 * [1] https://support.mozilla.org/kb/accessibility-services ***/
user_pref("accessibility.force_disabled", 1);
```
for anyone having the same issue in the future

**Comment by Thorin-Oakenpants** [comment]
That sounds like something the extension developer should fix
