### ISSUE TITLE
Gitlab login page hanging on load

### ISSUE THREAD

**Issue by pterocles** [arkenfox/user.js#1550]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox Beta 106.0b3 (64-bit), Windows 10 Education
  - Steps to Reproduce (STR): 
    - Arkenfox/user.js 11 September 2022, v104
    - Load https://gitlab.com/users/sign_in
    - Page hangs
  - Expected result:
    - Page should load and you should be able to proceed to login
  - Actual result:
    - Page doesn't completely load and hangs forever
  - Console errors and warnings:
![](https://i.ibb.co/dL5pNyX/1-fail.png)
![](https://i.ibb.co/dM8PtwH/2-fail.png)
  - Anything else you deem worth mentioning:
    - I am using the console and seeing these on every load of the login page so I can only assume this is the issue.

---

**Comment by rusty-snake** [comment]
GitLab login Bad trouble in the past with RFP more than once. Die you try to disable it?

**Comment by pterocles** [comment]
Disabling RFP works, but I thought this was fixed in a previous issue: https://github.com/arkenfox/user.js/issues/1482 

I might be mistaken but I think they might be related (not dupe).

**Comment by fxbrit** [comment]
worksforme, Nightly 107 + AF + uBO. are you using any extension? did you try without a VPN?

**Comment by rusty-snake** [comment]
WFM too if uB disabled.

Firefox 104.0.2, AF, Fedora

**Comment by rusty-snake** [comment]
You where blocking 1p scripts?

**Comment by pterocles** [comment]
> You were blocking 1p scripts?

The EasyList was blocking/filtering that specifically. I allowed it after seeing it in console.
