### ISSUE TITLE
`geo.provider.network.url` in user.js has same default as latest firefox esr

### ISSUE THREAD

**Issue by a1346054** [arkenfox/user.js#1552]
Why is

```javascript
user_pref("geo.provider.network.url", "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%");
```

set in

https://github.com/arkenfox/user.js/blob/3f09afdee07c5aea33f6dc4194e1425d6400a0d7/user.js#L117

when that is already the default value in Firefox 102esr? Is that some defense-in-depth mechanism, or is it simply a holdout from some different value it had previously?

**Comment by a1346054** [comment]
Nevermind, I discovered that windows version of firefox has a different default than linux.

**Comment by Thorin-Oakenpants** [comment]
also on windows it is still `https://www.googleapis.com/geolocation/v1/geolocate?key=%GOOGLE_LOCATION_SERVICE_API_KEY%`

**Comment by rusty-snake** [comment]
Did you tested this with a Firefox build from Mozilla or your distro? Because a lot of distros have such patches.
