### ISSUE TITLE
How do i change the adressbar back to normal?

### ISSUE THREAD

**Issue by Nibenee** [arkenfox/user.js#1553]
With the user.js configs i can only use it to type urls, but not to do searchs. I heard it is so the urls wont leak into search engines, but i dont use urls that much, so it is useless to me. It is also very annoying to have to type again what i just searched because it was in the wrong bar. I did not find anything saying how to change that back to normal, only a reddit post, but it did not work.

**Comment by Thorin-Oakenpants** [comment]
marking as invalid - use the correct troubleshooting issue, which would have told you to read the wiki, look for setup tags in the user.js, search the repo and more

for example: https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common] it's right there listed in the eight most COMMON prefs
