### ISSUE TITLE
stine.uni-hamburg.de shows warning on padlock [solved: 1270 warns you because you enabled 1201]

### ISSUE THREAD

**Issue by starraiderx** [arkenfox/user.js#1554]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Win 11. FF105 (version independent)
  - Steps to Reproduce (STR): visit stine.uni-hamburg.de
  - Expected result: TLS 1.2 Encrpytion Verified By: Verein zur Foerderung eines Deutschen Forschungsnetzes e.V.
  - Actual result: Broken Encrpytion Not verified
  - Console errors and warnings: Broken encryption  (TLS_ECDHE_RSA_WITH_AES_256_GCMSHA384, 256 Bit keys, TLS 1.2). 
  Strict-Transport-Security: The site specified a header that did not include a ‘max-age’ directive.
  - Anything else you deem worth mentioning: Website does not work when 1201 is enabled. Does not happen with unmodified chrome or FF

![image](https://user-images.githubusercontent.com/33199500/192652475-be745f75-dcdf-4993-9514-f434a9d740d0.png)
It appears that there is a second Strict-Transport-Security header with a max age of 0. Still curious why arkenfox FF flags the site as insecure while default FF and chromium browsers dont
---

**Comment by Thorin-Oakenpants** [comment]
I know this is not what you're aksing about: just reiterating ... 1201 is required to be false - that's a separate issue and entirely up to you if you want to flip that or not

https://github.com/arkenfox/user.js/blob/3f09afdee07c5aea33f6dc4194e1425d6400a0d7/user.js#L446

---

so testing with 1201 at false, site: https://stine.uni-hamburg.de/

nightly left, my AF'ed FF on the right

![weird](https://user-images.githubusercontent.com/16656956/192662037-f3a9a933-cbb4-41c6-8e84-944f96bdd711.png)

The only diff is one is verified and one isn't. Bizarre

@fxbrit

**Comment by Thorin-Oakenpants** [comment]
AF is doing it's job and warning you that unsafe_negotiations is broken, which is why you needed to flip 1201 in the first place

```
/* 1270: display warning on the padlock for "broken security" (if 1201 is false)
 * Bug: warning padlock not indicated for subresources on a secure page! [2]
 * [1] https://wiki.mozilla.org/Security:Renegotiation
 * [2] https://bugzilla.mozilla.org/1353705 ***/
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
```

[STATS] SSL Labs (Sept 2021) reports over 99.3% of top sites have secure renegotiation - https://www.ssllabs.com/ssl-pulse/
