### ISSUE TITLE
Remove browser.ssl_override_behavior

### ISSUE THREAD

**Issue by gmvk** [arkenfox/user.js#1560]
It's been broken for several years now.

**Comment by Thorin-Oakenpants** [comment]
it looks like a dead pref: https://searchfox.org/mozilla-central/search?q=ssl_override&path=&case=false&regexp=false

**Comment by Thorin-Oakenpants** [comment]
what the pref did - https://bugzilla.mozilla.org/show_bug.cgi?id=413861#c1

**Comment by Thorin-Oakenpants** [comment]
code removed in FF68
- https://bugzilla.mozilla.org/show_bug.cgi?id=1530348
- https://hg.mozilla.org/mozilla-central/rev/46b2369b332c

**Comment by gmvk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1773092

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/pull/1558/commits/e93bff5c038b7c44505c94a1b7cc68d326e974f8

**Comment by mvk-foo** [comment]
This pref can be replaced by `security.certerror.hideAddException`
