### ISSUE TITLE
imges are stripped [invalid: RTFM - it's canvas]

### ISSUE THREAD

**Issue by firefoxlover** [arkenfox/user.js#1561]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Mull / Firefox newest Ubuntu
  - Steps to Reproduce (STR): open a pdf and open the slide view
  - Expected result: Canvas loads for pdf.js only
  - Actual result: Pages are shown as the striped images
  - Console errors and warnings:
  - Anything else you deem worth mentioning: A possible selfmade modification is enough, as pdf.js is said to be a security risk (if this risk can be avoided by stopping the loading of external contents or scripts, that would be even better)

---

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L857-L858

https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D#-rfp
