### ISSUE TITLE
discussion: personal section cleanup

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1563]
IN the current v106 PR, this section is 73 lines total and 46 prefs (or which 4 are active, because those four make sense and everyone finds those four things annoying). It's getting bloated. And I expect I will be moving a few more items there

This is an issue. The more inactive items in here that we add, the more items that get reset to default with prefsCleaner. Which is not an issue if someone wants to change from default and they add an override: so they have a record and it doesn't get accidentally reverted by clicking around in settings where those cards can have fucking wide click areas to toggle shit, and also makes it easier for them to migrate. This is the way.

But what about users who, for example, via the UI change an option (unaware that there is an inactive pref in the user.js), e.g. they customize and then right click on the downloads button and select auto-hide. Next startup it has reverted back. Or they disable the default browser check on startup (which I just moved in the v106 PR to personal) .. etc. Granted not many of these 46 items have a UI.

Now I could just remove some of them, that seem fairly useless, and/or have a UI: like default browser check, the non-master milestone prefs, the full-screen prefs, but then after that it starts becoming subjective, and there's some neat info in there. And it doesn't solve the issue of the section potentially growing.

So what I propose is to move it all to a sticky issue and link to it. A locked issue. If anyone wants anything added they can ask in a new issue, and the size of the personal prefs length is not an issue - although this is NOT the purpose of this repo, and any additions would have to be fucking great ones. I'm not going to maintain a list of hundreds of prefs.

The only issue is what to do with the four active ones: and that's easy, we keep them in that section

So something like this
```js
/*** [SECTION 9000]: PERSONAL
   Over time we have collected a lot of non-project related but useful prefs, listed at [1].
   If any interest you, add them to your overrides. The four active prefs below are universally
   agreed upon as really annoying, so we've added them here for you to save you the trouble

   [1] https://github.com/arkenfox/user.js/issues/ISSUENUMBER
***/
user_pref("_user.js.parrot", "9000 syntax error: the parrot's cashed in 'is chips!");
/* ANNOYANCES ***/
user_pref("browser.messaging-system.whatsNewPanel.enabled", false); // What's New toolbar icon
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
   // [SETTING] General>Browsing>Recommend extensions as you browse
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
   // [SETTING] General>Browsing>Recommend features as you browse
user_pref("browser.startup.homepage_override.mstone", "ignore"); // welcome notices
```

Class, discuss! I'm 100% sold on this, so if you have objections, speak up

**Comment by Thorin-Oakenpants** [comment]
DONE, but feel free to discuss it

**Comment by fxbrit** [comment]
I like this 🥇

**Comment by Thorin-Oakenpants** [comment]
> I like this 🥇

![allhail](https://user-images.githubusercontent.com/16656956/196025526-b03ccd8f-d621-47d8-98aa-0a9315d64c63.png)

**Comment by ExceptionGit** [comment]
It is not clear to me what problem these changes solved: 
- [-] subjective/UI prefs remained in the user.js
- [+] user.js has become 70 lines smaller
- [-] but 70 lines/prefs have moved to another place #1564
- [-] you still need to monitor the changes in these prefs

I use most of the prefs from personal section and use git+custom script to update user.js. Now I need to use github api and new script with pref parser to update this section or update it all manually.

Most users will just copy the prefs and never check #1564 again.

**Comment by Thorin-Oakenpants** [comment]
> It is not clear to me what problem these changes solved

read OP then. It removes (most) non-project related prefs. It reduces complexity/length and walls of text (that section wasn't the prettiest syntax around). It saves users getting settings reset each update (with prefsCleaner) and confusing them. It saves me maintenance.

> subjective/UI prefs remained in the user.js

they're not subjective, they're UNIVERSALLY HATED and we're saving end users time & effort, also we need something there to anchor the link

> but 70 lines/prefs have moved

good, because they have nothing to do with this repo's purpose

> you still need to monitor the changes in these prefs

no you don't. they virtually never change, and it's super unlikely to ever grow

> Most users will just copy the prefs and never check

that's on them - they are provided gratis as is - not my F problem

> I use most of the prefs from personal section and ...

you have to add them as overrides, there is no point listing them twice when they almost never change. If you want to scrape with scripts and compare this every release, you're wasting your time. Just add the overrides and be done with it. You'll know if an override stops working

I'm not going to maintain this as a copy in the user.js just so you can see what changes - they are NON-PROJECT related. I can always just delete #1564 and be done with it - it's not up to me to deal with everyone's pet wishlist of prefs

The beatings will continue until morale improves

**Comment by ExceptionGit** [comment]
> read OP then. It removes (most) non-project related prefs..

I understood it.

The rest contains many contradictions and I see no point in discussing.

**Comment by Thorin-Oakenpants** [comment]
you have made a very good point for me to remove #1564 completely

**Comment by Thorin-Oakenpants** [comment]
DONE - https://github.com/arkenfox/user.js/pull/1558/commits/34e7af0ebb3fa4c6c7cc2450459125de6049a623

It is exactly why I removed all of this because I am not supporting it. It is out of scope of the repo. But instead you (and no doubt others) will insist on me supporting it. So instead of linking to it, I will remove that. And #1564 is now unstickied, and closed as simply an archive of what we had - I _almost_ deleted it, it is of zero consequence and importance to me and this repo, and the information is still in previous commits/releases

Thank you for showing me that I can't rely on common sense and trying to accommodate everyone

**Comment by ExceptionGit** [comment]
First you deleted an personal section because it contained NON-PROJECT RELATED prefs https://github.com/arkenfox/user.js/commit/934bd24ac1f7901a141d577b7ed688d4329ce382 and now you have created a separate section for NON-PROJECT RELATED prefs https://github.com/arkenfox/user.js/commit/34e7af0ebb3fa4c6c7cc2450459125de6049a623.

I completely stopped seeing common sense and logic in your actions.

**Comment by Thorin-Oakenpants** [comment]
I don't have to justify myself to you, but I have - again and again. Go create your own repo if you don't like it

It has already been explained that the section was problematic. It has already been explained, multiple times, why those four prefs were kept, **_as exceptions to the "rule"_** (the "rule" being **_one that I made, not you_** - i.e we should not include prefs that have nothing to do with this repo's core purpose... wait for it...  unless it really adds value for our user-base) - this was explained above, it was explained when that section was made and everything was inactive _except_ those four, it was explained in the previous commit where it said "these four prefs are active because ... "

You are arguing over something that was never stated. No-where did I ever state that ALL personal prefs would be removed. You are arguing over semantics, and pointing out what is fucking obvious, that not all personal prefs were removed.

Now, because there is nothing else left, it is appropriated named "non-project related". What goes in there or not is up to me, not you. There is no contradiction here - I "wrote" the fucking "rule", not you.

If _you_ want to be a "purist" based on how _you_ perceive my logic, by not allowed any non-project related prefs, and have the section removed, go ahead

The archived issue is now going to be erased, thanks to you

**Comment by Thorin-Oakenpants** [comment]
The issue's title is "personal section **_cleanup_**", not "personal section **_removal_**"

If you persist in arguing this non-argument, more steps will be taken

**Comment by ExceptionGit** [comment]
> What goes in there or not is up to me, not you. There is no contradiction here - I "wrote" the fucking "rule", not you.

I didn't plan to argue and thinking that project was created/maintained for users, therefore I expressed my opinion earlier in this discussion. I received an even more detailed answer than I expected. You are right, I have no more questions and no more contradictions, thank you. It's just a pity that you chose the worst way to solve this problem in my opinion.

> The archived issue is now going to be erased, thanks to you

I am not responsible for your actions, so this does not make me feel guilty, anyway I got the answers and you can stop it. Thanks again for the details.

**Comment by Thorin-Oakenpants** [comment]
> I am not responsible for your actions, so this does not make me feel guilty

No, I am, and I am glad I did it. It was your actions that led me to remove it, so take the kudos, and good job too - one less thing for me to maintain. Once again, thanks for your insight.

**Comment by MagicalDrizzle** [comment]
my, my
I was wondering where 1273 and 2030 went
you really deleted it all huh
I think doing all this to spite one person isn't nice (not removing them from the user.js, rather deleting everything about them and the archived issue)...a lot of people use those personal prefs too
