### ISSUE TITLE
Iframe does not work

### ISSUE THREAD

**Issue by Bohmthedudevulture** [arkenfox/user.js#1565]
I am trying to access and use this page https://lyricstraining.com/de/play/berge/wir-sind-frei, although I can access the page the iframe of the game does not load. Why is the configuration entry that I must change?

**Comment by Thorin-Oakenpants** [comment]
page not found, also .. fucking dodgy site pushing a lyrics app (dodgy shit to start with) _and_ "games" - WTF? ... also follow the instructions when you log an issue for TROUBLESHOOTING HELP - https://github.com/arkenfox/user.js/issues/new/choose

Also, arkenfox does not block iframes (or fiddle with CORS/COOP/COEP, AFAICT). If it did block an iframe's content, it might be ETP stict, but I doubt it
