### ISSUE TITLE
roblox client doesn't open

### ISSUE THREAD

**Issue by sexymotherhugger** [arkenfox/user.js#1570]
**- Browser version & OS:**
   - 106.0.1 (64-bit)
   - AtlasOS (https://atlasos.net/) (https://discord.com/invite/ERAy8HNFPg)
  
  **- Steps to Reproduce (STR):**
   - Create a Roblox account.
   - Try to join any game/experience.
  
  **- Expected result:**
   - (If installed) the game client opens.
  
  **- Actual result:**
   - An error saying: "An error occurred trying to launch the experience. Please try again later."
   
   ![image](https://user-images.githubusercontent.com/108868243/197409130-6c067663-4390-4832-a248-76cfab66683a.png)

  **- Console errors and warnings:**
   
   ![image](https://user-images.githubusercontent.com/108868243/197409090-232b3e6e-6695-4556-a7b4-e4fac7712245.png)

__Checked #1319 and tried every solution, nothing seemed to work.__

**Comment by Thorin-Oakenpants** [comment]
> and tried every solution, nothing seemed to work

what did you try?

**Comment by Thorin-Oakenpants** [comment]
so you didn't try any of the other common prefs that can cause issues? Or read the troubleshooting guide?

**Comment by sexymotherhugger** [comment]
> so you didn't try any of the other common prefs that can cause issues? Or read the troubleshooting guide?

read it and nothing seemed to be about/help my problem.

**Comment by sexymotherhugger** [comment]
instagram stories don't play either, and i'm pretty sure it's related to roblox client not opening.

**Comment by Thorin-Oakenpants** [comment]
> read it and nothing seemed to be about/help my problem

so you didn't try any of them then? Look, obviously keyword searching from the urlbar is not it. But did you try webgl, did you try RFP?

**Comment by GlassGruber** [comment]
Have you tried disabling ETP? Snatching from rusty:

https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L722

https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L719-L720

_Originally posted by @rusty-snake in https://github.com/arkenfox/user.js/issues/1567#issuecomment-1288136515_

**Comment by sexymotherhugger** [comment]
> > read it and nothing seemed to be about/help my problem
> 
> so you didn't try any of them then? Look, obviously keyword searching from the urlbar is not it. But did you try webgl, did you try RFP?

i tried them and then came to the conclusion that it's not something that helps with my problem.

**Comment by sexymotherhugger** [comment]
> Have you tried disabling ETP? Snatching from rusty:
> 
> https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L722
> 
> https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L719-L720
> 
> _Originally posted by @rusty-snake in [#1567 (comment)](https://github.com/arkenfox/user.js/issues/1567#issuecomment-1288136515)_

did not work dawg

**Comment by rusty-snake** [comment]
Do you use any extension messing up referers?

**Comment by sexymotherhugger** [comment]
> Do you use any extension messing up referers?

no

**Comment by bashonly** [comment]
> instagram stories don't play either, and i'm pretty sure it's related to roblox client not opening.

instagram stories are fixed by overriding `network.http.referer.XOriginPolicy` to `0`

**Comment by g-2-s** [comment]
Did you try on another OS?

**Comment by sexymotherhugger** [comment]
> Did you try on another OS?

no and i don't think it's something related to the OS, it worked before.

**Comment by SomeHybrid** [comment]
I'm pretty sure the issues with roblox are due to firefox, not the arkenfox user.js.

**Comment by sexymotherhugger** [comment]
> > Did you try on another OS?
> 
> no and i don't think it's something related to the OS, it worked before.

i installed arkenfox in a virtual machine with AtlasOS installed and tried to open a roblox experience and it worked. so it's 100% not something to do with the OS.

> I'm pretty sure the issues with roblox are due to firefox, not the arkenfox user.js.

seems like it, i'll try changing some settings and let you guys know if it worked or not

**Comment by sexymotherhugger** [comment]
yikes, i "refreshed" my settings and the problem has fixed itself. was NOT a problem with arkenfox.

**Comment by Thorin-Oakenpants** [comment]
glad you sorted it out

slapping an invalid on it - this does not mean you didn't have a genuine issue, it just means not arkenfox's fault, so people can ignore it when searching or whatnot
