### ISSUE TITLE
Question about uBlock privacy filterlists

### ISSUE THREAD

**Issue by umbralOptimatum** [arkenfox/user.js#1571]
Minor question that doesn't seem to have come up in issues before. By default uBlock enables EasyPrivacy and the wiki recommends enabling AdGuard URL Tracking Protection, but uBlock offers two other privacy filter lists. Is there a reason to avoid these in particular besides generally minimizing the number of things installed? Would installing these cause any issues or are they merely redundant?

**Comment by Thorin-Oakenpants** [comment]
this is not an arkenfox issue - uBlock is a content blocker, block what you like
