### ISSUE TITLE
What about recommending the extension "DuckDuckGo Privacy Essentials"?

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1574]
`https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/`

**Comment by Thorin-Oakenpants** [comment]
what does it add that isn't already covered

**Comment by Thorin-Oakenpants** [comment]
So you just want to throw things at me and get me to do all the work? I would expect at least some investigation and arguments as to why

https://addons.mozilla.org/firefox/addon/duckduckgo-for-firefox/

FEATURE HIGHLIGHTS 
- Search Privately by Default
   - users can already do this, it's called changing your default search engine
- Escape Website Trackers Before They Load
   - well ETP already blocks 3rd party trackers, and then we really recommend uBO, so there's those filters as well
- Automatically Enforce Encryption
   - we use HTTPS-Only mode
- Escape Fingerprinting
   - we already have RFP or for those who can't handle that there's CB, and for those who don't think it's a threat, there's ETP's fingerprinters list
- Block Tracking Cookies
   - we have dFPI - send me your cookies, we don't care
- Enable Built-in Email Protection
   - umm, NFI

ADDITIONAL PROTECTIONS NOT AVAILABLE ON MOST BROWSERS
- Link Tracking Protection
   - we disable cross-site referers and for those who can't live with that (and it can break a lot of stuff depending your mileage), we currently recommend Smart Referer
   - we also have recommended uBO lists for `removeparam` - https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-recommended
- Embedded Social Content Tracking Protection
   - ETP, I think, blocks these under social media trackers, and definitely under Smart Block, plus uBO does this (or can do) - also dFPI
- Google AMP Protection
   - yeah I hate that shit, but honestly I never see it. There are two issues: getting redirected to it, and being given it in a link. Claustromaniac did a big deep dive on it years ago, and found there was no guaranteed way to not connect to AMP first to get the original URL - obviously there are some rules of thumb that work. Brave added something recently, and Firefox might (they already do it for new tab tiles or something - maybe they add more, who knows). Anyway, blocking off large chunks of the internet is not how you get privacy. You get privacy by doing what we're doing AND masking your IP. If you do that, you're just a random visitor, never to be seen again.
- Signal Your Privacy Preference with Global Privacy Control (GPC)
   - meh. we had an issue about this recently. big deal, it's practically useless and it will get enabled when mozilla is ready

next time, please at least try to do some homework, thanks
