### ISSUE TITLE
Is `dom.disable_beforeunload` still necessary?

### ISSUE THREAD

**Issue by GlassGruber** [arkenfox/user.js#1575]
I got bit by this on a form I was building and testing on several browser for the typical user warning like "Hey the form is not complete yet do you want to close the page?".  
On a profile with arkenfox the warning is not triggered and the page is closed with form data lost.

I think the abuse of warning spam is something that got fixed (I believe?) by browsers some time ago by [hardening the requirements](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#security) to enable the `beforeunload` event.

AFAICS last time this was touched was 5 years ago, is this still a concern?  
Should there be a warning in the user.js comments informing of potential sideffects of the switch?

https://github.com/arkenfox/user.js/blob/f4187632faef76df4de0cbb0cdc7199f22fadd76/user.js#L611-L614

Thank you!

**Comment by Thorin-Oakenpants** [comment]
it's probably overkill and could be put into optional hardening

https://developer.mozilla.org/en-US/docs/Glossary/Transient_activation is a great page
so is this - https://developer.mozilla.org/en-US/docs/Web/Security/User_activation

**Comment by Thorin-Oakenpants** [comment]
>  is this still a concern

I'm trying to work out why this is a privacy issue. It was clearly added for the "JS leaks of page close event", but I'm also sure the spammy "Do you really want to leave? Please don't. We love you." dialogs was also part of it. Who cares if the site knows you closed a page, or attempted to - it's meaningless data. Sites can poll anyway (or use service workers?).

I tend to click in pages _all. the. time._ I'm not a text painter, but boy oh boy do I click (I like to know what has focus). I would pass the transient user activation 99% of the time. If I come across any sites that annoy me with "please don't leave" BS, then I simply won't use that site again

So I see this as a usability issue, not a privacy one. The pref can go.

**Comment by rusty-snake** [comment]
If sites abuse it, you can disable it on a per site basis using uB's `+js`.

One override less. Thanks.

**Comment by GlassGruber** [comment]
> So I see this as a usability issue, not a privacy one. The pref can go.

Nice! 🎉 
I think the major concern is the abuse of the message pop up customization like "Install securiteh patch NOW!1!" and all that crap. AFAICT is not possible now to customize the popup in any reliable way,  browsers will just ignore any modifications.

> If sites abuse it, you can disable it on a per site basis using uB's +js.

Oh boy I keep forgetting the tremendous potential of custom js rules for uBO I really need a deep dive into it, thank you for the reminder!
