### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by Unreal85** [arkenfox/user.js#1581]
The last update broke my Firefox profile. If I navigate to Extensions I will get the following error when searching for any extension 

"Secure Connection Failed

An error occurred during a connection to addons.mozilla.org. The server uses key pinning (HPKP) but no trusted certificate chain could be constructed that matches the pinset. Key pinning violations cannot be overridden.

Error code: MOZILLA_PKIX_ERROR_KEY_PINNING_FAILURE"

**Comment by Thorin-Oakenpants** [comment]
read the instructions, closing as invalid -> https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid

pref `1223` has a `[SETUP` tag, it has an error code for you to search for, it is listed as one of 10 common items in [the wiki](https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]) ... 

The value in arkenfox has not changed for the last 5 years, so it was not the arkenfox update that caused this

https://github.com/arkenfox/user.js/blob/8a65c5a7bad0ec764d968b0941ebdf01bdcd2408/user.js#L478-L482
