### ISSUE TITLE
Search bar behaving weirdly

### ISSUE THREAD

**Issue by Thedinotamer** [arkenfox/user.js#1584]
In the user.js file everything about the search bar seem to be disabled, but it will still autocomplete my searches and show me these "Firefox suggestions". If I just press the search bar it will also show me a bunch of websites that I frequently visit. Is this normal?

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [Yes] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 106.0.5, Windows 10
  - Steps to Reproduce (STR): just press the search bar and/or write anything
  - Expected result: search bar should only show what you're currently writing, nothing else.
  - Actual result: when I click on the search bar, a drop-down menu shows a bunch of websites I often visit and when I write something it both finshes what it thinks i'm going to write and shows a bunch of "Firefox suggestions" below.
  - Console errors and warnings: none
  - Anything else you deem worth mentioning: no

---

**Comment by rusty-snake** [comment]
No. What's the state of `browser.search.suggest.enabled`?

btw you talk about the urlbar and not the search bar I guess. The search bar does not have any history/frequently visited features AFAIK.

**Comment by Thedinotamer** [comment]
> No. What's the state of `browser.search.suggest.enabled`?
> 
> btw you talk about the urlbar and not the search bar I guess. The search bar does not have any history/frequently visited features AFAIK.

Yeah, i'm talking about the urlbar. search.suggest.enabled is set to false

**Comment by Thorin-Oakenpants** [comment]
> but it will still autocomplete my searches and show me these "Firefox suggestions"

what is "_these_"?

> In the user.js file everything about the search bar seem to be disabled

urlbar: this is not true. We don't hide or limit the max results or dropdown, we don't disable suggestions based on history, bookmarks, openpages, or topsites. We do not block the search icons either.

> Is this normal?

yes (we do clear history on close, but if you override that, then it will have more to draw from for autocomplete suggestions)

we are not aiming to have a dumb urlbar. We disable searching from it (but you can still click a search icon in the drop down, and you can still use search keywords)

**Comment by Thorin-Oakenpants** [comment]
> Expected result: search bar should only show what you're currently writing, nothing else.

who said that? We didn't

**Comment by Thedinotamer** [comment]
@Thorin-Oakenpants 

> what is "these"?

The drop-down menu that shows up when you start typing something.

> yes (we do clear history on close, but if you override that, then it will have more to draw from for autocomplete suggestions), we are not aiming to have a dumb urlbar. We disable searching from it (but you can still click a search icon in the drop down, and you can still use search keywords)

Ah, ok. What's the pref called that enable those things? I would just like to read about them to see the details :)

> who said that? We didn't

I thought it was a part of the arkenfox project since this [https://youtu.be/F7-bW2y6lcI?t=118](url) video from Techlore talks about that suggestions sends out queries to your search engine if they are enabled
