### ISSUE TITLE
New updater doesn't mention date of user.js backup file

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1589]
![image](https://user-images.githubusercontent.com/30274161/202960992-34ce27e5-3558-43bb-add5-7ac42427c506.png)

Tested with the version 107.

**Comment by icpantsparti2** [comment]
Hi @earthlng.  prefsCleaner.bat backs up prefs.js with similar code, does that need the fix too?  Thanks.

**Comment by earthlng** [comment]
hi @icpantsparti2, thanks for asking but no. The 2 scripts used the exact same lines of code to generate the date string but the updater.bat is running that part of the code with EnableDelayedExpansion and that's why it wasn't working.
