### ISSUE TITLE
2621: network.protocol-handler.external.ms-windows-store

### ISSUE THREAD

**Issue by crssi** [arkenfox/user.js#1591]
Is "this" really so intensive that we should bother?

I had 0 occurrences from the day 1 on.

Cheers

**Comment by crssi** [comment]
Edited title... wrong clipboard data 😉

**Comment by Thorin-Oakenpants** [comment]
duplicate of #1142

**Comment by crssi** [comment]
Oh crap... sorry about duplicate. 😢 
Should have asked on #1142 if there is any change in your point of view.
Not expecting your answer here at all.
Wish you best ❤️

**Comment by Thorin-Oakenpants** [comment]
well, the last one got no traction answers, but I have a new win10/11 laptop I just opened (yet to set it up), so I will be able to test it myself and dig further - I'll reopen #1142 for follow up
