### ISSUE TITLE
prefscleaner.bat

### ISSUE THREAD

**Issue by privacyguy123** [arkenfox/user.js#1593]
"line 139 is too long

aborting"

**Comment by earthlng** [comment]
indeed

**Comment by privacyguy123** [comment]
How does one fix this then? It's never complained about long lines before ...

**Comment by GlassGruber** [comment]
You should check what's in line 139 of your prefs.js file, according to MS docs 8191 is the max length possible to parse in cmd.exe. 

https://learn.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation

(Is the poor kitteh chap gone? 🐈  Very sad!)

**Comment by GlassGruber** [comment]
Mmm looking better at the prefscleaner.bat script it's a bit obscure to me why there is this type of string length check. Sorry I'm not very into cmd esotericism. 

Still I guess that without a proper inspection of what is in that line it's a difficult issue to debug.

**Comment by privacyguy123** [comment]
It's literally a default Firefox preference that will always be that long with my addon/preferences setup.

As I said before, before v107 this was not an issue.

**Comment by GlassGruber** [comment]
And how long is that string? In my prefs.js file for FF ESR 102 the longest line is 4029.  
Do you have a backup of previous prefs.js file to compare?

I've used this script to get that length, if you are using something like WSL or Git for windows you should have awk available.

```
# from https://www.baeldung.com/linux/print-longest-lines-in-file
$ awk '{ln=length}
       ln>max{delete result; max=ln}
       ln==max{result[NR]=$0}
       END{for(i in result) print result[i] }' prefs.js | wc -L
```

**Comment by Thorin-Oakenpants** [comment]
> It's literally a default Firefox preference that will always be that long with my addon/preferences setup.

so it's not a default then? are you talking about `extensions.webextensions.uuids`

**Comment by GlassGruber** [comment]
> are you talking about `extensions.webextensions.uuids`

Interesting in my case max length line is pref `browser.uiCustomization.state`,  `extensions.webextensions.uuids` is 3446 chars long.

**Comment by privacyguy123** [comment]
> > It's literally a default Firefox preference that will always be that long with my addon/preferences setup.
> 
> so it's not a default then? are you talking about `extensions.webextensions.uuids`

yes, and even when disabling extensions it complains another line is too long - headache

**Comment by privacyguy123** [comment]
> And how long is that string? In my prefs.js file for FF ESR 102 the longest line is 4029. Do you have a backup of previous prefs.js file to compare?
> 
> I've used this script to get that length, if you are using something like WSL or Git for windows you should have awk available.
> 
> ```
> # from https://www.baeldung.com/linux/print-longest-lines-in-file
> $ awk '{ln=length}
>        ln>max{delete result; max=ln}
>        ln==max{result[NR]=$0}
>        END{for(i in result) print result[i] }' prefs.js | wc -L
> ```

No and no

**Comment by GlassGruber** [comment]
And what is the length of your questionable lines?

**Comment by privacyguy123** [comment]
"...According to some website string might be 8296 characters long,"

**Comment by GlassGruber** [comment]
> "...According to some website string might be 8296 characters long,"

Sorry I don't understand, what website and why a website should know the length of lines in _your_ file?

If you mean you have pasted your prefs.js content on a website to get the length and that's the result, then you have your answer: that line is too long to be processed via cmd.exe. I guess only fix would be to go with powershell or another script language.

But I would say that there is probably a underlying issue with your profile: how many extension have you installed?  
Maybe I'm wrong, but I'm afraid you could have quite.

**Comment by Thorin-Oakenpants** [comment]
> > are you talking about `extensions.webextensions.uuids`
> 
> Interesting in my case max length line is pref `browser.uiCustomization.state`, `extensions.webextensions.uuids` is 3446 chars long.

That was my other guess. It remembers the state of all changes, including extensions that you have since discarded (so when you add them back, they have their toolbar icons etc where you left them)

Mine is 1077 chars long and all I did was move three extension icons from the navbar to the toolbar, add the search bar, and add the home button. BTW, if you use a decent editor like Notepad++, the status bar in Notepad++ tells you the column number where the cursor is at.

With FF open, go to about:config, search for `browser.uiCustomization.state` and reset it. Then close and reopen FF and re-customize (right click tabstrip > customize). You won't lose anything

**Comment by Thorin-Oakenpants** [comment]
I just reset mine and after re-customizing (I removed some spaces, added the search bar, added the home button + moved the download icon both between urlbar + searchbar, and added/moved three extension icons to my toolbar) and I dropped to 1001 (I had a old extension uuid in there: I changed speed dials a few months back)

**Comment by privacyguy123** [comment]
What a weird limitation - I guess my prefs are fine for now ... unless there's been some major changes under the hood that matter?

**Comment by Thorin-Oakenpants** [comment]
I'm closing this. If you have a heap of extensions, maybe get rid of a few (depends on how much of them were used in cusotmizing the toolbar/navbar etc). Reset your pref and customize only what you need to do. Nothing changed upstream, prefsCleaner has nothing to do with Mozilla, and the code here hasn't changed in the sense that it affects

Your other option is to copy the pref in prefs.js, run prefs cleaner, and then put the pref back manually (in prefs.js) before opening Firefox again (don't add it to the overrides)

Someone else had this issue from memory - something about maintaining the uuids when migrating, and they had a ton of extensions. Not arkenfox's problem IMO
