### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by umbralOptimatum** [arkenfox/user.js#1594]
On the extensions page, the description of Behave is "Monitors and warns if a web page; performs DNS Rebinding attacks to Private IPs, accesses Private IPs, does Port Scans". Monitors and warns if a web page what?

**Comment by Thorin-Oakenpants** [comment]
exact description as per https://addons.mozilla.org/en-US/firefox/addon/behave/ - the semi:colon indicates a list
