### ISSUE TITLE
Auto-update for prefsCleaner?

### ISSUE THREAD

**Issue by umbralOptimatum** [arkenfox/user.js#1596]
Just noticed my prefsCleaner has been one version behind for months. I find the updater's auto-update flag very helpful as I use a script to automate my Arkenfox updates with minimum attention needed from me. Any chance of a similar flag for prefsCleaner?

**Comment by heretoenhance** [comment]
I support this, would be helpful

**Comment by atomGit** [comment]
@claustromaniac @overdodactyl - combining the cleaner and updater scripts might be worth considering

**Comment by earthlng** [comment]
prefsCleaner v1.6 now has auto-update functionality
