### ISSUE TITLE
Arkenfox breaking smoothscroll Profile

### ISSUE THREAD

**Issue by Chillsmeit** [arkenfox/user.js#1598]
I usually use a custom smoothscroll profile.
It works out of the box just fine with a new Librewolf install, or a Firefox fresh install.
But somehow if I use Arkenfox, after pasting the raw profile in the user-overrides.js and running the updater.bat, it completely breaks the smoothscroll profile and behaves completely different. 
Tested it multiple times side by side, I don't know what Arkenfox is changing that is breaking the smoothscroll profile tbh.

This is the smoothscroll profile I'm using https://github.com/Chillsmeit/SmoothScrollFirefox/blob/main/Profiles/Snappier.js

**Comment by Chillsmeit** [comment]
Found the issue, 
Had to change `user_pref("privacy.resistFingerprinting", true);` to `user_pref("privacy.resistFingerprinting", false);`
Didn't know that resistFingerpriting changed scrolling behaviour.

**Comment by Thorin-Oakenpants** [comment]
> Didn't know that resistFingerpriting changed scrolling behaviour.

https://github.com/arkenfox/user.js/blob/45d23f8d75c4cd23be26cfcb32689e60ebbad072/user.js#L831

this limits FPS to 60 (i.e 16.666667ms per "animation") - this is done on a global level so affects animations, video playback etc.

what hrtz is your monitor?

**Comment by Chillsmeit** [comment]
> > Didn't know that resistFingerpriting changed scrolling behaviour.
> 
> https://github.com/arkenfox/user.js/blob/45d23f8d75c4cd23be26cfcb32689e60ebbad072/user.js#L831
> 
> this limits FPS to 60 (i.e 16.666667ms per "animation") - this is done on a global level so affects animations, video playback etc. The previous protection was 100ms on various performance and timing APIs and did not affect playback etc
> 
> what hrtz is your monitor?

Ahhh, that explains it then, thanks for the insight! (My monitor is 100hz)

**Comment by Thorin-Oakenpants** [comment]
going to dupe this to #1568 to help keep `answered` labels down
