### ISSUE TITLE
remove security.tls.version.enable-deprecated

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1600]
@fxbrit 

AFAICT you can't downgrade anymore, so we should be good to remove this? yes? no?

```js
/* 6010: enforce/reset TLS 1.0/1.1 downgrades to session only
 * [NOTE] In FF97+ the TLS 1.0/1.1 downgrade UX was removed
 * [TEST] https://tls-v1-1.badssl.com:1010/ ***/
user_pref("security.tls.version.enable-deprecated", false); // [DEFAULT: false]
```

**Comment by fxbrit** [comment]
I agree we can remove it since the UI doesn't exist anymore and it's default.

users can downgrade to TLS1.1 only if they have `security.tls.version.enable-deprecated` in their overrides or if they change `security.tls.version.min` to 1, but both are active choices and it's not like clicking a button by mistake or just to get past the error screen.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/pull/1592/commits/6d7198f4d3c1e0cb23ee4314624ad9e3d228f1ae

**Comment by Thorin-Oakenpants** [comment]
reverting this, because ... https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40565

**Comment by fxbrit** [comment]
I don't get it, assuming pierov is talking bout https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-102.5.0esr-12.5-1/browser/app/profile/001-base-profile.js#L75 why would we care?

**Comment by Thorin-Oakenpants** [comment]
that's what he said .. flipping that switch bypasses the locks ? Now we don't actually flip those prefs (they are under dont bother) and two of them have since been removed upstream in hardcode - not going to look it up, am done with ciphers, I hate them

**Comment by fxbrit** [comment]
> Now we don't actually flip those prefs

yeah, I would just ignore it for arkenfox tbh

**Comment by Thorin-Oakenpants** [comment]
> and two of them have since been removed upstream in hardcode 

I thought I might have been cc'd in it, but I can;t find it .. but from memory they actually removed the ciphers from the TLS suites IIUIC

anyway, leaving it in for another ESR cycle is fine since according to pierov's comment, it is used to bypass those prefs (just in case someone hardened their browser against downgrade attacks for whatever reason, not going to judge) - so no, not ignoring it for arkenfox

hopefully in another year some more of those ciphers will die - I think the remaining ones account for about 1% of secure traffic

**Comment by Thorin-Oakenpants** [comment]
found it - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41468

**Comment by fxbrit** [comment]
I guess this explains why they have been flipped in early beta [[1]](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#13410-13413) [[2]](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#13400-13403)

**Comment by fxbrit** [comment]
should we revert https://github.com/arkenfox/user.js/commit/e4a85c30c129cf664cc8a39705bb070fce828d33?

**Comment by Thorin-Oakenpants** [comment]
I thought about it, but couldn't be fucked .. we want it reset .. but I guess I should to be consistent
