### ISSUE TITLE
How to block the message "Before you continue to YouTube"

### ISSUE THREAD

**Issue by FlailAway** [arkenfox/user.js#1603]
"Before you continue to YouTube" insanely pervasive.

I have tried the "consent.youtube.com" Block in FFx (107.0) and "user.js" (107) downloaded from here yesterday.

I have tried the uBlock Origin (v1.45.2) Filter "google.*##^script:has-text(consentCookiePayload)"

I never log into google-anything, is there some way user.js can handle this?

Thanks

**Comment by Thorin-Oakenpants** [comment]
this is not a privacy issue, this is an annoyance issue - take it up with uBO if you want
