### ISSUE TITLE
per site zoom not remembered [solved: RFP]

### ISSUE THREAD

**Issue by sexymotherhugger** [arkenfox/user.js#1608]
🟪 REQUIRED INFO
  - Browser version & OS:
     * 108.0.1 (64-bit)
     * AtlasOS v0.5.2
  - Steps to Reproduce (STR):
  1. Open a site
  1.a Press CTRL + I
  1.b Set "Set cookies" to "Allow"
  2. Zoom in/out
  3. Close and re-open the site/Close firefox and re-open the site
  - Expected result:
     * The zoom ratio (110%, 90% etc.) is saved and you are zoomed in/out when you open the site.
  - Actual result:
     * The zoom ratio is set to default (100%)
  - Console errors and warnings:
     * None.
  - Anything else you deem worth mentioning:
     * idk man i thought allowing cookies would fix it

---

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/7135907b2fe13fa55eb8ebf162603037f83e353c/user.js#L798

Also, in future, use the issue template and check the checkbox

**Comment by Thorin-Oakenpants** [comment]
also batting at 100% invalid .. 2 from 2 : https://github.com/arkenfox/user.js/issues?q=is%3Aissue+author%3Asexymotherhugger

**Comment by sexymotherhugger** [comment]
thanks for the info dawg, and mb for the mistakes
