### ISSUE TITLE
unable to access codeberg [solved: IPv6]

### ISSUE THREAD

**Issue by oomfiee** [arkenfox/user.js#1610]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: firefox 108.1 (flatpak), NixOS 22.11
  - Steps to Reproduce (STR): same steps to add arkenfox to your firefox profile
  - Expected result: being able to access codeberg
  - Actual result: unable to access codeberg and missing cert
  - Console errors and warnings: PR_CONNECT_RESET_ERROR
  - Anything else you deem worth mentioning: this does not happen with clean firefox profile

---
```
// RANDOM OVERRIDES //
user_pref("widget.use-xdg-desktop-portal.file-picker", 1); // force Firefox to use KDE filepicker

user_pref("browser.startup.page", 1); // set about:home as the startup page
//user_pref("browser.startup.homepage", "about:home"); // set about:home as the homepage and newtab page
user_pref("browser.newtabpage.enabled", true); // enable newtab page

user_pref("browser.safebrowsing.downloads.remote.enabled", true); // enable SafeBrowsing checks for downloads

/* location bar and search related overrides */
user_pref("keyword.enabled", true); // enable location bar using search
user_pref("browser.search.suggest.enabled", true); // enable search suggestions
user_pref("browser.urlbar.suggest.searches", true);
// Make firefox urlbar consistent with Windows behaviour
user_pref("browser.urlbar.clickSelectsAll", true);
user_pref("browser.urlbar.doubleClickSelectsAll", false);
user_pref("layout.word_select.stop_at_punctuation", true);

user_pref("privacy.resistFingerprinting.letterboxing", false); // disable RFP letterboxing

user_pref("media.eme.enabled", true); // enable DRM

/* DNS related spells */
user_pref("network.trr.mode", 3); // only use TRR
user_pref("network.trr.uri", "https://dns.google/dns-query"); // use Google DNS-over-HTTPS
user_pref("network.trr.custom_uri", "https://dns.google/dns-query");
user_pref("network.dns.echconfig.enabled", true); // enable ECH
user_pref("network.dns.use_https_rr_as_altsvc", true);
user_pref("network.http.http3.enable", true); // enable DNS-over-HTTP3/QUIC
user_pref("network.dns.http3_echconfig.enabled", true); // enable ECH for DNS-over-HTTP3/QUIC

/* Make scrolling snappier - Credits: Kellegram */
user_pref("general.smoothScroll.msdPhysics.enabled", true);
user_pref("general.smoothScroll.msdPhysics.continuousMotionMaxDeltaMS", 250);
user_pref("general.smoothScroll.msdPhysics.motionBeginSpringConstant", 400);
user_pref("general.smoothScroll.msdPhysics.regularSpringConstant", 400);
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaMS", 120);
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio",  0.4);
user_pref("general.smoothScroll.msdPhysics.slowdownSpringConstant", 5000);
user_pref("mousewheel.min_line_scroll_amount", 22);
user_pref("toolkit.scrollbox.horizontalScrollDistance", 4);
user_pref("toolkit.scrollbox.verticalScrollDistance", 5);
user_pref("apz.frame_delay.enabled", false);

/* Miscellaneous Stuff */
user_pref("fission.autostart", true); // ensuring that fission, site isolation, is enabled
user_pref("gfx.webrender.all", true);
user_pref("extensions.pocket.enabled", false); // disable Pocket
user_pref("devtools.theme", "dark"); // enable dark theme in devtools
user_pref("signon.rememberSignons", false); // disable saving passwords
user_pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false); // disable PiP
```

**Comment by rusty-snake** [comment]
> Anything else you deem worth mentioning: this does not happen with clean firefox profile

Does it happen with a clean firefox profile with only arkenfox (no extensions, no old prefs.js, ...)?

**Comment by Thorin-Oakenpants** [comment]
nothing sticks out from your overrides except _maybe_ the networking ones, but more than likely not.

https://support.mozilla.org/en-US/questions/1280856 - AV? Extensions?

**Comment by oomfiee** [comment]
> > Anything else you deem worth mentioning: this does not happen with clean firefox profile
> 
> Does it happen with a clean firefox profile with only arkenfox (no extensions, no old prefs.js, ...)?

nope on clean profile codeberg just connects normally

**Comment by oomfiee** [comment]
> nothing sticks out from your overrides except _maybe_ the networking ones, but more than likely not.
> 
> https://support.mozilla.org/en-US/questions/1280856 - AV? Extensions?

no AV or Extensions just brand new profile with user.js on it

**Comment by fxbrit** [comment]
I tested the dns/http3/ech prefs on my profile and codeberg works fine. did you setup a firewall on your machine or network?

**Comment by Thorin-Oakenpants** [comment]
this is actually a good troubleshooting guide: https://kinsta.com/knowledgebase/pr_connect_reset_error/

**Comment by oomfiee** [comment]
> I tested the dns/http3/ech prefs on my profile and codeberg works fine. did you setup a firewall on your machine or network?

nope i just checked my system and i dont have firewall on my machine or network since i can access the same site on different profile

**Comment by Thorin-Oakenpants** [comment]
> just brand new profile with user.js on it

I assume you mean you have the issue with arkenfox AND all your overrides. What happens on a new profile with just arkenfox master user.js ?

**Comment by oomfiee** [comment]
> > just brand new profile with user.js on it
> 
> I assume you mean you have the issue with arkenfox AND all your overrides. What happens on a new profile with just arkenfox master user.js ?

i tested this issue on new profile with just user.js still the same issue
and retested it with overrides still the same issue

**Comment by Thorin-Oakenpants** [comment]
So did this just start happening, how long have you been using the user.js? None of use (fxbrit, rusty-snake or myself) have any issues

Have you tried troubleshooting by bisecting the prefs? see the wiki

**Comment by oomfiee** [comment]
> So did this just start happening, how long have you been using the user.js? None of use (fxbrit, rusty-snake or myself) have any issues
> 
> Have you tried troubleshooting by bisecting the prefs? see the wiki

since this issue only started in version 107 before that everything was working normally

**Comment by Thorin-Oakenpants** [comment]
hmmm .. helps if you link to things - https://codeberg.org/Codeberg/Community/issues/744#issuecomment-689571

**Comment by oomfiee** [comment]
> hmmm .. helps if you link to things - https://codeberg.org/Codeberg/Community/issues/744#issuecomment-689571

sorry about that, i am currently testing if this happens again with a complete clean install

**Comment by oomfiee** [comment]
same thing for some reason
![Screenshot_20230102_194617](https://user-images.githubusercontent.com/80048740/210259292-8395fd70-c57c-4381-9c0e-a43585b28581.png)
and the console inputs nothing
![Screenshot_20230102_194701](https://user-images.githubusercontent.com/80048740/210259362-0fc8933f-843d-4dce-9431-d46d8a969d67.png)

**Comment by Thorin-Oakenpants** [comment]
I assume that you are repeating the same steps and the above is with your full user,js as per the original post.

But a new profile works. You clearly have no issues setting up profiles - as already mentioned .. bisect the user.js until you hit the problem
- create a new profile, test it works, add a bookmark on the toolbar
- close FF, copy the profile and rename it profile-master or something
- add half the user js (say the start til end of 1400, restart and test
   - did the test work? if yes then had some more of the user.js, restart and test
   - if not, then the problem is in the first half, reset the profile and add a quarter

Given none of us can repro, I'm almost going to say it's some combo of your ISP, codeberg, jesus, VPNs, proxys, and satan

**Comment by fxbrit** [comment]
> same thing for some reason

this is a fresh install with arkenfox and no overrides right? it seems like it didn't even try to do a security negotiation because you have no "security" tab in the network analysis tool. I don't understand why this would happen only with arkenfox and only on codeberg, it makes little to no sense.

I would suggest you run a network analysis with wireshark if you can, I just cannot reproduce this.

**Comment by oomfiee** [comment]
> I assume that you are repeating the same steps and the above is with your full user,js as per the original post.
> 
> But a new profile works. You clearly have no issues setting up profiles - as already mentioned .. bisect the user.js until you hit the problem
> 
>     * create a new profile, test it works, add a bookmark on the toolbar
> 
>     * close FF, copy the profile and rename it profile-master or something
> 
>     * add half the user js (say the start til end of 1400, restart and test
>       
>       * did the test work? if yes then had some more of the user.js, restart and test
>       * if not, then the problem is in the first half, reset the profile and add a quarter
> 
> 
> Given none of us can repro, I'm almost going to say it's some combo of your ISP, codeberg, jesus, VPNs, proxys, and satan

it breaks on selection 0700

**Comment by oomfiee** [comment]
i found what breaks it its ```user_pref("network.dns.disableIPv6", true);```

**Comment by Thorin-Oakenpants** [comment]
This is why I wrote the wiki. IDK much about IPv4 vs IPv6. But that has come up before, when someone in India had issues with it with a certain mobile provider. It's an ISP thing I think.

**Comment by Thorin-Oakenpants** [comment]
add an override, and close if you're happy

**Comment by Thorin-Oakenpants** [comment]
PS: https://vad.solutions/ipmap/ .. cuz it's such a cool map
