### ISSUE TITLE
Without setting browser.search.region, localized search engines are added

### ISSUE THREAD

**Issue by Dupond** [arkenfox/user.js#1612]
Hello!

I just wanted to mention that [this commit](https://github.com/arkenfox/user.js/pull/1606/commits/bd1a0c28ddd2fc1f170151f8f9e4baab8be0d21e) (and more precisely the removal of the `browser.search.region` pref) has a little downside: instead of having the default US search engines, other search engines are added depending on your IP address.

This is particularly annoying when/if you use a VPN: each time you change the VPN server you connect to, some new localized search engines are added.

At least that's what I can see on my Firefox 108.0.1 on Arch Linux.

**Comment by Thorin-Oakenpants** [comment]
all discussed in #1590 

If you wanted to, just add your own search engine and disable the built in ones

> each time you change the VPN server you connect to, some new localized search engines are added

it's not meant to change any search engines until two weeks continuous same region. We're not doing anything different than all the other Firefox users have - so if changing VPN end points is modifying your search engines immediately, then that is an upstream issue

**Comment by Thorin-Oakenpants** [comment]
Can you confirm the search engines change with a VPN endpoint change? If so then we can file a bug

**Comment by Dupond** [comment]
> if changing VPN end points is modifying your search engines immediately, then that is an upstream issue

Oh, OK! So I'll investigate and see if I can find the cause...

> Can you confirm the search engines change with a VPN endpoint change? If so then we can file a bug

I don't have the time to do many tests right now, but I'll do it this weekend and I'll let you know as soon as I've confirmed it.

**Comment by Thorin-Oakenpants** [comment]
^ cool, take your time, and when confirmed I can hopefully upstream it with prejudice

use a new profile. note your real region, the build language, and the engines (test it by seeing where it lands e.g. google.com or google.de). Then VPN into some foreign region that would change your engine, and note if the any pref changes (there's several region prefs such as home etc)

Not asking you to share your region here, but it's kinda important info. If you want you can tell me in private, just let me know when you're all ready

**Comment by Dupond** [comment]
> use a new profile.

Just to be sure: you men a new profile *without* your `user.js`, right?

**Comment by Thorin-Oakenpants** [comment]
^ yes. We want STR (steps to reproduce) and don't want any other customizing to confound the issue

**Comment by Dupond** [comment]
OK, here's what I've done:

1. First test:
- VPN server in Amsterdam (Netherlands)
- create a new profile; open it; list of search engines:
    - Google
    - Amazon.nl
    - Bing
    - DuckDuckGo
    - eBay
    - Wikipedia (en)
- close Firefox; save `prefs.js` (for future comparison)
- VPN server in Paris (France)
- open the new profile; the list of search engines has NOT changed
- save prefs.js; the diff between the 2 prefs.js shows NO important difference between before and after the VPN location change; in particular, even after switching to a VPN server located in Paris, the `browser.search.region` is still set to "NL"!

2. Second test:
- this time the VPN server is first located in Paris (France)
- create a new profile; open it; list of search engines:
    - Google
    - Amazon.fr
    - Bing
    - DuckDuckGo
    - Wikipedia (en)
    - (so: Amazon.nl is now Amazon.fr, and there's no search engine for eBay)
- close Firefox; save `prefs.js` (for future comparison)
- VPN server in Amsterdam (Netherlands)
- open the new profile; the list of search engines has NOT changed
- save prefs.js; the diff between the 2 prefs.js shows NO important difference between before and after the VPN location change; in particular, even after switching to a VPN server located in the Netherlands, the `browser.search.region` is still set to "FR".

So... Of course, I was wrong and you were right, and I probably shouldn't have opened this issue. Sorry.

That being said, using the Arkenfox `user.js` file, if I switch my VPN from France to Netherlands, then my search engines change (I have a new eBay search engine and Amazon.fr is now Amazon.nl)... but I have to find out why.

**Comment by Thorin-Oakenpants** [comment]
test 1 amazon.nl, test 2 amazon.fr

This might be misleading. You might be getting redirected based on IP. i.e the search engine itself isn't changed. IDK without testing myself (I don't have a VPN).

> That being said, using the Arkenfox user.js file, ...

The whole thing is convoluted and I hate dealing with it. Not bashing FF here, it all seems reasonable. I just hate dealing with it and all the variables: such as original app build language, the diffs between say en-AU, en-CA, en-GB, en-US (some stick with .com, some don't), the IP, the region prefs. Does my head in

for example, I am not in the US, my region is not en-US, but my FF is en-US app language/build and my engines are all the same as an en-US build and I land on google.com for searches. How does that translate for someone using en_US app builds in NL?

Maybe you need to reset everything to your real region so the base/core engines are correct? i.e resetting the region prefs, it then writes them as the VPN on the next start. In the next AF those prefs have been removed - i.e not in `6050` precisely so we're not resetting them with prefsCleaner

**Comment by Dupond** [comment]
> Maybe you need to reset everything to your real region so the base/core engines are correct?

My FF has always been in en-US, and thought it was better because of fingerprinting, and easier when you need to find some help about FF (since the interface and all the error messages are in english, and most useful resources are too).

I think I'll re-add the removed prefs to my `user-overrides.js`.

That being said, I understand the reasons and your explanations:

> How does that translate for someone using en_US app builds in NL?

That's a good question ;)

Anyway, thank you for your time and your explanations!

**Comment by Thorin-Oakenpants** [comment]
> because of fingerprinting

the region prefs in the AF patches don't affect FPing, just internal FF code for knowing when to roll out features such as DoH, credit cards  - or to update the built in search engines - and actual region doesn't change unless 2 weeks continuous diff

let's not confuse the "App" language (chrome/UI - not to be confused with `AppLocale` - see [1635561#c8](https://bugzilla.mozilla.org/show_bug.cgi?id=1635561#c8)) vs what websites are requested in (languages) vs `RegionalPrefLocales` (not to do with region prefs in this issue: it's to do with your resolvedOptions in unified `Intl.`).

My guess is that installing as en-US will have it's own default search engines inside omni.ja - but you might be in region DE for example,. so on first region check it will set your region and change those bundled search engines. This is now your default, and nothing should change without 2 weeks continuous change. Also Firefox (and Tor Browser) now have live language loading (that's Application language) which means a single installer

Regardless, you should be able to get your profile to it's "natural" state with search engines, and nothing should change without 2 weeks continuous change

I can't really offer any more insight. But it must be somewhat annoying - e.g. what shows in the urlbar as search suggestions etc - e.g. you type `cocaine and hookers` and ebay shows up - screws with muscle memory. Another option is to remove those engines (they're still in omni.ja) and just add your own

**Comment by Dupond** [comment]
Thanks a lot for your insights!

About fingerprinting, I was pretty sure I was wrong, and you wouldn't have removed some prefs that would impact the user's fingerprint ;) But I'm never sure whether I fully understand the new commits; so thanks for the explanations.

> Another option is to remove those engines (they're still in omni.ja) and just add your own

Maybe I'll do that... but it's annoying when you have to deal with several computers...
