### ISSUE TITLE
Can't access https://accounts.firefox.com/ or use sync

### ISSUE THREAD

**Issue by Keenly5490** [arkenfox/user.js#1617]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 109.0 Windows 11
  - Steps to Reproduce (STR): Setup Arkenfox
  - Expected result: Being able to access Firefox account
  - Actual result: Error 500 page
  - Console errors and warnings: N/A
  - Anything else you deem worth mentioning: Does not occur with clean Firefox profile

---
// my overrides
/* override recipe: enable session restore ***/
user_pref("browser.startup.page", 3); // 0102
  // user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  // user_pref("browser.sessionstore.privacy_level", 0); // 1003 optional to restore cookies/formdata
user_pref("privacy.clearOnShutdown.history", false); // 2811
  // user_pref("privacy.cpd.history", false); // 2820 optional to match when you use Ctrl-Shift-Del/* override recipe: enable session restore ***/
user_pref("browser.startup.page", 3); // 0102
  // user_pref("browser.privatebrowsing.autostart", false); // 0110 required if you had it set as true
  // user_pref("browser.sessionstore.privacy_level", 0); // 1003 optional to restore cookies/formdata
user_pref("privacy.clearOnShutdown.history", false); // 2811
  // user_pref("privacy.cpd.history", false); // 2820 optional to match when you use Ctrl-Shift-Del
  user_pref("keyword.enabled", true);                   // 0801: enabled urlbar search
user_pref("signon.rememberSignons", false);           // 5003: disable saving passwords

**Comment by Thorin-Oakenpants** [comment]
Hmm, so I only just now noticed this issue .. WTF, not sure what I was doing 18 months ago, but it must have been good

links
- WORKSFORME [1810741](https://bugzilla.mozilla.org/show_bug.cgi?id=1810741) RFP breaks Sync login
- ^DUPLICATE [1810868](https://bugzilla.mozilla.org/show_bug.cgi?id=1810868) 500 Error when signing in to Firefox Accounts with `privacy.resistFingerprinting` enabled
- ^DUPLICATE [1811255](https://bugzilla.mozilla.org/show_bug.cgi?id=1811255) accounts.firefox.com -Can't log to sync, when ("privacy.resistFingerprinting", is set to true)
- related.. [1621729](https://bugzilla.mozilla.org/show_bug.cgi?id=1621729) privacy.resistFingerprinting set to true breaks login at https://appleid.apple.com/

So all these issues related to timing/performance API and were mostly all solved in FF111+ [1811567](https://bugzilla.mozilla.org/show_bug.cgi?id=1811567) Remove RFP Restrictions on the Performance APIs
