### ISSUE TITLE
Firefox Account Page Error (Sync not working)

### ISSUE THREAD

**Issue by patricksoboyle** [arkenfox/user.js#1619]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ x ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: firefox-109.0_1 on voidlinux
  - Steps to Reproduce (STR): follow the installation steps. copy in the user.js. try launching with and without updating/cleaning using the relevant scripts. i have tried this on multiple fresh profiles as well.
  - Expected result: The firefox sign-in account page should pull up without errors
  - Actual result: Error pasted below

> 500 Error

> Oh dear, something went wrong there. We've been notified and will get working on a fix.
> 
> n@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:13512
> diff@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:13673
> getLoad@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:16126
> getAllData@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:24310
> getFilteredData@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:25652
> flush@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:23291
> logEvent@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:26424
> logView@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:27200
> logView@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:1:37891
> showView/</<@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/app.bundle.en_US.js:9:111026
> invoke@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:84:6401
> run@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:84:1809
> R/<@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:99:2761
> invokeTask@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:84:7019
> runTask@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:84:2424
> m@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:84:9056
> invokeTask@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:84:8124
> p@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:115:743
> d@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:115:1058
> _@https://accounts-static.cdn.mozilla.net/bundle-4f438d13259e05054dc032d5caa7e8c2fffaced7/appDependencies.bundle.js:115:1357

  - Console errors and warnings: Below

> TypeError: this is undefined
>     n navigation-timing.js:72
>     diff navigation-timing.js:101
>     getLoad speed-trap.js:67
>     getAllData metrics.js:441
>     getFilteredData metrics.js:502
>     flush metrics.js:343
>     logEvent metrics.js:588
>     logView metrics.js:716
>     logView base.js:838
>     showView app.js:134
>     invoke zone.js:372
>     run zone.js:134
>     R zone.js:1275
>     invokeTask zone.js:406
>     runTask zone.js:178
>     m zone.js:585
>     invokeTask zone.js:491
>     p zone.js:1661
>     d zone.js:1692
>     _ zone.js:1729
> logger.js:72:35

  - Anything else you deem worth mentioning: 
  - When following the troubleshooting steps, everything somehow works when executing the same window after running the **troubleshooter script**. However, the fix does not persist.
  - I have also modified the permissions to allow cookies, disable tracking protection, and allow pop-up windows.
  - I have tried following the advice in the prefsCleaner script (deleting prefs.js)

---

**Comment by Thorin-Oakenpants** [comment]
[1810741](https://bugzilla.mozilla.org/show_bug.cgi?id=1810741) RFP breaks Sync login

clearly you missed https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common] which lists the 9 most common prefs that may cause users an issue ... no 9 (not ranked, but because it follows the user.js layout) is RFP

RFP also has a `[SETUP-WEB` tag

**Comment by Thorin-Oakenpants** [comment]
also see https://bugzilla.mozilla.org/show_bug.cgi?id=1811567
