### ISSUE TITLE
Handle the absence of the WMIC utility

### ISSUE THREAD

**Issue by dartraiden** [arkenfox/user.js#1624]
Starting from Windows 11 [WMIC](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic) is an optional component and can be uninstalled by the user. Both prefsCleaner and updater use WMIC to construct the name of the backup file. If the WMIC is missing, an error `The filename, directory name, or volume label syntax is incorrect` appears. Backup will not be created.

The error text is incomprehensible to the user. I suggest adding a check for the presence of WMIC. If WMIC is missing, display a warning that the backup will not be created and skip the whole backup procedure.

**Comment by earthlng** [comment]
I've replaced WMIC with a powershell command to get the date-timestamp in the Updater.bat.
Can you test if that works for you?
If it does, I'll make the change in the prefsCleaner as well.

**Comment by dartraiden** [comment]
Yes, the new updater.bat works correctly 👍

**Comment by earthlng** [comment]
Okay, thanks for the feedback. I made the change in the prefsCleaner too.
