### ISSUE TITLE
changelog: v109, v110, v111, v112, v113, v114

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1627]
## :green_square: v114

[FF114 release notes](https://www.mozilla.org/firefox/114.0/releasenotes/)
[FF114 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/114)
[FF114 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2023-20/)

there isn't a v114 release, nothing changed

## :green_square: v113

[FF113 release notes](https://www.mozilla.org/firefox/113.0/releasenotes/)
[FF113 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/113)
[FF113 security advisories](https://www.mozilla.org/security/advisories/mfsa2023-16/)

there isn't a v113 release, nothing changed

## :green_square: v112

date: 5-May-2023

[FF112 release notes](https://www.mozilla.org/firefox/112.0/releasenotes/)
[FF112 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/112)
[FF112 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2023-13/)

### CHANGELOG

v112 was just cosmetic changes

- [all changes](https://github.com/arkenfox/user.js/compare/111.0...112.0)
- [ToDo: diffs FF110-FF111](https://github.com/arkenfox/user.js/issues/1661) issue
- v112 PR is at #1654

---

## :green_square: v111

date: 30-March-2023

[FF111 release notes](https://www.mozilla.org/firefox/111.0/releasenotes/)
[FF111 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/111)
[FF111 security advisories](https://www.mozilla.org/security/advisories/mfsa2023-09/)

### CHANGELOG

- [all changes](https://github.com/arkenfox/user.js/compare/110.0...111.0)
- [ToDo: diffs FF110-FF111](https://github.com/arkenfox/user.js/issues/1646) issue
- v111 PR is at #1650

---

- new  in user.js v111
```js
// user_pref("alerts.useSystemBackend.windows.notificationserver.enabled", false);
```

---

## :green_square: v110

date: 12-March-2023

[FF110 release notes](https://www.mozilla.org/firefox/110.0/releasenotes/)
[FF110 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/110)
[FF110 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2023-05/)

### CHANGELOG

v110 was just cosmetic changes

- [all changes](https://github.com/arkenfox/user.js/compare/109.0...110.0)
- [ToDo: diffs FF109-FF110](https://github.com/arkenfox/user.js/issues/1640) issue
- v110 PR is at #1629

---

## :green_square: v109

date: 7-February-2023

[FF109 release notes](https://www.mozilla.org/firefox/109.0/releasenotes/)
[FF109 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/109)
[FF109 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2023-01/)

### OTHER NEWS

@kewiha and @earthlng added an unattended flag in prefsCleaner.bat - thanks :pizza: :beers:
- see #1616

:star: your friendly reminder to run prefsCleaner

![62baz6](https://user-images.githubusercontent.com/16656956/150662274-33812185-e970-47e7-899e-72d18cc83f06.jpg)

---

### CHANGELOG

- [all changes](https://github.com/arkenfox/user.js/compare/108.0...109.0)
- [ToDo: diffs FF108-FF109](https://github.com/arkenfox/user.js/issues/1623) issue
- v109 PR is at #1614

---

- removed in user.js v109 (in section 6050 for prefsCleaner)
   - see #1618 - thanks @partingscientist
```js
// user_pref("browser.startup.blankWindow", "");
```

- made inactive in user.js v109 (moved to section 5000 for optional hardening)
   - for popup events see #1609 - thanks @emphoeller
```js
// user_pref("browser.pagethumbnails.capturing_disabled", true);
// user_pref("dom.popup_allowed_events", "click dblclick mousedown pointerdown");
```

---

```
 STATS v109: up to and including section 4500, minus the parrots
 ==========
    total: 184
 inactive:  44
           ---
   active: 140
  default:  23 (at least)
      n/a:   2 (of the four prefs in 0202, at most only two will apply)
           ---
  flipped: 115 (at most)
```

**Comment by GlassGruber** [comment]
What about some hails? 💯 

![](https://thumbs.gfycat.com/DazzlingEntireFlee-size_restricted.gif)

**Comment by GlassGruber** [comment]
> At some stage, arkenfox will cease to be updated, maybe by the end of this ESR's EOL - I'm tracking (and soon to be part of, kinda already am TBH - will be granted access shortly) something elsewhere I think will replace this - not going to discuss it, so don't ask. But at the rate of change here, AF is nearing EOL too (but I won't leave it without a successor)

Sounds spicy! Very cool let's hope for the best! 👍

**Comment by fxbrit** [comment]
the most interesting part here is the per-containers prefs with the incremental number 👀
