### ISSUE TITLE
ns_error_not_implemented issue

### ISSUE THREAD

**Issue by linuxgirl22** [arkenfox/user.js#1628]
Hello
Thank you very much for your work; really appreciate being able to use arkenfox, and that, although I'm not very technically minded, it is very straightforward to use. 

I have made sure the error isn't caused by arkenfox. Ran user.js in console filter box, and no errors showed. 
Running latest firefox, installed via MX Linux package manager. 
Steps to reproduce ... go to these two pages:
https://mullvad.net/en/check/
https://mullvad.net/en/servers/
... no connection or expected information shown.

Had no problem running the two mullvad pages on first installing arkenfox 2 weeks ago. 
These errors show now on the live connection/leaks page:
![console messages](https://user-images.githubusercontent.com/35760727/218234411-aa774eaf-463e-4877-80d4-b4187bb1ebaa.png)

Contacted mullvad support and so far they've said to look at the console messages, and try e.g. safe mode. Backing up .mozilla and running firefox without arkenfox/privacy/add-ons makes the two pages show, but can't use browser like that. 

From my side, only the version of firefox is different since 2 weeks ago, plus latest arkenfox. Am 100% about prioritising arkenfox/privacy, and there are other sites where can check about leaks, but am concerned that, although mullvad otherwise works really well on linux, online page changes may be affecting access, or is it that the firefox update may have changed something? No problem with anything necessary being blocked; just not sure what is causing the issue.

**Comment by Thorin-Oakenpants** [comment]
You are on Firefox 109, right? What OS? What are your overrides if any?  I can't reproduce from my machine (no VPN). What does the other console show (control-shift-k)

Are you testing this with a VPN? Is that VPN system wide or an extension (just FYI, VPN extensions are not reliable BTW - not problem related, just saying)

**Comment by Thorin-Oakenpants** [comment]
> Had no problem running the two mullvad pages on first installing arkenfox 2 weeks ago.

2 weeks ago, FF109 had already already been released. When did you update to 109 (MX Linux package manager) ?

What I'm trying to ask, is are you sure this started with 109 + AF, and 108 +AF worked?

> I have made sure the error isn't caused by arkenfox. Ran user.js in console filter box, and no errors showed

This isn't how you test if arkenfox is the cause. You test that by testing in a new profile without arkenfox (or any extensions), and then retest that new profile with arkenfox (and no extensions)

> errors

Can you show me the developer console instead (control-shift-K) - I would expect to see a bunch of CORS

---

those browser console errors don't even look related (and I don't get those errors). I mean what the heck does coldstartupcheck  have to do with a website? don't answer - it's a rhetorical q

`resource:///modules/BrowserGlue.jsm`
```js
  _collectStartupConditionsTelemetry() {
    let nowSeconds = Math.round(Date.now() / 1000);
    // Don't include cases where we don't have the pref. This rules out the first install
    // as well as the first run of a build since this was introduced. These could by some
    // definitions be referred to as "cold" startups, but probably not since we likely
    // just wrote many of the files we use to disk. This way we should approximate a lower
    // bound to the number of cold startups rather than an upper bound.
    let lastCheckSeconds = Services.prefs.getIntPref(
      "browser.startup.lastColdStartupCheck",
      nowSeconds
    );
    Services.prefs.setIntPref(
      "browser.startup.lastColdStartupCheck",
      nowSeconds
    );
    try {
      let secondsSinceLastOSRestart =
        Services.startup.secondsSinceLastOSRestart;
      let isColdStartup =
        nowSeconds - secondsSinceLastOSRestart > lastCheckSeconds;
      Services.telemetry.scalarSet("startup.is_cold", isColdStartup);
      Services.telemetry.scalarSet(
        "startup.seconds_since_last_os_restart",
        secondsSinceLastOSRestart
      );
    } catch (ex) {
      Cu.reportError(ex);  // <=== line 1624 in my Firefox
    }
  },
```

**Comment by linuxgirl22** [comment]
Hi Thorin-Oakenpants and thanks for your responses. Yes, running systemwide vpn 24/7, and, when first installed FF 2 weeks ago, it was at 109; installed arkenfox before using the browser fully, and two mullvad pages had worked fine then ... had seen dns leak then realised overrides file needed some tweaks, and that fixed things. With being new to arkenfox and overrides, had downloaded an overrides file ... one or two bits I don't understand, but looked up some bits and tweaked them. Probably mistakes in there, lol, as most of it I don't understand, but look up online.  

Thank you for advice about how to properly test ... FF with no arkenfox or add-ons runs the 2 pages, but will test now a new profile with arkenfox, and will add in with/without overrides. 

Thanks for advice about the console. This is the network tab output on mullvad connection/leak check page:

![network tab of CtrlShiftK](https://user-images.githubusercontent.com/35760727/218254001-fc4dea10-a713-4cab-a471-31b31ee3f382.png)

The main console output is a lot of text, and I'm aware the overrides file paste will be large, so I can paste some bits from the main console output, if that's better for now. Sorry, I can't see anything where I can enclose code [please just cut it if text is too long].

[CanvasBlocker] invalid content script order: require not defined at https://mullvad.net/en/check/ dd2f4bf8-beb0-4238-b599-1fd95f726479:17:16
TypeError: r is undefined
    Wm https://mullvad.net/static/check/assets/vendor.js:1
    lv https://mullvad.net/static/check/assets/vendor.js:1
    C https://mullvad.net/static/check/assets/vendor.js:1
    S https://mullvad.net/static/check/assets/vendor.js:1
...........................................
    Ic https://mullvad.net/static/check/assets/vendor.js:1
    Ic https://mullvad.net/static/check/assets/vendor.js:1
vendor.js:1:12751
Uncaught TypeError: r is undefined
    Wm https://mullvad.net/static/check/assets/vendor.js:1
    lv https://mullvad.net/static/check/assets/vendor.js:1
    C https://mullvad.net/static/check/assets/vendor.js:1
    S https://mullvad.net/static/check/assets/vendor.js:1
............................................
    mount https://mullvad.net/static/check/assets/vendor.js:1
    mount https://mullvad.net/static/check/assets/vendor.js:1
    <anonymous> https://mullvad.net/static/check/index.659e9be54c6a.js:2
vendor.js:1:59593
Uncaught (in promise) TypeError: m.value is null
    Y https://mullvad.net/static/check/assets/vendor.js:25
    registerTick https://mullvad.net/static/check/assets/vendor.js:23
vendor.js:25:43050
Uncaught (in promise) TypeError: r is undefined
    Wm https://mullvad.net/static/check/assets/vendor.js:1
    lv https://mullvad.net/static/check/assets/vendor.js:1
    C https://mullvad.net/static/check/assets/vendor.js:1
    S https://mullvad.net/static/check/assets/vendor.js:1
.................................................
    ne https://mullvad.net/static/check/assets/vendor.js:1
    registerDep https://mullvad.net/static/check/assets/vendor.js:1
vendor.js:1:59593
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ipv6.am.i.mullvad.net/json. (Reason: CORS request did not succeed). Status code: (null).
TypeError: r is undefined
    Wm https://mullvad.net/static/check/assets/vendor.js:1
    lv https://mullvad.net/static/check/assets/vendor.js:1
    C https://mullvad.net/static/check/assets/vendor.js:1

Again, please cut text if too much, but this is the overrides file contents:

//DNS over HTTPS
//Protects web requests from an ISP
//Please pick a provider you trust.
//Disable if you use PiHole, but tools like pfBlocker work fine.
// Cloudflare (default in US & Canada).
//Quad 9: https://dns.quad9.net/dns-query
user_pref("network.trr.mode", 5);

//Disable Safe Browsing, this phones home to Google.
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);

// Leave IPv6 enabled
user_pref("network.dns.disableIPv6", false);

//Reenable search engines
user_pref("keyword.enabled", true);
//Enable Search Engine suggestion
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);
// Disk caching, which might improve performance if enabled.
user_pref("browser.cache.disk.enable", false);
//Enable favicons, the icons in bookmarks
user_pref("browser.shell.shortcutFavicons", true);
//Enable Mozilla Container Tabs
//Redundant with Total Cookie Protection, but useful if you have multiple accounts
//with the same provider (e.g. a work Google account and a personal Google account)
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.ui.enabled", true);

//WebRTC settings, things like video calls
user_pref("media.peerconnection.enabled", false);
// Disable Media Plugins
   // user_pref("media.gmp-provider.enabled", false);
// Disable DRM
   // user_pref("media.gmp-widevinecdm.enabled", false);
user_pref("media.eme.enabled", false);
//Autoplaying settings
//0=Allow all, 1=Block non-muted media (default), 5=Block all
   // user_pref("media.autoplay.default", 5);
//If some websites REALLY need autoplaying...
//0=sticky (default), 1=transient, 2=user
user_pref("media.autoplay.blocking_policy", 2);

//Use Disconnect's blocklist to block ads
user_pref("browser.contentblocking.category", "strict");

//Delete cookies on close, but see below to make exceptions
/* 2801: delete cookies and site data on exit
 //* 0=keep until they expire (default), 2=keep until you close Firefox
 * [NOTE] A "cookie" block permission also controls localStorage/sessionStorage, indexedDB,
 * sharedWorkers and serviceWorkers. serviceWorkers require an "Allow" permission
 * [SETTING] Privacy & Security>Cookies and Site Data>Delete cookies and site data when Firefox is closed
 * [SETTING] to add site exceptions: Ctrl+I>Permissions>Cookies>Allow
 * [SETTING] to manage site exceptions: Options>Privacy & Security>Permissions>Settings ***/
user_pref("network.cookie.lifetimePolicy", 2);
//Disabling disk cache is better, but try this if you like performance
   // user_pref("privacy.clearsitedata.cache.enabled", true);

//Clear data on shutdown
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.clearOnShutdown.cache", true);     // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.downloads", true); // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.formdata", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.history", true);   // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.sessions", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.clearOnShutdown.cookies", false);
   // user_pref("privacy.clearOnShutdown.siteSettings", false); // [DEFAULT: false]
// Manual wiping, such as the forget-me-not button
user_pref("privacy.cpd.cache", true);    // [DEFAULT: true]
user_pref("privacy.cpd.formdata", true); // [DEFAULT: true]
user_pref("privacy.cpd.history", true);  // [DEFAULT: true]
user_pref("privacy.cpd.sessions", true); // [DEFAULT: true]
user_pref("privacy.cpd.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.cpd.cookies", false);
   // user_pref("privacy.cpd.downloads", true); // not used, see note above
   // user_pref("privacy.cpd.passwords", false); // [DEFAULT: false] not listed
   // user_pref("privacy.cpd.siteSettings", false); // [DEFAULT: false]
// Delete everything ever.
user_pref("privacy.sanitize.timeSpan", 0);
//Delete history.
//Helps against forensic tools.
user_pref("places.history.enabled", false);

//WebGL is a security risk, but sometimes breaks things.
user_pref("webgl.disabled", true);

//Firefox stores passwords in plain text and obsolete if you use a password manager.
user_pref("signon.rememberSignons", false);
//Disable Pocket
user_pref("extensions.pocket.enabled", false);
// Disable Mozilla account
user_pref("identity.fxaccounts.enabled", false);

//Enable new tab per link
user_pref("browser.tabs.loadBookmarksInTabs", true);

**Comment by Thorin-Oakenpants** [comment]
For the record: arkenfox has only added four prefs this ESR cycle - that's 4 prefs in 8 releases - and two of those are at default in 109. So only two pref flips in reality. One of those is urlbar search suggestions which is not used until FF110. So only one pref flip to be more precise. And that is a linux geo pref that doesn't even get used unless you allow the site when it asks for your geolocation, which it doesn't do. This is excluding all those prefs we made inactive or removed.

Arkenfox is not the cause of your problem. You indicated it worked fine before (and AF v109 was only released a few days ago with NO new pref flip). So regardless of the FF release or the AF release, AF is not the cause.

And then you say you added a heap of overrides without understanding them and now websites break. There's your problem.

Here's a tip, the next time, disable all your extensions and see if that fixes it. i.e eliminate extensions being the cause, because if it an extension, then this will save you wasting time creating a new profile etc

> This is the network tab output 

I wanted the console tab, but nevermind, you pasted the results

> I can't see anything where I can enclose code

`````
   ```
   code goes here
   ```
`````

you can use ` ```js ` or ` ```html ` or ` ```yaml ` to specify the language

**Comment by Thorin-Oakenpants** [comment]
some quick notes about your overrides (not going through the whole thing) - not going to ask where this came from, but don't just add other people's shit - half the descriptions are misleading or factually wrong. Don't apply other people's shitty overrides to AF and then comes crying to me

sorry of I sound harsh, I'm being a bitch so others will be warned off (which saves me time long term)

remove this from your overrides - **_ IT DOESN'T EVEN EXIST ANYMORE_** and adding it with value 2 will cause you to MIGRATE a bunch of sanitizing prefs **_on every restart_** - meaning those same prefs in your user.js prefs can change from what you intended
```js
//Delete cookies on close, but see below to make exceptions
 ... etc
user_pref("network.cookie.lifetimePolicy", 2);
```

remove this from your overrides - **_ FFS this is already what AF sets_** (and it is way more than just disconnect's lists)
```js
//Use Disconnect's blocklist to block ads
user_pref("browser.contentblocking.category", "strict");
```

remove this from your overrides - **_FFS this is already what AF sets_**
```js
// Disable DRM
   // user_pref("media.gmp-widevinecdm.enabled", false);
user_pref("media.eme.enabled", false);
```

remove these from your overrides - **_FFS this is already what AF sets_**
```js
//Clear data on shutdown
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.clearOnShutdown.cache", true);     // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.downloads", true); // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.formdata", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.history", true);   // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.sessions", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.offlineApps", false); // [DEFAULT: false]
```

remove these from your overrides - **_FFS this is already what AF sets_**
```js
// Manual wiping, such as the forget-me-not button
user_pref("privacy.cpd.cache", true);    // [DEFAULT: true]
user_pref("privacy.cpd.formdata", true); // [DEFAULT: true]
user_pref("privacy.cpd.history", true);  // [DEFAULT: true]
user_pref("privacy.cpd.sessions", true); // [DEFAULT: true]
user_pref("privacy.cpd.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.cpd.cookies", false);
   // user_pref("privacy.cpd.downloads", true); // not used, see note above
   // user_pref("privacy.cpd.passwords", false); // [DEFAULT: false] not listed
   // user_pref("privacy.cpd.siteSettings", false); // [DEFAULT: false]
// Delete everything ever.
user_pref("privacy.sanitize.timeSpan", 0);
```




remove these from your overrides - **_FFS this is already what AF sets_**
```js
//Enable Mozilla Container Tabs
//Redundant with Total Cookie Protection, but useful if you have multiple accounts
//with the same provider (e.g. a work Google account and a personal Google account)
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.ui.enabled", true);
```

remove this from your overrides - it has NOTHING to do with bookmark icons. It is about shortcuts to URLs dragged and dropped to the system (shell)
```js
//Enable favicons, the icons in bookmarks
user_pref("browser.shell.shortcutFavicons", true);
```

remove these from your overrides - this does nothing to stop "phoning" home to google's safe browsing API - you will still get local lists updated. And updating local lists is not a privacy issue. So all you are doing is removing a layer of security
```js
//Disable Safe Browsing, this phones home to Google.
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
```

remove this from your overrides - it is pointless, read 2001 (in fact I am going to move it the DON'T BOTHER section)
```js
//WebRTC settings, things like video calls
user_pref("media.peerconnection.enabled", false);
```

remove this from your overrides - I assume you want to ensure that DoH is never used - i.e EXPLICITLY OFF? Well, it's off unless you are in USA, Canada, Russia or Ukraine. In which case you get a prompt to use DoH and can say no. Of course if you want to ensure you don't get asked, then 5 is fine, but the way the override is written, it doesn't sound like this is what you wanted?
```js
//DNS over HTTPS
//Protects web requests from an ISP
//Please pick a provider you trust.
//Disable if you use PiHole, but tools like pfBlocker work fine.
// Cloudflare (default in US & Canada).
//Quad 9: https://dns.quad9.net/dns-query
user_pref("network.trr.mode", 5);
```

holy shit, I think I'll stop there

**Comment by Thorin-Oakenpants** [comment]
here's your overrides. delete the other one. replace it with this. run the updater, run prefsCleaner

```js
user_pref("_user.js.parrot", "linxgirl overrides: START");

// make sure I am not prompted for any DoH roll out
user_pref("network.trr.mode", 5);

// I want IPv6
user_pref("network.dns.disableIPv6", false);

// enable search via urlbar when typing just words + enable LIVE sugestions (search per keystroke)
user_pref("keyword.enabled", true);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);

// enable disk cache: ram is faster but disk may help with heavy sessions
user_pref("browser.cache.disk.enable", false);

// make each and every media user-initiated (0=sticky (default), 1=transient, 2=user)
user_pref("media.autoplay.blocking_policy", 2);

// keep EVERY single site's cookies + site data to track me first party FOREVER
user_pref("privacy.clearOnShutdown.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.clearOnShutdown.cookies", false);

// don't ever collect history (even though arkenfox clears all history on close)
user_pref("places.history.enabled", false);

// don't ask me to save passwords
user_pref("signon.rememberSignons", false);

// disable pocket account buttons
user_pref("extensions.pocket.enabled", false);

// disable Mozilla account buttons
user_pref("identity.fxaccounts.enabled", false);

// enable new tab per link
user_pref("browser.tabs.loadBookmarksInTabs", true);

user_pref("_user.js.parrot", "linxgirl overrides: SUCCESS");
```

**Comment by Thorin-Oakenpants** [comment]
did you really want to do this ?
```js
// keep EVERY single site's cookies + site data to track me first party FOREVER
user_pref("privacy.clearOnShutdown.offlineApps", false); // [DEFAULT: false]
user_pref("privacy.clearOnShutdown.cookies", false);
```

these should be removed, arkenfox sets them as true. And if you want to keep specific websites' cookies/sitedata then you add them as exceptions - see the wiki common page

---

did you really want to do this?
```
// don't ever collect history (even though arkenfox clears all history on close)
user_pref("places.history.enabled", false);
```

this just means you have zero history, recover from a crash, navigation back/forwards etc in your session. We already sanitize history on close.

---

did yo really want to do this?
```js
// enable disk cache: ram is faster but disk may help with heavy sessions
user_pref("browser.cache.disk.enable", false);
```

your original (copied) comment said to use disk for performance reasons - this is debatable (too many parameters/scenarios). Can you honestly tell any difference - I can't)


---

this is fine - you can use a password manager for syncing, or choose not to use anything - but I just want to point out that your (copied) comment said FF stores passwords in plain text - which is not true - if you did use lockwise, then you would surely put a master password on it. If you don't need password syncing then there is nothing too much wrong with FF's built in lockwise

```js
// don't ask me to save passwords
user_pref("signon.rememberSignons", false);
```

**Comment by Thorin-Oakenpants** [comment]
closing as invalid, but feel free to let me know that it was an extension causing it

**Comment by linuxgirl22** [comment]
Did you say anything regarding what is causing the 2 pages to not show? Or too busy blasting a first time arkenfox user/poster? Extensions weren't in the way 2 weeks ago and I run the bare minimum. I'll not post again, as I find tech stuff very difficult and had made an effort, plus included a 'lol' at myself while posting ie knew it was possibly not a good move to copy/paste. Yet you've said the overrides mostly contain what's in arkenfox, so I wasn't as dumb as you seem to have judged me. 

I have no idea what's blocked the 2 pages, and that's a genuine security concern and not invalid, as I'm not sure if mullvad are starting to add suspect stuff onto pages/whether I can trust. I'll just use a different resource, and hope that arkenfox is also trustworthy. Certainly can't be trusted to be polite.

**Comment by rusty-snake** [comment]
So what was it? `media.peerconnection.enabled`?

**Comment by Thorin-Oakenpants** [comment]
> Did you say anything regarding what is causing the 2 pages to not show?

No, because I cannot reproduce - that's up to you to troubleshoot your own mess.

I have no idea what prefs not listed you may have changed e.g. via about:config or the UI. I also have no idea what extensions you use. Based on the prefs shown, I couldn't see anything that stood out, and based on the canvas blocker console error, I suspected it might be an extension (which is the first thing you should rule out without me having to even consider it - see the wiki - I even wrote a guide on troubleshooting)

> what's blocked the 2 pages, and that's a genuine security concern and not invalid

the invalid label means this is not a valid arkenfox issue, not that the problem doesn't exist. Also broken pages are not a security concern

> Yet you've said the overrides mostly contain what's in arkenfox, so I wasn't as dumb as you seem to have judged me.

I never said you were dumb. I said not to blindly just copy other (random) lists from elsewhere - which look like they have been copied from arkenfox anyway, with descriptions altered. What I write here is for everyone, not just you. Don't take things personally.

> Certainly can't be trusted to be polite.

did you not read this : "sorry of I sound harsh, I'm being a bitch so others will be warned off (which saves me time long term)"

---

I spent time answering your questions. I spent time pointing out things such as how to show `code`, I gave tips on troubleshooting, I spent time checking that overrides list. I spent time writing you a new overrides with proper descriptions (which actually fixed your issue). I spent time telling you how to apply it cleanly with an update and prefscleaner. I spent time checking if what you had in the new cleaner overrides I wrote you was what you actually think they are - to make sure you weren't making things worse

I actually wrote a wiki on troubleshooting - and the issue template points to that and it lists all the steps you can take before posting an issue - but you ignored the issue template and deleted it - I should have just closed this issue as invalid as soon as you posted it

The whole reason I wrote the wiki and and enforcing (usually) that people follow instructions, is because otherwise it wastes my time - and lo and behold, this whole issue has been a colossal waste of my time

In future, all invalid issues will be terminated with prejudice - READ THE WIKI and FOLLOW THE ISSUE RULES
