### ISSUE TITLE
Uploading files doesnt work

### ISSUE THREAD

**Issue by firefoxlover** [arkenfox/user.js#1630]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox Flatpak 109.0.1 Fedora KDE
  - Steps to Reproduce (STR): try to upload a file to Github or anywhere else
  - Expected result: uploading normally
  - Actual result: upload fails
  - Console errors and warnings: 
  - Anything else you deem worth mentioning: this doesnt happen on a vanilla profile

---

**Comment by Thorin-Oakenpants** [comment]
When did this start happening? Where are you uploading the file from (e.g. a UNC - see pref `0703`)? What does the console say? Does this happen in a flatpak Firefox with no arkenfox and no extensions?

**Comment by firefoxlover** [comment]
this doesnt happen in flatpak firefox vanilla.

I upload from my normal file directory, picked by the file chooser. The file loads in the browser and the website even sees the name, but then it crashes.

**Comment by firefoxlover** [comment]
It doesnt happen on a vanilla profile using flatpak.

I try to upload a file to a website, the filechooser opens, the file is chosen and also displayed on the website but an error occurs when uploading the file.

I didnt get infos when running the flatpak from the commandline and dont know how to use the console, was filled with referrer messages thats it.

**Comment by Thorin-Oakenpants** [comment]
I'm going to ask this to save time, even though you said you read and tried the wiki troubleshooting

Did you disable all extensions

> but then it crashes

what crashes? The website or Firefox?

> dont know how to use the console

if it's not Firefox crashing then ...

do this
- load the site in question to the point where you are about to start uploading a file, i.e not selected to do so, just on the page where you can click `upload` or whatever
- open the console for that page - ctrl-shift-K
- make sure you are on the `console` tab
- make sure `errors`, `logs`, `debug`, `xhr`, `requests` are all enabled (you toggle them by clicking them, when they are enabled they have a button looking background)
- now upload your file and await the "crash"
- what does the console show

> Server is missing xdg_foreign support

have you changed any other settings in about:config

---

not expecting OP to look at these, they are listed here as relevant bugzillas (same error codes) I found

https://bugzilla.mozilla.org/show_bug.cgi?id=1639575 [Wayland/Sway] File chooser dialog doesn't show up anymore
https://bugzilla.mozilla.org/show_bug.cgi?id=1745174 Open/Save dialogs crash with MOZ_ENABLE_WAYLAND=1

**Comment by Thorin-Oakenpants** [comment]
feel free to answer
