### ISSUE TITLE
TC is now official unmaintened, hoping for a fork

### ISSUE THREAD

**Issue by rusty-snake** [arkenfox/user.js#1633]
- https://github.com/stoically/temporary-containers/issues/614
- https://github.com/stoically/temporary-containers/issues/618

**Comment by Thorin-Oakenpants** [comment]
that sucks - I edited the wiki and we'll see what happens in the future - not moving it to don't bother (yet) after all the fuss of getting up into optional - we can revisit it later

**Comment by ProgramminCat** [comment]
https://github.com/stoically/temporary-containers/issues/634#issuecomment-2351852094
