### ISSUE TITLE
# 7013

### ISSUE THREAD

**Issue by GitHugz** [arkenfox/user.js#1634]
Hello, this is not exactly a problem, but I could not locate a better location to place this (plz lmk if elsewhere is preferred should I find more additions in the future). 

User Preference 7013 is written as:
/* 7013: disable Clipboard API
 * [WHY] Fingerprintable. Breakage. Cut/copy/paste require user
 * interaction, and paste is limited to focused editable fields ***/
   // user_pref("dom.event.clipboardevents.enabled", false);
   
Clipboard privacy has been of interest to me, so I have been reading how FireFox handles it. I noticed there have been a few bugs discussed wrt this preference when false:
Discussion 1 (Closed/Merged): https://bugzilla.mozilla.org/show_bug.cgi?id=1312898
Discussion 2(Open): https://bugzilla.mozilla.org/show_bug.cgi?id=1684461

This setting appears to effect popular social media sites such as Facebook & Twitter. While I personally do not use these sites, given their popularity, I figured you may want to include this bug within the preference (as you do so with other potential bugs).

Cheers

**Comment by Thorin-Oakenpants** [comment]
see #1081 - also 7013 it is clearly in the `DON'T BOTHER` list with a WHY, and the WHY says "breakage" - nothing more needs to be added about this and not going to waste space on this section. The section exists to educate users and all the prefs are inactive so they are reset with prefsCleaner. If someone wants to ignore all that then that's on them

https://bugzilla.mozilla.org/show_bug.cgi?id=1312898 is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1104117 which is how when you disable the API it breaks functionality (well of course, duh). https://bugzilla.mozilla.org/show_bug.cgi?id=1684461 is the same, disable the API and the feature breaks - what the heck do people expect to happen when they disable functionality.
