### ISSUE TITLE
is request/response integrity and credentials discussion eroding privacy?

### ISSUE THREAD

**Issue by securingmom** [arkenfox/user.js#1639]
As it evolves

`https://github.com/wintercg/fetch/issues/6`

Munged to avoiding pinging issue.  Clearly not well enough.   Ping sent.

**Comment by Thorin-Oakenpants** [comment]
IDK what you're asking me to do

I'm not even sure what the issue us about TBH - just looks some some list - I'm sure the network nerd fish 🎣  fxbrit is into it, but this is out of scope and I fail to see what I can do (even if I understood all of it)

In terms of navigational tracking, such as referer, there isn't much we can do except cross-site block all and whitelist (still looking for a decent extensions as a better alt to cross-site block all)
