### ISSUE TITLE
broken after using updater.sh something something

### ISSUE THREAD

**Issue by hbednar** [arkenfox/user.js#1642]
After updating to the latest version using updater with the below arguments some web pages and firefox extensions are broken.
`updater.sh -b -s -p .mozilla/firefox/Profile.default`

I have tried a new firefox 112.0b2 profile with arkenfox user.js v110 and no other changes and its still broken.

Example websites:
https://rclone.org/install/
https://repology.org/projects/

**Comment by earthlng** [comment]
This doesn't sound like an updater problem

**Comment by Thorin-Oakenpants** [comment]
the example websites work for me
