### ISSUE TITLE
Firefox opens maxmised but is actually windowed

### ISSUE THREAD

**Issue by FREDDIERAMBO** [arkenfox/user.js#1643]
Arkenfox is mostly default with some minor overrides. As you can see firefox opens like this with a blue line across the top of the screen.

![Screenshot 2023-03-15 210748](https://user-images.githubusercontent.com/36176591/225633465-9b5e8f72-0844-44a0-bc66-922af2986979.png)
[user-overrides.txt](https://github.com/arkenfox/user.js/files/10991369/user-overrides.txt)

**Comment by fxbrit** [comment]
it would help if you could follow the issue template, it lets us know your setup. also, I think you attached the user.js instead of your overrides.

**Comment by Thorin-Oakenpants** [comment]
> Apologies but I don't see a template

go to https://github.com/arkenfox/user.js/issues/new/choose and click `get started` on `Troubleshooting help` - it will load like [this](https://github.com/arkenfox/user.js/issues/new?assignees=&labels=&template=troubleshooting-help.md&title=follow+instructions+or+this+will+be+closed+as+invalid)

```
<!--

Issues will be closed as invalid if you do not troubleshoot first, or if you ignore the required info in the template.

We do not support forks or no-longer supported releases.

-->


🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS:
  - Steps to Reproduce (STR):
  - Expected result:
  - Actual result:
  - Console errors and warnings:
  - Anything else you deem worth mentioning:

---

```

**Comment by Thorin-Oakenpants** [comment]
> Also I copy and pasted user-overrides.js to a text file, so I could upload it here

the attached file is the user.js, not your user-overrides.js

**Comment by Thorin-Oakenpants** [comment]
do the following
- open FF
- go to about:config
- change `privacy.resistFingerprinting` to false
- change `privacy.resistFingerprinting.letterboxing` to false
- load https://arkenfox.github.io/TZP/tzp.html#screen
- take a full desktop screenshot - edit out any personal info like your taskbar time, any bookmarks e.g. embarrassing sites like pokemon and pikachu
- flip the two prefs back (or they will just reset on next start if you didn't change them in overrides)

attach the screenshot. Sounds like a waste of time, but the easiest way for me to work things out is to actually measure pixels in images

This sounds like #1618

**Comment by Thorin-Oakenpants** [comment]
feel free to do the test I laid out in the previous comment

OP doesn't tell me if this starting happening this release, or has always been this way. The pic has an image size of 1919 x 1036 - which lead me to believe the res is 1920 x 1080, and since we start at 1600 x 900 there should be plenty of room - but screenshots don't have to use native resolution, so for all I know system scaling is on.

Closing. If OP can provide info, then feel free to reopen

**Comment by FREDDIERAMBO** [comment]
> 

Hi I think the issue here is actually my user-overrides.js not being properly set up. I have ressolved this by starting fresh.
