### ISSUE TITLE
Firefox increased list of known tracking parameters

### ISSUE THREAD

**Issue by Lostname777** [arkenfox/user.js#1655]
Firefox recently increased its URL tracking protection list in update: https://www.mozilla.org/en-US/firefox/112.0/releasenotes/
Doesn't it now make the AdGuard URL Tracking Protection list in uBO mentioned in the Wiki redundant?

I hope I will not get a beating for asking something Pants already know : |

**Comment by Thorin-Oakenpants** [comment]
nope, because it's PB mode only by default

**Comment by Thorin-Oakenpants** [comment]
wait, wot are you talking about?

**Comment by Thorin-Oakenpants** [comment]
the asset has 1445 lines in my uBO. IDK what exactly ETP Strict is covering. Extensions play nice with ETP, and it;s not worth comparing these lists

**Comment by Lostname777** [comment]
@rusty-snake are these the new ones added in 112 version?

**Comment by Lostname777** [comment]
@Thorin-Oakenpants I know now this issue is closed. Wanna ask something. How to do better in engineering. Understanding mathematics concepts in order to solve high level problems, not too high though. How to just work with that mindset of an engineer. Looking at you, who just rolls out random shitty codes and jargon which i don't understand and that BS attitude, I am truly inspired. Want to be like you

**Comment by rusty-snake** [comment]
To the best of my understanding (Firefox is complex and changes fast), this is the list  of parameters stripped by default by Firefox (I.e. all parameters not only the new ones).


Docs: https://firefox-source-docs.mozilla.org/toolkit/components/antitracking/anti-tracking/query-stripping/index.html

**Comment by Thorin-Oakenpants** [comment]
> Want to be like you

Nooooooooo. I'm a terrible role model or aspiration. Wouldn't you rather be plain and fit in with the crowd like @fxbrit 😀 

I'm not an engineer
I'm not a mathematician
I drink and I know things

**Comment by Lostname777** [comment]
> Nooooooooo.
N
　 O
　　　 O
　　　　 o
　　　　　o
　　　　　 o
　　　　　o
　　　　 。
　　　 。
　　　.
　　　.
　　　 .
　　　　.

> I'm a terrible role model or aspiration
Every great person would say that.

> Wouldn't you rather be plain and fit in with the crowd like @fxbrit 😀
I tried. And I failed, plain doesn't suit me. Gone through deep darkness and despairs of depression, darkness covered by darkness. Then some great teacher taught me how to learn and derive, understand and apply. And when I see people like you, I really gets heightened in my spirit to know more.

> I'm not an engineer
I'm not a mathematician
Well I don't agree with that. Seeing your knowledge in technical stuff and terminologies, I think you are. You are certainly intellectual (and wetty, oh I mean witty 💀)

> I drink and I know things
I will not drink tho. haha. .......
.....
FBI!!! ................................ F.....c.K!....OPEN UP!...!!!!

Jokes aside, I will be looking forward for some tips!

**Comment by Thorin-Oakenpants** [comment]
OK, here goes

> In order to complete your side quest, find your closest Chinatown. Then look for an old wise woman and tell her you want what's in the back. She will then send you on another more important quest to retrieve the staff of a thousand fires. This quest will be longer and more arduous than your first, but if you can find a good paladin warlock it can make things manageable. Once you defeat the undead soldier of the sands of time and receive the staff you must bring it back to the old wise woman. DO NOT fall victim to its power. It's best to just put it in your bag of holding and forget about it. Once all is complete then you are ready for step one.

**Comment by fxbrit** [comment]
> fit in with the crowd

ever seen a fish on Carnaby Street? don't think so

**Comment by Thorin-Oakenpants** [comment]
never been to London, what's your excuse
