### ISSUE TITLE
Address bar search  issue

### ISSUE THREAD

**Issue by o2rhkzqx** [arkenfox/user.js#1658]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
-  ☑️ I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 111.0.1 (64-bit), Windows 11
  - Steps to Reproduce (STR): When I type anything in address bar firefox automatically adds https:// to it.
  - Expected result: If I search for Game it should not make it as address url and give error instead it should populate with the searched results.
  
![image](https://user-images.githubusercontent.com/104969742/232340324-25f42f57-9cc2-4c02-8d12-b1a70343cd44.png)

  - Actual result: If I search for games it will autocompletes and makes it as https://games thus gives error 
![image](https://user-images.githubusercontent.com/104969742/232340078-fc408d50-dc1e-4fed-9047-9834e853e695.png)

  - Console errors and warnings: NA
  - Anything else you deem worth mentioning: I have tried enabling user_pref("browser.urlbar.autoFill", false); in user.js but still having the same issue.

---

**Comment by Thorin-Oakenpants** [comment]
did you really read the wiki?
- https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]#-common - `0801`
