### ISSUE TITLE
How best to start a new life with AF

### ISSUE THREAD

**Issue by git70** [arkenfox/user.js#1659]
I'm installing a new Linux machine right now and I'm wondering when is the best time to start AF after creating a new FF profile:

Way 1:
a) I create a new FF profile (now there is only one file times.json in the folder)
b) I run FF (now FF creates all other profile files)
c) I close FF and put AF

or

Way 2:
a) I create a new FF profile
b) I do NOT run FF
c) I put AF into the profile folder in which there is ONLY times.json
d) I run FF

or

Way 3: No difference?

**Comment by Thorin-Oakenpants** [comment]
What do you gain by not running FF first and letting it create a proper full profile? This is a rhetorical question

Just install/unpack FF & run it then close it to create a profile. Now add the user.js, run FF, work out what shit you don't like/need from the wiki (see common overrides), create a user-overrides.js. run updater (so it appends your overrides to the user.js). restart FF.

AF doesn't give a flying donkey about profiles in so much as you can put it into ANY profile to take effect. Adding it _before_ everything else is set up by the app sounds like a recipe for nonsense

**Comment by Thorin-Oakenpants** [comment]
There's nothing wrong with mozilla's telemetry - it uses PRIO, and it uses GLEAN, and it doesn't collect any PII, and it helps decisions upstream (and I'm not talking pedantic UI changes) that benefit everyone. Opt-in doesn't work. I'm sure you can google why. There is no reason to distrust Mozilla here - you're using their product

Anyway, what on earth is opening FF then closing it going to record that is of any importance? You can always check about:telemetry and see exactly what is collected, and you can delete the contents of the `profile\datareporting` dir, and you can always set it up with the internet disconnected. But this whole discussion is based on nonsense. There's no issue here

**Comment by Thorin-Oakenpants** [comment]
> then why do we disable it in AF

this is something I have mulled over for years - i.e it is somewhat at odds with trying to keep the mission on statement - e.g see removal of most personal section items. Also see how we still enable Safe Browsing except the real-time binary checks. The "problem" is the user base: they just want a "quiet" fox and if I excluded them or made them inactive, then it would just bloat most user's overrides.

That said - I should get around to adding some context, maybe in a new section. A bit like the intro to SB
