### ISSUE TITLE
updater traverses $HOME

### ISSUE THREAD

**Issue by nycex** [arkenfox/user.js#1670]
Ever since #1651, updater.sh traverses the CWD when starting as non-root to check if it had been accidentally run as root.
This makes sense if the file is run from the dir updater.sh is in, but is wrong otherwise. For instance, if it is run as `~/.mozilla/firefox/abc.default-release/updater.sh` from $HOME, it runs a `find` traversing all of `~`.

**Comment by Thorin-Oakenpants** [comment]
not my area - am assigning to the other two members so it's no longer my problem :)

**Comment by PaulDoesDev** [comment]
Just commenting to say I'm also experiencing this and that the shell script is quite broken on macOS atm. Have reverted to an earlier version
