### ISSUE TITLE
The PKCS #12 operation failed for unknown reasons.

### ISSUE THREAD

**Issue by sh3ll4rpw** [arkenfox/user.js#1672]
When I try to import a selfsigned cert into firefox I get the following error: `The PKCS #12 operation failed for unknown reasons.`
Without arkenfox I got no error and everything works. I changed `security.nocertdb` to `false` but I still can't import the certificate.

I checked all options in user.js but I can't find the right one. Which pref I need to add/change?

**Comment by sh3ll4rpw** [comment]
SOLVED: I had to put the pref in user.js and reboot instead of changing it in about:config

**Comment by Thorin-Oakenpants** [comment]
Yup .. says it right there on the tin `[RESTART]`

https://github.com/arkenfox/user.js/blob/04e6e77439bfa6e3f6b7b9c5e0afac7f74f0586a/user.js#L895
