### ISSUE TITLE
Having trouble finding and retrieving my bookmarks. this started after Arken and I cant seem to crack the case

### ISSUE THREAD

**Issue by monerohelp** [arkenfox/user.js#1676]
hello folks, I have a Dell Xps 13 9310 running ubuntu mate. I feel like I set it up right, with only this bookmark thing being an issue. my bookmarks are very important to me as I do a ton of research and gather resources. I plan to start a self study program, just gotta find a way to recover all my passwords.

So I tried about:support and support:profile, I tried checking in my bookmark restorer or what it is, but I only have three to choose from. I did a search for "keywords" in my entire filesystem and tried import some, because tbh I have no idea how to fix this. I'm wondering if theres a way to rollback ubuntu mate for like 5 days. I hope you all can help me get my bookmarks

**Comment by 2glops** [comment]
Bookmarks or passwords ?

Bookmarks are automatically saved in /home/<user>/.mozilla/firefox/<profile>/bookmarkbackups
Anyway:
https://support.mozilla.org/en-US/kb/restore-bookmarks-from-backup-or-move-them

**Comment by Thorin-Oakenpants** [comment]
arkenfox doesn't alter bookmarks, it can't do this via user prefs - it cannot add any, or remove any, it is literally impossible

> this bookmark thing being an issue

what thing? did you add arkenfox to a new or existing profile? are you saying all your bookmarks are gone? are you saying that you can't get bookmarks to show in the urlbar as suggestions when you type a keyword?

I can't guess, so please be clearer
