### ISSUE TITLE
Problems with dragging to url/tabs to search, and change the homepage

### ISSUE THREAD

**Issue by cathouse7545** [arkenfox/user.js#1678]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [✅] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: 113.0.2 (flatpak). Linux mint 21.1 Cinnamon

Greetings, I'm new here and was hoping to find help with a couple of problems I'm having.

- The first is that I can no longer drag text to the url or tab bar to search, instead it is entered as a url. This works correctly in both tor browser and firefox without arkenfox.

- The second is that I can no longer freely set with gui a custom homepage, as it is cleared on every restart. It seems that I can only enter it from user-overrides.js by modifying both `browser.startup.page` and `browser.startup.homepage`. This doesn't happen in tor browser either, is this the expected behavior?

I also thought it was worth mentioning that in the wiki (5.2) they suggest to search via triage by editing user.js, however, updater.sh resets it and without internet it doesn't even work. Also, I could not get the troubleshooter script to work, and the demo video is down.

PS: Sorry for not using the template strictly, but it's a few things and I wanted to keep it clean.

**Comment by rusty-snake** [comment]
1. Read. https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-common
2. Yes. For Browser does not user.js and can use defaultPref to change the default value of a pref rather changing it by user request.

**Comment by Thorin-Oakenpants** [comment]
> I also thought it was worth mentioning that in the wiki (5.2) they suggest to search via triage by editing user.js, however, updater.sh resets it and without internet it doesn't even work

what? These are using TEST profiles. Why are you updating test profiles? Even if it was your real profile, Arkenfox doesn't autorun any updater scripts - that's all on you to control

**Comment by Thorin-Oakenpants** [comment]
> Also, I could not get the troubleshooter script to work, and the demo video is down.

@earthlng FYI
