### ISSUE TITLE
Question only re settings for startup in Home Page

### ISSUE THREAD

**Issue by thorrrr** [arkenfox/user.js#1679]
Hello 
Sorry i am trying to get FF to set a static page as a default home page.
I am going to HOme in settings  and i am openeing the page i want as default
I set Homepage and new windows as custom url
then set as use currrent page which it does.
But whe i hit the home icon i keep getting a blank page and when i restart FF it has gone back to blank page.
It must be a setting but i have have read through it but cannot see it 
PLease can you point me to the line or advice how i can get this bit to work?

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/04e6e77439bfa6e3f6b7b9c5e0afac7f74f0586a/user.js#L86-L89

it's basically one of the first items in the user.js, or if you searched for HOME, you know ....

add to your overrides
```js
/* i want a custom URL as my home page */
user_pref("browser.startup.homepage", "https://somesite.com/whatever/");
```

overrides go in a [separate file](https://github.com/arkenfox/user.js/wiki/3.1-Overrides) and [you run the updater to append them](https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain#-update)

**Comment by thorrrr** [comment]
cheers
