### ISSUE TITLE
wiki: installing Arkenfox user.js causes data loss

### ISSUE THREAD

**Issue by WillemMali** [arkenfox/user.js#1690]
### Steps to reproduce:

* read `README.md`
* read wiki home and pages 1 and 2.1 and even 2.2
* install user.js and restart browser
* close browser
* **POOF!**

### Actual result:

All session data and browser history have been erased with no warning.

### Expected result:

*No loss of data without forewarning*. Either solid warnings in the very first part of the docs, or making the relevant sections of the `user.js` opt-in. There's nothing in the wiki or in the `README.md` about this `user.js` "only being for fresh installs" or something equivalent to that.

I don't even understand what erasing browser history would have to do with "enhancing" privacy or security, but it's certainly outside the realm of "while minimizing any loss of functionality and breakage (but it will happen)" - this default behavior is beyond breakage or loss of functionality.

### Suggested change:

Put advisory to back up your data and a warning that installing Arkenfox user.js *will otherwise result in data loss* right in the `README.md` and on the first page of the wiki that it links to.

As a side note: `README.md` links to page 2 of the wiki. That's a little odd, if there's a conflict between wiki page 1 and the `README.md` some information may be good to swap around between these two pages. I'm mentioning this because this makes it unclear where to put the warning I'm suggesting exactly, e.g. if it should be in wiki page 1, page 2, `README.md`, or a combination of these three.

Additionally, clarify in wiki page 2.1 - Backup, that installing Arkenfox `user.js` *will result in instant data loss* if you normally store browser history. There isn't any clue on the wiki home page, page 1, page 2.1, or page 2.2 that actual user data, not just browser preferences, will be deleted by Arkenfox `user.js` by default.

Alternatively: disable "delete cache/history on browser close" by default and make it entirely opt-in.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/1.1-to-arkenfox-or-not
> If you're going to use arkenfox's user.js, then don't expect to just start using it as is. You WILL NEED TO CREATE OVERRIDES, and FULLY read this wiki.

So you didn't fully read the wiki

https://github.com/arkenfox/user.js/wiki/2.2-Backup
- did you do a backup? You would if you read the wiki

https://github.com/arkenfox/user.js/wiki/3.1-Overrides
- did you create some overrides?

https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]
> Summary: These few items, out of 110+ pref changes, will solve 99% of usability issues and you only need to do it once. You can always undo things - except deleted items (such as cookies, history and session restore), so read the entire page!

REPEAT

**You can always undo things - except deleted items (such as cookies, history and session restore), so read the entire page!**

Did you read the user.js
>          e.g. some user data is erased on exit (section 2800), change this to suit your needs

Also, you didn't use the template. Not my fault you can't read or follow instructions
