### ISSUE TITLE
Can the user.js be installed?

### ISSUE THREAD

**Issue by NovatoMayor** [arkenfox/user.js#1691]
I apologize as I have been looking but I don't see how to do it.

Can you install user.js on a non-rooted Android? And on Windows?

An acquaintance told me that without root on Android you can not use Mull.

But I wanted to ask if there is any possibility to install it?

Thanks for your help

**Comment by iam-py-test** [comment]
> And on Windows?

Yes: you can install it on Windows

**Comment by Thorin-Oakenpants** [comment]
AF is not designed for android

**Comment by rusty-snake** [comment]
This does not stop people from doing it anyway :smile:.
