### ISSUE TITLE
Disable creation of `<BrowserName> Private browsing` shortcut

### ISSUE THREAD

**Issue by kowith337** [arkenfox/user.js#1698]
I can't remember which version of Firefox start to create private browsing shortcut automatically in Windows start menu, but see that prefs appear in #1572 with `browser.privateWindowSeparation.enabled` are set to `true`
I've searched about how to stopping its shortcut to be created and found ~~Red~~[Teddit](https://teddit.no-logs.com/r/firefox/comments/xkv92o/firefox_keeps_creating_a_shortcut_in_start_menu) posts that tell to change this prefs to `false`, trying it and seems it work as intended.
Because I'm using any browsers as semi-portable, it means that I won't install into program files, creating such shortcut is seems **Not OK**!

### To reproduce:
1. Start over like you didn't install Firefox previously or create fresh profile, deploying `user.js` in profile or `cfg` file in program folder is optional because that prefs didn't added in yet.
> - It's mean that you aren't have any existing profiles of Firefox before.
> - Otherwise, you can use other forks that surely didn't used yet, e.g. Librewolf, Mercury.
2. Launch browser
3. When you press Window Start button, you will see badge of new shortcut was created at start menu, then open app lists and you can found private browsing shortcut layed in there.

**Comment by Thorin-Oakenpants** [comment]
This has nothing to do with AF's core mission and is out of scope. Just delete the shortcut, it's only created once AFAICT (I also get rid of them, and I have installed Nightly + Dev, and portables for Beta + Stable, and a test suite of every portable release all the way back to FF52)
