### ISSUE TITLE
question: disabling quicksearch popup when pressing some keys

### ISSUE THREAD

**Issue by mhdna** [arkenfox/user.js#1699]
Hi, 

How can I disable the quicksearch popup when I type something in some webpage? As it's really annoying to have, especially when having some fullscreen video open then pressing "]" for example, then the popup appears so I have to press escape which does exit the quicksearch popup but unfullscreens the video as well.

I made some search through the user.js file, but such option doesn't look super clear to me, and this is not the default behavior in Firefox.

Thanks in advance!

**Comment by Thorin-Oakenpants** [comment]
what is a `quicksearch popup` ? - closing as invalid (not saying you don't have an issue) as I'm 99% sure this has nothing to do with arkenfox (clue: when I type something **_in some webpage_**). Happy to continue the discussion to help you out though

please follow the template when logging issues, which includes steps to reproduce

**Comment by mhdna** [comment]
It wasn't that I was too lazy to fill the template, it's just that I thought it's irrelevant and counterproductive for a very basic question like this.

I'm 99% sure this has something to do with arkenfox, as I've created a new barebone profile and this popup doesn't appear, then tried the default arkenfox user.js without any of my overrides or any of my Firefox plugins and the problem still exists.
 
Here's an example of how annoying this "quick search" or "quick find" (whatever they call it) is, when pressing some key in YT:

[arkenfox.webm](https://github.com/arkenfox/user.js/assets/76184333/df6cfcfa-aad3-44d9-8df7-aa6caafd97dc)

As you can see if I press any key (other than YT's shortcuts like `j` and `k`), I get this popup, and I can't get rid of it unless I press escape or use mouse.

**Comment by Thorin-Oakenpants** [comment]
> as I've created a new barebone profile and this popup doesn't appear, then tried the default arkenfox user.js without any of my overrides or any of my Firefox plugins and the problem still exists

cool, that's one of the steps in troubleshooting :) but AF doesn't alter defaults for shortcuts on a page - see ctlr-I>permissions

**Comment by rusty-snake** [comment]
You can try if `accessibility.typeaheadfind.manual = false` helps.

**Comment by Thorin-Oakenpants** [comment]
typing a char on a non-text area triggers the findbar - this is a FF setting in your UI

> about:preferences#general > Browsing > Search for text when you start typing

this is accessibility.typeaheadfind` - AF doesn't touch this

**Comment by mhdna** [comment]
This is what I'm talking about all the time!

Thank you guys, appreciate your help❤️.
