### ISSUE TITLE
Reset changes to defaults

### ISSUE THREAD

**Issue by HyperCriSiS** [arkenfox/user.js#1702]
Hi,

how can I reset all changes made by the arkenfox user.js to the Firefox default values?
I don't want to create a new FF profile, as this would be an insane amount of work with this many extensions and settings.

Thanks
Hyper

**Comment by Thorin-Oakenpants** [comment]
run prefsCleaner with Firefox closed, and then rename the user.js - it will reset EVERYTHING in the user.js

**Comment by Thorin-Oakenpants** [comment]
or you know .. BACKUP your profile so you can just role it back later
