### ISSUE TITLE
user.js v115 + Firefox 102ESR: Unable to see speed test info and results at https://speed.cloudflare.com 

### ISSUE THREAD

**Issue by docplastic** [arkenfox/user.js#1704]
Using user.js v115 + Firefox 102.14.0esr (64-bit) + Ubuntu 22.04 I am unable to see the test and the final results of the speed test info from Cloudflare: https://speed.cloudflare.com

Expected result: seeing the tests runing and the results shown
Actual result: besides the page template nothing more is shown

My user-overrides.js file:

edited by thorin

these will have no bearing on the test
```
user_pref("browser.sessionstore.interval", 1800000); // 1800000 milliseconds = 30 minutes
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("extensions.pocket.enabled", false); // disable Firefox Pocket
user_pref("signon.management.page.fileImport", true); // allow importing passwords from a CSV File

user_pref("browser.safebrowsing.downloads.enabled", false); // [0402]

user_pref("keyword.enabled", true); // // I using Startpage.com instead of Google [0801]

user_pref("dom.security.https_only_mode", false); // [1244]

user_pref("network.http.referer.XOriginPolicy", 0); // ## [1601]
user_pref("network.http.referer.XOriginTrimmingPolicy", 1); // ## [1602]

user_pref("media.eme.enabled", true); // ## [2022]

user_pref("privacy.window.maxInnerWidth", 1440); // ## [4502]
user_pref("privacy.window.maxInnerHeight", 900); // ## [4502]

user_pref("dom.event.contextmenu.enabled", false); // ## [7011] or, just use Shift-Right-Click

user_pref("security.ssl.require_safe_negotiation", false); // [1201] needed to login into some state (poorly setup) services
```

these should have an effect
```
user_pref("security.remote_settings.crlite_filters.enabled", false); // ## [1224]
user_pref("security.pki.crlite_mode", 0); // ## [1224]
```

these might be at fault
```
// Enable Cloudflare DNS over HTTPS (test it at: https://1.1.1.1/help)
// 0=default, 2=increased (TRR (Trusted Recursive Resolver) first), 3=max (TRR only), 5=off
user_pref("network.trr.mode", 2); // [0710] , should it be 3?
user_pref("network.trr.uri", "https://1.1.1.1/dns-query");
```

**Comment by rusty-snake** [comment]
Does it work w/o your overrides?

Does it work in a new profile w/o arkenfox? In a new profile with only arkenfox (no overrides, no extensions)?

**Comment by Thorin-Oakenpants** [comment]
works for me in my AF'd everyday FF

I suspect you're causing an issue with all your network pref and security overrides

**Comment by docplastic** [comment]
> Does it work w/o your overrides?
No.

> Does it work in a new profile w/o arkenfox?
Yes.

> In a new profile with only arkenfox (no overrides, no extensions)?
No.

> Also are the errors in the console or in the network tab?
Console error:
 Uncaught (in promise) TypeError: T(...).stop is not a function
    NextJS 2
Console Warnings:
 many warnings like (the byte value varies): Error fetching https://speed.cloudflare.com/__down?measId=9852444780706576&bytes=0: TypeError: r is undefined
 a few warnings like (the font name varies): Request for font "Open Sans" blocked at visibility level 1 (requires 3)

>     * esni is dead
>     * disabled crlite is a bad idea.
>     * https_only_mode has exceptions
>     * why do you set prefs that are FF115+?
I may be wrong and I am wrong many times, but the described problem also happens in a fresh FF + AF install over Ubuntu Linux 22.04.
I may be new to AF, but I have been a Linux user/syspop/programmer for the latest 25 years.

**Comment by docplastic** [comment]
> I suspect you're causing an issue with all your network pref and security overrides
 The described problem also happens in a fresh FF ESR + AF install over Ubuntu Linux 22.04.

**Comment by fxbrit** [comment]
some parts of this test seem to be using WebGL

**Comment by docplastic** [comment]
> some parts of this test seem to be using WebGL

Setting user_pref("webgl.disabled", false) did not help.

**Comment by docplastic** [comment]
> Can confirm the test working on 116 release but not 102esr.
> 
> See also: `https://old.reddit.com/r/firefox/comments/mgbid4/super_specific_to_speedcloudflarenet_but_what`

### SOLVED ###

Thank you Jee-Hex, that link showed the variable to be tweaked.

Adding:
 user_pref("privacy.resistFingerprinting", false);
to user-overrides.js allows to run the Internet speed test from https://speed.cloudflare.com.

**Comment by Thorin-Oakenpants** [comment]
OK, so RFP changed to 16.67 (60FPS) timing in FF102, so this is not necessarily the cause

```
   1692609 - reduce JS timing precision to 16.67ms (previously FF55+ was 100ms) (FF102)
```

I suspect it is more to do with fixing `performance.mark` and `performance.entries`, which was in FF111 [1811567](https://bugzilla.mozilla.org/show_bug.cgi?id=1811567)
- this `Uncaught (in promise) TypeError: T(...).stop is not a function` smells like it, but not worth digging

The problem with ESR115, is that ESR102 doesn't auto update users until EOL, and packages can lag. But still, in a few months all will be well

**Comment by docplastic** [comment]
I can confirm that in ESR115, AF works as expected and is able to run https://speed.cloudflare.com without problems.

 There is no need to set "user_pref("privacy.resistFingerprinting", false);"  anymore.

Thank you all.
