### ISSUE TITLE
logged out after firefox restart

### ISSUE THREAD

**Issue by Antarctic1337** [arkenfox/user.js#1705]
Hi,
I logged into YouTube yesterday. Everything was ok but whenever I restart my browser I have to log in again. The same with other sides. Except for Chatgpt, I somehow stay logged in.

I also tried the `privacy.clearonshutdown.cookies` etc. on false in the about: config.

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS:
  - Steps to Reproduce (STR):
  - Expected result: 
  - Actual result:
  - Console errors and warnings:
  - Anything else you deem worth mentioning:

---

**Comment by fxbrit** [comment]
We have a troubleshooting guide: https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D

**Comment by l1teng** [comment]
Hi, @Antarctic1337, have you solved this issue? The same to me, even when I add the sites (`https://www.youtube.com` and `https://accounts.google.com`) to Manage Exceptions.

**Comment by l1teng** [comment]
`reddit.com` has the same problem. I tried to inspect the cookies of the login sessions, and only found `https://www.reddit.com` from the cookies storage.

**Comment by l1teng** [comment]
I fixed the YouTube site, the solution is that `https://ogs.google.com` should be added to allow list.
