### ISSUE TITLE
Startup page takes effect into about:config but does not actually load

### ISSUE THREAD

**Issue by mich2k** [arkenfox/user.js#1706]
Hello! I'am trying to configure a mine `user-overrides.js` but after browsing the whole wiki, related issues etc I still do not manage to change the startup page, down are reported the steps I made

I also wanted to ask if there is any way to edit search engines (my goal is to switch from duckduckgo.com to start.duckduckgo.com in order to prevent the constant pop-ups that RFP gives back at every browser reboot)

To achieve this I also tried 
`user_pref("browser.startup.homepage", "https://start.duckduckgo.com/"); `
but still happens to load `about:blank` page (even if I am still trying into making this url the default also for the nav/search bar queries)

🟪 REQUIRED INFO
  - Browser version & OS: 116.0.3 (64 bit) on win11 
  - Steps to Reproduce (STR): Set `user_pref("browser.startup.homepage", "about:home");` in `user-overrides.js`
  - Expected result: Firefox opens at its homepage
  - Actual result: Browsing into about:config the field actually gets overridden but the startup page is still about:blank
  - Console errors and warnings: None both in +K & in +J

Appreciated any kind of help :)

![image](https://github.com/arkenfox/user.js/assets/13397578/5c88dac9-c34b-4fd8-b8f1-42484af561cd)

**Comment by Thorin-Oakenpants** [comment]
worksforme

not sure if you are doing what is in the image, but changing prefs (set by arkenfox) in about:config are session only, because every time firefox starts, the pref get written by arkenfox

what you do, as per the wiki
- put your overrides in a `user-overrides.js` file (in your profile directory), e.g.
- > ```js
  > user_pref("_user.js.parrot", "START: my overrides");
  > 
  > // change my start page and home page
  > // this does not change the newtab page
  > user_pref("browser.startup.homepage", "https://start.duckduckgo.com/"); 
  > 
  > user_pref("_user.js.parrot", "SUCCESS: my overrides");
  > ```
- run the updater
   - this will check for the latest version of arkenfox and update it if required
   - it will then APPEND your overrides to the END of the user.js
       - it does this so you don't ever lose your overrides
       - and adding them at the end means the last settings are applied last, i.e _your_ preference will override the arkenfox preference
- open firefox, it should work
- open about:config and type `parrot`, you should see e.g. `SUCCESS: my overrides`

---

search engines: arkenfox doesn't do anything with search engines for three reasons
- it's not AF's position to unilaterally decide what users should use
- even if we did, and we can't, not every firefox/regional install has the same search engines, and users can remove built-in search engines from being available
- there's a whole UI for users to configure search engines, knock yourself out

**Comment by Thorin-Oakenpants** [comment]
> in order to prevent the constant pop-ups that RFP gives back at every browser reboot

what pop-up?

**Comment by Thorin-Oakenpants** [comment]
FYI: a better solution for your startpage, which also makes newtab the same, is to set both to be `firefox home`, change your default search engine to DDG, and change the settings for the firefox home page to only show web search. This means that now you're not constantly loading DDG, only using it when you actually search. Note: as you type in the search field, it will jump you to the urlbar

here's an example - clean minimalist FF home page. My urlbar suggestions is limited (by choice), but if you have multiple search engines, it should also have entries for using any search engine you installed and have ticked. So it's really a better option that loading DDG _every. time. you. load. home. or. startup._

but you do you :)

![firefoxhome](https://github.com/arkenfox/user.js/assets/16656956/79804a45-3049-4274-887e-566b541481c7)

**Comment by Thorin-Oakenpants** [comment]
PS: don't be offended by the invalid label, it's to weed out noise for those searching/looking for answers

**Comment by mich2k** [comment]
>  but changing prefs (set by arkenfox) in about:config are session only,

I just opened about:config to show that the user-override is applied but the homepage is the blank one yet

With "swtiching search engine" I was referring to this, since arkanfox cleans cookies at every startup but actually I just discovered how hard is to change search engine in firefox is ( https://bugzilla.mozilla.org/show_bug.cgi?id=1683969 ) and since the default ddg from the dropdown menu in firefox settings shows a lot of pop ups becomes a very annoying experience to search actually

Maybe I will just allow cookies for DDG not being able to change to start.ddg 

I already tried setting the ff default as homepage editing 0102 and 0103

`ser_pref("browser.startup.page", true);`

`user_pref("browser.startup.homepage", "about:home");`

![image](https://github.com/arkenfox/user.js/assets/13397578/8268b3c0-5200-41ad-8d2f-a890eb21183f)

**Comment by rusty-snake** [comment]
> user_pref("browser.startup.page", true);

This should be an integer and not a boolean.

**Comment by mich2k** [comment]
> > user_pref("browser.startup.page", true);
> 
> This should be an integer and not a boolean.

I tought was the same, works thanks
