### ISSUE TITLE
follow instructions or this will be closed as invalid

### ISSUE THREAD

**Issue by dude4fox** [arkenfox/user.js#1723]
When importing bookmarks to a new profile (with/without arkenfox user.js) - each bookmarked website is pinged immediately after import. Lots of bookmarks/lots of chatter. 
Note: same result with the mullvad browser. 

Questions:

How/should I prevent this?

Should I even care - i.e. is this a pRiVacY issue? - I close often and employ a VPN.

Thank you for the repo. 
Apologies if this is invalid or out of scope. 

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [ ] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: macOS 13.5.2
  - Steps to Reproduce (STR): restore bookmarks file from via FF interface from previous FF profile
  - Expected result: successful import of bookmarks/no network chatter
  - Actual result: successful import of bookmarks, with the addition of network requests(?) to all bookmarked websites
  - Console errors and warnings: n/a
  - Anything else you deem worth mentioning: n/a

---

**Comment by rusty-snake** [comment]
> How/should I prevent this?

Disconnect the (WLAN) network cable and start the import.

> pRiVacY

¿?¿

**Comment by dude4fox** [comment]
>Disconnect the (WLAN) network cable and start the import.

of course. 

>Should I even care - i.e. is this a pRiVacY issue? - I close often and employ a VPN.

^^ and this?

thanks

**Comment by rusty-snake** [comment]
Depends ... on your threat model.

**Comment by dude4fox** [comment]
rock n roll

no need to keep this open - just noticed I did not rename the issue title correctly either.. oops

thanks again
