### ISSUE TITLE
small debloat settings

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1738]
> Firefox privacy, security and anti-tracking: a comprehensive user.js template for configuration and hardening 

I know that this is not really the purpose of this project, so I can understand if this doesn't get approved

I have a few suggestions to debloat the look and feel of firefox, which can be used by `user-overrides.js`
```
user_pref("browser.toolbars.bookmarks.visibility", "always"); // Always Show Bookmarks
user_pref("extensions.pocket.enabled", false); // Disable Pocket
user_pref("identity.fxaccounts.toolbar.enabled", false); // Hide Account Icon
user_pref("browser.tabs.firefox-view", false); // Hide Firefox View from tabs
```

**Comment by Thorin-Oakenpants** [comment]
no thanks
- bookmarks toolbar has a UI (right click) and is not a privacy issue
- pocket is not a privacy issue, it does nothing unless you have an account, and you can hide the button or whatever - I am not here to add barriers (e.g. for those that sign up for pocket)
- same with accounts, not a privacy issue, you can hide the button or whatever not the menu), and disabling it just another obstacle in front of those that use the service, which itself is not a privacy issue
- firefox view is tied to accounts

this is not "bloat", it's just code lying around that doesn't get used
