### ISSUE TITLE
a few more telemetry lines

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1739]
```
datareporting.healthreport.service.enabled
datareporting.sessions.current.clean
devtools.onboarding.telemetry.logged
toolkit.telemetry.hybridContent.enabled
toolkit.telemetry.prompted
toolkit.telemetry.rejected
toolkit.telemetry.reportingpolicy.firstRun
toolkit.telemetry.unifiedIsOptIn
```

Information: https://github.com/K3V1991/Disable-Firefox-Telemetry-and-Data-Collection
Additional information: https://gist.github.com/0XDE57/fbd302cef7693e62c769

**Comment by rusty-snake** [comment]
Are they no covered by the master switches?

**Comment by rusty-snake** [comment]
> Forgot about https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/blob/master/Files/FireFox%20Configuration%20Files/mozilla.cfg
Some of those aren't included in Arkenfox, is there a reason?

This file contains a lot of FUD, outdates prefs, wrong statments, prefs that make your FP stand out more from the mass and a lot of web breakage. Are there any concrete prefs you want to know about. Otherwise ignore this source, :jeans: is the wise.

**Comment by Thorin-Oakenpants** [comment]
Can you show me where any telemetry is gathered and sent? Rhetorical Q

**Comment by Thorin-Oakenpants** [comment]
> Can you show me where any telemetry is gathered and sent? Rhetorical Q

just stop. FFS - clean out your telemetry folder first, as you will have some shit in there from before you apply arkenfox - look in about:telemetry.  You can also delete everything in the datareporting dir (glean re-creates the files ready for writing to but there's nothing in them - same with Tor Browser, go look)

You have failed to show ANY collection let alone sending of any data AFTER applying AF
