### ISSUE TITLE
Updater [Options]: integrate `prefsCleaner.bat` with `updater.bat`

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1740]
I currently use `updater.bat -unattended -updatebatch`
I would love to see `updater.bat` use `prefsCleaner.bat` after `-updatebatch` or before `-unattended`.

**Comment by Thorin-Oakenpants** [comment]
no thanks - let's keep things simple. Updater does not mean the user.js changes, but it does mean overrides get appended

**Comment by Thorin-Oakenpants** [comment]
actually, it doesn't - some releases are just cosmetic

but that's NOT what I said - I said the UPDATER (being run) does not mean (YOUR) user.js changes
