### ISSUE TITLE
network.http.referer.trimmingPolicy

### ISSUE THREAD

**Issue by JosefEreq** [arkenfox/user.js#1742]
Is there a reason for setting network.http.referer.trimmingPolicy to 0 and not 1 or 2?
Usage: Controls how much referrer to send regardless of origin
Values:
        0 = (default) send the full URL
        1 = send the URL without its query string
        2 = only send the origin

From https://wiki.mozilla.org/Security/Referrer

It seems setting it to 1/2 would be the most privacy respecting setting. Does it have a great impact on some functionality by setting it to 1/2 or is there another reason for not doing it?

**Comment by rusty-snake** [comment]
Because it breaks a lot and does not improve privacy (the site your on knows the page you visit anyway).

**Comment by KOLANICH** [comment]
I use 2 and that `it breaks a lot` 8s in fict pretty tiny.

**Comment by KOLANICH** [comment]
I use `2` and that `it breaks a lot` is in fact pretty tiny.

**Comment by MagicalDrizzle** [comment]
> I use `2` and that `it breaks a lot` is in fact pretty tiny.

good luck with any cloudflare verification

**Comment by Thorin-Oakenpants** [comment]
AF is not setting anything, it's commented out (but prefsCleaners will reset it for you, currently default is 0)

https://github.com/arkenfox/user.js/blob/f54d632da585a08185c6164017d79315c331181f/user.js#L1037

https://github.com/arkenfox/user.js/blob/f54d632da585a08185c6164017d79315c331181f/user.js#L1080-L1083

As already pointed out, referrers within a site are meaningless - the site already knows

**Comment by KOLANICH** [comment]
>good luck with any cloudflare verification

Cloudflare verification and fingerprinting is malware and so is completely inacceptable, websites practicing it should be boycotted.

**Comment by Thorin-Oakenpants** [comment]
dude, just turn off your internet 😁

**Comment by KOLANICH** [comment]
As I have said, for the sane websites I visit `2` is OK. Of tye insane websites 100% requiring Cloudflare fingerprinter I know GitLab.com and OpenAI. I don't use them. And I seen rumours (in the form of source code) that faking Googlag Chrome TLS fingerprint with a special TLS library may bypass Cloudflare fingerprinting screen, though I haven't tried that yet.

**Comment by MagicalDrizzle** [comment]
I think if you are this concerned (I kinda don't want to use the word paranoid) then you probably should either use Mull or Tor Browser
hell, Whonix/Tails are good options too
