### ISSUE TITLE
Clear on shutdown does not clear cookies set for IPv6 hosts [1860033 fixed 125]

### ISSUE THREAD

**Issue by git70** [arkenfox/user.js#1743]
https://bugzilla.mozilla.org/show_bug.cgi?id=1860033

---

I don't know if this is a user.js problem or an FF problem. Can anyone confirm this behavior?

Browser version & OS: 
- Firefox 115.3.1 ESR on Debian 11 Bullseye
- user.js v117

Steps to reproduce:
- Visit [distrowatch.com](https://distrowatch.com) using its IPv6 address directly [https://[2a00:9080:1:58a::1]/](https://[2a00:9080:1:58a::1]/)
- close FF
- open FF and check Preferences > Privacy&Security > Cookies and Site Data > Manage Data

Expected result:
The cookie should be deleted

Actual result:
The cookie is still there
![screenFF](https://github.com/arkenfox/user.js/assets/49098178/c19b3c10-fa62-48a3-b5ca-50512d184398)

**Comment by Thorin-Oakenpants** [comment]
@wisniewskit is this a known sanitizing issue that pbz/hannah are aware of? - TIA

**Comment by Thorin-Oakenpants** [comment]
[1550317](https://bugzilla.mozilla.org/show_bug.cgi?id=1550317) [meta] Broken data sanitization

knock yourselves out logging a ticket - I don't see anything to do with IPv6 there

**Comment by Thorin-Oakenpants** [comment]
I can't test IPv6 myself, but marking as a bug given web extensions have the same issue

**Comment by Trikolon** [comment]
Hi folks! I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1860033 on the Firefox side.

**Comment by Thorin-Oakenpants** [comment]
Thanks @Trikolon
