### ISSUE TITLE
[Question] Developer Edition

### ISSUE THREAD

**Issue by MagicalDrizzle** [arkenfox/user.js#1744]
So I know using arkenfox with FF dev edition should be fine: https://github.com/arkenfox/user.js/issues/1692  
But I just want to ask if arkenfox have accounted for all the pref changes between FF stable and dev, or as Mozilla put it `Preferences tailored for web developers`  
Remote debugging seems to already be force disabled, but is there anything else?  
On that matter what's the pref difference between stable and dev? I know telemetry.enabled is locked to true and remote debugging is enabled, but is there anything else worth caring about?

**Comment by entrider** [comment]
this project currently supports v117, but dev edition is already v119. there are probably quite many differences in their prefs.

**Comment by rusty-snake** [comment]
> there are probably quite many differences in their prefs.


But the relevant (privacy and security) are  very few. Maybe none at all.

**Comment by entrider** [comment]
In this case, why v118 isn't released yet?

**Comment by Thorin-Oakenpants** [comment]
> In this case, why v118 isn't released yet?

i am money rich and time poor .. no wait, I am also money poor
