### ISSUE TITLE
Auto Updater .bat script which can be triggered via Windows Task Scheduler

### ISSUE THREAD

**Issue by Uneccessary** [arkenfox/user.js#1748]
Make a additional Updater.bat script which automatically updates user.js, applies prefs.cleaner and closes itself again. This could be easily daily, or weekly or whenever triggered via a simple Windows Task via the Windows Task Scheduler.

**Comment by Thorin-Oakenpants** [comment]
feel free to knock yourself out

**Comment by Uneccessary** [comment]
@Thorin-Oakenpants Feel free to be less toxic.
