### ISSUE TITLE
Allow new version updates  ("browser.startup.homepage_override.mstone")

### ISSUE THREAD

**Issue by trytomakeyouprivate** [arkenfox/user.js#1750]
Hi, I update my arkenfox-softening currently, and will use an override. Thats just so much better...

Anyways, what you cant do is remove lines at all. You can only set strict parameters. So what should I do if I want to allow

```
user_pref("browser.startup.homepage_override.mstone", "REPLACEWITHVERSIONNUMBER");
```

The version number here is variable and set by firefox, and I in general dont really get one would want to remove that, its just a note about whats new?

So as this is not really removable with normal tooling, I request to comment this line out, as its not really necessary

**Comment by trytomakeyouprivate** [comment]
yes but as its simply a small annoyance, anyone can add this to their overrides. But on the other hand, to remove this you would need to enter a version number, which breaks the purpose. So it cant be changed in an override afaik, at least not easily documented, and its not necessary.

**Comment by Thorin-Oakenpants** [comment]
it is not a privacy or tracking or security issue

**Comment by trytomakeyouprivate** [comment]
Bro... Yes it is not a security issue, thus this line should be commented out.

Currently the version update logs are disabled. There is no way for a useroverride to disable that! Because you cant set a value here, it has to be empty as the new version upgrade will set the value here.

This is not a security setting so it doesnt belong in a hardening user.js. It simply disables features that some people may want.

You like to refer to user overrides. Anyone can add a user override to also disable these version update informations. But it doesnt work the other way around.

Please stop simply closing all my issues and PRs, this is not constructive in any way.

**Comment by trytomakeyouprivate** [comment]
> > What's new” page
> > After a browser update, Firefox might show an additional tab next to your usual homepage to offer more information on changes or new features included in the update.
> 
> This just gives basic information for the end-user. Annoyance, I look at the release notes on their site

Yes you can do that. Add this disabling to your override, it will never change and always disable these dialogs.

But it doesnt work the other way around. Users using arkenfox need to manipulate the user.js which is not advised. I do that currently and have no idea how it will affect updates
