### ISSUE TITLE
user.js Directory name is a problem

### ISSUE THREAD

**Issue by trytomakeyouprivate** [arkenfox/user.js#1751]
I currently have a small problem. I wanted to clone the git repo to my profile folder, have it there and then copy the user.js back from the cloned repo to the profile directory

But on Linux the user.js directory can't coexist with the user.js file, because of the name

Would you just say "put it somewhere else" or do you agree that the repo name should be changed? 

I rewrote my setup script to fit your tooling, but still I am not sure how well it suits automatic updates.

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 118, Linux Fedora
  - Steps to Reproduce (STR): Clone the git repo to a profile folder with user.js file in it
  - Expected result: the repo should not have the same name
  - Actual result: the repo and the file have the same name, causing overwrite issues

**Comment by rusty-snake** [comment]
Why not clone it so say arkrnfox-user.js? You don't have to stick to defaults.

**Comment by trytomakeyouprivate** [comment]
okay didnt know this existed in git. closed.
