### ISSUE TITLE
Shopping Experience, is is actually needed to block?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [arkenfox/user.js#1753]
I can imagine that some may not want this feature. But I couldnt find any issues with it. The "bug report" is simply a thread on how the UI should look like, and not anything bad with it.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1840156#c0 ***/

user_pref("browser.shopping.experience2023.enabled", false); // [DEFAULT: false]

I dont think this is necessary?

**Comment by Thorin-Oakenpants** [comment]
see #1730
