### ISSUE TITLE
do something with intl.accept_languages

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1759]
in FF119+ the pref to make locale match en-US was deprecated, as long term RFP (and FPP might use it) want to be able to cover all languages etc - there's a lot of tightening to do, such as enforcing preferred languages to match specific defaults (i.e not changing the order or adding/removing any), maybe using a smaller subset of preferred languages - e.g es-ES as the only spanish one, and making the locale match the language (or a smaller subset of languages)

so this leaves us with changing users preferred language(s) but still leaking their locale. I _think_ it only changes/leaks if your system locale matches the first part - e.g. my computer is en-CA (not really, it's an example), but I use en-US in the app, so it uses my system locale. If my system locale was de-DE it wouldn't change it - I'm not sure, it's not like I set up foreign language VMs

anyway, the fact remains that the pref is now somewhat useless, and when they cover all languages, then it becomes moot.

I do not want to make it inactive, because after prefCleaner is run, I do not know what Firefox will do. So we either remove it now, or leave it in for a while?

Anyone have any insight or thoughts?

**Comment by Thorin-Oakenpants** [comment]
Thanks. That makes sense. I'm just overthinking it - lots of packages/installers - e.g. I use a lot of windows portable versions, I have also installed a language version (in the past, pretty sure I grabbed some from a moz archive) and now we have live language reload - so a single installer for all of them, stub or not

Just confirms that we should remove it and not make it inactive, otherwise prefsCleaner could cause issues

is everyone happy with that?

**Comment by Thorin-Oakenpants** [comment]
will not add to scratchpad cleanup script for the same reasons

**Comment by PaintThePicture** [comment]
May I add to the conversation, and by no means you guys are the experts and I'm grateful for your work.  
 
There is a setting called, “privacy.spoof_english” which directly translates to, Settings --> General --> Language --> Choose your preferred language for displaying pages --> choose --> [ ] Request English versions of web pages for enhanced privacy.  
 
About:config, has two values either “1”, which is default off and “2” which is on.  
 
I believe this setting is new in Firefox and may be worth adding and I do understand that some people aren’t native English speakers such as me, though might be worth adding into the Arkenfox but having it like the following example //user_pref(“privacy.spoof_english”, “2”);

**Comment by iam-py-test** [comment]
I am sorry, but I believe this has been discussed before: https://github.com/arkenfox/user.js/issues/1314
Thanks

**Comment by Thorin-Oakenpants** [comment]
AFAICT, and I'll worry about this later with Tor Browser based on ESR128), spoof english is broken in at least some regards in Firefox - it doesn't (always?) set the locale to en-US, it just changes the accept languages and navigator properties

this because they ripped out the `javascript.use_us_english_locale` pref

long term, they are supposed to be adding language/locale protections back but TBH, it's a bit of a mess (kinda always has been)
- it never checked for en-* variants properly to start with (so if you were en-CA for example, you were never prompted)
- it never handled accept languages properly
   - i.e you go in and change `en-US, en` to `en, en-US` or add languages
- it has never handled anything but en-US
  - i.e it should be possible for you to select what language you want (e.g. russian) and it would then tighten your languages and order and change the locale to match russian .. etc

spoof english is broken in FF, do not use

**Comment by Thorin-Oakenpants** [comment]
> has two value

it actually has three values :)
