### ISSUE TITLE
changelog v119, v120, v121, v122, v123, v124, v125

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1765]
## :green_square: v125

[FF125.0.1 release notes](https://www.mozilla.org/firefox/125.0.1/releasenotes/)
[FF125 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/125)
[FF125 security advisories](https://www.mozilla.org/security/advisories/mfsa2024-18/)

there is no v125 release: nothing to add yet: just some [new sanitizing prefs](https://github.com/arkenfox/user.js/issues/1836)  that aren't used yet, also see #1837

## :green_square: v124

[FF124 release notes](https://www.mozilla.org/firefox/124.0/releasenotes/)
[FF124 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/124)
[FF124 security advisories](https://www.mozilla.org/security/advisories/mfsa2024-12/)
[FF124.0.1 security advisories](https://www.mozilla.org/security/advisories/mfsa2024-15/)

there is no v124 release: nothing to add yet: just [2 items](https://github.com/arkenfox/user.js/issues/1820) we don't need to flip yet, already added for next PR

## :green_square: v123

[FF123 release notes](https://www.mozilla.org/firefox/123.0/releasenotes/)
[FF123 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/123)
[FF123 security advisories](https://www.mozilla.org/security/advisories/mfsa2024-05/)

there is no v123 release: nothing to add that is can't wait: just [1 new pref](https://github.com/arkenfox/user.js/issues/1814#issuecomment-1975146470) about external links and containers to be added as inactive (commented out) for the information factor

## :green_square: v122

[FF122 release notes](https://www.mozilla.org/firefox/122.0/releasenotes/)
[FF122 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/122)
[FF122 security advisories](https://www.mozilla.org/security/advisories/mfsa2024-01/)

just cosmetic/information changes

## :green_square: v121

[FF121 release notes](https://www.mozilla.org/firefox/121.0/releasenotes/)
[FF121 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/121)
[FF121 security advisories](https://www.mozilla.org/security/advisories/mfsa2023-56/)

there is no v121 release - there was nothing to change

## :green_square: v120

[FF120 release notes](https://www.mozilla.org/firefox/120.0/releasenotes/)
[FF120 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/120)
[FF120 security advisories](https://www.mozilla.org/security/advisories/mfsa2023-49/)

there is no v120 release - there was nothing to change

---

## :green_square: v119

date: 20-November-2023

[FF119 release notes](https://www.mozilla.org/firefox/119.0/releasenotes/)
[FF119 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/119)
[FF119 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2023-45/)

---

### CHANGELOG

- [all changes](https://github.com/arkenfox/user.js/compare/118.0...119.0)
- [ToDo: diffs FF118-FF119](https://github.com/arkenfox/user.js/issues/1755) issue
- v119 PR is at #1757

---

removed in user.js 119 - see #1759
```js
user_pref("intl.accept_languages", "en-US, en");
```

- new in user.js 119
```js
user_pref("browser.search.separatePrivateDefault", true); // [FF70+]
user_pref("browser.search.separatePrivateDefault.ui.enabled", true); // [FF71+]
```

- made inactive in user.js 119
```js
   // user_pref("extensions.autoDisableScopes", 15); // [DEFAULT: 15]
```

- moved to `9999: DEPRECATED / REMOVED`:
```js
user_pref("javascript.use_us_english_locale", true); // [HIDDEN PREF]
user_pref("network.dns.skipTRR-when-parental-control-enabled", false);
```

---

```
 STATS v119: up to and including section 4500, minus the parrots
 ==========
    total: 173
 inactive:  40
           ---
   active: 133
  default:  21 (at least)
      n/a:   2 (of the four prefs in 0202, at most only two will apply)
           ---
  flipped: 110 (at most)
```

---

also ... 

## **ALL HAIL PANTS**

![allhail-AF](https://github.com/arkenfox/user.js/assets/16656956/c752f72d-95d5-4e6d-a4c2-d386d7a09b1f)

**Comment by Yellow224** [comment]
Post update 120 release notes 
https://www.mozilla.org/en-US/firefox/120.0/releasenotes/

**Comment by Thorin-Oakenpants** [comment]
check out that stability and quiet the last two years

## ALL HAIL PANTS 👿 

![fukyeah](https://github.com/arkenfox/user.js/assets/16656956/f7f2bd68-566b-4eec-a5c7-6dfc3921c0f0)

**Comment by crssi** [comment]
Thank you Pants and all the contributors. ❤️
