### ISSUE TITLE
follow instructions or this will be closed as invalid

### ISSUE THREAD

**Issue by d3athg0d** [arkenfox/user.js#1766]
hi i have tried to find out which overrides but could not seem to find the answer.
after i configured arkenfox user.js, the button highlighted in Red box will always show up as "Add to Firefox" instead of "Remove" after the extension has been installed.

![CleanShot 2023-11-21 at 02 35 56](https://github.com/arkenfox/user.js/assets/78822442/f8ddebf1-0616-4d93-80ab-1102969e1cb8)

🟪 REQUIRED INFO
  - Browser version & OS: Firefox v119, MacOS Sonama
  - Steps to Reproduce (STR): as shown in the picture
  - Expected result: button show as "Remove"
  - Actual result: button show as "Add to Firefox"
  - Console errors and warnings:
  - Anything else you deem worth mentioning:

---

**Comment by rusty-snake** [comment]
Maybe

https://github.com/arkenfox/user.js/blob/fd72683abe15de5cf57574125b64879e809cf5c4/user.js#L755-L758

Can not test here.

**Comment by iam-py-test** [comment]
Yep, `privacy.resistFingerprinting.block_mozAddonManager` is the cause. [However, that is the whole point of enabling `privacy.resistFingerprinting.block_mozAddonManager`](https://wiki.mozilla.org/Security/Fingerprinting#mozAddonManager).
It is a comedic issue; extensions can still be installed without any issues.

**Comment by Thorin-Oakenpants** [comment]
the pref blocks Mozilla integrating on AMO (i.e having powers to hook into the browser to know what you have installed) - so this is an intended side effect. If you don't know what extensions you have, then you have too many. You can "remove" extensions from `about:addons`
