### ISSUE TITLE
updater.bat failing on Windows 11 Home Edition

### ISSUE THREAD

**Issue by PencilVoid** [arkenfox/user.js#1769]
When running updater.bat, it fails at the "retrieving latest user.js" stage.

Steps to reproduce:
1. create a user-overrides.js file in the preferred profile folder
2. download updater.bat and other necessary files from latest release
3. put them in the preferred profile folder
4. run updater.bat
5. press S as prompted to start

Expected result: updater.bat downloads user.js, appends the contents of user-overrides.js, and continues as expected.
Actual result:
![2023-11-20_16-49-20-285_WindowsTerminal_JnaSgkORve](https://github.com/arkenfox/user.js/assets/83508866/0d6e4863-6bc2-4ea8-9b0a-6712e399c521)

Things I have tried, that did not fix it:
- double-checking WiFi is on
- running it with admin permissions
- running it in Powershell
- running it in Powershell with admin permissions
- opening ports 9418 and 22 in the firewall
- installing the PsDownload module (command not recognised)

I managed to use it properly on another machine running Windows 10 Pro Edition by following the steps given in the wiki. The troubleshooting I did leads me to believe it's caused by a difference between 11 Home and 10 Pro.

**Comment by Thorin-Oakenpants** [comment]
I wonder if 23H2 (The update began rolling out on October 31, 2023) has anything to do with it. I haven't tested anything, btw - this is not really my cup of tea - pinging the bat boffins @earthlng 

Can you tell me if this has ever worked for you on that machine, and if so when did it start failing?

**Comment by Thorin-Oakenpants** [comment]
hang on - it's in the wiki - https://github.com/arkenfox/user.js/wiki/3.4-Apply-&-Update-&-Maintain#-update-error

My best guess is that you are blocking it - anti virus, firewall, pihole, etc

**Comment by PencilVoid** [comment]
> Can you tell me if this has ever worked for you on that machine, and if so when did it start failing?

It's never worked on this machine. I first tried it about 2 days before I created the issue.

**Comment by Thorin-Oakenpants** [comment]
OK, so the issue is not that it doesn't work, but that "something" is blocking it. If we can work it out, I can edit the wiki - e.g. windows 10/11 home users, do "this"

**Comment by Thorin-Oakenpants** [comment]
Actually, IDK - it could be the script because that error message is from the script

**Comment by Thorin-Oakenpants** [comment]
can you do this?

![test](https://github.com/arkenfox/user.js/assets/16656956/fe28cb6d-55f1-48b6-9dec-385599059d73)

**Comment by PencilVoid** [comment]
![image](https://github.com/arkenfox/user.js/assets/83508866/b7b3611a-6b03-4fca-9c25-1c2b772d46fc)
Seems to work fine.

**Comment by earthlng** [comment]
please remove `>nul 2>&1` from line 225 and run it again. This will show the error message in the console.
Let us know what the message says, thanks.

**Comment by PencilVoid** [comment]
![image](https://github.com/arkenfox/user.js/assets/83508866/0e74b681-48c8-4cee-ae4c-aa73540f319d)

**Comment by iam-py-test** [comment]
Would you mind running `Get-ChildItem env:\__PSLockDownPolicy` and posting the result?
Thanks

**Comment by PencilVoid** [comment]
![image](https://github.com/arkenfox/user.js/assets/83508866/54debfb5-5f02-4e37-944d-4a92222cd479)

**Comment by iam-py-test** [comment]
Thanks.
As I suspected, PowerShell is running in [Constrained Language Mode](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.4).

**Comment by Thorin-Oakenpants** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.4

**Comment by PencilVoid** [comment]
Setting the environment variable `__PSLockdownPolicy` to 8 worked and now updater.bat runs without issue. Thanks for the help.

**Comment by Thorin-Oakenpants** [comment]
how did you set the environment variable, why chose 8? - so I can add the info to the wiki - TIA

**Comment by PencilVoid** [comment]
I did it by opening the Start menu and searching "environment variables". This should pull up "Edit the system environment variables" from the Control Panel. You click on the result, then click on "Environment Variables" at the bottom of the window that pops up. In the window that opens, you can look for "__PSLockdownPolicy" in the list labelled "System variables", and set its value to 8 by selecting it and clicking "Edit...". I set it to 8 as that corresponds to the FullLanguage language mode, according to [StackOverflow](https://stackoverflow.com/questions/57032747/how-to-change-powershell-mode-to-fulllanguage-mode-from-constrained-mode#57032893).

**Comment by Thorin-Oakenpants** [comment]
updated the wiki - thanks for troubleshooting @PencilVoid 🍕 🍺 🍰
