### ISSUE TITLE
prefscleaner.sh cannot start

### ISSUE THREAD

**Issue by nsoci** [arkenfox/user.js#1770]
`prefsCleaner.sh canot start:
./prefsCleaner.sh
It looks like this script was previously run with elevated privileges,
you will need to change ownership of the following files to your user:
./user.js

Update work to version 119.
If I run updater.sh again it doesn't work and I got the same msg as I wrote above.`

Thank you.

**Comment by iam-py-test** [comment]
Just a thought, but can you run `sudo chown [your username] user.js` and see what happens?
Thanks

**Comment by nsoci** [comment]
authentication failed

**Comment by nsoci** [comment]
The first time when I ru updater.sh and prefsCleaner.sh both works but lthe next time the problem.
I use clone github and download zip file and it is the same.

**Comment by iam-py-test** [comment]
Can you run `ls -l user.js prefs.js updater.sh prefsCleaner.sh` and see what it returns?
Thanks

**Comment by nsoci** [comment]
> Can you run `ls -l user.js prefs.js updater.sh prefsCleaner.sh` and see what it returns? Thanks

 ls -l user.js prefs.js updater.sh prefsCleaner.sh
-rw-------  1 aj  aj  27680 Nov 23 15:35 prefs.js
-rwxr-xr-x  1 aj  aj   6167 Nov 23 12:52 prefsCleaner.sh
-rwxr-xr-x  1 aj  aj  13953 Nov 23 12:52 updater.sh
-rw-r--r--  1 aj  aj  74634 Nov 23 12:52 user.js

**Comment by iam-py-test** [comment]
Thanks. That's bizarre. If I read that correctly, you should be able to modify those files.
Maybe someone smarter has an answer.

**Comment by element-wise** [comment]
> The first time when I ru updater.sh and prefsCleaner.sh both works but lthe next time the problem.
> I use clone github and download zip file and it is the same.

Can you please run `ls -l user.js prefs.js updater.sh prefsCleaner.sh` before and after running `updater.sh` and `prefsCleaner.sh`?

> `prefsCleaner.sh canot start:
> ./prefsCleaner.sh
> It looks like this script was previously run with elevated privileges,
> you will need to change ownership of the following files to your user:
> ./user.js

Please also show us the command you're using to run these scripts. Are you running them as root or user `aj`?

**Comment by nsoci** [comment]
I am running as user aj.
Before:
-rw-------  1 aj  aj  27845 Nov 24 05:19 prefs.js
-rwxr-xr-x  1 aj  aj   6167 Nov 23 12:52 prefsCleaner.sh
-rwxr-xr-x  1 aj  aj  13953 Nov 23 12:52 updater.sh
-rw-r--r--  1 aj  aj  74634 Nov 23 12:52 user.js

After I run ./updater.sh which works now:
-rw-------  1 aj  aj  27845 Nov 24 05:19 prefs.js
-rwxr-xr-x  1 aj  aj   6167 Nov 23 12:52 prefsCleaner.sh
-rwxr-xr-x  1 aj  aj  13953 Nov 23 12:52 updater.sh
-rw-------  1 aj  wheel  75403 Nov 24 05:31 user.js

and now i the problem:
 ./prefsCleaner.sh
It looks like this script was previously run with elevated privileges,
you will need to change ownership of the following files to your user:
./user.js

I do not know why changing user.js aj to wheel?

Thank you for your time.

**Comment by rusty-snake** [comment]
Did you changed your primary group to wheel rather than adding wheel as supplementary group?

**Comment by earthlng** [comment]
Hi,

I removed the check for "is group == root/wheel" in both scripts, because it's probably enough to check the user only.
I don't think Firefox will mind either, as long as the user has read permissions on these files.

If you have auto-update enabled, both scripts should update themselves and the problem should be fixed.
Otherwise just update both scripts manually.

**Comment by Thorin-Oakenpants** [comment]
I assume this worked? closing - feel free to ping me if it doesn't work
