### ISSUE TITLE
Properly disabling Push

### ISSUE THREAD

**Issue by mik0l** [arkenfox/user.js#1774]
Fixed the `dom.push.connection.enabled` pref. It does not affect PushManager.

For testing: https://browserleaks.com/features

**Comment by mik0l** [comment]
More:
// This preference should be used in UX to enable/disable push.
https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js#3245

**Comment by Thorin-Oakenpants** [comment]
what privacy issue are you trying to solve? rhetorical question

**Comment by mik0l** [comment]
Many users disable the entire API and it's a fingerprint problem. Sooner or later this customization will be added to the UX.

// This preference should be used in UX to enable/disable push.
https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js#3245

**Comment by Thorin-Oakenpants** [comment]
show me how you can fingerprint that

**Comment by Thorin-Oakenpants** [comment]
> `dom.push.enabled` - disables PushManager

I fucking know, it's in the user.js, in the don't touch section, with warnings, and inactive so it gets reset with prefsCleaner

> `dom.push.connection.enabled`

I fucking know what it does and doesn't do - once again .. HOW DO YOU FINGERPPRINT THIS
