### ISSUE TITLE
updater.sh error

### ISSUE THREAD

**Issue by wonderful-cheesecake** [arkenfox/user.js#1788]
Hello!
i have all the files from the user.js zip file moved into the root directory for the profile i'm using. i've run the prefscleaner.sh and it seems to run fine. when i try to run updater.sh it just return an error that says "Error! Could not download updater.sh" and another that says the same but for the user.js. i tried using the -d command to not check for updates to the updater.sh, and that gets rid of the first error but not the one about the user.js. I checked the parrot in about:config and it does say he's just resting, so something's happening i just don't know what. if it helps i'm running alpine linux with the xfce desktop which i know is kinda weird, the hardware i'm working with is just ancient. i also double checked and my terminal can ping the internet and that's all good. i've setup the arkenfox user.js on linux mint before and really had no issues. any help is appreciated :)

**Comment by rusty-snake** [comment]
Install curl and/or GNU wget.

By default alpine might not have curl installed and wget is only the busybox wget.

**Comment by wonderful-cheesecake** [comment]
pretty sure that did it, thank you!
