### ISSUE TITLE
recursion testing

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1789]
test: https://arkenfox.github.io/TZP/tests/recursion.html

example results: you can **_ignore iframe and worker_**
```
level: 39289
stack: 8448
```

I'm determining if this (`level`) is stable enough as a fingerprint, and it seems so (we can round the number into buckets). So the next question becomes what does it return on different hardware. The other factor is enabling/disabling ion/jit etc - which AFAICT requires a restart for it to affect the results (I always close and re-test in a new tab)

So here's some Tor Browser results to give you an idea
- the standard vs safer means the browser opened with that setting (see point above about a restart required)
- the security level is toggling `javascript.options.baselinejit`

```
recursion level (TB unless stated)

                     worker         doc/iframe
                standard  safer   standard   safer

    win11 32bit   16180    4616     43439    12408 (i686-w64-mingw32 - on 64bit OS)

    win11 64bit   21620    6486     39376    11811 (x86_64-w64-mingw32)
    win11 64bit   21558    6472     39251    11778 (FF123n)
    win10 64bit   21572    6474     39309    11784 (iam-py-test FF121)
 debian12 64bit   21607    6482     39386    11816 (VM on windows)
         debian   21607    6482     39386    11816 (PieroV)
debian bookworm   21551    6465     39358    11807 (2glops FF121)
 fedora39 64bit            6474              11833 (rusty Fedora 39; x86_64; FF121)
 fedora39 64bit   21567    6470     39466    11840 (jayna37 FF121 M2 MacBook Air aarch64)
     arch 64bit   21560    6468     39363    11811 (therealmate FF121)
    LMDE6 64bit   21551    6465     39358    11810 (g-2-s FF121)
    LMDE6 64bit   21607    6482     39386    11816 (g-2-s)

     iMac 64bit   21690    6507     39398    11820 (Apple M1)
    MacBook Pro    6495    6495     11808    11808 (javulticat FF121: M1 Pro AArch64/ARM64) *


galaxyA30 64bit   21689    6506     30226     9066
      Pixel7Pro    6506    6506      9070     9070 (javulticat FF121: AArch64/ARM64) *

* these are "64bit-only" devices
```

So what I'm interested in is on any device (os, vm), with any gecko browser (TB, FF) and any version - can you past me the results - just tell me those parameters - browser bitness, os, vm + underlying os, browser (TB, FF), version ... **and** tell me if you have opened ~~it~~ the browser with `javascript.options.baselinejit` = true or false. If you want, test both true and false (i.e change the value and restart)

TIA

**Comment by rusty-snake** [comment]
- WORKER
  - level: 6474
  - stack: 8960
- DOCUMENT
  - level: 11833
  - stack: 8448
- IFRAME
  - level: 11828
  - stack: 9344 

Fedora 39; x86_64; Firefox 121 (from Fedora); baselinejit,ion=false;

**Comment by Thorin-Oakenpants** [comment]
i'm updating OP with results as I go

**Comment by therealmate** [comment]
* WORKER
  * level: 6468
  * stack: 8960
* DOCUMENT
  * level: 11809
  * stack: 8448
* IFRAME
  * level: 11811
  * stack: 9344

Arch Linux; 64 bit; Firefox 121.0-1; javascript.options.baselinejit=false

**Comment by iam-py-test** [comment]
- Worker
level: 39309
stack: 8448
- Document
level: 39309
stack: 8448
- iframe
level: 39320
stack: 9344

Firefox 121.0 (64-bit) running on Windows 10 22H2 (32.0 GB of RAM). Firefox is running on default settings (javascript.options.baselinejit = true)
With javascript.options.baselinejit=false:
- Worker
level: 6474
stack: 8960
- Doc
level: 11784
stack: 8448
- iframe

level: 11788
stack: 9344

Thanks

**Comment by Thorin-Oakenpants** [comment]
@iam-py-test I don't think your worker result for baselinejit = true is correct

**Comment by iam-py-test** [comment]
Re-did and got
```
level: 21572
stack: 8960
```
Wonder why it didn't work the first time...

**Comment by Thorin-Oakenpants** [comment]
it worked the first time, my test page is a bit shit to copy paste - i,e you can't do it in one hit - so its just a copy/past human error

**Comment by therealmate** [comment]
Added javascript.options.baselinejit=true to my post

**Comment by Thorin-Oakenpants** [comment]
so far this is promising ... android, mac intel, arm (IDK if I'm using the right words! 😁 )  might tell a different story - so far it's looking like equivalency of items that can't really be masked - so the only issue here is likely to be that the pref state on startup can be detected as a bit of information which would add entropy when the user changes the security slider to be the opposite during a session (but I have a cunning plan to fix that)

**Comment by javulticat** [comment]
### System: [MacBook Pro (16-inch, 2021)](https://support.apple.com/kb/SP858)

- **OS:** [macOS](https://en.wikipedia.org/wiki/MacOS) [Sonoma](https://en.wikipedia.org/wiki/MacOS_Sonoma) [14.2.1 (23C71)](https://en.wikipedia.org/wiki/MacOS_Sonoma#Release_history)
- **SoC:** [Apple M1 Pro](https://en.wikipedia.org/wiki/Apple_M1_Pro) ([Apple silicon](https://en.wikipedia.org/wiki/Apple_silicon))
    - **Architecture:** [AArch64/ARM64](https://en.wikipedia.org/wiki/AArch64) ([ARMv8.5-A](https://en.wikipedia.org/wiki/AArch64#ARMv8.5-A))
- **Browser:** [Firefox 121.0](https://www.mozilla.org/en-US/firefox/121.0/releasenotes/)
    - **Platform:** [macOS](https://ftp.mozilla.org/pub/firefox/releases/121.0/mac/en-US/Firefox%20121.0.dmg)

### Results: https://arkenfox.github.io/TZP/tests/recursion.html
- **`javascript.options.baselinejit`:** `false`
    - **WORKER:**
        - **level:** 6495
        - **stack:** 8960
    - **DOCUMENT:**
        - **level:** 11808
        - **stack:** 8448
    - **IFRAME:**
        - **level:** 11810
        - **stack:** 9344
- **`javascript.options.baselinejit`:** `true`
    - **WORKER:**
        - **level:** 6495
        - **stack:** 8960
    - **DOCUMENT:**
        - **level:** 11808
        - **stack:** 8448
    - **IFRAME:**
        - **level:** 11810
        - **stack:** 9344

---

### System: [Google Pixel 7 Pro](https://www.gsmarena.com/google_pixel_7_pro-11908.php)
- **OS:** [GrapheneOS](https://grapheneos.org/) [2023121200](https://grapheneos.org/releases#2023121200)
    - Based on [Android 14](https://en.wikipedia.org/wiki/Android_14) [QPR1 (UQ1A.231205.015)](https://9to5google.com/2023/12/06/android-14-qpr1-december-pixel-update/)
- **SoC:** [Google Tensor G2](https://en.wikipedia.org/wiki/Google_Tensor#G2)
    - **Architecture:** [AArch64/ARM64](https://en.wikipedia.org/wiki/AArch64) ([ARMv8.2-A](https://en.wikipedia.org/wiki/AArch64#ARMv8.2-A))
- **Browser:** [Mull](https://github.com/Divested-Mobile/mull-fenix) [121.0.0 (21210020)](https://f-droid.org/packages/us.spotco.fennec_dos/#21210020)
    - Based on [Firefox 121.0 for Android](https://www.mozilla.org/en-US/firefox/android/121.0/releasenotes/)
### Results: https://arkenfox.github.io/TZP/tests/recursion.html
- **`javascript.options.baselinejit`:** `false`
    - **WORKER:**
        - **level:** 6506
        - **stack:** 8960
    - **DOCUMENT:**
        - **level:** 9070
        - **stack:** 8448
    - **IFRAME:**
        - **level:** 9068
        - **stack:** 9344
- **`javascript.options.baselinejit`:** `true`
    - **WORKER:**
        - **level:** 6506
        - **stack:** 8960
    - **DOCUMENT:**
        - **level:** 9070
        - **stack:** 8448
    - **IFRAME:**
        - **level:** 9068
        - **stack:** 9344

**Comment by Thorin-Oakenpants** [comment]
@g-2-s re `LMDE6, x64, Tor Browser 13.0.8, javascript.options.baselinejit = true` result - that looks like false, not true

**Comment by Thorin-Oakenpants** [comment]
@javulticat  those are great, thanks, except the results have true = false. You need to restart firefox in between tests (on android I use menu>quit - I didn't need to force quit from apps)

**Comment by javulticat** [comment]
> @javulticat those are great, thanks, except the results have true = false. You need to restart firefox in between tests (on android I use menu>quit - I didn't need to force quit from apps)

@Thorin-Oakenpants I triple-checked my results after changing the config option using a variety of ways to exit and restart the browser (quit normally, force quit and clear cache, restart OS - each time confirming in `about:config` upon reopening the browser that the setting value remained changed) on both systems since the test results kept coming back identically, but so far I have been unable to get any other set of results on either system, regardless of how `javascript.options.baselinejit` is set and how the app/system is restarted.

Perhaps this behavior is somehow specific to AArch64 architectures, since I am seeing the same thing on two systems based on that architecture family? Or perhaps my config is enabling/disabling other settings that are causing any change to `javascript.options.baselinejit` to not have an impact?

Another thing that may be rather unique about my systems is that macOS Catalina is 64-bit-only (from CPU to OS to apps) and the Pixel 7/7 Pro were the first ever 64-bit-only Android phones (likewise, from CPU to OS to apps), despite the fact that 32-bit instruction sets _can_ be enabled on AArch64 chips (and are enabled on almost every other mobile SoC - AFAIK, the Google Fold and Pixel 7a/8/8 Pro, all also based on the Google Tensor G2/G3 SoC, are the only other 64-bit-only Android phones on the market so far). The only other entry in your list that looks like it may also be from a 64-bit-only AArch64-based system is the M1 iMac (they still make iMacs?), but its results look rather suspect to me, as its `doc/iframe:safer` result is _exactly_ equal to its `worker:standard` result, which doesn't occur on any other system on your list, and, at 21690, it's ~10k/2x larger than any other `doc/iframe:safer` result on your list as well.

I will try the test on my x86_64 Windows 11 machine tomorrow to see if I can get different results on a different architecture, which should help rule out (or confirm 🙃) user error. I can also post my `user.js` (or values for any specific settings) if that would be helpful.

**Comment by Thorin-Oakenpants** [comment]
@g-2-s hmmm .. and the slider was at safer when you opened TB? hmmm there might be something else at play here

@javulticat thanks - this is why we test :)

what gets me is the result for all of them is identical for all six measurements, not even out by `1` - in all three = unlikely IMO - and the TB one changes all the prefs (see below)

There are other prefs that the slider changes - see [these](https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-115.3.0esr-13.0-1/toolkit/components/securitylevel/SecurityLevel.jsm?ref_type=heads#L266) - so any of those `javascript` prefs might also be affecting results.

I only tested the baselinejit one (in FF) as a quick mimic of the slider in TB

**Comment by Thorin-Oakenpants** [comment]
going to ping @PIeroV for this AArch64 conundrum (IANAHardwareE)

**Comment by Thorin-Oakenpants** [comment]
the iMac is my desktop - in About>system settings>general .. it says the chip is M1 - it's a year old and is one of these - https://www.apple.com/imac/ (but not from the USA) - I got the lower end spec model in the shop (I had two options)

I'm not super savvy on hardware, but would be nice to know what causes these differences. I ~~initially suspected~~ was hoping that the `21690` jit=off size was a normal thing for macs (not mac intel - I might be getting confused here with terms)

**Comment by Thorin-Oakenpants** [comment]
ok, that confirms what I thought. Sorry my test is a pain to copy the results and STR are a bit confusing


original TB - https://github.com/arkenfox/user.js/issues/1789#issuecomment-1873444943
```
WORKER level: 6482 | DOCUMENT level: 11814 | javascript.options.baselinejit = false
WORKER level: 6482 | DOCUMENT level: 11816 | javascript.options.baselinejit = true
LMDE6, x64, Tor Browser 13.0.8
```

TB post above
```
WORKER level: 21607 | DOCUMENT level: 39386 | standard (baselinejit = true)
WORKER level:  6482 | DOCUMENT level: 11816 | standard (baselinejit = false)
   ^ i think this is safer, not standard
```

i.e you opened at standard + tested, then set to safer + restarted + tested, then set to safest + restarted + tested

so the original post must be another case of copy/paste gone wrong or human confusion? has to be since the new results are consistent with your FF results on the same machine

the two safest tests when you allow JS to run will just return whatever state the browser was started in (for our test on recursion levels and stack lengths)

thanks for testing :) have some 🍕 and 🍰

**Comment by Thorin-Oakenpants** [comment]
ok, I fubared my iMac result, I just retested - that `21690` - NFI why I wrote that down (not a copy paste job, manually typing between two computer screens)

```
                     worker         doc/iframe
                standard  safer   standard   safer

     iMac 64bit   21690    6507     39398    21690 (Apple M1)  <-- wrong, human fubar

     iMac 64bit   21690    6507     39398    11820 (Apple M1) <-- correct
```

**Comment by 2glops** [comment]
FF 121.0 on Debian Bookworm

WORKER
level: 21551
stack: 8960

DOCUMENT
level: 39358
stack: 8448

IFRAME
level: 39367
stack: 9344

javascript.options.baselinejit = true
javascript.options.ion = true

**Comment by jayna37** [comment]
Firefox 121.0, aarch64 Fedora Linux, M2 MacBook Air

# javascript.options.baselinejit = true

WORKER
level: 21567
stack: 8960

DOCUMENT
level: 39466
stack: 8448

IFRAME
level: 39467
stack: 9344

![baselinejit_true](https://github.com/arkenfox/user.js/assets/3247063/9001fde1-47c8-45d8-9f68-03e41640c7d5)

# javascript.options.baselinejit = false

WORKER
level: 6470
stack: 8960

DOCUMENT
level: 11840
stack: 8448

IFRAME
level: 11840
stack: 9344

![baselinejit_false](https://github.com/arkenfox/user.js/assets/3247063/4a2a4f1f-6ef6-42e8-b3bc-18170e09b627)

**Comment by Thorin-Oakenpants** [comment]
there's already a HW diff in audio - `x86/amd` vs `ARM` (IDK what that means)

And here we have some aarch64 being different ( IANAE .. something about 64bit _only_ ) - depending on our step a) results upstream, it may be we always load at disabled and that would solve that (if you know what I'm talking about)

would be nice if someone like ted campbell (I think) from moz weighed in

IDK if VMs are worth it just yet - they seem to mirror the host

**Comment by Thorin-Oakenpants** [comment]
holy crap that's identical to my VM .. and you said you had different results :P
```
 debian12 64bit   21607    6482     39386    11816 (VM on windows)
         debian   21607    6482     39386    11816 (pierov)
```

**Comment by Thorin-Oakenpants** [comment]
ok, got all I need - thanks everyone
