### ISSUE TITLE
Where is prefsCleaner?

### ISSUE THREAD

**Issue by zdat** [arkenfox/user.js#1790]
Unless I'm an idiot, I don't see where I'm supposed to download prefsCleaner?

On [3.5-prefsCleaner](https://github.com/arkenfox/user.js/wiki/3.5-prefsCleaner) the only link is to [arkenfox-cleanup.js](https://github.com/arkenfox/user.js/blob/master/scratchpad-scripts/arkenfox-cleanup.js)

Is arkenfox-cleanup.js prefsCleaner?

I have an old prefsCleaner.bat in my profile but I have no idea where I got that from.

Any help? Thanks.

**Comment by Thorin-Oakenpants** [comment]
same place you got your user.js

**Comment by 9ao9ai9ar** [comment]
@notDavid Having recently rewritten both `prefsCleaner.sh` and `updater.sh` in #1908, here's my take: the `arkenfox-cleanup.js` is to be run manually by the user, as proper automation, I think, requires installation of a WebDriver; the prefs.js cleaner scripts, on the other hand, can be run in a cron job (uh, there is still a problem in the shell script version that if Firefox is running it'll hang/loop indefinitely, but that could be fixed easily) without any prior setup, but relies on hackish detection of all the prefs present in the user.js file, while in the case of `arkenfox-cleanup.js` the list of deprecated/removed prefs is maintained for Firefox 91+.

@Thorin-Oakenpants If my pull request passes the review and is merged, I can help with updating the shell script parts of the wiki, too. If I recall correctly, you want edits to the wiki to keep the color boxes intact, right?

**Comment by 9ao9ai9ar** [comment]
> However, would it not be good to update / download it, so people have the latest version - regardless whether they will execute it or not?

That may depend on the user. If they do not use a feature, would the additional file, storage and network bandwidth, however miniscule they are, be considered good?

But I do think there is benefit to combining the user.js updater and prefs.js cleaner into one script, since there are some overlapping code and conceptually they can also be considered a single unit. We could also take this opportunity to redefine the interface, e.g. make the shell script options more idiomatic, unify the feature set and make the behaviors of the Unix shell scripts and Windows batch files more consistent, etc.

The above is a perfectionist approach, but also kind of overenginnering and wasting time because this project is slated to be deprecated sometime in the future, and what we currently have already works quite well for the majority of cases.

**Comment by 9ao9ai9ar** [comment]
> However, would it not be good to update / download it, so people have the latest version - regardless whether they will execute it or not?

That may depend on the user. If they do not use a feature, would the additional file, storage and network bandwidth, however miniscule they are, be considered good or just extra noise?

> Currently, you would have to go manually search for it. Why not just include it and keep it up to date automatically?

I'm not quite sure what you mean by having to go manually search for it. You could either git clone the whole arkenfox repo and periodically pull from master to have everything up-to-date, or download the updater script (and optionally the prefsCleaner script) and use it to update both the user.js file and itself. The `-l` and `-p` options enable you to keep the script(s) in one location and have the arkenfox configuration applied to any Firefox profile.

The latter usage pattern also highlights the benefit of having a single script that combines the features of both the user.js updater and the prefs.js cleaner: it cuts the minimum file count for a complete setup from 2 to 1. Not to mention that this might also shed off some lines of shared code and provide an opportunity to redefine the interfaces, e.g. make the shell script options more idiomatic, unify the feature sets and make the behaviors of the Unix shell scripts and Windows batch files more consistent, etc.

But that is pursuing perfectionism. In any case, what we currently have already works quite well for the majority of cases, and any further major rework of the shell scripts may be considered counterproductive, even more so when this project is slated to be deprecated sometime in the future.
