### ISSUE TITLE
Disable javascript JIT

### ISSUE THREAD

**Issue by trytomakeyouprivate** [arkenfox/user.js#1791]
```
user_pref("javascript.options.baselinejit", false);
user_pref("javascript.options.ion", false);
user_pref("javascript.options.wasm", false);
user_pref("javascript.options.asmjs", false);
```

Those are probably all settings that disable JIT in Firefox. JIT is a big security problem and the speed is not worth it really, if there are so many vulnerabilities.

Would this fit Arkenfox'es scope? I think so.

**Comment by Thorin-Oakenpants** [comment]
FFS .. did you even look at what is in the user.js

**Comment by trytomakeyouprivate** [comment]
I use arkenfox and those where not set. Maybe its not up to date?

**Comment by Thorin-Oakenpants** [comment]
> and those where not set ... But true they are all already set

wot? AF is a template, not everything is `active` (i.e not commented out). What is active either enforces a default in case a user changed it (and to educate those who bother to read the user.js), or it sets it for a balance between do nothing or do everything.

section 5500 which contains your suggested additions, is inactive - use them at your own risk - they will cause pain and weird side effects - enjoy. Even Tor Browser doesn't ship with these (your 4 items) disabled by default. If you're at the stage where you think you need them disabled, then just go use TB on security setting "safer" - or you know, read the user.js and add them as overrides at your own risk/tolerance
