### ISSUE TITLE
Block cookie banners

### ISSUE THREAD

**Issue by Schwitzd** [arkenfox/user.js#1793]
Hello,

Firefox recently launched [Block cookie banners 
](https://support.mozilla.org/en-US/kb/cookie-banner-reduction). Would be great if you can implement it.

Thx

**Comment by Thorin-Oakenpants** [comment]
it's not really going to do anything for privacy (everything is already partitioned by 1st party, we already have uBO which also has some of these AFAICT ... or rather you should have uBO else you're doing it wrong) - Firefox will turn it on for everyone when they're ready and it's one less bit of information I need to deal with
