### ISSUE TITLE
Is there a way to disable resolution spoofing

### ISSUE THREAD

**Issue by notswwife** [arkenfox/user.js#1799]
Is there a way to get back the default resolution (not the spoofed one)? I really like the config, but I find the resolution a dealbreaker.

latest version, windows

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/4a510a4b4ceda8a177831a77309f2faccf7e18d5/user.js#L691

**Comment by notswwife** [comment]
thanks, sad tho

**Comment by rusty-snake** [comment]
It is not really clear to what you refer with "resolution spoofing". Media queries (inner/outer window size, ...), display ration, letterboxing, ...

For letterboxing see.

https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-fingerprinting
https://github.com/arkenfox/user.js/blob/4a510a4b4ceda8a177831a77309f2faccf7e18d5/user.js#L759-L768

**Comment by crssi** [comment]
To start FF window maximized I use extension [Maximize All Windows (Minimalist Version)](https://addons.mozilla.org/firefox/addon/maximize-all-windows-minimal/ )

**Comment by Thorin-Oakenpants** [comment]
> https://github.com/arkenfox/user.js/blob/4a510a4b4ceda8a177831a77309f2faccf7e18d5/user.js#L691

actually, these days with RFPTargets this is not strictly true :)
