### ISSUE TITLE
windows Office365 users: lend me your ears!

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1801]
Pipe up if you have office 365 on windows (most likely win10+)

**Comment by PieroV** [comment]
@Obegg do you have cloud fonts? They should have a little cloud next to their name.
Could you please try to install one?
After you''ve added it, can you use it outside Office applications?
Do you see it in C:\Windows\Fonts?
Thanks in advance!

**Comment by PieroV** [comment]
Sorry, the cloud should be visible in office, e.g. in Word.
Something like this: https://filestore.community.support.microsoft.com/api/images/b071b00b-3f17-4f5a-93a7-b1378aca29a4

**Comment by PieroV** [comment]
Great, thank you for your help!

**Comment by Thorin-Oakenpants** [comment]
Thanks @Obegg .. here's some free 🍕 and a 🍺
