### ISSUE TITLE
CRLite seems not to work

### ISSUE THREAD

**Issue by brokoler** [arkenfox/user.js#1811]
Arkenfox switched to a new certificate revocation check mechanism, it now uses CRLite instead of OCSP per default.
This is appreciated, since CRLite offers many advantages. Right now it seems not to work compared to a Firefox install without Arkenfox.

**Default behavior with CRLite enabled:**
`security.remote_settings.crlite_filters.enabled = true`
Firefox downloads multiple files required and saves them in the user profile folder inside sub-folder "security_state".
Certificate revocation checks based on CRLite are only working, when these files were downloaded successfully. 

**Mozilla explains the feature in detail:**
Certificate revocation checks are only performed via CRLite after specific files were downloaded:
https://blog.mozilla.org/security/2020/01/09/crlite-part-2-end-to-end-design/
The file "crlite.filter" contains all revocation information.

**Issue with Arkenfox applied:**
With Arkenfox applied the lists never get downloaded.

### A clean install of Firefox is not affected by the issue
Tested with a clean Firefox 122.0.1 install, no user.js and only two about:config adjustements applied:
- security.pki.crlite_mode = 2
- security.remote_settings.crlite_filters.enabled = true

In this case CRLite files are downloaded successfully (took a few minutes and is reproducable):
![image](https://github.com/arkenfox/user.js/assets/57031979/8c2fb47b-29d2-4519-9ce8-4c82fb072f26)
Same behavior is expected with Arkenfox, since CRLite is enabled per default by Arkenfox.
With Arkenfox the files are missing after waiting for several hours.

🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 122.0.1 (Clean Install) and Windows 10
  - Steps to Reproduce (STR): Start Firefox with applied Arkenfox user.js, CRLite should be downloaded automatically
  - Expected result: Profile folder "security_state" should contain CRLite files
  - Actual result: Profile folder "security_state" does not contain CRLite files (folder is empty)
  - Console errors and warnings: Tried troubleshooting which Arkenfox setting might be responsible but failed
  - Anything else you deem worth mentioning: See above

---

**Comment by Thorin-Oakenpants** [comment]
So my FF has it no issues, I think it just takes time... I'm just spitballing here
- meta ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1429800
- a ticket linked to meta mentioned `services.settings.poll_interval` (24 hrs)
   - which led me to this: https://searchfox.org/mozilla-central/source/services/settings/RemoteSettingsComponents.sys.mjs#17

IDK if that means anything, and I didn't test much, but on a new FF (portable, I just rename the profile and it creates a new on on demand), I added AF and sure, nothing downloaded in the first 5 minutes.

My main AF (also portable) does have it

Give it a day and then report back

**Comment by Thorin-Oakenpants** [comment]
That's interesting - LW doesn't have anything and it's been installed for months (but I almost never open it)

**Comment by brokoler** [comment]
@Thorin-Oakenpants Thanks for helping!
After my recent testings it's **not** related to
`user_pref("permissions.manager.defaultsUrl", "");`

I further checked on this and my guess is, that the CRLite files are installed via Push Services.
It seems like the Mozilla Push Server contacts the client, because of that the installation seems delayed by minutes or hours.

So following value is required (already enabled in AF per default):
`user_pref("dom.push.enabled", true);`

It was enabled in my setup but took long.
With an install where I disabled Push Services it definitely never came through.
Still in testing phase, but I'm mostly sure about it and logged the network connectivity via GlassWire where "autopush.prod.mozaws.net" was contacted when my files FINALLY arrived :)

So nothing to change on AF side, just a reminder how important dom.push.enabled is.

**Comment by brokoler** [comment]
Can confirm it worked multiple times now.
Only with Push Services enabled, they are mandatory to receive CRLite files.

**Comment by brokoler** [comment]
Very vague description by Mozilla (Does mention a Remote Server pushes updates to Firefox Clients):
https://blog.mozilla.org/security/2020/12/01/crlite-part-4-infrastructure-design/

![grafik](https://github.com/arkenfox/user.js/assets/57031979/e08cb40e-570d-4a07-9aca-80f205c9dc6b)

**Comment by Thorin-Oakenpants** [comment]
great detective work @brokoler ... here's your cake 🍰 :)

I will so something in the user.js - thanks

**Comment by Thorin-Oakenpants** [comment]
when I do the next PR

```
/* 7019: disable Push Notifications [FF44+]
 * [WHY] Website "push" requires subscription, and the API itself is required for CRLite (1224)
 * [NOTE] To remove all subscriptions, reset "dom.push.userAgentID"
 * [1] https://support.mozilla.org/kb/push-notifications-firefox ***/
   // user_pref("dom.push.enabled", false);
```

**Comment by Thorin-Oakenpants** [comment]
`dom.push.enabled` is true in LW ... but I did see a bunch of maybe related errors in the console for `remote-settings/` .. so my best guess is this is caused by a patch they did trying to make "Firefox silent" (see the black vs white false dichotomy in #1807 ) - if this is the case, just another example of perceived privacy gains but actually achieving security losses

**Comment by prettyv** [comment]
I also believe this has to be related to some Remote Settings related changes there, as despite having `dom.push.enabled` set to false here (I'll re-enable this, just an oversight on my part), the expected CRLite files in the profile's `security_state` are up-to-date having been updated an hour ago. I.e. the files are fetched from Remote Settings by regular polling (see the event handler [here](https://searchfox.org/mozilla-central/source/security/manager/ssl/RemoteSecuritySettings.sys.mjs#541)) just fine, not sure where the additional push message is handled in the code specifically after a quick search.

So as I understand it this only means updates could reach Firefox faster with enabled push services, but they aren't strictly required. The added comment "and the API itself is required for CRLite" is thus at least misleading I think and should be either softened - indicating _faster_ CRLite data updates -  or removed again.

**Comment by Thorin-Oakenpants** [comment]
The polling is 24 hrs and I linked to it in https://github.com/arkenfox/user.js/issues/1811#issuecomment-1951201076 - so yes, Remote Services is used. My best guess is the change in prefs is picked up and uses push to get started, else ?? it then manifests within 24 hrs (depends when your next poll is)? right ??? If someone wants to test that and confirm, then I can amend my proposed change

**Comment by brokoler** [comment]
I will test how the CRLite updates look like with
` user_pref("dom.push.enabled", false);`

**Personal opinion**
`dom.push.enabled` might be a privacy concern, since the browser establish a persistent connection to Amazon AWS services. Besides CRLite updates, what else does someone really need from Push Services? Most websites don't use push and the functional gain of push messages is minimal for a webbrowser (compared to a smartphone, where it's mostly mandatory).

Especially when you think about the latest leaks of government documents that Push Services spy on users on Apple and Android Smartphones, this might be the same with Firefox Push Services enabled:
`https://www.reuters.com/technology/cybersecurity/governments-spying-apple-google-users-through-push-notifications-us-senator-2023-12-06/`

You have to decide yourself if the security gain by faster CRLite updates are worth the potential privacy issues.
For me CRLite is definitely required, I will evaluate how often it updates with Push Services disabled.

**Comment by brokoler** [comment]
Opened a feature request on Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1880888

**Comment by Thorin-Oakenpants** [comment]
https://codeberg.org/librewolf/issues/issues/1794

two weeks .. dead silence ... **_nobody's home!!_** 

---

so https://github.com/arkenfox/user.js/pull/1816/commits/e037014a56ed22a7de39ebef6efe9dfe0c325549 is the commit

speak up if anyone is unhappy with how I framed it

**Comment by brokoler** [comment]
@Thorin-Oakenpants Guess it will never work with Librewolf, since they block the hardcoded URL "firefox.settings.services.mozilla.com". It's a philosophy thing I guess.

Also there is a testing website, with a revoked certificate, to check if CRLite works:
https://digicert-tls-ecc-p384-root-g5-revoked.chain-demos.digicert.com/

With the settings Arkenfox is using it works fine!

**Comment by brokoler** [comment]
@Thorin-Oakenpants some more updates about my findings.

You can download CRLite files with `dom.push.enabled = false`
In this case `services.settings.poll_interval = 1` is required (all other values didn't work for me).

These values combined successfully download and update CRLite files with the AWS push connection being disabled.

**Comment by Thorin-Oakenpants** [comment]
Thanks

> In this case services.settings.poll_interval = 1 is required (all other values didn't work for me).

yeah .. we're not going to do polling every 1 second and I wouldn't expect anyone else to either. So I think the user.js edit is perfectly correct given a few assumptions
