### ISSUE TITLE
Move the "sticky: override recipes" to a file in the repo

### ISSUE THREAD

**Issue by notDavid** [arkenfox/user.js#1815]
Hi there,

please consider moving the "sticky: override recipes" #1080 to a Markdown file (for example `overrides_recipes.md`) in the repository; we would then automatically be able to:
- see updates to the recipes by following the commits in an rss reader (via for example `https://github.com/arkenfox/user.js/commits/master/overrides_recipes.md.atom` )
- have a history / changelog of it

Thank you!

**Comment by Thorin-Oakenpants** [comment]
IDK if it's worth it. It's hasn't changed in almost a year, and aside from flipping from RFP to FPP .. I do not see anything else ever happening

**Comment by Thorin-Oakenpants** [comment]
feel free to argue for it ... I'm just closing because I detest open issues :)
