### ISSUE TITLE
GPC

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1818]
> what about adding it to the user.js to enforce its default value with prefscleaner (currently false)?

_Originally posted by @Tiagoquix in https://github.com/arkenfox/user.js/issues/1542#issuecomment-2011030614_

**Comment by Thorin-Oakenpants** [comment]
IDK, my initial reaction is no (because then I will have to repeatedly defend it) .. if something isn't in the user.js then you shouldn't change it .. but I get the info factor is tempting

at the end of the day, it's really only going to help RFP users (by being enforced as off) - TB next ESR will have it too (because PB mode, assuming they don't change it and I don't see why they would) - not that we are trying to look like TB

I also need to check if setting the prefs affects PB mode

What I would like to happen is if ETP Strict then send it - this would then make Mozilla happy that it was opted in

I need to drink about it ... maybe in [Portugal](https://gitlab.torproject.org/tpo/team/-/wikis/Meetings/2024/Lisbon)

**Comment by xe-3** [comment]
> What I would like to happen is if ETP Strict then send it - this would then make Mozilla happy that it was opted in

Can you elaborate on this?

Am I understanding correctly that what you are saying here is that if ETP strict mode is enabled GPC would be enabled? Or have I misunderstood your meaning.

Also could you elaborate on what you alluded to with making Mozilla happy that it remains opt-in? Is this their policy/position?

**Comment by Thorin-Oakenpants** [comment]
> Can you elaborate on this

not really .. just musing, not really thinking about it - its not high priority for me right now. Haven't even checked anything.

Someone said it's used in PB mode ... ~~but the default API is off~~ ok, the API is enabled by default now, that's right, I forgot .... so anyway, it must be configurable (i.e the value sent is based on some criteria, e.e. window mode etc) - just checked a PB window and `navigator.globalPrivacyControl` = `true`, normal window = `false`

So the logic is this - we follow what Mozilla does. Right now your PB windows use ETP Strict and do PB mode special things (e.g. FPP if RFP is disabled, anything else they throw in like cookie banners and bounce stuff)

The same holds for ETP Strict ... we follow what Mozilla does - see these examples

```
/* 7015: enable the DNT (Do Not Track) HTTP header
 * [WHY] DNT is enforced with Tracking Protection which is used in ETP Strict (2701) ***/
   // user_pref("privacy.donottrackheader.enabled", true);
/* 7016: customize ETP settings
 * [NOTE] FPP (fingerprintingProtection) is ignored when RFP (4501) is enabled
 * [WHY] Arkenfox only supports strict (2701) which sets these at runtime ***/
   // user_pref("network.cookie.cookieBehavior", 5); // [DEFAULT: 5]
   // user_pref("privacy.fingerprintingProtection", true); // [FF114+] [ETP FF119+]
   // user_pref("network.http.referer.disallowCrossSiteRelaxingDefault", true);
   // user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true); // [FF100+]
   // user_pref("privacy.partition.network_state.ocsp_cache", true); // [DEFAULT: true FF123+]
   // user_pref("privacy.query_stripping.enabled", true); // [FF101+]
   // user_pref("privacy.trackingprotection.enabled", true);
   // user_pref("privacy.trackingprotection.socialtracking.enabled", true);
   // user_pref("privacy.trackingprotection.cryptomining.enabled", true); // [DEFAULT: true]
   // user_pref("privacy.trackingprotection.fingerprinting.enabled", true); // [DEFAULT: true]
```

if that's not clear ... look at doNotTrack - default is `unspecified`, but we return `1` (a string) .. ETP Strict already changes out fingerprint, including headers.

So if ETP Strict added GPC then it is what it is, and we look like all other ETP Strict users in this regard - rather than outliers changing their passive fingerprint on a whim

**Comment by Thorin-Oakenpants** [comment]
> Also could you elaborate on what you alluded to with making Mozilla happy that it remains opt-in? Is this their policy/position?

**_I am not privy to any of Mozilla's position on this, so do not quote me_**. My understanding or gut feeling in reading about this in the past (all I do is read and drink and know things) is that it will unlikely ever be turned on by default for all users (but maybe that will change because shit happens, it's called the future and I have a bridge to sell people)

Brave started from a different point than FF. FF has to turn things on slowly. Brave just does things regardless, for all users - they started from a position of "hey we will do things to improve your privacy and you may experience some pain", i.e all users since day one have had this expectation. FF doesn't have that luxury with their existing user base, and only turns on features if the user OPTS IN - e.g. user chooses to use a PB window, user chooses to use ETP Strict - and even then they're cautious. Not saying GPC would break anything, but it follows the same pattern/policy

Back in the day (handy wavy not going to look anything up) doNotTrack was specified as must-be-opt-in. I think from the advertisers, because otherwise they wouldn't abide by it. So Mozilla did that, you had to opt in (e.g. via checkbox or via using pb mode). But then someone (internet explorer I think, wiki seems to suggest so) turned it on by default, and then all the advertisers who would have abided by it, said fuck this, no .. and thus it fucking died as being anything useful

anyway ... I do not know for sure if/when GPC will ever be default on for all users in FF - I wish they would purely from a FP perspective and then it (mostly) becomes a moot point, but until it does, we should just do what mozilla do

Here is the meta [1848951](https://bugzilla.mozilla.org/show_bug.cgi?id=1848951) .. do you see anything about turning this on by default for all users .. it's conspicuously absent

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1848951#c3

> a large part of why DNT failed is because Microsoft unilaterally hardcoded it on in their browsers which gave the advertisers an excuse to walk away.

yup .. fucking MS .. ironic

**Comment by Thorin-Oakenpants** [comment]
> However, it would create additional fingerprinting, so I'm not sure if it would be beneficial to all.

I'm not going to modify passive fingerprints, so I will never turn it on. It's also not going to be beneficial if it was enabled (do I really need to explain this again)

**Comment by Thorin-Oakenpants** [comment]
> Epic Portuguese meeting incoming 🚀

taylor swift concert: https://www.taylorswift.com/gig/sat-may-25-2024-estadio-da-luz-lisbon-portugal/

might stay and get me some taytay and swiftie love .. y'all jelly ?

**Comment by xe-3** [comment]
I prefer universal technical solutions as well. But I do not believe there is a universal technical solution that addresses the same scope of problems GPC seeks to address. dFPI (unless I misunderstand its capabilities) is an exceptional universal solution _to a different problem_.

> So yes, I fully appreciate understand what is going on

Respectfully, I do still feel there are things you are misundersting in the specific case of GPC. I respect and defer to your expertise on technical matters or anything related to FF, AF, TBB etc, I have learned much from things you've written, and you have vastly more expertise than I do. But in this specific case, it feels like you are jumping to conclusions about GPC based on a slight misunderstanding of what GPC is and what problems it is trying to solve (your primary criticism that it is irrelevant or ineffective due to dFPI etc, seems more applicable to DNT than GPC).

GPC's primary utility is not in preventing cross site tracking. It's primary purpose as I understand it is to signal a preference that you do not want your personal data to be sold or shared, and that preference is legally enforceable in a growing number of jurisdictions. If respected, GPC addresses things that dFPI and sanitizing between sessions cannot. Particularly in the context of services and websites you log in to (because there are no fully effective technical solutions to data collection in this context). (Just because you log in to a service, doesn't mean you deserve to have your info sold/shared)

GPC isn't a replacement for dFPI or other technical solutions, but it is complementary, and it addresses a different scope of problems than dFPI does.

> When you login, you are already giving away a uuid, so this non-sanitizing, becomes a moot point. And your ToS per that site likely (I honestly don't care) dictate your privacy and make GPC obsolete (again, IDF care)

I disagree. This is precisely a scenario where I think GPC has value. And one where I don't see how technical "universal solutions" could solve the problem. (can you?)

Like you say, once you are using a 1st party service, logged in, ToS (and legal limits) apply, and the GPC is an efficient way to take advantage of rights that many companies now include in their ToS and rights that some jurisdictions mandate and enforce. Users still deserve privacy, still deserve a say over what happens with their personal information, even with first party services and user accounts. The EU recognizes this right by default, in California, Colorado, and other jurisdictions, users must opt-out if they want these sames rights, and the GPC is currently the most efficient, and universal way to do so.

Don't feel obligated to respond to this comment (I don't want to distract you from Taylor and her kitty), I can see that your opinion on enabling GPC has not changed, and I respect that,  so I will let it go (it'd be better to address this upstream if possible anyway, (e.g. toggling GPC on when ETP strict is enabled)).

But I'd humbly encourage you to revisit the GPC with fresh eyes when you have time, because I think you might be slightly but meaningfully misunderstanding one of the primary problems it intends to solve, that to my knowledge has not been solved by technical universal solutions.

As always, I appreciate your time, thoughts, and this project.

**Comment by xe-3** [comment]
> I think Thorin's idea is the fact that this is just a signal and that the signal by itself doesn't guarantee anything on the technical side.

I don't dispute that. If a technical solution existed, or could theoretically exist, I agree that it would be preferable. But as I understand it, there is no technical solution.

> Meanwhile, for example, we have the RFP, which in effect guarantees that factors will be changed in such a way as to "fool" the website you visit.

except for any website where you identify yourself (intentionally or accidentally), login, etc. <-- this, is the primary value I see in GPC. First party services you choose to use, or are forced to use, with an account or with your real identity. E.g. your insurance company, your mobile carrier, a newspaper subscritpion etc. These are not cases, where dFPI or RFP can do much for you. GPC, is imperfect, legal solutions are imperfect, but in this context, I don't see any alternative. And both the EU and California have shown a willingness to prosecute violators.

 > In my opinion, as much as the GPC idea is good and I agree with its adoption, I think that something this important should not be decided by the arkenfox user.js, but rather by Mozilla at a more central/universal level (similar to Brave, which adopted for everyone forcibly).

That is a reasonable point of view. I'm not sure I agree or not, but I am sympathetic to it, and respect it. And I accept this as reasonable reason to reject the proposal, even if I am personally disappointed by that decision.

**Comment by Thorin-Oakenpants** [comment]
> GPC's primary utility is not in preventing cross site tracking. It's primary purpose as I understand it is to signal a preference that you do not want your personal data to be sold or shared

what personal data? Let me explain it yet again - every time you visit the site has no (easily available on-tap) record of you - it keeps creating new shadow profiles and assigning new uuids - big fucking deal (again, excluding IP address and fingerprinting, excluding sites you log into, where you are gifting them an id to reused) - in other words partitioning and sanitizing removes this

maybe now _you_ understand

**Comment by Thorin-Oakenpants** [comment]
https://discuss.techlore.tech/t/i-want-to-like-mullvad-browser-but/8826/13

@xe-3 since TB/MB start in PB mode, GPC will on next ESR release, so in about 3 to 4 months .. unless someone decides to override that. For the TB/MB crowd is doesn't matter what FF does. So you get your wish there. Not sure why you plaster the internet everywhere with this request, I think I've seen it in a dozen places and I'm not even looking (do you have special shares in GPC Inc. j/k) - but there you go .. success, somewhere, the once .. yay .. enjoy 🍻

**Comment by xe-3** [comment]
> since TB/MB start in PB mode, GPC will on next ESR release, so in about 3 to 4 months

That's good news in my eyes, I hadn't connected those dots in my mind. Thanks for the update!

> Not sure why you plaster the internet everywhere with this request [...] seen it in a dozen places

A dozen might be a _sliiiight_ exaggeration :) 
I didn't intend to 'plaster the internet' I'm bummed if that's how it came off. It's just a feature that I think has value and I suggested it to 4ish projects that I care about and personally use (Arkenfox being one of them, and the other 3 are (1) Firefox--specifically for etp strict mode (2) Librewolf, (3) Mullvad Browser). 

> but there you go .. success, somewhere, the once .. yay .. enjoy 🍻

Woo! looks like my GPC shares are about to go through the roof 💰 🥂  I guess I don't have to hide my ulterior motives any longer... acquire massive wealth and affluence through buying as many shares as possible in... *checks notes*... a not for profit project..? Damnit, I think I may have made a poor investment decision...

**Comment by ntnguyen1234** [comment]
Hi, when I tested arkenfox + these overrides

```js
user_pref("privacy.resistFingerprinting", true); // [FF41+]
user_pref("privacy.resistFingerprinting.pbmode", true); // [FF114+]
```

in a new Firefox profile (v131.0.2) and test on https://arkenfox.github.io/TZP/tzp.html , I see the values of DNT and GPC are `1/true`

![image](https://github.com/user-attachments/assets/d1216d64-82fd-4a4b-a70f-9cb8b6bfb97e)

However, the settings in Firefox are not ticked

![image](https://github.com/user-attachments/assets/41461e77-48b5-43ca-9349-44741bbbaa59)

Is it expected?

**Comment by Thorin-Oakenpants** [comment]
you do not need `pbmode` - if RFP is true it is enforced in normal and pbm windows and the pbmode pref is ignored. The pbmode pref is there to enable RFP in pb mode when it's disabled by default
```js
user_pref("privacy.resistFingerprinting", true);
user_pref("privacy.resistFingerprinting.pbmode", true);
```

RFP has nothing to do with DNT or GPC

DNT - is enforced with ETP Strict - the UI is misleading
- see https://bugzilla.mozilla.org/show_bug.cgi?id=1865032

GPC - is enforced with pb mode
- the UI is for using it in all windows

**Comment by Thorin-Oakenpants** [comment]
> test on https://arkenfox.github.io/TZP/tzp.html , I see the values of DNT and GPC are 1/true

Were you in a private window? I see 1/false

**Comment by ntnguyen1234** [comment]
> > test on https://arkenfox.github.io/TZP/tzp.html , I see the values of DNT and GPC are 1/true
> 
> Were you in a private window? I see 1/false

Yes, I was in private window. After I commented above, I just realized that and when tested again with non-private window, it's `1/false`.

**Comment by Thorin-Oakenpants** [comment]
doh, just realized as I re-read some things "when I tested arkenfox + Always use private browsing mode" .. my bad, sue me :)

**Comment by Thorin-Oakenpants** [comment]
we had this conversation, ~~not going to look for it, might be here~~ [up the top in this comment etc](https://github.com/arkenfox/user.js/issues/1818#issuecomment-2012697791)

honestly, Brave enabled it and they're what 70mn users .. FF at 180mn isn't a big deal, and it's not DNT it's GPC with _some_ teeth behind it. If chrome enabled it (and all the forks said fuck it, why not, not a big deal) then what are companies going to do - break the law in the EU etc ?

**Comment by Thorin-Oakenpants** [comment]
FF141+ https://bugzilla.mozilla.org/show_bug.cgi?id=1951781 - DNT no longer in PB windows or when ETP Strict is enabled

**Comment by Thorin-Oakenpants** [comment]
yes, I know :) One less thing that distinguished PB windows (albeit it was tied to ETP Strict and in the past had a UI and pref - and most users wouldn't change settings, so it was a strong indicator) - now we only have a few things left, GPC is one of them

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1366318#c13
