### ISSUE TITLE
I think arkenfox is slowing down certain pages

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1819]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: 
![image](https://github.com/arkenfox/user.js/assets/13978119/c9e20e84-442b-40b2-a502-b453492f3e0b)
```
Edition	Windows 10 IoT Enterprise LTSC
Version	21H2
Installed on	‎3/‎23/‎2024
OS build	19044.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0
```
  - Steps to Reproduce (STR):
1. Download and install Firefox.
2. Download and run arkenfox.
3. Visit https://app.tvtime.com/ and https://my.bezeq.co.il/#/dashboard_screen
  - Expected result: Pages will not be slow, memory usage will be low.
  - Actual result: Slow page performance, can't login, high memory usage:
![image](https://github.com/arkenfox/user.js/assets/13978119/f168bc6c-de4f-4cbd-92d1-61737af00aa3)
  - Console errors and warnings: ?
  - Anything else you deem worth mentioning: First noticed on my main machine, later on tested on a fresh install of windows on VM.
On the second website (bezeq) it will have high memory usage.
This is the default arkenfox user.js, there are no overrides.
As I said - tested on VM, so I also tested it without arkenfox and there were no issues, this is caused by arkenfox.

---

**Comment by Thorin-Oakenpants** [comment]
Not even going to try to diagnose or confirm memory/perf

both sites seem to use webgl - try that
- close Firefox, reopen (so everything is sanitized)
- open about:config, type `webgl.disabled` and double-click it to `false`
- test

If that's not the pref then try `privacy.resistFingerprinting`

There are some basic very common prefs that cause 99% of all issues, listed in the wiki. TRY them - I just listed two

**Comment by Thorin-Oakenpants** [comment]
I can't tell for sure, but if webgl is required then the site won't work anyway - it's not just _your_ memory and perf - it's bad website design

**Comment by Thorin-Oakenpants** [comment]
out of 9 items listed on the wiki - 3 are directly web site related - all the rest are usability issues (retain logins, history, etc). I don't think a 9 item list with webgl, RFP and strict pinning is making anything too hard to find

webgl also has a `[SETUP-WEB]` tag - as per the wiki `[SETUP-WEB] can cause some websites to break`

**Comment by Thorin-Oakenpants** [comment]
thanks for the info and troubsleshooting .. here's some 🍕 :)
