### ISSUE TITLE
how to modify user_perf `browser.uiCustomization.state`?

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1823]
a bit unrelated to arkenfox, but i'm not sure where else to ask this,
i'm trying to add `browser.uiCustomization.state` user_perf to `user_overrides` and i run in a bit of hard time since this perf has value of many `"` and `{`, it's not simply `true` or `false`, it's a long string which i have no idea how to modify.

**Comment by Thorin-Oakenpants** [comment]
take the line from prefs.js and append `user_`
