### ISSUE TITLE
who's up for some simple testing - any platform .. all welcome, except that _one_ guy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1824]
https://arkenfox.github.io/TZP/tests/fontdefaults.html
- please use a new profile or your own if you know you haven't fucked around with fonts>advanced
- zoom doesn't matter, zooming text only doesn't matter etc

Tor Browser, Mullvad Browser, Firefox, ESR, dev, nightly, stable .... android, windows, mac, any flavor of Linux you have: just provide that info in your reply: platform, browser + version - TIA .. here's some free 🧀 I'll start

**e5179dbb** :  windows 11: FF115-127, TB13+, MB13+

<details><summary>click me for details</summary><p>

```json
{
  "sans-serif-13-16-16": [
    "arabic",
    "devanagari",
    "hebrew",
    "thai"
  ],
  "sans-serif-16-16-16": [
    "japanese",
    "korean",
    "simplified chinese",
    "traditional chinese (hong kong)",
    "traditional chinese (taiwan)"
  ],
  "serif-13-16-16": [
    "armenian",
    "bengali",
    "cyrillic",
    "ethiopic",
    "georgian",
    "greek",
    "gujurati",
    "gurmukhi",
    "kannada",
    "khmer",
    "latin",
    "malayalam",
    "mathematics",
    "odia",
    "other",
    "sinhala",
    "tamil",
    "telugu",
    "tibetan",
    "unified canadian syllabary"
  ]
}
```

</p></details>

**Comment by Thorin-Oakenpants** [comment]
**632e080a** : Android 9: TB13 stable + alpha, FF125, FF127 Nightly

<details><summary>click me for details</summary><p>

```json
{
  "sans-serif-12-16-16": [
    "arabic",
    "cyrillic",
    "greek",
    "hebrew",
    "latin",
    "other"
  ],
  "sans-serif-13-16-16": ["thai"],
  "sans-serif-16-16-16": [
    "japanese",
    "korean",
    "simplified chinese",
    "traditional chinese (hong kong)",
    "traditional chinese (taiwan)"
  ],
  "serif-13-16-16": [
    "armenian",
    "bengali",
    "devanagari",
    "ethiopic",
    "georgian",
    "gujurati",
    "gurmukhi",
    "kannada",
    "khmer",
    "malayalam",
    "mathematics",
    "odia",
    "sinhala",
    "tamil",
    "telugu",
    "tibetan",
    "unified canadian syllabary"
  ]
}
```

</p></details>

cc @PieroV

**Comment by glitsj16** [comment]
**a4253645** : Arch Linux: TB13 stable, FF125, FF127 Nightly

<details>
<summary> click me for details </summary>

```json
{
  "sans-serif-12-16-16": ["arabic", "hebrew"],
  "sans-serif-13-16-16": ["thai"],
  "sans-serif-16-16-16": [
    "japanese",
    "korean",
    "simplified chinese",
    "traditional chinese (hong kong)",
    "traditional chinese (taiwan)"
  ],
  "serif-12-16-16": ["cyrillic", "greek", "latin", "other"],
  "serif-13-16-16": [
    "armenian",
    "bengali",
    "devanagari",
    "ethiopic",
    "georgian",
    "gujurati",
    "gurmukhi",
    "kannada",
    "khmer",
    "malayalam",
    "mathematics",
    "odia",
    "sinhala",
    "tamil",
    "telugu",
    "tibetan",
    "unified canadian syllabary"
  ]
}

```

</details>

**Comment by 2glops** [comment]
Debian 12 bookworm
Firefox ESR 115 / release 125 / Beta 126 / Nightly 127
Mullvad Browser 13.0.14
Tor browser 13.0.14 / alpha 13.5a6

a4253645

{
  "sans-serif-12-16-16": ["arabic", "hebrew"],
  "sans-serif-13-16-16": ["thai"],
  "sans-serif-16-16-16": [
    "japanese",
    "korean",
    "simplified chinese",
    "traditional chinese (hong kong)",
    "traditional chinese (taiwan)"
  ],
  "serif-12-16-16": ["cyrillic", "greek", "latin", "other"],
  "serif-13-16-16": [
    "armenian",
    "bengali",
    "devanagari",
    "ethiopic",
    "georgian",
    "gujurati",
    "gurmukhi",
    "kannada",
    "khmer",
    "malayalam",
    "mathematics",
    "odia",
    "sinhala",
    "tamil",
    "telugu",
    "tibetan",
    "unified canadian syllabary"
  ]
}

**Comment by sertonix** [comment]
*a4253645*: Alpine Linux: ESR115, FF125, FF126 dev

*632e080a*: Android 8.1: FF125, FF126 nightly, TB13 stable + alpha

(json already above)

**Comment by DuMuT6p** [comment]
a4253645 : Fedora 39, Firefox 125
`{
  "sans-serif-12-16-16": ["arabic", "hebrew"],
  "sans-serif-13-16-16": ["thai"],
  "sans-serif-16-16-16": [
    "japanese",
    "korean",
    "simplified chinese",
    "traditional chinese (hong kong)",
    "traditional chinese (taiwan)"
  ],
  "serif-12-16-16": ["cyrillic", "greek", "latin", "other"],
  "serif-13-16-16": [
    "armenian",
    "bengali",
    "devanagari",
    "ethiopic",
    "georgian",
    "gujurati",
    "gurmukhi",
    "kannada",
    "khmer",
    "malayalam",
    "mathematics",
    "odia",
    "sinhala",
    "tamil",
    "telugu",
    "tibetan",
    "unified canadian syllabary"
  ]
}`

**Comment by Thorin-Oakenpants** [comment]
thanks everybody - confirms what I suspected - that's it's stable and equivalency of OS - but of course fingerprintable if you change any of it (Fonts > Advanced)

Am working on a separate issue which is very noisy (subpixels, font family fallbacks, font character async fallback, app language, web language etc) - so good to know I can eliminate these settings - which I knew weren't really involved since I set an actual size, but not a language, and in due diligence, hence this test

once again, thanks .. here's another piece of 🧀
