### ISSUE TITLE
Should I use FPP, RFP or both

### ISSUE THREAD

**Issue by jh-devv** [arkenfox/user.js#1826]
Hey!

I am pretty new to "resisting fingerprinting", before I just enabled strict mode `FPP` and that was it.

The question is, can I use both at the same time, even with something like `ublock` installed, the wiki mentioned something about extensions?

Regards,
jh-devv ^-^

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/33a84b608c8a1f871c6ce9c4d2b932dc57078fae/user.js#L714

**Comment by jh-devv** [comment]
> https://github.com/arkenfox/user.js/blob/33a84b608c8a1f871c6ce9c4d2b932dc57078fae/user.js#L714

Oh yea, thanks! :)

**Comment by jh-devv** [comment]
@rusty-snake What about `pbmode`, should I use it?

If I want the "best anti-fingerprinting":

- Could I just enable `4500 and `4501` + `pb-mode`. Should I even use `pbmode` in FF 119+?

**Comment by rusty-snake** [comment]
For fping it does not make much difference with AF. If you want to use it for other reasons depends on you.

**Comment by eternal-sorrow** [comment]
> RFP overrides FPP

This does not answer the question. If RFP is enabled, it obviously doesn't matter. Bus should it be enabled? Of FPP is enough?

**Comment by rusty-snake** [comment]
Well it answers the "or both".

For either or see https://github.com/arkenfox/user.js/issues/1846#issuecomment-2163324853 *and the following*.

**Comment by Thorin-Oakenpants** [comment]
![snoop](https://github.com/user-attachments/assets/be76eb0a-0d25-4083-bf4a-20f0161c1a2e)
