### ISSUE TITLE
Difference between 4501 and 4510 in terms of preferred colors

### ISSUE THREAD

**Issue by jh-devv** [arkenfox/user.js#1830]
What is the difference between `4501` and `4510`, since `privacy.resistFingerprinting` already prefers `light` mode?

Is `4510` just for that it does not take the "preferred colors" from the "system colors" if `4501` is not enabled?

Since, in the [code](https://hg.mozilla.org/mozilla-central/rev/4739353088fcad81bc126deab56e8de0fad7a88a#l10.13), `privacy.resistFingerprinting` always takes priority over `browser.display.use_system_colors` and this is also somewhat said in the "drawbacks" for `4501`.

---

*If you notice anything dumb with this issue, don't hesitate to point if I am wrong!*

**Comment by Thorin-Oakenpants** [comment]
so prefers-color-scheme is binary a css property - either `light` or `dark`. It can reflect your OS, your theme or neither. It doesn't matter what sets it. When a website asks (or in ua client hints if/when gecko adds them), the browser indicates what you _prefer_. So websites that can offer a dark or light mode can serve you that. This is all it is. With RFP enabled, everyone says they prefer `light`

system colors are exactly that - colors used by your OS. See https://arkenfox.github.io/TZP/tests/csscolors.html

RFP controls a number of these, but not all. The pref in `4510` helps control a few more. But there are still some that are not tightly set to prevent entropy - especially as we transition away from deprecated and reduce -moz prefs into CSS4

**Comment by Thorin-Oakenpants** [comment]
AFAIK ... these css colors (and a lot have been removed) in the past were so each platform could have a native look and feel for widgets (buttons, input forms, progress bars, etc), and match your system

for example AccentColor if you change it in your system on OS, it is reflected in the web content, e.g. focus rings

![example](https://github.com/arkenfox/user.js/assets/16656956/4933bfc4-b61a-4e00-b405-7a13771d6937)

**Comment by Thorin-Oakenpants** [comment]
So as you can see, if everyone could just pick and choose whatever they wanted (there are over 16 million rgb colors) for each of the various properties, and it also gets changed by system themes (i.e users don't need to specifically go into settings to change them individually), then that's more variations than people on the planet

so RFP tries to mitigate that, but we haven't fully solved it yet but I have plans :)

closing, but feel free to keep asking

**Comment by Thorin-Oakenpants** [comment]
wow .. windows 11 at least ... toggling `show accent color on title bars and windows` (windows system setting) .. changes the chrome size by 1px :)
