### ISSUE TITLE
user pref for "extenstion has been added" notification

### ISSUE THREAD

**Issue by Obegg** [arkenfox/user.js#1834]
![image](https://github.com/arkenfox/user.js/assets/13978119/857ca855-a1c5-41e1-ae2e-34c2ba7e7550)

Is there any possible way to hide this notification?

**Comment by rusty-snake** [comment]
> Is there any possible way to hide this notification?

Click on "Okay". SCNR.


Otherwise mess around with userChrome.css.

**Comment by Thorin-Oakenpants** [comment]
please stop bombarding this repo with questions that are not about privacy/security/tracking - there's always r/firefox
