### ISSUE TITLE
LocalFortress (extension)

### ISSUE THREAD

**Issue by atomGit** [arkenfox/user.js#1839]
[LocalFortress ](https://addons.mozilla.org/en-US/firefox/addon/localfortress/)

> This extension blocks requests to localhost from websites that are not running on localhost. ...

not sure this is the best way to handle this, but it's quick and easy

uBO users shouldn't need this ('Block Outsider Intrusion into LAN' filter list)

**Comment by Thorin-Oakenpants** [comment]
4 users

**Comment by atomGit** [comment]
4 months old

**Comment by Thorin-Oakenpants** [comment]
age is irrelevant. Why would anyone ever suggest an unproven and practically zero users extension? And that's before we even look at the developer and if the extension even does anything meaningful

**Comment by atomGit** [comment]
> age is irrelevant.

so is the number of users

> Why would anyone ever suggest an unproven...

dunno what's gotten into you - i didn't suggest anything, i simply linked to it for review after having a cursory look at the code and you immediately close it

whatever - i won't bother contributing anything more

**Comment by Thorin-Oakenpants** [comment]
why would I review something that has no record (age is immaterial - it could be 4 months old, have 10k users, be written by gorhill and actually do something - _then_ it would be worth looking at)

nothing has gotten into me

**Comment by Thorin-Oakenpants** [comment]
FYI: now down to 3 users
