### ISSUE TITLE
 126.0 - Firefox’s new search data collection - Disabled? 

### ISSUE THREAD

**Issue by pflanzenandi** [arkenfox/user.js#1840]
Hello, is the new telemetry introduced in 126.0 disabled by default via arkenfox user.js v122?
Or do I need to add a perf?

**Comment by rusty-snake** [comment]
It very likely is covered by the master switches. And if not, it will be picked up in the diffs for 126.

**Comment by Thorin-Oakenpants** [comment]
[it's covered by the master switch](https://blog.mozilla.org/en/products/firefox/firefox-search-update/)
