### ISSUE TITLE
126.0: potential addition for 0105

### ISSUE THREAD

**Issue by glitsj16** [arkenfox/user.js#1841]
FYI:

`0105` has user_pref("browser.newtabpage.activity-stream.showSponsored", false); // [FF58+]

Today I noticed there's `browser.newtabpage.activity-stream.system.showSponsored` (defaulting to true). Might be something to add to 0105 in `false` state.

**Comment by 1Naim** [comment]
still default false for me, fyi im on Fedora 40

**Comment by Thorin-Oakenpants** [comment]
added in FF120 as false and still false ... nothing to do o even look at (assuming we care) until/if it ever changes

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1858038
