### ISSUE TITLE
[Solved]Problems with fonts on Kubuntu 24.04 LTS

### ISSUE THREAD

**Issue by Innocentius0** [arkenfox/user.js#1844]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [X] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: v126 & Kubuntu 24.04 LTS
  - Steps to Reproduce (STR): Install Arkenfox, go to a website like Wikipedia or Archwiki. 
  - Expected result: That it should look like it is supposed to do without the spaces. 
  - Actual result: The fonts look strange with large spaces, see the image below. 
  - Console errors and warnings: 
Some cookies are misusing the recommended “SameSite“ attribute 41
Request for font "Noto Sans" blocked at visibility level 1 (requires 2)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://login.wikimedia.org/wiki/Special:CentralAutoLogin/checkLoggedIn?type=script&wikiid=enwiki startup.js:1053:16
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://meta.wikimedia.org/w/index.php?title=Special:BannerLoader&campaign=wle_2024_se&banner=wle_2024_se&uselang=en&debug=false jquery.js:10016:18
Loading failed for the <script> with source “https://meta.wikimedia.org/w/index.php?title=Special:BannerLoader&campaign=wle_2024_se&banner=wle_2024_se&uselang=en&debug=false”. Main_Page:1:1
Cookie “WMF-Last-Access” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute. checkLoggedIn
Cookie “GeoIP” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute. checkLoggedIn
Cookie “NetworkProbeLimit” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute. checkLoggedIn
Cookie “WMF-Last-Access” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute. checkLoggedIn
Cookie “GeoIP” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute. checkLoggedIn
Cookie “NetworkProbeLimit” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute

  - Anything else you deem worth mentioning:
After troubleshooting, the culprit seems to be "privacy.resistFingerprinting", true". If I disable this option, it does work fine.  I did not have this problem before upgrading from 23.10. I ran the following command, after trying to find a solution:

for i in $(echo verdana,arial,helvetica,sans-serif | tr ',' ' '); do fc-match $i; done

and I got the following results:

NotoSans-Regular.ttf: "Noto Sans" "Regular"
LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
NotoSans-Regular.ttf: "Noto Sans" "Regular"

Which seems normal to me. 

I also tried to set the following prefs to 2, without success:

user_pref("layout.css.font-visibility.private", 2);
user_pref("layout.css.font-visibility.standard", 2);
user_pref("layout.css.font-visibility.trackingprotection", 2);

This is obviously a setting I do not want to set to false, so if there is some way to solve it that would be very much appreciated!

![Screenshot_20240522_195436](https://github.com/arkenfox/user.js/assets/167767051/d4495ad4-22cd-4b5a-8a5a-d4aaca39e939)

**Comment by Thorin-Oakenpants** [comment]
for my reference

```
// 1402: limit font visibility (Windows, Mac, some Linux) [FF94+]
   // Uses hardcoded lists with two parts: kBaseFonts + kLangPackFonts [1], bundled fonts are auto-allowed
   // In normal windows: uses the first applicable: RFP over TP over Standard
   // In Private Browsing windows: uses the most restrictive between normal and private
   // 1=only base system fonts, 2=also fonts from optional language packs, 3=also user-installed fonts
   // [1] https://searchfox.org/mozilla-central/search?path=StandardFonts*.inc
   // [-] https://bugzilla.mozilla.org/1847599
   // user_pref("layout.css.font-visibility.private", 1);
   // user_pref("layout.css.font-visibility.standard", 1);
   // user_pref("layout.css.font-visibility.trackingprotection", 1);
```

Thanks. I'm traveling atm, so can't give full attention for 3 or 4 days. The fonts settings _should_ work with RFP, i.e level 2 should be the same as FPP - but linux is also a little different, as not all distros are the same and not all are covered.

So initially, as a test, can you please screenshot what it should look like, and can you inspect the font used in both cases (right click and inspect the element, look at the rightmost panel, choose the fonts tab).

At first glance this is either RFP being overly restrictive, or something in FPP fonts needs addressing

**Comment by Innocentius0** [comment]
PROBLEM SOLVED!

The update butchered one of my etc/fonts/conf.d files, specifically 56-kubuntu-noto.conf. The file had prioritized Noto color emoji as font on all types, so I rearrange it to a previous version which I had backed up using timeshift.

**Comment by 1Naim** [comment]
u can close this issue if its solved

**Comment by Thorin-Oakenpants** [comment]
thanks @Innocentius0 .. linux is special :) I should have also mentioned font config files, but you know, travel, drinking ... :)

**Comment by valr337** [comment]
> PROBLEM SOLVED!
> 
> The update butchered one of my etc/fonts/conf.d files, specifically 56-kubuntu-noto.conf. The file had prioritized Noto color emoji as font on all types, so I rearrange it to a previous version which I had backed up from timeshift.

Hey can you provide that font conf? The update also broke my font config.

**Comment by Innocentius0** [comment]
> > PROBLEM SOLVED!
> > The update butchered one of my etc/fonts/conf.d files, specifically 56-kubuntu-noto.conf. The file had prioritized Noto color emoji as font on all types, so I rearrange it to a previous version which I had backed up from timeshift.
> 
> Hey can you provide that font conf? The update also broke my font config.

Hello! Just edit 56-kubuntu-noto.conf using e.g. kate and rearrange the order like in the code below. I got the specific order from my previous version of Kubuntu. 




```
<family>serif</family>
 <prefer>
      <family>Tinos</family>
      <family>Noto Serif</family>
      <family>Noto Serif CJK SC</family>
      <family>Noto Naskh Arabic</family>
      <family>Noto Serif Thai</family>
      <family>Noto Serif Armenian</family>
      <family>Noto Serif Georgian</family>
      <family>Noto Serif Devanagari</family>
      <family>Noto Serif Hebrew</family>
      <family>Noto Serif Bangali</family>
      <family>Noto Serif Gujarati</family>
      <family>Noto Serif Kannada</family>
      <family>Noto Serif Malayalam</family>
      <family>Noto Serif Tamil</family>
      <family>Noto Serif Telugu</family>
      <family>Lohit Punjabi</family>
      <family>Lohit Oriya</family>
      <family>Noto Serif Khmer</family>
      <family>Noto Serif Lao</family>
      <family>Noto Serif Ethiopic</family>
      <family>Noto Serif Myanmar</family>
      <family>Noto Serif Sinhala</family>
      <family>Jomolhari</family>
      <family>Noto Color Emoji</family>
      <family>Noto Sans Symbols</family>
      <family>Noto Sans Symbols2</family>
      <family>DejaVu Serif</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Arimo</family>
      <family>Noto Sans</family>
      <family>Noto Sans CJK SC</family>
      <family>Noto Sans Arabic</family>
      <family>Noto Sans Thai</family>
      <family>Noto Sans Devanagari</family>
      <family>Noto Sans Tamil</family>
      <family>Noto Sans Hebrew</family>
      <family>Noto Sans Bengali</family>
      <family>Noto Sans Telugu</family>
      <family>Noto Sans Kannada</family>
      <family>Noto Sans Malayalam</family>
      <family>Noto Sans Gurmukhi</family>
      <family>Noto Sans Gujarati</family>
      <family>Noto Sans Oriya</family>
      <family>Noto Sans Armenian</family>
      <family>Noto Sans Georgian</family>
      <family>Noto Sans Khmer</family>
      <family>Noto Sans Lao</family>
      <family>Noto Sans Ethiopic</family>
      <family>Noto Sans Myanmar</family>
      <family>Noto Sans Sinhala</family>
      <family>Jomolhari</family>
      <family>Noto Sans Coptic</family>
      <family>Noto Sans Deseret</family>
      <family>Noto Sans TaiTham</family>
      <family>Noto Sans CanadianAboriginal</family>
      <family>Noto Sans Yi</family>
      <family>Noto Sans Tifinagh</family>
      <family>Noto Sans Adlam</family>
      <family>Noto Sans Cherokee</family>
      <family>Noto Sans Chakma</family>
      <family>Noto Sans Osage</family>
      <family>Noto Color Emoji</family>
      <family>Noto Sans Symbols</family>
      <family>Noto Sans Symbols2</family>
      <family>DejaVu Sans</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Cousine</family>
      <family>Noto Sans Mono</family>
      <family>Noto Sans Mono CJK SC</family>
      <family>Noto Naskh Arabic</family>
      <family>Noto Sans Thai</family>
      <family>Noto Sans Devanagari</family>
      <family>Noto Sans Tamil</family>
      <family>Noto Sans Bengali</family>
      <family>Noto Sans Telugu</family>
      <family>Noto Sans Kannada</family>
      <family>Noto Sans Malayalam</family>
      <family>Noto Sans Gurmukhi</family>
      <family>Noto Sans Gujarati</family>
      <family>Noto Sans Oriya</family>
      <family>Noto Sans Armenian</family>
      <family>Noto Sans Georgian</family>
      <family>Noto Sans Ethiopic</family>
      <family>Noto Sans Myanmar</family>
      <family>Noto Sans Sinhala</family>
      <family>Noto Sans Tibetan</family>
      <family>Noto Sans Coptic</family>
      <family>Noto Sans Deseret</family>
      <family>Noto Sans TaiTham</family>
      <family>Noto Sans Cherokee</family>
      <family>Noto Sans Chakma</family>
      <family>Noto Sans Osage</family>
      <family>Noto Color Emoji</family>
      <family>Noto Sans Symbols</family>
      <family>Noto Sans Symbols2</family>
      <family>Droid Sans Fallback</family>
      <family>DejaVu Sans Mono</family>
    </prefer>
  </alias>
  <alias>
    <family>ui-sans</family>
    <prefer>
      <family>Noto Sans UI</family>
      <family>Noto Sans CJK SC</family>
      <family>Noto Naskh Arabic UI</family>
      <family>Noto Sans Thai UI</family>
      <family>Noto Sans Devanagari UI</family>
      <family>Noto Sans Tamil UI</family>
      <family>Noto Sans Hebrew</family>
      <family>Noto Sans Bengali UI</family>
      <family>Noto Sans Telugu UI</family>
      <family>Noto Sans Kannada UI</family>
      <family>Noto Sans Malayalam UI</family>
      <family>Noto Sans Gurmukhi UI</family>
      <family>Noto Sans Gujarati UI</family>
      <family>Noto Sans Oriya UI</family>
      <family>Noto Sans Armenian</family>
      <family>Noto Sans Georgian</family>
      <family>Noto Sans Khmer UI</family>
      <family>Noto Sans Lao UI</family>
      <family>Noto Sans Ethiopic</family>
      <family>Noto Sans Myanmar UI</family>
      <family>Noto Color Emoji</family>
      <family>Noto Symbols</family>
      <family>Droid Sans Fallback</family>
      <family>DejaVu Sans</family>
    </prefer>
  </alias>
```
