### ISSUE TITLE
Typo in user.js

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1848]
/* 4003: disable remote FPP overrides [FF127+] ***/
   // user_pref("privacy.fingerprintingProtection.remoteOverrides.enabled"; false);

"**;** false

should be

"**,** false

(comma instead of semi-colon)
(same typo in the changelog issue)

~~also, this seems to be a hidden pref (firefox v126), so we should mark it as such~~

![image](https://github.com/arkenfox/user.js/assets/30274161/00028afb-7448-4529-b150-72479df10ebb)

**Comment by Thorin-Oakenpants** [comment]
thanks
