### ISSUE TITLE
Clipboard pref default changed

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1849]
/* 0807: disable urlbar clipboard suggestions [FF118+] ***/
   // user_pref("browser.urlbar.clipboard.featureGate", false); // **[DEFAULT: true FF125+]**

Default is false since v126 (was true in v125)

https://www.mozilla.org/en-US/firefox/126.0/releasenotes/

> The URL Paste Suggestion feature added in [Fx125](https://www.mozilla.org/firefox/125.0.1/releasenotes/) was temporarily disabled while the team investigates a potential performance issue. The feature will be re-enabled in a future release once the performance issue is addressed.

**Comment by Thorin-Oakenpants** [comment]
okie dokie ... did I miss that in 126 diffs? will edit next PR
