### ISSUE TITLE
Privacy-Preserving Attribution (FF 128)

### ISSUE THREAD

**Issue by glitsj16** [arkenfox/user.js#1854]
https://support.mozilla.org/en-US/kb/privacy-preserving-attribution
Privacy-preserving attribution (PPA) is an experimental feature shipping in Firefox 128.
Privacy & Security > Website Advertising Preferences

Is it worthwhile to add `user_pref("dom.private-attribution.submission.enabled", false);` in user.js?

**Comment by Thorin-Oakenpants** [comment]
nope
- we're not on 128 yet - we await diffs rather than action possible future things
   - i.e we are default false and i do not want to liter the user.js with enforcing loads of defaults
- we disable experiments (and we don't particularly care about nightly: i can;t remember if experiments can be disabled there)
- it literally says "privacy preserving" so sounds like a good thing
   - I actually have a quick look at PPA the other week and on face value it's something we would want, so until it lands in stable, I don't care to dive any deeper

**Comment by Thorin-Oakenpants** [comment]
> nope

yup, as part of the "quiet fox"

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1908312

**Comment by Thorin-Oakenpants** [comment]
I think I'll just remove the pref TBH

**Comment by sertonix** [comment]
I would like to have a comment to hopefully reduce the misconceptions around PPA

**Comment by Thorin-Oakenpants** [comment]
nope - the UI (when landed) will clearly show it unchecked and greyed out - nothing to do or see

**Comment by MineRock** [comment]
I'm currently on version 128.0, freshly installed and user.js is from the latest commit (Thorin-Oakenpants-patch-2), PPA seems to be enabled for me even when telemetry is disabled.
![image](https://github.com/user-attachments/assets/a706b9a0-9fa8-4c0c-8c6d-a7dda435d29c)
![image](https://github.com/user-attachments/assets/2d4cf624-823f-452c-b715-57802fda454d)

**Comment by glitsj16** [comment]
@MineRock It's confusing, but what you're seeing is the buggy UI. The proper fix is in `128.0.2`. Your OS should catch up pretty soon.

**Comment by xe-3** [comment]
> PPA seems to be enabled for me even when telemetry is disabled.

Seems to be,  but it isn't. As @glitsj16 its just an oversight with the UI, its been fixed, not sure it has rolled out yet though, PPA can't work without the Telemetry subsystem according to Mozilla. Confirmation [here](https://redlib.kylrth.com/r/firefox/comments/1e43w7v/comment/lde62d4/) and [here](https://github.com/mozilla/explainers/issues/14#issuecomment-2237823919)

**Comment by boredsquirrel** [comment]
I dont see how settings this value to "false" causes harm? We can comment it out anyways.

Currently it looks as if arkenfox would be lacking behind.

@glitsj16 where did you get that info? Would be nice if you are right.

**Comment by boredsquirrel** [comment]
thanks for being so fast in tracking this down! I understood now, if not already done I could help document the change somewhere
