### ISSUE TITLE
add FPP granularOverrides for the FYI factor

### ISSUE THREAD

**Issue by qxlf** [arkenfox/user.js#1857]
Resist fingerprinting spoofs a couple things, including my time zone.
my time zone is utc +2:00, can i change it to that without disabeling resist finger printing?

**Comment by sertonix** [comment]
I think the best you can get is FPP with all RFPTargets except timezone spoofing.

**Comment by qxlf** [comment]
how would i do that?

**Comment by Thorin-Oakenpants** [comment]
1. https://github.com/arkenfox/user.js/blob/6446d73cf572fcdf631534a5a51276a64eec4a2d/user.js#L735-L741
2. https://github.com/arkenfox/user.js/issues/1334

**Comment by qxlf** [comment]
thanks

**Comment by Thorin-Oakenpants** [comment]
so something like `+AllTargets, -JSDateTimeUTC`

**Comment by Thorin-Oakenpants** [comment]
you can also override it for specific sites - e.g. gmail gets the real time but all other sites get UTC (or Atlantic/Reykjavik in FF128+)

**Comment by Thorin-Oakenpants** [comment]
> override it for specific sites

`privacy.fingerprintingProtection.granularOverrides` - takes a JSON

```
[ { "firstPartyDomain": "example.com" , "overrides": "+Example1" }, { "firstPartyDomain": "example.org" , "overrides": "+Example2" } ]
```

**Comment by qxlf** [comment]
i want my timezone to be the same across the web, i saw in the first link that the command was something like:
ITEM_VALUE(AllTargets, 0xFFFFFFFF'FFFFFFFF)
what command type would i need to get my timezone the same across the web?

**Comment by Thorin-Oakenpants** [comment]
So first things first

- create an `overrides-user.js` in the same directory you have `user.js`
- add this (below)
- close FF
- run the updater (so your overrides are appended to the end of the user.js)
- run prefsCleaner (always best to do this when you update so commented out prefs get reset)
- restart FF

```js
// my arkenfox overrides

// disable RFP so FPP kicks in
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("webgl.disabled", false);

// change FPP to use all RFP (+) protections except the ones I don't want (-) globally
user_pref("privacy.fingerprintingProtection.overrides", "+AllTargets,-JSDateTimeUTC");
```

NOTE the `+` and `-` signs
- the syntax is comma delimited `AllTargets,-RFPTarget1,-RFPTarget2,-RFPTarget3`
- you can change the signs e.g disable all protections and only add some

In arkenfox v128 the "disable RFP so FPP kicks in" will be redundant as they will be the default (if you run prefsCleaner once arkenfox 128 is released)

**Comment by qxlf** [comment]
im probably blind, but there is no target specified for time on the linked site.
and i didnt know arkenfox was gonna disable letterboxing, is that better for privacy?

**Comment by Thorin-Oakenpants** [comment]
I given it to you twice now ... `-JSDateTimeUTC`

keep letterboxing if you want, since you're keeping all the other RFP targets

**Comment by qxlf** [comment]
thanks

**Comment by crssi** [comment]
@Thorin-Oakenpants do you use RFP or FPP?

...and thank you for all your work for us. Love you ❤️

**Comment by Thorin-Oakenpants** [comment]
I will forever use RFP because .. reasons

**Comment by qxlf** [comment]
i think i have both?
definately rfp in the about:config

**Comment by sertonix** [comment]
You can only use ether RFP or FPP. RFP has a higher priority when enabled. So you need these 2 at least:
```js
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.fingerprintingProtection.overrides", "+AllTargets,-JSDateTimeUTC");
```

**Comment by Thorin-Oakenpants** [comment]
> i am still missing something

run the updater so your overrides get added to the user.js

**Comment by qxlf** [comment]
nope, still didnt work. time is still on UTC 0:00 instead of UTC 2:00
i updated my config, i cleaned my prefs, updated my config again and still nothing

**Comment by Thorin-Oakenpants** [comment]
open the user.js and check if your overrides are added to the bottom

**Comment by Thorin-Oakenpants** [comment]
closing since I've added it to the next PR

@qxlf feel free to keep asking about how to get your overrides working - I've tried to step you thru it, and it should work

**Comment by qxlf** [comment]
i could just drop my full overrides in, maybe that would be easier to problem solve it?

**Comment by Thorin-Oakenpants** [comment]
the whole point of having a separate `user-overrides.js` is so that when you update they get appended to the bottom and not lost

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/1857#issuecomment-2180394803
 > ~~`overrides-user.js`~~ 

well, fuck. i just corrected it, but it's `user-overrides.js` - but going by your link that's not the problem

try this
- close FF
- rename `user-overrides.js` to `user-overrides.backup`
- run updater - so you get nothing but a brand new clean arkenfox v126 user.js with no overrides added
- open user.js - make sure there are no overrides
- rename `user-overrides.backup` to `user-overrides.js`
- run updater
- open user.js - has it changed .. AT ALL .. did it add _anything_ from `user-overrides.js`

This is the first step - because it's still not clear if you are actually applying user-overrides.js -> user.js

**Comment by qxlf** [comment]
did all steps, the user.js indeed removes all notes from my overrides and applys them when it needs to.

**Comment by Thorin-Oakenpants** [comment]
OK, I'll have a play later, just for you - because I do not support this config myself personally nor have time for arkenfox to either (because I _am_ arkenfox)

```js
user_pref("browser.search.suggest.enabled.private, false);
```

this line (line 124 in your overrides linked to) has a syntax error - it is missing a closing `"` on the pref name

```js
user_pref("browser.search.suggest.enabled.private", false);
```

so any prefs under that line might not be applied - see https://github.com/arkenfox/user.js/wiki/2.1-User.js#-usage - the link about it syntax errors and parsing being aborted

---

in your linked user-overrides.js I do not see [these lines](https://github.com/arkenfox/user.js/issues/1857#issuecomment-2180683541) - this is required (i.e you need to disable RFP) in order for FPP to kick in and for `privacy.fingerprintingProtection.overrides` to be used



---

some quick observations

```js
// this is deprecated, remove it and reset it in about:config
user_pref("network.cookie.lifetimePolicy", 0);

// these are commented out in arkenfox, no need to set it - remove it
user_pref("network.dns.disableIPv6", false);
user_pref("media.eme.enabled", true);

// these are already set false in arkenfox, no need to duplicate - remove them
user_pref("browser.cache.disk.enable", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.searches", false);

// these are already set true in arkenfox, no need to duplicate - remove them
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.ui.enabled", true);

// this is already set strict in arkenfox (and required for FPP which you want), no need to duplicate - remove it
user_pref("browser.contentblocking.category", "strict");

```

**Comment by Thorin-Oakenpants** [comment]
Can I also check that you're on FF127 ? and not ESR115 - thanks

**Comment by qxlf** [comment]
im on 127, i am using Opensuse Tumbleweed (Linux) so im up to date

**Comment by Thorin-Oakenpants** [comment]
^ https://github.com/arkenfox/user.js/issues/1334#issuecomment-2191364911

I saw it yesterday and thought neat (for testing) but didn't add anything - but given your enthusiasm in sharing, I'll count you as dependable in keeping it up to date :) thanks
