### ISSUE TITLE
Changing timezone to another

### ISSUE THREAD

**Issue by Demon12377** [arkenfox/user.js#1864]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox 127.0 64bit. Windows 10
  - Steps to Reproduce (STR): Change default timezone
  - Expected result: Change to another timezone or local in the system
  - Actual result: ?
  - Console errors and warnings: nope
  - Anything else you deem worth mentioning: How to change the time zone from the static one on GMT+0 to some other one?

---

**Comment by Demon12377** [comment]
I rather created a stupid request, because I use RFP as you do by default, but as I understand it, it cannot be configured separately? This can only be avoided if you disable RFP?

**Comment by Thorin-Oakenpants** [comment]
this was brought up in #1857 (which I hijacked for another purpose)

RFP is all or nothing. If you disable RFP and use FPP then you can use RFPTargets - something like this - https://github.com/arkenfox/user.js/issues/1857#issuecomment-2180394803
