### ISSUE TITLE
extensions.enabledScopes

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1867]
https://github.com/arkenfox/user.js/blob/23caf6961483e0e55544cd4f3594734d0aa35cf0/user.js#L611-L618

Current default for this pref. seems to already be `5`. See "Core Code" on https://searchfox.org/mozilla-central/search?q=extensions.enabledScopes&path=&case=false&regexp=false.

Should we still enforce this value, considering that we don't enforce any value for the `extensions.autoDisableScopes` pref.?

**Comment by rusty-snake** [comment]
> See "Core Code" on https://searchfox.org/mozilla-central/search?q=extensions.enabledScopes&path=&case=false&regexp=false.

Says default is 31 except for gecko-view where it is 5. Does fenix/firefox for android inherit this value? For anything else (including desktop) it looks like the default is still 31.
