### ISSUE TITLE
Question about extensions

### ISSUE THREAD

**Issue by git70** [arkenfox/user.js#1874]
Hi

As recommended on the wiki, I try to keep the number of my extensions to a minimum.
I'm using FF 115 ESR on Linux + Arkenfox of course, but with such overrides:
```
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.ice.no_host", true);
user_pref("privacy.clearsitedata.cache.enabled", true);
user_pref("browser.cache.offline.enable", false);
user_pref("javascript.options.wasm", false);
user_pref("javascript.options.wasm_baselinejit", false);
user_pref("javascript.options.asmjs", false);
user_pref("javascript.options.ion", false);
user_pref("javascript.options.baselinejit", false);
user_pref("javascript.options.jit_trustedprincipals", true);
user_pref("mathml.disabled", true);
user_pref("security.nocertdb", true);
```
(RFP disabled because I really need Dark Mode and correct UTC time)

Currently:

1. I disabled **ClearURLs** (I did not uninstall)
Instead, I added two lists to **uBO**:
- [Legitimate URL Shortener](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt)
- [ClearURLs for uBo](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt)

2. I disabled **Request Control** (I did not uninstall)
- Seems unmaintained (last updated 4 years ago)
- Generally I needed it to redirect `reddit.com` to `old.reddit.com` but now I use **LibRedirect** (and I changed Reddit to Lemmy ;) )
- I've only used standard RC lists, so uBO seems to do the trick (with the two new lists mentioned above)

Questions:

1. Do I generally do the right thing in your opinion?
2. Is there any difference in security between a disabled addon vs an uninstalled addon in Firefox?
3. Do I understand correctly that in the upcoming 128ESR RFP will not be needed and my problems with Dark Mode + UTC time will end?

**Comment by rusty-snake** [comment]
1. There is no (simple) answer to this question. What is your thread model? You seem to have a medium care about privacy/tracking/fingerprinting (no RFP, but uB with extras) and a very high care about security (no WASM, no JIT). If this slight unbalanced thread model is what you have, there is nothing wrong.
2. no
