### ISSUE TITLE
Wiki Question: Is the "xxx fingerprint defender" suite of Addons recommended ?

### ISSUE THREAD

**Issue by boredsquirrel** [arkenfox/user.js#1875]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: doesnt matter
  - Steps to Reproduce (STR): install the extentions
  - Expected result: improve privacy
  - Actual result: not sure about that
  - Console errors and warnings: none
  - Anything else you deem worth mentioning: this is a question about recommended Addons

---

Brave Browser did something interesting by randomizing different identifiers. TP and Arkenfox do the opposite by unifying the fingerprint as much as possible. But there may be identifiers left that Arkenfox cannot change. What these extensions do is report random values.

I am talking about these extensions by "ilGur":
- [Font fingerprint defender](https://addons.mozilla.org/de/firefox/addon/font-fingerprint-defender) ([Homepage](https://mybrowseraddon.com/font-defender.html))
- [WebGL fingerprint defender](https://addons.mozilla.org/de/firefox/addon/webgl-fingerprint-defender/) ([Homepage](https://mybrowseraddon.com/webgl-defender.html))

Interesting to note that the Addon "[Audiocontext fingerprint defender](https://addons.mozilla.org/en-US/firefox/addon/audioctx-fingerprint-defender/)" was removed from the store.

Interesting also: they seem to not be open source? But using the Addon "Extension Source Viewer" you can download the source anyways.
- [webgl-fingerprint-defender.zip](https://github.com/user-attachments/files/16381352/webgl-fingerprint-defender.zip)
- [font-fingerprint-defender.zip](https://github.com/user-attachments/files/16381355/font-fingerprint-defender.zip)
 
These Extensions could be harmful or unnecessary. I know Arkenfox disables WebGL by default, but I have an override to enable it again, and use NoScript to disable it by default. This allows to allow some sites to use it, for compatibility.

In this case the extension could be useful, could also not.

**Comment by rusty-snake** [comment]
Answered in the wiki: https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-dont-bother

**Comment by rusty-snake** [comment]
> use NoScript to disable it by default

Does NS disable WebGL reliable today?
