### ISSUE TITLE
linux: Is it possible to force Firefox use StandardFonts

### ISSUE THREAD

**Issue by powerman** [arkenfox/user.js#1877]
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: firefox-128.0.3, Gentoo Linux
  - Steps to Reproduce (STR): Check fonts section on https://coveryourtracks.eff.org results page
  - Expected result: One in x browsers have this value: 71.05
  - Actual result: One in x browsers have this value: 19945.0
  - Console errors and warnings: N/A
  - Anything else you deem worth mentioning: I've copied all fonts from Ubuntu 22.04 to my Gentoo and see them in `fc-list` output. And I've tried to set `layout.css.font-visibility` to 1 and 2 - it has some minor effect, but no more.

---

The question is: how to force Firefox to use only fonts from https://searchfox.org/mozilla-central/source/gfx/thebes/StandardFonts-linux.inc when I've much more fonts than Ubuntu 22.04 ones?

**Comment by Thorin-Oakenpants** [comment]
first of all - don't use entropy figures from web sites, they are all BS (tainted data sets, small data sets, limited tests, even faulty tests .. etc)

**Comment by Thorin-Oakenpants** [comment]
So we have
- `kBaseFonts` + `kLangFonts` for Ubuntu_22_04
- `kBaseFonts` + `kLangFonts` for Ubuntu_20_04
- `kBaseFonts` for Fedora_39
- `kBaseFonts` for Fedora_38

So in Linux, FF determines if your OS meets one of those releases and therefore RFP/FPP font protections are gated. IDK what Gentoo (unknown version) identifies as for this purpose

`layout.css.font-visibility` - see [this](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#9022-9026)
> Visibility level of font families available to CSS font-matching:
> 1 - only base system fonts
> 2 - also fonts from optional language packs
> 3 - also user-installed fonts
> name: layout.css.font-visibility

AFAICT is only used when you have no font protection. Earlier names for this pref (and others since deprecated) only ever applied to RFP. And FPP use RFPTargets, IIUIC. for example
- with this value at `3` on windows with RFP I am still limited to base fonts
- with this value at `3` on windows with FPP I am still limited to base + language pack fonts

So my understanding is that Gentoo cannot use font protection in RFP or FPP. RFP is `privacy.resistFingerprinting` and if enabled overrides all other font protections. FPP is `fingerprint protection` and is enabled if in private browsing windows or if ETP is stet to Strict.

So short answer, no Gentoo is not supported

@tomrittervg FYI if you want to correct anything .. also, how silly would it be for a pref to force using a particular gate?

---

If you linux supports font protection, then there are ways to force using base, base + lang, or all fonts - via RFPTargets, as part of FPP

**Comment by sertonix** [comment]
Is it possible to do font protection with `font.system.whitelist` (and a fonts.config)?

Ref https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.1.0esr-14.0-1/browser/app/profile/001-base-profile.js#L832

**Comment by powerman** [comment]
> Ref https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.1.0esr-14.0-1/browser/app/profile/001-base-profile.js#L832

I've tried to just blindly apply this TorBrowser's setup (just replaced `pref()` with `user_pref()`) - no effect.

**Comment by Thorin-Oakenpants** [comment]
whitelist is designed for TB. If it is not blank, then it overrides RFP. I do not know if it interferes with FPP. It is also supposed to auto include any bundled fonts, which are kept in the `\Browser\fonts` directory, however, TB also makes sure to properly list the exact fonts they bundle on Linux (in TB all fonts are bundled including those used for the UI - on Mac/Windows they also include some expected system fonts). TB also modifies the font prefs for font fallback orders per language. And they include a font.cfg file.

It's entirely up to you, but I wouldn't be messing with TB settings. For FF, using the whitelist, bundled fonts dir and on linux font.cfg is certainly one way to control the "system" fonts available to web content - just be aware of all the pitfalls.

**Comment by powerman** [comment]
> For FF, using the whitelist, bundled fonts dir and on linux font.cfg is certainly one way to control the "system" fonts available to web content

Hmm. What does all this means in terms of user-override.js commands? (I suppose by `font.cfg` you actually mean `/etc/fonts.conf` and the rest of the fontconfig setup - this one is already configured to provide all Ubuntu 22.04 fonts on my system.)

**Comment by tomrittervg** [comment]
> @tomrittervg FYI if you want to correct anything 

No, that's all right.

> also, how silly would it be for a pref to force using a particular gate?

You mean like a pref that says "I don't care if you don't think I'm Fedora 23, pretend I'm Fedora 23"?  That doesn't seem very effective to me - one of the things about font allowlists is that if (a) you don't have the exact allowlist and (b) the fingerprinter checks the fonts you don't have - you're going to look very unique.  So such a pref seems more likely to make people unique than anything else...

If a user wants to muck with prefs to I'd say just use the whitelist pref.  `fonts.system.whitelist` overrides RFP so it ought to override FPP too.

**Comment by powerman** [comment]
So, it is possible (and how) to set `fonts.system.whitelist` to force it use Ubuntu 22.04 fonts only on non-Ubuntu system?

**Comment by powerman** [comment]
> "I don't care if you don't think I'm Fedora 23, pretend I'm Fedora 23"

TBH I was surprised to see "Windows NT 10.0" in my current UserAgent. Not sure which user.js settings do this, but having any linux fonts with such a UserAgent… Why it's not Linux, btw?

**Comment by Thorin-Oakenpants** [comment]
`Windows NT 10.0` in the https header (windows, linux, mac) is a RFP thing which should be dropped. Basically it stems from Tor Browser old timey decisions about leaving OS info in logs. It's already patched out in Mullvad Browser and we plan to do the same in TB (and upstream if possible) - not to be confused with the fact that we still protect information in the userAgent - the idea is to drop returning two OSes and revert back to 4 OSes

**Comment by Thorin-Oakenpants** [comment]
> So, it is possible (and how) to set `fonts.system.whitelist` to force it use Ubuntu 22.04 fonts only on non-Ubuntu system?

So yes you can do it, but it is really out of scope of this project - and you need to alter your font prefs for default font order/fallbacks per script (e.g. western, cyrillic...). I removed the whitelist pref from the user.js for this reason.

If you want fingerprint protection, FPP (and RFP) already randomize canvas in Firefox and this _should_ be enough to thwart a lot of scripts (that said, detecting altered canvas from known is trivial).

**Comment by rusty-snake** [comment]
Alternative suggestion to use a Ubuntu chroot/container to run your Firefox.
