### ISSUE TITLE
Firefox HTTP -> HTTPS change in version 129

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1879]
https://www.mozilla.org/en-US/firefox/129.0/releasenotes/

> HTTPS is replacing HTTP as the default protocol in the address bar on non-local sites. If a site is not available via HTTPS, Firefox will fall back to HTTP.

I'm making this issue just as a heads-up (like a FYI) to see if we will need to change or add new prefs on the following section:

https://github.com/arkenfox/user.js/blob/11582f905a21971eb5869b48ef8c3f2d4eac4d89/user.js#L469-L484

**Comment by Thorin-Oakenpants** [comment]
no, we do not need to do anything
