### ISSUE TITLE
confused...

### ISSUE THREAD

**Issue by nsoci** [arkenfox/user.js#1880]
...about updated user.js. Today I run updater and there were no update but on the github is updated 2 days ago. Is something wrong with updater or is just mistake on github? Thank you.

**Comment by sertonix** [comment]
The `updater.sh` checks if the `version: 126` in the `user.js` has changed but it hasn't been. There were not meaningful changes in that file so you can ignore that.

**Comment by rusty-snake** [comment]
> but on the github is updated 2 days ago.

![](https://github.com/user-attachments/assets/49f51c71-1891-42d7-bc24-5c90a2e16c57)

**Comment by Thorin-Oakenpants** [comment]
> but on the github is updated 2 days ago

the repo update date also includes PRs, commits to any file - the updater is only checking the live master user.js

**Comment by Thorin-Oakenpants** [comment]
sysntax :)
