### ISSUE TITLE
[Question] Implications of disabling `network.dns.native_https_query`

### ISSUE THREAD

**Issue by xfzv** [arkenfox/user.js#1881]
Since Firefox 129.0, `network.dns.native_https_query` is set to true:

- [Source 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1906239)
- [Source 2](https://hg.mozilla.org/mozilla-central/rev/c48809d5af6a)

From [129.0 releases notes](https://www.mozilla.org/en-US/firefox/129.0/releasenotes/):

> HTTPS DNS records can now be resolved with the operating system's DNS resolver on specific platforms (Windows 11, Linux, Android 10+). Previously this required [DNS over HTTPS](https://support.mozilla.org/kb/firefox-dns-over-https) to be enabled. This capability allows the use of HTTP/3 without needing to use the [Alt-Svc](https://developer.mozilla.org/docs/Web/HTTP/Headers/Alt-Svc) header, upgrades requests to HTTPS when the DNS record is present, and enables wider use of [ECH](https://support.mozilla.org/kb/faq-encrypted-client-hello).

Having `network.dns.native_https_query` set to `true` causes DNS leaks on my system (Linux) after resuming from suspend. Turning `network.dns.native_https_query` to false solves the problem.

Is there any downside if I keep this disabled? It was disabled until now so I guess it's safe but who knows.

Thanks!

**Comment by Thorin-Oakenpants** [comment]
> causes DNS leaks on my system (Linux) after resuming from suspend

have you logged an issue with bugzilla?
