### ISSUE TITLE
[Question] cross-site cookies (third party cookies) exceptions

### ISSUE THREAD

**Issue by tomervazana** [arkenfox/user.js#1884]
I've noticed that I get notifications from Firefox about some websites are using cross, these sites are usually not in my "Manage Exceptions" list for cookies. ("Settings>Privacy & Security>Cookies and Site Data>Manage Exceptions", attachment 2)
### 1. How can I make sure that these sites are blocked from collecting cross-site cookies in every scenario? 
There are 3 possible scenarios:

   a. Not allowed site collecting cross-site cookies from another not allowed site (see example in "Attachment 1").
   b. Not allowed site collecting cross-site cookies from allowed site.
   c. Allowed site collecting cross-site cookies from not allowed site. (I always use my allowed sites in a container)

Attachment 1: Example, YouTube collecting from GitHub:
![Screenshot 2024-08-19 191845](https://github.com/user-attachments/assets/94597f5f-1adc-4d30-a265-55ecff928069)

Attachment 2: As you can see in my "Manage Exceptions" list, both are not allowed:
![Screenshot 2024-08-19 191952](https://github.com/user-attachments/assets/81b37512-8d36-4013-88dd-fc666929ba7c)

### 2. How can I cancel my choice if I accidentally clicked "Allow", for example I accidentally clicked on the allow button when I've surfed in YouTube, and allowed Google cross-site cookies while I'm using YouTube. The option is not shown in anymore "permissions for youtube.com" (attachment 3), I also cannot see youtube.com in the "Manage Exceptions" list above (attachment 2) how can I cancel the permission that I accidentally gave and making sure that its blocked?

Attachment 3: I don't see the notification anymore that Google using cross site cookies on youtube.com
![Screenshot 2024-08-19 193820](https://github.com/user-attachments/assets/450e3d24-bec2-48b0-b396-77779a832c85)

Thanks

**Comment by rusty-snake** [comment]
The permission for accessing cross-site cookies is distinct from the permission to use cookies (and keep them with clearOnShutdown and disable ETP isolation).

1. Disable webcompat heuristics for cross-site cookies. Either disable Webcompat (including stuff like shims) https://github.com/arkenfox/user.js/blob/11582f905a21971eb5869b48ef8c3f2d4eac4d89/user.js#L636-L642 or only the cross-site cookue heuristics https://codeberg.org/rusty-snake/firefox-config/src/commit/208de7347d3bad12c4aecac4dc862f133eba310e/assets/user-overrides.js#L7-L12.
2. Maybe the permission for google.com is shown on google.com rather than youtube.com, IDK.

**Comment by tomervazana** [comment]
I've chose to use these overrides
user_pref("privacy.restrict3rdpartystorage.heuristic.recently_visited", false);
user_pref("privacy.restrict3rdpartystorage.heuristic.redirect", false);
user_pref("privacy.restrict3rdpartystorage.heuristic.window_open", false);
user_pref("privacy.restrict3rdpartystorage.heuristic.opened_window_after_interaction", false);

but my device is blocking challenges.cloudflare.com which limit my network traffic,
I tried to add it to cookies exceptions / ETP exceptions / user_pref("privacy.restrict3rdpartystorage.skip_list", "https://challenges.cloudflare.com");
But none of them helped, how can I unblock challenges.cloudflare.com?

**Comment by rusty-snake** [comment]
> how can I unblock challenges.cloudflare.com?

It is not blocked by Arkenfox.

Maybe uBlock origin.

**Comment by tomervazana** [comment]
Ok, I added so I added these overrides:
```
defaultPref("privacy.restrict3rdpartystorage.heuristic.recently_visited", false);
defaultPref("privacy.restrict3rdpartystorage.heuristic.redirect", false);
defaultPref("privacy.restrict3rdpartystorage.heuristic.window_open", false);
defaultPref("privacy.restrict3rdpartystorage.heuristic.opened_window_after_interaction", false);
defaultPref("privacy.restrict3rdpartystorage.heuristic.skip_list", "");
``` 
And added to uBO rules:
```
* challenges.cloudflare.com * noop
* cloudflareinsights.com * noop
* static.cloudflareinsights.com * noop
``` 
I think that problem is solved.
Thank you

**Comment by rusty-snake** [comment]
Nooping cloudflares analytics service shouldn't be necessary for human check.

**Comment by tomervazana** [comment]
> Nooping cloudflares analytics service shouldn't be necessary for human check.

Ok thank, I removed the lines:
```
* cloudflareinsights.com * noop
* static.cloudflareinsights.com * noop
``` 
It should undo the effect right by simply removing the lines and commit the changes? (or should I block it?)
 
BTW: I'm new at Firefox I thank you so much for your help.

**Comment by rusty-snake** [comment]
Just let the staic filter engine do it's job. (=remove from dynamic filter)
