### ISSUE TITLE
[Question] More details on `disable partitioning` when adding sites to exception

### ISSUE THREAD

**Issue by KAGEYAM4** [arkenfox/user.js#1885]
https://github.com/arkenfox/user.js/wiki/3.2-Overrides-%5BCommon%5D#-keep-logins, mentions ->
> ⚠️ Be selective with what cookies you keep, as they also disable partitioning, see [bugzilla 1767271](https://bugzilla.mozilla.org/1767271)

I couldn't find any details about `partitioning`, can please add some points in wiki explaining what it is and its implications.

**Comment by KAGEYAM4** [comment]
> So avoid adding too many exceptions as they will use traditional storage, not protected by partitions, to keep track of you.

Wow, that totally make TCP useless. Are there any way to have exception but with TCP ?

**Comment by rusty-snake** [comment]
> that totally make TCP useless.

Not totally, only for sites with exceptions.

> Are there any way to have exception but with TCP ?

Well, that's what is bugzilla is about. There is no way.
<sub>from one of linked bugzillas, maybe there are tricks with http vs https</sub>

>  Does multi-account container helps here any way?

Partly, it helps if you want to isolate "im logged in as" from other sites.

**Comment by KAGEYAM4** [comment]
One last thing, do you guys use [Cookie Auto Delete](https://addons.mozilla.org/firefox/addon/cookie-autodelete/) ? On the wiki it says this ->
> As of Firefox 86, strict mode is not supported at this time due to missing APIs to handle the Total Cookie Protection

But i can't find this anymore on the site anymore, maybe it got fixed.

My main reason of using `Cookie Auto Delete ` is it offers ease for adding site to exception.

**Comment by KAGEYAM4** [comment]
Isn't it far better to not delete `KEEP LOGINS, cookies`, this way TCP gets utilised and To use some other extensions ( don't know any ) that can delete cookies of sites with exception. Or is it not possilble to do this ?

**Comment by KAGEYAM4** [comment]
@qupig  what are your thoughts on using this method, not using "clear when close" and instead using  https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search to delete cookies. This way we can get both 'cokkie partitioning' while deleting cookies with exception set in the extension.
