### ISSUE TITLE
[Guide] How to get started

### ISSUE THREAD

**Issue by KAGEYAM4** [arkenfox/user.js#1886]
I read the whole wiki but couldn't find how to get started? Specifically `prefsCleaner.sh`, how does this script get updated ? 

`Updater.sh` can handle updating itself & user.js & it merges user-overrides.js. But what about if the `prefsCleaner.sh` gets an update?

**Comment by rusty-snake** [comment]
https://github.com/arkenfox/user.js/blob/11582f905a21971eb5869b48ef8c3f2d4eac4d89/prefsCleaner.sh#L69-L80

**Comment by KAGEYAM4** [comment]
Ok, so prefsCleaner.sh is also self updateable.
