### ISSUE TITLE
Cleanup script not working

### ISSUE THREAD

**Issue by popogomo** [arkenfox/user.js#1891]
The cleanup script provided here: https://raw.githubusercontent.com/arkenfox/user.js/master/scratchpad-scripts/arkenfox-cleanup.js
doesn't work and instructions are not complete either:

1. When opening the Web Console using Ctrl+Shift+K, we then need to type "allow pasting" in the Firefox console as it doesn't allow to paste scripts by default. The manual doesn't mention this. It should be like this:

 - load about:config and press Ctrl+Shift+K to open the Web Console for about:config
    - using about:config is important, so the script has the right permissions
- **type allow pasting in the console window. No need to press enter**
  - paste this script **above allow pasting command**

2. The script itself doesn't work, generating an error as show below:

![image](https://github.com/user-attachments/assets/04812928-c40d-48fd-8fe9-a285386801f2)

**Comment by rusty-snake** [comment]
I guess the script works, but you added some invalid words `allow pasting` at it's top.

Btw, `devtools.selfxss.count = 5` works too.
