### ISSUE TITLE
extensions.autoDisableScopes default value

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1896]
The `user.js` says the default is `15`, but, in my case, on Fedora Linux, the default is `0`. The default is also `0` in Tor Browser (from Tor Browser Launcher downloaded from Fedora official repos).

What is happening?

It's weird because they set it to `15`: https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.2.0esr-14.0-1/browser/app/profile/firefox.js#L59 (edit: they also set it to `0` https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.2.0esr-14.0-1/browser/app/profile/001-base-profile.js#L592)

Also, here are some things from searchfox:
https://searchfox.org/mozilla-central/source/remote/shared/RecommendedPreferences.sys.mjs#237-242
https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#57-61

Currently, this pref. is inactive in the user.js.

I believe there is an issue somewhere. But where?

Edit: some additional context - https://github.com/arkenfox/user.js/issues/960
But I'm still confused, even after reading through all the comments.

**Comment by rusty-snake** [comment]
Heard of downstream patches?

https://src.fedoraproject.org/rpms/firefox/blob/f40/f/firefox-enable-addons.patch

**Comment by rusty-snake** [comment]
- There are reasons why this is set by Fedora. (You will end up with en-US interface because languages package are distributed differently).
- IMHO it's not the job of arkenfox to fixup all the mess all the different Linux distributions do to their firefox builds. (If it is even possible with user.js)
