### ISSUE TITLE
browser.download.enable_spam_prevention = true

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1897]
See https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41764 (https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.2.0esr-14.0-1/browser/app/profile/001-base-profile.js#L69).

I think it would be interesting to enable in Arkenfox too.

**Comment by Thorin-Oakenpants** [comment]
I would question why TB even added it (clearly I was not involved) - [1731668](https://bugzilla.mozilla.org/show_bug.cgi?id=1731668) - @PieroV 

PS: We are not TB.

**Comment by PieroV** [comment]
We enabled it as a result of a security audit: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41764
This feature is partially broken in Firefox.
ma1 wrote a patch to fix it but hasn't uplifted it yet.

**Comment by Thorin-Oakenpants** [comment]
indeed - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42832

**Comment by Thorin-Oakenpants** [comment]
note exactly the meta I was looking for ... i think ... but it will do
- [1306334](https://bugzilla.mozilla.org/show_bug.cgi?id=1306334) [meta] Protection from sites that try to download multiple files automatically

given any outstanding issues (such as the TPO one) and the delay in getting them resolved (priorities) and the threat model, this is not something we need to enable or include - when it's ready it will ride the trains
