### ISSUE TITLE
breakpad.reportURL

### ISSUE THREAD

**Issue by Tiagoquix** [arkenfox/user.js#1900]
Tor Browser sets it to `data:`, while arkenfox sets to `""`.

https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.2.0esr-14.0-1/browser/app/profile/001-base-profile.js#L215-217

Is this difference important somehow?

**Comment by Thorin-Oakenpants** [comment]
no - same effect
