### ISSUE TITLE
https://coles.com.au won't let me login with arkenfox

### ISSUE THREAD

**Issue by CarlosMerc** [arkenfox/user.js#1902]
What works:
Setup a new 128esr firefox profile.
Toggle Strict Enhanced Tracking Protection on. Restart.
Go to https://coles.com.au
Click the "Log in/Sign up" person looking option. It will go to https://auth.colesgroupprofile.com.au for you to put in your (valid account) email and the next screen goes to password and logs in.

What doesn't work..
Using default settings on arkenfox, I go to the email login section, press continue and get "Apologies, something went wrong. We are currently experiencing a network issue. Please refresh and try again."

Options tried to fix: put https://coles.com.au and https://auth.colesgroupprofile.com.au into the Manage Exceptions field for Enhanced Tracking Protection. Restart.
No Go.
Blanked out all the [SETUP-WEB], No Go.
0905 changed to 2
1003 changed to 0
1223 changed to 1
1602 cross-origin was changed to 0 (send full URI)
Read the documentation but not sure which ones to try next.

**Comment by Thorin-Oakenpants** [comment]
> ETP Strict

try adding https://www.coles.com.au/  (note the www part) - add exceptions from the urlbar > blueshield (switch ETP to off) and it adds it to the exceptions and reloads the page

![exceptions](https://github.com/user-attachments/assets/689d4b24-455e-4151-b75f-bfff74b28fa7)

> Blanked out ...

Not sure what you mean by "blank out" - I will assume you mean you commented or removed the lines. Don't modify the user.js - this is not how it works. The user.js only applies active (non-commented-out) lines. You need to add overrides. In testing, you can just change the pref in about:config

> Apologies, something went wrong

What do you get in the console - cntrl-shift-k?

**Comment by CarlosMerc** [comment]
www.coles.com.au was already there, along with coles.com.au and auth.colesgroupprofile.com.au. All show ETP off (greyed out).

I was only experimenting with the user.js file, commenting out and changing values.
I have been using overrides and changing about:config after that.

Upon loading firefox, there are no errors in the console.
Once I try and login to coles and after the error appears, the following is what the console outputs (with a clean default user.js):

Some cookies are misusing the recommended “SameSite“ attribute 33
Cookie “TEST_AMCV_COOKIE_WRITE” has been rejected for invalid domain. launch-43efd722077f.min.js:2:26685
Cookie “TEST_AMCV_COOKIE_WRITE” has been rejected for invalid domain. launch-43efd722077f.min.js:2:26685
Cookie “TEST_AMCV_COOKIE_WRITE” has been rejected for invalid domain. launch-43efd722077f.min.js:2:26685
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. launch-43efd722077f.min.js:6:24766
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. launch-43efd722077f.min.js:6:29805
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. dest5.html
Cookie “_dp” will soon be rejected because it is foreign and does not have the “Partitioned“ attribute. dest5.html:6:220
unreachable code after return statement _Incapsula_Resource:1:47951
unreachable code after return statement _Incapsula_Resource:1:53278
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. () False-What-wise-put-walls-doe-and-Leuilter-know-:1:69351
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. False-What-wise-put-walls-doe-and-Leuilter-know-:1:80330
Cookie “reese84” has been rejected for invalid domain. False-What-wise-put-walls-doe-and-Leuilter-know-:2:88900
Cookie “x-d-token” has been rejected for invalid domain. False-What-wise-put-walls-doe-and-Leuilter-know-:2:89529
Cookie “_ga_C8RCBCKHNM” has been rejected for invalid domain. js:354:271
Cookie “_ga_C8RCBCKHNM” has been rejected for invalid domain. js:354:271
Cookie “_ga” has been rejected for invalid domain. js:354:271
Cookie “s_cc” has been rejected for invalid domain. AppMeasurement.min.js:2:1813
Cookie “s_sq” has been rejected for invalid domain. AppMeasurement.min.js:2:1813
Cookie “s_sq” has been rejected for invalid domain. AppMeasurement.min.js:2:1813

**Comment by CarlosMerc** [comment]
> > Failed to create WebGL context: WebGL creation failed:
> 
> This is caused by `webgl.disabled: true`. You could try setting it to `false` but I am not certain if this will help.

The default value in user.js is currently default (webgl.disabled = false).

**Comment by CarlosMerc** [comment]
Cookie “s_sq” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite AppMeasurement.min.js:2:1813
Cookie “s_sq” has been rejected for invalid domain. AppMeasurement.min.js:2:1813

Another go on the same site. Looks like a samesite cookie issue?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value

**Comment by Thorin-Oakenpants** [comment]
Soooo .. let's clarify something. In a brand new Firefox profile
- can you login?
- then clear all the site cookies and data, close, reopen and change ETP to Strict
- can you still login?

**Comment by CarlosMerc** [comment]
You can close the issue.
Removed firefox (via revo uninstaller). Delete all traces. Reinstall.
user.js added. Now works. Don't know what it was.
Thanks for the help.

**Comment by Thorin-Oakenpants** [comment]
okie dokie - going to mark as invalid for archiving purposes (i.e not saying your issue was invalid)
