### ISSUE TITLE
Consider including stricter user-overrides.js with release

### ISSUE THREAD

**Issue by calhix** [arkenfox/user.js#1903]
With the default changing to FPP, it may be preferable to include an overrides file with the strictest prefs for those that don't mind the breakage that comes with RFP but perhaps not monitoring current issues. I saw your overrides listed in a comment in #1804 which I am using and do prefer but not sure if everyone saw. Firefox with the strictest settings is as good as we can get for those on aarch64 IMO since TB or MB do not have aarch64 releases so it's nice to easily get as close as possible since there's no other option. I think the best would be to have two different user.js files in each release (one of them stricter) but that would mean changes to updater.sh to ensure proper tracking of which is which.

**Comment by Thorin-Oakenpants** [comment]
i'm not interested in providing an overrides file - the entire user.js is a template and users should already be looking adding overrides (even I have some) .. so declined, sorry, not sorry :)

**Comment by Thorin-Oakenpants** [comment]
>  since TB or MB do not have aarch64 releases

ikr! lets blame @morganava ... also I think @PieroV would love doing more builds, also one for gecko on iOS for the EU :D
