### ISSUE TITLE
platform architecture fingerprint test time: using the console

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1910]
Any platform, any chip, any recent/current gecko build, bare metal or VM

STR
- open the console (I use about:config because it allows precision timing)
- past in the this script and hit enter
- ```js
   function get_arch() {
	let t0 = performance.now()
	let result
	try {
		const f = new Float32Array(1)
		const u8 = new Uint8Array(f.buffer)
		f[0] = Infinity
		f[0] = f[0] - f[0]
		result = u8[3]
	} catch(e) {
		result = e+''
	}
	let t1 = performance.now()
	console.log(result, t1-t0)
   }
   get_arch()
   ```

Tell us the results and hardware/software details. **_If a VM, also tell us the bare metal details_**

TIA

**Comment by Thorin-Oakenpants** [comment]
...

**Comment by rusty-snake** [comment]
`255 0` Fedora, x86_64, FF and TB

**Comment by nsoci** [comment]
255 0.0175630000885576 debugger eval code:14:11
FF 132.0 (amd64) FreeBSD 14.1

**Comment by 2glops** [comment]
Linux testing - Trixie

FF 132
255 0.08538900001440197

Firefox nightly
255 0.07908599999791477

Mullvad browser 12.5.9
255 0

**Comment by sertonix** [comment]
- `255 0.09062900000026275` FF ESR 128.4.0, x86_64, alpine linux
- `255 0.11189700000068115` FF 132.0 (not a clean profile), x86_64, alpine linux
- `255 0.0803989999985788` FF DEV 132.0b9, x86_64, alpine linux
- `127 0` TB 14.0, aarch64, android 8.1.0

**Comment by Thorin-Oakenpants** [comment]
sweeet .. I think you can see where this is going :)

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1928095
