### ISSUE TITLE
Which options to set if I want to continue using RFP?

### ISSUE THREAD

**Issue by cococosr** [arkenfox/user.js#1919]
Hi, I have been using Arkenfox for a few years now, but I'm not sure, which preferences I need to set to continue with RFP. Firefox ist en-US, macOS is set to english user interface with german locale / time zone. I set both RFP and Letterboxing to true, disabled WebGL and set privacy.spoof_english to 2. Is that correct? Thanks!

**Comment by Thorin-Oakenpants** [comment]
yup - that's what I use

https://github.com/arkenfox/user.js/blob/eae5762d29f18115fbffd73d89bd9e2510b25427/user.js#L756-L758

part of my overrides
```js
// RFP
user_pref("privacy.resistFingerprinting", true);
user_pref("privacy.resistFingerprinting.letterboxing", true);
user_pref("webgl.disabled", true);
user_pref("privacy.spoof_english", 2);
```

**Comment by Thorin-Oakenpants** [comment]
> I've noticed that Mullvad by default opens with a 1400x700 window but firefox + arkenfox + your overrides opens at 1400x800 on my machine

we both actually have the same `max height` of 900, so I suspect on mullvad you have the toolbar showing on new windows, but not on arkenfox. Other than that, there is a plethora of changes to upstream to Firefox from Tor Project, about 2+ years worth, that may account for this. @PieroV is going to try and upstream them as a priority this next cycle (14.5 tor project cycle), so at least we'll be on par with mozilla and can tackle other 'screensize' issues with moz devs

> I ask this because Mullvad browser isn't yet available on aarch64

@PieroV can answer this better than me, but I believe this is not far off ?

> Also, would you consider adding recommended overrides to each new release for those that want to continue with RFP in the future

you can't pretend to be MB, for starters the fonts are radically different. So there is no such thing as "Mullvad-like setup"

RFP is an all-in or nothing, and the settings to flip to enable RFP are already listed

https://github.com/arkenfox/user.js/blob/eae5762d29f18115fbffd73d89bd9e2510b25427/user.js#L756-L760

**Comment by PieroV** [comment]
> > I've noticed that Mullvad by default opens with a 1400x700 window but firefox + arkenfox + your overrides opens at 1400x800 on my machine
> 
> we both actually have the same `max height` of 900, so I suspect on mullvad you have the toolbar showing on new windows, but not on arkenfox. Other than that, there is a plethora of changes to upstream to Firefox from Tor Project, about 2+ years worth, that may account for this. @PieroV is going to try and upstream them as a priority this next cycle (14.5 tor project cycle), so at least we'll be on par with mozilla and can tackle other 'screensize' issues with moz devs
> 

My ideas are:
- fonts (MB has a couple of patches to customize the system font to Arimo and maybe the default height)
- bookmark bar

But if your machine is aarch64, how did you test MB there?

> > I ask this because Mullvad browser isn't yet available on aarch64
> 
> @PieroV can answer this better than me, but I believe this is not far off ?
> 

The main problem is that we don't have test/dev hardware at the moment.
Maybe we could use Raspbery Pi for testing, but debugging would need us to be able to build there.
We recently added [aarch64 nightly builds](https://nightlies.tbb.torproject.org/nightly-builds/tor-browser-builds/tbb-nightly.2024.12.12/mullvadbrowser-nightly-linux-aarch64/) thanks to the help of a community member, but we aren't able to run them (I still haven't tried to spin up my old RPi3).
Without hardware, we can't publish, or we'd publish something not tested, which is not good, and not right for users.

> > Also, would you consider adding recommended overrides to each new release for those that want to continue with RFP in the future
> 
> you can't pretend to be MB, for starters the fonts are radically different. So there is no such thing as "Mullvad-like setup"
> 

Yeah, there are also patches, files, etc.
You'll still be different.

**Comment by calhix** [comment]
Thank you both for the information, I'd happily donate the amount for a Pinebook Pro if that means future stable releases! Would that work for you?

**Comment by Thorin-Oakenpants** [comment]
IDK much about builds (or hardware - I do know lots about taking arrows to the knee), and I am not employed by TPO - but undertaking a commitment to provide and test for specific platforms/architecture would be more than some hardware (although the gesture is awesome). The first consideration is cost in terms of resources (people and time - hardware would be lower end I think) - it's currently all voluntary and that can't continue if it is to be _officially_ supported

**Comment by Thorin-Oakenpants** [comment]
@calhix  `https://github.com/mullvad/mullvad-browser/issues/11#issuecomment-2552069750`
