### ISSUE TITLE
Why and how to disable machine learning

### ISSUE THREAD

**Issue by 321MBT** [arkenfox/user.js#1920]
### ML in FF?

**Without a good reason to use ML, it seems wise to disable it to save resources or increase speed and responsiveness.**

1. Why would someone want to use ML with FF+Arkenfox?
2. Can anyone provide context for these new machine-learning settings? If not, I appended this post with a ChatGPT 1o response.
     - browser.ml.checkForMemory
     - browser.ml.defaultModelMemoryUsage
     - browser.ml.maximumMemoryPressure
     - browser.ml.minimumPhysicalMemory

### Disable ML

Are these settings sufficient to disable ML?
```
user_pref("pdfjs.enableML", false);
user_pref("browser.ml.enable", false);
user_pref("browser.urlbar.quicksuggest.mlEnabled", false);
user_pref("browser.ml.chat.sidebar", false);
user_pref("browser.ml.chat.enabled", false);
user_pref("browser.urlbar.yelp.mlEnabled", false);
user_pref("browser.ml.chat.hideLocalhost", true);
user_pref("browser.ml.chat.shortcuts", false);
user_pref("browser.ml.chat.shortcuts.custom", false);
user_pref("browser.ml.checkForMemory", true);
user_pref("browser.ml.defaultModelMemoryUsage", 0);
user_pref("browser.ml.maximumMemoryPressure", 0);
user_pref("browser.ml.minimumPhysicalMemory", 0);
user_pref("browser.ml.queueWaitInterval", -1);
user_pref("browser.ml.queueWaitTimeout", 0);
```

### Explanation of new memory ML settings (ChatGPT 1o):

> The preferences you’ve listed appear to relate to how Firefox manages memory for certain machine learning (ML) features or models it may use internally. Although Mozilla’s official documentation is limited or may not explicitly detail these particular settings, we can infer their roles based on naming conventions and known Firefox practices.
> 
> The preferences you’ve listed appear to relate to how Firefox manages memory for certain machine learning (ML) features or models it may use internally. Although Mozilla’s official documentation is limited or may not explicitly detail these particular settings, we can infer their roles based on naming conventions and known Firefox practices.
> 
> **1. browser.ml.checkForMemory**
>
> **What it controls:**
> This setting likely determines whether Firefox actively checks the system’s memory conditions before enabling or running ML-related features or models.
>
> **Effect:**
> 
> - If enabled (true), Firefox might assess available RAM and memory pressure before running ML tasks.
> - If disabled (false), Firefox may skip these checks, potentially running ML tasks even if the system is low on memory.
> 
> **2. browser.ml.defaultModelMemoryUsage**
>
> **What it controls:**
> This preference probably specifies a default expected or allocated memory footprint for the machine learning model(s). It could represent a target memory usage level or an approximate memory budget for the ML component.
>
> **Effect:**
> 
> - Setting a higher value might allow ML models to be more complex or run faster, but at the cost of using more system memory.
> - A lower value might restrict the ML model’s complexity or performance but reduce its memory impact.
> 
> **3. browser.ml.maximumMemoryPressure**
>
> **What it controls:**
> “Memory pressure” is a measure of how strained your system’s memory is. This setting may define a threshold above which Firefox’s ML components either stop running, scale down, or avoid starting.
>
> **Effect:**
> 
> - A lower threshold means that even a moderate increase in memory usage would cause Firefox to disable or reduce ML features.
> - A higher threshold allows ML tasks to continue running until the system memory is quite heavily used, potentially improving ML functionality but risking reduced overall performance under memory stress.
> 
> **4. browser.ml.minimumPhysicalMemory**
>
> **What it controls:**
> This likely sets a minimum amount of physical RAM that must be present on the system for ML tasks to run. If the system falls below this threshold, Firefox may opt not to start the ML features at all.
>
> **Effect:**
> 
> - On machines with plenty of RAM, ML features will likely run as intended.
> - On lower-end systems, ML components may be disabled to maintain performance and stability.
> 
> **In Summary:**
> 
> - browser.ml.checkForMemory: Toggles whether Firefox checks memory conditions before running ML tasks.
> - browser.ml.defaultModelMemoryUsage: Sets a default memory budget for ML models.
> - browser.ml.maximumMemoryPressure: Establishes a memory pressure threshold to halt or reduce ML operations.
> - browser.ml.minimumPhysicalMemory: Sets a minimum RAM requirement for running ML features.
> 
> These settings as a whole give Firefox a way to intelligently adapt ML feature usage based on the machine’s available resources, helping maintain performance and stability.

**Comment by rusty-snake** [comment]
> ```js
> user_pref("pdfjs.enableML", false);
> user_pref("browser.ml.enable", false);
> user_pref("browser.ml.chat.enabled", false);
> ```

Answered for me.

> Can anyone provide context for these new machine-learning settings? If not, I appended this post with a ChatGPT 1o response.

https://searchfox.org/mozilla-central/rev/e3d80c5d94cbfa5dc579d5536cccea2b69b60635/modules/libpref/init/all.js#3767-3794

and don't mess with them, there's no need.

> Without a good reason to use ML, it seems wise to disable it to save resources or increase speed and responsiveness.

Do you have any prove that it costs resources or causes slowdowns when not used?

**Comment by 321MBT** [comment]
> > ```js
> > user_pref("pdfjs.enableML", false);
> > user_pref("browser.ml.enable", false);
> > user_pref("browser.ml.chat.enabled", false);
> > ```
> 
> Answered for me.

Thanks, but are you sure those three settings disable all ML? I ask because it seems odd for FF to offer two different switches to turn off the same thing (ML) via browser.ml.enable and browser.ml.chat.enabled. (Yes, I realize chat may be a different 'thing', but it's under browser.ml.) Logic seems to dictate if I set browser.ml.enable to false all other browser.ml.XXX settings should be off, too.

Because I don't know what triggers an ML event, nor what turns off all ML, and the effects of toggling those settings are opaque to me, I took the shotgun approach by disabling those browser.ml.XXX settings and forcing ML not to run by changing the ML memory settings. So far, I have seen no issues with disabling ML through memory setting changes, but I also am not measuring anything, so it's pretty subjective.

> > Can anyone provide context for these new machine-learning settings? If not, I appended this post with a ChatGPT 1o response.
> 
> https://searchfox.org/mozilla-central/rev/e3d80c5d94cbfa5dc579d5536cccea2b69b60635/modules/libpref/init/all.js#3767-3794
> 
> and don't mess with them, there's no need.
>

Thanks for the link. I already checked serachfox, and those code comments don't provide context to the effects of changing the settings. That is what I was asking about. Too often, FF settings are opaque in operation, with a dearth of usage context.

> > Without a good reason to use ML, it seems wise to disable it to save resources or increase speed and responsiveness.
> 
> Do you have any prove that it costs resources or causes slowdowns when not used?

I may misunderstand what you're asking, or I may have misworded my question. My reason for turning off ML isn't lost resources/speed when ML is _off_but when ML is _activated_. 

So the question to me should be, "Do you have proof that ML costs resources or causes slowdowns when activated (in use)?"

**Comment by 321MBT** [comment]
@Thorin-Oakenpants 

Please remove the invalid tag and reopen this thread. Or explain why you think this discussion is invalid. @rusty-snake, and I have a friendly and useful discussion that will benefit at least some Arkenfox users.

**Comment by Thorin-Oakenpants** [comment]
It's invalid because it has nothing to do with privacy - instead your perceived performance and resources "issue" is out of scope for arkenfox. This is not a free-for-all-discuss=anything-mozilla repo and if I get too much noise, I will simply lock issues and ban perps if need be. It's invalid, move on. Not saying you are a nazi, it's just a phrase, but I do not wish to become the nazi-bar (google it) - so I will be rude, blunt, close shit, label things, and ban people as I see fit

**Comment by 321MBT** [comment]
> It's invalid because it has nothing to do with privacy - instead your perceived performance and resources "issue" is out of scope for arkenfox. This is not a free-for-all-discuss=anything-mozilla repo and if I get too much noise, I will simply lock issues and ban perps if need be. It's invalid, move on. Not saying you are a nazi, it's just a phrase, but I do not wish to become the nazi-bar (google it) - so I will be rude, blunt, close shit, label things, and ban people as I see fit

Oh, I get it. You love privacy becuase you're a scared little bitch who loves being a key board warrior. Fucking laughable. I came in very nice and just asked why. You can in like a fucking bitch who can't handle anyone asking you "why." Please go right ahead and fuck off, you little bitch. Unless you'd like to meet?

Please ban me, then I will just create an army of alts to fuck your shit up and give you lots of headaches. Fucking piece of shit.
