### ISSUE TITLE
[Wiki] replace Temporary Containers (TC) with Open in Temp Container (OiTP)

### ISSUE THREAD

**Issue by privacy-advo** [arkenfox/user.js#1924]
> https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-optional

As Temporary Containers (TC) is not maintained and saw its last update four years ago, it would be good to list an alternative. Open in Temp Container's (OiTP) feature set is great. The maintainer is very active, issues get fixed within days.

https://addons.mozilla.org/en-US/firefox/addon/open-in-temp-container/
https://github.com/igorlogius/open-in-temp-container

**Comment by privacy-advo** [comment]
Sure thing. But I must add that it has existed since April 2023.

**Comment by Thorin-Oakenpants** [comment]
oh, I looked at https://addons.mozilla.org/en-US/firefox/addon/open-in-temp-container/versions/ and it only listed the one from Nov 22 2024
