### ISSUE TITLE
Change the Default Branch from master to main

### ISSUE THREAD

**Issue by Commrade1312** [arkenfox/user.js#1925]
The term "master" in the context of version control systems has been criticized for its association with slavery and the historical connotations it carries. Many in the tech community believe that using more neutral language, such as "main," is a step towards creating a more inclusive environment. As a result, many organizations and projects have opted to change the default branch name from `master` to `main` to reflect this commitment to inclusivity and sensitivity.

By changing the default branch name from `master` to `main`, developers and organizations can contribute to a culture that values respect and equality, moving away from terminology that may evoke painful historical associations. This change is part of a broader effort to make technology more accessible and welcoming to everyone, regardless of their background. It reflects a commitment to fostering an inclusive community where all individuals feel valued and respected.

*To sum up this summary*:  **No Masters! No $laves!**

## Steps to Change the Default Branch

To change the default branch name from `master` to `main` in a Git repository, follow these steps:

### Step 1: Rename the Local Branch

1. Open your terminal or command prompt.
2. Navigate to your Git repository.
3. Rename the `master` branch to `main` using the following command:

   ```bash
   git branch -m master main

### Step 2: Push the New Branch to Remote

   ```bash
   git push -u origin main
   ```

### Step 3: Update the Default Branch on Remote

1. Go to your repository on GitHub (or your Git hosting service).
2. Navigate to the repository settings.
3. Find the "Branches" section.
4. Change the default branch from master to main.

### Step 4: Delete the Old master Branch (Optional)

   ```bash
   git push origin --delete master
   ```

**Comment by 9ao9ai9ar** [comment]
Except that there is an "i" and a "man" in "main", and the word itself is derived from

> Old English mægen (Mercian megen) "power, bodily strength; force, violent effort; strength of mind or will; efficacy; supernatural power," ―[Online Etymology Dictionary](https://www.etymonline.com/word/main)

I also don't want to be thinking that I'm pushing my commits to a

> large pipe that carries waste water and sewage (= human waste, etc.) away from a building ―[Oxford Learner's Dictionaries](https://www.oxfordlearnersdictionaries.com/definition/english/main_2)

Now I'm going back to sleep on my king sized bed in my master bedroom.
