### ISSUE TITLE
sticky: unofficial: extension breakage due to prefs

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#391]
The information in here is user submitted and not verified by this repo (unless stated). I will also not maintain or update or clean up this thread. ***Have at it, it's ALL yours*** - just look at the readme first.

### :large_orange_diamond: read me

I am not against information being shared if it helps end users, but I am not interested in maintaining any lists of extension issues to do with prefs or adding info to the user.js (except those extensions we recommend)

* This user.js does not have a monopoly on pref changes. Extension breakage information ***belongs*** with the developer/support site.
   * Sometimes they can code fixes / fallbacks / workarounds
   * Sometimes they can detect the issue and alert the user
   * At the very least they can add something to the help section
* It just isn't feasible (time constraints, sheer numbers, constant code changes)
* The user.js is already lengthy & bulky

Do not ask for troubleshooting in here (open a new issue if you really need help). Keep this thread clean and tidy, we only need confirmation that pref(s) `X` caused  extension(s) `Y` to break in `Z` manner. Link back to any developer discussions if need be.

### :large_orange_diamond: Use this format if you can

```
**pref(s)**: `prefname`
**extension(s)**: 
**breakage**: 
**site/support issue**: 
**comments**: 
```

**Comment by Thorin-Oakenpants** [comment]
**pref(s)**: `dom.w3c_pointer_events.enabled`-`false`
**extension(s)**: [Gesturefy](https://addons.mozilla.org/en-US/firefox/search/?q=gesturefy) in FF59+
**breakage**: see support issue linked below
**site/support issue**: https://github.com/Robbendebiene/Gesturefy/issues/271
**comments**: RFP may take care of this one day: see [1363508](https://bugzilla.mozilla.org/show_bug.cgi?id=1363508)

**Comment by Thorin-Oakenpants** [comment]
**pref(s)**: `dom.allow_cut_copy`=`false`
**extension(s)**: [Copy on Select](https://addons.mozilla.org/en-US/firefox/addon/copy-on-select/) and other auto-copying extensions
**breakage**: doh!
**site/support issue**: N/A

**Comment by crssi** [comment]
**pref(s)**: `media.autoplay.enabled = false`
**breakage**: sometimes doesn't work, sometimes work in a reverse order
**comments**: one of the future version of FF will sort this out, so I have read on one FF roadmap the @Thorin-Oakenpants  pointed to recently

**Comment by crssi** [comment]
**pref(s)**: `security.tls.version.min <> 1`
**breakage**: some web pages can rearly still be found that do not support higher than 1
**comments**: just for info, it is not recommended to use lower value than 3, see 1202

**Comment by crssi** [comment]
**pref(s)**: `security.OCSP.require = true`
**breakage**: in some rearly cases, like in developing, this can cause the page not to load
**comments**: it is not recomended to set it to false, see 1212

**Comment by crssi** [comment]
**pref(s)**: `security.mixed_content.block_display_content = true`
**breakage**:  in some rearly cases, this can cause breakage or some elements on the page not to load
**comments**: it is not recomended to set it to false, see 1241

**Comment by crssi** [comment]
**pref(s)**: `dom.event.contextmenu.enabled = false`
**breakage**: annoyance really and not breakage, custom context menu defined by web page is not shown
**comments**: see 2401

**Comment by crssi** [comment]
**pref(s)**: `full-screen-api.enabled = false`
**breakage**: full screen video playback is not supported/does not work
**comments**: see 2206

**Comment by crssi** [comment]
**pref(s)**: `svg.disabled = true`
**breakage**: youtube and similar player controls breakage
**comments**: see 2671

**Comment by crssi** [comment]
**pref(s)**: `dom.indexedDB.enabled = false`
**extension(s)**: uBlock Origin [1.14.0+] and other extensions that require IndexedDB
**breakage**: also some web sites require it enabled to work as intended
**comments**: see 2720

**Comment by crssi** [comment]
**pref(s)**: `privacy.firstparty.isolate = true`
**extension(s)**: Cookie AutoDelete and simmilar
**breakage**: some extensions and some login pages
**comments**: see 4001

**Comment by Thorin-Oakenpants** [comment]
Oh dear .. how can I put this delicately - this is about EXTENSIONS breaking - not about how prefs break websites. It is also not about items already covered in the user.js such as extensions we recommend. Please remove ALL of it

- `media.autoplay.enabled`
- `security.tls.version.min` - ALREADY states the problem/workaround
- `security.OCSP.require`
- `security.mixed_content.block_display_content`
- `dom.event.contextmenu.enabled` - INACTIVE in the user.js and ALREADY states the problem/workaround
- `full-screen-api.enabled` - ALREADY states the problem in the user.js
- `svg.disabled` - INACTIVE in the user.js and ALREADY states the problem
- `dom.indexedDB.enabled` - INACTIVE in the user.js and ALREADY states the problem
- `privacy.firstparty.isolate` - ALREADY states the problem in the user.js

There is no need to regurgitate all of this :mrgrumpypants-face:

**Comment by Thorin-Oakenpants** [comment]
**pref(s)**: `privacy.resistFingerprinting`=`true`
**extension(s)**: anything that uses canvas or depends on local time
**breakage**: extensions use UTC 0, canvas is blocked
**site/support issue**: N/A
**comments**: known and will be dealt with in time (pun intended)
   * [1412961](https://bugzilla.mozilla.org/show_bug.cgi?id=1412961) resolved fixed in FF61+, canvas use in extensions no longer get blocked
   * [1377744](https://bugzilla.mozilla.org/show_bug.cgi?id=1377744) not resolved yet: time spoof + extensions

**Comment by mazesy** [comment]
Since I had pointed out the` dom.w3c_pointer_events.enabled-true` requirement for the _Gesturefy_ extension,
because the scenario of an extension requiring a pref to be set differently than what privacy suggests is not the ultimate,
maybe is is worth mentioning another extension named _Foxy Gestures_, very similar (I'd even say better) to _Gesturefy_ exists that runs flawlessly with` dom.w3c_pointer_events.enabled` set to `false`

For whom may be concerned. Of course it's always better to use an extension which doesn't appear to contradict our privacy settings.

**Comment by Thorin-Oakenpants** [comment]
**pref(s)**: `security.OCSP.enabled`=`1` (this is FF's default value)
**extension(s)**: [Hoxx VPN Proxy](https://addons.mozilla.org/en-US/firefox/addon/hoxx-vpn-proxy/) and probably others
**breakage**: failure to use/log-in to VPN
**site/support issue**: https://github.com/ghacksuserjs/ghacks-user.js/issues/295
**comments**: `security.OCSP.require` may also be a factor in these sorts of cases. In the user.js we enforce a value of `true`, the default is `false`

**Comment by Thorin-Oakenpants** [comment]
Thanks @Pilford
**pref(s)**: `layout.css.font-loading-api.enabled`=`false`
**extension(s)**: [Save Page WE](https://addons.mozilla.org/firefox/addon/save-page-we/) and probably other "save as" extensions
**breakage**: save silently fails, console warning: `document.fonts is undefined`
**site/support issue**: #592 
**comments**: read the issue

**Comment by Pilford** [comment]
From the developer of Save Page WE:

Save Page WE uses the CSS Font Loading Module to check which fonts are currently being used in the page that is being saved.
 
Without doing this check, Save Page WE would have to save all of the font files that are referenced in any CSS ‘@font-face’ rules.  This would often make saved files much larger.
 
When saving the page, Save Page WE downloads the font files for the fonts that are currently being used in the page and (optionally) for WOFF fonts.

**Comment by aesthicc** [comment]
pref(s): network.auth.subresource-http-auth-allow = 1
extension(s): [Torrent Control](https://addons.mozilla.org/en-US/firefox/addon/torrent-control/) 
breakage: failed login
site/support issue: https://github.com/Mika-/torrent-control

**Comment by powerman** [comment]
> **pref(s)**: `dom.w3c_pointer_events.enabled`-`false`
> **extension(s)**: [Gesturefy](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/) in FF59+ and maybe other gesture type extensions
> **breakage**: see support issue linked below
> **site/support issue**: [Robbendebiene/Gesturefy#271](https://github.com/Robbendebiene/Gesturefy/issues/271)
> **comments**: RFP may take care of this one day: see [1363508](https://bugzilla.mozilla.org/show_bug.cgi?id=1363508)

This comment should be updated:
- RFP must be disabled for Gesturefy-2.x
- Gesturefy-1.2.2 [should work](https://github.com/Robbendebiene/Gesturefy/issues/327#issuecomment-423776629) with RPF
- [1363508](https://bugzilla.mozilla.org/show_bug.cgi?id=1363508) was resolved 5 months ago, but in FF 66.0 Gesturefy still doesn't work with RPF, so I suppose this bug didn't fixed this issue

**Comment by GitCurious** [comment]
**pref(s)**:  // user_pref("javascript.options.ion", false);
                    // user_pref("javascript.options.baselinejit", false);
**extension(s)**:  Ublock Origin
**breakage**:  Significant delays opening pages when these are enabled
**site/support issue**:  all
**comments**:  I DO realise these are OFF by default but discovered by trial and error that these were responsible for the delays on Firefox since approx v.66.xx

**Comment by Thorin-Oakenpants** [comment]
I lived with those prefs as active for about 6 months, 3 years ago. They caused lots of little issues, like fucked up widgets, etc. As it happens, yesterday I fixed the tag - https://github.com/ghacksuserjs/ghacks-user.js/commit/d41372a7f00edefe16b7aa28c5f5abd2e2951328

**Comment by GIPeon** [comment]
**pref(s)**: `privacy.resistFingerprinting`
**extension(s)**: uBlock Origin
**breakage**: Can't use shortcuts for uBlock tools like Zapper etc..
**site/support issue**: all
**comments**: With resist fingerprint enabled you cant set any shortcut in the setting page.  
I tried also to disable RFP, set the shortcut and enable RFP again, yet when you try to use the shortcut it wont fire the tool action (eg. Zapper). 

Btw your troubleshooting tips and the script turned out to be very useful. I scratched my head quite some time trying to debug this, looking at possible console errors and stuff but nothing really pointed me in the RFP direction (or maybe my lack of experience, quite deep unfortunately, didn't allow me to find any correlation). 

I take the chance to thank you all for all your commitment in this incredible work, very well done sirs! :tophat:

**Comment by Hackerpcs** [comment]
**pref(s)**: `dom.IntersectionObserver.enabled` = false
**extension(s)**: Reddit Enhancement Suite, studio.youtube.com
**breakage**: On RES, the button "hide child comments" may be missing from comments below the first, comments may not load at all besides the first one.
**breakage2**: studio.youtube.com (not an extension I know) doesn't load at all
**site/support issue**: -
**comments**: n/a

**Comment by cokeflash** [comment]
I can't login anymore because I tweaked my prefs in Firefox.

Which prefs could break the LOGIN procedure to web email accounts.
I reverted back all Javascript prefs to default but that did not help.

When I click on Login-button, nothing happend.

Idea?

**Comment by Thorin-Oakenpants** [comment]
you tweaked, changed, locked .. over 2000 prefs and asked in another issue. If you want *any* help, then stick to posting in the other issue and don't post off-topic in this one: which is **specifically** for listing **known EXTENSION breakage** from prefs that **we** use

**Comment by Thorin-Oakenpants** [comment]
FYI

[1576254](https://bugzilla.mozilla.org/show_bug.cgi?id=1576254): FF70+ (and supposed to get backported to the next ESR)
**pref(s)**: `javascript.options.wasm`
**breakage**: pref no longer applies to extensions

[1564208](https://bugzilla.mozilla.org/1564208): FF70+ and ESR68.1.0+
**pref(s)**: `gfx.font_rendering.opentype_svg.enabled`
**breakage**: pref no longer applies to extensions

**Comment by earthlng** [comment]
`gfx.font_rendering.opentype_svg.enabled` ??? Isn't 1564208 about `svg.disabled`?

**Comment by Thorin-Oakenpants** [comment]
I misread it as enabled and there was only one `svg.enabled` in the user.js

**Comment by atomGit** [comment]
i probably should have added this long ago, but i'm lazy

pants, forgive me for not using your template but i didn't feel like doing that for a pile of prefs ... because i'm lazy :)

this may help some folks, however be aware of the risks when deviating from the ghacks prefs - [go here](https://codeberg.org/12bytes.org/Firefox-user.js-supplement/raw/branch/master/user-overrides.js) and Ctrl+F 'GHACKS DIFFS' - particularly the prefs tagged with 'UNBREAK'

**Comment by sshockley** [comment]
Having dom.storage.next_gen=true appears to break the Kee add-on.  With it enabled, this shows in the debug panel for Kee:

```
Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:831
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:678
Failed to persist storage for principal: moz-extension://a89a86d1-eb13-4bb1-a064-6a5651978d2d ExtensionStorageIDB.jsm:758
    callback resource://gre/modules/ExtensionStorageIDB.jsm:758
```

The add-on shows the red "OFF" splat and is greyed out.  Setting dom.storage.next_gen=false fixes it.

This started with FF83, but I'm not sure if that's coincidence.

**Comment by Thorin-Oakenpants** [comment]
> This started with FF83, but I'm not sure if that's coincidence

I only added it to the user.js in the [11 days ago](https://github.com/arkenfox/user.js/commit/accef19af474c4aba5534325f465d45c5fb85ea1), so not a coincidence

Have you spoken to the extension developer? What happens if you try the extension in a new profile and add some data? When I get time I'll see what I can test, but some legwork from the dev would be helpful

**Comment by rubaboo** [comment]
**pref(s)**: need help to find which ones
**extension(s)**: [Pinboard WebExtension](https://addons.mozilla.org/en-CA/firefox/addon/pinboard-webextension)
**breakage**: "Save tab set" not producing a list of windows and tabs
**comments**: "Save tab set" opens a new tab to pinboard.in website (login required, unfortunately) populated with a list of all windows and tabs I have in the session. This works on a new profile but the moment I add `arkenfox/user.js` to the profile and restart, the page is not populated anymore. Any hints on which particular preferences could be causing this are appreciated.

**Comment by Thorin-Oakenpants** [comment]
> tweak any of the other 3 related prefs

If you mean the ones that are commented out in section 4000, then no. They will do nothing if `privacy.firstparty.isolate` = `false`

**Comment by rubaboo** [comment]
> 
> 
> > tweak any of the other 3 related prefs
> 
> If you mean the ones that are commented out in section 4000, then no. They will do nothing if `privacy.firstparty.isolate` = `false`

I understand, that's why I specifically said "Wondering if it's possible to **keep this switch true but** *tweak any of the other 3 related prefs* **to get the "Save tab set" working** on pinboard.in.". Yes, I did mean the ones that are commented out in section 4000. I have since played with those and nothing would help other than turning off the master switch (`privacy.firstparty.isolate` = `false`).

**Comment by Thorin-Oakenpants** [comment]
OK, sorry. Haven't had my beersies today :)  You could try with `privacy.firstparty.isolate.restrict_opener_access` as false but AFAIK it hasn't ever really done anything and Moz (tom ritter) wanted to rip it out

**Comment by rubaboo** [comment]
The only error is in the chrome console (Browser Toolbox):
```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
popup_menu.js:7
    <anonymous> moz-extension://dc93e56f-ce5c-40f9-9865-367cbf028d44/popup_menu.js:7
```

**Comment by gapop** [comment]
@rubaboo , yes, that console error is almost certainly unrelated.

**Comment by Youngblood50** [comment]
> dom.w3c_pointer_events.enabled

This also breaks firefox "picture in picture" mode

**Comment by crssi** [comment]
> 
> 
> Following pref: dom.w3c_pointer_events.enabled = false
> 
> also breaks firefox "picture in picture" mode

Does it? I have no issues with PIP.
Could you be so kind and write STR (Steps To Reproduce)?

Cheers

**Comment by Youngblood50** [comment]
> 
> 
> > Following pref: dom.w3c_pointer_events.enabled = false
> > also breaks firefox "picture in picture" mode
> 
> Does it? I have no issues with PIP.
> Could you be so kind and write STR (Steps To Reproduce)?
> 
> Cheers

I just tested this with several new profiles: If this is the only option present in user.js, the pip button appears in videos but when you try and click on it nothing happens.

**Comment by crssi** [comment]
Ahhh... sorry, my bad and you are right.
I was confused, since arkenfox_user.js doesn't touch that pref.

**Comment by rusty-snake** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/33577

**Comment by khius** [comment]
I need help figuring out which preference breaks the extension raindrop.io from signing in.

<img width="694" alt="Screen Shot 2021-11-10 at 10 51 30 AM" src="https://user-images.githubusercontent.com/6244107/141152875-c6c8a3c5-7868-4463-b321-172e5c9db35d.png">

**Comment by rusty-snake** [comment]
Did you tested https://github.com/arkenfox/user.js/blob/f8932dced142ec5ea633bfb163bfc7579ac38a07/user.js#L952

**Comment by khius** [comment]
Oh, that was easy! It worked! I am wondering if there is a workaround to keep "privacy.firstparty.isolate" to true an make this extension functional? Thanks btw

**Comment by rusty-snake** [comment]
This needs to be fixed on their end.

Btw does anybody know if dFPI can break such extensions (extensions not aware of FPI) too?

**Comment by rusty-snake** [comment]
But if they don't use it they will break, right?

**Comment by Thorin-Oakenpants** [comment]
^ soz, went and found the ticket I had in mind, it was for GPC - https://bugzilla.mozilla.org/show_bug.cgi?id=1735372

**Comment by rusty-snake** [comment]
If anyone cares:

- FPI: `privacy.websites.firstPartyIsolate == true`
- dFPI: `privacy.websites.cookieConfig.behavior == "reject_trackers_and_partition_foreign"`

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites

---

@khius you can use [TC](https://addons.mozilla.org/de/firefox/addon/temporary-containers) in automatic mode to get a similar isolation as with FPI.

**Comment by khius** [comment]
@rusty-snake I set privacy.websites.firstPartyIsolate == false, I installed TC with Isolation global, I excluded in TC raindrop.io and subdomains from Isolation, I allowed cookies in FF settings from raindrop.io and subdomains but the extension **is not working**. Once I disable TC it works again. I don't know what I am missing.

**Comment by rusty-snake** [comment]
- TC: How did you setup isolation?
- TC: How did you setup exceptions?
- Ctrl-Alt-Del, go on `about:networking` make sure it is empty, do raindrop.io, reload `about:networking`, which addresses show up? Are all of them excluded?
- privacy.websites.firstPartyIsolate is a WebExt API.

**Comment by powerman** [comment]
>     * Ctrl-Alt-Del, go on `about:networking` make sure it is empty, do raindrop.io, reload `about:networking`, which addresses show up? Are all of them excluded?

You just caught me - for a second I believed FF actually set some binding for Ctrl-Alt-Del! :rofl:

**Comment by rusty-snake** [comment]
Arrrg. I meant Ctrl-Shift-Entf.

**Comment by khius** [comment]
TC: How did you setup isolation?
Automatic Mode
TC: How did you setup exceptions?
<img width="317" alt="Screen Shot 2021-11-11 at 9 28 45 AM" src="https://user-images.githubusercontent.com/6244107/141315504-83faec3c-d5f0-4f93-94e7-1650e7e60bfc.png">
go on `about:networking` make sure it is empty, do raindrop.io, reload `about:networking`, which addresses show up? Are all of them excluded?
These are the addresses that shows in about:networking
![IMG_1626](https://user-images.githubusercontent.com/6244107/141315617-75e68812-3e9f-4683-9aae-dab93a8da6c5.jpeg)
But it's still not working 😬

**Comment by rusty-snake** [comment]
> TC: How did you setup isolation?
Automatic Mode

That's not isolation that's automatic mode. Isolation is configured under "isolation" (not "general"). To setup isolation it is IMHO the best to "Isolation > Global > Navigation > Different from Tab Domain & Subdomain". (Don't get me wrong automatic mode is useful and should be used in addition).

If you are interested what I do: https://codeberg.org/rusty-snake/firefox-config/src/branch/main/LOG.md

> How did you setup exceptions?

This exceptions are only for isolation but not from automatic mode. Try to add the raindrop domains (the ocsp isn't necessary and the couldfront domain is maybe from firefox itself) under "Advanced > Ignoring requests to"

**Comment by khius** [comment]
Thank you @rusty-snake! now it's working! I left Automatic Mode ON and added under "Advanced > Ignoring requests to" the raindrop.io domains and subdomains. I set up "Isolation > Global > Navigation > Different from Tab Domain & Subdomain" as suggested and it's working fine.

**Comment by NylaTheWolf** [comment]
@rusty-snake @khius Funny, I was literally just about to comment about the exact same issue with first party isolation and Raindrop.io! I'll be sure to try that workaround when I get home!

For what it's worth, I did email the dev about it a few days ago about the issue and [he added it to the troubleshooting pages](https://help.raindrop.io/firefox-extension-problems).

**Comment by rusty-snake** [comment]
> Be sure that privacy.firstparty.isolate is disabled

TBH they should fix this in their code (IDK how long this suggestions is there (no site histroy), so maybe they are already working on a fix and this is only a interim suggestion).

**Comment by RevolverTexture** [comment]
**pref(s)**: `user_pref("privacy.resistFingerprinting", true);`
**extension(s)**: [Dark Mode Website Switcher](https://addons.mozilla.org/en-US/firefox/addon/dark-mode-website-switcher/) 
**breakage**:  websites prefer light mode than dark mode
**solution**: change  `user_pref("privacy.resistFingerprinting", true);` to `false`
