### ISSUE TITLE
user.js viewer/comparer/tool (userjs-tool.html)

### ISSUE THREAD

**Issue by icpantsparti** [arkenfox/user.js#608]
Experimental/alpha: https://github.com/icpantsparti/firefox-user.js-tool
Opens offline, or online: [userjs-tool.html](https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html)
(Revival of the old user.js dark/light theme.)
![](https://github.com/icpantsparti/firefox-user.js-tool/blob/master/images/userjs-tool.png?raw=true)
(EDITED: online link, 2020.02.22 user.js comparer added)

**Comment by bogachenko** [comment]
Whoopsie daisy advertising

**Comment by Thorin-Oakenpants** [comment]
looks interesting. I had a play but couldn't get it to load a local js file (and I had to use Opera - my FF is locked down, might see if if I can get it to work tomorrow) - but simply pasting in the links at the bottom and I could view the live master - it certainly is easier viewing in a more interactive environment (jumping to sections, collapsing etc)

Hope you learnt lots about html, js, css etc (from your repo info)

**Comment by icpantsparti** [comment]
Noteworthy changes (hope you don't mind me 'advertising' again :D).

https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html

added user.js compare, improved file/URL loading, updated layout and more
multi preference regex search [Groups] now work in the newer about:config search box
added functions for find (filter/list)/reset/set on about:config Web Console

Live auto-load and view ghacks-user.js master:
https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html?action=view1&box=a&load1=https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js

Hope someone else finds this useful.  Thank you.

**Comment by Thorin-Oakenpants** [comment]
I could/should do more about/with this - re-opening so it's on my radar.

Good stuff @icpantsparti 

I find the page ~~quite~~ terribly confusing - e.g I went to help and couldn't work out how to get back (but I did work it out) etc ... nothing got colored, there's some button/element partially hidden (I tested in both my main FF and in FF75 nightly)

^^ Don't take any of that the wrong way. I'm just looking at it from going there as a new user and going - what does this do, how does this work? And that's partly on me for not reading/understanding the purpose of the site - but the site could do with some fresh eyes on it  :)

---

I was actually thinking of creating that real-time interactive ghacks user.js that @overdodactyl did - but doing it all from scratch under `https://github.com/ghacksuserjs/` - i.e fetch file, parse it

**Comment by icpantsparti** [comment]
> Don't take any of that the wrong way.

Thanks for looking and your fair comments.

I have made a few tweaks addressing your immediate examples.

> nothing got colored

I am unsure how to reproduce this.  Does the hint added since, about using the View (or Compare) button after loading user.js resolve this, was the issue after clicking, or was it with the auto-load link (which 'clicks' the View button using JavaScript)?

**Comment by Thorin-Oakenpants** [comment]
Not sure what you did, and I can't exactly remember how it looked before (and sorry for not inspecting elements or doing any basic troubleshooting) .. I am testing in Nightly 75 and whatever was partially hidden before is no longer hidden - and the help/info seemed to help me at least get to hit the view button, and now I see color

I can't work out how to get back to the main default screen (after clicking view) .. oh, actions button - probably a case of getting used to it.

Seems weird that 9999 is just the header + parrot and then a new section called 9999+ is created. Since I'll never change this number for deprecated, you could maybe hardcode for as special treatment -> or is something missing in the user.js that causes this?

I definitely want to something more with this: i.e point to it as a tool for users - but I'm not entirely sure of the purpose (that's on me) and not sure about helping users discover at all those other user.js - over 35% of pk's items are deprecated (see: `https://github.com/privacytoolsIO/privacytools.io/issues/1240` ) and without looking too deeply at the others: most have IMO at least some terrible pref choices enforced and/or are quickly abandoned - so I don't really want to do anything that helps promote them

All that said (and I haven't looked at the code), but I like the speed. #578  Overdactyl's real-time interactive ( https://nwmviewer.shinyapps.io/ghacks_userjs/ - and I think it's still looking at an old version for testing) takes ages to fetch, load,parse, and output: it *seems* heavy (IDK: maybe I can't make it any faster). And I want to recreate his and finish it (without heavy libraries or third parties). But this would have a different purpose to yours

**Comment by overdodactyl** [comment]
>takes ages to fetch, load,parse, and output: it seems heavy

Just seeing this thread, but that's an interesting issue of all things...seems to consistently render in under 1 second for me and on various speed testing sites.  

I don't remember where I posted that code (or if I did), but I can track it down if it's helpful.  It was primarily written in R. Things could, of course, be written without any additional libraries, but in cases like this there's often not much reason to reinvent the wheel...more than likely will end up with something that's not flexible enough, too slow, difficult to maintain etc.  Just my two cents for what it's worth.

**Comment by Thorin-Oakenpants** [comment]
OMG .. the bird lives 👍  @overdodactyl 

For me, it takes about 5 seconds (basically a new profile on nightly) - always has. As for rolling an own solution, who knows: I don't think it is hard to cover any potential errors in order to make it robust and futureproofed - it's really only parsing a text file -> output. Whether it's worth the time and effort IDK - its not high priority, but it sure would be nice for users to be able to toggle active/inactive, or default/non-default, setup-tag/non-setup-tag etc - as well as other basics like hyperlinked references

**Comment by icpantsparti** [comment]
https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html?action=table1&size=100&load1=https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js

**Comment by Thorin-Oakenpants** [comment]
spiffy and blazingly fast

**Comment by icpantsparti** [comment]
>whatever was partially hidden before is no longer hidden

A button on the view area placeholder was visible beyond the Actions panel making it seem like a hidden element, width was reduced 2020.02.24

>how to get back to the main default screen (after clicking view) .. oh, actions button

Have now added a "Back" button (it replaces/merges "Actions" and close buttons)

>Seems weird that 9999 is just the header + parrot and then a new section called 9999+ is created.

The user.js does not cause this, when section 9999 was big the extra divide at ESRs was useful, no need for that anymore and divide removed 2020.02.27

>other user.js ... most have IMO at least some terrible pref choices enforced and/or are quickly abandoned

The list of user.js links was removed 2020.02.27  just link to here remains :)

>could be anchored/overlaid at the top with the date/version

The "Table View" now updated 2020.03.21, improved tag detection and added a Filter button too

> which skip redirect extension didn't like

Have added this shortcut now (auto-loads ghacks user.js into "Table View"):
https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html?gt

**Comment by Thorin-Oakenpants** [comment]
cool 👍 

> when section 9999 was big the extra divide at ESRs was useful, no need for that anymore

An ESR divide/split will still happen as we transition between the start of the next ESR and the actual EOL of the previous one - https://wiki.mozilla.org/Release_Management/Calendar - e.g. see the overlap with `68.10, 68.11, 68.12` - i.e we will start a new ESR section at 78, but have to keep the ESR68 section until 81

**Comment by username-is-not** [comment]
> manual file comparison

On what device... Notepad++ (on PC) has a compare plugin, btw.

**Comment by Thorin-Oakenpants** [comment]
@icpantsparti - thanks for keeping everything working with the cleanup / restructuring in #1235

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/blob/4b393b9b1220481bf544153893995ba2e4bff7d8/user.js#L1221-L1223

@icpantsparti do you need to code around this? i.e a numbered item with no pref entries?

**Comment by Thorin-Oakenpants** [comment]
https://icpantsparti.github.io/firefox-user.js-tool/userjs-tool.html?at

Just been having a play with this. Shame it fetches cross-domain and hardened uBO needed an exception. I wonder if we could host a copy here that autoloads AF - and/or we could pass filter parameters

I feel we could do more promoting/using this

**Comment by icpantsparti2** [comment]
Latest version now at a new account, [https://github.com/icpantsparti2/firefox-user.js-tool](https://github.com/icpantsparti2/firefox-user.js-tool), made a few tweaks (listed in the ChangeLog file).

Any previous links in this thread to /icpantsparti/ now point at a dormant account/repo (which I cannot access).

> a numbered item with no pref entries

There were some like that in the past, the code is ok with it, thanks.

> host a copy here that autoloads AF

I have added some code to the latest version that would auto load/display if the document is hosted anywhere at arkenfox.github.io eg "https://arkenfox.github.io/foo/bar.html", it would fetch "https://arkenfox.github.io/user.js/user.js" (if GitHub pages are enabled, unless you know another way of being same domain).  It will also auto use an arkenfox theme (defined in the css near the top) if you want some different values.  (I have not tested this.)

> and/or we could pass filter parameters

what did you have in mind?

**Comment by Thorin-Oakenpants** [comment]
so my idea is/was to turn on github pages and we could link to it (autoloaded with the live master) - and if we could pass e.g. `#filter_value` (and we would check it's a valid filter in code), then it wouldn't be handy to link to show users, e.g.
- have you checked all these `https://.../index.html#filter_setup-web`
- basically, anything that can be filtered should be able to be parsed via the url
   - load local user.js
   - built filter lists
   - parse `window.location.href` for filter
   - valid filter
   - apply filter
- note: we wouldn't want to trigger any url param cleaning

I would definitely want some cosmetic changes (font size is too big, make colors consistent with TZP, hide some options), and not sure where I want to house this - maybe make an arkenfox/gui repo (easy enough to load and update a single user.js in there once a month)

**Comment by icpantsparti2** [comment]
> if we could pass e.g. #filter_value

I just started playing with something like this recently, the latest version put up not long before you posted now has a regexp search option and a s= parameter working, eg:

_note: it would not need the 'at&' bit when on arkenfox (it would autoload)_

- https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&s=ocsp

- https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&s=\[setup-web

- https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&s=\b(netflix|eme|gmp|cdm|drm)\b

> we wouldn't want to trigger any url param cleaning

hopefully s= is ok as it is common for search parameters.

> arkenfox/gui repo (easy enough to load and update a single user.js in there once a month)

if it is `https://arkenfox.github.io/gui/index.html` and if github pages are also enabled on the main user.js repo, then it will auto load `https://arkenfox.github.io/user.js/user.js`.  coded for that already.

**Comment by Thorin-Oakenpants** [comment]
i need to drink on this a bit more, but I'm leaning towards a separate repo, and you can have admin rights there

the index page would be something simple to say that this is a front end for the current release (as shown when loaded) and to link back to this repo, and to link to the actual gui.html (or whatever we call it)

if we filter, we should update the urlbar to match

zooming - one of the things I want to strip out: basically I just a gui/filter, not a compare tool - just hiding the UI options should be enough: stick it behind some auto-code if you want so your original repo doesn't have issues

Lemme drink a bit more first .. but if you're happy with `arkenfox/gui` as a repo and `index.html` and `live.html` for the two pages, I can go ahead and set that up and we can move discussion there and fire this puppy up as we protoype

**Comment by Thorin-Oakenpants** [comment]
to be clear - the user.js needs to reside in the same repo - we will just update it once a month when I do each release here

**Comment by Thorin-Oakenpants** [comment]
https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&size=85&s=%5C%5Bsetup-web

ahh, i see, it adds a search filter rather than use an existing one

https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&size=85&s=%5C%5Bsetup <-- shows all of them. e.g. setup-chrome, setup-web etc

so ff should return all FF version tagged items (didn't try it - time for me to knock off and get some downtime)

**Comment by Thorin-Oakenpants** [comment]
[https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&size=85&s=\b(netflix|eme|gmp|cdm|drm)\b](https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?at&size=85&s=%5Cb(netflix%7Ceme%7Cgmp%7Ccdm%7Cdrm)%5Cb)

fuck yeah 👍 🥇

**Comment by icpantsparti2** [comment]
I have now added an arkenfox repo mode (automatic when the .html is on an arkenfox repo and it will load the user.js copy on that repo).  [This link for demo.](https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html?afmode=demo)

It has reduced UI, smaller font, TZP color values, urlbar changes on some filters (ie to show parameters t= for tag s= for search).  [(ChangeLog)](https://github.com/icpantsparti2/firefox-user.js-tool/blob/master/ChangeLog)

**Comment by Thorin-Oakenpants** [comment]
sorry for the delay .. I'll set up the repo so we can finishing prototyping - I think we will alter this in many subtle ways, and should treat it as a separate project/code from the original tool - but of course, the bulk of the code will stay the same - we can talk about it there

In hindsight I think a single index.html is fine (a landing page is just extra work), and we will include info in a header section or whatever that links to arkenfox repo itself and where to log issues

**Comment by Thorin-Oakenpants** [comment]
closing .. see new pinned shiny
