### ISSUE TITLE
meta: tor uplift: privacy.firstparty.isolate

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#8]
Locked sticky issue for tracking privacy.firstparty.isolate
 - [Tor Uplift](https://wiki.mozilla.org/Security/Tor_Uplift/Tracking)
 - [MVP Tracking](https://wiki.mozilla.org/Security/Fingerprinting)
 - [Bugzilla META FPI ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1299996)
 - [Bugzilla META partitioning ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1590107)
 - [Tor Uplift Dependency Tree](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1260929&hide_resolved=0)

Last updated: see changelog at foot

---

### 🔶 FPI : `privacy.firstparty.isolate`

:small_red_triangle_down: FF51
 * [1260931](https://bugzilla.mozilla.org/show_bug.cgi?id=1260931) enable First Party Isolation
   // user_pref("privacy.firstparty.isolate", true);
 * [1278037](https://bugzilla.mozilla.org/show_bug.cgi?id=1278037) isolate indexedDB

:small_red_triangle_down: FF52
 * [1277803](https://bugzilla.mozilla.org/show_bug.cgi?id=1277803) isolate favicons
 * [1264562](https://bugzilla.mozilla.org/show_bug.cgi?id=1264562) isolate OCSP cache
 * [1268726](https://bugzilla.mozilla.org/show_bug.cgi?id=1268726) isolate Shared Workers
 * [1316283](https://bugzilla.mozilla.org/show_bug.cgi?id=1316283) isolate SSL session cache

:small_red_triangle_down: FF53
 * [1317927](https://bugzilla.mozilla.org/show_bug.cgi?id=1317927) isolate media cache

:small_red_triangle_down: FF54
 * [1323644](https://bugzilla.mozilla.org/show_bug.cgi?id=1323644) isolate HSTS and HPKP
 * [1334690](https://bugzilla.mozilla.org/show_bug.cgi?id=1334690) isolate HTTP Alternative Services
* [1319773#c22](https://bugzilla.mozilla.org/show_bug.cgi?id=1319773#c22) enforce FPI restriction for window.opener
   // user_pref("privacy.firstparty.isolate.restrict_opener_access", true);

:small_red_triangle_down: FF55
 * [1334693](https://bugzilla.mozilla.org/show_bug.cgi?id=1334693) isolate SPDY/HTTP2
 * [1337893](https://bugzilla.mozilla.org/show_bug.cgi?id=1337893) isolate DNS cache
 * [1344170](https://bugzilla.mozilla.org/show_bug.cgi?id=1344170) isolate blob: URI
 * [1300671](https://bugzilla.mozilla.org/show_bug.cgi?id=1300671) isolate data://, about: URLs

:small_red_triangle_down: FF58
 * [1376971](https://bugzilla.mozilla.org/show_bug.cgi?id=1376971) isolate Page Info media previews to content first party
* [1376973](https://bugzilla.mozilla.org/show_bug.cgi?id=1376973) favicon of tabs dropdown list does not honor originAttributes
* [1409045](https://bugzilla.mozilla.org/show_bug.cgi?id=1409045) extensions can control `privacy.firstparty.isolate`

:small_red_triangle_down: FF63
* [1473247](https://bugzilla.mozilla.org/show_bug.cgi?id=1473247) isolate IP addresses

:small_red_triangle_down: FF65
* [1492607](https://bugzilla.mozilla.org/show_bug.cgi?id=1492607) Prevent postMessage communication across first-party when restrict_opener_access = true

:small_red_triangle_down: FF68
* [1542309](https://bugzilla.mozilla.org/1542309) isolate top-level domain URLs
* [1506693](https://bugzilla.mozilla.org/1506693) isolate PDFJS range-based requests  [Tor 26540, resolved 8.5a5](https://trac.torproject.org/projects/tor/ticket/26540)

:small_red_triangle_down: FF69
* [1330467](https://bugzilla.mozilla.org/1330467) isolate site permissions

:small_red_triangle_down: FF73
* [1534339](https://bugzilla.mozilla.org/1534339) isolate IPv6 addresses

---

### NOTABLE RESOLVED BREAKAGE
 * ~~[1418931](https://bugzilla.mozilla.org/show_bug.cgi?id=1418931) - FPI & IDB clearing on close or manually via clear recent/all history~~
   * fixed in FF58+
 * ~~[1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197) - FPI & cookies~~
   * fixed in FF59+
 * ~~[1384657](https://bugzilla.mozilla.org/show_bug.cgi?id=1384657) Pocket & FPI~~
   * fixed in FF66+

### PENDING

* [444222](https://bugzilla.mozilla.org/show_bug.cgi?id=444222) window.name
* cross-domain / login issues
   [lots: here are *some*] [1319728](https://bugzilla.mozilla.org/show_bug.cgi?id=1319728), [1336458](https://bugzilla.mozilla.org/show_bug.cgi?id=1336458), [1319839](https://bugzilla.mozilla.org/show_bug.cgi?id=1319839), [1319761](https://bugzilla.mozilla.org/show_bug.cgi?id=1319761), [1316019](https://bugzilla.mozilla.org/show_bug.cgi?id=1316019), ~~[1340949 - breaks FF Sync's Manage Accounts](https://bugzilla.mozilla.org/show_bug.cgi?id=1340949)~~
* [1371651](https://bugzilla.mozilla.org/show_bug.cgi?id=1371651) about:cache is broken
* [1397624](https://bugzilla.mozilla.org/show_bug.cgi?id=1397624) option to restrict FPI to PB mode
* [1398414](https://bugzilla.mozilla.org/show_bug.cgi?id=1398414) css visited links
* [1422056](https://bugzilla.mozilla.org/show_bug.cgi?id=1422056) isolate site permissions by OA
* [1475811](https://bugzilla.mozilla.org/show_bug.cgi?id=1475811) entering urls in addressbar violates FPI
* [1549587](https://bugzilla.mozilla.org/show_bug.cgi?id=1549587) dynamic FPI

### INVALID / WONTFIX
* ~~[1312655](https://bugzilla.mozilla.org/show_bug.cgi?id=1312655) checkbox in about:preferences#privacy for privacy.firstparty.isolate~~

### CHANGELOG

this is now obsolete: FPI is not being worked on: it is superceeded by dFPI

...

**Comment by Atavic** [comment]
[TheWebNeverForgets](https://github.com/citp/TheWebNeverForgets) has a paper called [Persistent Tracking Mechanisms in the Wild](https://securehomes.esat.kuleuven.be/%7Egacar/persistent/the_web_never_forgets.pdf) that explains a very underrated issue: **Cookie Syncing**.

**Comment by Roman-Nopantski** [comment]
Thanks, when I get time I want to read up on it. But wrong issue, this is for the specific tor uplift pref listed above, and FPI is going to be a doozey! :) Just open a new issue: to investigate: cookie syncing, or FYI: cookie syncing. Cheers

**Comment by earthlng** [comment]
2698c is isolating the OCSP cache, not the requests
2698e I think is irrelevant with `security.ssl.disable_session_identifiers;true`

**Comment by Roman-Nopantski** [comment]
2698e may be irrelevant because we have 1212, but 2698e is part of the info on all the stuff they're isolating .. the actual pref itself isolated cookies and cache and blobs etc .. not listing all that, which was all marked as duplicate back to the original FPI ticket. But everything else after is information which allows us in future to re-enable things maybe

I could say the same about 2698h - because we already disable HTTP Alternative Services in 2666. Or 2698d because we disable Shared Workers anyway.

I was going to link each one, where applicable, back to relevant pref eh 2698e->1212 etc, but decided against it.

Part of the reason I like documenting this is it shows how so not ready it is for prime time yet. Not just that some of the final items won;t even land until 55 or after, but they have major issues with sites using different domain logins, and FPI is starting to break lots of addons (because I guess the information is isolated) - example Self Destructing cookies. So for now, its just a case of adding relevant info and watching it for the next 5 months (55 lands in 2017-08-08) or longer (56 lands in 2017-10-03) and by 57 (2017-11-14) all hell will break loose. I hope they delay *that* change until the new year - the timing sucks

**Comment by earthlng** [comment]
Yes, I totally appreciate all the infos and didn't mean for you to remove it or anything.
I was just looking at it and was wondering if it would still honor that pref with those changes - I'm not sure though, but I think it does still honor it.

**Comment by earthlng** [comment]
And yeah, not looking forward to FF57 either. I'll probably switch to ESR then and use that as long as possible. I hope I won't have to abandon FF all-together because that would be a shame.

**Comment by Roman-Nopantski** [comment]
> Yes, I totally appreciate all the infos and didn't mean for

Absolutely. Corrrect description fixup appreciated. It will be something we can look at in 6 months. And each type of isolation will be a case by case basic. eg allowing "isolated" SSL session tickets might be an answer to a session-only solution. So speed shit up, less handshakes etc. But a new session starts anew? Or a new window/tab? IDK - shit to do in 6 months :)

> FF57
I will cross this bridge when we come to it. I am happy to lose all the UI changes - I want function over form. But a lot of functionality will be lost from a few addons. Example, Disable IndexedDB (which I will dump anyway - never use it) will be obsolete (toggle button), because access by addons outside their own extension specific prefs is prohibited. And on that note, its worth mentioning that this will fuel the rise of user.js - all those add-ons will break.

It's bad enough with e10s. I have whittled myself down to 40 add-ons - 10 are non e10s, and 3 of those will kill me. XUL deprecation will slaughter them all. Which means, I too will move to ESR, but then that will start to impact maintaining this user.js (or at least make it messy and more work). Closer to the event we can make decisions on all that, its too far away - but I right now (subject to change) I am inclined to change versioning to ESR, only support ESR, until such time as we can cover everything properly with WE - because I see a lot of extensions from the chrome store coming into play. Shit like Awesome Tabs and DownThemAll and CTR and so on are immaterial - they are not privacy/security items. Just as long as we can get decent granular control over Referers (and there's one already listed in the addons sticky) and Popup Blockers and all the other stuff, then I'm in - I will just lose some stuff I like/love but learn to adapt and move on.

**Comment by Roman-Nopantski** [comment]
>  I won't have to abandon FF all-together because that would be a shame.

There are no viable alternatives. I can see Mozilla slowly adding in some extra WE API functionality (maybe chrome etc will follow suit .. oh gees, the wars start again), but essentially they are all on a level playing field. They will all be fast, they will all be sandboxed, multi-process, secure, safe browsing, malware blocks etc etc. The only point of difference IMO will probably be privacy and the *insane* level of customization for these (exhibit A: ghacks user.js) - these will keep me on FF period. The others just don't care.

**Comment by earthlng** [comment]
> There are no viable alternatives.

yes, at least at the moment. I'm just worried that they may have more sinister reasons for all those changes. Dumbing it down and not allowing full-access anymore could lead to the same shit we now see in Win10. I mean ADs in the lockscreen, the start menu, the share menu, the taskbar AND the freaking File Explorer - are you god-damn fucking kidding me???!!! I'm expecting some kind of side-OS soon, so they can also shows Ads on the fucking blue-screen!! This shit is unbelievable

**Comment by Atavic** [comment]
FF 52.0 ESR 
```
// Show favicons in web notifications.
pref("alerts.showFavicons", false);

// No Favicons, Thanks!
pref("browser.chrome.favicons, false);
```

See [here](https://www.wilderssecurity.com/threads/mozilla-created-shortcuts-favicon-caching-windows.343315/) for `browser.shell.shortcutFavicons`

**Comment by earthlng** [comment]
=> moved from [Issue #15](https://github.com/ghacksuserjs/ghacks-user.js/issues/15)

@crssi commented on 21 Feb 

Observation report:
- **`privacy.firstparty.isolate`**
Oh man, this one is a problem maker. I know, its still in development, but just FYI.
It was somehow expected where I can find a problem.
`privacy.firstparty.isolate = true` isolates session in a way that even some FF extensions stops working.
For example "Self-Destructing Cookies" (SDC) does not destruct cookies after session, obviously SDC cannot access the session namespace.
Haven't tested uBlocker, uMatrix, NoScript... etc.

**Comment by Atavic** [comment]
A [Gmail notifier](http://add0n.com/gmail-notifier.html) [issue](https://github.com/inbasic/ignotifier/issues/444).

**Comment by Thorin-Oakenpants** [comment]
Note: https://bugzilla.mozilla.org/show_bug.cgi?id=1358361 . So as of FF55 these are no longer hidden prefs. Just making a note to remind us when we move to v55

**Comment by earthlng** [comment]
> So as of FF55 these are no longer hidden prefs

they never were!? That bugzilla is for `Firefox for Android`

**Comment by Thorin-Oakenpants** [comment]
Well poop .. I just got carried away as I was checking thru a list of tickets - because the other 'matching" one is https://bugzilla.mozilla.org/show_bug.cgi?id=1345322 which is for resistFingerprinting which is currently hidden (and marked as so)

**Comment by Atavic** [comment]
SDC is unable to access private cookie jar: https://github.com/pyllyukko/user.js/issues/245#issuecomment-287362397

**Comment by earthlng** [comment]
Instead of the current format
```js
/*** 2698: FIRST PARTY ISOLATION (FPI)
 ** isolate favicons (FF52+)
   [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1277803
 ** isolate OCSP cache (FF52+)
   [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1264562
// ...
```
can we do this: (?)
/*** 2698: FIRST PARTY ISOLATION (FPI)
 ** 1277803 - isolate favicons (FF52+)
 ** 1264562 - isolate OCSP cache (FF52+)
// ...
```
it makes it a lot easier to read IMO.

**Comment by Thorin-Oakenpants** [comment]
1397624 option to use FPI in PB mode - interesting, ignoring all the cross-domain login issues, if this was used in PB mode and 1381197 (FPI cookies are protected from extensions) is also resolved, then this would enable PB Mode users to properly control cookies (and local dom storage I would assume)

Meanwhile, those stats are telling. PB mode is a terrible name

**Comment by Thorin-Oakenpants** [comment]
@fmarier It has just come to my attention, that privacy.firstparty.isolate => true applies globally, to both normal and PB mode windows. My easy way to test (indexedDB) won't work in PB mode. Can you enlighten me please - TIA

**Comment by earthlng** [comment]
> 1397624 option to use FPI in PB mode 

> It has just come to my attention, that privacy.firstparty.isolate => true applies globally ...

huh? I'm confused

**Comment by Thorin-Oakenpants** [comment]
FPI is supposedly global - i.e the pref turns it on for all windows. The proposed 2nd pref *pbm would allow PB mode only to be toggled on/off (I assume both at false means no FPI). Or not. Something like

* [ ] Use FPI
    * [ ] Only use FPI in PB Mode

Where the first must be ticked in order to allow the second

**Comment by earthlng** [comment]
Oh okay thanks. Although I don't really understand why they would want FPI enabled in PB windows but not in normal windows. (?)

**Comment by Thorin-Oakenpants** [comment]
^^ because of breakage. It is better to test things in PB mode.

FPI will always have cross-domain login issues because some websites effectively use supercookies for their login flow.

Tor always uses PB mode, FPI was developed by Tor, they made it so it was used in all windows. If Mozilla were to uptake on it, they would want to trial it in PB mode

**Comment by earthlng** [comment]
That makes sense, thanks.

**Comment by Thorin-Oakenpants** [comment]
FYI: starting in FF58 WE have access to this pref - https://bugzilla.mozilla.org/show_bug.cgi?id=1409045

**Comment by Thorin-Oakenpants** [comment]
@earthlng - https://bugzilla.mozilla.org/show_bug.cgi?id=1418931#c2 ... not sure if you will get to see this

**Comment by earthlng** [comment]
thanks. Can *you* test it and see if you can reproduce it on FF57.0.2?
Create a fresh new profile, no user.js, start it, set FPI to true then go to that [site](https://static.raymondcamden.com/demos/2014/feb/7/index.html#/home), add a note or 2 and try to clear it with "Clear Recent History->Offline Website Data". Then check if the folder is gone and whether you have any error messages in the console.

**Comment by Thorin-Oakenpants** [comment]
will do, tomorrow .. am in the middle of some llama porn

**Comment by earthlng** [comment]
I can still reproduce it in ESR but not in nightly. It may have been a combination of using the different methods to clear the cache that perhaps locked it up in my original nightly testing, IDK. (forget this site, clear All Data in the new UI, and Clear Recent History)
btw you *can* use the user.js with a cookie exception to do the testing.

**Comment by Thorin-Oakenpants** [comment]
Some more comments since your post 8hrs ago

**Comment by Thorin-Oakenpants** [comment]
^^ https://github.com/ghacksuserjs/ghacks-user.js/commit/2a2b80902aa7d55d3468f9b1d19171edd5b15db5 - but yeah, didn't update this issue

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl [reddit](https://www.reddit.com/r/firefox/comments/87idde/facebook_container_extension_take_control_of_how/) .. IDB was isolated in the first bug in OP [1260931](https://bugzilla.mozilla.org/show_bug.cgi?id=1260931) .. also see [1405884](https://bugzilla.mozilla.org/show_bug.cgi?id=1405884) where even Arthur forgot it was covered already

**Comment by overdodactyl** [comment]
Thanks! I'll update by comment to reflect that :)

**Comment by dartraiden** [comment]
First-Party Isolation also breaks Pocket functionality. You cannot add something to Pocket via location bar button.

**Comment by Thorin-Oakenpants** [comment]
just added
 * [1384657](https://bugzilla.mozilla.org/show_bug.cgi?id=1384657) Pocket & FPI

**Comment by Thorin-Oakenpants** [comment]
> * [1492607](https://bugzilla.mozilla.org/show_bug.cgi?id=1492607) Prevent postMessage communication across first-party when restrict_opener_access = true

@earthlng Do we need to add anything this (FF65+) to `4002` ?

**Comment by earthlng** [comment]
The patch only addresses postMessage's sent to targetOrigin `*`.

There's a new hidden pref `privacy.firstparty.isolate.block_post_message` but the patch also provides some additional protection without the new pref set.

The commit title is `Make postMessage aware of OAs when the targetOrigin is "*".`
> This patch adds a MOZ_DIAGNOSTIC_ASSERT for assuring the OAs are matching when the targetOrigin is "*" for the postMessage(). But it ignores the FPD in OA since the FPDs are possible to be different.
We also add a new pref 'privacy.firstparty.isolate.block_post_message' for allowing blocking postMessage across different FPDs.

I think that means totally unrelated and potentially malicious 3rd-party sites, which you may have open in another tab, can no longer receive messages sent between 2 connected sites. (think cross-login fe)
And you don't need the pref for that part!

The pref (default-off and hidden because it can cause breakage!) will stop the communication if the 2 sites don't also share the same 1st-party domain.

> Do we need to add anything ...?

we can add the new pref but I don't think it's necessary to enable it.

**Comment by Thorin-Oakenpants** [comment]
I'd like to add something. Anything RFP+FPI related I like to get into their respective section headers so it paints a full picture. I thought just a note under 4002 would suffice eg `[NOTE] FF65+ when true...` . but now it seems complicated and might be better if you word it all. Just do it and commit it, if you want.

**Comment by earthlng** [comment]
```
 ** 1492607 - make postMessage with targetOrigin "*" aware of OAs when restrict_opener_access = true (FF65+)
```
```js
/* 4002: enforce FPI restriction for window.opener (FF54+)
 * [NOTE] Setting this to false may reduce the breakage in 4001
 * [FF65+] assures the OAs are matching when the targetOrigin is "*" for postMessage() but it ignores
 *         the FPD in OA since the FPDs are possible to be different. (see [2] + [3])
 *         The 2nd pref enables you to only allow communication if 1p-domain also matches
 * [1] https://bugzilla.mozilla.org/1319773#c22
 * [2] https://bugzilla.mozilla.org/1492607
 * [3] https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage ***/
user_pref("privacy.firstparty.isolate.restrict_opener_access", true);
   // user_pref("privacy.firstparty.isolate.block_post_message", true); // hidden pref
```
or maybe a bit easier to understand:
```
[FF65+] blocks postMessage with targetOrigin "*" if originAttributes don't match. But
to reduce breakage it ignores the 1st-party domain (FPD) originAttribute. (see [2],[3])
The 2nd pref removes that limitation and will only allow communication if FPDs also match.
```

**Comment by earthlng** [comment]
oh and btw default value for `.restrict_opener_access` is and always has been `true`...
```js
user_pref("privacy.firstparty.isolate.restrict_opener_access", true); // default: true
```
:wink:

**Comment by earthlng** [comment]
agreed 1st version is terrible

> "make aware of OA" = "isolate" IMO

yeah we can go with that :+1:

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1630869

**Comment by Thorin-Oakenpants** [comment]
FPI is no longer actively worked on: it will be superseded by dFPI which is being tracked in #1051
