### ISSUE TITLE
reminder: network_state.connection_with_proxy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#990]
leftover from 78->79: new pref
* pref("privacy.partition.network_state.connection_with_proxy", false); investigate for `4003` [1642667](https://bugzilla.mozilla.org/1642667)

**Comment by Thorin-Oakenpants** [comment]
[1660524](https://bugzilla.mozilla.org/show_bug.cgi?id=1660524)

**Comment by earthlng** [comment]
wrong issue :)

**Comment by Thorin-Oakenpants** [comment]
awwwww... crap :)
